### PR TITLE
metamorphic: randomly use disk for tests

### PR DESCRIPTION
**Pull request by nicktrav**
Currently, by default, the metamorphic tests use a MemFS-backed DB by
default. The `-disk` flag can be used to override all tests to use a
disk-backed filesystem. The behavior is "all or nothing".

To better simulate use of Pebble with a real, disk-backed filesystem,
randomly generate test configurations that use disk.

Tweak the flags to allow specifying an override filesystem type. In the
case that "mem" or "disk" are specified, all metamorphic tests will use
that FS type, ignoring the randomly generated FS type. The default is to
use the randomly generated FS types. Disk-backed filesystems are used
25% of the time for the randomly generated configurations.

Related to cockroachdb/cockroach#69414.

### CODE REVIEW

**Review by nicktrav — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1250)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @jbowens and @sumeerbhola)

*[a discussion](https://reviewable.io/reviews/cockroachdb/pebble/1250#-MiXuNIs8LDkEatAe47V:-MiXuNIs8LDkEatAe47W:byecei5) (no related file):*
Possibly controversial, but I noticed that we seem to always use a MemFS in the nightly tests (presumably to bias towards running more tests, and generating more configurations).

Thought it might be useful to use disk-backed DBs at least some of the time.

---

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1250)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @jbowens)

*[a discussion](https://reviewable.io/reviews/cockroachdb/pebble/1250#-MiXuNIs8LDkEatAe47V:-Mj5XIsc4O503DTTmZO2:b-os10j3) (no related file):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

Possibly controversial, but I noticed that we seem to always use a MemFS in the nightly tests (presumably to bias towards running more tests, and generating more configurations).

Thought it might be useful to use disk-backed DBs at least some of the time.
</blockquote></details>

@jbowens do you have an opinion here? I think this is ok, but wondering if we expect this to have caught any past bugs, and whether we are just opening ourselves to some test flakes, and doing fewer runs with strict `MemFS`.

---

**Review by jbowens — APPROVED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1250)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @nicktrav and @sumeerbhola)

*[a discussion](https://reviewable.io/reviews/cockroachdb/pebble/1250#-MiXuNIs8LDkEatAe47V:-Mj5e0iE5ZexDMdXk2Ws:b-q2pa5h) (no related file):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

@jbowens do you have an opinion here? I think this is ok, but wondering if we expect this to have caught any past bugs, and whether we are just opening ourselves to some test flakes, and doing fewer runs with strict `MemFS`.
</blockquote></details>

I think this makes sense, although maybe we want an even lower probability for random disk runs.

I can think of a couple past issues this might've highlighted:
* The `MemFS` used to implement the more permissive Linux semantics allowing removal of open files. Metamorphic runs on disk on Windows would've caught those instances where we required file removal to succeed, even if the file was still open.
* This wasn't a bug, but `MemFS` and `vfs.Default` recently had different semantics for `Create`: one replacing the file and one truncating it. If there was a bug hiding due to this semantic mismatch, the disk runs would've highlighted it.

This will also help exercise some of the filesystem-only functionality, like readahead and preallocation. 

:LGTM:

---

**Review by nicktrav — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1250)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nicktrav)

*[a discussion](https://reviewable.io/reviews/cockroachdb/pebble/1250#-MiXuNIs8LDkEatAe47V:-Mj5gvmc-iO7q-OVIzyh:bwncc8m) (no related file):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

I think this makes sense, although maybe we want an even lower probability for random disk runs.

I can think of a couple past issues this might've highlighted:
* The `MemFS` used to implement the more permissive Linux semantics allowing removal of open files. Metamorphic runs on disk on Windows would've caught those instances where we required file removal to succeed, even if the file was still open.
* This wasn't a bug, but `MemFS` and `vfs.Default` recently had different semantics for `Create`: one replacing the file and one truncating it. If there was a bug hiding due to this semantic mismatch, the disk runs would've highlighted it.

This will also help exercise some of the filesystem-only functionality, like readahead and preallocation. 

:LGTM:
</blockquote></details>

Thank you both.

I'll lower the prob down to something like 10%.

The other thing to note is that we also tripled the runtime of the nightly `stressmeta` (via cockroachdb/cockroach#69720), so we are hopefully making up the lost time from the slower disk-based scenarios with a longer overall runtime.

---

**Pull request merged**
