### PR TITLE
tool: regenerate fixtures at more current formats

### PR DESCRIPTION
**Pull request by RaduBerinde**
These commits update the `tool` fixtures to use at least `FlushableIngest / Pebblev1`.

#### tool: regenerate out-of-order.sst

Regenerate this test fixture at TableFormatPebblev1.

#### tool: regenerate find-db

Regenerate this test store at FormatFlushableIngest.

#### tool: regenerate testdata/mixed

Regenerate `testdata/mixed` at the current newest version.

#### tool: update find-mixed sst

Copy the contents of `find-db/000005.sst` so we have a valid sst.

#### tool: update corrupted.sst

Regenerating at a newer format by copying `find-db/000005.sst` and
modifying a byte.

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3145)* status: 0 of 37 files reviewed, 1 unresolved discussion (waiting on @sumeerbhola)

___
*[`tool/testdata/find` line 29 at r5](https://reviewable.io/reviews/cockroachdb/pebble/3145#-NlPRbx874PeGchVgbzm:-NlPRbx874PeGchVgbzn:brzmeo4) ([raw file](https://github.com/cockroachdb/pebble/blob/bf645c9f32c4710e036cb0cdf950b362c966ef94/tool/testdata/find#L29)):*
> ```
> 000002.log
>     626262#11,SET test value formatter: 2
> 000005.sst [616161#10,SET-636363#14,MERGE]
> ```

I'm not sure why the previous one had so many more ssts..

**Review by jbowens — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, 21 of 21 files at r2, 14 of 14 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3145)* status: 33 of 37 files reviewed, 1 unresolved discussion (waiting on @RaduBerinde)

___
*[`tool/testdata/find` line 29 at r5](https://reviewable.io/reviews/cockroachdb/pebble/3145#-NlPRbx874PeGchVgbzm:-NlTo9_J5fBQ78Y4k08k:b-n2gnv5) ([raw file](https://github.com/cockroachdb/pebble/blob/bf645c9f32c4710e036cb0cdf950b362c966ef94/tool/testdata/find#L29)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I'm not sure why the previous one had so many more ssts..
</blockquote></details>

Yeah, I'm confused too. It looks like we're missing all the writes after the `compact("a", "z")`. Since we start at sequence number `10` now and we perform 10 write operations, we should see sequence numbers across the range [10,19].

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3145)* status: 33 of 37 files reviewed, 1 unresolved discussion (waiting on @jbowens)

___
*[`tool/testdata/find` line 29 at r5](https://reviewable.io/reviews/cockroachdb/pebble/3145#-NlPRbx874PeGchVgbzm:-NlUNU9oCBQDNjWOkQEc:b-m9jodn) ([raw file](https://github.com/cockroachdb/pebble/blob/bf645c9f32c4710e036cb0cdf950b362c966ef94/tool/testdata/find#L29)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

Yeah, I'm confused too. It looks like we're missing all the writes after the `compact("a", "z")`. Since we start at sequence number `10` now and we perform 10 write operations, we should see sequence numbers across the range [10,19].
</blockquote></details>

My mistake, the program hit an error - I wasn't setting the proper table format when creating an sst for ingestion. Fixed.

**Review by jbowens — APPROVED** [review]
:lgtm:

> Reviewed 15 of 22 files at r7, 14 of 17 files at r8, 2 of 5 files at r9, 5 of 5 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3145#-:-NlUSQgw03RTexcC_I8U:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @RaduBerinde)

___
*[`tool/testdata/find` line 29 at r5](https://reviewable.io/reviews/cockroachdb/pebble/3145#-NlPRbx874PeGchVgbzm:-NlUSSdC9KGEOsdc8tS6:b-q39fdb) ([raw file](https://github.com/cockroachdb/pebble/blob/bf645c9f32c4710e036cb0cdf950b362c966ef94/tool/testdata/find#L29)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

My mistake, the program hit an error - I wasn't setting the proper table format when creating an sst for ingestion. Fixed.
</blockquote></details>

Ah nice

**Pull request merged**
