### PR TITLE
vfs: extend disk-health checking to filesystem metadata operations

### LINKED ISSUE #1643: vfs: WithDiskHealthChecks doesn't time filesystem ops
The [`vfs.WithDiskHealthChecks`](https://github.com/cockroachdb/pebble/blob/31def7d7bdf69d56fe373ebc57d68f7838adaaaa/vfs/disk_health.go#L137) function wraps a vfs.FS and watches for disk stalls by timing all write operations. Individual `vfs.File`s are wrapped with a [`diskHealthCheckingFile`](https://github.com/cockroachdb/pebble/blob/31def7d7bdf69d56fe373ebc57d68f7838adaaaa/vfs/disk_health.go#L25). A close reading didn't reveal any gaps in coverage there.

However, the `vfs.FS`'s implementation does not time calls to [`Create`](https://github.com/cockroachdb/pebble/blob/31def7d7bdf69d56fe373ebc57d68f7838adaaaa/vfs/disk_health.go#L149), [`ReuseForWrite`](https://github.com/cockroachdb/pebble/blob/31def7d7bdf69d56fe373ebc57d68f7838adaaaa/vfs/disk_health.go#L165), or wholly unimplemented methods like `Link`, `Remove`, `RemoveAll`, `MkdirAll` or `Lock`. Since all of these filesystem operations may need to write data to disk, they should all be wrapped with timing.

Related to cockroachlabs/support#1520.

### PR DESCRIPTION
**Pull request by jbowens**
Previously, disk stalls while syncing a filesystem directory were undetected,
because the health-checking filesystem's OpenDir method did not wrap the
directory handle.

Additionally, disk stalls during all filesystem metadata operations (eg, file
creation, removal, rename, etc) were undetected. These operations are performed
directly on a vfs.FS (not a vfs.File), and require an adjusted implementation
to accommodate concurrent write-oriented operations.

This commit implements a scheme in which filesystem metadata operations lock a
vfs.FS-wide mutex to acquire a 'slot' into which they record their start time.
When an operation completes, the operation atomically zeroes its slot without
reacquiring the mutex. A long-running goroutine listens on a ticker,
periodically acquiring the vfs.FS mutex and scanning the slots for start times
older than a threshold.

The long-running goroutine is launched lazily by the first filesystem operation
to acquire the mutex. A new `io.Closer` return value of `WithDiskHealthChecks`
may be used to stop the long-running goroutine.

Fix #1643.

### CODE REVIEW

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> Reviewed 2 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1677)* status: 2 of 6 files reviewed, 4 unresolved discussions (waiting on @itsbilal and @jbowens)

___
*[`vfs/disk_health.go` line 23 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1677#-N15PUJg8-QLx8Lpdtdx:-N15PUJg8-QLx8Lpdtdy:b-dl6ybm) ([raw file](https://github.com/cockroachdb/pebble/blob/48d0870968bb8e20d79287aa106e5c76364302bd/vfs/disk_health.go#L23)):*
> ```Go
> 	// each additional slot will incur an additional allocation. We choose 8
> 	// here with the expectation that it is significantly more than required in
> 	// practice.
> ```

Is there empirical evidence from CockroachDB, running something realistic, that 8 is sufficient?
Given that these are per FS, we could easily afford more.
___
*[`vfs/disk_health.go` line 216 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1677#-N15Qu4V1ooS6Ll5kcS2:-N15Qu4V1ooS6Ll5kcS3:b-60b6yv) ([raw file](https://github.com/cockroachdb/pebble/blob/48d0870968bb8e20d79287aa106e5c76364302bd/vfs/disk_health.go#L216)):*
> ```Go
> 		// If there's no long-running goroutine to monitor this filesystem
> 		// operation, start one.
> 		if !d.mu.tickerRunning {
> ```

is there a reason the ticker is not started in `WithDiskHealthChecks`?
___
*[`vfs/disk_health.go` line 236 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1677#-N15Rmwr7ywm7LmMWB4E:-N15Rmwr7ywm7LmMWB4F:b-yayoae) ([raw file](https://github.com/cockroachdb/pebble/blob/48d0870968bb8e20d79287aa106e5c76364302bd/vfs/disk_health.go#L236)):*
> ```Go
> 				startNanos: startNanos,
> 			}
> 			d.mu.inflight = append(d.mu.inflight, s)
> ```

So inflight will grow to the "working set" size of slots, so we should be able to avoid allocations after that happens? I think this could use a comment. Its not obvious in the declaration struct why we have 2 arrays and one slice.
___
*[`vfs/disk_health.go` line 257 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1677#-N15SdjE8GWgK_W0W7dY:-N15SdjE8GWgK_W0W7dZ:bhl8616) ([raw file](https://github.com/cockroachdb/pebble/blob/48d0870968bb8e20d79287aa106e5c76364302bd/vfs/disk_health.go#L257)):*
> ```Go
> 		for {
> 			select {
> 			case <-ticker.C:
> ```

is there a risk of this mutex being held for too long and adding to the cost of FS operations? Especially if the inflight slice is very large?
There is a similar question related to scanning when trying to acquire a slot and affecting other operations trying to do the same.
What do you think of doing a microbenchmark with high concurrency and a high CPU machine to measure the overhead?
If it indicates a problem we could chunk up the contention footprint by having slot arrays of length N each with their own mutex.

**Review by nicktrav — COMMENTED** [review]
Flushing some comments.

edit: looks like I'm restating some of Sumeer's points too. Feel free to collapse my comments in favor of addressing his.

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1677#-:-N15VrQwD2zS7Co1HVqz:b-uj7wtb)* status: all files reviewed, 9 unresolved discussions (waiting on @itsbilal and @jbowens)

___
*[`vfs/disk_health.go` line 24 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1677#-N14z8S09Z2sQjEOEJ_t:-N14z8S09Z2sQjEOEJ_u:b-1xihbg) ([raw file](https://github.com/cockroachdb/pebble/blob/48d0870968bb8e20d79287aa106e5c76364302bd/vfs/disk_health.go#L24)):*
> ```Go
> 	// here with the expectation that it is significantly more than required in
> 	// practice.
> 	preallocatedSlotCount = 8
> ```

Wondering if it's worth looking at this in the context of a "typical" Cockroach cluster with one of the existing workloads and seeing what size this ends up being in practice? I suspect it wouldn't make much difference in the grand scheme of things (we'll allocate enough to cover the peak concurrent file usage), though if we always end up allocating, it may be worth tweaking the default.

Alternatively, given a `slot` is small (32B), could we just make this large to begin with?
___
*[`vfs/disk_health.go` line 166 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1677#-N15SbWG5sp8xzfkZblu:-N15SbWG5sp8xzfkZblv:bfb5mou) ([raw file](https://github.com/cockroachdb/pebble/blob/48d0870968bb8e20d79287aa106e5c76364302bd/vfs/disk_health.go#L166)):*
> ```Go
> // operations on the FS are wrapped with disk health detection checks. Disk
> // operations that are observed to take longer than diskSlowThreshold trigger an
> // onSlowDisk call.
> ```

nit: document that `diskSlowThreshold=0` disables the checks?
___
*[`vfs/disk_health.go` line 202 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1677#-N150Unp0hHItURGBlGI:-N150Unp0hHItURGBlGJ:bgc4m3w) ([raw file](https://github.com/cockroachdb/pebble/blob/48d0870968bb8e20d79287aa106e5c76364302bd/vfs/disk_health.go#L202)):*
> taking advantage of the fact that writes to a single vfs.File handle are not performed in parallel

Is this requirement documented somewhere higher up? If no, should it be? Seems like there's a risk that this breaks if / when we ever write to a file concurrently (that doesn't seem _too_ outlandish?).
___
*[`vfs/disk_health.go` line 211 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1677#-N15TsvrBIStasdrGv_G:-N15TsvrBIStasdrGv_H:b-83hioh) ([raw file](https://github.com/cockroachdb/pebble/blob/48d0870968bb8e20d79287aa106e5c76364302bd/vfs/disk_health.go#L211)):*
> ```Go
> 	var s *slot
> 	func() {
> 		d.mu.Lock()
> ```

Given this is on the hot path for a filesystem operation, are we concerned at all about the potential for the mutex becoming contended? There's also the potential allocation for the slice resize too.

 The alternative would be investing in some lock free datastructure / algo, would complicate things some more.
___
*[`vfs/disk_health.go` line 221 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1677#-N151MCKDm9vQDk9KJn5:-N151MCKDm9vQDk9KJn6:b17m9qd) ([raw file](https://github.com/cockroachdb/pebble/blob/48d0870968bb8e20d79287aa106e5c76364302bd/vfs/disk_health.go#L221)):*
> ```Go
> 
> 		startNanos := time.Now().UnixNano()
> 		for i := 0; i < len(d.mu.inflight); i++ {
> ```

Total bikeshed comment ...

Given we hold the mutex here already, wondering if there's some sort of "ring buffer" style approach to finding the next available slot (or increasing the size of the slice). Store a ref to the "first" (modulo) empty slot that can be used, then seek forward from that position to find the next one.

Thinking of a worst case where the prefix of the slice is full of "slow" in progress operations, and we have to iterate from the start each time to find the empty slot at the end of the slice.

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1677)* status: all files reviewed, 8 unresolved discussions (waiting on @itsbilal, @jbowens, @nicktrav, and @sumeerbhola)

___
*[`vfs/disk_health.go` line 23 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1677#-N15PUJg8-QLx8Lpdtdx:-N15X1Oe60zE1r3RecWA:b-29cnmk) ([raw file](https://github.com/cockroachdb/pebble/blob/48d0870968bb8e20d79287aa106e5c76364302bd/vfs/disk_health.go#L23)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Is there empirical evidence from CockroachDB, running something realistic, that 8 is sufficient?
Given that these are per FS, we could easily afford more.
</blockquote></details>

This is based on reasoning from Pebble's limited concurrency.

A single compaction or flush may have at most 1 filesystem operation in progress (although median is significantly smaller, since vast majority of time is spent in writing to _files_, not file metadata operations). The rotation of the WAL additionally may have at most 1 filesystem operation in progress.

The only other significant source of file metadata operations _on a VFS_ is ingested files. So we have approximately a max of `MaxCompactionCurrency + 1 /* flush */ + 1 /* WAL */ + ConcurrentWritingForIngest`.

In reality, each of the above described 'threads' spends very little of its time performing file metadata operations. All `Write`s and `Sync`s will still go through the individual `vfs.File` lock-free health-checking.
___
*[`vfs/disk_health.go` line 202 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1677#-N150Unp0hHItURGBlGI:-N15rp7KCWkjQmaFKBVm:b-u11uog) ([raw file](https://github.com/cockroachdb/pebble/blob/48d0870968bb8e20d79287aa106e5c76364302bd/vfs/disk_health.go#L202)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

> taking advantage of the fact that writes to a single vfs.File handle are not performed in parallel

Is this requirement documented somewhere higher up? If no, should it be? Seems like there's a risk that this breaks if / when we ever write to a file concurrently (that doesn't seem _too_ outlandish?).
</blockquote></details>

Added a comment `vfs.File`.
___
*[`vfs/disk_health.go` line 211 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1677#-N15TsvrBIStasdrGv_G:-N15tYLv31wIj7iTB33G:b9khcc3) ([raw file](https://github.com/cockroachdb/pebble/blob/48d0870968bb8e20d79287aa106e5c76364302bd/vfs/disk_health.go#L211)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

Given this is on the hot path for a filesystem operation, are we concerned at all about the potential for the mutex becoming contended? There's also the potential allocation for the slice resize too.

 The alternative would be investing in some lock free datastructure / algo, would complicate things some more.
</blockquote></details>

Left some comments addressing these elsewhere
___
*[`vfs/disk_health.go` line 216 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1677#-N15Qu4V1ooS6Ll5kcS2:-N15nZS32NqupraE9861:bjym0mo) ([raw file](https://github.com/cockroachdb/pebble/blob/48d0870968bb8e20d79287aa106e5c76364302bd/vfs/disk_health.go#L216)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

is there a reason the ticker is not started in `WithDiskHealthChecks`?
</blockquote></details>

Yeah, `(*pebble.Options).EnsureDefaults()` will call `WithDiskHealthChecks` if `FS` is not provided. Existing call sites will leak a goroutine. I want to preserve all the existing usages of `*Options`, including uses that pass one `*Options` to `Open` multiple times. This scheme allows the `FS` to be used, closed by `DB.Close`, used again and closed again.
___
*[`vfs/disk_health.go` line 257 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1677#-N15SdjE8GWgK_W0W7dY:-N15pAOY2GUqPKCR8v6T:b-gr9fnr) ([raw file](https://github.com/cockroachdb/pebble/blob/48d0870968bb8e20d79287aa106e5c76364302bd/vfs/disk_health.go#L257)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

is there a risk of this mutex being held for too long and adding to the cost of FS operations? Especially if the inflight slice is very large?
There is a similar question related to scanning when trying to acquire a slot and affecting other operations trying to do the same.
What do you think of doing a microbenchmark with high concurrency and a high CPU machine to measure the overhead?
If it indicates a problem we could chunk up the contention footprint by having slot arrays of length N each with their own mutex.
</blockquote></details>

I'll take a stab at a microbenchmark, but I don't think there's much risk given this is only for file creation, removal, etc. The volume is about the same as the pebble logger, which logs every file creation, removal, WAL rotation, etc, also acquires a mutex and likely performs more work (a buffer copy).

The potential for concurrency in these operations is very limited in Pebble and is mostly a function of the number of compactions. CockroachDB has few places where it performs file creation, links or removals _in parallel_ (eg, encryption-at-rest's operations are performed sequentially with respect to Pebble's existing concurrent threads).

With multiple stores (or a temporary store), each store is given its own VFS, with its own disk-health checking FS.

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1677)* status: 5 of 7 files reviewed, 8 unresolved discussions (waiting on @itsbilal, @jbowens, @nicktrav, and @sumeerbhola)

___
*[`vfs/disk_health.go` line 257 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1677#-N15SdjE8GWgK_W0W7dY:-N16ilp_7BUqbMiJBdFJ:b-3f67de) ([raw file](https://github.com/cockroachdb/pebble/blob/48d0870968bb8e20d79287aa106e5c76364302bd/vfs/disk_health.go#L257)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

I'll take a stab at a microbenchmark, but I don't think there's much risk given this is only for file creation, removal, etc. The volume is about the same as the pebble logger, which logs every file creation, removal, WAL rotation, etc, also acquires a mutex and likely performs more work (a buffer copy).

The potential for concurrency in these operations is very limited in Pebble and is mostly a function of the number of compactions. CockroachDB has few places where it performs file creation, links or removals _in parallel_ (eg, encryption-at-rest's operations are performed sequentially with respect to Pebble's existing concurrent threads).

With multiple stores (or a temporary store), each store is given its own VFS, with its own disk-health checking FS.
</blockquote></details>

Sounds good. Can you capture some of these responses in a file level comment.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 3 of 6 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1677#-:-N1G8tuLENNpI2Ibz_DC:bg7igkv)* status: all files reviewed (commit messages unreviewed), 10 unresolved discussions (waiting on @itsbilal, @jbowens, @nicktrav, and @sumeerbhola)

___
*[`vfs/disk_health.go` line 157 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1677#-N1G6slo0ztVAg1M6Ndk:-N1G6slo0ztVAg1M6Ndl:b-aw1kf0) ([raw file](https://github.com/cockroachdb/pebble/blob/e7415fee80cf94868062ce963ed5afe3b85d625f/vfs/disk_health.go#L157)):*
> ```Go
> // The number of slots on a diskHealthCheckingFS grows to a working set of the
> // maximum concurrent filesystem operations. This is expected to be very few
> // for a reasons:
> ```

for these reasons:
___
*[`vfs/disk_health_test.go` line 308 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1677#-N1G8hKK98sZFKlOlGuE:-N1G8hKK98sZFKlOlGuF:bdtvsrl) ([raw file](https://github.com/cockroachdb/pebble/blob/e7415fee80cf94868062ce963ed5afe3b85d625f/vfs/disk_health_test.go#L308)):*
> ```Go
> 		// Invoke the closer. This will cause the long-running goroutine to
> 		// exit, but the fs should still be usable and should still detect
> 		// subsequent stalls.
> ```

why is this being referred to as a "subsequent stall"? Hasn't the stall already happened by the time the fs.Create returned?

**Review by nicktrav — APPROVED** [review]
:lgtm: - thanks for improving the coverage here!

> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1677#-:-N1Jw-TH09ZahA7l7oSS:b-9eqsap)* status: all files reviewed, 7 unresolved discussions (waiting on @itsbilal, @jbowens, and @sumeerbhola)

**Comment by erikgrinaker** [comment]
Will we be backporting this?

**Pull request merged**
