### PR TITLE
sstable/metamorphic: add Writer parallelism to the metamorphic tests

### PR DESCRIPTION
**Pull request by bananabrick**
This pr adds some scaffolding to enable parallelism in the sstable writer,
and adds support to the metamorphic tests to generate options which enable
Writer parallelism.

### CODE REVIEW

**Review by bananabrick — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1544)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @itsbilal and @jbowens)

___
*[testdata/metrics, line 92 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1544#-Mx1LQ0C2-kSYeIKCBYh:-Mx1LQ0D33JQSkIVwbyC:bruatxv) ([raw file](https://github.com/cockroachdb/pebble/blob/26c244e2ad58e5809ab72e6bd81770c0eaf19e19/testdata/metrics#L92)):*
> ```
> disk-usage
> ----
> 3.6 K
> ```

The `Metrics.private.optionsFileSize` increases a little bit, which causes an increase here. It used to be `1026` in this test, and is now `1060`, and the difference is enough to change the numbers here.

The size is different because I added the parallelism field to the returned value of the`Options.String` function.

**Review by nicktrav — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1544)* status: all files reviewed, 3 unresolved discussions (waiting on @bananabrick, @itsbilal, and @jbowens)

___
*[sstable/writer.go, line 259 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1544#-MxG5u-R1oG8syoTd5M2:-MxG5u-R1oG8syoTd5M3:bnzykkj) ([raw file](https://github.com/cockroachdb/pebble/blob/ffd591459d595fe02105f070472c59498aa0b9bd/sstable/writer.go#L259)):*
> ```Go
> 	var writeQueueSize int
> 	if parallelismEnabled {
> 		writeQueueSize = runtime.GOMAXPROCS(0)
> ```

This seems like something that should be configurable too.
___
*[sstable/writer.go, line 359 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1544#-MxG82LY3Uyt0T9g1Srb:-MxG82LY3Uyt0T9g1Src:b-umq846) ([raw file](https://github.com/cockroachdb/pebble/blob/26c244e2ad58e5809ab72e6bd81770c0eaf19e19/sstable/writer.go#L359)):*
> ```Go
> func newIndexBlockBuf(useMutex bool) *indexBlockBuf {
> 	i := indexBlockBufPool.Get().(*indexBlockBuf)
> 	i.size.useMutex = useMutex
> ```

Can `i.size.useMutex` be set here without the function call?

**Review by bananabrick — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1544)* status: all files reviewed, 3 unresolved discussions (waiting on @itsbilal, @jbowens, and @nicktrav)

___
*[sstable/writer.go, line 259 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1544#-MxG5u-R1oG8syoTd5M2:-MxGrRSn23l2lOikb9IX:b-jo8i0n) ([raw file](https://github.com/cockroachdb/pebble/blob/ffd591459d595fe02105f070472c59498aa0b9bd/sstable/writer.go#L259)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

This seems like something that should be configurable too.
</blockquote></details>

Setting it to max for the purpose of using this in metamorphic tests. The only reason to not use `runtime.GOMAXPROCS(0)`, is the fear that faster compactions will do excessive IO. I'll probably set this to a const in a future pr.
___
*[sstable/writer.go, line 359 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1544#-MxG82LY3Uyt0T9g1Srb:-MxGrkYz1JcTD5C63HoS:blbxvss) ([raw file](https://github.com/cockroachdb/pebble/blob/26c244e2ad58e5809ab72e6bd81770c0eaf19e19/sstable/writer.go#L359)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

Can `i.size.useMutex` be set here without the function call?
</blockquote></details>

Not sure what this entails. Whether the mutex is used or not depends on a Writer level property(`parallelismEnabled`).

**Review by bananabrick — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1544)* status: all files reviewed, 3 unresolved discussions (waiting on @itsbilal, @jbowens, and @nicktrav)

___
*[sstable/writer.go, line 259 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1544#-MxG5u-R1oG8syoTd5M2:-MxH02UM9F1QlfTQwXoG:b3lmbn1) ([raw file](https://github.com/cockroachdb/pebble/blob/ffd591459d595fe02105f070472c59498aa0b9bd/sstable/writer.go#L259)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

Consider an operator that wants to specify how many goroutines are doing IO.

Alternatively, if you want to keep this as it is, we should at least document in the options that if parallelism is enabled then we spawn as many goroutines as cores.
</blockquote></details>

I'm not sure if we want to let an individual configure that, but I could add it.

My current plan was to experiment and find the number of goroutines which match the amount of IO done during compactions in the current master branch. Once we finish the IO utilization project, we can always spawn `runtime.GOMAXPROCS(0)` goroutines.

If an operator has a problem with the amount of goroutines spawned, then they can disable parallelism in the Writer, instead of fiddling with a setting like this.

I'm only setting this to `runtime.GOMAXPROCS(0)` for the metamorphic tests and only for now. I could set it to any number > 1 as long as it will let the metamorphic test suite test writer parallelism.
___
*[sstable/writer.go, line 254 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1544#-MxGxSf1DSucrYFq1zWa:-MxH16xGBykRHY8E-qnb:b-6b6s1j) ([raw file](https://github.com/cockroachdb/pebble/blob/26c244e2ad58e5809ab72e6bd81770c0eaf19e19/sstable/writer.go#L254)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

This is the function call I was asking about eliminating. Could you just do `c.sizeEstimate.useMutex = parallelismEnabled`? The function call didn't seem necessary.
</blockquote></details>

Yea, I could remove this. This pr is blocked by some other work I'm currently doing. I'll make the update when I get around to this pr.
___
*[sstable/writer.go, line 359 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1544#-MxG82LY3Uyt0T9g1Srb:-MxH0yQw8vVD8OQSjBNy:b-7xtfy4) ([raw file](https://github.com/cockroachdb/pebble/blob/26c244e2ad58e5809ab72e6bd81770c0eaf19e19/sstable/writer.go#L359)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

Woops, I commented on the wrong line.
</blockquote></details>

Yea,

**Review by itsbilal — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1544)* status: all files reviewed, 5 unresolved discussions (waiting on @bananabrick, @jbowens, and @nicktrav)

___
*[options.go, line 487 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1544#-MxfTLbG1-_xC_lcdnmW:-MxfTLbG1-_xC_lcdnmX:b-bj1a2i) ([raw file](https://github.com/cockroachdb/pebble/blob/26c244e2ad58e5809ab72e6bd81770c0eaf19e19/options.go#L487)):*
> ```Go
> 		// compress data blocks and write datablocks to disk in parallel with the Writer client
> 		// goroutine.
> 		EnableWriterParallelism bool
> ```

nit: This could just be `WriterParallelism` or `ParallelCompression`, the Enable is implied with the bool. Though I'd prefer if this were an `int` that specified the max number of threads we'd create per writer, defaulting to 1 (no parallelism).,
___
*[options.go, line 911 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1544#-MxfTRlk8hhVPplVlXb5:-MxfTRlk8hhVPplVlXb6:bo0jkph) ([raw file](https://github.com/cockroachdb/pebble/blob/26c244e2ad58e5809ab72e6bd81770c0eaf19e19/options.go#L911)):*
> ```Go
> 	fmt.Fprintf(&buf, "  wal_dir=%s\n", o.WALDir)
> 	fmt.Fprintf(&buf, "  wal_bytes_per_sync=%d\n", o.WALBytesPerSync)
> 	fmt.Fprintf(&buf, "  enable_writer_parallelism=%t\n", o.Experimental.EnableWriterParallelism)
> ```

Would need to be updated based on conversation below about this option
___
*[sstable/writer.go, line 259 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1544#-MxG5u-R1oG8syoTd5M2:-MxfTiH18R-uNRuQsjLF:b564hf4) ([raw file](https://github.com/cockroachdb/pebble/blob/ffd591459d595fe02105f070472c59498aa0b9bd/sstable/writer.go#L259)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

I'm not sure if we want to let an individual configure that, but I could add it.

My current plan was to experiment and find the number of goroutines which match the amount of IO done during compactions in the current master branch. Once we finish the IO utilization project, we can always spawn `runtime.GOMAXPROCS(0)` goroutines.

If an operator has a problem with the amount of goroutines spawned, then they can disable parallelism in the Writer, instead of fiddling with a setting like this.

I'm only setting this to `runtime.GOMAXPROCS(0)` for the metamorphic tests and only for now. I could set it to any number > 1 as long as it will let the metamorphic test suite test writer parallelism.
</blockquote></details>

I think it'd make sense to have `WriterParallelism` be an `int` option which defaults to 1 (no parallelism) and if increased beyond 1, is the max number of threads we'll spawn per writer, going up to `min(that option, GOMAXPROCS(0))`. It makes sense to give the spawner of pebble some control over the max value of this parallelism, just like we do with compaction concurrency and other concurrency gates. We will likely have multiple writers open at once, and it seems inefficient for us to go straight to letting them spawn as many threads as the number of cores. Cockroach could, for example, default to a value of `GOMAXPROCS(0)/4`, or a constant like 2-4.

**Comment by bananabrick** [comment]
The commits here are all dependent on #1565, and should only be reviewed once #1565 is merged, and the commits in this pr have been rebased on top of the commits in #1565.

**Comment by bananabrick** [comment]
The commits here are all dependent on #1581 , and should only be reviewed once #1581 is merged

**Pull request closed without merging**
