### PR TITLE
docs: add nightly benchmarks

### LINKED ISSUE #597: perf: continuous benchmarking before the performance improvement
We are very interested in the performance improvement of Pebble. But before do this we must measure performance and predict the effectiveness.

Recently, I introduced [continue benchmarking](http://marsettler.com/marsettler/benchmark/) with [Github Actions](https://github.com/hueypark/marsettler/blob/master/.github/workflows/benchmark.yml) and [gobenchdata](https://github.com/bobheadxi/gobenchdata) in my toy project. How about applying this continuous benchmark to Pebble?

### PR DESCRIPTION
**Pull request by petermattis**
The benchmarks are powered by nightly runs of `pebble bench ycsb` on
Cockroach Labs' TeamCity server. The raw data from those runs is stored
on the `benchmark-data` branch and "cooked" to create `docs/js/data.js`.

Fixes #597

### CODE REVIEW

**Comment by petermattis** [comment]
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/797)

**Comment by petermattis** [comment]
I haven't completely hooked all of the TeamCity automation, but I think everything is good on the Pebble repo side.

**Comment by petermattis** [comment]
I've decided to change how this works so that the github-pages site is served out of the `docs` directory on the master branch rather than from the `gh-pages` branch. There is enough javascript code in the benchmarks page that it deserves to be code reviewed.

**Comment by petermattis** [comment]
TFTR!

**Comment by hueypark** [comment]
Wonderful!

**Pull request merged**
