### PR TITLE
internal/rangekey: optimize Coalesce 

### LINKED ISSUE #2175: sstable: remove range key coalescing from the sstable Writer
The sstable writer is a low level abstraction used to write sstables to disk and it shouldn't have to worry about coalescing range keys. Instead, we could perform the coalescing above the Writer.

Within the Writer, we could add an invariant check to ensure that the spans which have been added to the Writer have already been coalesced.

### PR DESCRIPTION
**Pull request by jbowens**
Optimize rangekey.Coalesce by sorting range keys altogether once, and then
deduplicating in a second pass.

```
name                                   old time/op  new time/op  delta
Transform/shadowing=false/keys=1-10    46.5ns ± 0%  35.7ns ± 0%  -23.19%  (p=0.016 n=5+4)
Transform/shadowing=false/keys=2-10     116ns ± 0%    96ns ± 0%  -17.50%  (p=0.008 n=5+5)
Transform/shadowing=false/keys=4-10     436ns ± 0%   256ns ± 0%  -41.30%  (p=0.008 n=5+5)
Transform/shadowing=false/keys=8-10    1.77µs ± 0%  0.95µs ± 0%  -46.67%  (p=0.008 n=5+5)
Transform/shadowing=false/keys=16-10   8.85µs ± 0%  3.24µs ± 0%  -63.42%  (p=0.008 n=5+5)
Transform/shadowing=false/keys=32-10   48.7µs ± 0%   7.2µs ± 0%  -85.19%  (p=0.008 n=5+5)
Transform/shadowing=false/keys=64-10    170µs ± 0%    19µs ± 0%  -88.85%  (p=0.008 n=5+5)
Transform/shadowing=false/keys=128-10   432µs ± 0%    47µs ± 0%  -89.05%  (p=0.008 n=5+5)
Transform/shadowing=true/keys=1-10     46.6ns ± 0%  36.0ns ± 2%  -22.83%  (p=0.008 n=5+5)
Transform/shadowing=true/keys=2-10     95.6ns ± 1%  85.3ns ± 0%  -10.79%  (p=0.008 n=5+5)
Transform/shadowing=true/keys=4-10      227ns ± 0%   201ns ± 0%  -11.68%  (p=0.008 n=5+5)
Transform/shadowing=true/keys=8-10      774ns ± 0%   830ns ± 0%   +7.34%  (p=0.008 n=5+5)
Transform/shadowing=true/keys=16-10    3.29µs ± 0%  2.79µs ± 0%  -15.23%  (p=0.008 n=5+5)
Transform/shadowing=true/keys=32-10    16.3µs ± 0%   6.7µs ± 0%  -58.72%  (p=0.008 n=5+5)
Transform/shadowing=true/keys=64-10    83.5µs ± 0%  18.9µs ± 0%  -77.42%  (p=0.008 n=5+5)
Transform/shadowing=true/keys=128-10    243µs ± 0%    48µs ± 0%  -80.14%  (p=0.008 n=5+5)
```

Close #2175.

### CODE REVIEW

**Review by jbowens — COMMENTED** [review]
@bananabrick — you might want to look at the first commit which addresses #2175

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2197#-:-NLSE06f8QyAskffwpsc:benw6gb)* status: 0 of 9 files reviewed, all discussions resolved (waiting on @bananabrick and @sumeerbhola)

**Review by bananabrick — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, 1 of 6 files at r3, 1 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2197)* status: 3 of 9 files reviewed, 6 unresolved discussions (waiting on @jbowens and @sumeerbhola)

___
*[`internal/keyspan/span.go` line 83 at r4](https://reviewable.io/reviews/cockroachdb/pebble/2197#-NLgXAYv1S2tCi8VcpoM:-NLgXAYv1S2tCi8VcpoN:b-k7guma) ([raw file](https://github.com/cockroachdb/pebble/blob/caeb1a90429744548e08c4f2eb7b5660953ea9b1/internal/keyspan/span.go#L83)):*
> ```Go
> // visible, because non-visible batch span keys are filtered when they're
> // fragmented.
> func (k Key) VisibleAt(snapshot uint64) bool {
> ```

Is it possible to make use of`base.Visible` here? Although, I see that it has a few more parameters.
___
*[`internal/rangekey/coalesce.go` line 297 at r4](https://reviewable.io/reviews/cockroachdb/pebble/2197#-NM253SU55os_r7N7hqE:-NM253SU55os_r7N7hqF:b-719dgs) ([raw file](https://github.com/cockroachdb/pebble/blob/a80169845786dc35b791d5071a165977c45b80d7/internal/rangekey/coalesce.go#L297)):*
> ```Go
> 			}
> 			keysBySuffix.keys = append(keysBySuffix.keys, k)
> 			sort.Sort(keysBySuffix)
> ```

Is removing this the main reason this is faster now?
___
*[`sstable/writer.go` line 1052 at r4](https://reviewable.io/reviews/cockroachdb/pebble/2197#-NLgZILd6lCTFgPpnJpA:-NLgZILd6lCTFgPpnJpB:b-40rk4o) ([raw file](https://github.com/cockroachdb/pebble/blob/caeb1a90429744548e08c4f2eb7b5660953ea9b1/sstable/writer.go#L1052)):*
> ```Go
> //
> // Keys must be added to the table in increasing order of start key. Spans are
> // not required to be fragmented. The same suffix may not be set or unset twice.
> ```

It might be helpful to add a "The same suffix may not be set or unset twice because...".
___
*[`sstable/writer.go` line 1130 at r4](https://reviewable.io/reviews/cockroachdb/pebble/2197#-NM1n36_1f9O520a0hWq:-NM1n36_1f9O520a0hWr:b-qbjnb1) ([raw file](https://github.com/cockroachdb/pebble/blob/caeb1a90429744548e08c4f2eb7b5660953ea9b1/sstable/writer.go#L1130)):*
> ```Go
> }
> 
> func (w *Writer) encodeRangeKeySpan(span keyspan.Span) {
> ```

Should we keep the comment which explains why it's okay to mutate the span, and I'm guessing why it's also okay to store the span in the Writer in the `w.rangeKeySpan = span` line?
___
*[`sstable/writer.go` line 1133 at r4](https://reviewable.io/reviews/cockroachdb/pebble/2197#-NLgZr3FE9MLG5bZgGYF:-NLgZr3FE9MLG5bZgGYG:b3vdyc3) ([raw file](https://github.com/cockroachdb/pebble/blob/caeb1a90429744548e08c4f2eb7b5660953ea9b1/sstable/writer.go#L1133)):*
> ```Go
> 	// This method is the emit function of the Fragmenter.
> 	//
> 	// NB: The span should only contain range keys and be internally consistent
> ```

How difficult would it be to do an invariants.Enabled check here to confirm this invariant?
___
*[`internal/rangekey/coalesce_test.go` line 83 at r4](https://reviewable.io/reviews/cockroachdb/pebble/2197#-NM1yI9m9Bl_o_C8SnKs:-NM1yI9m9Bl_o_C8SnKt:b-uhtwl0) ([raw file](https://github.com/cockroachdb/pebble/blob/caeb1a90429744548e08c4f2eb7b5660953ea9b1/internal/rangekey/coalesce_test.go#L83)):*
> ```Go
> 					return err
> 				}
> 				// Update the span with the (potentially reduced) keys slice.  coalesce left
> ```

nit: errant space before "coalesce". It's also the same in the `Coalesce` function.

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2197)* status: 3 of 9 files reviewed, 5 unresolved discussions (waiting on @bananabrick and @sumeerbhola)

___
*[`internal/keyspan/span.go` line 83 at r4](https://reviewable.io/reviews/cockroachdb/pebble/2197#-NLgXAYv1S2tCi8VcpoM:-NM9lKfp-fySHgOZ9eJg:b72nz5q) ([raw file](https://github.com/cockroachdb/pebble/blob/caeb1a90429744548e08c4f2eb7b5660953ea9b1/internal/keyspan/span.go#L83)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

Is it possible to make use of`base.Visible` here? Although, I see that it has a few more parameters.
</blockquote></details>

It's not a fit here here because the visibility rules are slightly different for spans which have their non-visible batch keys filtered upfront. 
___
*[`internal/rangekey/coalesce.go` line 297 at r4](https://reviewable.io/reviews/cockroachdb/pebble/2197#-NM253SU55os_r7N7hqE:-NM9kwI69nXnZTeoRBoC:bj2lj9q) ([raw file](https://github.com/cockroachdb/pebble/blob/a80169845786dc35b791d5071a165977c45b80d7/internal/rangekey/coalesce.go#L297)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

Is removing this the main reason this is faster now?
</blockquote></details>

yes, plus removing the call to `keysBySuffix.get` for every key.
___
*[`sstable/writer.go` line 1052 at r4](https://reviewable.io/reviews/cockroachdb/pebble/2197#-NLgZILd6lCTFgPpnJpA:-NM9j0A7AvYEuaQiE_r6:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/caeb1a90429744548e08c4f2eb7b5660953ea9b1/sstable/writer.go#L1052)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

It might be helpful to add a "The same suffix may not be set or unset twice because...".
</blockquote></details>

Done.
___
*[`sstable/writer.go` line 1130 at r4](https://reviewable.io/reviews/cockroachdb/pebble/2197#-NM1n36_1f9O520a0hWq:-NM9jPwj6jUVGwduKY1v:b-6xkbdl) ([raw file](https://github.com/cockroachdb/pebble/blob/caeb1a90429744548e08c4f2eb7b5660953ea9b1/sstable/writer.go#L1130)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

Should we keep the comment which explains why it's okay to mutate the span, and I'm guessing why it's also okay to store the span in the Writer in the `w.rangeKeySpan = span` line?
</blockquote></details>

We actually don't rely on the stability of `w.rangeKeySpan`. We only set `w.rangeKeySpan` to prevent an allocation when we pass a pointer into `w.rangeKEyEncoder.Encode`. Added a comment explaining this.
___
*[`sstable/writer.go` line 1133 at r4](https://reviewable.io/reviews/cockroachdb/pebble/2197#-NLgZr3FE9MLG5bZgGYF:-NM9k2Pd61pPLIuKNfzZ:bk74xdi) ([raw file](https://github.com/cockroachdb/pebble/blob/caeb1a90429744548e08c4f2eb7b5660953ea9b1/sstable/writer.go#L1133)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

How difficult would it be to do an invariants.Enabled check here to confirm this invariant?
</blockquote></details>

Not easy. This is also only invoked when the _client_ is building an sstable for ingestion, so an `invariants.Enabled` assertion check wouldn't detect much (`invariants.Enabled` is not set, for eg, when running tests in the Cockroach repo)

**Review by bananabrick — COMMENTED** [review]
Assuming the invariants written down in the `coalesce` function were correct, I believe the function is behaving like its previous version. So, this :lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2197#-:-NMLK0YqDoHVZWoHH2bW:b-5ecqod)* status: 1 of 9 files reviewed, 1 unresolved discussion (waiting on @jbowens and @sumeerbhola)

___
*[`internal/rangekey/coalesce.go` line 290 at r6](https://reviewable.io/reviews/cockroachdb/pebble/2197#-NMLDhbo-ofc0I3RfWnb:-NMLDhbo-ofc0I3RfWnc:biope9s) ([raw file](https://github.com/cockroachdb/pebble/blob/65b82b570eb1002afc3e4bf1b2814294ea156d4d/internal/rangekey/coalesce.go#L290)):*
> ```Go
> 	deleteIdx := -1
> 	for i := range keys {
> 		if invariants.Enabled && i > 0 && keys[i].Trailer > keys[i-1].Trailer {
> ```

Is `keys[i].Trailer == keys[i-1].Trailer` okay?

**Review by jbowens — COMMENTED** [review]
TFTR!

Mind hitting the approval button?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2197#-:-NM_67xwErQNBZNt8ePB:bj1uvkw)* status: 1 of 9 files reviewed, 1 unresolved discussion (waiting on @bananabrick and @sumeerbhola)

___
*[`internal/rangekey/coalesce.go` line 290 at r6](https://reviewable.io/reviews/cockroachdb/pebble/2197#-NMLDhbo-ofc0I3RfWnb:-NM_6-5q7hcDFDoK3gXq:b49kyyu) ([raw file](https://github.com/cockroachdb/pebble/blob/65b82b570eb1002afc3e4bf1b2814294ea156d4d/internal/rangekey/coalesce.go#L290)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

Is `keys[i].Trailer == keys[i-1].Trailer` okay?
</blockquote></details>

yeah, it's ok so long as the keys have different suffixes.

**Review by bananabrick — APPROVED** [review]
> Reviewed 2 of 4 files at r1, 6 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2197)* status: 4 of 9 files reviewed, 1 unresolved discussion (waiting on @sumeerbhola)

**Pull request merged**
