### PR TITLE
[WIP] *: Wire up compaction picking with L0Sublevels, enable flush splits

### PR DESCRIPTION
**Pull request by itsbilal**
This change connects the compaction picking methods in L0SubLevels
with the existing compaction picker, replacing existing logic for
picking L0 compactions.

It also enables flush splits, and adds a pebble Option (FlushSplitBytes)
to set the threshold for number of bytes that would need to be observed
in L0 files since the last split key before an interval boundary is
added as a flush split key.

Very much a work-in-progress; first commit is #615.

### CODE REVIEW

**Comment by petermattis** [comment]
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/642)

**Comment by itsbilal** [comment]
@sumeerbhola I've answered the questions you asked in #670. This PR was mostly a reference point for any reviewers of past PRs to be able to tie together pieces, but I didn't expect it to be reviewed directly. As I mentioned in #670, my experimentation so far shows that the prioritization done here is less impactful than other changes like flush splits and preIngestDelay changes.

The `else` code is dead for now, but I expect to either make it enable-able with a knob, or delete it very soon. Also discussing this in #670.

**Comment by petermattis** [comment]
@itsbilal This can be closed, right?

**Comment by itsbilal** [comment]
Yes, this can be closed. Thanks for reminding!

**Pull request closed without merging**
