### PR TITLE
wal: add facilities to list WAL files across Dirs

### PR DESCRIPTION
**Pull request by jbowens**
Add some internal (still unexported) facilities for listing the WAL files across several directories, ordering the consitutent files by log number and index.

### CODE REVIEW

**Review by jbowens — COMMENTED** [review]
@sumeerbhola — I decided to pull out some of these small interface changes and the listing of log files. I'll put up the `Reader` implementation in its own PR.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3261#-:-NpacnYy2rvjCQbf3MSY:bnxddl9)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @sumeerbhola)

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3261#-:-NpfV7Jx5sQojhb3fWkz:bg7igkv)* status: all files reviewed, 2 unresolved discussions (waiting on @jbowens)

___
*[`wal/wal.go` line 60 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3261#-NpfRgEgAsCnTPIjwzB1:-NpfRgEgAsCnTPIjwzB2:bdxh6mi) ([raw file](https://github.com/cockroachdb/pebble/blob/b0c20123925a4b26089a6d3827a8885718b115eb/wal/wal.go#L60)):*
> ```Go
> 		return base.MakeFilename(base.FileTypeLog, base.DiskFileNum(wn))
> 	}
> 	return fmt.Sprintf("%s-%03d.log", base.DiskFileNum(wn).String(), index)
> ```

nit: should this be `fmt.Sprintf("%s-%s.log", base.DiskFileNum(wn), index)`?
___
*[`wal/wal.go` line 75 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3261#-NpfS1Fn7aC-GLLMreJZ:-NpfS1Fn7aC-GLLMreJ_:b-mc5vs2) ([raw file](https://github.com/cockroachdb/pebble/blob/b0c20123925a4b26089a6d3827a8885718b115eb/wal/wal.go#L75)):*
> ```Go
> 		dfn, ok := base.ParseDiskFileNum(name[:i])
> 		if !ok {
> 			return 0, 0, false
> ```

Not being a log file and not parsing despite a ".log" suffix deserve different return values. Latter should be an error.

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3261)* status: 2 of 7 files reviewed, 1 unresolved discussion (waiting on @sumeerbhola)

___
*[`wal/wal.go` line 60 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3261#-NpfRgEgAsCnTPIjwzB1:-NptvGmfDqiU5GtPpvg9:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/b0c20123925a4b26089a6d3827a8885718b115eb/wal/wal.go#L60)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nit: should this be `fmt.Sprintf("%s-%s.log", base.DiskFileNum(wn), index)`?
</blockquote></details>

Done.
___
*[`wal/wal.go` line 75 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3261#-NpfS1Fn7aC-GLLMreJZ:-NptvYia9yyvs2EJBYOn:b-9ffk08) ([raw file](https://github.com/cockroachdb/pebble/blob/b0c20123925a4b26089a6d3827a8885718b115eb/wal/wal.go#L75)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Not being a log file and not parsing despite a ".log" suffix deserve different return values. Latter should be an error.
</blockquote></details>

Hrm, this would be a change in behavior that has a slight chance of causing an issue. I wouldn't be surprised if some customer out there has a `.log` file that's actually diagnostic logs, either because they pointed their logging into the data directory or`cp`'d a log file there when zipping up some diagnostics or the like. thoughts?

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 3 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3261#-:-NpvA1_q9lRfqYikWOcJ:bg7igkv)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @jbowens)

___
*[`wal/wal.go` line 75 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3261#-NpfS1Fn7aC-GLLMreJZ:-Npv9aPVAmSOE7RQa9FE:bd8cnmo) ([raw file](https://github.com/cockroachdb/pebble/blob/b0c20123925a4b26089a6d3827a8885718b115eb/wal/wal.go#L75)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

Hrm, this would be a change in behavior that has a slight chance of causing an issue. I wouldn't be surprised if some customer out there has a `.log` file that's actually diagnostic logs, either because they pointed their logging into the data directory or`cp`'d a log file there when zipping up some diagnostics or the like. thoughts?
</blockquote></details>

Good point. Can you add a code comment?
___
*[`wal/wal.go` line 222 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3261#-NpvA-U-3lfx-nSumKGD:-NpvA-U-3lfx-nSumKGE:b-3ge38x) ([raw file](https://github.com/cockroachdb/pebble/blob/b0c20123925a4b26089a6d3827a8885718b115eb/wal/wal.go#L222)):*
> ```Go
> 	// indicating the position of a record. Logical is deterministic with
> 	// respect to the contents of the records.
> 	Logical int
> ```

no need for `Logical`?

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3261)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @sumeerbhola)

___
*[`wal/wal.go` line 75 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3261#-NpfS1Fn7aC-GLLMreJZ:-NpvKIK2Dit44k3yEeMc:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/b0c20123925a4b26089a6d3827a8885718b115eb/wal/wal.go#L75)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Good point. Can you add a code comment?
</blockquote></details>

Done.
___
*[`wal/wal.go` line 222 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3261#-NpvA-U-3lfx-nSumKGD:-NpvKJNi4bbu0Fj2F0Sa:b-726qex) ([raw file](https://github.com/cockroachdb/pebble/blob/b0c20123925a4b26089a6d3827a8885718b115eb/wal/wal.go#L222)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

no need for `Logical`?
</blockquote></details>

I realized in the standalone case it's a bit cumbersome to compute a logical offset that's deterministic with respect to the record data. We don't actually know the the record length and just pass the `io.Reader` off to the client. We could easily have a logical offset that's not deterministic with respect to the record contents, but I wasn't sure where it would be used.

I'll merge and we can follow up with a logical offset where/when we want it.

**Pull request merged**
