### PR TITLE
db: improve metrics formatting

### LINKED ISSUE #1473: db: reformat `Metrics.String()` output
The `Metrics.String()` output is often used in debugging storage issues. As we've accumulated more statistics that are _not_ per-level, each has been appended as an independent line with descriptive annotations like `(size == estimated-debt, score = in-progress-bytes, in = num-in-progress)`.

With a little thought and elbow grease, I think these could be restructured to be a little more legible and avoid the excess vertical height.

```
//   __level_____count____size___score______in__ingest(sz_cnt)____move(sz_cnt)___write(sz_cnt)____read___w-amp
//       WAL         1    27 B       -    48 B       -       -       -       -   108 B       -       -     2.2
//         0         2   1.6 K    0.50    81 B   825 B       1     0 B       0   2.4 K       3     0 B    30.6
//         1         0     0 B    0.00     0 B     0 B       0     0 B       0     0 B       0     0 B     0.0
//         2         0     0 B    0.00     0 B     0 B       0     0 B       0     0 B       0     0 B     0.0
//         3         0     0 B    0.00     0 B     0 B       0     0 B       0     0 B       0     0 B     0.0
//         4         0     0 B    0.00     0 B     0 B       0     0 B       0     0 B       0     0 B     0.0
//         5         0     0 B    0.00     0 B     0 B       0     0 B       0     0 B       0     0 B     0.0
//         6         1   825 B    0.00   1.6 K     0 B       0     0 B       0   825 B       1   1.6 K     0.5
//     total         3   2.4 K       -   933 B   825 B       1     0 B       0   4.1 K       4   1.6 K     4.5
//     flush         3
//   compact         1   1.6 K     0 B       1          (size == estimated-debt, score = in-progress-bytes, in = num-in-progress)
//     ctype         0       0       0       0       0  (default, delete, elision, move, read)
//    memtbl         1   4.0 M
//   zmemtbl         0     0 B
//      ztbl         0     0 B
//    bcache         4   752 B    7.7%  (score == hit-rate)
//    tcache         0     0 B    0.0%  (score == hit-rate)
//    titers         0
//    filter         -       -    0.0%  (score == utility)
```

### PR DESCRIPTION
**Pull request by RaduBerinde**
This change improves the formatting of the Pebble metrics:
 - we no longer try to artificially fit non-tabular information in a single table
 - all byte figures end in B/KB/MB/etc
 - counts and corresponding sizes are grouped together
 - flushable ingests information moved under ingestions

These metrics are periodically logged and can be obtained through the db console as well.

Fixes #1473.

Release note: Pebble metrics formatting improvements; tools that parse
these logs might need updating.

Open to any suggestions for further improvement. Example of the new format:
```
      |                     |       |       |   ingested   |     moved    |    written   |       |    amp
level | tables  size val-bl | score |   in  | tables  size | tables  size | tables  size |  read |   r   w
------+---------------------+-------+-------+--------------+--------------+--------------+-------+---------
    0 |   101   102B     0B | 103.0 |  104B |   112   104B |   113   106B |   221   217B |  107B |   1  2.1
    1 |   201   202B     0B | 203.0 |  204B |   212   204B |   213   206B |   421   417B |  207B |   2  2.0
    2 |   301   302B     0B | 303.0 |  304B |   312   304B |   313   306B |   621   617B |  307B |   3  2.0
    3 |   401   402B     0B | 403.0 |  404B |   412   404B |   413   406B |   821   817B |  407B |   4  2.0
    4 |   501   502B     0B | 503.0 |  504B |   512   504B |   513   506B |  1.0K  1017B |  507B |   5  2.0
    5 |   601   602B     0B | 603.0 |  604B |   612   604B |   613   606B |  1.2K  1.2KB |  607B |   6  2.0
    6 |   701   702B     0B |     - |  704B |   712   704B |   713   706B |  1.4K  1.4KB |  707B |   7  2.0
total |  2.8K  2.7KB     0B |     - | 2.8KB |  2.9K  2.8KB |  2.9K  2.8KB |  5.7K  8.4KB | 2.8KB |  28  3.0
-----------------------------------------------------------------------------------------------------------
WAL: 22 files (24B)  in: 25B  written: 26B (4% overhead)
Flushes: 8
Compactions: 5  estimated debt: 6B  in progress: 2 (7B)
             default: 27  delete: 28  elision: 29  move: 30  read: 31  rewrite: 32  multi-level: 33
MemTables: 12 (11B)  zombie: 14 (13B)
Zombie tables: 16 (15B)
Block cache: 2 entries (1B)  hit rate: 42.9%
Table cache: 18 entries (17B)  hit rate: 48.7%
Snapshots: 4  earliest seq num: 1024
Table iters: 21
Filter utility: 47.4%
Ingestions: 27  as flushable: 36 (34B in 35 tables)
```

### CODE REVIEW

**Comment by RaduBerinde** [comment]
I tried to switch over other uses of humanize to the new formats but it is a lot of work (especially in the compaction tool which parses the logs). I will leave all that for another PR.

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
Thanks for doing this!
Minor question about making the format more verbose.

> I tried to switch over other uses of humanize to the new formats but it is a lot of work (especially in the compaction tool which parses the logs)

I suppose you are referring to the parsing of this output that happens in https://github.com/cockroachdb/pebble/blob/9976c78b28bc3e563d06ce425c43985e14d2a062/tool/logs/compaction.go#L113-L119

Does that still work?

> Reviewed 1 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2739#-:-N_Jl64Z12aynTleCoYg:b-hu4ugf)* status: 1 of 7 files reviewed, 2 unresolved discussions (waiting on @jbowens and @RaduBerinde)

___
*[`testdata/event_listener` line 272 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2739#-N_JjYW27-p19ripRL7v:-N_JjYW27-p19ripRL7w:b-752938) ([raw file](https://github.com/cockroachdb/pebble/blob/f233ee7d68e200564d244be671a0209162180525/testdata/event_listener#L272)):*
> ```
> ----
>   level |            tables |   score |      in |          ingest |            move |           write |    read |   r-amp   w-amp
> --------+-------------------+---------+---------+-----------------+-----------------+-----------------+---------+----------------
> ```

I wonder if there is a way to succinctly say that for all pairs of columns it is a (count, size) pair.
Maybe in a row after the total?
___
*[`testdata/event_listener` line 282 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2739#-N_JkIOC2VAPaN4i8rbW:-N_JkIOC2VAPaN4i8rbX:b6skk23) ([raw file](https://github.com/cockroachdb/pebble/blob/f233ee7d68e200564d244be671a0209162180525/testdata/event_listener#L282)):*
> ```
>   total |         3   2.0KB |       - |    825B |       1    717B |       0      0B |       4   3.4KB |   1.3KB |       3     4.2
> ---------------------------------------------------------------------------------------------------------------------------------
> WAL: 1 (27B)  in: 48B  written: 108B (125% overhead)
> ```

given this PRs goal of improving the readability, I wonder whether some of the non-byte values could use "units". I realize this is quite subjective.
I generally find it easier to go from "WAL: 1" to "there is 1 WAL file", than to go from "Block cache: 8" to "there are 8 entries in the block cache".

Thoughts?

**Review by RaduBerinde — COMMENTED** [review]
I should say, it picks off the value before the last 8 characters.

**Comment by RaduBerinde** [comment]
I made another update. I used two lines for the heading and improved the column names, and I added the value blocks under the `tables` group (we now always show it).
```
        |                         |         |         |     ingested    |      moved      |     written     |         |       amp
  level |  tables    size  val-bl |   score |      in |  tables    size |  tables    size |  tables    size |    read |   r-amp   w-amp
--------+-------------------------+---------+---------+-----------------+-----------------+-----------------+---------+----------------
      0 |      0B      0B      0B |    0.00 |     56B |       0      0B |       0      0B |       2   1.2KB |      0B |       0    22.6
      1 |      0B      0B      0B |    0.00 |      0B |       0      0B |       0      0B |       0      0B |      0B |       0     0.0
      2 |      0B      0B      0B |    0.00 |      0B |       0      0B |       0      0B |       0      0B |      0B |       0     0.0
      3 |      0B      0B      0B |    0.00 |      0B |       0      0B |       0      0B |       0      0B |      0B |       0     0.0
      4 |      0B      0B      0B |    0.00 |      0B |       0      0B |       0      0B |       0      0B |      0B |       0     0.0
      5 |      0B      0B      0B |    0.00 |      0B |       0      0B |       0      0B |       0      0B |      0B |       0     0.0
      6 |      1B    639B      0B |       - |   1.2KB |       0      0B |       0      0B |       1    639B |   1.2KB |       1     0.5
  total |      1B    639B      0B |       - |     84B |       0      0B |       0      0B |       3   1.9KB |   1.2KB |       1    23.7
---------------------------------------------------------------------------------------------------------------------------------------
WAL: 1 files (28B)  in: 34B  written: 84B (147% overhead)
Flushes: 2
Compactions: 1  estimated debt: 0B  in progress: 0 (0B)
             default: 1  delete: 0  elision: 0  move: 0  read: 0  rewrite: 0  multi-level: 0
MemTables: 1 (256KB)  zombie: 2 (512KB)
Zombie tables: 2 (1.2KB)
Block cache: 8 entries (1.1KB)  hit rate: 42.9%
Table cache: 2 entries (1.3KB)  hit rate: 66.7%
Snapshots: 0  earliest seq num: 0
Table iters: 2
Filter utility: 0.0%
Ingestions: 0  as flushable: 0 (0B in 0 tables)
```

**Comment by sumeerbhola** [comment]
This looks great! My only remaining question is whether we can squeeze this horizontally a bit without affecting readability, by reducing the whitespace -- discounting the increase in columns due to val-bl, the new format is using 126 characters per row (for the table) while the previous one was using 112. No big deal if we can't.

**Comment by RaduBerinde** [comment]
I managed to get it down to 116 chars, including the val blocks.
```
      |                      |       |        |    ingested   |     moved     |    written    |        |     amp
level | tables   size val-bl | score |     in | tables   size | tables   size | tables   size |   read | r-amp w-amp
------+----------------------+-------+--------+---------------+---------------+---------------+--------+------------
    0 |    101   102B     0B | 103.0 |   104B |    112   104B |    113   106B |    221   217B |   107B |     1   2.1
    1 |    201   202B     0B | 203.0 |   204B |    212   204B |    213   206B |    421   417B |   207B |     2   2.0
    2 |    301   302B     0B | 303.0 |   304B |    312   304B |    313   306B |    621   617B |   307B |     3   2.0
    3 |    401   402B     0B | 403.0 |   404B |    412   404B |    413   406B |    821   817B |   407B |     4   2.0
    4 |    501   502B     0B | 503.0 |   504B |    512   504B |    513   506B |   1.0K  1017B |   507B |     5   2.0
    5 |    601   602B     0B | 603.0 |   604B |    612   604B |    613   606B |   1.2K  1.2KB |   607B |     6   2.0
    6 |    701   702B     0B |     - |   704B |    712   704B |    713   706B |   1.4K  1.4KB |   707B |     7   2.0
total |   2.8K  2.7KB     0B |     - |  2.8KB |   2.9K  2.8KB |   2.9K  2.8KB |   5.7K  8.4KB |  2.8KB |    28   3.0
--------------------------------------------------------------------------------------------------------------------
WAL: 22 files (24B)  in: 25B  written: 26B (4% overhead)
Flushes: 8
Compactions: 5  estimated debt: 6B  in progress: 2 (7B)
             default: 27  delete: 28  elision: 29  move: 30  read: 31  rewrite: 32  multi-level: 33
MemTables: 12 (11B)  zombie: 14 (13B)
Zombie tables: 16 (15B)
Block cache: 2 entries (1B)  hit rate: 42.9%
Table cache: 18 entries (17B)  hit rate: 48.7%
Snapshots: 4  earliest seq num: 1024
Table iters: 21
Filter utility: 47.4%
Ingestions: 27  as flushable: 36 (34B in 35 tables)
```

If this is ok, I will update the compaction log parser regexp and tests.

**Comment by RaduBerinde** [comment]
Actually, make that 111 chars (I added some tests which show that all humanized values will never be more than 5 chars):
```
      |                      |       |       |    ingested   |     moved     |    written    |       |    amp
level | tables   size val-bl | score |    in | tables   size | tables   size | tables   size |  read |   r    w
------+----------------------+-------+-------+---------------+---------------+---------------+-------+---------
    0 |    101   102B     0B | 103.0 |  104B |    112   104B |    113   106B |    221   217B |  107B |   1  2.1
    1 |    201   202B     0B | 203.0 |  204B |    212   204B |    213   206B |    421   417B |  207B |   2  2.0
    2 |    301   302B     0B | 303.0 |  304B |    312   304B |    313   306B |    621   617B |  307B |   3  2.0
    3 |    401   402B     0B | 403.0 |  404B |    412   404B |    413   406B |    821   817B |  407B |   4  2.0
    4 |    501   502B     0B | 503.0 |  504B |    512   504B |    513   506B |   1.0K  1017B |  507B |   5  2.0
    5 |    601   602B     0B | 603.0 |  604B |    612   604B |    613   606B |   1.2K  1.2KB |  607B |   6  2.0
    6 |    701   702B     0B |     - |  704B |    712   704B |    713   706B |   1.4K  1.4KB |  707B |   7  2.0
total |   2.8K  2.7KB     0B |     - | 2.8KB |   2.9K  2.8KB |   2.9K  2.8KB |   5.7K  8.4KB | 2.8KB |  28  3.0
---------------------------------------------------------------------------------------------------------------
WAL: 22 files (24B)  in: 25B  written: 26B (4% overhead)
Flushes: 8
Compactions: 5  estimated debt: 6B  in progress: 2 (7B)
             default: 27  delete: 28  elision: 29  move: 30  read: 31  rewrite: 32  multi-level: 33
MemTables: 12 (11B)  zombie: 14 (13B)
Zombie tables: 16 (15B)
Block cache: 2 entries (1B)  hit rate: 42.9%
Table cache: 18 entries (17B)  hit rate: 48.7%
Snapshots: 4  earliest seq num: 1024
Table iters: 21
Filter utility: 47.4%
Ingestions: 27  as flushable: 36 (34B in 35 tables)
```

**Review by sumeerbhola — APPROVED** [review]
This looks great! The narrower table sets us up well for the future where we may need more columns for blob files (with value separation).

:lgtm_strong: 

> Reviewed 2 of 7 files at r1, 2 of 7 files at r4, 8 of 8 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2739#-:-N_dFBCt5_-ZyBuhPgPr:bjd93x2)* status: all files reviewed, 3 unresolved discussions (waiting on @jbowens and @RaduBerinde)

___
*[`tool/logs/compaction.go` line 118 at r6](https://reviewable.io/reviews/cockroachdb/pebble/2739#-N_dGGeU9Ist5u2-bUJe:-N_dGGeV2KwhyXV_WU5F:b-iv6d86) ([raw file](https://github.com/cockroachdb/pebble/blob/762649e49a68f03543fc97fbfea0863cc49d1a01/tool/logs/compaction.go#L118)):*
> ```Go
> 	//
> 	readAmpPattern = regexp.MustCompile(
> 		/* Read-amp     */ `(?:^|\+)total \|.*?(?P<value>\d+).{5}$`,
> ```

Should we keep the old regexp too, and fallback to trying to parse with it in case this pattern doesn't succeed?
May help in case someone recently upgraded their cockroachdb binary and then tries to run this tool on logs recently produced by the older version.

And perhaps we should put something in the CRDB release notes when bumping Pebble to pick this up, in case some users have built some tooling to parse this format.

**Review by jbowens — COMMENTED** [review]
Thanks for doing this; the new format is really nice.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2739#-:-N_dTZfY6lS9DkVKsNZC:b-gl80wj)* status: all files reviewed, 3 unresolved discussions (waiting on @RaduBerinde and @sumeerbhola)

**Review by RaduBerinde — COMMENTED** [review]
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2739#-:-N_dtUN923sFD25obwCZ:bz5mair)* status: 10 of 13 files reviewed, 3 unresolved discussions (waiting on @sumeerbhola)

___
*[`tool/logs/compaction.go` line 118 at r6](https://reviewable.io/reviews/cockroachdb/pebble/2739#-N_dGGeU9Ist5u2-bUJe:-N_dtTEACwh9813j8BWo:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/762649e49a68f03543fc97fbfea0863cc49d1a01/tool/logs/compaction.go#L118)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Thanks, I will fork the test file to keep a test with the 23.1 format and make sure both work.

Agreed on the release notes.
</blockquote></details>

Done.

**Pull request merged**
