### PR TITLE
db: Remove calls to the block property collector from addIndexEntry

### PR DESCRIPTION
**Pull request by bananabrick**
In #1383, we will introduce the ability to compress blocks in parallel
to the goroutine which makes calls to the Writer. We will also write
blocks to disk in a goroutine which runs parallel to the Writer goroutine.

This disk write goroutine will call Writer.addIndexEntry, which causes
issues with how block property collectors work.

So, this pr moves all calls to the block property collector out of
addIndexEntry.

### CODE REVIEW

**Review by bananabrick — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1403)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @itsbilal and @jbowens)

___
*[sstable/writer.go, line 416 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1403#-MqR0xwd9oG4MlxpqYku:-MqR0xwd9oG4MlxpqYkv:b-jxz5ju) ([raw file](https://github.com/cockroachdb/pebble/blob/6e070658444429237604969542c1a9687328b24e/sstable/writer.go#L416)):*
> ```Go
> 	shouldFlushIndexBlock := supportsTwoLevelIndex(w.tableFormat) &&
> 		shouldFlush(
> 			w.historicSepLength, w.historicEncodedBlockHandleWithPropertiesLength,
> ```

I'm using these historic values here to determine if the index block should be flushed. Right now, it's just the values determined when the previous data block was flushed, but we could keep a weighted average, too.

**Review by sumeerbhola — COMMENTED** [review]
I'm having a hard time understanding what is going on here, and why. Even if this turns out to be necessary, I would suggest trying to figure out an intermediate abstraction (to be added to this file) that sits above the writers `[]BlockPropertyCollector` and `blockPropertiesEncoder`. Otherwise we will end up with spaghetti code that is hard to understand and maintain.

More specifically,
- When the decision is made that the previous data block is finished (in the first goroutine), we have to iterate over the `[]BlockPropertyCollector` and use the `blockPropertiesEncoder` to encode the block properties. We have the encoded block properties sitting in `blockPropertiesEncoder.propsBuf`. The current code has the `BlockHandle` since the compression has happened so it can immediately serialize `BlockHandleWithProperties` (reusing the `tmp` buffer) and write it to the index.

- I am assuming what has changed is that will no longer have the `BlockHandle` until the compression is done, so we can't serialize `BlockHandleWithProperties`, so we need to stash the properties away for use later. We have a similar situation now with the top-level block in a two level index, since we don't have the `BlockHandle` (which includes the offset) until we can actually write the lower level index blocks. In that case we use `blockPropertiesEncoder.props` instead of `unsafeProps` to make a copy. I imagine we would need to do the same (and based on benchmark results figure out an optimization to reduce memory allocations -- maybe keep a single larger slice from which we parcel out subslices for the props).

- The other problem is determining up front where the index block boundaries will lie, and carrying that information for later. You have some code for that here, but it is hard to understand why in this isolated context. I think we should have a struct `dataBlockState` that contains the `[]byte` of the uncompressed block produced by `blockWriter.finish()`, the index key,  and the corresponding `props`, and have a `[][]dataBlockState`, where these are first gathered according to the index block they belong in and then all of them.
So unless I am missing something, I'd rather see this change as part of the clean abstractions that are built for the compression pipelining change.

I haven't had time to look at the compression pipelining change, and am unlikely be able to do so this week. I notice @jbowens is commenting there.
@bananabrick @jbowens am I missing something?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1403#-:-MqUsxRB025Q-2Ap4qHs:bjpwdcc)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @itsbilal and @jbowens)

**Review by bananabrick — COMMENTED** [review]
The interaction between parallel compression and block property collectors was that, the block property collector was being accessed, and its functions were being called by two separate goroutines, and block property collectors have invariants on when, and in what order its functions must be called.

In this change, I did a bit of a code shuffle(while ensuring that the block property collector, and encoder) and invariants are met, so that I can avoid calling into the block property collector through two goroutines in the pipelining pr.

To achieve that, I had to determine whether an index block should be flushed, before we called `addIndexEntry`. I believe the behaviour is still exactly the same as before.

> I am assuming what has changed is that will no longer have the BlockHandle until the compression is done, so we can't serialize BlockHandleWithProperties, so we need to stash the properties away for use later. We have a similar situation now with the top-level block in a two level index, since we don't have the BlockHandle (which includes the offset) until we can actually write the lower level index blocks. In that case we use blockPropertiesEncoder.props instead of unsafeProps to make a copy. I imagine we would need to do the same (and based on benchmark results figure out an optimization to reduce memory allocations -- maybe keep a single larger slice from which we parcel out subslices for the props).

I already do this, other than the part where I reduce allocations(haven't pushed that yet).

> The other problem is determining up front where the index block boundaries will lie, and carrying that information for later. You have some code for that here, but it is hard to understand why in this isolated context. I think we should have a struct dataBlockState that contains the []byte of the uncompressed block produced by blockWriter.finish(), the index key, and the corresponding props, and have a [][]dataBlockState, where these are first gathered according to the index block they belong in and then all of them.

My current design avoids having to store them in something like a `[][]dataBlockState`. The only problem was the calls to the block property collectors itself.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1403#-:-MqVCKl0DxD-YeT7KQ-_:b-7wz74z)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @itsbilal and @jbowens)

**Comment by bananabrick** [comment]
Capturing some conversation from a short meeting with @sumeerbhola 

1. It would be better to have some abstractions in this code to make the code easier to understand.
2. After having some discussion in this pr, it's best to close this, and integrate the code with the entire parallel compression pr.

**Review by bananabrick — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1403)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @itsbilal and @jbowens)

___
*[sstable/writer.go, line 416 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1403#-MqR0xwd9oG4MlxpqYku:-MqVQnCn88rpM_VBMyBZ:bx0zfc0) ([raw file](https://github.com/cockroachdb/pebble/blob/6e070658444429237604969542c1a9687328b24e/sstable/writer.go#L416)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

I think I'm misunderstanding, don't we have the the real `indexSep` and `encodedBHP` right here? Why do we need to use historic lengths as an estimate? I thought the only remaining problem in determining whether or not we will need to flush the index block is the length of the compressed sstable itself.
</blockquote></details>

We won't have the encodedBHP in the case of parallel compression(we won't have a block handle, either).

**Review by bananabrick — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1403)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @itsbilal and @jbowens)

___
*[sstable/writer.go, line 416 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1403#-MqR0xwd9oG4MlxpqYku:-MqVRDTj8L06caWUgHGg:bi71nrt) ([raw file](https://github.com/cockroachdb/pebble/blob/6e070658444429237604969542c1a9687328b24e/sstable/writer.go#L416)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

We won't have the encodedBHP in the case of parallel compression(we won't have a block handle, either).
</blockquote></details>

The encodedBHP will contain the length of the compressed sstable, though.

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1403)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @bananabrick and @itsbilal)

___
*[sstable/writer.go, line 416 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1403#-MqR0xwd9oG4MlxpqYku:-MqVol5-BhFbMUQMhtnh:b-xzcf7p) ([raw file](https://github.com/cockroachdb/pebble/blob/6e070658444429237604969542c1a9687328b24e/sstable/writer.go#L416)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

The encodedBHP will contain the length of the compressed sstable, though.
</blockquote></details>

Why won't we have `encodedBHP`? The data block is finished, and we need to compute the block properties for the block synchronously with the `(*Writer).Add` call in order to not violate the existing block property collector's contract.

It seems like we could:
1. Decide that we need to finish the data block.
2. Collect the data block's properties.
3. Use `w.block.curKey` to compute the separator that will be added to the index block.
4. Compute an upper bound on the size of the `BlockHandle`-value that will be written to the index block by using `binary.MaxVarintLen64` instead of the true length of the varint encoded compressed block.
5. Use the values from 3 and 4 and to compute whether we'll need to flush the index block.

**Review by bananabrick — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1403)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @itsbilal and @jbowens)

___
*[sstable/writer.go, line 416 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1403#-MqR0xwd9oG4MlxpqYku:-MqWKw0pAR3d5DvDlBiF:b-9u5uwt) ([raw file](https://github.com/cockroachdb/pebble/blob/6e070658444429237604969542c1a9687328b24e/sstable/writer.go#L416)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

Why won't we have `encodedBHP`? The data block is finished, and we need to compute the block properties for the block synchronously with the `(*Writer).Add` call in order to not violate the existing block property collector's contract.

It seems like we could:
1. Decide that we need to finish the data block.
2. Collect the data block's properties.
3. Use `w.block.curKey` to compute the separator that will be added to the index block.
4. Compute an upper bound on the size of the `BlockHandle`-value that will be written to the index block by using `binary.MaxVarintLen64` instead of the true length of the varint encoded compressed block.
5. Use the values from 3 and 4 and to compute whether we'll need to flush the index block.
</blockquote></details>

We won't have it because we need the block handle to compute the encoded BHP. We can compute the block properties for the data block synchronously without the block handle or encodedBHP.

I already do points 1, 2, 3 in your list. I can probably use an upper bound instead of using a historic value.

**Comment by bananabrick** [comment]
Closing this out. Will integrate this with the parallel compression pr while making some changes.

**Pull request closed without merging**
