### PR TITLE
make randomHeight faster by using runtime.fastrand

### PR DESCRIPTION
**Pull request by zhiqiangxu**
FYI:

https://github.com/golang/go/blob/b5c66de0892d0e9f3f59126eeebc31070e79143b/src/runtime/stubs.go#L115

### CODE REVIEW

**Comment by petermattis** [comment]
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/583)

**Comment by zhiqiangxu** [comment]
I didn't benchmark myself, but I compared the implementation, the runtime one is much cheaper, besides, it's also used in TiDB:)

About the dependency issue, I can deal with it if you decide to choose the runtime one:)

**Comment by petermattis** [comment]
> I didn't benchmark myself, but I compared the implementation, the runtime one is much cheaper, besides, it's also used in TiDB:)

How did you compare the implementation? Did you benchmark it? There are existing benchmarks in `internal/arenaskl` that you can run.

**Comment by zhiqiangxu** [comment]
This is the benchmark I ran:

BenchmarkFastRand-4   	300000000	         4.43 ns/op	       0 B/op	       0 allocs/op

BenchmarkPCG-4   	300000000	         5.01 ns/op	       0 B/op	       0 allocs/op


10% faster .

Test is available here: https://github.com/zhiqiangxu/util/blob/master/uuid_test.go#L20

**Comment by petermattis** [comment]
It is common practice to run a benchmark 10 or 20 times and use a tool like [benchstat](https://godoc.org/golang.org/x/perf/cmd/benchstat) to compare the before and after.

10% faster is only 0.6ns, though. That is literally lost in the noise of a `Skiplist.Add` operation:

```
name                 time/op
ReadWrite/frac_0-16   301ns ± 7%
```

I'd really like to see a high-level benchmark (such as `ReadWrite/frac_0`) affected by this change.

**Comment by zhiqiangxu** [comment]
Right，it is lost in the noise of skiplist.Add,which takes several hundreds of ns.

**Pull request closed without merging**
