### PR TITLE
colblk: add keyspan block writer, reader, iterator

### PR DESCRIPTION
**Pull request by jbowens**
Add a columnar block schema for keyspans, used for range deletion and range keys.

```
goos: linux
goarch: amd64
pkg: github.com/cockroachdb/pebble/sstable/colblk
cpu: Intel(R) Xeon(R) CPU @ 2.80GHz
                                                                             │    old.log    │              newer.log               │
                                                                             │    sec/op     │    sec/op     vs base                │
KeyspanBlock_RangeDeletions/numSpans=1/keysPerSpan=1/keySize=10/SeekGE-24       156.20n ± 1%    73.42n ± 0%  -53.00% (p=0.000 n=10)
KeyspanBlock_RangeDeletions/numSpans=1/keysPerSpan=1/keySize=10/Next-24          49.36n ± 0%    71.46n ± 0%  +44.77% (p=0.000 n=10)
KeyspanBlock_RangeDeletions/numSpans=1/keysPerSpan=1/keySize=128/SeekGE-24      171.00n ± 0%    80.19n ± 0%  -53.11% (p=0.000 n=10)
KeyspanBlock_RangeDeletions/numSpans=1/keysPerSpan=1/keySize=128/Next-24         54.04n ± 0%    71.32n ± 0%  +31.98% (p=0.000 n=10)
KeyspanBlock_RangeDeletions/numSpans=1/keysPerSpan=2/keySize=10/SeekGE-24       292.45n ± 1%    88.55n ± 0%  -69.72% (p=0.000 n=10)
KeyspanBlock_RangeDeletions/numSpans=1/keysPerSpan=2/keySize=10/Next-24          83.44n ± 0%   102.00n ± 0%  +22.25% (p=0.000 n=10)
KeyspanBlock_RangeDeletions/numSpans=1/keysPerSpan=2/keySize=128/SeekGE-24      325.20n ± 0%    95.70n ± 0%  -70.57% (p=0.000 n=10)
KeyspanBlock_RangeDeletions/numSpans=1/keysPerSpan=2/keySize=128/Next-24         95.14n ± 0%   102.20n ± 0%   +7.42% (p=0.000 n=10)
KeyspanBlock_RangeDeletions/numSpans=1/keysPerSpan=5/keySize=10/SeekGE-24        916.0n ± 1%    135.9n ± 0%  -85.16% (p=0.000 n=10)
KeyspanBlock_RangeDeletions/numSpans=1/keysPerSpan=5/keySize=10/Next-24          487.4n ± 1%    196.8n ± 0%  -59.64% (p=0.000 n=10)
KeyspanBlock_RangeDeletions/numSpans=1/keysPerSpan=5/keySize=128/SeekGE-24      1061.5n ± 1%    143.6n ± 0%  -86.47% (p=0.000 n=10)
KeyspanBlock_RangeDeletions/numSpans=1/keysPerSpan=5/keySize=128/Next-24         541.1n ± 0%    197.5n ± 0%  -63.50% (p=0.000 n=10)
KeyspanBlock_RangeDeletions/numSpans=10/keysPerSpan=1/keySize=10/SeekGE-24      3602.5n ± 0%    138.1n ± 0%  -96.17% (p=0.000 n=10)
KeyspanBlock_RangeDeletions/numSpans=10/keysPerSpan=1/keySize=10/Next-24       3608.50n ± 0%    69.97n ± 0%  -98.06% (p=0.000 n=10)
KeyspanBlock_RangeDeletions/numSpans=10/keysPerSpan=1/keySize=128/SeekGE-24     3687.0n ± 0%    154.1n ± 0%  -95.82% (p=0.000 n=10)
KeyspanBlock_RangeDeletions/numSpans=10/keysPerSpan=1/keySize=128/Next-24      3649.50n ± 0%    70.40n ± 0%  -98.07% (p=0.000 n=10)
KeyspanBlock_RangeDeletions/numSpans=10/keysPerSpan=2/keySize=10/SeekGE-24      3958.0n ± 0%    166.4n ± 0%  -95.80% (p=0.000 n=10)
KeyspanBlock_RangeDeletions/numSpans=10/keysPerSpan=2/keySize=10/Next-24        3700.0n ± 0%    100.8n ± 0%  -97.28% (p=0.000 n=10)
KeyspanBlock_RangeDeletions/numSpans=10/keysPerSpan=2/keySize=128/SeekGE-24     4091.5n ± 0%    182.5n ± 0%  -95.54% (p=0.000 n=10)
KeyspanBlock_RangeDeletions/numSpans=10/keysPerSpan=2/keySize=128/Next-24       3749.5n ± 0%    101.1n ± 0%  -97.30% (p=0.000 n=10)
KeyspanBlock_RangeDeletions/numSpans=10/keysPerSpan=5/keySize=10/SeekGE-24      5440.5n ± 1%    251.3n ± 0%  -95.38% (p=0.000 n=10)
KeyspanBlock_RangeDeletions/numSpans=10/keysPerSpan=5/keySize=10/Next-24        4626.0n ± 0%    196.6n ± 0%  -95.75% (p=0.000 n=10)
KeyspanBlock_RangeDeletions/numSpans=10/keysPerSpan=5/keySize=128/SeekGE-24     5756.0n ± 0%    267.6n ± 0%  -95.35% (p=0.000 n=10)
KeyspanBlock_RangeDeletions/numSpans=10/keysPerSpan=5/keySize=128/Next-24       4738.0n ± 0%    196.4n ± 0%  -95.85% (p=0.000 n=10)
KeyspanBlock_RangeDeletions/numSpans=100/keysPerSpan=1/keySize=10/SeekGE-24     5528.5n ± 0%    200.8n ± 0%  -96.37% (p=0.000 n=10)
KeyspanBlock_RangeDeletions/numSpans=100/keysPerSpan=1/keySize=10/Next-24      3611.00n ± 0%    70.10n ± 0%  -98.06% (p=0.000 n=10)
KeyspanBlock_RangeDeletions/numSpans=100/keysPerSpan=1/keySize=128/SeekGE-24    5909.0n ± 0%    227.2n ± 0%  -96.16% (p=0.000 n=10)
KeyspanBlock_RangeDeletions/numSpans=100/keysPerSpan=1/keySize=128/Next-24     3650.00n ± 0%    70.09n ± 0%  -98.08% (p=0.000 n=10)
KeyspanBlock_RangeDeletions/numSpans=100/keysPerSpan=2/keySize=10/SeekGE-24     7137.0n ± 0%    231.7n ± 0%  -96.75% (p=0.000 n=10)
KeyspanBlock_RangeDeletions/numSpans=100/keysPerSpan=2/keySize=10/Next-24       3697.5n ± 0%    101.0n ± 0%  -97.27% (p=0.000 n=10)
KeyspanBlock_RangeDeletions/numSpans=100/keysPerSpan=2/keySize=128/SeekGE-24    7847.5n ± 0%    258.7n ± 0%  -96.70% (p=0.000 n=10)
KeyspanBlock_RangeDeletions/numSpans=100/keysPerSpan=2/keySize=128/Next-24      3754.5n ± 0%    101.0n ± 0%  -97.31% (p=0.000 n=10)
KeyspanBlock_RangeDeletions/numSpans=100/keysPerSpan=5/keySize=10/SeekGE-24    12801.5n ± 0%    324.1n ± 0%  -97.47% (p=0.000 n=10)
KeyspanBlock_RangeDeletions/numSpans=100/keysPerSpan=5/keySize=10/Next-24       4644.5n ± 1%    195.8n ± 0%  -95.79% (p=0.000 n=10)
KeyspanBlock_RangeDeletions/numSpans=100/keysPerSpan=5/keySize=128/SeekGE-24   14830.5n ± 0%    352.1n ± 0%  -97.63% (p=0.000 n=10)
KeyspanBlock_RangeDeletions/numSpans=100/keysPerSpan=5/keySize=128/Next-24      4752.5n ± 1%    196.2n ± 0%  -95.87% (p=0.000 n=10)
geomean                                                                          1.746µ         137.7n       -92.11%

                                                                             │   old.log   │              newer.log              │
                                                                             │  bytes/row  │ bytes/row   vs base                 │
KeyspanBlock_RangeDeletions/numSpans=1/keysPerSpan=1/keySize=10/SeekGE-24       39.00 ± 0%   91.00 ± 0%  +133.33% (p=0.000 n=10)
KeyspanBlock_RangeDeletions/numSpans=1/keysPerSpan=1/keySize=10/Next-24         39.00 ± 0%   91.00 ± 0%  +133.33% (p=0.000 n=10)
KeyspanBlock_RangeDeletions/numSpans=1/keysPerSpan=1/keySize=128/SeekGE-24      277.0 ± 0%   331.0 ± 0%   +19.49% (p=0.000 n=10)
KeyspanBlock_RangeDeletions/numSpans=1/keysPerSpan=1/keySize=128/Next-24        277.0 ± 0%   331.0 ± 0%   +19.49% (p=0.000 n=10)
KeyspanBlock_RangeDeletions/numSpans=1/keysPerSpan=2/keySize=10/SeekGE-24       30.00 ± 0%   47.50 ± 0%   +58.33% (p=0.000 n=10)
KeyspanBlock_RangeDeletions/numSpans=1/keysPerSpan=2/keySize=10/Next-24         30.00 ± 0%   47.50 ± 0%   +58.33% (p=0.000 n=10)
KeyspanBlock_RangeDeletions/numSpans=1/keysPerSpan=2/keySize=128/SeekGE-24      209.0 ± 0%   167.5 ± 0%   -19.86% (p=0.000 n=10)
KeyspanBlock_RangeDeletions/numSpans=1/keysPerSpan=2/keySize=128/Next-24        209.0 ± 0%   167.5 ± 0%   -19.86% (p=0.000 n=10)
KeyspanBlock_RangeDeletions/numSpans=1/keysPerSpan=5/keySize=10/SeekGE-24       24.60 ± 0%   20.20 ± 0%   -17.89% (p=0.000 n=10)
KeyspanBlock_RangeDeletions/numSpans=1/keysPerSpan=5/keySize=10/Next-24         24.60 ± 0%   20.20 ± 0%   -17.89% (p=0.000 n=10)
KeyspanBlock_RangeDeletions/numSpans=1/keysPerSpan=5/keySize=128/SeekGE-24     168.20 ± 0%   68.20 ± 0%   -59.45% (p=0.000 n=10)
KeyspanBlock_RangeDeletions/numSpans=1/keysPerSpan=5/keySize=128/Next-24       168.20 ± 0%   68.20 ± 0%   -59.45% (p=0.000 n=10)
KeyspanBlock_RangeDeletions/numSpans=10/keysPerSpan=1/keySize=10/SeekGE-24      23.70 ± 0%   19.90 ± 0%   -16.03% (p=0.000 n=10)
KeyspanBlock_RangeDeletions/numSpans=10/keysPerSpan=1/keySize=10/Next-24        23.70 ± 0%   19.90 ± 0%   -16.03% (p=0.000 n=10)
KeyspanBlock_RangeDeletions/numSpans=10/keysPerSpan=1/keySize=128/SeekGE-24     154.6 ± 0%   151.0 ± 0%    -2.33% (p=0.000 n=10)
KeyspanBlock_RangeDeletions/numSpans=10/keysPerSpan=1/keySize=128/Next-24       154.6 ± 0%   151.0 ± 0%    -2.33% (p=0.000 n=10)
KeyspanBlock_RangeDeletions/numSpans=10/keysPerSpan=2/keySize=10/SeekGE-24      22.35 ± 0%   11.95 ± 0%   -46.53% (p=0.000 n=10)
KeyspanBlock_RangeDeletions/numSpans=10/keysPerSpan=2/keySize=10/Next-24        22.35 ± 0%   11.95 ± 0%   -46.53% (p=0.000 n=10)
KeyspanBlock_RangeDeletions/numSpans=10/keysPerSpan=2/keySize=128/SeekGE-24    147.80 ± 0%   77.55 ± 0%   -47.53% (p=0.000 n=10)
KeyspanBlock_RangeDeletions/numSpans=10/keysPerSpan=2/keySize=128/Next-24      147.80 ± 0%   77.55 ± 0%   -47.53% (p=0.000 n=10)
KeyspanBlock_RangeDeletions/numSpans=10/keysPerSpan=5/keySize=10/SeekGE-24     21.540 ± 0%   5.980 ± 0%   -72.24% (p=0.000 n=10)
KeyspanBlock_RangeDeletions/numSpans=10/keysPerSpan=5/keySize=10/Next-24       21.540 ± 0%   5.980 ± 0%   -72.24% (p=0.000 n=10)
KeyspanBlock_RangeDeletions/numSpans=10/keysPerSpan=5/keySize=128/SeekGE-24    143.70 ± 0%   32.22 ± 0%   -77.58% (p=0.000 n=10)
KeyspanBlock_RangeDeletions/numSpans=10/keysPerSpan=5/keySize=128/Next-24      143.70 ± 0%   32.22 ± 0%   -77.58% (p=0.000 n=10)
KeyspanBlock_RangeDeletions/numSpans=100/keysPerSpan=1/keySize=10/SeekGE-24     22.26 ± 0%   13.82 ± 0%   -37.92% (p=0.000 n=10)
KeyspanBlock_RangeDeletions/numSpans=100/keysPerSpan=1/keySize=10/Next-24       22.26 ± 0%   13.82 ± 0%   -37.92% (p=0.000 n=10)
KeyspanBlock_RangeDeletions/numSpans=100/keysPerSpan=1/keySize=128/SeekGE-24    142.4 ± 0%   133.0 ± 0%    -6.60% (p=0.000 n=10)
KeyspanBlock_RangeDeletions/numSpans=100/keysPerSpan=1/keySize=128/Next-24      142.4 ± 0%   133.0 ± 0%    -6.60% (p=0.000 n=10)
KeyspanBlock_RangeDeletions/numSpans=100/keysPerSpan=2/keySize=10/SeekGE-24    21.630 ± 0%   8.915 ± 0%   -58.78% (p=0.000 n=10)
KeyspanBlock_RangeDeletions/numSpans=100/keysPerSpan=2/keySize=10/Next-24      21.630 ± 0%   8.915 ± 0%   -58.78% (p=0.000 n=10)
KeyspanBlock_RangeDeletions/numSpans=100/keysPerSpan=2/keySize=128/SeekGE-24   141.70 ± 0%   68.50 ± 0%   -51.66% (p=0.000 n=10)
KeyspanBlock_RangeDeletions/numSpans=100/keysPerSpan=2/keySize=128/Next-24     141.70 ± 0%   68.50 ± 0%   -51.66% (p=0.000 n=10)
KeyspanBlock_RangeDeletions/numSpans=100/keysPerSpan=5/keySize=10/SeekGE-24    21.250 ± 0%   4.970 ± 0%   -76.61% (p=0.000 n=10)
KeyspanBlock_RangeDeletions/numSpans=100/keysPerSpan=5/keySize=10/Next-24      21.250 ± 0%   4.970 ± 0%   -76.61% (p=0.000 n=10)
KeyspanBlock_RangeDeletions/numSpans=100/keysPerSpan=5/keySize=128/SeekGE-24   141.30 ± 0%   28.81 ± 0%   -79.61% (p=0.000 n=10)
KeyspanBlock_RangeDeletions/numSpans=100/keysPerSpan=5/keySize=128/Next-24     141.30 ± 0%   28.81 ± 0%   -79.61% (p=0.000 n=10)
geomean                                                                         63.79        38.09        -40.29%
```

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3782)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @jbowens, @petermattis, and @sumeerbhola)

___
*[`sstable/colblk/block.go` line 78 at r2](https://reviewable.io/reviews/cockroachdb/pebble/3782#-O2R-dEX7PjMxM8th76E:-O2R-dEX7PjMxM8th76F:b-qomvl5) ([raw file](https://github.com/cockroachdb/pebble/blob/539410cd1de2fec88a6859384387ae35e554c80d/sstable/colblk/block.go#L78)):*
> ```Go
> //	a-e:{(#0,RANGEDEL)}
> //	b-d:{(#100,RANGEDEL)}
> //
> ```

It would be useful to add to this example a span that doesn't touch another span
___
*[`sstable/colblk/block.go` line 91 at r2](https://reviewable.io/reviews/cockroachdb/pebble/3782#-O2R-jLF9F845BQcO0Bz:-O2R-jLF9F845BQcO0C-:b10xnl9) ([raw file](https://github.com/cockroachdb/pebble/blob/539410cd1de2fec88a6859384387ae35e554c80d/sstable/colblk/block.go#L91)):*
> ```Go
> //
> //	+-----------------+-----------------+-----------------+-----------------+
> //	| Start index     | Trailer         | Suffix          | Value           |
> ```

This indexing seems backwards to me. We primarily need to figure out which keys apply to a span not the other way around. Do we ever need to map the other way?

We could store a `startKeyIndex` and `numKeys` for each user key. In this case


| user key | start index | num keys |
|----|----|----|
| a | 0 | 1 |
| b | 1 | 2 |
| d | 3 | 1 |
| e | 0 | 0 |

Zero numKeys values indicate a user key that is only an end key.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3782)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @jbowens, @petermattis, and @sumeerbhola)

___
*[`sstable/colblk/block.go` line 91 at r2](https://reviewable.io/reviews/cockroachdb/pebble/3782#-O2R-jLF9F845BQcO0Bz:-O2R1uBXBpLcWEdYKl3y:b6mb0qh) ([raw file](https://github.com/cockroachdb/pebble/blob/539410cd1de2fec88a6859384387ae35e554c80d/sstable/colblk/block.go#L91)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This indexing seems backwards to me. We primarily need to figure out which keys apply to a span not the other way around. Do we ever need to map the other way?

We could store a `startKeyIndex` and `numKeys` for each user key. In this case


| user key | start index | num keys |
|----|----|----|
| a | 0 | 1 |
| b | 1 | 2 |
| d | 3 | 1 |
| e | 0 | 0 |

Zero numKeys values indicate a user key that is only an end key.
</blockquote></details>

We can also use just a start index if we always include the start and end key in pairs (duplicate keys are almost free). This might also make the search logic cleaner, since we can directly look only at end keys (odd positions) or only at start keys (even positions) depending on what we care about.

| user key | start/end index |
|---|----|
| a | 0 |
| b | 1 |
| b | 1 |
| d | 3 |
| d | 3 |
| e | 4 |

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3782)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @petermattis, @RaduBerinde, and @sumeerbhola)

___
*[`sstable/colblk/block.go` line 91 at r2](https://reviewable.io/reviews/cockroachdb/pebble/3782#-O2R-jLF9F845BQcO0Bz:-O2fZKSx-uQGMJIbFX7k:b37b24q) ([raw file](https://github.com/cockroachdb/pebble/blob/539410cd1de2fec88a6859384387ae35e554c80d/sstable/colblk/block.go#L91)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

We can also use just a start index if we always include the start and end key in pairs (duplicate keys are almost free). This might also make the search logic cleaner, since we can directly look only at end keys (odd positions) or only at start keys (even positions) depending on what we care about.

| user key | start/end index |
|---|----|
| a | 0 |
| b | 1 |
| b | 1 |
| d | 3 |
| d | 3 |
| e | 4 |
</blockquote></details>

Unfortunately, we can't use PrefixBytes for the user keys because they may be suffixed (in both range del and range key cases). We could decompose the user keys column into a prefix and suffix column, but I don't think it's worth the additional complexity.

Indexing the keys in the user key makes sense; We'll need to maintain a bit more state in the keyspan iterator for relative positioning but it seems worth it to remove the binary search over the start indices

**Review by RaduBerinde — APPROVED** [review]
Very cool!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3782#-:-O30YtWiBQ6UQjBHRfAB:b-jdo7t9)* status: 0 of 5 files reviewed, 10 unresolved discussions (waiting on @jbowens, @petermattis, and @sumeerbhola)

___
*[`sstable/colblk/keyspan.go` line 22 at r3](https://reviewable.io/reviews/cockroachdb/pebble/3782#-O30YhBZ2o8p8omqKdcr:-O30YhBZ2o8p8omqKdcs:b-rkm30v) ([raw file](https://github.com/cockroachdb/pebble/blob/c822ad1ebd200fba458851125fdef57a2134750f/sstable/colblk/keyspan.go#L22)):*
> ```Go
> )
> 
> const keyspanHeaderSize = 4
> ```

[nit] add a comment explaining the keyspan header encodes the 32-bit number of rows.
___
*[`sstable/colblk/keyspan.go` line 164 at r3](https://reviewable.io/reviews/cockroachdb/pebble/3782#-O30WhJxBTADeOdZqbSj:-O30WhJxBTADeOdZqbSk:b-dtq3he) ([raw file](https://github.com/cockroachdb/pebble/blob/c822ad1ebd200fba458851125fdef57a2134750f/sstable/colblk/keyspan.go#L164)):*
> ```Go
> 	binary.LittleEndian.PutUint32(w.buf[1+hOff:], pageOffset)
> 	pageOffset = w.boundaryUserKeys.Finish(0, w.boundaryUserKeys.rows, pageOffset, w.buf)
> 	w.buf[hOff] = byte(DataTypeBytes)
> ```

[nit] Seems odd that we write this at the end and not before the write to `w.buf[1+hOff:]`
___
*[`sstable/colblk/keyspan.go` line 167 at r3](https://reviewable.io/reviews/cockroachdb/pebble/3782#-O30WAUf-4MYCeEHs0Rm:-O30VonlEqWUzTfZg2Iw:b9jlvjk) ([raw file](https://github.com/cockroachdb/pebble/blob/c822ad1ebd200fba458851125fdef57a2134750f/sstable/colblk/keyspan.go#L167)):*
> ```Go
> 
> 	// Write the boundary key indices.
> 	hOff = blockHeaderSize(keyspanColBoundaryKeyIndices, keyspanHeaderSize)
> ```

The way we're using `blockHeaderSize` here is very confusing. Can't we start `hOff` as `blockHeaderBase + customHeaderSize` and then do `hOff += columnHeaderSize` each time? Also consider moving this logic to a `ColumnHeaderBuilder` helper (with a method like `AddColumn(DataTypeBytes, pageOffset)`)

In fact, maybe it's worth having a more general builder which internally keeps track of two positions (the position in the header, and the pageOffset). And we would have a method like `AddColumn(DataTypeBytes, pageOffset, w.boundaryKeyIndexes)` with the last argument being an interface or generic that implements `Finish()`
___
*[`sstable/colblk/keyspan.go` line 277 at r3](https://reviewable.io/reviews/cockroachdb/pebble/3782#-O30sZWm524JzkKCrC2Q:-O30sZWm524JzkKCrC2R:b9b69e0) ([raw file](https://github.com/cockroachdb/pebble/blob/c822ad1ebd200fba458851125fdef57a2134750f/sstable/colblk/keyspan.go#L277)):*
> ```Go
> }
> 
> func (r *KeyspanReader) searchBoundaryKeys(cmp base.Compare, key []byte) (index int, equal bool) {
> ```

[nit] worth a comment. Returns the first boundary key >= key, correct?
___
*[`sstable/colblk/keyspan.go` line 287 at r3](https://reviewable.io/reviews/cockroachdb/pebble/3782#-O30sR6V8ZvUesUG8BKh:-O30sR6V8ZvUesUG8BKi:b9yv90s) ([raw file](https://github.com/cockroachdb/pebble/blob/c822ad1ebd200fba458851125fdef57a2134750f/sstable/colblk/keyspan.go#L287)):*
> ```Go
> 		case 0:
> 			return h, true
> 		case -1:
> ```

[nit] maybe just leave this case as the `default` so the generated code is more efficient
___
*[`sstable/colblk/keyspan.go` line 310 at r3](https://reviewable.io/reviews/cockroachdb/pebble/3782#-O30w_0jAUGJ3kRD8WIq:-O30w_0jAUGJ3kRD8WIr:bfiquo5) ([raw file](https://github.com/cockroachdb/pebble/blob/c822ad1ebd200fba458851125fdef57a2134750f/sstable/colblk/keyspan.go#L310)):*
> ```Go
> 	// [startKeyIndex, endKeyIndex). When positioned, endKeyIndex >=
> 	// startKeyIndex.
> 	startKeyIndex uint32
> ```

Do we need these fields? Can't we just obtain them in `materializeSpan()`?
___
*[`sstable/colblk/keyspan.go` line 339 at r3](https://reviewable.io/reviews/cockroachdb/pebble/3782#-O30uoUF95B3S13398uB:-O30uoUF95B3S13398uC:b96588) ([raw file](https://github.com/cockroachdb/pebble/blob/c822ad1ebd200fba458851125fdef57a2134750f/sstable/colblk/keyspan.go#L339)):*
> ```Go
> 	j, eq := i.r.searchBoundaryKeys(i.cmp, key)
> 	// If the found boundary key does not exactly equal the given key, it's
> 	// strictly greater than key. We need to back up one consider the span that
> ```

[nit] to consider
___
*[`sstable/colblk/keyspan.go` line 389 at r3](https://reviewable.io/reviews/cockroachdb/pebble/3782#-O30u3qR6dE0O7Y36TEu:-O30u3qR6dE0O7Y36TEv:b30ug5r) ([raw file](https://github.com/cockroachdb/pebble/blob/c822ad1ebd200fba458851125fdef57a2134750f/sstable/colblk/keyspan.go#L389)):*
> ```Go
> // [startBoundIndex] as the span's start boundary.
> func (i *KeyspanIter) gatherKeysForward(startBoundIndex int) *keyspan.Span {
> 	i.startBoundIndex = startBoundIndex
> ```

[nit]A `numRows := i.r.blockReader.header.Rows` would help a lot in here
___
*[`sstable/colblk/keyspan.go` line 405 at r3](https://reviewable.io/reviews/cockroachdb/pebble/3782#-O30t8jX5sH5VHey4SEz:-O30t8jX5sH5VHey4SF-:bf2owew) ([raw file](https://github.com/cockroachdb/pebble/blob/c822ad1ebd200fba458851125fdef57a2134750f/sstable/colblk/keyspan.go#L405)):*
> ```Go
> 	i.startKeyIndex = i.r.boundaryKeyIndices.At(i.startBoundIndex)
> 	i.endKeyIndex = i.startKeyIndex
> 	for i.startKeyIndex < i.r.blockReader.header.Rows {
> ```

Here we need at most one step, no? So this could just be:
```
i.endKeyIndex = i.r.boundaryKeyIndices.At(i.startBoundIndex+1)
if i.startKeyIndex == i.endKeyIndex {
  i.startBoundIndex++
  if i.startBoundIndex+1 >= int(i.r.boundaryKeysCount) { return CorruptionError() }
  i.endKeyIndex = i.r.boundaryKeyIndices.At(i.startBoundIndex+1)
}
```

We could also add a helper method
```
func (i) isSpan(startBoundIndex) bool {
  return boundaryKeyIndices.At(startBoundIndex) < boundaryKeyIndices.At(endBoundIndex)
}
```
would make things cleaner:
```
func (i *KeyspanIter) gatherKeysForward(startBoundIndex int) *keyspan.Span {
  if startBoundIndex >= int(i.r.boundaryKeysCount)-1 {
    return nil
  }
  if !isSpan(startBoundIndex) {
    if startBoundIndex == int(i.r.boundaryKeysCount)-2 {
      // Corruption error
    }
    startBoundIndex++
    if !isSpan(startBoundIndex) {
      // Corruption error
    }
  }
```

**Review by jbowens — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3782#-:-O33mkgx9v-l54UzWcPl:b-814g8k)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @petermattis, @RaduBerinde, and @sumeerbhola)

___
*[`sstable/colblk/keyspan.go` line 22 at r3](https://reviewable.io/reviews/cockroachdb/pebble/3782#-O30YhBZ2o8p8omqKdcr:-O33K5Lz74EDAhOcYECK:bb6un1j) ([raw file](https://github.com/cockroachdb/pebble/blob/c822ad1ebd200fba458851125fdef57a2134750f/sstable/colblk/keyspan.go#L22)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] add a comment explaining the keyspan header encodes the 32-bit number of rows.
</blockquote></details>

Done
___
*[`sstable/colblk/keyspan.go` line 164 at r3](https://reviewable.io/reviews/cockroachdb/pebble/3782#-O30WhJxBTADeOdZqbSj:-O33KNlT97UpCT4wPBiO:bb6un1j) ([raw file](https://github.com/cockroachdb/pebble/blob/c822ad1ebd200fba458851125fdef57a2134750f/sstable/colblk/keyspan.go#L164)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] Seems odd that we write this at the end and not before the write to `w.buf[1+hOff:]`
</blockquote></details>

Done
___
*[`sstable/colblk/keyspan.go` line 167 at r3](https://reviewable.io/reviews/cockroachdb/pebble/3782#-O30WAUf-4MYCeEHs0Rm:-O33U1Sk9JGGa6ucnprH:bb2lupm) ([raw file](https://github.com/cockroachdb/pebble/blob/c822ad1ebd200fba458851125fdef57a2134750f/sstable/colblk/keyspan.go#L167)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

The way we're using `blockHeaderSize` here is very confusing. Can't we start `hOff` as `blockHeaderBase + customHeaderSize` and then do `hOff += columnHeaderSize` each time? Also consider moving this logic to a `ColumnHeaderBuilder` helper (with a method like `AddColumn(DataTypeBytes, pageOffset)`)

In fact, maybe it's worth having a more general builder which internally keeps track of two positions (the position in the header, and the pageOffset). And we would have a method like `AddColumn(DataTypeBytes, pageOffset, w.boundaryKeyIndexes)` with the last argument being an interface or generic that implements `Finish()`
</blockquote></details>

Good call, added a `blockEncoder` type that cleans this up
___
*[`sstable/colblk/keyspan.go` line 277 at r3](https://reviewable.io/reviews/cockroachdb/pebble/3782#-O30sZWm524JzkKCrC2Q:-O33UYAQBG_w8oTH4Icb:bb6un1j) ([raw file](https://github.com/cockroachdb/pebble/blob/c822ad1ebd200fba458851125fdef57a2134750f/sstable/colblk/keyspan.go#L277)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] worth a comment. Returns the first boundary key >= key, correct?
</blockquote></details>

Done
___
*[`sstable/colblk/keyspan.go` line 287 at r3](https://reviewable.io/reviews/cockroachdb/pebble/3782#-O30sR6V8ZvUesUG8BKh:-O33URJo8qfORVvBs_g1:bb6un1j) ([raw file](https://github.com/cockroachdb/pebble/blob/c822ad1ebd200fba458851125fdef57a2134750f/sstable/colblk/keyspan.go#L287)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] maybe just leave this case as the `default` so the generated code is more efficient
</blockquote></details>

Done
___
*[`sstable/colblk/keyspan.go` line 310 at r3](https://reviewable.io/reviews/cockroachdb/pebble/3782#-O30w_0jAUGJ3kRD8WIq:-O33lDAu7ON9PPs7gAG_:bb6un1j) ([raw file](https://github.com/cockroachdb/pebble/blob/c822ad1ebd200fba458851125fdef57a2134750f/sstable/colblk/keyspan.go#L310)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Do we need these fields? Can't we just obtain them in `materializeSpan()`?
</blockquote></details>

Done
___
*[`sstable/colblk/keyspan.go` line 339 at r3](https://reviewable.io/reviews/cockroachdb/pebble/3782#-O30uoUF95B3S13398uB:-O33UoZW39_OosjfpLXp:bb6un1j) ([raw file](https://github.com/cockroachdb/pebble/blob/c822ad1ebd200fba458851125fdef57a2134750f/sstable/colblk/keyspan.go#L339)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] to consider
</blockquote></details>

Done
___
*[`sstable/colblk/keyspan.go` line 389 at r3](https://reviewable.io/reviews/cockroachdb/pebble/3782#-O30u3qR6dE0O7Y36TEu:-O33UpgOA11l8KKpFHk7:bb6un1j) ([raw file](https://github.com/cockroachdb/pebble/blob/c822ad1ebd200fba458851125fdef57a2134750f/sstable/colblk/keyspan.go#L389)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit]A `numRows := i.r.blockReader.header.Rows` would help a lot in here
</blockquote></details>

Done
___
*[`sstable/colblk/keyspan.go` line 405 at r3](https://reviewable.io/reviews/cockroachdb/pebble/3782#-O30t8jX5sH5VHey4SEz:-O33kWgQ2il_0POIlpyi:b-56p496) ([raw file](https://github.com/cockroachdb/pebble/blob/c822ad1ebd200fba458851125fdef57a2134750f/sstable/colblk/keyspan.go#L405)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Here we need at most one step, no? So this could just be:
```
i.endKeyIndex = i.r.boundaryKeyIndices.At(i.startBoundIndex+1)
if i.startKeyIndex == i.endKeyIndex {
  i.startBoundIndex++
  if i.startBoundIndex+1 >= int(i.r.boundaryKeysCount) { return CorruptionError() }
  i.endKeyIndex = i.r.boundaryKeyIndices.At(i.startBoundIndex+1)
}
```

We could also add a helper method
```
func (i) isSpan(startBoundIndex) bool {
  return boundaryKeyIndices.At(startBoundIndex) < boundaryKeyIndices.At(endBoundIndex)
}
```
would make things cleaner:
```
func (i *KeyspanIter) gatherKeysForward(startBoundIndex int) *keyspan.Span {
  if startBoundIndex >= int(i.r.boundaryKeysCount)-1 {
    return nil
  }
  if !isSpan(startBoundIndex) {
    if startBoundIndex == int(i.r.boundaryKeysCount)-2 {
      // Corruption error
    }
    startBoundIndex++
    if !isSpan(startBoundIndex) {
      // Corruption error
    }
  }
```
</blockquote></details>

Good call—I was being overly prognosticating, imagining applying visibility filtering and the like here. We can cross bridges if they come.

**Review by RaduBerinde — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3782#-:-O386TLu87QK9P8ZOL-t:bnfp4nl)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @petermattis and @sumeerbhola)

**Comment by jbowens** [comment]
TFTR!

**Pull request merged**
