### PR TITLE
db: write OPTIONS file to temporary path

### LINKED ISSUE #1243: db: crash during OPTIONS-XXXXXX write may leave DB inoperable
An ill-timed crash while writing the `OPTIONS-XXXXXX` file during Open may leave it partially written. On a subsequent Open, a half-written `comparer` or `merger` value could cause `checkOptions` to error out, mistakenly thinking the database was written with a different comparer or merger implementation. There might be other parsing conditions where a partially written `OPTIONS-XXXXXX` file causes Open to error out.

We can fix this by writing to a .tmp file and renaming it to its final `OPTIONS-XXXXXX` location.

### PR DESCRIPTION
**Pull request by jbowens**
db: write OPTIONS file to temporary path

During Open, write the OPTIONS file to a temporary file, renaming it
into place only once the entire file is written. This fixes a
theoretical problem where a crash may leave a partially-written OPTIONS
file. Subsequent Opens may refuse to open the database because of the
corrupt OPTIONS file.

Also, only validate the most recent OPTIONS file. There may be multiple
OPTIONS files if the previous process exited before it removing an
earlier OPTIONS file.

This change modifies the filename format of temporary files. These
temporary files are used for CURRENT rotations (while using the
FormatMostCompatible format major version) and for the OPTIONS file
starting in this commit. This change is ok to make without
backwards-incompatibility gating. An old Pebble version that encounters
temporary files with the new filename format will ignore the
unrecognized files. When the database is eventually opened by a new
Pebble version again, Pebble will clean up the leftover temporary files.

Fix #1243.

### CODE REVIEW

**Review by sumeerbhola — COMMENTED** [review]
I am forgetting something -- why does this rename work without using a marker, when using the encrypted FS?

> Reviewed 3 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1264#-:-Mk3tiMvArdp3mnH-bOg:bhnsdjn)* status: 3 of 8 files reviewed, all discussions resolved (waiting on @sumeerbhola)

**Review by jbowens — COMMENTED** [review]
We're relying on the destination path being empty. Since cockroachdb/cockroach#69496 a rename to path that does not exist is okay.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1264#-:-Mk7Xn0C3ePXBTB0O1Yc:byite35)* status: 3 of 8 files reviewed, all discussions resolved (waiting on @sumeerbhola)

**Review by sumeerbhola — APPROVED** [review]
> We're relying on the destination path being empty

ah yes, of course. Thanks!
And could you add this in a code comment.

:lgtm: 

> Reviewed 5 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1264#-:-Mk8cIB_-iMFNedq6gi7:b-lcfyzm)* status: all files reviewed, 1 unresolved discussion (waiting on @jbowens)

___
*[internal/base/filenames.go, line 56 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1264#-Mk8vwlc5DNi5ViQTF5v:-Mk8vwlc5DNi5ViQTF5w:bgb5l6o) ([raw file](https://github.com/cockroachdb/pebble/blob/45efeb852a0dd482690756ec8b543551c4d05ca3/internal/base/filenames.go#L56)):*
> ```Go
> 		return fs.PathJoin(dirname, fmt.Sprintf("CURRENT.%s.dbtmp", fileNum))
> 	case FileTypeTemp:
> 		return fs.PathJoin(dirname, fmt.Sprintf("temporary.%s.dbtmp", fileNum))
> ```

Does this change not need a new format major version? Would be worth stating why in the commit description.

**Review by jbowens — COMMENTED** [review]
for sure,

TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1264#-:-MkDZ1kR2lhU4fAjJTLR:b-x5yt62)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @sumeerbhola)

___
*[internal/base/filenames.go, line 56 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1264#-Mk8vwlc5DNi5ViQTF5v:-MkDYxfw9TvNcZYbBk5O:b-896fja) ([raw file](https://github.com/cockroachdb/pebble/blob/45efeb852a0dd482690756ec8b543551c4d05ca3/internal/base/filenames.go#L56)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Does this change not need a new format major version? Would be worth stating why in the commit description.
</blockquote></details>

Done!

**Pull request merged**
