### PR TITLE
sstable: document some invariants in virtualLastSeekLE

### PR DESCRIPTION
**Pull request by itsbilal**
Follow-up from #3252.

### CODE REVIEW

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3254)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @itsbilal)

___
*[`sstable/reader_iter_single_lvl.go` line 936 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3254#-NpS19jfAwx2vxqf8Xei:-NpS19jfAwx2vxqf8Xej:b-uscupu) ([raw file](https://github.com/cockroachdb/pebble/blob/b56ae1734732a6cb19e8093582ca0dc4a38d3516/sstable/reader_iter_single_lvl.go#L936)):*
> ```Go
> 		return i.skipBackward()
> 	}
> 	// Case B. It could be B2, so there could be keys in the block > key. But the
> ```

I think there is a tighter version of my original comment. We are here either because it was (a) originally case B2, (b) originally case B1 and we iterated successfully to a block with `ikey.UserKey > key`. So the invariant here is `ikey.UserKey > key` and the block preceding this one has no keys > key.
___
*[`sstable/reader_iter_single_lvl.go` line 946 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3254#-NpS10Nz0fCoZIi3epTi:-NpS10Nz0fCoZIi3epTj:b3dih8h) ([raw file](https://github.com/cockroachdb/pebble/blob/b56ae1734732a6cb19e8093582ca0dc4a38d3516/sstable/reader_iter_single_lvl.go#L946)):*
> ```Go
> 		// Enforce the lower bound here, as we could have gone past it, if the
> 		// block property filter excluded the only relevant block within the
> 		// bounds.
> ```

So if `ikey.UserKey > key` then the only way for `ikey.UserKey < i.lower` to be true is if `key < i.lower`. Am I missing something?
___
*[`sstable/reader_iter_single_lvl.go` line 964 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3254#-NpS3M9U88FQNRMiKcfQ:-NpS3M9U88FQNRMiKcfR:bonfyoq) ([raw file](https://github.com/cockroachdb/pebble/blob/b56ae1734732a6cb19e8093582ca0dc4a38d3516/sstable/reader_iter_single_lvl.go#L964)):*
> ```Go
> 	if ikey != nil {
> 		// Enforce the lower bound here, as we could have gone past it. This happens
> 		// if keys between `i.blockLower` and `key` are obsolete, for instance.
> ```

Thanks, this is clearer to me now.
Perhaps extend the comment a bit. Something like the following (feel free to rephrase). Mentioning RANGEDEL below because if they were obsolete due to a more recent point key, we would have found a userkey higher than the lower bound.

// Even though `i.blockLower` (which is equal to `i.lower`) is <= `key`, all internal keys in the user key interval `[i.blockLower, key]` could be obsolete (due to a RANGEDEL). And `i.data.Prev` will skip all these obsolete keys, and could land on a key below the lower bound.

**Review by itsbilal — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3254#-:-NpVvr3n9mv-YodGK8Ju:b-814g8k)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @sumeerbhola)

___
*[`sstable/reader_iter_single_lvl.go` line 936 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3254#-NpS19jfAwx2vxqf8Xei:-NpVuypBDGx7L8JXX-mq:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/b56ae1734732a6cb19e8093582ca0dc4a38d3516/sstable/reader_iter_single_lvl.go#L936)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I think there is a tighter version of my original comment. We are here either because it was (a) originally case B2, (b) originally case B1 and we iterated successfully to a block with `ikey.UserKey > key`. So the invariant here is `ikey.UserKey > key` and the block preceding this one has no keys > key.
</blockquote></details>

Done.
___
*[`sstable/reader_iter_single_lvl.go` line 946 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3254#-NpS10Nz0fCoZIi3epTi:-NpVv9aN9HcC8gOr0r4V:bvl2g22) ([raw file](https://github.com/cockroachdb/pebble/blob/b56ae1734732a6cb19e8093582ca0dc4a38d3516/sstable/reader_iter_single_lvl.go#L946)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

So if `ikey.UserKey > key` then the only way for `ikey.UserKey < i.lower` to be true is if `key < i.lower`. Am I missing something?
</blockquote></details>

I think that's accurate, but that's also the same logic that `SeekLT` applies. We're supposed to check for the lower bound in all cases so I think that's why we need this here.
___
*[`sstable/reader_iter_single_lvl.go` line 964 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3254#-NpS3M9U88FQNRMiKcfQ:-NpVvlZV7yDWhb8j_0VP:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/b56ae1734732a6cb19e8093582ca0dc4a38d3516/sstable/reader_iter_single_lvl.go#L964)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Thanks, this is clearer to me now.
Perhaps extend the comment a bit. Something like the following (feel free to rephrase). Mentioning RANGEDEL below because if they were obsolete due to a more recent point key, we would have found a userkey higher than the lower bound.

// Even though `i.blockLower` (which is equal to `i.lower`) is <= `key`, all internal keys in the user key interval `[i.blockLower, key]` could be obsolete (due to a RANGEDEL). And `i.data.Prev` will skip all these obsolete keys, and could land on a key below the lower bound.
</blockquote></details>

Done.

**Comment by sumeerbhola** [comment]
(reviewable stopped working for me)

> I think that's accurate, but that's also the same logic that SeekLT applies.

I think that for SeekLT, `key` is allowed to be lower than the lower bound. But here that is not allowed.

We should also consider simplifying the signature of `virtualLastSeekLE` to not accept a parameter since it is always called with `i.upper`. I also don't understand what is going on in the following (it seems unnecessary):
```
func (i *twoLevelIterator) virtualLastSeekLE(key []byte) (*InternalKey, base.LazyValue) {
	// Callers of SeekLE don't know about virtual sstable bounds, so we may
	// have to internally restrict the bounds.
	//
	// TODO(bananabrick): We can optimize this check away for the level iter
	// if necessary.
	if i.cmp(key, i.upper) >= 0 {
		if !i.endKeyInclusive {
			panic("unexpected virtualLastSeekLE with exclusive upper bounds")
		}
		key = i.upper
	}
```

We can always generalize later (if a general `SeekLE` is needed).

**Comment by itsbilal** [comment]
> I think that for SeekLT, key is allowed to be lower than the lower bound. But here that is not allowed.

> We should also consider simplifying the signature of virtualLastSeekLE to not accept a parameter since it is always called with i.upper. I also don't understand what is going on in the following (it seems unnecessary)

Cleaned up both and removed the parameter in `virtualLastSeekLE`. Also removed the unnecessary upper bound check seeing as `key` will now always be the upper bound.

**Review by sumeerbhola — APPROVED** [review]
looks great
:lgtm: 

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3254#-:-Nq3uZcR2Pac8VGa86Hz:bmf8erq)* status: all files reviewed, 4 unresolved discussions (waiting on @itsbilal)

___
*[`-- commits` line 2 at r3](https://reviewable.io/reviews/cockroachdb/pebble/3254#-Nq3tm7kBMxY1Z24Azn_):*
slightly stale commit message

**Pull request merged**
