### PR TITLE
sstable: trace/expensive log when sstable footer read is slow

### PR DESCRIPTION
**Pull request by sumeerbhola**
Relates to #3728

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3745#-:-O1YQd2XEgc0O_CSSfB3:bnfp4nl)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @jbowens and @sumeerbhola)

___
*[`internal/base/logger.go` line 104 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3745#-O1YPdCj7ZdGvc5Gp4JW:-O1YPdCj7ZdGvc5Gp4JX:bpw96pb) ([raw file](https://github.com/cockroachdb/pebble/blob/fcbfbd22b6b7e6484fdfce9556e4a2ac1e4ecfaf/internal/base/logger.go#L104)):*
> ```Go
> 	// avoid calling Eventf (which will be a noop when tracing or expensive
> 	// logging is not enabled) to avoid the overhead of boxing the args.
> 	IsTracingEnabled(ctx context.Context) bool
> ```

BTW I noticed a possible issue in the `IsTracingEnabled` implementation in Cockroach - it calls `ExpensiveLogEnabled` which is meant to be called directly - specifically the `VDepth(1)` check gets the source file where `ExpensiveLogEnabled` is called. As things stand, you can only turn all pebble logs on (by using `pebble_logger_and_tracer=2`)
___
*[`sstable/table.go` line 330 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3745#-O1YOonE6A6yOzkyiU3R:-O1YOonE6A6yOzkyiU3S:b-xex4xo) ([raw file](https://github.com/cockroachdb/pebble/blob/fcbfbd22b6b7e6484fdfce9556e4a2ac1e4ecfaf/sstable/table.go#L330)):*
> ```Go
> 		err = f.ReadAt(ctx, buf, off)
> 	}
> 	readDuration := time.Since(readStartTime)
> ```

[nit] We should add a little helper type that would be used like:

```
l := MakeStopwatch(ctx)
...
if duration, shouldLog := l.Finish(); shouldLog {
}
```

This would also give us the flexibility to skip `time.Now()` if tracing is not enabled (not sure which is slower through - `time.Now` or `IsTracingEnabled`)

**Review by sumeerbhola — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3745#-:-O1b6GG_CLk_gSrSIyTC:b-814g8k)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @jbowens and @RaduBerinde)

___
*[`internal/base/logger.go` line 104 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3745#-O1YPdCj7ZdGvc5Gp4JW:-O1ay4G1CEzhvcJaMjY7:b-fv5ir0) ([raw file](https://github.com/cockroachdb/pebble/blob/fcbfbd22b6b7e6484fdfce9556e4a2ac1e4ecfaf/internal/base/logger.go#L104)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

BTW I noticed a possible issue in the `IsTracingEnabled` implementation in Cockroach - it calls `ExpensiveLogEnabled` which is meant to be called directly - specifically the `VDepth(1)` check gets the source file where `ExpensiveLogEnabled` is called. As things stand, you can only turn all pebble logs on (by using `pebble_logger_and_tracer=2`)
</blockquote></details>

Yes, I realized that when doing it, but thought it was not too harmful. I had convinced myself then that it was a simpler story than knowing the Pebble filename, but now I realize that was all wrong. Looking at the source code for `log.modulePat` there seems to be some support for pattern matching, so I suppose one can also include more of the path and we are not stuck with something like --vmodule=reader=2 picking up all reader.go files in CockroachDB and Pebble.

Since the log package functions do accept a depth parameter, we can fix this by changing the implementation in pebble_logger_and_tracer.go. I'll make that change.
___
*[`sstable/table.go` line 330 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3745#-O1YOonE6A6yOzkyiU3R:-O1b5fTCB2kXUCec_6oF:b-13xppm) ([raw file](https://github.com/cockroachdb/pebble/blob/fcbfbd22b6b7e6484fdfce9556e4a2ac1e4ecfaf/sstable/table.go#L330)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] We should add a little helper type that would be used like:

```
l := MakeStopwatch(ctx)
...
if duration, shouldLog := l.Finish(); shouldLog {
}
```

This would also give us the flexibility to skip `time.Now()` if tracing is not enabled (not sure which is slower through - `time.Now` or `IsTracingEnabled`)
</blockquote></details>

I added a `stopwatch` to abstract out the `deterministicReadBlockDurationForTesting` logic.

Did not hide the call to `IsTracingEnabled` because it has the same problem (that we want to fix) that the original caller should be calling it. We can increase the depth when there is a constant extra level of indirection via pebble_logger_and_tracer.go but can't handle a variable amount of indirection.

**Review by RaduBerinde — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3745#-:-O1bCgGD3RPzvKMaeYlL:bnfp4nl)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @jbowens and @sumeerbhola)

___
*[`sstable/reader.go` line 1099 at r2](https://reviewable.io/reviews/cockroachdb/pebble/3745#-O1bCZb24d4Hj9aTUjin:-O1bCZb24d4Hj9aTUjio:beh73t2) ([raw file](https://github.com/cockroachdb/pebble/blob/069a48b95fd4f15a27c2026d5647d884d25d950f/sstable/reader.go#L1099)):*
> ```Go
> func (w stopwatch) stop() time.Duration {
> 	dur := time.Since(w.startTime)
> 	if deterministicReadBlockDurationForTesting {
> ```

[nit] maybe rename to `deterministicDurationsforTesting` or `deterministicStopwatchForTesting`.

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3745)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @jbowens)

___
*[`sstable/reader.go` line 1099 at r2](https://reviewable.io/reviews/cockroachdb/pebble/3745#-O1bCZb24d4Hj9aTUjin:-O1bRMLl3Fh8LL15bAAF:bb7f2mf) ([raw file](https://github.com/cockroachdb/pebble/blob/069a48b95fd4f15a27c2026d5647d884d25d950f/sstable/reader.go#L1099)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] maybe rename to `deterministicDurationsforTesting` or `deterministicStopwatchForTesting`.
</blockquote></details>

done

**Pull request merged**
