### PR TITLE
db: use sublevel level iters for all compactions out of L0

### PR DESCRIPTION
**Pull request by bananabrick**
The simplest way I could come up with to achieve the goal is in this pr.
The compaction picker generates sublevel information which is then used
by the compaction.

### CODE REVIEW

**Review by bananabrick — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1666)* status: 0 of 5 files reviewed, 1 unresolved discussion

___
*[`compaction.go` line 1080 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1666#-N0WajMm9WEl61JQssww:-N0WajMm9WEl61JQsswx:b-kan4y0) ([raw file](https://github.com/cockroachdb/pebble/blob/e86df0baadaa8d94df41bacef0ae087720d92e40/compaction.go#L1080)):*
> ```Go
> 		for _, info := range sublevelInfo {
> 			if err = addItersForLevel(
> 				&compactionLevel{0, info.LevelSlice}, info.Sublevel); err != nil {
> ```

Didn't turn the the `level` `int` in `compactionLevel` into a `manifest.Level` because there's some places in the code where we expect the `int` to be `-1`, and `manifest.Level` is a `uint`.

Didn't seem worthwhile to change that logic.

**Comment by bananabrick** [comment]
Cam hold off on review. Seeing the data race for the first time. Looking.

**Review by itsbilal — COMMENTED** [review]
Looking mostly good! Just waiting for the version lock before giving it another review. 

> Reviewed 3 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1666#-:-N0fnJFf4OyLUe804cKN:b-7b2yv3)* status: 3 of 6 files reviewed, 4 unresolved discussions (waiting on @bananabrick and @itsbilal)

___
*[`db.go` line 1329 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1666#-N0fmbSgAKyG64DBYRTL:-N0fmbSgAKyG64DBYRTM:b-8fx2u7) ([raw file](https://github.com/cockroachdb/pebble/blob/8decd08cdb9d90f4df36e7e3f9daa9f82c1da886/db.go#L1329)):*
> ```Go
> 			// ranges, and not splitting l0 allows us to add level iters
> 			// instead of file iters into the merging iter, which results
> 			// in a faster compaction.
> ```

:+1: 
___
*[`internal/manifest/l0_sublevels.go` line 1441 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1666#-N0fmnz-6Y3bkppg0PTP:-N0fmnz-6Y3bkppg0PTQ:brms6mr) ([raw file](https://github.com/cockroachdb/pebble/blob/dbe67547ab24d671c8b2541cf86db0d0ec7a7e64/internal/manifest/l0_sublevels.go#L1441)):*
> ```Go
> // GenerateSublevelInfo will generate the level slices for each of the sublevels
> // from the level slice for all of L0.
> func GenerateSublevelInfo(cmp base.Compare, levelFiles LevelSlice) []SublevelInfo {
> ```

I think it might be a better idea to put this in the compaction file instead, and just export `f.subLevel` by renaming it to `f.Sublevel`. Seeing as that's the only place where it's used and it's more of a helper function.
___
*[`internal/manifest/version.go` line 185 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1666#-N0fnDDV7vVGxvooi4zW:-N0fnDDV7vVGxvooi4zX:b-rpb8tb) ([raw file](https://github.com/cockroachdb/pebble/blob/dbe67547ab24d671c8b2541cf86db0d0ec7a7e64/internal/manifest/version.go#L185)):*
> ```Go
> 
> // SetSublevel is only used for testing purposes.
> func (m *FileMetadata) SetSublevel(sublevel int) {
> ```

Will be unnecessary once you export `FileMetadata.subLevel`.

**Review by bananabrick — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1666)* status: 1 of 6 files reviewed, 4 unresolved discussions (waiting on @bananabrick and @itsbilal)

___
*[`internal/manifest/l0_sublevels.go` line 1441 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1666#-N0fmnz-6Y3bkppg0PTP:-N0fzQ423kzuN0GM1j1Z:ba0dhgh) ([raw file](https://github.com/cockroachdb/pebble/blob/dbe67547ab24d671c8b2541cf86db0d0ec7a7e64/internal/manifest/l0_sublevels.go#L1441)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

I think it might be a better idea to put this in the compaction file instead, and just export `f.subLevel` by renaming it to `f.Sublevel`. Seeing as that's the only place where it's used and it's more of a helper function.
</blockquote></details>

I wanted to put this in L0 compaction files, but unfortunately, it's also used for manual compactions, or any other type of compaction which will pick a file out of L0 and those don't create the L0CompactionFile structure.

**Review by itsbilal — COMMENTED** [review]
> Reviewed 1 of 5 files at r1, 2 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1666)* status: 2 of 6 files reviewed, 4 unresolved discussions (waiting on @bananabrick and @itsbilal)

___
*[`internal/manifest/l0_sublevels.go` line 1441 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1666#-N0fmnz-6Y3bkppg0PTP:-N0gThi-0tu8Ntl9omuA:bilm2ab) ([raw file](https://github.com/cockroachdb/pebble/blob/dbe67547ab24d671c8b2541cf86db0d0ec7a7e64/internal/manifest/l0_sublevels.go#L1441)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

I wanted to put this in L0 compaction files, but unfortunately, it's also used for manual compactions, or any other type of compaction which will pick a file out of L0 and those don't create the L0CompactionFile structure.
</blockquote></details>

I shoulda been clearer, by `compaction  file` I meant compaction.go (or `compaction_picker.go`). It can live there, it doesn't need to be in the manifest package or need to be exported with an exported SublevelInfo too; both could be exported and in the outer package.

**Review by bananabrick — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1666)* status: 1 of 6 files reviewed, 4 unresolved discussions (waiting on @itsbilal)

___
*[`internal/manifest/l0_sublevels.go` line 1441 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1666#-N0fmnz-6Y3bkppg0PTP:-N0gJgp01DE5JU3nH0Ck:b-plett8) ([raw file](https://github.com/cockroachdb/pebble/blob/dbe67547ab24d671c8b2541cf86db0d0ec7a7e64/internal/manifest/l0_sublevels.go#L1441)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

I shoulda been clearer, by `compaction  file` I meant compaction.go (or `compaction_picker.go`). It can live there, it doesn't need to be in the manifest package or need to be exported with an exported SublevelInfo too; both could be exported and in the outer package.
</blockquote></details>

Ohh gotcha. Done.
___
*[`internal/manifest/version.go` line 185 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1666#-N0fnDDV7vVGxvooi4zW:-N0gbomGAWO20biELJij:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/dbe67547ab24d671c8b2541cf86db0d0ec7a7e64/internal/manifest/version.go#L185)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Will be unnecessary once you export `FileMetadata.subLevel`. 
</blockquote></details>

Done.

**Review by itsbilal — APPROVED** [review]
:lgtm: great work!

> Reviewed 1 of 1 files at r2, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1666#-:-N0qvnHC5yFlBEGdO_oV:b-2zonaq)* status: all files reviewed, 3 unresolved discussions (waiting on @bananabrick)

___
*[`compaction_picker.go` line 101 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1666#-N0qvX1g2jcZfsydIia5:-N0qvX1g2jcZfsydIia6:b-89wvgj) ([raw file](https://github.com/cockroachdb/pebble/blob/34a4e802f06a06fd655fc0789ae79d32fbe80cb9/compaction_picker.go#L101)):*
> ```Go
> type sublevelInfo struct {
> 	manifest.LevelSlice
> 	Sublevel manifest.Level
> ```

nit: doesn't need to be exported

**Pull request merged**
