### PR TITLE
db: add NextPrefix method to Iterator 

### PR DESCRIPTION
**Pull request by jbowens**
Expose a NextPrefix method on *pebble.Iterator that may be called when the user
wishes to move to the next key prefix (as determined by Comparer.Split).
NextPrefix guarantees that it will move to the next key prefix.

Here's a benchmark comparison of two versions of the benchmark. On the 'old'
benchmark, there is no NextPrefix optimization and the benchmark manually
checks for a new unique prefix. In the 'new' benchmark, the benchmark uses
NextPrefix and omits the manual checks since NextPrefix guarantees the next
returned key will be a new prefix:

```
name                         old time/op    new time/op    delta
NextPrefix/versions=1-24        135µs ± 0%     130µs ± 1%   -4.25%  (p=0.000 n=10+10)
NextPrefix/versions=2-24        313µs ± 1%     154µs ± 0%  -50.97%  (p=0.000 n=10+10)
NextPrefix/versions=10-24      1.71ms ± 0%    0.35ms ± 1%  -79.70%  (p=0.000 n=10+10)
NextPrefix/versions=100-24     12.0ms ± 3%     2.6ms ± 2%  -78.37%  (p=0.000 n=10+9)
NextPrefix/versions=1000-24     142ms ± 1%      53ms ± 1%  -62.72%  (p=0.000 n=10+10)

name                         old alloc/op   new alloc/op   delta
NextPrefix/versions=1-24        10.0B ± 0%     10.0B ± 0%     ~     (all equal)
NextPrefix/versions=2-24        13.0B ± 0%     10.0B ± 0%  -23.08%  (p=0.002 n=8+10)
NextPrefix/versions=10-24       35.4B ± 2%     13.0B ± 0%  -63.28%  (p=0.000 n=10+10)
NextPrefix/versions=100-24       137B ±29%       36B ± 0%  -73.66%  (p=0.000 n=10+8)
NextPrefix/versions=1000-24    3.26kB ± 2%    1.24kB ± 4%  -61.92%  (p=0.000 n=9+8)

name                         old allocs/op  new allocs/op  delta
NextPrefix/versions=1-24         1.00 ± 0%      1.00 ± 0%     ~     (all equal)
NextPrefix/versions=2-24         1.00 ± 0%      1.00 ± 0%     ~     (all equal)
NextPrefix/versions=10-24        1.00 ± 0%      1.00 ± 0%     ~     (all equal)
NextPrefix/versions=100-24       1.40 ±43%      1.00 ± 0%     ~     (p=0.087 n=10+10)
NextPrefix/versions=1000-24      28.4 ± 5%      11.0 ± 0%  -61.23%  (p=0.000 n=8+8)
```

### CODE REVIEW

**Review by jbowens — COMMENTED** [review]
I need to think through testing. The _Pebble_ metamorphic tests don't use suffixed keys and Pebble's behavior will increasingly be dependent on suffixes.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1387#-:-MpIcmmu3C1Fx_CkmrYH:bl7nlm9)* status: 0 of 15 files reviewed, all discussions resolved

**Review by sumeerbhola — COMMENTED** [review]
> Reviewed 5 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1387)* status: 4 of 15 files reviewed, 1 unresolved discussion (waiting on @jbowens and @sumeerbhola)

___
*[sstable/block.go, line 855 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1387#-MpiBIhd5a-DUSEnVacI:-MpiBIhd5a-DUSEnVacJ:bw9naho) ([raw file](https://github.com/cockroachdb/pebble/blob/8ae8bb8d2b90b636ffe3c44667b1483fed36c6da/sstable/block.go#L855)):*
> ```Go
> 		// number of bytes shared is greater than currentPrefixLen, then some of
> 		// the suffix is shared and this key must have the same prefix as the
> 		// key that the user last saw. In that case, we continue in the loop.
> ```

I think we still have a problem. The continuing issue is that the encoding of prefix@suffix can have information about the positioning and length of the suffix anywhere in the userkey, and we have no visibility into that without calling Split or Compare on the assembled key.

Say Compare was sorting in increasing lexicographic order of the prefix, and the part after the + is the suffix (byte concatenation):
b + \0 
b\0 + \0\0...

currentPrefixLen will be 1 after the first key, and since the next key shares a byte prefix >= currentPrefixLen we will skip it, even though it is the NextPrefix.

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1387)* status: 4 of 15 files reviewed, 1 unresolved discussion (waiting on @sumeerbhola)

___
*[sstable/block.go, line 855 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1387#-MpiBIhd5a-DUSEnVacI:-MpiMYlQAR_jdu4DvkF5:b-ee3jz) ([raw file](https://github.com/cockroachdb/pebble/blob/8ae8bb8d2b90b636ffe3c44667b1483fed36c6da/sstable/block.go#L855)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I think we still have a problem. The continuing issue is that the encoding of prefix@suffix can have information about the positioning and length of the suffix anywhere in the userkey, and we have no visibility into that without calling Split or Compare on the assembled key.

Say Compare was sorting in increasing lexicographic order of the prefix, and the part after the + is the suffix (byte concatenation):
b + \0 
b\0 + \0\0...

currentPrefixLen will be 1 after the first key, and since the next key shares a byte prefix >= currentPrefixLen we will skip it, even though it is the NextPrefix.

</blockquote></details>

Yeah, I think we still need the fix I mentioned in #1385: I think we need to `Split(i.ikey.UserKey)` and only skip over the key if `Split(i.ikey.UserKey) == currentPrefixLen`. I'll work it in and re-run the benchmarks this flex friday

**Review by nicktrav — COMMENTED** [review]
> Reviewed 15 of 15 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1387)* status: all files reviewed, 1 unresolved discussion (waiting on @sumeerbhola)

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1387)* status: 0 of 19 files reviewed, 1 unresolved discussion (waiting on @nicktrav and @sumeerbhola)

___
*[sstable/block.go, line 855 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1387#-MpiBIhd5a-DUSEnVacI:-MtPcXlo3YFOWlUNeydd:bjl6ywc) ([raw file](https://github.com/cockroachdb/pebble/blob/8ae8bb8d2b90b636ffe3c44667b1483fed36c6da/sstable/block.go#L855)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

Yeah, I think we still need the fix I mentioned in #1385: I think we need to `Split(i.ikey.UserKey)` and only skip over the key if `Split(i.ikey.UserKey) == currentPrefixLen`. I'll work it in and re-run the benchmarks this flex friday
</blockquote></details>

I updated this to `split` the user key before skipping to ensure that the key has the same prefix.

**Comment by jbowens** [comment]
Metamorphic tests revealed an issue where we don't always advance to the next prefix. I'll look into it.

**Pull request closed without merging**
