### PR TITLE
sstable: Fix twoLevelIterator handling around boundaries

### PR DESCRIPTION
**Pull request by itsbilal**
twoLevelIterator had a bug that would become apparent when run
with small SSTs under a levelIter (which has a different treatment
of range tombstone boundaries than when the twoLevelIterator is
used directly).

Basically, it was possible to Prev() past the start
key of the top level index, therefore returning nil while leaving
the next index' iterator and the data iterator valid. However if the
next operation is a Next(), it would see that the underlying
singleLevelIterator is valid, so the next couple Next()s would fall
through to it,
until that iterator is exhausted, and then the topLevelIterator would
be Next()'d to its first value, reloading the nexet index iterator back
to the same value that was returned in a previous Next(). The twoLevelIterator
would therefore seem to go "backward" in a sequence of Next()s.

This change updates twoLevelIterator to invalidate all underlying
iterators when the top level iterator is exhausted.

Found via the metamorphic test.

### CODE REVIEW

**Comment by petermattis** [comment]
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/655)

**Comment by itsbilal** [comment]
Made a small change and moved one `data.invalidate()` into `loadIndex()`, to match `singleLevelIterator` behaviour.

I'll tackle a test for this tomorrow. Need to see why the reader tests aren't helping here.

**Comment by itsbilal** [comment]
And yes, we probably should backport this to 20.1. twoLevelIterators seem to be rarely used by us, and as a well-placed panic just showed, we don't test them in `TestReader` at all.

**Comment by itsbilal** [comment]
Updated `TestReader` to test two-level indexes. Had to both pass writerOptions through (which weren't being passed through, surprisingly) - and also build a larger SST.

**Comment by itsbilal** [comment]
TFTR!

**Pull request merged**
