### PR TITLE
internal/manifest: delete L0Sublevels_LargeImport test

### LINKED ISSUE #2710: l0_sublevels: unskip TestL0Sublevels_LargeImportL0
This test has been skipped for years. It needs to be fixed and un-skipped, or removed if equivalent test coverage is already provided by other means.

### PR DESCRIPTION
**Pull request by itsbilal**
Previously we had skipped the L0Sublevels_LargeImport test as
it was not well-written and buggy. On closer inspection it does
not provide any net new test coverage and is just a sanity test
with loading a large manifest and picking some compactions in a row,
something that will happen with metamorphic test runs too. Plus,
the same manifest is already loaded in some benchmarks. Fixing
the test added 60+ seconds to the runtime of the whole test suite.

This change deletes this test.

Fixes #2710

### CODE REVIEW

**Comment by itsbilal** [comment]
Though it's debatable if this test is useful to begin with. It takes 60 seconds on its own (!), most of which is taken up by the L0 sublevels initialization and the read of the giant manifest. I don't see what bugs this would expose that won't also be exposed by the metamorphic test, also all it does is ensure compaction picking doesn't panic, there aren't any assertions here. My initial hunch would be to delete it. Thoughts?

**Comment by jbowens** [comment]
> My initial hunch would be to delete it. Thoughts?

🚮

**Comment by itsbilal** [comment]
🚮 it is

**Review by jbowens — APPROVED** [review]
lgtm

**Comment by itsbilal** [comment]
TFTR!

**Pull request merged**
