### PR TITLE
compaction: propose multi level compaction heursitics

### PR DESCRIPTION
**Pull request by msbutler**
This PR proposes heuristic to start a multilevel compaction, leveraging the multilevel compaction mechanics introduced in #1603

WIP: still experimenting/experimenting with compaction mechanics.

### CODE REVIEW

**Comment by msbutler** [comment]
Before posting some updated benchmarking results with additional low level metrics (hopefully next week), I wanted to respond to some questions raised about the theoretical benefits of multi-level compaction:

### Modeling WriteAmp with a MultiLevel Compaction Policy
In the first two paragraphs in @sumeerbhola's comment [here,](https://github.com/cockroachdb/pebble/pull/1603#issuecomment-1144309758) , he describes a toy model used to think about write amp when multiLevel compaction is possible. What if we modelled per level write-amp as an _expected value_ , allowing us to cleanly model it as a function of multiLevel compaction probability. I.e.:

`PerLevelWriteAmp = Probability_Multilevel*Wamp_MultiLevel+(1-Probability_Multilevel)*(Wamp_SingleLevel)`

where `Wamp_SingleLevel = (bytesFlushed+ BytesCompacted)/(bytesWritten)`, and  `Probability_MultiLevel` is the probability that the given level is an intermediate level in a multiLevel compaction-- data will be read from the level, but no data will be written to it. 

I _think_ that first term can be set to 0, implying that  `PerLevelWriteAmp = (1-Probability_Multilevel)*(Wamp_SingleLevel)`. Why? When a level is an intermediate level, the compaction picker is avoiding some contribution to writeAmp to that level. After all, if multiLevel compaction didn't exist, that compaction event would have contributed some write amp at the given level.

If the formula above is valid, I think i we can model the probability of a multi level compaction as a function of per level file size, per level fan out / write amp. On the other hand, maybe my logic is totally off :D.

@petermattis also [pointed me](https://github.com/cockroachdb/pebble/pull/1603#issuecomment-1146024781) to his [toy model](https://github.com/petermattis/compacttoy/blob/master/multilevel.go) where he works out write amp in a multiLevel compaction toy model. Like him, I'm quite puzzled by the math. Specifically, I don't understand where the per level write amp definition comes from (below). From the bit of reading I've done, it seems that per level fanout (`s_(x+1)/s_x`) is a decent heuristic for  per level write amp, and but his model is doing something more complicated. 
```
// Write amplification is minimized when it is the same at each
// level. The formulas below define the write amplification at each
// level based on the size of each level.
//
// s(x) = size of level x
// T(y) = sum of level sizes [1,y]
// T(y+1) = T(y) + s(y+1)
//
// w(1) = s(1) / 2               ; write-amp at level 1
// w(n) = T(n) / (T(n-1) + 1)    ; write-amp at level n
```

### Triggering a multilevel compaction only when a sufficient chunk of the intermediate level is involved. 
As @sumeerbhola points out in the last paragraph in his comment [here](https://github.com/cockroachdb/pebble/pull/1603#issuecomment-1144309758), we should _only_ trigger a multilevel compaction if the would be intermediate level is sufficiently involved. 

Currently, we trigger a multi-level compaction if `fullOutputSoon || highOutputInvolvement`, but we should change it to:
`highOutputInvolvement || (fullOutputSoon && minOutputInvolvement)`, where perhaps:

```
highOutputInvolvement := (float64(pc.outputLevel.files.SizeSum()) / float64(curOutputLevelSize)) > 0.5
minOutputInvolvement := (float64(pc.outputLevel.files.SizeSum()) / float64(curOutputLevelSize)) > 0.2
```

**Review by sumeerbhola — COMMENTED** [review]
I'm having a hard time understanding anything in https://github.com/petermattis/compacttoy/blob/master/multilevel.go -- I'm probably thinking about this with a different mental model. We should ask Peter what he does recall -- maybe he is puzzled by only some later bits of the math so can help get us to at least the same level of understanding.

I was roughly thinking of the following -- want to understand how close this is to what you have in mind.
Do a multi-level compaction when all the following conditions are satisfied
- The output level will fill up due to this compaction (I am not convinced about a disjunction with 50% involved in the compaction, since that may result in excessive compactions when the output level is close to empty, when a level first starts getting populated, that can happen when the LSM is new-ish.)
- Calculate `w-amp-2-level = compaction-output-level-bytes/compaction-input-level-bytes` and `w-amp-3-level = compaction-output-level-plus-1-bytes/ (compaction-output-level-bytes+compaction-input-level-bytes)`. If `w-amp-3-level + delta < w-amp-2-level` (I don't know what delta should be -- perhaps 0), then do a 3 level compaction. The idea here is that even though we are not choosing the best keyspan from the perspective of the `kMinOverlappingRatio`, we are choosing something where the write-amp for this 3 level compaction is not worse than the 2 level compaction.

I have of course no idea whether the above will work well -- I am making things up. But the rough principle I'd like to follow is:
- Use conservative heuristics that we are somewhat convinced will do no damage.
- Add metrics (I mentioned some in my comments on the previous PR) that help us deeply understand how these heuristics are behaving.
- Run experiments on two kinds of LSMs, and say add 50GB (a) starting from empty, (b) starting with 300GB. For (b) we can copy the LSM state after it reaches 300GB and use that as the starting state for each subsequent experiment. That will help us understand the behavior of heuristics both on a "young" LSM and an "old" LSM.
- Iterate over the previous steps.

None of this requires production quality code, so we can optimize on experimentation speed. I'm happy to promptly look at new heuristics and the metrics that help us understand the experiment results (I was ooo for a couple of weeks), in case you want an extra pair of eyes through the process (which will also help in the eventual code review of the heuristics we settle on, since the why-this-heuristic question will already be answered).

btw, in your earlier experiments, how were you ensuring that compactions were not falling behind? Was the compaction concurrency set to very high, or was the write concurrency low? We want to run this with high amount of provisioned bandwidth and high enough compaction concurrency such that none of the experiments have a compaction backlog when the writes end, so that we are getting write-amp numbers that are actually comparable.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1746#-:-N6FVBTMD3U7pSnsZBTQ:b-nurghs)* status: 0 of 15 files reviewed, all discussions resolved (waiting on @msbutler)

**Comment by petermattis** [comment]
> I'm having a hard time understanding anything in https://github.com/petermattis/compacttoy/blob/master/multilevel.go -- I'm probably thinking about this with a different mental model. We should ask Peter what he does recall -- maybe he is puzzled by only some later bits of the math so can help get us to at least the same level of understanding.

I don't understand the math I wrote in that code either. I think better to start with the comment:

> // The multi-level compaction strategy. A flush attempts to write data into the
// lowest non-empty level. Failing to find such a level, compactions are rooted
// at the highest level and include the subsequent levels such that the
// compaction would not cause the level being compacted into to become "too
// large". The observation behind this strategy is that if a compaction from
// Ln->Ln+1 causes Ln+1 to require a compaction, then we would have been better
// off to perform a compaction from Ln->Ln+2 (i.e. a compaction which
// encompasses Ln+1). A similar observation applies to flushes: if a flush to
// Ln triggers a compaction from Ln->Ln+1, then that compaction should be
// merged with the flush in order to reduce write amplification.

I believe the complexity in the math is determining when is a level "too large". Rather than use the level sizing heuristics, the multi-level compaction strategy aims to minimize total write-amp which occurs when all levels experience the same write-amp. I very well might have butchered something in the math there. Could be useful to add some debugging statements to that simulation to see how it behaves as data is written.

**Comment by msbutler** [comment]
closing in favor of #2787

**Pull request closed without merging**
