### PR TITLE
crl-release-22.1: vfs: add SyncData,SyncTo,Preallocate to vfs.File 

### PR DESCRIPTION
**Pull request by jbowens**
Expand the vfs.File interface to expose SyncData, SyncTo and Preallocate as
first-class methods. Previously, the file created through vfs.NewSyncingFile
would perform analagous I/O operations (eg, `Fdatasync`, `sync_file_range`,
`Fallocate`) outside the context of the interface. This easily allowed the
accidental loss of the disk-health checking over these operations by minor
tweaks to the interface of the disk-health checking implementation or by adding
intermediary VFS wrappers between the disk-health checking FS and the syncing
file.

See https://github.com/cockroachdb/cockroach/issues/94373 where the introduction of an additional VFS
wrapper resulted in these I/O operations being uncovered by disk-stall
detection.

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
Looks very good overall, some minor comments.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2284#-:-NMogG9r0Bss6FY9pFCp:bqqkfp6)* status: 0 of 26 files reviewed, 3 unresolved discussions (waiting on @jbowens)

___
*[`vfs/default_linux.go` line 64 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2284#-NModnSk8O5f2-PEtbeY:-NModnSk8O5f2-PEtbeZ:b-lrqb44) ([raw file](https://github.com/cockroachdb/pebble/blob/0bcdaeac06055006de7aed6ae255f221e6fb038c/vfs/default_linux.go#L64)):*
> ```Go
> func (f *linuxFile) SyncTo(offset int64) (fullSync bool, err error) {
> 	if !f.useSyncRange {
> 		// Use fdatasync, which does provide persistence guarantees but won't
> ```

[nit] Maybe this belongs inside `SyncData` and this can call `f.SyncData()`
___
*[`vfs/syncing_file.go` line 22 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2284#-NMofEfr1j2um8eTL_ml:-NMofEfr1j2um8eTL_mm:b-gts9vk) ([raw file](https://github.com/cockroachdb/pebble/blob/0bcdaeac06055006de7aed6ae255f221e6fb038c/vfs/syncing_file.go#L22)):*
> ```Go
> 	File
> 	// fd can be InvalidFd if the underlying File does not support it.
> 	fd              uintptr
> ```

Do we still need a `fd` here?
___
*[`vfs/syncing_file.go` line 151 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2284#-NMof0K0AV7sWDfwZPb_:-NMof0K0AV7sWDfwZPba:bh8jlvn) ([raw file](https://github.com/cockroachdb/pebble/blob/0bcdaeac06055006de7aed6ae255f221e6fb038c/vfs/syncing_file.go#L151)):*
> ```Go
> 	}
> 	if fullSync {
> 		f.ratchetSyncOffset(offset)
> ```

We go through some trouble to return the flag just for this, which seems like a minor optimization (for configurations we don't care that much about)

**Comment by RaduBerinde** [comment]
@jbowens is the plan to forward-port this to v22.2 and master when it's ready?

**Comment by jbowens** [comment]
@RaduBerinde yeah, this is actually already the backport of #2276. and the plan is to update #2271 to incorporate the bit of feedback that was applied to #2276 but not yet #2271.

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2284)* status: 0 of 26 files reviewed, 3 unresolved discussions (waiting on @RaduBerinde)

___
*[`vfs/syncing_file.go` line 22 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2284#-NMofEfr1j2um8eTL_ml:-NN7KQy09sNjQRYbGgR5:b-krbngf) ([raw file](https://github.com/cockroachdb/pebble/blob/0bcdaeac06055006de7aed6ae255f221e6fb038c/vfs/syncing_file.go#L22)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Do we still need a `fd` here?
</blockquote></details>

i suppose we could call `file.Fd()`
___
*[`vfs/syncing_file.go` line 151 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2284#-NMof0K0AV7sWDfwZPb_:-NN7J6IC4vPqzvcH0TyR:bxv06ys) ([raw file](https://github.com/cockroachdb/pebble/blob/0bcdaeac06055006de7aed6ae255f221e6fb038c/vfs/syncing_file.go#L151)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

We go through some trouble to return the flag just for this, which seems like a minor optimization (for configurations we don't care that much about)
</blockquote></details>

it's not just configurations we don't care about, because `sync_file_range` isn't universally available on linux. we only even attempt to use it on `ext{2,3,4}` filesystems. XFS is also a recommended CockroachDB filesystem, and despite not being recommended we have customers that use ZFS.

**Review by RaduBerinde — COMMENTED** [review]
Ah, I didn't realize that merged to 22.2. Then please ignore any comments here, we don't want the backport to be different

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2284#-:-NN7Tgdk58YD-CkjWw7Y:b-diafbk)* status: 0 of 26 files reviewed, 3 unresolved discussions (waiting on @jbowens)

___
*[`vfs/syncing_file.go` line 22 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2284#-NMofEfr1j2um8eTL_ml:-NN7U5a3EKsgZ3Ow0nlZ:b-1cyvuo) ([raw file](https://github.com/cockroachdb/pebble/blob/0bcdaeac06055006de7aed6ae255f221e6fb038c/vfs/syncing_file.go#L22)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

i suppose we could call `file.Fd()`
</blockquote></details>

I meant do we still need it at all? I guess we are still comparing it to `InvalidFd` so never mind.. (though in the future we might want to switch to some get-capabilities functionality in vfs.File, or at least rename the field here to `supportsPreallocate bool`)

**Review by RaduBerinde — APPROVED** [review]

**Comment by jbowens** [comment]
TFTR!

**Pull request merged**
