### PR TITLE
db: use uncompensated scores to smoothe compaction picking scores

### PR DESCRIPTION
**Pull request by jbowens**
When adjusting scores by smoothing scores, use a parallel uncompensated
score as the divisor for the smoothing adjustment. This helps avoid
range deletions in lower levels from starving compactions in higher
levels through excessive prioritization of lower-level disk space
reclamation.

Informs #1181.

### CODE REVIEW

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
Can you run the roachtest mentioned in https://github.com/cockroachdb/pebble/commit/730159ff3e1131b433d0c9d472b93d989cc801be so we have some comparison numbers.

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1189#-:-Me_caRH2luyZdL43l6N:b-sa865x)* status: all files reviewed, 2 unresolved discussions (waiting on @jbowens)

___
*[compaction_picker.go, line 732 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1189#-Me_ZtXXCyyPTq6DM-VB:-Me_ZtXY-prMo8_AGs58:b5d34l0) ([raw file](https://github.com/cockroachdb/pebble/blob/f29b3837481048db326d63a93015e1d555417b30/compaction_picker.go#L732)):*
> ```Go
> 				sizeAdjust[input.level].outgoingCompensatedBytes += compensatedSize
> 				sizeAdjust[input.level].outgoingActualBytes += actualSize
> 				if c.outputLevel != -1 {
> ```

Could you add a comment to `compaction.outputLevel` clarifying when it is nil (I believe it is delete only compactions). And I think that is what causes this -1 case for `compactionInfo.outputLevel`. Confusingly, there is another `CompactionInfo` struct where we set the output level to L6 when `compaction.outputLevel` is nil (which of course won't work here).
___
*[compaction_picker_test.go, line 180 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1189#-Me_bsQG7CMoU8AEz9D5:-Me_bsQG7CMoU8AEz9D6:b-b6pf81) ([raw file](https://github.com/cockroachdb/pebble/blob/f29b3837481048db326d63a93015e1d555417b30/compaction_picker_test.go#L180)):*
> ```Go
> 		func(d *datadriven.TestData) string {
> 			switch d.Cmd {
> 			case "init":
> ```

Can you add a code comment about the input format accepted by load version.

**Review by jbowens — COMMENTED** [review]
> Can you run the roachtest mentioned in 730159f so we have some comparison numbers.

I'll try it — I'm not sure exactly which configuration @petermattis tried,  and it sounds like he altered it to run for an hour. I'll run with both master and this change. I'm not sure that we'll see much difference, since I don't think we write many range tombstones unless there's rebalancing... I'll run something with nodes > replication factor.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1189#-:-MeaAmNo1jNtK6yyA1WI:b-aclnfz)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @sumeerbhola)

___
*[compaction_picker.go, line 732 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1189#-Me_ZtXXCyyPTq6DM-VB:-Me_m1Yh-7RM2eAOdF_I:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/f29b3837481048db326d63a93015e1d555417b30/compaction_picker.go#L732)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Could you add a comment to `compaction.outputLevel` clarifying when it is nil (I believe it is delete only compactions). And I think that is what causes this -1 case for `compactionInfo.outputLevel`. Confusingly, there is another `CompactionInfo` struct where we set the output level to L6 when `compaction.outputLevel` is nil (which of course won't work here).
</blockquote></details>

Done.
___
*[compaction_picker_test.go, line 180 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1189#-Me_bsQG7CMoU8AEz9D5:-Me_pR-l7jMOmd_q-yOd:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/f29b3837481048db326d63a93015e1d555417b30/compaction_picker_test.go#L180)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Can you add a code comment about the input format accepted by load version.
</blockquote></details>

Done.

**Review by petermattis — COMMENTED** [review]
In the absence of point/range tombstones, we expect this change to have no effect on compaction scores, right? The change conceptually makes sense to me. I suspect we could use a new workload, perhaps in `pebble bench`, that has a mixture of writes and range deletions. 

Some additional commentary that could be added is that the point of this scoring adjustment is to avoid compacting into a level that is "too large" as doing so increases write amplification (we'll just have to compact out of that level in the near future). But that argument only applies to the uncompensated level size. If a range tombstone is inflating a level's compensated size, then we can compact into it without problem. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1189#-:-MeaEfDSDwMUbthBmwkH:b-3qx6im)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @sumeerbhola)

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1189#-:-MefI1M91SQ3hXC11hiy:bg7igkv)* status: all files reviewed, 2 unresolved discussions (waiting on @sumeerbhola)

**Review by jbowens — COMMENTED** [review]
@sumeerbhola, @nicktrav — thoughts on merging this to help address cockroachlabs/support#1788?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1189#-:-NDE1X8vAf6AIMqpnHlW:b50949h)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @sumeerbhola)

**Comment by nicktrav** [comment]
Is it possible to "reverse engineer" the scores from https://github.com/cockroachlabs/support/issues/1788 and then run them back through this proposed change to see what the effect would have been?

I'm all for landing this if we have the real-world data backing it up.

**Comment by jbowens** [comment]
It would definitely increase priority of compactions out of L0 in cases like this. IMO, the only reason to _not_ merge this is the tradeoff of possibly increasing w-amp during these scenarios of large deletes.


It's not possible to reverse engineer scores that are directly comparable to the scores in the LSM printout, because we don't have knowledge of the active compactions at the exact moment the LSM printout was obtained.

Back of the envelope, if there were no active compactions :
```
L0 score (unadjusted) : 2*<sublevels>/<L0Threshold> = (2*9)/4          = 4.5
L6 initial goal size  : <DB size> * .9 = 963 G * .9                    = 867 G
L1 goal size.         : <LBaseMaxBytes>                                = 64 MB
L1 score (unadjusted) : (<L1 size> / <level max bytes> = 29 MB / 64 MB = 0.4531
L0 adjusted.          : <L0 score> / <L1 score> = 4.5 / 0.4531         = ~9.9 
```

**Comment by jbowens** [comment]
Superseded by #2663.

**Pull request closed without merging**
