### PR TITLE
sstable: sanity check read blockhandles are within file

### PR DESCRIPTION
**Pull request by dt**

### CODE REVIEW

**Review by itsbilal — APPROVED** [review]
:lgtm:

We need more of these checks around calls of `decodeBlockHandle` to catch what would be future read-time errors early, but this is a good place to start.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1039#-:-MQIK3eZ2nK9U0Vkrape:bdt5sit)* status: all files reviewed, 1 unresolved discussion (waiting on @dt)

___
*[sstable/table.go, line 264 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1039#-MQIKEvI1QTwNMjHNGrz:-MQIKEvI1QTwNMjHNGs-:b-ymt3u7) ([raw file](https://github.com/cockroachdb/pebble/blob/494fd80b82c6526dcf9643f2029897cd3b191959/sstable/table.go#L264)):*
> ```Go
> 		var n int
> 		footer.metaindexBH, n = decodeBlockHandle(buf)
> 		if n == 0 || footer.metaindexBH.Offset > end || footer.metaindexBH.Offset+footer.metaindexBH.Length > end {
> ```

Can be simplified to the offset+length check alone. If offset > end ,offset + length > end will also be true as these are uints.

**Review by dt — COMMENTED** [review]
These are the only two that are coming out of bytes which aren't checksummed though, right?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1039#-:-MQIOlFP7fsxXe2dUoTf:b-q1n25k)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @itsbilal)

___
*[sstable/table.go, line 264 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1039#-MQIKEvI1QTwNMjHNGrz:-MQIOkdn-s7cCEl8GKRt:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/494fd80b82c6526dcf9643f2029897cd3b191959/sstable/table.go#L264)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Can be simplified to the offset+length check alone. If offset > end ,offset + length > end will also be true as these are uints.
</blockquote></details>

Done.

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1039)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @dt and @itsbilal)

___
*[sstable/table.go, line 269 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1039#-MQIobW38nmmPF1ohh7r:-MQIobW38nmmPF1ohh7s:b-f47h1q) ([raw file](https://github.com/cockroachdb/pebble/blob/acc0391aab7877213fcbc51dded3336cfe804c15/sstable/table.go#L269)):*
> ```Go
> 		buf = buf[n:]
> 
> 		footer.indexBH, n = decodeBlockHandle(buf)
> ```

There are a lot of callers of `decodeBlockHandle` and we are only checking here. Ideally we would do the offset, length consistency checking inside `decodeBlockHandle` but it seems many of the call-sites don't have the file size handy.
Was there a real issue that motivated this PR? Should we add a TODO in `decodeBlockHandle` to do more error checking?

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1039)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @itsbilal and @sumeerbhola)

___
*[sstable/table.go, line 269 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1039#-MQIobW38nmmPF1ohh7r:-MQIpzB35W1gGB-iA4Y4:b-amsj6c) ([raw file](https://github.com/cockroachdb/pebble/blob/acc0391aab7877213fcbc51dded3336cfe804c15/sstable/table.go#L269)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

There are a lot of callers of `decodeBlockHandle` and we are only checking here. Ideally we would do the offset, length consistency checking inside `decodeBlockHandle` but it seems many of the call-sites don't have the file size handy.
Was there a real issue that motivated this PR? Should we add a TODO in `decodeBlockHandle` to do more error checking?
</blockquote></details>

I commented at the top level on this: the ones decoding block handles from the index or whatever are reading from checksummed bytes -- AFAIK, these are the only two reading from the footer bytes which have no checks, right?

**Review by itsbilal — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1039)* status: all files reviewed, 1 unresolved discussion (waiting on @sumeerbhola)

___
*[sstable/table.go, line 269 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1039#-MQIobW38nmmPF1ohh7r:-MQJ9flyAtXuUyElVFkD:bc7100e) ([raw file](https://github.com/cockroachdb/pebble/blob/acc0391aab7877213fcbc51dded3336cfe804c15/sstable/table.go#L269)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

I commented at the top level on this: the ones decoding block handles from the index or whatever are reading from checksummed bytes -- AFAIK, these are the only two reading from the footer bytes which have no checks, right?
</blockquote></details>

That seems correct, I can't think of any other non-footer places where we read from non-checksummed bytes.

**Comment by dt** [comment]
TFTR!

**Pull request merged**
