### PR TITLE
*: crlfmt all code

### PR DESCRIPTION
**Pull request by choleraehyq**
Signed-off-by: Cholerae Hu <choleraehyq@gmail.com>

### CODE REVIEW

**Review by petermattis — COMMENTED** [review]
`gofmt` style is dependent on the Go version you're using. Some of these changes might be reflective of that. Additionally, the Pebble developers are CockroachDB developers. In the CRDB repo we use a tool called `crlfmt` which extends `gofmt` with a few additional style changes (e.g. wrapping long function declarations). I think it would be best to run `crlfmt` on this code, rather than `gofmt`. 

> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/928#-:-MHfi2LsCFLWe1iWHOFk:bwvjzdy)* status: 1 of 6 files reviewed, all discussions resolved

**Comment by choleraehyq** [comment]
@petermattis Done.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/928)* status: 0 of 200 files reviewed, 1 unresolved discussion (waiting on @choleraehyq and @petermattis)

___
*[compaction_picker.go, line 23 at r2](https://reviewable.io/reviews/cockroachdb/pebble/928#-MHkarVT7wWfjr0ryQ9o:-MHkarVT7wWfjr0ryQ9p:b-3fubkx) ([raw file](https://github.com/cockroachdb/pebble/blob/75558a276a18cf596bd364c3f6d576075b383498/compaction_picker.go#L23)):*
> ```Go
> 
> type compactionEnv struct {
> 	bytesCompacted		*uint64
> ```

What is going on here? The spaces between `bytesCompacted` and `*uint64` were replaced with tabs. That doesn't seem right and my version of `crlfmt` (which I just recompiled) doesn't do this. @choleraehyq Do you have any idea how this occurred?

**Comment by choleraehyq** [comment]
@petermattis I'm using the master version of crlfmt. The exact command I ran is `crlfmt -w -diff=false -ignore 'vendor' .`, did I miss some flag?

I run `crlfmt -w compaction_picker.go` and no diff printed.

**Comment by petermattis** [comment]
Huh. This is what I get:

```
~ crlfmt -diff=true compaction_picker.go | head -20
diff -u old/compaction_picker.go new/compaction_picker.go
--- old/compaction_picker.go	2020-09-22 08:00:25.000000000 -0400
+++ new/compaction_picker.go	2020-09-22 08:00:25.000000000 -0400
@@ -20,10 +20,10 @@
 const minIntraL0Count = 4

 type compactionEnv struct {
-	bytesCompacted		*uint64
-	earliestUnflushedSeqNum	uint64
-	earliestSnapshotSeqNum	uint64
-	inProgressCompactions	[]compactionInfo
+	bytesCompacted          *uint64
+	earliestUnflushedSeqNum uint64
+	earliestSnapshotSeqNum  uint64
+	inProgressCompactions   []compactionInfo
 }

 type compactionPicker interface {
@@ -41,8 +41,8 @@
```

I don't know what is going on here and I don't have time right now to investigate further. We can't merge this PR until it is figured out because subsequent PRs will just reverse all of this whitespace change.

**Comment by choleraehyq** [comment]
@petermattis Seems it's because of github.com/cockroachdb/gostdlib/x/tools/imports. After I add fast=true, these tabs related diff disappear. Crlfmt doesn't use any dependencies management tools, so maybe we are using different versions of github.com/cockroachdb/gostdlib/x/tools/imports. I'm using the latest version of gostdlib, which is fbdd8f0abc9baea11b7bf52b6a19d5eab5e5af10.

**Comment by choleraehyq** [comment]
It's a little bit hard to dig deeper into it. Because the unit tests of crlfmt itself don't pass https://github.com/cockroachdb/crlfmt/issues/34 .

**Comment by petermattis** [comment]
> It's a little bit hard to dig deeper into it. Because the unit tests of crlfmt itself don't pass cockroachdb/crlfmt#34 .

Ah, you're installing `cockroachdb/crlfmt`. CRDB engineers are using the `crlfmt` vendored into `cockroachdb/cockroach`. Slightly onerous, but if you check out `github.com/cockroachdb/cockroach` and `make bin/.bootstrap` you'll get the same `bin/crlfmt` that I use.

**Comment by choleraehyq** [comment]
@petermattis Done.

**Review by petermattis — APPROVED** [review]
:lgtm: Thanks for figuring out that white space issue.

> Reviewed 3 of 187 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/928#-:-MI0Dcvk4UnBCkLMst7-:b-mrsuvn)* status: 0 of 36 files reviewed, all discussions resolved (waiting on @petermattis)

**Comment by SWDevAngel** [comment]
@choleraehyq LAST DAY TO ORDER!
Hi Cholerae. Thank you for contributing to CockroachDB this year. As a token of our appreciation we would like to send you a gift. We tried to reach you via GitHub and on email, but if you didn’t see the message please DM me on our [community Slack](https://cockroa.ch/slack) `@lisa` so I can send you a link to order your gift. (If you don’t want a gift, we also have a charitable contribution choice.) All orders must be in by December 13 (that’s tomorrow!), so please send this asap. :)

**Pull request merged**
