### PR TITLE
db: avoid loading later files for a level in SeekPrefixGE

### LINKED ISSUE #3575: db: avoid loading later files for a level in SeekPrefixGE
In `levelIter.SeekPrefixGE` we do `loadFileIndicator := l.loadFile(l.findFileGE(key, flags), +1)` which does not care about the prefix (in CockroachDB, these `MVCCGet` iterators don't have bounds set), so can load an arbitrarily later file in the level. This is something we should optimize, since there could be gaps in levels which are causing us to unnecessarily load files. This is likely to be true for CockroachDB local keys, including locks and intents which we always try to read, since that part of the key space is very sparse.

(noticed due to https://github.com/cockroachdb/cockroach/pull/123313 where we had a failed read of an AbortSpanKey due to slow shared storage file read, even though the AbortSpanKey is a replicated range-id local key, so will never be in a shared storage file)

Jira issue: PEBBLE-299

### PR DESCRIPTION
**Pull request by jbowens**
Don't load arbitrarily later files during levelIter.SeekPrefixGE. This avoids unnecessary IO and CPU overhead.

Close #3575.

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3615)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @itsbilal, @jbowens, and @sumeerbhola)

___
*[`level_iter.go` line 562 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3615#-NxnmuYI5TaTvXMV8JlJ:-NxnmuYJ1vPo1ZdikXsW:b-ghhdhw) ([raw file](https://github.com/cockroachdb/pebble/blob/5fd7e15183fae374bd94a71857769be2adb15bd0/level_iter.go#L562)):*
> ```Go
> 		// unnecessary. This has been observed in practice on slow shared
> 		// storage. See #3575.
> 		if l.prefix != nil && l.cmp(file.SmallestPointKey.UserKey[l.split(file.SmallestPointKey.UserKey):], l.prefix) > 0 {
> ```

The `:` looks in the wrong place here

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3615)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @itsbilal, @RaduBerinde, and @sumeerbhola)

___
*[`level_iter.go` line 562 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3615#-NxnmuYI5TaTvXMV8JlJ:-Nxs3vLC0H4RL9UehNAy:b-44ve9e) ([raw file](https://github.com/cockroachdb/pebble/blob/5fd7e15183fae374bd94a71857769be2adb15bd0/level_iter.go#L562)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

The `:` looks in the wrong place here
</blockquote></details>

Ooof; fixed and added a test that I should've added to begin with
___
*[`testdata/level_iter` line 184 at r2](https://reviewable.io/reviews/cockroachdb/pebble/3615#-Nxs42QwBKtNgVvM1Yj4:-Nxs42QwBKtNgVvM1Yj5:b-kfso1e) ([raw file](https://github.com/cockroachdb/pebble/blob/5e941d80f72e392bced6b67c70bcba5d612182c2/testdata/level_iter#L184)):*
> ```
> next
> prev
> prev
> ```

prevs removed because these are not actually permitted by the `InternalIterator` interface

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3615#-:-Nxs6vLM7FNqt78zXR49:bnfp4nl)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @itsbilal, @jbowens, and @sumeerbhola)

___
*[`level_iter.go` line 562 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3615#-NxnmuYI5TaTvXMV8JlJ:-Nxs5fuG8MAaq9J3yZEY:b-avftcp) ([raw file](https://github.com/cockroachdb/pebble/blob/5fd7e15183fae374bd94a71857769be2adb15bd0/level_iter.go#L562)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

Ooof; fixed and added a test that I should've added to begin with
</blockquote></details>

I would add a `Prefix(userKey []byte) []byte` method on `base.Split` and change this and the other callsite to `l.split.Prefix(file.SmallestPointKey.UserKey)`.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3615)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @itsbilal, @jbowens, and @sumeerbhola)

___
*[`level_iter.go` line 562 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3615#-NxnmuYI5TaTvXMV8JlJ:-NxxOIFUD3POueU5dNSJ:b-ytsrzw) ([raw file](https://github.com/cockroachdb/pebble/blob/5fd7e15183fae374bd94a71857769be2adb15bd0/level_iter.go#L562)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I would add a `Prefix(userKey []byte) []byte` method on `base.Split` and change this and the other callsite to `l.split.Prefix(file.SmallestPointKey.UserKey)`.
</blockquote></details>

If you want, I can make that change separately, there are probably many other call sites that would benefit.

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3615)* status: 0 of 9 files reviewed, 2 unresolved discussions (waiting on @itsbilal, @RaduBerinde, and @sumeerbhola)

___
*[`level_iter.go` line 562 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3615#-NxnmuYI5TaTvXMV8JlJ:-NxxP_Jp-FK2R0snA9hL:b6hin09) ([raw file](https://github.com/cockroachdb/pebble/blob/5fd7e15183fae374bd94a71857769be2adb15bd0/level_iter.go#L562)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

If you want, I can make that change separately, there are probably many other call sites that would benefit.
</blockquote></details>

was working on it just now! pushed

**Review by RaduBerinde — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3615#-:-NxxeibWCZT6XeEd0rJJ:bnfp4nl)* status: 0 of 9 files reviewed, 3 unresolved discussions (waiting on @itsbilal, @jbowens, and @sumeerbhola)

___
*[`level_iter.go` line 562 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3615#-NxnmuYI5TaTvXMV8JlJ:-NxxejFV4MMGoXghvD_m:b-wdj8zi) ([raw file](https://github.com/cockroachdb/pebble/blob/5fd7e15183fae374bd94a71857769be2adb15bd0/level_iter.go#L562)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

was working on it just now! pushed
</blockquote></details>

Nice, thanks!
___
*[`internal/base/comparer.go` line 128 at r3](https://reviewable.io/reviews/cockroachdb/pebble/3615#-NxxeZm62tl-rwH2FmXi:-NxxeZm62tl-rwH2FmXj:b-30vum5) ([raw file](https://github.com/cockroachdb/pebble/blob/f4944c97e86bcef63dea4704011be49f43d36321/internal/base/comparer.go#L128)):*
> ```Go
> // Prefix returns the prefix of the key k, using s to split the key.
> func (s Split) Prefix(k []byte) []byte {
> 	return k[:s(k)]
> ```

[nit] Do you see any downside to doing `k[:n:n]` just to be safe?

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3615)* status: 0 of 9 files reviewed, 4 unresolved discussions (waiting on @itsbilal and @jbowens)

___
*[`level_iter.go` line 563 at r2](https://reviewable.io/reviews/cockroachdb/pebble/3615#-NxxgbcF-f4U0F5ShDRV:-NxxgbcG3NHSy3pqL_KV:b8agte0) ([raw file](https://github.com/cockroachdb/pebble/blob/f47c1a770bc07297f512fc192c16ba925e52a5c1/level_iter.go#L563)):*
> ```Go
> 		// storage. See #3575.
> 		if l.prefix != nil && l.cmp(file.SmallestPointKey.UserKey[:l.split(file.SmallestPointKey.UserKey)], l.prefix) > 0 {
> 			return noFileLoaded
> ```

Does returning `noFileLoaded` have any implication on the `SeekGEFlags` based optimizations?

**Review by jbowens — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3615#-:-NxxkMYnCEmBWWYsJf-B:b-814g8k)* status: 0 of 9 files reviewed, 4 unresolved discussions (waiting on @itsbilal, @RaduBerinde, and @sumeerbhola)

___
*[`level_iter.go` line 563 at r2](https://reviewable.io/reviews/cockroachdb/pebble/3615#-NxxgbcF-f4U0F5ShDRV:-Nxxk90L7SMrqUwxlpAq:b-oc71eo) ([raw file](https://github.com/cockroachdb/pebble/blob/f47c1a770bc07297f512fc192c16ba925e52a5c1/level_iter.go#L563)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Does returning `noFileLoaded` have any implication on the `SeekGEFlags` based optimizations?
</blockquote></details>

Not directly; added a comment discussing TrySeekUsingNext. Since the file hasn't been loaded, a subsequent seek with TrySeekUsingNext()=true will disable TrySeekUsingNext on the sstable iterator seek
___
*[`internal/base/comparer.go` line 128 at r3](https://reviewable.io/reviews/cockroachdb/pebble/3615#-NxxeZm62tl-rwH2FmXi:-Nxxk6og1ZXVl2MHZ5tg:byzd987) ([raw file](https://github.com/cockroachdb/pebble/blob/f4944c97e86bcef63dea4704011be49f43d36321/internal/base/comparer.go#L128)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] Do you see any downside to doing `k[:n:n]` just to be safe?
</blockquote></details>

I don't, done!

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3615)* status: 0 of 9 files reviewed, 5 unresolved discussions (waiting on @itsbilal, @jbowens, and @RaduBerinde)

___
*[`level_iter.go` line 563 at r5](https://reviewable.io/reviews/cockroachdb/pebble/3615#-Nxxmji45IrQTr0lw-kx:-Nxxmji45IrQTr0lw-ky:bnfns8g) ([raw file](https://github.com/cockroachdb/pebble/blob/f1c55d46bee936359129196bea2324def7fbe245/level_iter.go#L563)):*
> ```Go
> 		// storage. See #3575.
> 		if l.prefix != nil && l.cmp(l.split.Prefix(file.SmallestPointKey.UserKey), l.prefix) > 0 {
> 			// Note that because we don't update l.iter, a subsequent call to
> ```

nit: should this say "because l.iter will be nil, ..."

And there's no issue with the `manifest.LevelIterator` and the `SeekGEFlags` either because we've stopped earlier, yes?

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3615)* status: 0 of 9 files reviewed, 5 unresolved discussions (waiting on @itsbilal, @RaduBerinde, and @sumeerbhola)

___
*[`level_iter.go` line 563 at r5](https://reviewable.io/reviews/cockroachdb/pebble/3615#-Nxxmji45IrQTr0lw-kx:-NxxryjV5np_75tZmxuA:b2nign6) ([raw file](https://github.com/cockroachdb/pebble/blob/f1c55d46bee936359129196bea2324def7fbe245/level_iter.go#L563)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nit: should this say "because l.iter will be nil, ..."

And there's no issue with the `manifest.LevelIterator` and the `SeekGEFlags` either because we've stopped earlier, yes?
</blockquote></details>

yes

**Pull request merged**
