### PR TITLE
db: add Iterator.SetOptions for modifying iterator options 

### PR DESCRIPTION
**Pull request by jbowens**
Add a SetOptions method to Iterator allowing a user to modify the IterOptions
of an existing iterator. This is intended to be used within CockroachDB for
modifying the key types and range key mask suffix of an existing Iterator.

The point iterator stack and range iterator stack both are initialized only
when needed. If no longer needed, the iterator stacks are preserved (in
`Iterator.pointIter` and `Iterator.rangeKey.rangeKeyIter`) but left
disconnected from the Iterator's root internal iterator. This allows the
existing iterator stack to be reused if the Iterator is switched back to
including a key type.

### CODE REVIEW

**Review by nicktrav — APPROVED** [review]
Nice! The metamorphic tests are :pinched_fingers: too. :lgtm: 

> Reviewed 1 of 1 files at r1, 11 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1601#-:-MyyE5Mw8HNIQeiIWTJh:b-9qzhl0)* status: all files reviewed, 3 unresolved discussions (waiting on @erikgrinaker, @jbowens, and @sumeerbhola)

___
*[iterator.go, line 1704 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1601#-Myy9GKS-owIZ6X0gboH:-Myy9GKS-owIZ6X0gboI:bnxtu06) ([raw file](https://github.com/cockroachdb/pebble/blob/e45b42059ab17e9dba8e307beda45a2317ccb294/iterator.go#L1704)):*
> ```Go
> 	i.hasPrefix = false
> 	i.iterKey = nil
> 	i.iterValue = nil
> ```

Fine to leave `err` set? I assume the next positioning method will clear it? Or are there operations one can call between `SetOptions` and the positioning method that could see the old error?
___
*[internal/metamorphic/generator.go, line 698 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1601#-MyyARHx9tau8NnPcPtS:-MyyARHx9tau8NnPcPtT:batpf4l) ([raw file](https://github.com/cockroachdb/pebble/blob/e45b42059ab17e9dba8e307beda45a2317ccb294/internal/metamorphic/generator.go#L698)):*
> ```Go
> 	iterID := g.liveIters.rand(g.rng)
> 
> 	// Generate a new key with a .1% probability.
> ```

Maybe this is overkill - some percentage change of retaining the current bounds? Not sure what the typical usage patterns will look like.
___
*[internal/metamorphic/generator.go, line 705 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1601#-MyyA-gi6wSbZxEbugc7:-MyyA-gi6wSbZxEbugc8:b-naezd) ([raw file](https://github.com/cockroachdb/pebble/blob/e45b42059ab17e9dba8e307beda45a2317ccb294/internal/metamorphic/generator.go#L705)):*
> ```Go
> 		lower, upper = upper, lower
> 	}
> 	if g.itersLastBounds == nil {
> ```

nit: should we just initialize this map in `newGenerator`? We do the "if nil, make" dance in `iterSetBounds` too.

**Review by erikgrinaker — APPROVED** [review]
API looks great, thanks! Are there any options that can/should not be set in this way? Also, consider adding a comment on the `Options` struct that any new options must also be handled in `SetOptions`.

**Review by sumeerbhola — APPROVED** [review]
non-test changes :lgtm: 
I like the generalization using SetOptions.

> Reviewed 1 of 1 files at r1, 5 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1601#-:-Mz1vU-G1Ysujq2H69tE:b-84kbgp)* status: all files reviewed, 6 unresolved discussions (waiting on @jbowens)

___
*[db.go, line 949 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1601#-Mz1qi2ZCc7flRiyo3Vw:-Mz1qi2ZCc7flRiyo3Vx:b-kkwf27) ([raw file](https://github.com/cockroachdb/pebble/blob/25b62c2237b40b1675a80dd35e9b1536138ec8c0/db.go#L949)):*
> ```Go
> 	} else {
> 		// We only need to read from memtables which contain sequence numbers older
> 		// than seqNum. Trim off newer sstables.
> ```

nit: newer memtables.
___
*[db.go, line 968 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1601#-Mz1rYH71p9ZlkDwZn6M:-Mz1rYH71p9ZlkDwZn6N:b-funatj) ([raw file](https://github.com/cockroachdb/pebble/blob/25b62c2237b40b1675a80dd35e9b1536138ec8c0/db.go#L968)):*
> ```Go
> 
> 	// For the in-memory prototype of range keys, wrap the merging iterator with
> 	// an interleaving iterator. The dbi.rangeKeysIter is an iterator into
> ```

nit: The db.rangeKey.rangeKeyIter is ...
___
*[iterator.go, line 1572 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1601#-Mz1sLrC5fa-thtBax2N:-Mz1sLrC5fa-thtBax2O:b-q99787) ([raw file](https://github.com/cockroachdb/pebble/blob/e45b42059ab17e9dba8e307beda45a2317ccb294/iterator.go#L1572)):*
> ```Go
> 		//
> 		// Calling Close on a closed internal iterator or fragment iterator is
> 		// allowed.
> ```

I'm confused by this comment. It seems to be saying that i.iter.Close() is not guaranteed to have closed these point and range iters, so we're going to make sure by closing them (possibly again). And then it says calling close again is not allowed. What am I missing?

**Review by nicktrav — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1601)* status: all files reviewed, 3 unresolved discussions (waiting on @jbowens)

**Review by jbowens — COMMENTED** [review]
TFTRs!


> Are there any options that can/should not be set in this way? 

Nope, they're all supported.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1601#-:-MzH3-gw8TCL3mpFeL4v:buytnam)* status: all files reviewed, 1 unresolved discussion (waiting on @sumeerbhola)

___
*[iterator.go, line 1572 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1601#-Mz1sLrC5fa-thtBax2N:-MzGyfU545tIDv8FeOAc:b7owysq) ([raw file](https://github.com/cockroachdb/pebble/blob/e45b42059ab17e9dba8e307beda45a2317ccb294/iterator.go#L1572)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I'm confused by this comment. It seems to be saying that i.iter.Close() is not guaranteed to have closed these point and range iters, so we're going to make sure by closing them (possibly again). And then it says calling close again is not allowed. What am I missing?
</blockquote></details>

I might be misreading, but I think it says that it _is_ allowed. I rephrased it to be more explicit in any case.
___
*[iterator.go, line 1704 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1601#-Myy9GKS-owIZ6X0gboH:-MzH-0sm-AN2_9SNUlO3:by9j9nz) ([raw file](https://github.com/cockroachdb/pebble/blob/e45b42059ab17e9dba8e307beda45a2317ccb294/iterator.go#L1704)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

Fine to leave `err` set? I assume the next positioning method will clear it? Or are there operations one can call between `SetOptions` and the positioning method that could see the old error?
</blockquote></details>

I'll clear it—it is possible for `SetOptions` itself to generate an error that is only surfaced through `i.iter.Error()`, and clearing gives the user an opportunity to check for it before positioning the iterator.
___
*[internal/metamorphic/generator.go, line 698 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1601#-MyyARHx9tau8NnPcPtS:-MzH0XOZ4rS-kBzXHwgN:b-48vilg) ([raw file](https://github.com/cockroachdb/pebble/blob/e45b42059ab17e9dba8e307beda45a2317ccb294/internal/metamorphic/generator.go#L698)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

Maybe this is overkill - some percentage change of retaining the current bounds? Not sure what the typical usage patterns will look like.
</blockquote></details>

Good call, done.

**Pull request merged**
