### PR TITLE
[WIP] Merger Finish "includesBase" argument

### PR DESCRIPTION
**Pull request by 256dpi**
As discussed in #622.

### CODE REVIEW

**Comment by petermattis** [comment]
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/625)

**Comment by 256dpi** [comment]
> The includesBase argument looks fine, but please move this to a separate PR. I think change != newStripe is the correct approach, but we'll really want to test the various scenarios. See testdata/compaction_iter for existing test cases of the handling of merges by compactionIter. Perhaps we can extend the merge operator used in that test to indicate whether Finish(true) or Finish(false) was called.

I'll look into it.

**Comment by 256dpi** [comment]
I added the comments and tried the suggested testing approach. For now, I just copied the results to the file, in order to make the tests pass. Could you verify that the expectations are correct?

**Comment by 256dpi** [comment]
I added the suggested cosmetics and squashed the PR. But, I'm struggling to figure out how to detect the other cases where "includeBase" would be true. Since it is not crucial to detect these properly we could leave it at that for now. However, if you're inclined in doing it right I would be happy if somebody could take this over that has more knowledge of the pebble internals.

**Pull request closed without merging**
