### PR TITLE
sstable: clean up; drop support for range deletion v1 blocks

### PR DESCRIPTION
**Pull request by jbowens**
**sstable/rowblk: replace RawWriter with methods on rowblk.Writer**

**sstable: add metaIndexWriter**

Add a helper metaIndexWriter type that handles sorting the meta index keys so
Writer.Close doesn't need to maintain a delicate ordering.

**sstable: drop support for v1 range deletion blocks**

The v1 range deletion blocks predate Pebble. Our format major versions that
required compaction of all pre-Pebble sstables ensure that no v1 range deletion
blocks should exist in the wild without an accompanying v2 range deletion
block. This required regeneration of the sstable fixtures.

**sstable: add layoutWriter**
    
Refactor management of block handles, file size and the meta index into a
layoutWriter type responsible for writing blocks to durable storage. This will
allow the columnar block format to share logic.

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Is this true even of older backups? (CC @dt) I remember trying to deprecate some table formats before and I ended up reverting it because of backup.

**Review by jbowens — COMMENTED** [review]
IIRC, range deletions are never written to backup sstables. I also thought backup compatibility has some bound. The last we would've written these sstables would've been with rocksDB in 20.1. Let's wait for @dt for confirmation tho

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3710#-:-O0Ljooe-ey8cZZTg0MQ:bp2tgi6)* status: 0 of 25 files reviewed, all discussions resolved (waiting on @aadityasondhi and @RaduBerinde)

**Review by jbowens — COMMENTED** [review]
Got David's confirmation in the dr-eng channel

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3710#-:-O0PdgW42nRZT82wnAm4:bzeeh22)* status: 0 of 30 files reviewed, all discussions resolved (waiting on @aadityasondhi and @RaduBerinde)

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3710#-:-O0QFIpOARPYuq60U2yY:bnfp4nl)* status: 0 of 30 files reviewed, 7 unresolved discussions (waiting on @aadityasondhi and @jbowens)

___
*[`sstable/layout.go` line 311 at r4](https://reviewable.io/reviews/cockroachdb/pebble/3710#-O0QBuD29uHfiId05kSB:-O0QBuD29uHfiId05kSC:b-bnhbxq) ([raw file](https://github.com/cockroachdb/pebble/blob/3b92b9378bd18b7da76afa0acac2ecba5cc08334/sstable/layout.go#L311)):*
> ```Go
> 	// sstables with a two-level index, the last update will set the two-level
> 	// index.
> 	indexHandle block.Handle
> ```

[nit] maybe `lastIndexHandle` or even `lastIndexBlockHandle`
___
*[`sstable/layout.go` line 314 at r4](https://reviewable.io/reviews/cockroachdb/pebble/3710#-O0QDa8i4sfeLj4gj00m:-O0QDa8i4sfeLj4gj00n:bf8obzz) ([raw file](https://github.com/cockroachdb/pebble/blob/3b92b9378bd18b7da76afa0acac2ecba5cc08334/sstable/layout.go#L314)):*
> ```Go
> 	handles     []metaIndexHandle
> 	handlesBuf  bytealloc.A
> 	tmp         [blockHandleLikelyMaxLen]byte
> ```

[nit] This constant doesn't seem right since we never include arbitrary properties, and we assume it's always large enough. I think we want something like `blockHandleMaxLenWithoutProperties` but that is also big enough for value block handles.
___
*[`sstable/layout.go` line 333 at r4](https://reviewable.io/reviews/cockroachdb/pebble/3710#-O0QCdWT6sQNG4HtdRzJ:-O0QCdWT6sQNG4HtdRzK:b7v2t9f) ([raw file](https://github.com/cockroachdb/pebble/blob/3b92b9378bd18b7da76afa0acac2ecba5cc08334/sstable/layout.go#L333)):*
> ```Go
> type metaIndexHandle struct {
> 	key   string
> 	value []byte
> ```

[nit] // value containes the encoded block handle
___
*[`sstable/layout.go` line 343 at r4](https://reviewable.io/reviews/cockroachdb/pebble/3710#-O0QCmkM6G97TTzxpMfM:-O0QCmkM6G97TTzxpMfN:b-lxqw7r) ([raw file](https://github.com/cockroachdb/pebble/blob/3b92b9378bd18b7da76afa0acac2ecba5cc08334/sstable/layout.go#L343)):*
> ```Go
> }
> 
> func (w *layoutWriter) writeDataBlock(b []byte, buf *blockBuf) (block.Handle, error) {
> ```

[nit] the methods that are used by other types should be capitalized
___
*[`sstable/layout.go` line 470 at r4](https://reviewable.io/reviews/cockroachdb/pebble/3710#-O0QDIco-Fp3NPVtkYyA:-O0QDIco-Fp3NPVtkYyB:bp3fmpb) ([raw file](https://github.com/cockroachdb/pebble/blob/3b92b9378bd18b7da76afa0acac2ecba5cc08334/sstable/layout.go#L470)):*
> ```Go
> func (w *layoutWriter) clearFromCache(offset uint64) {
> 	if w.cacheID != 0 && w.fileNum != 0 {
> 		// Remove the block being written from the cache. This provides defense in
> ```

[nit] this first paragraph an be moved to a method comment
___
*[`sstable/value_block.go` line 580 at r4](https://reviewable.io/reviews/cockroachdb/pebble/3710#-O0QEhZJ1L3au4ArMksB:-O0QEhZJ1L3au4ArMksC:bw0z57r) ([raw file](https://github.com/cockroachdb/pebble/blob/3b92b9378bd18b7da76afa0acac2ecba5cc08334/sstable/value_block.go#L580)):*
> ```Go
> 	}
> 	var err error
> 	if n > 0 {
> ```

We already handled the `n==0` case above.
___
*[`sstable/writer.go` line 2371 at r2](https://reviewable.io/reviews/cockroachdb/pebble/3710#-O0P5GTZ3Heoz3ew2pfB:-O0P5GTZ3Heoz3ew2pfC:b2yjc0) ([raw file](https://github.com/cockroachdb/pebble/blob/a9500d963be3f6437547666b085e5386ff2722e4/sstable/writer.go#L2371)):*
> ```Go
> }
> 
> type metaIndexWriter struct {
> ```

This is great. It would be nice if it provided higher-level functions (`addRangeDel`, `addFilter`, etc); can be a TODO.

**Review by jbowens — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3710#-:-O0QZGRuCKTs-lICP8-y:b-814g8k)* status: 0 of 30 files reviewed, 4 unresolved discussions (waiting on @aadityasondhi and @RaduBerinde)

___
*[`sstable/layout.go` line 311 at r4](https://reviewable.io/reviews/cockroachdb/pebble/3710#-O0QBuD29uHfiId05kSB:-O0QQwz898Kt6pHeaNC2:bb6un1j) ([raw file](https://github.com/cockroachdb/pebble/blob/3b92b9378bd18b7da76afa0acac2ecba5cc08334/sstable/layout.go#L311)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] maybe `lastIndexHandle` or even `lastIndexBlockHandle`
</blockquote></details>

Done
___
*[`sstable/layout.go` line 314 at r4](https://reviewable.io/reviews/cockroachdb/pebble/3710#-O0QDa8i4sfeLj4gj00m:-O0QQxpl-biZdl4lF6i7:b-1cix09) ([raw file](https://github.com/cockroachdb/pebble/blob/3b92b9378bd18b7da76afa0acac2ecba5cc08334/sstable/layout.go#L314)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] This constant doesn't seem right since we never include arbitrary properties, and we assume it's always large enough. I think we want something like `blockHandleMaxLenWithoutProperties` but that is also big enough for value block handles.
</blockquote></details>

Updated to `valueBlocksIndexHandleMaxLen`
___
*[`sstable/layout.go` line 333 at r4](https://reviewable.io/reviews/cockroachdb/pebble/3710#-O0QCdWT6sQNG4HtdRzJ:-O0QRdG_-yFgHIjgtAtS:b-z8fp94) ([raw file](https://github.com/cockroachdb/pebble/blob/3b92b9378bd18b7da76afa0acac2ecba5cc08334/sstable/layout.go#L333)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] // value containes the encoded block handle
</blockquote></details>

updated the field name to `encodedBlockHandle`
___
*[`sstable/layout.go` line 343 at r4](https://reviewable.io/reviews/cockroachdb/pebble/3710#-O0QCmkM6G97TTzxpMfM:-O0QUxo3-rZCB5kWJynz:bb6un1j) ([raw file](https://github.com/cockroachdb/pebble/blob/3b92b9378bd18b7da76afa0acac2ecba5cc08334/sstable/layout.go#L343)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] the methods that are used by other types should be capitalized
</blockquote></details>

Done
___
*[`sstable/layout.go` line 470 at r4](https://reviewable.io/reviews/cockroachdb/pebble/3710#-O0QDIco-Fp3NPVtkYyA:-O0QUyqP9krRwzf4tGTK:bb6un1j) ([raw file](https://github.com/cockroachdb/pebble/blob/3b92b9378bd18b7da76afa0acac2ecba5cc08334/sstable/layout.go#L470)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] this first paragraph an be moved to a method comment
</blockquote></details>

Done
___
*[`sstable/value_block.go` line 580 at r4](https://reviewable.io/reviews/cockroachdb/pebble/3710#-O0QEhZJ1L3au4ArMksB:-O0QV8fkDdXlYzWn-a9h:b6zrrkh) ([raw file](https://github.com/cockroachdb/pebble/blob/3b92b9378bd18b7da76afa0acac2ecba5cc08334/sstable/value_block.go#L580)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

We already handled the `n==0` case above.
</blockquote></details>

Good catch.

**Pull request merged**
