### PR TITLE
db: keep track of virtual sstable count in metrics

### PR DESCRIPTION
**Pull request by bananabrick**
This pr adds an int to the LevelMetadata and incrementally
keeps track of the number of virtual sstables in the level.

Also adds a field in the LevelMetrics to keep track of virtual
sstables, and print the virtual sstables as part of the metrics
string.

### CODE REVIEW

**Comment by bananabrick** [comment]
First commit from https://github.com/cockroachdb/pebble/pull/2957

**Review by bananabrick — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2961)* status: 0 of 9 files reviewed, 1 unresolved discussion

___
*[`version_set.go` line 603 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2961#-NfhU1A50OpBqF4ezfCa:-NfhU1A50OpBqF4ezfCb:b-2oa9j8) ([raw file](https://github.com/cockroachdb/pebble/blob/aa077af625936fb6b52d8efdd1a8bcf7070a1509/version_set.go#L603)):*
> ```Go
> 		}
> 		if invariants.Enabled {
> 			if count := int64(newVersion.Levels[i].Len()); l.NumFiles != count {
> ```

This check was irrelevant.

**Review by RaduBerinde — COMMENTED** [review]
Changes LGTM. One thing - the log tool has a regex for the `total` line to obtain the read-amp. I think it will continue to work but we should update the tests.
https://github.com/cockroachdb/pebble/blob/master/tool/logs/testdata/compactions-latest#L82

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2961#-:-NfqCSii2cv5KKOb2E7T:b-cq5kpz)* status: 0 of 9 files reviewed, 1 unresolved discussion

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

Ok to merge once the logs testdata is updated.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2961#-:-NfqDAOGCOXutCKPESnz:bxnq3cy)* status: 0 of 9 files reviewed, 1 unresolved discussion

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2961)* status: 0 of 10 files reviewed, 2 unresolved discussions (waiting on @bananabrick)

___
*[`tool/logs/testdata/compactions-latest` line 91 at r4](https://reviewable.io/reviews/cockroachdb/pebble/2961#-NfrLddq3TVrGdMQFv0D:-NfrLddq3TVrGdMQFv0E:b-muehje) ([raw file](https://github.com/cockroachdb/pebble/blob/643a0d43c9202c73bb92b527e8dbcc6a0a65a49b/tool/logs/testdata/compactions-latest#L91)):*
> ```
> I211215 00:00:15.000000 434 kv/kvserver/store.go:3251 ⋮ [n1,s1] 31356
>       |                            |       |       |   ingested   |     moved    |    written   |       |    amp
> level | tables  size val-bl vtabes | score |   in  | tables  size | tables  size | tables  size |  read |   r   w
> ```

vtables

**Review by bananabrick — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2961)* status: 0 of 10 files reviewed, 2 unresolved discussions (waiting on @RaduBerinde)

___
*[`tool/logs/testdata/compactions-latest` line 91 at r4](https://reviewable.io/reviews/cockroachdb/pebble/2961#-NfrLddq3TVrGdMQFv0D:-NfrNGFhAryWIxENe47a:b-3eywoa) ([raw file](https://github.com/cockroachdb/pebble/blob/643a0d43c9202c73bb92b527e8dbcc6a0a65a49b/tool/logs/testdata/compactions-latest#L91)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

vtables
</blockquote></details>

oops, fixed.

**Review by RaduBerinde — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 8 files at r2, 2 of 3 files at r3, 1 of 3 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2961#-:-NfrNlJP3C8MgMPzYKTy:bnfp4nl)* status: 9 of 10 files reviewed, 2 unresolved discussions

**Pull request merged**
