### PR TITLE
db: deprecate older format versions

### PR DESCRIPTION
**Pull request by RaduBerinde**
This change deprecates format versions below `FormatFlushableIngest`
(the 23.1 version) and sstable formats below `TableFormatPebblev1`.

As part of this change, we remove code that deals with split keys;
further simplifications will be made separately (e.g. removing atomic
unit logic, simplifying the truncation iterator).

We also remove all code related to the `CURRENT` file.

The plan is to merge this after we tag a `v1.0.0` release, which will
for the time being be the recommended version series for users other
than CockroachDB.

Informs #3064

### CODE REVIEW

**Review by jbowens — COMMENTED** [review]
Looking great, thanks for doing this! :put_litter_in_its_place: Just had a few small questions

> Reviewed 71 of 80 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3152#-:-NlePHm69Vf0pGoZj9oV:b-v28cio)* status: all files reviewed, 4 unresolved discussions (waiting on @RaduBerinde and @sumeerbhola)

___
*[`format_major_version.go` line 139 at r2](https://reviewable.io/reviews/cockroachdb/pebble/3152#-NleKd53EsFT_g0jyThu:-NleKd53EsFT_g0jyThv:b-j1ncu5) ([raw file](https://github.com/cockroachdb/pebble/blob/6e9f783cc81277ac27cce5bc09d21a95c75f41da/format_major_version.go#L139)):*
> ```Go
> 		FormatSSTableValueBlocks
> */
> const numDeprecatedVersions = 12
> ```

nit: maybe we should keep lines within the `const` stanza to increment the `iota` automatically? Could do something like:

```
const (
    // FormatMostCompatible (deprecated) ...
    _ = iota

    // FormatVersioned (deprecated) ...
   _


```
___
*[`open.go` line 148 at r2](https://reviewable.io/reviews/cockroachdb/pebble/3152#-NleM6Gq4MnzjL6qPyn2:-NleM6Gq4MnzjL6qPyn3:b62ip8p) ([raw file](https://github.com/cockroachdb/pebble/blob/6e9f783cc81277ac27cce5bc09d21a95c75f41da/open.go#L148)):*
> ```Go
> 		//
> 		// To error in the first case, we set ErrorIfPristine.
> 		opts.ErrorIfNotPristine = true
> ```

I'm forgetting, will this error if there's a `CURRENT` file?
___
*[`compaction_iter_test.go` line 97 at r2](https://reviewable.io/reviews/cockroachdb/pebble/3152#-NleO3q53owHRFfCRnSm:-NleO3q53owHRFfCRnSn:b-4xs2d6) ([raw file](https://github.com/cockroachdb/pebble/blob/288bf0fb7ec9b59df57ec3fe69a35bc7fb6a27b9/compaction_iter_test.go#L97)):*
> ```Go
> 		}
> 		if formatVersion < FormatDeleteSizedAndObsolete {
> 			return "testdata/compaction_iter_set_with_del"
> ```

should we keep this one for format major versions earlier than `FormatDeleteSizedAndObsolete`?
___
*[`db_test.go` line 79 at r2](https://reviewable.io/reviews/cockroachdb/pebble/3152#-NleOeeoDPAJc9hiTzVu:-NleOeeoDPAJc9hiTzVv:bec31pb) ([raw file](https://github.com/cockroachdb/pebble/blob/6e9f783cc81277ac27cce5bc09d21a95c75f41da/db_test.go#L79)):*
> ```Go
> 
> func TestBasicReads(t *testing.T) {
> 	t.Skip("TODO")
> ```

still intended to be skipped?

**Review by RaduBerinde — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3152#-:-NlfVi6325HJenVtv6WZ:b-814g8k)* status: 77 of 81 files reviewed, 4 unresolved discussions (waiting on @jbowens and @sumeerbhola)

___
*[`format_major_version.go` line 139 at r2](https://reviewable.io/reviews/cockroachdb/pebble/3152#-NleKd53EsFT_g0jyThu:-NlfV1akDPhI_bMRAy-0:b-fznogt) ([raw file](https://github.com/cockroachdb/pebble/blob/6e9f783cc81277ac27cce5bc09d21a95c75f41da/format_major_version.go#L139)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

nit: maybe we should keep lines within the `const` stanza to increment the `iota` automatically? Could do something like:

```
const (
    // FormatMostCompatible (deprecated) ...
    _ = iota

    // FormatVersioned (deprecated) ...
   _


```
</blockquote></details>

Good idea, done.
___
*[`open.go` line 148 at r2](https://reviewable.io/reviews/cockroachdb/pebble/3152#-NleM6Gq4MnzjL6qPyn2:-NlfV43u7LaEsBk1GEeK:bmp2kno) ([raw file](https://github.com/cockroachdb/pebble/blob/6e9f783cc81277ac27cce5bc09d21a95c75f41da/open.go#L148)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

I'm forgetting, will this error if there's a `CURRENT` file?
</blockquote></details>

No, it will error if any data operations have been performed.
___
*[`compaction_iter_test.go` line 97 at r2](https://reviewable.io/reviews/cockroachdb/pebble/3152#-NleO3q53owHRFfCRnSm:-NlfVaACC1C-5M09wm1X:bves986) ([raw file](https://github.com/cockroachdb/pebble/blob/288bf0fb7ec9b59df57ec3fe69a35bc7fb6a27b9/compaction_iter_test.go#L97)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

should we keep this one for format major versions earlier than `FormatDeleteSizedAndObsolete`?
</blockquote></details>

Good catch! Fixed.
___
*[`db_test.go` line 79 at r2](https://reviewable.io/reviews/cockroachdb/pebble/3152#-NleOeeoDPAJc9hiTzVu:-NlfVh2XA2cNvZOA9Ey0:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/6e9f783cc81277ac27cce5bc09d21a95c75f41da/db_test.go#L79)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

still intended to be skipped?
</blockquote></details>

Done.

**Comment by RaduBerinde** [comment]
I think this is ready to merge when I get an approval. Thanks!

**Review by sumeerbhola — APPROVED** [review]
Couple of nits only. Thanks for doing this!
:lgtm: 

> Reviewed 11 of 80 files at r1, 4 of 9 files at r2, 2 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3152#-:-Nlxp_ob-o-rqgGGAEyf:biws164)* status: 79 of 81 files reviewed, 6 unresolved discussions (waiting on @jbowens and @RaduBerinde)

___
*[`format_major_version.go` line 139 at r2](https://reviewable.io/reviews/cockroachdb/pebble/3152#-NleKd53EsFT_g0jyThu:-NlxmPYo-40wp7JrpoE1:b-uyswqj) ([raw file](https://github.com/cockroachdb/pebble/blob/6e9f783cc81277ac27cce5bc09d21a95c75f41da/format_major_version.go#L139)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Good idea, done.
</blockquote></details>

can we add a trivial unit test to assert the actual numbers to ensure we don't renumber something by mistake?
___
*[`open.go` line 147 at r3](https://reviewable.io/reviews/cockroachdb/pebble/3152#-NlxoNvY2ERDWaay_uQT:-NlxoNvY2ERDWaay_uQU:b-yui9in) ([raw file](https://github.com/cockroachdb/pebble/blob/8e0081d1fe3bd601e1e7655156005671c51045a0/open.go#L147)):*
> ```Go
> 		//  - we are retrying a failed creation.
> 		//
> 		// To error in the first case, we set ErrorIfPristine.
> ```

nit: should this say "... set ErrorIfNotPristine"?
___
*[`open.go` line 1022 at r3](https://reviewable.io/reviews/cockroachdb/pebble/3152#-NlxogjJBgC2MRg4XnPw:-NlxogjJBgC2MRg4XnPx:bdblvt0) ([raw file](https://github.com/cockroachdb/pebble/blob/8e0081d1fe3bd601e1e7655156005671c51045a0/open.go#L1022)):*
> ```Go
> 
> 	// mem is nil here.
> 	if !d.opts.ReadOnly && batchesReplayed > 0 {
> ```

curious about the addition of `batchesReplayed > 0` here -- was this an existing bug?

**Review by RaduBerinde — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3152#-:-Nlxtz-77kNdxmATDQWW:b-814g8k)* status: 76 of 81 files reviewed, 4 unresolved discussions (waiting on @jbowens and @sumeerbhola)

___
*[`open.go` line 1022 at r3](https://reviewable.io/reviews/cockroachdb/pebble/3152#-NlxogjJBgC2MRg4XnPw:-NlxsdPe6LkrXFzJB0gV:b-q1qn4d) ([raw file](https://github.com/cockroachdb/pebble/blob/8e0081d1fe3bd601e1e7655156005671c51045a0/open.go#L1022)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

curious about the addition of `batchesReplayed > 0` here -- was this an existing bug?
</blockquote></details>

I don't think it was a bug, just an unnecessary operation. I was hitting some panics in this code path while I was developing the change and adding the check helped. If I remove it now, the tests pass, but it makes sense to keep it.

**Pull request merged**
