### PR TITLE
valblk: fix Writer.Size() performance

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### sstasble: improve writer benchmark

Add varying `vals-per-key` parameter and add an `EstimatedSize()` call
per key (which happens during compactions).

#### valblk: fix Writer.Size() performance

`Writer.Size()` unnecessarily loops through all the blocks instead of
using `totalBlockBytes`. This seems like an oversight: we only append
to `blocks` in `compressAndFlush` where we also update
`totalBlockBytes`. I verified that in all Pebble tests these values are
the same, using `if sz != w.totalBlockBytes { panic() }`.

```
name                                                                                                        old time/op    new time/op     delta
WriterWithVersions/vals-per-key=1/format=(Pebble,v5)/block=32KB/filter=false/compression=NoCompression        77.2ms ± 1%     76.6ms ± 0%    -0.70%  (p=0.008 n=5+5)
WriterWithVersions/vals-per-key=10/format=(Pebble,v5)/block=32KB/filter=false/compression=NoCompression        752ms ± 0%       99ms ± 1%   -86.83%  (p=0.008 n=5+5)
WriterWithVersions/vals-per-key=10000/format=(Pebble,v5)/block=32KB/filter=false/compression=NoCompression     908ms ± 0%      103ms ± 0%   -88.64%  (p=0.008 n=5+5)

name                                                                                                        old speed      new speed       delta
WriterWithVersions/vals-per-key=1/format=(Pebble,v5)/block=32KB/filter=false/compression=NoCompression       462MB/s ± 1%    466MB/s ± 0%    +0.70%  (p=0.008 n=5+5)
WriterWithVersions/vals-per-key=10/format=(Pebble,v5)/block=32KB/filter=false/compression=NoCompression     53.0MB/s ± 0%  402.7MB/s ± 1%  +659.47%  (p=0.008 n=5+5)
WriterWithVersions/vals-per-key=10000/format=(Pebble,v5)/block=32KB/filter=false/compression=NoCompression  49.1MB/s ± 0%  431.8MB/s ± 0%  +780.16%  (p=0.008 n=5+5)
```

### CODE REVIEW

**Comment by RaduBerinde** [comment]
I will backport to 24.3 (for when we add the cluster setting to enable value blocks).

**Comment by RaduBerinde** [comment]
I confirmed this is only an issue with `v5`:
```
BenchmarkWriterWithVersions/vals-per-key=10/format=(Pebble,v2)/block=32KB/filter=false/compression=NoCompression                      19          59592377 ns/op         660.38 MB/s
BenchmarkWriterWithVersions/vals-per-key=10/format=(Pebble,v3)/block=32KB/filter=false/compression=NoCompression                      12          94971892 ns/op         484.55 MB/s
BenchmarkWriterWithVersions/vals-per-key=10/format=(Pebble,v5)/block=32KB/filter=false/compression=NoCompression                       2         757362896 ns/op          52.63 MB/s
```

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/4205#-:-OEQSVgg5ghD5JOYOmQj:bg7igkv)* status: all files reviewed, 1 unresolved discussion (waiting on @jbowens and @RaduBerinde)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/cockroachdb/pebble/4205#-OEQPzCx2miJKNs-UZ9G:-OEQPzCx2miJKNs-UZ9H:b-rx0yr0):*
nit: sstable

**Review by RaduBerinde — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/4205#-:-OER882Q9h5zZvSkcyyk:b-814g8k)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jbowens)

**Pull request merged**
