### PR TITLE
WIP - meta: add sequence generator; add SET -> DEL -> SINGLEDEL sequence

### PR DESCRIPTION
**Pull request by nicktrav**
This first commit in this PR adds the concept of a "sequence generator" to produce random sequences governed by a state machine.

The second adds a sequence to reproduce the bug we were seeing in cockroachdb/cockroach#69414.

### CODE REVIEW

**Comment by nicktrav** [comment]
Marking this as WIP, as we probably don't want to merge the second commit until we work out whether this needs to be fixed at the pebble layer (in which case we'll want the fix to accompany the addition of the sequence).

**Review by nicktrav — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1254)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @sumeerbhola)

___
*[internal/metamorphic/scenario.go, line 18 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1254#-Mj1MsUSAe5ZJmWHLRlP:-Mj1MsUSAe5ZJmWHLRlQ:bth94uy) ([raw file](https://github.com/cockroachdb/pebble/blob/bc89d4072bdc5731dd47bcb3c030ff268657940e/internal/metamorphic/scenario.go#L18)):*
> ```Go
> // fetching the key after it has been single-deleted.
> //
> // This sequenceGenerator is regression test for cockroachdb/cockroach#69414.
> ```

At this SHA, we can force a metamorphic test failure with seed `1631054105813493000`.

**Review by nicktrav — COMMENTED** [review]
Reading cockroachdb/cockroach#69891, we can probably save the second commit here for when the final item in that issue is merged into pebble, which will serve as a regression test.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1254#-:-Mj1SKrHBJEhNwS17eO5:b-9koviq)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @sumeerbhola)

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1254)* status: 4 of 6 files reviewed, 3 unresolved discussions (waiting on @nicktrav)

___
*[internal/metamorphic/scenario.go, line 20 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1254#-Mj5dF-L2o5-zLMi5P_v:-Mj5dF-L2o5-zLMi5P_w:b-tbssrd) ([raw file](https://github.com/cockroachdb/pebble/blob/bc89d4072bdc5731dd47bcb3c030ff268657940e/internal/metamorphic/scenario.go#L20)):*
> ```Go
> // This sequenceGenerator is regression test for cockroachdb/cockroach#69414.
> func makeDelToSingleDelSequence(key []byte, valueFn func() []byte) *sequenceGenerator {
> 	reader, writer := makeObjID(dbTag, 0), makeObjID(dbTag, 0)
> ```

I see why this state machine seems simpler than tracking key states.
- Should this be setup such that keys used in such sequence generators are never to be used for writes by the usual operations. They can of course be used for reads.
- This restricts us to performing operations on the DB directly since it avoids the complexity of tracking the key through various writers. Is there a way to make this more sophisticated without sacrificing the simplicity?

I would like to see a code attempt at tracking the state of keys in a central place, as an alternative, and see if the complexity of that is not too high (my comment in #1248)
___
*[internal/metamorphic/scenario.go, line 24 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1254#-Mj5cGX_22f8Jpgl21Qd:-Mj5cGXaBHjYOC_dlqeF:b60rqyc) ([raw file](https://github.com/cockroachdb/pebble/blob/bc89d4072bdc5731dd47bcb3c030ff268657940e/internal/metamorphic/scenario.go#L24)):*
> ```Go
> 	var statePrev opType
> 	var doneDel, doneSingleDel bool
> 	var setCount, trailingGetCount int
> ```

I wonder if the state management in this code would be easier to read if this were a struct implementing an interface and the interface was what was driven by the `sequenceGenerator`. There is clearly some shared state that these funcs need and it is being provided by the surrounding environment, which is less readable than if these were methods on a struct.

**Comment by nicktrav** [comment]
Closing this out, as we have the `keyManager` abstraction now.

**Pull request closed without merging**
