### PR TITLE
base: add InternalKeyKindForSeek alias

### PR DESCRIPTION
**Pull request by nicktrav**
Currently, Pebble uses `base.InternalKeyKindMax`, with corresponding
integer value of `17` when writing keys to an index block of an sstable.
This matches the RocksDB on-disk format (at least in versions prior to
`6.11.4`).

The `base.InternalKeyKindMax` constant is effectively an alias for the
maximum usable key kind. The true value corresponds to RocksDB's
[`kTypeBlobIndex`][1]. RocksDB additionally references the constant
[`kValueTypeForSeek`][2] when writing out separator or successor keys
into an index block. In versions prior to `6.11.4`, this constant points
to `kTypeBlobIndex`.

Rather than directly referring to `InternalKeyKindMax` when writing keys
into an index block, mimic the RocksDB behavior of using the value
pointed to by an additional constant, `base.InternalKeyKindForSeek`,
which is an alias for `base.InternalKeyKindBlobIndex` (which was
previously disabled).

Uncoupling `base.InternalKeyKindMax` from the value `17` allows the
maximum allowable key type to be increased in the future, in line with
the comment associated with the constant, without affecting the values
written to sstable index blocks.

Split existing references to `InternalKeyKindMax` into use-cases that
are for "seeking", and those that are for "checking validity of keys".
For seeking, the new `InternalKeyKindForSeek` is used. For validation,
the existing use of `InternalKeyKindMax` remains.

Remove the string value `MAX` from the slice and map of values to
strings, and replace with `BLOBINDEX`, which reflects the on-disk key
type, rather than the alias.

[1]: https://github.com/facebook/rocksdb/blob/8df334342e7b014fb21c309236f2b9aeacf8a653/db/dbformat.h#L62
[2]: https://github.com/facebook/rocksdb/blob/1482c8697c260cc12f7fce9f15401a85330d2ff1/db/dbformat.cc#L26

### CODE REVIEW

**Comment by nicktrav** [comment]
I have also confirmed that the failing tests from #1261 are working after applying this change.

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> Reviewed 2 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1270)* status: 2 of 9 files reviewed, 1 unresolved discussion (waiting on @jbowens, @nicktrav, and @petermattis)

___
*[internal/base/internal.go, line 37 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1270#-MjfF4Ff-5aH-Ygron_u:-MjfF4Ff-5aH-Ygron_v:bsvk4wd) ([raw file](https://github.com/cockroachdb/pebble/blob/a504154b346e084d8b51f6c8aa279495d3f38723/internal/base/internal.go#L37)):*
> ```Go
> 	InternalKeyKindRangeDelete = 15
> 	// InternalKeyKindColumnFamilyBlobIndex                    = 16
> 	InternalKeyKindBlobIndex = 17
> ```

I'm not sure I fully understand these changes. We have the following use cases:
- For constructing either side of a span [internal-start, internal-end) given [user-start, user-end): It should be using `InternalKeyKindMax` that adjusts when we add new key kinds that are not backwards compatible. This comes up in SeekGE, SeekLT and for the inclusive start key for a compaction (the end key is also inclusive for compactions so we use base.MakeInternalKey(user-end, 0, 0)). I think we also need a code comment that explains this.
- For separator and successor: any key kind suffices. We just need it to be stable.

So I am surprised to see:
`InternalKeyKindForSeek InternalKeyKind = InternalKeyKindBlobIndex`.

Shouldn't this be
`InternalKeyKindThatSortsFirst InternalKeyKind = InternalKeyKindMax`

And instead of adding back a key kind named "BlobIndex", which doesn't have a meaning in Pebble,  I'd prefer to call it
`InternalKeyKindForSeparator = 17`
It doesn't really need to be reserved, and for now we can use "SEPARATOR" as the string name for the tests.
I don't actually care whether we reserve it or not -- if we don't we can undo the string name change and rewrite the datadriven tests when we introduce SETWITHDEL.

Am I missing something?

**Review by nicktrav — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1270)* status: 2 of 9 files reviewed, 1 unresolved discussion (waiting on @jbowens and @petermattis)

___
*[internal/base/internal.go, line 37 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1270#-MjfF4Ff-5aH-Ygron_u:-MjfOvIYEbK2uDg5u5iR:b-bdhkl7) ([raw file](https://github.com/cockroachdb/pebble/blob/a504154b346e084d8b51f6c8aa279495d3f38723/internal/base/internal.go#L37)):*
> Am I missing something?

I think it's more just my lack of historical context. Here's how I currently see it:

>So I am surprised to see:
>InternalKeyKindForSeek InternalKeyKind = InternalKeyKindBlobIndex.

Surprising, but [this is actually what RocksDB is doing](https://github.com/facebook/rocksdb/blob/1482c8697c260cc12f7fce9f15401a85330d2ff1/db/dbformat.cc#L26), which was the inspiration for this PR:

```
// kValueTypeForSeek defines the ValueType that should be passed when
// constructing a ParsedInternalKey object for seeking to a particular
// sequence number (since we sort sequence numbers in decreasing order
// and the value type is embedded as the low 8 bits in the sequence
// number in internal keys, we need to use the highest-numbered
// ValueType, not the lowest).
const ValueType kValueTypeForSeek = kTypeBlobIndex;
```

It then [uses this alias when writing out index blocks](https://github.com/facebook/rocksdb/blob/1482c8697c260cc12f7fce9f15401a85330d2ff1/db/dbformat.cc#L137-L169) (thanks @jbowens for the find). For index blocks, to your point, the important part is that the key is stable, as opposed to being the max (in fact, at the same SHA, [that alias is NOT the max key type in RocksDB](https://github.com/facebook/rocksdb/blob/1482c8697c260cc12f7fce9f15401a85330d2ff1/db/dbformat.h#L62)).

> And instead of adding back a key kind named "BlobIndex", which doesn't have a meaning in Pebble, I'd prefer to call it
>InternalKeyKindForSeparator = 17

I'm not opposed this. But it does seem confusing (at least to me, given my limited knowledge of the compatibility requirements) to be resurrecting RocksDB values and then rebranding / reusing them for other purposes.

The intention of the PR was to bring Pebble more in-line with what RocksDB is doing, which allows us to avoid having to regenerate the sstable fixtures. If we've gone past the point of no return for RocksDB / Pebble compatibility, that seems fine. However, I'm missing the history here on what the contract is.

Given this PR was intended to avoid having to regenerate the sstables, perhaps we should just bite the bullet and do that?

Assuming that is fine, here are a couple of options:

Option 1:

- introduce the new key kind (SetWithDelete = 18)
- bump `InternalKeyKindMax = 18`
- regenerate the sstable fixtures (which will write out the index blocks with key type 18)

Option 2, which is in line with your suggestion:

- co-opt value `17` as `InternalKeyKindForSeparator` (with string value "SEPARATOR", though it doesn't matter too much)
- update code that generates separators and successors to use `InternalKeyKindForSeparator` instead of `InternalKeyKindMax` (ultimately used for index block writes)
- introduce the new key kind (`SetWithDelete = 18`)
- bump `InternalKeyKindMax = 18` (used for reads / seeks)

Option 2 seems better, as it remedies the fact that we're "leaking" `InternalKeyKindMax` into index blocks right now, which opens us up to issues when we bump its value, as it is no longer stable. This is what I'm seeing with the test failures on my SetWithDelete PR. Option 2 also allows us to avoid having to regenerate the sstable fixtures each time we add a new key type.

As a historical side note, [at some point RocksDB changed the value they were writing into separator keys in index blocks](https://github.com/facebook/rocksdb/blob/82e7631de6e6ff87db62e64b0cc73d3c7886bb3a/db/dbformat.cc#L27). That must have required some type of migration? Seems like we definitely want to avoid that. Again, Option 2 seems good in that regard.

I will work up a PR for Option 2.

**Comment by sumeerbhola** [comment]
> That must have required some type of migration? 

I don't think it needs a migration as long as they updated tests. I should not have used the phrase "We just need it to be stable." without qualification -- we need the stability only because our tests are doing such comparisons, and not because it matters in the actual DB.

**Pull request closed without merging**
