### PR TITLE
sstable: Add missing invalidate() calls in Seek* methods

### PR DESCRIPTION
**Pull request by itsbilal**
Similar vein as the previous bug fix in twoLevelIterator (#655),
except with Seek methods. The iterator would occasionally
demonstrate really odd key jumps if the topLevelIterator was Seek'd
past its bounds and then the next couple operations were Next() or
Prev()s, which would flow down to the lower level iterator.

Found via the metamorphic test.

### CODE REVIEW

**Comment by petermattis** [comment]
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/708)

**Comment by itsbilal** [comment]
It shouldn't, because the only cases where `First()` or `Last() `would invalidate the top level iterator is if there are zero keys, and in that case the lower level iterator would never have been valid anyway.

**Comment by itsbilal** [comment]
TFTR!

**Comment by petermattis** [comment]
Ack. Ok. We'll want to backport this to `crl-release-20.1` and then to CRDB's `release-20.1` branch.

**Pull request merged**
