### PR TITLE
internal/keyspan: add Value to Span

### PR DESCRIPTION
**Pull request by jbowens**
Add a Value to the `Span` type, copying it to both fragments at a
fragmentation point. This will be used in the implementation of range
keys, which will be fragmented but carry a value.

### CODE REVIEW

**Review by nicktrav — APPROVED** [review]
Just nits. :lgtm:

> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1382#-:-MpDE_HTETgXEE_AD5ua:b78sqjr)* status: all files reviewed, 3 unresolved discussions (waiting on @jbowens and @sumeerbhola)

___
*[internal/keyspan/fragmenter_test.go, line 20 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1382#-MpD4b0621qL5YnnzlxV:-MpD4b0621qL5YnnzlxW:bn3p4aq) ([raw file](https://github.com/cockroachdb/pebble/blob/42e672b8c7fee836e4120768cfd7aaad2b27f2ce/internal/keyspan/fragmenter_test.go#L20)):*
> ```
> `(\d+):\s*(\w+)-*(\w+) *([^\n]*)`
> ```

nit: can the whitespace character after the third capture group be an `\s`? Slightly more explicit. i.e.:

```
(\d+):\s*(\w+)-*(\w+)\s*([^\n]*)
```
___
*[internal/keyspan/testdata/fragmenter_values, line 71 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1382#-MpDBcGV2-sLpMmzjgHa:-MpDBcGV2-sLpMmzjgHb:b33q6u) ([raw file](https://github.com/cockroachdb/pebble/blob/42e672b8c7fee836e4120768cfd7aaad2b27f2ce/internal/keyspan/testdata/fragmenter_values#L71)):*
> ```
> 2: a---e                      banana
> 1: a-----g                    coconut
> flush-to d
> ```

I had to squint to spot the differences between this test case and the one prior (flush vs. truncate-and-flush). Might be worth a brief comment above one or both of the test cases to call out the difference explicitly.

Also, unrelated to the test case itself, and more to the docs on `FlushTo`, I was a little confused as to why the `c-e` spans were flushed. Reading inside the function itself, it seems that we "flush all span fragments with a start key <= key". Can we repeat that comment on the function signature itself?
___
*[internal/keyspan/testdata/fragmenter_values, line 85 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1382#-MpD71pxDGIu44jdLDKa:-MpD71pxDGIu44jdLDKb:bvwwwsp) ([raw file](https://github.com/cockroachdb/pebble/blob/42e672b8c7fee836e4120768cfd7aaad2b27f2ce/internal/keyspan/testdata/fragmenter_values#L85)):*
> ```
> 1:     e-g                    coconut
> 3:       g-i                  orange
> ```

supernit: extra trailing newline

**Review by jbowens — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1382#-:-MpDq3T259SFgVKpol68:b-814g8k)* status: 13 of 16 files reviewed, 2 unresolved discussions (waiting on @nicktrav and @sumeerbhola)

___
*[internal/keyspan/fragmenter_test.go, line 20 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1382#-MpD4b0621qL5YnnzlxV:-MpDonXv1OqCN2LrQe-v:b-4pj5my) ([raw file](https://github.com/cockroachdb/pebble/blob/42e672b8c7fee836e4120768cfd7aaad2b27f2ce/internal/keyspan/fragmenter_test.go#L20)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

> ```
> `(\d+):\s*(\w+)-*(\w+) *([^\n]*)`
> ```

nit: can the whitespace character after the third capture group be an `\s`? Slightly more explicit. i.e.:

```
(\d+):\s*(\w+)-*(\w+)\s*([^\n]*)
```
</blockquote></details>

Nice, done.
___
*[internal/keyspan/testdata/fragmenter_values, line 71 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1382#-MpDBcGV2-sLpMmzjgHa:-MpDpmMCCFFl5MSetaii:b-48vilg) ([raw file](https://github.com/cockroachdb/pebble/blob/42e672b8c7fee836e4120768cfd7aaad2b27f2ce/internal/keyspan/testdata/fragmenter_values#L71)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

I had to squint to spot the differences between this test case and the one prior (flush vs. truncate-and-flush). Might be worth a brief comment above one or both of the test cases to call out the difference explicitly.

Also, unrelated to the test case itself, and more to the docs on `FlushTo`, I was a little confused as to why the `c-e` spans were flushed. Reading inside the function itself, it seems that we "flush all span fragments with a start key <= key". Can we repeat that comment on the function signature itself?
</blockquote></details>

Good call, done.

**Review by sumeerbhola — COMMENTED** [review]
> Reviewed 12 of 16 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1382)* status: all files reviewed (commit messages unreviewed), 3 unresolved discussions

___
*[internal/keyspan/testdata/fragmenter, line 25 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1382#-MpDx_fPAV3JlD49uhNA:-MpDx_fQ0K4iL6gfx289:b-39soph) ([raw file](https://github.com/cockroachdb/pebble/blob/3036ce0f15619b1ca01a2cae9b2769c7b0734241/internal/keyspan/testdata/fragmenter#L25)):*
> ```
> 1:          j--m
> 2:             m-----s
> 1:             m-----s------z
> ```

why did this change?

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1382)* status: all files reviewed (commit messages unreviewed), 3 unresolved discussions

___
*[internal/keyspan/testdata/fragmenter, line 25 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1382#-MpDx_fPAV3JlD49uhNA:-MpDywqC9P-18EyykCYM:bqbkkoh) ([raw file](https://github.com/cockroachdb/pebble/blob/3036ce0f15619b1ca01a2cae9b2769c7b0734241/internal/keyspan/testdata/fragmenter#L25)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

why did this change?
</blockquote></details>

The deleted portion `------z` was ignored by the parsing regex and nonsensical here, where each line indicates 1 new fragment.

**Pull request merged**
