### PR TITLE
sstable: implement NextPrefix for the sstable iterators

### PR DESCRIPTION
**Pull request by sumeerbhola**
The NextPrefix implementation mostly delegates to blockIter.nextPrefix.
If the next-prefix is not found in the current data block they first
attempt to step the index block and see if the successor key is
contained in that block. If that fails, they fall back to an approach
similar to SeekGE by also seeking the index.

blockIter.nextPrefix is defined for both v2 and v3 sstables, with the
latter utilizing the setHasSameKeyPrefix bit encoded in the value
prefix, and the bit encoded in the key restarts. To utilize this bit
efficiently, the shared prefix (for key prefix compression) when
writing a v3 sstable is limited to the prefix length of the preceding
key. This allows the read path to step over many keys that share
the same prefix, without assembling the full key, since any of them
can subsequently service the key prefix decompression.

The IteratorScanNextPrefix benchmark uses both NextPrefix and SeekGE,
to evaluate the difference. In general, NextPrefix is faster.
Additionally, the v3 format is faster than the v2 format when doing
NextPrefix. See the code comment in the benchmark with a more detailed
analysis.

The old is v2 and new is v3.

```
name                                                       old time/op    new time/op    delta
IteratorScanNextPrefix/versions=1/method=seek-ge-10          52.8ns ± 0%    54.4ns ± 0%   +3.04%  (p=0.008 n=5+5)
IteratorScanNextPrefix/versions=1/method=next-prefix-10      33.3ns ± 0%    15.4ns ± 0%  -53.62%  (p=0.016 n=4+5)
IteratorScanNextPrefix/versions=2/method=seek-ge-10          82.5ns ± 0%    90.0ns ± 0%   +9.21%  (p=0.008 n=5+5)
IteratorScanNextPrefix/versions=2/method=next-prefix-10      61.6ns ± 0%    19.1ns ± 0%  -68.95%  (p=0.008 n=5+5)
IteratorScanNextPrefix/versions=10/method=seek-ge-10          828ns ± 0%     936ns ± 2%  +13.13%  (p=0.008 n=5+5)
IteratorScanNextPrefix/versions=10/method=next-prefix-10      495ns ± 1%      63ns ± 0%  -87.33%  (p=0.008 n=5+5)
IteratorScanNextPrefix/versions=100/method=seek-ge-10        1.22µs ± 0%    1.04µs ± 0%  -15.02%  (p=0.016 n=4+5)
IteratorScanNextPrefix/versions=100/method=next-prefix-10    1.03µs ± 1%    0.27µs ± 1%  -73.95%  (p=0.008 n=5+5)

name                                                       old alloc/op   new alloc/op   delta
IteratorScanNextPrefix/versions=1/method=seek-ge-10           0.00B          0.00B          ~     (all equal)
IteratorScanNextPrefix/versions=1/method=next-prefix-10       0.00B          0.00B          ~     (all equal)
IteratorScanNextPrefix/versions=2/method=seek-ge-10           0.00B          0.00B          ~     (all equal)
IteratorScanNextPrefix/versions=2/method=next-prefix-10       0.00B          0.00B          ~     (all equal)
IteratorScanNextPrefix/versions=10/method=seek-ge-10          0.00B          0.00B          ~     (all equal)
IteratorScanNextPrefix/versions=10/method=next-prefix-10      0.00B          0.00B          ~     (all equal)
IteratorScanNextPrefix/versions=100/method=seek-ge-10         0.00B          0.00B          ~     (all equal)
IteratorScanNextPrefix/versions=100/method=next-prefix-10     0.00B          0.00B          ~     (all equal)
```

Informs https://github.com/cockroachdb/pebble/issues/1170

### CODE REVIEW

**Review by sumeerbhola — COMMENTED** [review]
The first commit is from https://github.com/cockroachdb/pebble/pull/2134

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2149#-:-NI-WPo9-i_HOwE_DVO1:baxmeve)* status: 0 of 37 files reviewed, all discussions resolved (waiting on @jbowens)

**Review by jbowens — COMMENTED** [review]
I had a thought while thinking about [this comment](https://reviewable.io/reviews/cockroachdb/pebble/2178#-NInBiUXDipLVF3MeoAX). When `Next`-ing within prefix-iteration mode, we could use an unset `setHasSameKeyPrefix` bit to early return (nil,nilv).

> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2149#-:-NIncPw5CSMfgOoBGwsc:b-h3yrmy)* status: 1 of 12 files reviewed, 4 unresolved discussions (waiting on @sumeerbhola)

___
*[`sstable/block.go` line 1135 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2149#-NIngdTJ6YR0huVQwk4w:-NIngdTJ6YR0huVQwk4x:b-d5nhwc) ([raw file](https://github.com/cockroachdb/pebble/blob/281e5c1692e51f6a05a05e2695dfdeb55933ae2b/sstable/block.go#L1135)):*
> ```Go
> 		if keyKind == InternalKeyKindSet {
> 			if invariants.Enabled && value == 0 {
> 				panic(errors.AssertionFailedf("value is of length 0"))
> ```

took me a minute (by reading ahead) to realize this is an assertion failure because the value prefix must be present. maybe include some language about the value prefix in the assertion error message?

TIL about `errors.AssertionFailedf`
___
*[`sstable/block.go` line 1186 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2149#-NInhwur237DEzKeXuCn:-NInhwur237DEzKeXuCo:b-qcnotr) ([raw file](https://github.com/cockroachdb/pebble/blob/281e5c1692e51f6a05a05e2695dfdeb55933ae2b/sstable/block.go#L1186)):*
> ```Go
> 					startingIndex := index
> 					for index != i.numRestarts &&
> 						i.data[i.restarts+4*index+3]&restartMaskLittleEndianHighByteOnlySetHasSamePrefix != 0 {
> ```

i didn't follow this indexing. maybe a short explanatory comment?
___
*[`sstable/block.go` line 1192 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2149#-NIniOuUE0mB4x4hMN1U:-NIniOuVByB6XRdn7Upr:bbf1h4c) ([raw file](https://github.com/cockroachdb/pebble/blob/281e5c1692e51f6a05a05e2695dfdeb55933ae2b/sstable/block.go#L1192)):*
> ```Go
> 						// Unable to skip past any restart. Since we have exhausted our
> 						// iteration budget, break out of the loop.
> 						break
> ```

if all of the keys between restart index and restart index+1 are SETs, then this indicates that the prefix change is very close, right? it's between the current position and the next restart. it seems like a shame to fall back to seeking when we've already positioned the block iter part way through the restart points in which the key lies.

if not all of the keys between the restart index and restart index+1 are SETs, then the prefix change may still be far. but could we disqualify that by checking if the key at restart `index+1` has a different prefix? 
___
*[`sstable/block.go` line 1217 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2149#-NInjpxr1arhyFVJvuj_:-NInjpxr1arhyFVJvuja:b-glrqu) ([raw file](https://github.com/cockroachdb/pebble/blob/281e5c1692e51f6a05a05e2695dfdeb55933ae2b/sstable/block.go#L1217)):*
> ```Go
> 			// key to be copied if the caller knows the block has a restart interval of
> 			// 1. An important example of this is range-del blocks.
> 			i.key = unsharedKey
> ```

in this case, is there any reason to perform the `i.fullKey` copy up above? should we move that into the else branch?

**Review by sumeerbhola — COMMENTED** [review]
Good point. From a spec perspective we currently say
```
	// 1 bit indicates SET has same key prefix as immediately preceding key that
	// is also a SET. This is optional, in that if this bit is false, there is
	// no information.
```
But the actual implementation is stronger in that if the previous key is a SET and the current key is a SET, the `setHasSameKeyPrefix` bit is always correct.
The `blockIter` would need to also confirm that the `ikey` at the start of the `nextPrefix` call is a SET. This would save one key comparison. Done now. The old v3 vs new v3:
```
name                                                       old time/op    new time/op    delta
IteratorScanNextPrefix/versions=1/method=seek-ge-10          54.7ns ± 1%    54.4ns ± 0%   -0.59%  (p=0.008 n=5+5)
IteratorScanNextPrefix/versions=1/method=next-prefix-10      33.9ns ± 0%    15.4ns ± 0%  -54.43%  (p=0.008 n=5+5)
IteratorScanNextPrefix/versions=2/method=seek-ge-10          90.4ns ± 0%    90.0ns ± 0%   -0.42%  (p=0.008 n=5+5)
IteratorScanNextPrefix/versions=2/method=next-prefix-10      35.6ns ± 0%    19.1ns ± 0%  -46.29%  (p=0.008 n=5+5)
IteratorScanNextPrefix/versions=10/method=seek-ge-10          926ns ± 0%     936ns ± 2%     ~     (p=0.651 n=5+5)
IteratorScanNextPrefix/versions=10/method=next-prefix-10     77.9ns ± 0%    62.7ns ± 0%  -19.51%  (p=0.008 n=5+5)
IteratorScanNextPrefix/versions=100/method=seek-ge-10        1.03µs ± 0%    1.04µs ± 0%   +0.82%  (p=0.008 n=5+5)
IteratorScanNextPrefix/versions=100/method=next-prefix-10     279ns ± 0%     268ns ± 1%   -3.85%  (p=0.008 n=5+5)
```


Addressed existing comments. I will ping after rebasing.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2149#-:-NJR7x6t4FLTnHiDeZPX:blm3sdo)* status: 1 of 12 files reviewed, 4 unresolved discussions (waiting on @jbowens)

___
*[`sstable/block.go` line 1135 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2149#-NIngdTJ6YR0huVQwk4w:-NJR9QlQC_cfMhfmD4kq:bb6un1j) ([raw file](https://github.com/cockroachdb/pebble/blob/281e5c1692e51f6a05a05e2695dfdeb55933ae2b/sstable/block.go#L1135)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

took me a minute (by reading ahead) to realize this is an assertion failure because the value prefix must be present. maybe include some language about the value prefix in the assertion error message?

TIL about `errors.AssertionFailedf`
</blockquote></details>

Done
___
*[`sstable/block.go` line 1186 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2149#-NInhwur237DEzKeXuCn:-NJRApQK9avAND09uiZ7:bb6un1j) ([raw file](https://github.com/cockroachdb/pebble/blob/281e5c1692e51f6a05a05e2695dfdeb55933ae2b/sstable/block.go#L1186)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

i didn't follow this indexing. maybe a short explanatory comment?
</blockquote></details>

Done
___
*[`sstable/block.go` line 1192 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2149#-NIniOuUE0mB4x4hMN1U:-NJRB3Yg07Ad8cIIIQvv:b-vtdg9a) ([raw file](https://github.com/cockroachdb/pebble/blob/281e5c1692e51f6a05a05e2695dfdeb55933ae2b/sstable/block.go#L1192)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

if all of the keys between restart index and restart index+1 are SETs, then this indicates that the prefix change is very close, right? it's between the current position and the next restart. it seems like a shame to fall back to seeking when we've already positioned the block iter part way through the restart points in which the key lies.

if not all of the keys between the restart index and restart index+1 are SETs, then the prefix change may still be far. but could we disqualify that by checking if the key at restart `index+1` has a different prefix? 
</blockquote></details>

index is the first restart that does not have the same prefix. So index-1 is where we want to resume. But if index==startIndex we didn't skip any restarts, and we've exhausted our fast-budget `nextFastThresholdBeforeSeek`. I think what you are suggesting is that this notion of fast budget is flawed, in that if we know the next prefix is not far, we should continue iterating. I think that makes sense, so made the change. Which means `nextFastThresholdBeforeSeek` is just for (a) iterating before using the restarts, (b) a safety mechanism in case someone is using a very high restart interval. I've renamed it to `nextFastThresholdBeforeRestarts`.
This doesn't move the benchmark, which is fine.
___
*[`sstable/block.go` line 1217 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2149#-NInjpxr1arhyFVJvuj_:-NJb0yoX2tuaMhbil_us:b-fg3f9h) ([raw file](https://github.com/cockroachdb/pebble/blob/281e5c1692e51f6a05a05e2695dfdeb55933ae2b/sstable/block.go#L1217)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

in this case, is there any reason to perform the `i.fullKey` copy up above? should we move that into the else branch?
</blockquote></details>

Nice observation. I lifted this from `readEntry`. I've added a TODO in both places, for a followup PR. Should help for range key/del blocks where we have `restartInterval=1`.

**Review by sumeerbhola — COMMENTED** [review]
Rebased.

For v2, the slightly optimized implementations in `reader.go` that first step to the next block are slightly better with a larger number of versions (the -9.56% below)
```
name                                                       old time/op    new time/op    delta
IteratorScanNextPrefix/versions=1/method=seek-ge-10          52.5ns ± 0%    53.1ns ± 0%  +1.18%  (p=0.008 n=5+5)
IteratorScanNextPrefix/versions=1/method=next-prefix-10      36.0ns ± 0%    33.6ns ± 1%  -6.67%  (p=0.008 n=5+5)
IteratorScanNextPrefix/versions=2/method=seek-ge-10          81.9ns ± 0%    82.3ns ± 0%  +0.58%  (p=0.008 n=5+5)
IteratorScanNextPrefix/versions=2/method=next-prefix-10      63.0ns ± 0%    61.3ns ± 0%  -2.61%  (p=0.016 n=5+4)
IteratorScanNextPrefix/versions=10/method=seek-ge-10          826ns ± 0%     823ns ± 0%  -0.31%  (p=0.008 n=5+5)
IteratorScanNextPrefix/versions=10/method=next-prefix-10      502ns ± 0%     492ns ± 0%  -2.06%  (p=0.008 n=5+5)
IteratorScanNextPrefix/versions=100/method=seek-ge-10        1.33µs ± 0%    1.32µs ± 0%  -1.13%  (p=0.008 n=5+5)
IteratorScanNextPrefix/versions=100/method=next-prefix-10    1.22µs ± 0%    1.10µs ± 0%  -9.56%  (p=0.008 n=5+5)
```

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2149#-:-NJbD4rLBRpE1Eyy0U4A:bsy5zak)* status: 0 of 12 files reviewed, 4 unresolved discussions (waiting on @jbowens)

**Review by jbowens — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2149#-:-NJzxqlM6C5PSC0PqIOK:bnfp4nl)* status: 0 of 13 files reviewed, 1 unresolved discussion

**Pull request merged**
