### PR TITLE
README.md: add coverage link

### PR DESCRIPTION
**Pull request by RaduBerinde**

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Looks like this:

image

**Review by bananabrick — COMMENTED** [review]
Nice

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2891#-:-Ndr1Gt-6LCJqVH4ASE7:bb70w76)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @itsbilal)

**Comment by RaduBerinde** [comment]
Can I get the rubber stamp? :)

**Review by itsbilal — APPROVED** [review]
Aye

**Pull request merged**
