### PR TITLE
db: use uncompensated scores to smoothe compaction picking scores

### PR DESCRIPTION
**Pull request by bananabrick**
When adjusting scores by smoothing scores, use a parallel uncompensated score as the divisor for the smoothing adjustment. This helps avoid range deletions in lower levels from starving compactions in higher levels through excessive prioritization of lower-level disk space reclamation.

### CODE REVIEW

**Comment by bananabrick** [comment]
Previous approved pr: https://github.com/cockroachdb/pebble/pull/1189. I pushed changes to that branch too, but reviewable wasn't letting me leave comments.

**Review by bananabrick — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2663)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @itsbilal)

___
*[`compaction_picker.go` line 1046 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2663#-NYVMiW1-n2yhoSyIin1:-NYVMiW1-n2yhoSyIin2:b-2hvilo) ([raw file](https://github.com/cockroachdb/pebble/blob/84c66c1775ccbbe7e2103023eb8ee9cf5e5e7aa0/compaction_picker.go#L1046)):*
> ```Go
> 			const minScore = 0.01
> 			if scores[level].score >= minScore {
> 				scores[prevLevel].score /= scores[level].rawScore
> ```

I think using score here doesn't make sense, because we aren't reducing the write amp by not compacting into a level which has a high score due to level size compensation. This was discussed in the previous approved pr.

**Review by bananabrick — COMMENTED** [review]
The only change I made was fixed the tests which needed to be rebased.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2663#-:-NYVN5D2ASJ-wf4FBncO:b3qghyx)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @itsbilal)

**Comment by bananabrick** [comment]
Read amp is looking a bit better(100 vs 200): https://grafana.testeng.crdb.io/d/ngnKs_j7x/admission-control?orgId=1&from=1687393951622&to=1687398461047&var-cluster=arjunnair-1687393815-01-n10cpu16&var-instances=All

https://grafana.testeng.crdb.io/d/ngnKs_j7x/admission-control?orgId=1&var-cluster=arjunnair-1687207031-01-n10cpu16&var-instances=All&from=1687205345636&to=1687212953183

But the KV store requests graph seems choppy with this change. Will look into it.

**Comment by jbowens** [comment]
Nice, makes sense.

There are still a lot of snapshot applications forcing flushes.
Screenshot 2023-06-22 at 11 19 36 AM
There are also still compactions wasting bandwidth writing data that is pinned by snapshots:
Screenshot 2023-06-22 at 12 47 28 PM

It looks like there's a spike of elastic admittance right at the same time as the snapshot applications. Are these range merges that are being allowed in?
Screenshot 2023-06-22 at 1 03 37 PM

I think the aggressive range merging we see here is a large part of why it's so disruptive. It looks like we're simultaneously dropping `RANGEDEL`s _and_ replacing most of the LSM by applying broad range snapshots of merged ranges.

So there's still a few sources of badness outside of compaction-picker scoring that I think we do want to address:
1. The write bandwidth wasted by open LSM snapshots: This would be fixed by #1810 or maybe reducing the length of time these snapshots are held.
2. The flushes forced by snapshot reception increase read-amp excessively: cockroachdb/cockroach#99273 is probably contributing. Or if these snapshots are for merged ranges that cover old replicas already in the store, that could contribute as well. If we fixed cockroachdb/cockroach#99273 _and_ use Ingest+Excise, there would be no increase in read-amp because the the snapshot sstables could be ingested directly into L6.
3. We seem to be aggressively merging ranges, despite the increasing read amplification. Should admission control be preventing these merge operations from overwhelming the storage engine?

In terms of compaction scoring, maybe we should consider putting a ceiling on the score that can result from compensated sizes. For example, the score of a level could be: `Max(MIN(3, Score(CompensatedSize)), Score(Size))`. During this test, L0 had large scores:

Screenshot 2023-06-22 at 1 14 09 PM

They just paled in comparison to the scores lower in the LSM due to the very large amount of garbage.

Screenshot 2023-06-22 at 1 14 50 PM

**Review by jbowens — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2663#-:-NYZKwat8teJgHJ94eBM:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @itsbilal)

**Comment by bananabrick** [comment]
Ran it again: https://grafana.testeng.crdb.io/d/ngnKs_j7x/admission-control?orgId=1&var-cluster=arjunnair-1687986297-01-n10cpu16&var-instances=All&from=now-1h&to=now. I don't see the any throughput drops.

I am seeing some high write amps, so looking into that. Maybe there were temporary spikes in disk throughput which led to fsync latency spikes.

**Comment by bananabrick** [comment]
Not sure what's going on now. Maybe I'm doing something wrong, but here's a run on master without this pr with a bunch of liveness failures: https://grafana.testeng.crdb.io/d/ngnKs_j7x/admission-control?orgId=1&var-cluster=arjunnair-1687996100-01-n10cpu16&var-instances=All&from=now-1h&to=now

I think I'm just gonna do another rounds of runs tomorrow, to see what's going on. I think the clearrange roachtest also failed during its last nightly run.

**Comment by bananabrick** [comment]
I wonder if these are just GCE disk stalls, the fsync latencies are 10s+. Didn't we have an issue with gce disk stalls? I did a cursory search in Cockroach and couldn't find that issue.

**Comment by bananabrick** [comment]
Alright, I can't repro the liveness failure anymore. I've made some minor changes. PTAL, @jbowens

**Review by jbowens — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2663#-:-NZBgP94-PZT04jINZ61:bnfp4nl)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @itsbilal)

**Comment by bananabrick** [comment]
Thanks

**Pull request merged**
