### PR TITLE
vfs: enforce serialized writes in diskHealthCheckingFile

### LINKED ISSUE #2274: vfs: enforce serialized operations in `diskHealthCheckingFile`
Currently, the [`diskHealthCheckingFile`](https://github.com/cockroachdb/pebble/blob/169e5dbe99922057ece23888608745b7044aca1b/vfs/disk_health.go#L81-L88) makes the assumption that there's one write op happening at a time. We rely on this assumption for monitoring purposes.

We should ensure that this assumption holds throughout the codebase, maybe by an `invariants.Enabled` check or using compare-and-swap for `lastWritePacked`.

Related to cockroachdb/cockroach#94373.

### PR DESCRIPTION
**Pull request by itsbilal**
If `invariants.Enabled`, this change replaces the atomic Stores with CompareAndSwaps to ensure that only one write operation at a time is writing to this disk health checking file. This increases confidence in our disk health checking, as the logic relies heavily on there being one write operation per file at a time.

Fixes #2274.

### CODE REVIEW

**Review by nicktrav — APPROVED** [review]
Nice. :lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2282#-:-NMj0Py728gNuO3sUOXA:bxsbkqo)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jbowens)

**Review by nicktrav — COMMENTED** [review]
Is it worth adding a test for this? On the fence about it, as we don't typically test our other invariant checks - rather, the lack of panic in an invariant-gated build is the test itself.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2282#-:-NMj0ytEDsEvEyOEvjER:b-wzrktw)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jbowens)

**Comment by itsbilal** [comment]
TFTR @nicktrav ! I too would be okay without a test, as other tests already check for disk operations stalling as well as all sorts of concurrent operations, and the fact that there's no panic there just gives us more confidence.

A bigger question would be, should we backport this to 22.2? It's just an invariants check so I'm not sure if we should.

**Comment by nicktrav** [comment]
> A bigger question would be, should we backport this to 22.2? It's just an invariants check so I'm not sure if we should.

Not sure. Are there nightly, invariant-gated checks that run on the 22.2 for Pebble? If no, I'm not sure there's much benefit. Maybe @jbowens has an opinion on this.

**Pull request merged**
