### PR TITLE
db: optimize SetBounds and SetOptions for unchanging bounds 

### PR DESCRIPTION
**Pull request by jbowens**
Restore the SetBounds optimization that avoids invalidating the iterator during
a call to SetBounds if the bounds are unchanged. This optimization was removed
in https://github.com/cockroachdb/pebble/pull/1073 because the previous version of this optimization improperly retained
the old bounds which might be mutated by the user. In this reintroduction of
the optimization, a call to SetBounds with unchanged bounds still propagates
the new bounds down the entire iterator tree. However, if the bounds are equal,
the iterator state is not invalidated, allowing subsequent seeks to take
advantage of optimizations like try-seek-using-next.

Additionally, apply the same optimization to SetOptions.

### CODE REVIEW

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> Reviewed 12 of 25 files at r3, 1 of 2 files at r5, 1 of 11 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1667)* status: 34 of 38 files reviewed, 6 unresolved discussions (waiting on @jbowens, @nicktrav, and @sumeerbhola)

___
*[`iterator.go` line 1668 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1667#-N0bFc23Cr_Dko2mo6MQ:-N0bFc24DTifv18XDK4w:b85ffvr) ([raw file](https://github.com/cockroachdb/pebble/blob/0a4b0a17d5b52470f78b43eaa9c239ecbd056fe2/iterator.go#L1668)):*
> ```Go
> // and false otherwise.
> func (i *Iterator) Valid() bool {
> 	return i.iterValidityState == IterValid && !i.requiresReposition
> ```

is this a semantic change, switching from non-deterministic behavior to deterministically exhausted?
___
*[`iterator.go` line 1820 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1667#-N0bG6K74RmBXpLHef4g:-N0bG6K74RmBXpLHef4h:b-it6kql) ([raw file](https://github.com/cockroachdb/pebble/blob/0a4b0a17d5b52470f78b43eaa9c239ecbd056fe2/iterator.go#L1820)):*
> ```Go
> 		// should call a repositioning method. We could have arbitrarily set i.pos
> 		// to one of the values. But it results in more intuitive behavior in
> 		// tests, which do not always reposition.
> ```

is this comment stale due to the introduction of requiresReposition?
___
*[`internal/arenaskl/iterator.go` line 227 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1667#-N0bGhG99uSapF1wz8jF:-N0bGhG99uSapF1wz8jG:b-qxe4hr) ([raw file](https://github.com/cockroachdb/pebble/blob/0a4b0a17d5b52470f78b43eaa9c239ecbd056fe2/internal/arenaskl/iterator.go#L227)):*
> ```Go
> }
> 
> // SetBounds sets the lower and upper bounds for the iterator. If equal is true,
> ```

false?
___
*[`internal/base/iterator.go` line 211 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1667#-N0bGpFt1_Uf0GhTuemp:-N0bGpFt1_Uf0GhTuemq:b-3jh5dm) ([raw file](https://github.com/cockroachdb/pebble/blob/0a4b0a17d5b52470f78b43eaa9c239ecbd056fe2/internal/base/iterator.go#L211)):*
> ```Go
> 	// SetBounds sets the lower and upper bounds for the iterator. If equal is
> 	// true, the provided bounds are logically equal to the previous bounds. If
> 	// equal, the iterator replaces its internal bounds with the new bounds.
> ```

In either case it needs to replace its internal bounds with the new bounds, yes?
___
*[`sstable/reader.go` line 1069 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1667#-N0bHKRs644zprx5JZ6K:-N0bHKRs644zprx5JZ6L:b-fexwpe) ([raw file](https://github.com/cockroachdb/pebble/blob/0a4b0a17d5b52470f78b43eaa9c239ecbd056fe2/sstable/reader.go#L1069)):*
> ```Go
> 		return
> 	}
> ```

We've already set i.lower and lower to be equal, and same for the upper slices. So the comparisons below are no longer doing what they were intended to do.

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1667)* status: 30 of 38 files reviewed, 5 unresolved discussions (waiting on @nicktrav and @sumeerbhola)

___
*[`iterator.go` line 1668 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1667#-N0bFc23Cr_Dko2mo6MQ:-N0bUYi81d_fGpYlyWub:b-9e8iyx) ([raw file](https://github.com/cockroachdb/pebble/blob/0a4b0a17d5b52470f78b43eaa9c239ecbd056fe2/iterator.go#L1668)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

is this a semantic change, switching from non-deterministic behavior to deterministically exhausted?
</blockquote></details>

not sure if I'm understanding the question correctly, but this ensures that `SetBounds()` itself always results in an exhausted iterator. Without it, the validity of the iterator after a `SetBounds` is still deterministic (a function of the previous bounds and the new bounds), but it's confusingly inconsistent. I wanted to keep the equal bounds optimization an internal optimization that doesn't leak through the interface. 
___
*[`iterator.go` line 1820 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1667#-N0bG6K74RmBXpLHef4g:-N0bXnihDXAduMmks1J3:bnr4zoj) ([raw file](https://github.com/cockroachdb/pebble/blob/0a4b0a17d5b52470f78b43eaa9c239ecbd056fe2/iterator.go#L1820)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

is this comment stale due to the introduction of requiresReposition?
</blockquote></details>

i think it's still necessary (see my comment on requiresReposition
___
*[`internal/arenaskl/iterator.go` line 227 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1667#-N0bGhG99uSapF1wz8jF:-N0bVcFP90k62wJOk6zw:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/0a4b0a17d5b52470f78b43eaa9c239ecbd056fe2/internal/arenaskl/iterator.go#L227)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

false?
</blockquote></details>

Done.
___
*[`internal/base/iterator.go` line 211 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1667#-N0bGpFt1_Uf0GhTuemp:-N0bVnXu6RtN5pO7jJZV:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/0a4b0a17d5b52470f78b43eaa9c239ecbd056fe2/internal/base/iterator.go#L211)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

In either case it needs to replace its internal bounds with the new bounds, yes?
</blockquote></details>

Done.
___
*[`sstable/reader.go` line 1069 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1667#-N0bHKRs644zprx5JZ6K:-N0bUIRE1G5mEH-JYo9N:bf27ire) ([raw file](https://github.com/cockroachdb/pebble/blob/0a4b0a17d5b52470f78b43eaa9c239ecbd056fe2/sstable/reader.go#L1069)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

We've already set i.lower and lower to be equal, and same for the upper slices. So the comparisons below are no longer doing what they were intended to do.
</blockquote></details>

Good catch, thanks

**Review by jbowens — COMMENTED** [review]
The metamorphic test extension I added in the second commit revealed a problem: The interleaving iterator needs to truncate spans to the configured bounds. This can result in the interleaving iterator returning the user-provided bound as a synthetic marker for the start bound. The top-level `pebble.Iterator` may have a `key` or `iterKey` that is still using the stale lower bound.

@sumeerbhola @erikgrinaker I'm tempted to endure the copy at each `SetBounds`. Thoughts?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1667#-:-N0bfbS60wMU1SCGXTt5:b-cbzelv)* status: 30 of 38 files reviewed, 5 unresolved discussions (waiting on @erikgrinaker, @nicktrav, and @sumeerbhola)

**Review by erikgrinaker — COMMENTED** [review]
> This can result in the interleaving iterator returning the user-provided bound as a synthetic marker for the start bound. The top-level pebble.Iterator may have a key or iterKey that is still using the stale lower bound. [...] I'm tempted to endure the copy at each SetBounds. Thoughts?

Aren't we calling `SetOptions/SetBounds` on the top-level iterator too, so it can invalidate/update its `key` or `iterKey`? And any byte buffers that have been returned to the original caller will no longer be valid after a `SetOptions/SetBounds` call, right?

> Reviewed 18 of 25 files at r3, 1 of 2 files at r4, 1 of 11 files at r6, 6 of 6 files at r8, 1 of 2 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1667#-:-N0eKVC1AD3_PBq70usl:b1iw56a)* status: 36 of 38 files reviewed, 6 unresolved discussions (waiting on @erikgrinaker, @jbowens, @nicktrav, and @sumeerbhola)

___
*[`internal/base/iterator.go` line 210 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1667#-N0eJq0c5CtHaX6XP_Vs:-N0eJq0c5CtHaX6XP_Vt:b-rvly6x) ([raw file](https://github.com/cockroachdb/pebble/blob/4eaf9316ea3a61c2cbfffe0afa7dea5d1aef3a1f/internal/base/iterator.go#L210)):*
> ```Go
> 
> 	// SetBounds sets the lower and upper bounds for the iterator. If equal is
> 	// true, the provided bounds are logically equal to the previous bounds.
> ```

Consider mentioning why this is needed.

**Review by jbowens — COMMENTED** [review]
> so it can invalidate/update its key or iterKey?

We could, but it'd require two additional key comparisons and seems brittle. Once these keys are interleaved, it's easy to leak them all over.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1667#-:-N0fF2mM6ulMIZ5iYctC:b-uzogoj)* status: 36 of 38 files reviewed, 6 unresolved discussions (waiting on @erikgrinaker, @jbowens, @nicktrav, and @sumeerbhola)

**Review by erikgrinaker — COMMENTED** [review]
>>so it can invalidate/update its key or iterKey?

>We could, but it'd require two additional key comparisons and seems brittle. Once these keys are interleaved, it's easy to leak them all over.

I see. Don't we have the same problem with the bound slices that the caller passes, when the caller changes them after the second `SetBounds()` call?

I suppose copying might work, it'll come down to performance. Can we do the copy while reusing the byte buffer, or will that have similar problems? Want to do some quick benchmarks, or alternatively prepare a patch that I can benchmark in CRDB?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1667#-:-N0fHFOC4HtbslMbWosu:b-ctlcc0)* status: 36 of 38 files reviewed, 6 unresolved discussions (waiting on @erikgrinaker, @jbowens, @nicktrav, and @sumeerbhola)

**Review by jbowens — COMMENTED** [review]
> Don't we have the same problem with the bound slices that the caller passes, when the caller changes them after the second SetBounds() call?

I think it's not a problem as long as we're not applying the equal bounds optimization. If we're invalidating the iterator, the caller is required to re-seek which clears any state that might reference the mangled bound. A `SetBounds` is documented as invalidating the iterator, so as soon as the caller calls `SetBounds` they can't rely on the return value of `Key()`.

> Can we do the copy while reusing the byte buffer, or will that have similar problems?

Yeah, I think we should be able to avoid the allocation and reuse a byte buffer pooled on the `iterAlloc` struct.

> So this would have been a bug even with the optimization being done in CockroachDB, and we're actually in a better place now since we can control the lifetime inside Pebble?

I think we would be fine if we continued performing the optimization in CockroachDB. If CockroachDB refrains from calling `SetBounds`/`SetOptions`, the existing bound is unchanged.

----

The options I see are:

1. Adjust this PR as-written to update `iterKey` if equal to the lower bound, only during the optimized case. I believe this would work, it's just more subtle and brittle than I'd like. Maybe the metamorphic test extension in the second commit is sufficient to give us confidence that we'd notice if the old bound was leaked beyond an optimized `SetBounds`/`SetOptions`.
2. Keep the optimization in CockroachDB. This adds code duplication between CockroachDB's iterator reuse and `SetOptions`, since both functions need to compute the delta of previous and new options to apply optimizations. Additionally, `SetOptions` is more limited in the optimizations it can apply, since it can't ever apply the bounds optimization even if it would otherwise apply (eg, the `IterOptions` are only adding a new key type to the iterator).
3. Copy the new bounds into `iterAlloc`-pooled key buffers. In CockroachDB this would result in writing bounds twice when changing the bounds: once to formulate the bounds with the NUL terminator and once when copying them into a buffer with a Pebble-controlled lifetime. In the case that bounds don't change, this would avoid recursively propagating the new bound buffers down the iterator tree. In the case the bounds have not changed, the copy can be omitted.

The metamorphic test extension is picking up additional problems: one with `i.span` in interleaving iterator, and another yet to be identified. I think this speaks to the brittleness of this path. I'll put together a chance for the third option so that we can evaluate it.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1667#-:-N0foiyZ5nLN-WZm5Nf4:b-y74gzq)* status: 36 of 38 files reviewed, 5 unresolved discussions (waiting on @erikgrinaker, @nicktrav, and @sumeerbhola)

___
*[`sstable/reader.go` line 1069 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1667#-N0bHKRs644zprx5JZ6K:-N0g-lwV8rrTCV9m3NKc:b-vk63dj) ([raw file](https://github.com/cockroachdb/pebble/blob/0a4b0a17d5b52470f78b43eaa9c239ecbd056fe2/sstable/reader.go#L1069)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Do we have a test that would have caught this bug?
</blockquote></details>

We don't and I'm open to suggestions here. This bug manifested as `i.boundsCmp` always set to zero, disabling this optimization.

**Review by erikgrinaker — COMMENTED** [review]
>The metamorphic test extension is picking up additional problems: one with i.span in interleaving iterator, and another yet to be identified. I think this speaks to the brittleness of this path. I'll put together a chance for the third option so that we can evaluate it.

I agree, let's give the copy option a shot and see if it's viable. If not, we can go with the existing CRDB bounds handling and `RefreshBatchSnapshot()` for now, and revisit later.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1667#-:-N0jLOekExUSAPuNToH1:brml082)* status: 36 of 38 files reviewed, 5 unresolved discussions (waiting on @erikgrinaker, @nicktrav, and @sumeerbhola)

**Review by jbowens — COMMENTED** [review]
Put up #1675 with bounds-copying. @sumeerbhola voiced concerns about places in CockroachDB where we repeatedly set bounds and seek, like geospatial code paths. I was able to reuse buffers pooled on the `iterAlloc`, so allocations should be minimal.

I also fixed up all the known issues on _this_ pull request. I'm running the metamorphic tests in the background to see if they shake out any additional issues.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1667#-:-N0lBhRJ8NK6If23eeUd:bv5srys)* status: 33 of 38 files reviewed, 5 unresolved discussions (waiting on @erikgrinaker, @nicktrav, and @sumeerbhola)

**Comment by jbowens** [comment]
Closing in favor of #1675.

**Pull request closed without merging**
