### PR TITLE
sstable,db: two small bounds related changes

### PR DESCRIPTION
**Pull request by nicktrav**
The first commit alters `(base.InternalKey).IsExclusiveSentinel` to handle all range key kinds - previously only a RANGEKEYSET with a max seqnum was considered a sentinel.

The second updates the smallest and largest point keys to be set using the helper methods, rather than referencing the smallest / largest fields directly.

### CODE REVIEW

**Comment by nicktrav** [comment]
I uncovered these while working on the refactor to set all the `FileMetadata` smallest / largest fields using helper methods. Figured these should be fixed on master, even if they end up being re-worked in subsequent patches.

**Review by jbowens — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1530)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @itsbilal and @nicktrav)

___
*[sstable/writer.go, line 1473 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1530#-MwbVnPV7bINXkHZnB1C:-MwbVnPV7bINXkHZnB1D:bamzp94) ([raw file](https://github.com/cockroachdb/pebble/blob/2c5224581900d0e02e11f88be532b7db888c076e/sstable/writer.go#L1473)):*
> ```Go
> 			return w.err
> 		}
> 		w.meta.LargestRangeKey = base.MakeInternalKey(endKey, base.InternalKeySeqNumMax, key.Kind()).Clone()
> ```

Is this prior code wrong? I guess it's up to us how we want to represent the bounds of a sstable containing, for example, a `RANGEKEYUNSET` from `a-c`.

I had been imagining that we'd update `InternalKey.IsExclusiveSentinel` to consider `RANGEKEYSET#inf`, `RANGEKEYUNSET#inf`, `RANGEKEYDEL#inf` all to be exclusive sentinel keys: https://github.com/cockroachdb/pebble/blob/2c5224581900d0e02e11f88be532b7db888c076e/internal/base/internal.go#L359-L360

We could choose always use `RANGEKEYSET#inf` as the largest bound, like you do here. I find it a little confusing though, that you can have a table that only contains `RANGEKEYUNSET`s and/or `RANGEKEYDELETE`s but has a largest bound with a `RANGEKEYSET` kind.
___
*[ingest_test.go, line 1246 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1530#-MwbYWHd2DLnqjJ8QNbW:-MwbYWHe2hzXiYf-3tVy:bhab9kq) ([raw file](https://github.com/cockroachdb/pebble/blob/2c5224581900d0e02e11f88be532b7db888c076e/ingest_test.go#L1246)):*
> ```Go
> 			// Construct the file metadata from the writer metadata.
> 			m := &fileMetadata{
> 				SmallestPointKey: wm.SmallestPoint,
> ```

Should we unexport `(sstable.WriterMetadata).SmallestPoint` and `(sstable.WriterMetadata).LargestPoint`? It looks like they're only accessed through internally and it might help prevent the same mistake?

**Review by nicktrav — COMMENTED** [review]
I switch the first commit to instead address the TODO in `IsExclusiveSentinel`. The second commit is still a bugfix.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1530#-:-MwbyJ8x9VZyta_Yy_ay:b-7nlncv)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @itsbilal and @jbowens)

___
*[sstable/writer.go, line 1473 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1530#-MwbVnPV7bINXkHZnB1C:-Mwbb7V727MUHHsKGLhG:b-u48y0j) ([raw file](https://github.com/cockroachdb/pebble/blob/2c5224581900d0e02e11f88be532b7db888c076e/sstable/writer.go#L1473)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

Is this prior code wrong? I guess it's up to us how we want to represent the bounds of a sstable containing, for example, a `RANGEKEYUNSET` from `a-c`.

I had been imagining that we'd update `InternalKey.IsExclusiveSentinel` to consider `RANGEKEYSET#inf`, `RANGEKEYUNSET#inf`, `RANGEKEYDEL#inf` all to be exclusive sentinel keys: https://github.com/cockroachdb/pebble/blob/2c5224581900d0e02e11f88be532b7db888c076e/internal/base/internal.go#L359-L360

We could choose always use `RANGEKEYSET#inf` as the largest bound, like you do here. I find it a little confusing though, that you can have a table that only contains `RANGEKEYUNSET`s and/or `RANGEKEYDELETE`s but has a largest bound with a `RANGEKEYSET` kind.
</blockquote></details>

Ah nice. I was going off a comment from another PR about using `IsExclusiveSentinel` for upper bounds (which is limited to rangekeyset currently), but I'd missed this TODO.

I shall amend, as it's less confusing to retain the key kind, as you say.
___
*[ingest_test.go, line 1246 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1530#-MwbYWHd2DLnqjJ8QNbW:-MwbcHtP060UuHH0W4Wb:b-gr7jrk) ([raw file](https://github.com/cockroachdb/pebble/blob/2c5224581900d0e02e11f88be532b7db888c076e/ingest_test.go#L1246)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

Should we unexport `(sstable.WriterMetadata).SmallestPoint` and `(sstable.WriterMetadata).LargestPoint`? It looks like they're only accessed through internally and it might help prevent the same mistake?
</blockquote></details>

I'm working on a separate change that cleans all of this up and takes the "read-only" approach for these fields, but leaves them exported.

**Review by jbowens — APPROVED** [review]
:lgtm: 

> Reviewed 3 of 8 files at r3, 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1530#-:-MwdLNcv2eThXQ4I0JFj:bg7igkv)* status: 7 of 8 files reviewed, all discussions resolved (waiting on @itsbilal)

**Comment by nicktrav** [comment]
TFTR!

**Pull request merged**
