### PR TITLE
batch: Add method to add internal keys

### PR DESCRIPTION
**Pull request by itsbilal**
This change adds an AddInternalKey method that can be used as an umbrella method to add any (indexable) internal key, in place of calling Set,Merge,Delete,SingleDelete, etc. More convenient for external callers that deal with internal keys instead of user keys.

### CODE REVIEW

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2339)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @itsbilal and @RaduBerinde)

___
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2339#-NOWT97S4ukgJHMKAsht):*
is this for `kvBatchSnapshotStrategy.Send` in the disaggregated storage world, which uses a Batch to stream data over?
___
*[`batch.go` line 568 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2339#-NOWX6PC7CyTSgOyZRXS:-NOWX6PC7CyTSgOyZRXT:b17tzm2) ([raw file](https://github.com/cockroachdb/pebble/blob/84650ee02c75c74cff379909ec0929d86daa1545/batch.go#L568)):*
> ```Go
> 		b.prepareDeferredKeyRecord(len(key.UserKey), key.Kind())
> 	default:
> 		b.prepareDeferredKeyValueRecord(keyLen, len(value), key.Kind())
> ```

Will this also work for the various range key operations, and for range delete? Our existing code does things like updating `b.rangeDelIndex` which the code here is not doing.
How about scoping this to write-only batches, since we don't use an indexed batch for CockroachDB snapshots?

I think we should explicitly check for the keys that are not supported and return an error.

**Review by itsbilal — COMMENTED** [review]
TFTR. Sorry for the late PR bump! I guess we finally need this now and I had ignored the PR earlier.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2339#-:-NXkXsnh-PJ-OJ0D5C1I:bmjcv1u)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @RaduBerinde and @sumeerbhola)

___
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2339#-NOWT97S4ukgJHMKAsht):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

is this for `kvBatchSnapshotStrategy.Send` in the disaggregated storage world, which uses a Batch to stream data over?
</blockquote></details>

Yep, basically. Will be used with `ScanInternal` from repl code.
___
*[`batch.go` line 568 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2339#-NOWX6PC7CyTSgOyZRXS:-NXkY-G72cqZx4tsHEiE:b8s9hn4) ([raw file](https://github.com/cockroachdb/pebble/blob/84650ee02c75c74cff379909ec0929d86daa1545/batch.go#L568)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Will this also work for the various range key operations, and for range delete? Our existing code does things like updating `b.rangeDelIndex` which the code here is not doing.
How about scoping this to write-only batches, since we don't use an indexed batch for CockroachDB snapshots?

I think we should explicitly check for the keys that are not supported and return an error.
</blockquote></details>

Good catch, it won't need to support range keys and range deletes. I've just changed the contract to panic if those key kinds are detected. That avoids us from having to force the use of non-indexed batches.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2339#-:-NXl4MQg94uKkTp3Z2ju:bg7igkv)* status: all files reviewed, 2 unresolved discussions (waiting on @RaduBerinde)

**Comment by itsbilal** [comment]
TFTR!

**Pull request merged**
