### PR TITLE
db: introduce TotalDuration to FlushInfo and CompactionInfo events

### PR DESCRIPTION
**Pull request by jbowens**
When a compaction or flush completes, we emit a CompactionEnd or FlushEnd
event. When configured with the logging event listener, these durations are
written to logs.

Previously, these events only contained 1 duration recording the time elapsed
during reading and writing sstables, but it did not include the time to write
the version edit to the manifest or construct the new in-memory representation
of the Version.  With a sufficiently large number of files in L0, this work at
the end of a compaction can be expensive. This change introduces a
TotalDuration field, computed just before the event is emitted. This field
ensures Pebble logs a comprehensive record of the end-to-end wall-time duration
of a compaction too.

### CODE REVIEW

**Review by jbowens — COMMENTED** [review]
We could also record two durations, since both are useful for diagnosing what's happening. Thoughts?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1407#-:-Mqom27nBSS27xcwVHs7:b-u1cw89)* status: 0 of 1 files reviewed, all discussions resolved

**Review by petermattis — COMMENTED** [review]
> We could also record two durations, since both are useful for diagnosing what's happening. Thoughts?

That was my thought upon seeing the commit message. I think it is interesting to understand how long writing the sstables took, and separately how long installing the new version took.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1407#-:-Mqox50S24Sy-qB8_gvx:b-refwo2)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @itsbilal and @sumeerbhola)

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1407#-:-MqpCkROCuQCKMkl5_EL:bg7igkv)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @itsbilal)

**Review by nicktrav — APPROVED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1407)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @itsbilal)

**Review by jbowens — COMMENTED** [review]
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1407#-:-MqpLveWEtteMiy3SdMH:bz5mair)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @itsbilal)

**Pull request merged**
