### PR TITLE
colblk: add data block builder, iterator

### PR DESCRIPTION
**Pull request by jbowens**
Introduce facilities for reading and writing data blocks using user-specified columns for user keys. The full data block schema is not yet complete (eg, the 'is obsolete' bit, etc has not yet been integrated).

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
Great stuff! Flushing some comments after an incomplete pass over `r1`

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3819#-:-O3IfrgVAo3ahqSoyIEc:bsexj94)* status: 0 of 8 files reviewed, 14 unresolved discussions (waiting on @jbowens)

___
*[`sstable/colblk/data_block.go` line 63 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3819#-O3IV4yN3dJ2vJc3ARb8:-O3IV4yN3dJ2vJc3ARb9:b-tzc0kn) ([raw file](https://github.com/cockroachdb/pebble/blob/39bb1588d7642836f0630362a1b6bfaaddfeb47a/sstable/colblk/data_block.go#L63)):*
> ```Go
> type KeyComparison struct {
> 	// PrefixLen is the length of the prefix of the key.
> 	PrefixLen int
> ```

[nit] should we call this `Split` so it's consistent with `Comparer.Split`? Or at least mention the latter in a comment
___
*[`sstable/colblk/data_block.go` line 65 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3819#-O3IVwjH16A8ykootihg:-O3IVwjH16A8ykootihh:bu1n55r) ([raw file](https://github.com/cockroachdb/pebble/blob/39bb1588d7642836f0630362a1b6bfaaddfeb47a/sstable/colblk/data_block.go#L65)):*
> ```Go
> 	PrefixLen int
> 	// PrefixLenShared is the length of the physical prefix of the logical
> 	// prefix that is shared with the previous key. For example, for "apple@1"
> ```

[nit] The struct is described as comparison to an arbitrary key, I'd use "the other key" instead of "previous key"
___
*[`sstable/colblk/data_block.go` line 67 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3819#-O3IVMgF7muXPQnPMTPA:-O3IVMgF7muXPQnPMTPB:b-1fimxh) ([raw file](https://github.com/cockroachdb/pebble/blob/39bb1588d7642836f0630362a1b6bfaaddfeb47a/sstable/colblk/data_block.go#L67)):*
> ```Go
> 	// prefix that is shared with the previous key. For example, for "apple@1"
> 	// and "applied@3" the value is 4 (the length of "appl"). For "apple@1" and
> 	// "apple@10" the value is 5 (the length of "apple"), because shareed
> ```

[nit] shared

I like the logical vs physical way to distinguish. Maybe add `(byte-wise)` after the first `physical` and use logical key prefix
___
*[`sstable/colblk/data_block.go` line 68 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3819#-O3IVfWC7cQKdO1aimtD:-O3IVfWC7cQKdO1aimtE:b-ho9dm1) ([raw file](https://github.com/cockroachdb/pebble/blob/39bb1588d7642836f0630362a1b6bfaaddfeb47a/sstable/colblk/data_block.go#L68)):*
> ```Go
> 	// and "applied@3" the value is 4 (the length of "appl"). For "apple@1" and
> 	// "apple@10" the value is 5 (the length of "apple"), because shareed
> 	// physical prefix within the suffix is not included.
> ```

Maybe "shared bytes within the suffix are not included"
___
*[`sstable/colblk/data_block.go` line 69 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3819#-O3IVDTL-FaCna9obYTL:-O3IVDTL-FaCna9obYTM:b-z84mzy) ([raw file](https://github.com/cockroachdb/pebble/blob/39bb1588d7642836f0630362a1b6bfaaddfeb47a/sstable/colblk/data_block.go#L69)):*
> ```Go
> 	// "apple@10" the value is 5 (the length of "apple"), because shareed
> 	// physical prefix within the suffix is not included.
> 	PrefixLenShared int
> ```

[nit] CommonPrefixLen
___
*[`sstable/colblk/data_block.go` line 74 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3819#-O3IbRIqCDqvqjcO3E7U:-O3IbRIqCDqvqjcO3E7V:b-g3gosr) ([raw file](https://github.com/cockroachdb/pebble/blob/39bb1588d7642836f0630362a1b6bfaaddfeb47a/sstable/colblk/data_block.go#L74)):*
> ```Go
> 	//
> 	//   Compare(key, otherKey)
> 	UserKeyComparison int
> ```

[nit] could make the fields int32s to make it smaller, since we're going to be passing it around in hot paths
___
*[`sstable/colblk/data_block.go` line 83 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3819#-O3IbbMN4Uxx2ndWazmq:-O3IbbMN4Uxx2ndWazmr:b59bp9z) ([raw file](https://github.com/cockroachdb/pebble/blob/39bb1588d7642836f0630362a1b6bfaaddfeb47a/sstable/colblk/data_block.go#L83)):*
> ```Go
> // KeySeeker iterates over the keys in a columnar data block.
> //
> // Users of Pebble who define their own key schema and must implement
> ```

[nit] remove "and"
___
*[`sstable/colblk/data_block.go` line 105 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3819#-O3IeyVS9Plo7JsbILp0:-O3IeyVS9Plo7JsbILp1:bknoig7) ([raw file](https://github.com/cockroachdb/pebble/blob/39bb1588d7642836f0630362a1b6bfaaddfeb47a/sstable/colblk/data_block.go#L105)):*
> ```Go
> 	// MaterializeUserKey materializes the user key of the specified row.
> 	// Implementations may use the memory of dst to avoid an allocation.
> 	MaterializeUserKey(dst []byte, row int) []byte
> ```

[nit] maybe remame `dst` to `buf` since we're *not* appending to it if it's non-zero length
___
*[`sstable/colblk/data_block.go` line 107 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3819#-O3IbhVo3mKU4_swXe6A:-O3IbhVo3mKU4_swXe6B:bnv7dv6) ([raw file](https://github.com/cockroachdb/pebble/blob/39bb1588d7642836f0630362a1b6bfaaddfeb47a/sstable/colblk/data_block.go#L107)):*
> ```Go
> 	MaterializeUserKey(dst []byte, row int) []byte
> 	// Release releases the KeySeeker. It's called when the seeker is no longer
> 	// in use. Implementations may pool KeySeeker implementations.
> ```

[nit] KeySeeker objects
___
*[`sstable/colblk/data_block.go` line 128 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3819#-O3IbvUf1uzTQWKp0nNw:-O3IbvUf1uzTQWKp0nNx:b-lbkln0) ([raw file](https://github.com/cockroachdb/pebble/blob/39bb1588d7642836f0630362a1b6bfaaddfeb47a/sstable/colblk/data_block.go#L128)):*
> ```Go
> 
> // DefaultKeySchema returns the default key schema that decomposes a user key
> // into its lexicographically sorted prefix, and a suffix.
> ```

[nit] "lexicographically sorted" is odd when we're talking about a single user key. Maybe just add a separate "Prefixes are stored in lexicographical order".
___
*[`sstable/colblk/data_block.go` line 163 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3819#-O3IcBcZ4snsxhCiXwX-:-O3IcBc_2SsOhqSfbwgR:bi5d990) ([raw file](https://github.com/cockroachdb/pebble/blob/39bb1588d7642836f0630362a1b6bfaaddfeb47a/sstable/colblk/data_block.go#L163)):*
> ```Go
> 		// The keys share the same MVCC prefix. Compare the suffixes.
> 		cmpv.UserKeyComparison = w.comparer.CompareSuffixes(key[cmpv.PrefixLen:], w.suffixes.LastSlice())
> 		return cmpv
> ```

Here we are assuming that a key (logical) prefix can't be a byte-wise-prefix of another key prefix. I don't think this is always the case (definitely not with the default or testkeys comparer). We need to look at the previous key's split point - maybe `LastKey()` can return that too?

[nit] add an invariant cross-check against `comparer.Compare` (in both return paths)
___
*[`sstable/colblk/data_block.go` line 174 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3819#-O3Id8o9221NK9Mv9LTs:-O3Id8oA-uRYhH56D2cn:bfxserp) ([raw file](https://github.com/cockroachdb/pebble/blob/39bb1588d7642836f0630362a1b6bfaaddfeb47a/sstable/colblk/data_block.go#L174)):*
> ```Go
> 		// Both keys have at least 1 additional byte at which they diverge.
> 		// Compare the diverging byte.
> 		cmpv.UserKeyComparison = cmp.Compare(key[cmpv.PrefixLenShared], lp[cmpv.PrefixLenShared])
> ```

[nit] invariant check that the result is non-zero
___
*[`sstable/colblk/data_block.go` line 274 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3819#-O3Idv_W82kD43SODoj-:-O3Idv_XDleYqqfohZeL:b-w1u50w) ([raw file](https://github.com/cockroachdb/pebble/blob/39bb1588d7642836f0630362a1b6bfaaddfeb47a/sstable/colblk/data_block.go#L274)):*
> ```Go
> 		h := int(uint(l+u) >> 1) // avoid overflow when computing h
> 		// l ≤ h < u
> 		c := ki.comparer.CompareSuffixes(suffix, ki.suffixes.At(h))
> ```

[nit] I'd swap the argument so the "inclusive" case matches the GE condition we are implementing, e.g.
```
if CompareSuffixes(At(h), suffix) >= 0 {
  u = h
} else {
  l = h+1
}
```
___
*[`sstable/colblk/data_block.go` line 295 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3819#-O3IeZds2rG6CSIjjyEr:-O3IeZds2rG6CSIjjyEs:boqqyx6) ([raw file](https://github.com/cockroachdb/pebble/blob/39bb1588d7642836f0630362a1b6bfaaddfeb47a/sstable/colblk/data_block.go#L295)):*
> ```Go
> 	// Ensure i.key has sufficient capacity.
> 	n := len(ki.sharedPrefix) + len(bundlePrefix) + len(rowSuffix) + len(suffix)
> 	if len(dst) < n {
> ```

We should use `cap(dst)` here instead of the caller doing it.

We should actually do `dst = slices.Grow(dst[:0], n)` then `append` to ensure we don't reallocate many times if we have a slowly increasing `n`.

Or if we want to actually have append semantics (which is more typical), we can do `slices.Grow(dst, len(dst) + n)`.

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3819)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @RaduBerinde)

___
*[`sstable/colblk/data_block.go` line 63 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3819#-O3IV4yN3dJ2vJc3ARb8:-O3JKoEC-Xm8i1AOJ0mQ:bb6un1j) ([raw file](https://github.com/cockroachdb/pebble/blob/39bb1588d7642836f0630362a1b6bfaaddfeb47a/sstable/colblk/data_block.go#L63)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] should we call this `Split` so it's consistent with `Comparer.Split`? Or at least mention the latter in a comment
</blockquote></details>

Done
___
*[`sstable/colblk/data_block.go` line 65 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3819#-O3IVwjH16A8ykootihg:-O3JKosZ3PHcEThCcdyV:bb6un1j) ([raw file](https://github.com/cockroachdb/pebble/blob/39bb1588d7642836f0630362a1b6bfaaddfeb47a/sstable/colblk/data_block.go#L65)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] The struct is described as comparison to an arbitrary key, I'd use "the other key" instead of "previous key"
</blockquote></details>

Done
___
*[`sstable/colblk/data_block.go` line 67 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3819#-O3IVMgF7muXPQnPMTPA:-O3JLHlL4bqfO2p8JpJH:bb6un1j) ([raw file](https://github.com/cockroachdb/pebble/blob/39bb1588d7642836f0630362a1b6bfaaddfeb47a/sstable/colblk/data_block.go#L67)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] shared

I like the logical vs physical way to distinguish. Maybe add `(byte-wise)` after the first `physical` and use logical key prefix
</blockquote></details>

Done
___
*[`sstable/colblk/data_block.go` line 68 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3819#-O3IVfWC7cQKdO1aimtD:-O3JLIDoBDf483wPqD6D:bb6un1j) ([raw file](https://github.com/cockroachdb/pebble/blob/39bb1588d7642836f0630362a1b6bfaaddfeb47a/sstable/colblk/data_block.go#L68)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Maybe "shared bytes within the suffix are not included"
</blockquote></details>

Done
___
*[`sstable/colblk/data_block.go` line 69 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3819#-O3IVDTL-FaCna9obYTL:-O3JLLnqBUcv9HowtY8d:bb6un1j) ([raw file](https://github.com/cockroachdb/pebble/blob/39bb1588d7642836f0630362a1b6bfaaddfeb47a/sstable/colblk/data_block.go#L69)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] CommonPrefixLen
</blockquote></details>

Done
___
*[`sstable/colblk/data_block.go` line 74 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3819#-O3IbRIqCDqvqjcO3E7U:-O3JM9PB4JrhVzab-MXX:bb6un1j) ([raw file](https://github.com/cockroachdb/pebble/blob/39bb1588d7642836f0630362a1b6bfaaddfeb47a/sstable/colblk/data_block.go#L74)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] could make the fields int32s to make it smaller, since we're going to be passing it around in hot paths
</blockquote></details>

Done
___
*[`sstable/colblk/data_block.go` line 83 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3819#-O3IbbMN4Uxx2ndWazmq:-O3JLSn606YxetwER-cQ:bb6un1j) ([raw file](https://github.com/cockroachdb/pebble/blob/39bb1588d7642836f0630362a1b6bfaaddfeb47a/sstable/colblk/data_block.go#L83)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] remove "and"
</blockquote></details>

Done
___
*[`sstable/colblk/data_block.go` line 105 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3819#-O3IeyVS9Plo7JsbILp0:-O3JMV2H8qQ8q1NIH-ra:bb6un1j) ([raw file](https://github.com/cockroachdb/pebble/blob/39bb1588d7642836f0630362a1b6bfaaddfeb47a/sstable/colblk/data_block.go#L105)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] maybe remame `dst` to `buf` since we're *not* appending to it if it's non-zero length
</blockquote></details>

Done
___
*[`sstable/colblk/data_block.go` line 107 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3819#-O3IbhVo3mKU4_swXe6A:-O3JMZW1CQS9YFKMyhuq:bb6un1j) ([raw file](https://github.com/cockroachdb/pebble/blob/39bb1588d7642836f0630362a1b6bfaaddfeb47a/sstable/colblk/data_block.go#L107)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] KeySeeker objects
</blockquote></details>

Done
___
*[`sstable/colblk/data_block.go` line 128 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3819#-O3IbvUf1uzTQWKp0nNw:-O3JMhmP182dbs825913:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/39bb1588d7642836f0630362a1b6bfaaddfeb47a/sstable/colblk/data_block.go#L128)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] "lexicographically sorted" is odd when we're talking about a single user key. Maybe just add a separate "Prefixes are stored in lexicographical order".
</blockquote></details>

Done.
___
*[`sstable/colblk/data_block.go` line 163 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3819#-O3IcBcZ4snsxhCiXwX-:-O3JN4PFA4ANKU4FaTnL:bv4j6dk) ([raw file](https://github.com/cockroachdb/pebble/blob/39bb1588d7642836f0630362a1b6bfaaddfeb47a/sstable/colblk/data_block.go#L163)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Here we are assuming that a key (logical) prefix can't be a byte-wise-prefix of another key prefix. I don't think this is always the case (definitely not with the default or testkeys comparer). We need to look at the previous key's split point - maybe `LastKey()` can return that too?

[nit] add an invariant cross-check against `comparer.Compare` (in both return paths)
</blockquote></details>

We're taking advantage of the lexicographical ordering. Since prev ≤ key, CommonPrefixLen == PrefixLen implies equality of prefix. Added a comment and assertion that clarifies this.

Cross-checking against `Compare` would requires an allocation (to materialize the previous key), which I think is too much even behind `invariants` in such a hot path
___
*[`sstable/colblk/data_block.go` line 174 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3819#-O3Id8o9221NK9Mv9LTs:-O3JUU030jgJmqTPqEOU:bb6un1j) ([raw file](https://github.com/cockroachdb/pebble/blob/39bb1588d7642836f0630362a1b6bfaaddfeb47a/sstable/colblk/data_block.go#L174)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] invariant check that the result is non-zero
</blockquote></details>

Done
___
*[`sstable/colblk/data_block.go` line 274 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3819#-O3Idv_W82kD43SODoj-:-O3JYDIG4wkt32D0_k5W:bb6un1j) ([raw file](https://github.com/cockroachdb/pebble/blob/39bb1588d7642836f0630362a1b6bfaaddfeb47a/sstable/colblk/data_block.go#L274)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] I'd swap the argument so the "inclusive" case matches the GE condition we are implementing, e.g.
```
if CompareSuffixes(At(h), suffix) >= 0 {
  u = h
} else {
  l = h+1
}
```
</blockquote></details>

Done

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3819)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @jbowens)

___
*[`sstable/colblk/data_block.go` line 163 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3819#-O3IcBcZ4snsxhCiXwX-:-O3NIfrZ6QXX_qRRmIgi:b7x5pp8) ([raw file](https://github.com/cockroachdb/pebble/blob/39bb1588d7642836f0630362a1b6bfaaddfeb47a/sstable/colblk/data_block.go#L163)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

We're taking advantage of the lexicographical ordering. Since prev ≤ key, CommonPrefixLen == PrefixLen implies equality of prefix. Added a comment and assertion that clarifies this.

Cross-checking against `Compare` would requires an allocation (to materialize the previous key), which I think is too much even behind `invariants` in such a hot path
</blockquote></details>

Nice, makes sense, I missed that PrefixLen would be longer for this key.

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3819)* status: 0 of 11 files reviewed, 2 unresolved discussions (waiting on @sumeerbhola)

___
*[`sstable/colblk/prefix_bytes.go` line 342 at r9](https://reviewable.io/reviews/cockroachdb/pebble/3819#-O3nouzO1aZ3g9c2g-U5:-O3nouzO1aZ3g9c2g-U6:bamyfnx) ([raw file](https://github.com/cockroachdb/pebble/blob/791b3749feb52978b973d79904fb79632b38046e/sstable/colblk/prefix_bytes.go#L342)):*
> ```Go
> 		it.cap = it.len << 1
> 		it.ptr = mallocgc(uintptr(it.cap), nil, false)
> 		memmove(it.ptr, b.rawBytes.data, uintptr(b.sharedPrefixLen))
> ```

I'm at a loss here. This commit seems to show a consistent ~3% _regression_ in the PrefixBytes iteration benchmark when we remove the logic to grow the buffer if necessary:

```
goos: darwin
goarch: arm64
pkg: github.com/cockroachdb/pebble/sstable/colblk
                                     │   old.txt   │              new.txt               │
                                     │   sec/op    │   sec/op     vs base               │
PrefixBytes/alphaLen=2/iteration-10    5.611n ± 1%   5.811n ± 1%  +3.56% (p=0.000 n=25)
PrefixBytes/alphaLen=5/iteration-10    5.701n ± 2%   5.877n ± 1%  +3.09% (p=0.000 n=25)
PrefixBytes/alphaLen=26/iteration-10   5.554n ± 1%   5.810n ± 1%  +4.61% (p=0.000 n=25)
geomean                                5.622n        5.833n       +3.75%
```

**Review by RaduBerinde — APPROVED** [review]
:lgtm: overall. I will try to do one more pass in more depth but feel free to merge before that.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3819#-:-O4C5vii4noTTmUmAny5:b-znzn1)* status: 0 of 13 files reviewed, 5 unresolved discussions (waiting on @jbowens and @sumeerbhola)

___
*[`-- commits` line 17 at r12](https://reviewable.io/reviews/cockroachdb/pebble/3819#-O4Bwne4Bnip4lRoZg_v):*
What a great idea!
___
*[`-- commits` line 18 at r12](https://reviewable.io/reviews/cockroachdb/pebble/3819#-O4BwlYx0ycncTMRqLNH):*
[nit] contained
___
*[`sstable/colblk/data_block.go` line 59 at r10](https://reviewable.io/reviews/cockroachdb/pebble/3819#-O4Bt6q80zr-1xh1niVg:-O4Bt6q80zr-1xh1niVh:biu5dqc) ([raw file](https://github.com/cockroachdb/pebble/blob/838b01bd2337eaec16bdcd7f8dffdc2475445361/sstable/colblk/data_block.go#L59)):*
> ```Go
> 	// be stable until the next call to WriteKey or the KeyWriter columns are
> 	// finished.
> 	WriteKey(row int, key []byte, keyPrefixLen, keyPrefixLenSharedWithPrev int32) (unsafePrefix []byte)
> ```

[nit] The return value is strange here, the caller already has this information. Maybe explain a bit more the usecase you have in mind.
___
*[`sstable/colblk/prefix_bytes.go` line 342 at r9](https://reviewable.io/reviews/cockroachdb/pebble/3819#-O3nouzO1aZ3g9c2g-U5:-O4C-Aij9rKuwBMSA2uJ:bn4n8ap) ([raw file](https://github.com/cockroachdb/pebble/blob/791b3749feb52978b973d79904fb79632b38046e/sstable/colblk/prefix_bytes.go#L342)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

I'm at a loss here. This commit seems to show a consistent ~3% _regression_ in the PrefixBytes iteration benchmark when we remove the logic to grow the buffer if necessary:

```
goos: darwin
goarch: arm64
pkg: github.com/cockroachdb/pebble/sstable/colblk
                                     │   old.txt   │              new.txt               │
                                     │   sec/op    │   sec/op     vs base               │
PrefixBytes/alphaLen=2/iteration-10    5.611n ± 1%   5.811n ± 1%  +3.56% (p=0.000 n=25)
PrefixBytes/alphaLen=5/iteration-10    5.701n ± 2%   5.877n ± 1%  +3.09% (p=0.000 n=25)
PrefixBytes/alphaLen=26/iteration-10   5.554n ± 1%   5.810n ± 1%  +4.61% (p=0.000 n=25)
geomean                                5.622n        5.833n       +3.75%
```
</blockquote></details>

I tried it too and see something similar. I can recover the difference if I remove the `invariants.Enabled` from the first length check in SetNext. I looked at the assembly and it's pretty much the same other than the extra check and panic handling code..

FWIW I saw paradoxical results with benchmarks that have nanosecond-order times on multiple occasions (e.g. a code difference that wasn't even being run). I suspect that the way important instruction blocks align to cachelines might play a role. In any case, I would not worry about it.

One optimization here would be to maintain the value of `At(offsetIndex+1)` in the struct. We would only need to do a single `At` in the `SetNext` fast path instead of two.

I think it would be a good idea to do the length checks in all builds, if there is a bug somewhere (perhaps on the building side), the result could be impossible to debug.

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3819)* status: 0 of 13 files reviewed, 3 unresolved discussions (waiting on @RaduBerinde and @sumeerbhola)

___
*[`-- commits` line 17 at r12](https://reviewable.io/reviews/cockroachdb/pebble/3819#-O4Bwne4Bnip4lRoZg_v):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

What a great idea!
</blockquote></details>

:raised_hands: 
___
*[`sstable/colblk/data_block.go` line 59 at r10](https://reviewable.io/reviews/cockroachdb/pebble/3819#-O4Bt6q80zr-1xh1niVg:-O4LWldf8D0c39EjmVT3:b-68neri) ([raw file](https://github.com/cockroachdb/pebble/blob/838b01bd2337eaec16bdcd7f8dffdc2475445361/sstable/colblk/data_block.go#L59)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] The return value is strange here, the caller already has this information. Maybe explain a bit more the usecase you have in mind.
</blockquote></details>

I think this is no longer necessary because I added `ComparePrev` to the `KeyWriter` interface. Previously, this return value was what allowed the sstable writer to compare against the previous key's prefix without having to copy it. I'll remove it and we can resurrect it if I'm overlooking something.
___
*[`sstable/colblk/prefix_bytes.go` line 342 at r9](https://reviewable.io/reviews/cockroachdb/pebble/3819#-O3nouzO1aZ3g9c2g-U5:-O4LVydS1QXjWhWPtI9U:b-z9b2ka) ([raw file](https://github.com/cockroachdb/pebble/blob/791b3749feb52978b973d79904fb79632b38046e/sstable/colblk/prefix_bytes.go#L342)):*
> One optimization here would be to maintain the value of `At(offsetIndex+1)` in the struct. We would only need to do a single `At` in the `SetNext` fast path instead of two.

I wonder if this won't be as important now with your adjustment to the offset encoding and specialized offset lookup? Eg, is it actually faster to add an additional store the value of `At(offsetIndex+1)` and then load it, rather than performing the `At(offsetIndex+1)` load?

> I think it would be a good idea to do the length checks in all builds, if there is a bug somewhere (perhaps on the building side), the result could be impossible to debug.

Yeah, I debated this. You're right, we should be conservative

**Comment by RaduBerinde** [comment]
*[`sstable/colblk/prefix_bytes.go` line 342 at r9](https://reviewable.io/reviews/cockroachdb/pebble/3819#-O3nouzO1aZ3g9c2g-U5:-O4N0xU7D1Cw-mO86a7M:bovw88o) ([raw file](https://github.com/cockroachdb/pebble/blob/791b3749feb52978b973d79904fb79632b38046e/sstable/colblk/prefix_bytes.go#L342)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

> One optimization here would be to maintain the value of `At(offsetIndex+1)` in the struct. We would only need to do a single `At` in the `SetNext` fast path instead of two.

I wonder if this won't be as important now with your adjustment to the offset encoding and specialized offset lookup? Eg, is it actually faster to add an additional store the value of `At(offsetIndex+1)` and then load it, rather than performing the `At(offsetIndex+1)` load?

> I think it would be a good idea to do the length checks in all builds, if there is a bug somewhere (perhaps on the building side), the result could be impossible to debug.

Yeah, I debated this. You're right, we should be conservative
</blockquote></details>

Yeah I think it won't matter with the new offset lookup

**Pull request merged**
