### PR TITLE
keyspan: reimplement straddle spans in LevelIter

### PR DESCRIPTION
**Pull request by RaduBerinde**
This change reimplements the way straddle spans are generated in LevelIter. The existing code is hard to change to allow empty files in range key mode. It also makes things harder to reason about because there are subtle differences in state depending on the mode.

We now store a generalized position which can be "at" a file or "before/after" a file (corresponding to a straddle span).

### CODE REVIEW

**Review by jbowens — COMMENTED** [review]
Much cleaner!

:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3724#-:-O0o8HNjAcRucK1tiD06:b-c3mfdn)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @RaduBerinde)

___
*[`internal/keyspan/keyspanimpl/level_iter.go` line 133 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3724#-O0o6IyHEBvJ2xfANHIG:-O0o6IyI9jH6xqotdZxC:bwu2z7v) ([raw file](https://github.com/cockroachdb/pebble/blob/e983ad67388708d27edb6f1a0d015247acba1925/internal/keyspan/keyspanimpl/level_iter.go#L133)):*
> ```Go
> // (either after one file, or before the other file). We use the one which makes
> // it easier to keep l.file in sync with the l.files iterator (which depends on
> // the iteration direfction).
> ```

nit: "direction"
___
*[`internal/keyspan/keyspanimpl/level_iter.go` line 138 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3724#-O0o8Mbm1h_v6ZVj4XTB:-O0o8Mbm1h_v6ZVj4XTC:b-fkqwys) ([raw file](https://github.com/cockroachdb/pebble/blob/e983ad67388708d27edb6f1a0d015247acba1925/internal/keyspan/keyspanimpl/level_iter.go#L138)):*
> ```Go
> // all the files: beforeFile with nil file indicates that the iterator is
> // positioned after the last file; afterFile with nil file indicates that the
> // iterator is positioned before the first file.
> ```

nit: I find this a little confusing, but I'm at a loss for better terminology—maybe "forwardNextFile" and "backwardPrevFile"?
___
*[`internal/keyspan/keyspanimpl/level_iter.go` line 162 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3724#-O0o70Cp4c93nkovfl2d:-O0o70Cp4c93nkovfl2e:btivcgi) ([raw file](https://github.com/cockroachdb/pebble/blob/e983ad67388708d27edb6f1a0d015247acba1925/internal/keyspan/keyspanimpl/level_iter.go#L162)):*
> ```Go
> 			// positioning operations. Consider this example, with a b-c range key:
> 			//   SeekGE(a) -> a-b:{}
> 			//   Next() -> b-c{(#5,RANGEKEYSET,@4,foo)} Prev() -> nil
> ```

nit: seems like the `Prev() -> nil` bit of this comment should be on a new line
___
*[`internal/keyspan/keyspanimpl/level_iter.go` line 443 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3724#-O0o7wIzCRs_plBR-WpK:-O0o7wIzCRs_plBR-WpL:bkyty76) ([raw file](https://github.com/cockroachdb/pebble/blob/e983ad67388708d27edb6f1a0d015247acba1925/internal/keyspan/keyspanimpl/level_iter.go#L443)):*
> ```Go
> // files in the level, in the order they appear in the level.
> func (l *LevelIter) needStraddleSpan(f1, f2 *manifest.FileMetadata) bool {
> 	// We directly use range key bounds directly because that is the current
> ```

nit: repeat "directly"s 
___
*[`internal/keyspan/keyspanimpl/level_iter.go` line 449 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3724#-O0o81iw3kBuwhlHWVmS:-O0o81iw3kBuwhlHWVmT:bvug8he) ([raw file](https://github.com/cockroachdb/pebble/blob/e983ad67388708d27edb6f1a0d015247acba1925/internal/keyspan/keyspanimpl/level_iter.go#L449)):*
> ```Go
> 
> // makeStraddleSpan returns a straddle span that covers the gap between f1 and f2.
> func (l *LevelIter) makeStraddleSpan(f1, f2 *manifest.FileMetadata) *keyspan.Span {
> ```

nit: maybe name `f1` and `f2` to clarify that f1 must be previous to f2

**Review by RaduBerinde — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3724#-:-O0oiNgTBe1xVaDNyYg-:b-814g8k)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @jbowens)

___
*[`internal/keyspan/keyspanimpl/level_iter.go` line 138 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3724#-O0o8Mbm1h_v6ZVj4XTB:-O0ohm2W2JCh4dfGTnMA:b-p2b76p) ([raw file](https://github.com/cockroachdb/pebble/blob/e983ad67388708d27edb6f1a0d015247acba1925/internal/keyspan/keyspanimpl/level_iter.go#L138)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

nit: I find this a little confusing, but I'm at a loss for better terminology—maybe "forwardNextFile" and "backwardPrevFile"?
</blockquote></details>

I added some diagrams, does this help?

**Comment by RaduBerinde** [comment]
@jbowens can you stamp the PR with an approval? Thanks!

**Review by jbowens — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3724)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @RaduBerinde)

___
*[`internal/keyspan/keyspanimpl/level_iter.go` line 138 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3724#-O0o8Mbm1h_v6ZVj4XTB:-O1INYzY5xAlEm3VSp6r:bnxx8e0) ([raw file](https://github.com/cockroachdb/pebble/blob/e983ad67388708d27edb6f1a0d015247acba1925/internal/keyspan/keyspanimpl/level_iter.go#L138)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I added some diagrams, does this help?
</blockquote></details>

It does!

**Pull request merged**
