### PR TITLE
db: fix L0->LBase input expansion bug

### LINKED ISSUE #958: internal/metamorphic: TestMeta failed
Pebble nightly metamorphic test failed on [879f3bfeef077b895c9dae801ac97383a93e258e](https://github.com/cockroachdb/pebble/commits/879f3bfeef077b895c9dae801ac97383a93e258e):

```
            // INFO: write stall ending
            db.Delete("zwhpeazg") // <nil> #3614
            iter22.Next() // [false] pebble: SeekPrefixGE supplied with key outside of upper bound #3615
            iter22.Next() // [false] pebble: SeekPrefixGE supplied with key outside of upper bound #3616
            iter22.SeekPrefixGE("ahhudjig") // [false] pebble: SeekPrefixGE supplied with key outside of lower bound #3617
            // INFO: [JOB 2602] compacting L0 [002514] (856 B) + L5 [002501] (780 B)
            snap27.Get("qplmyjl") // [""] pebble: not found #3618
            // INFO: [JOB 2602] compacting: sstable created 002518
            snap27.Get("cslftr") // [""] pebble: not found #3619
            // INFO: write stall beginning: memtable count limit reached
            // INFO: [JOB 2601] MANIFEST created 002519
            // INFO: [JOB 2601] flushed 2 memtables to L0 [002517] (778 B), in 0.0s, output rate 1.4 M/s
            // INFO: [JOB 2601] WAL deleted 002510
            // INFO: [JOB 2601] MANIFEST deleted 002515
            // INFO: [JOB 2604] WAL created 002520
            // INFO: write stall ending
            db.DeleteRange("rnaprsubi", "unjlfoeid") // <nil> #3620
            iter22.SeekLT("qigmthv") // [true,"dbvgwhq","hpemhntcrwa"] <nil> #3621
            iter22.Last() // [true,"dbvgwhq","hpemhntcrwa"] <nil> #3622
            iter22.SeekLT("rjanuiq") // [true,"dbvgwhq","hpemhntcrwa"] <nil> #3623
            // INFO: write stall beginning: memtable count limit reached
            // INFO: [JOB 2602] MANIFEST created 002521
            // INFO: [JOB 2602] compacted L0 [002514] (856 B) + L5 [002501] (780 B) -> L5 [002518] (856 B), in 0.0s, output rate 6.2 M/s
            // INFO: [JOB 2602] sstable deleted 002501
            // INFO: [JOB 2606] flushing 4 memtables to L0
            // INFO: [JOB 2602] sstable deleted 002514
            // INFO: [JOB 2602] MANIFEST deleted 002519
            // INFO: [JOB 2606] flushing: sstable created 002522
            // INFO: [JOB 2607] compacting L0 [002517] (778 B) + L5 [002499] (1.1 K)
            // INFO: [JOB 2607] compacting: sstable created 002523
            // INFO: [JOB 2606] flushing: sstable created 002524
            // INFO: [JOB 2607] MANIFEST created 002525
            // INFO: [JOB 2607] compacted L0 [002517] (778 B) + L5 [002499] (1.1 K) -> L5 [002523] (1.2 K), in 0.0s, output rate 7.5 M/s
            // INFO: [JOB 2607] sstable deleted 002499
            // INFO: [JOB 2607] sstable deleted 002517
            // INFO: [JOB 2607] MANIFEST deleted 002521
            // INFO: [JOB 2606] MANIFEST created 002526
            // INFO: [JOB 2606] flushed 4 memtables to L0 [002522 002524] (1.6 K), in 0.0s, output rate 1.8 M/s
            // INFO: [JOB 2606] WAL deleted 002513
            // INFO: [JOB 2606] WAL deleted 002516
            // INFO: [JOB 2606] MANIFEST deleted 002525
            // INFO: [JOB 2610] WAL created 002527
            // INFO: write stall ending
            db.Delete("sloyluqhw") // <nil> #3624
            // INFO: [JOB 2612] compacting L0 [002524 002522] (1.6 K) + L5 [002518] (856 B)
            // INFO: [JOB 2612] compacting: sstable created 002529
            // INFO: [JOB 2611] WAL created 002528
            // INFO: [JOB 2613] flushing 2 memtables to L0
            // INFO: [JOB 2613] flushing: sstable created 002530
            // INFO: [JOB 2612] compaction to L5 error: pebble: internal error: L5 files 002523 and 002529 have overlapping ranges: [xuvv#900,RANGEDEL-zwhpeazg#781,SET] vs [mmatxgyqudk#907,RANGEDEL-zwhpeazg#909,DEL]

```

<details><summary>More</summary><p>

Artifacts: [meta](https://viewLog.html?buildId=2338724&tab=artifacts#meta)
```
go test -mod=vendor -tags 'invariants' -exec 'stress -p 1' -timeout 0 -test.v -run TestMeta$ ./internal/metamorphic -seed 1601611138394694662
```

<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub>
</p></details>

### PR DESCRIPTION
**Pull request by jbowens**
The fix in #955 was bad. It assumed that `SeekGE(pc.largest.UserKey)`
would seek to exactly the last base file included in the compaction,
which is not true if an L0 input extends beyond the last base file.

I took this as an indication this logic is too subtle (like #955's TODO
alludes) and a refactor to access unbounded LevelIterators is
worthwhile.

Fix #958.

### CODE REVIEW

**Review by petermattis — APPROVED** [review]
:lgtm: modulo possible simplification.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/959#-:-MIf2sgfBmgaYNDP0kSW:b8udpan)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @itsbilal, @jbowens, and @petermattis)

___
*[compaction_picker.go, line 237 at r1](https://reviewable.io/reviews/cockroachdb/pebble/959#-MIf1x-nDap-U8oAtlvb:-MIf1x-o0YjDCKLmpRnY:b-2pcywy) ([raw file](https://github.com/cockroachdb/pebble/blob/a46086e1979719be10a5bb7da1e2bb4b61397085/compaction_picker.go#L237)):*
> ```Go
> 			}
> 		} else {
> 			start, end := pc.outputLevel.files.Bounds()
> ```

Could this use `Reslice` instead? I'm slightly uneasy with `Bounds` returning unbounded iterators as that isn't clear from the name. I'm imagining something like:

```
pc.outputLevel.files.Reslice(func(start, end *LevelIterator) {
  if sm := start.Prev(); sm != nil {
    smallestBaseKey = sm.Largest
  }
  if la := end.Next(); la != nil {
    largestBaseKey = la.Smallest
  }
})
```

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/959)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @itsbilal and @petermattis)

___
*[compaction_picker.go, line 237 at r1](https://reviewable.io/reviews/cockroachdb/pebble/959#-MIf1x-nDap-U8oAtlvb:-MIf6FOP3CRzHEXdsC4I:b9qk3fe) ([raw file](https://github.com/cockroachdb/pebble/blob/a46086e1979719be10a5bb7da1e2bb4b61397085/compaction_picker.go#L237)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Could this use `Reslice` instead? I'm slightly uneasy with `Bounds` returning unbounded iterators as that isn't clear from the name. I'm imagining something like:

```
pc.outputLevel.files.Reslice(func(start, end *LevelIterator) {
  if sm := start.Prev(); sm != nil {
    smallestBaseKey = sm.Largest
  }
  if la := end.Next(); la != nil {
    largestBaseKey = la.Smallest
  }
})
```
</blockquote></details>

:+1: I updated it to use `Reslice`, with a comment clarifying that we intentionally discard the return value and that `outputLevel.files` is not modified.

**Review by itsbilal — APPROVED** [review]
LGTM, thanks for getting to the bottom of this quickly! I like how the new code is very concise too.

(Unrelated: reviewable seems to be failing for me with a Firebase error, so I'm reviewing this on github directly)

**Review by jbowens — COMMENTED** [review]
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/959#-:-MIfHx8I0jEBrRqVM6ke:bz5mair)* status: 0 of 2 files reviewed, all discussions resolved

**Pull request merged**
