### PR TITLE
db: tolerate errors during async ingest sstable validation

### PR DESCRIPTION
**Pull request by jbowens**
After a table is ingested, an asynchronous job reads the table and validates
its checksums. If corruption is uncovered, the job fatals the process.
Previously, a transient I/O error would also fatal the process, even if the I/O
error did not indicate corruption. This commit adapts this code path to log the
error to the BackgroundError event listener and re-queue the file for
validation.

Informs #270.
Informs #1115.

### CODE REVIEW

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2982)* status: all files reviewed, 3 unresolved discussions (waiting on @jbowens)

___
*[`ingest_test.go` line 3163 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2982#-Ng5XGj1EHPFmsakJMEd:-Ng5XGj1EHPFmsakJMEe:b-35kvzk) ([raw file](https://github.com/cockroachdb/pebble/blob/7ca1c72e7b5f5720a90963edc5655f2c69131599/ingest_test.go#L3163)):*
> ```Go
> 		errLocationIngest
> 		errLocationValidation
> 		errLocationBackground
> ```

This could use a comment to distinguish it from `errLocationValidation`. It seems both are during validation, while one is a background error and does not cause a Fatalf.
Maybe call it `errLocationValidationBackgroundErr`.
___
*[`ingest_test.go` line 3217 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2982#-Ng5WiucCGy_g098Ujlj:-Ng5WiucCGy_g098Ujlk:b558pao) ([raw file](https://github.com/cockroachdb/pebble/blob/7ca1c72e7b5f5720a90963edc5655f2c69131599/ingest_test.go#L3217)):*
> ```Go
> 			wantErrType: errLocationBackground,
> 			errorfsInjector: errorfs.InjectorFunc(func(op errorfs.Op, path string) error {
> 				// Inject an error on the first read-at operation on an sstable.
> ```

Won't there be a call to `ReadAt` during the ingest to read certain blocks when we open an iterator to look for overlaps, which would make this errLocationIngest?
___
*[`ingest_test.go` line 3322 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2982#-Ng5W3GZ0bL9eVze4uyC:-Ng5W3GZ0bL9eVze4uyD:b-dpcaya) ([raw file](https://github.com/cockroachdb/pebble/blob/7ca1c72e7b5f5720a90963edc5655f2c69131599/ingest_test.go#L3322)):*
> ```Go
> 					f, err = fs.OpenReadWrite(ingestTableName)
> 					require.NoError(t, err)
> 					corrupt(f)
> ```

I am missing something -- why does corrupting before doing the ingest allow for corruption to be discovered in `errLocationValidation`? Won't it be discovered in ingest itself when opening the iterator and seeking?
Is this because this is always used with `corruptionLocationInternal`, so the relevant block does not get read during the ingest?

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2982)* status: all files reviewed, 3 unresolved discussions (waiting on @sumeerbhola)

___
*[`ingest_test.go` line 3163 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2982#-Ng5XGj1EHPFmsakJMEd:-NgK8fZn4-IukpswrQkv:b-u4a9jy) ([raw file](https://github.com/cockroachdb/pebble/blob/7ca1c72e7b5f5720a90963edc5655f2c69131599/ingest_test.go#L3163)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

This could use a comment to distinguish it from `errLocationValidation`. It seems both are during validation, while one is a background error and does not cause a Fatalf.
Maybe call it `errLocationValidationBackgroundErr`.
</blockquote></details>

I added some comments and did some renaming to make this clearer:

errLocation -> errReportLocation
errLocationValidation -> errReportLocationFatal
errLocationBackground -> errReportLocationBackgroundError
___
*[`ingest_test.go` line 3217 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2982#-Ng5WiucCGy_g098Ujlj:-NgK7kL71RMZPEx65goD:bibi056) ([raw file](https://github.com/cockroachdb/pebble/blob/7ca1c72e7b5f5720a90963edc5655f2c69131599/ingest_test.go#L3217)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Won't there be a call to `ReadAt` during the ingest to read certain blocks when we open an iterator to look for overlaps, which would make this errLocationIngest?
</blockquote></details>

This was subtle. This test creates to-be-ingested sstables at the path `ext` which doesn't have the `.sst` extension, and so are excluded from the error injection. I added an explicit `path != "ext"` condition and expanded the comment to make this clearer.
___
*[`ingest_test.go` line 3322 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2982#-Ng5W3GZ0bL9eVze4uyC:-NgKAHWlBw8mS-pQvOJa:b-8ofb7f) ([raw file](https://github.com/cockroachdb/pebble/blob/7ca1c72e7b5f5720a90963edc5655f2c69131599/ingest_test.go#L3322)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I am missing something -- why does corrupting before doing the ingest allow for corruption to be discovered in `errLocationValidation`? Won't it be discovered in ingest itself when opening the iterator and seeking?
Is this because this is always used with `corruptionLocationInternal`, so the relevant block does not get read during the ingest?
</blockquote></details>

That's right, `Ingest` won't read the corrupted blocks when used with `corruptionLocationInternal`. I added an explanatory comment at the `corruptionLocation` enum declaration.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2982#-:-NgL8JR2-mqKb0QS7VYg:bg7igkv)* status: all files reviewed, 4 unresolved discussions (waiting on @jbowens)

___
*[`ingest_test.go` line 3166 at r4](https://reviewable.io/reviews/cockroachdb/pebble/2982#-NgL7ot97fjlz3t1NNh7:-NgL7ot97fjlz3t1NNh8:bfey7ht) ([raw file](https://github.com/cockroachdb/pebble/blob/3fabe145657cd4258172c9cadcae6d5116d1408d/ingest_test.go#L3166)):*
> ```Go
> 	)
> 	// The errReportLocation type defines an enum to allow tests to enforce
> 	// expectations about how an error surfced during ingestion or validation is
> ```

nit: surfaced

**Review by jbowens — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2982#-:-NgLOni32oKejYtXYpvS:b-814g8k)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @sumeerbhola)

**Pull request merged**
