### PR TITLE
tool: enhance db check

### PR DESCRIPTION
**Pull request by rohansuri**
Include new checks in DB.CheckLevels:
1) Point key ordering in SSTs.
2) Ordering and fragmentation of rangeDelV2 formatted blocks in SSTs.
3) Successful processing of all MERGE records.

Issue: #264

### CODE REVIEW

**Comment by petermattis** [comment]
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/544)

**Comment by rohansuri** [comment]
Will address the remaining comments tomorrow and check why the build is failing.

**Comment by rohansuri** [comment]
@petermattis PTAL.

**Comment by rohansuri** [comment]
@petermattis TFYR! PTAL.

**Pull request merged**
