### PR TITLE
cmd/pebble: replay ingests, flushes faithfully

### PR DESCRIPTION
**Pull request by jbowens**
This PR has two commits. One introduces a private hook for ingesting sstables with nonzero sequence numbers directly into L0. The other adapts cmd/pebble's bench compact commands to use the new hook.

### CODE REVIEW

**Comment by petermattis** [comment]
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/666)

**Comment by jbowens** [comment]
Screen Shot 2020-05-12 at 9 29 55 AM

This doesn't bode well...

**Comment by jbowens** [comment]
I just realized there's a bug here. When we replay an ingest, we increment `logSeqNum`. It's possible to increment `logSeqNum` past the smallest unflushed sequence number that was in the memtable. When we go to replay the next flush, we'll detect that we're trying to flush a table with a sequence number less than the current `logSeqNum` and error.

Maybe we could use the `VersionEdit.LastSeqNum` field to dictate sequence numbers when we replay an Ingest? Going to think on it

**Comment by jbowens** [comment]
Errr, I guess we _have_ the ingested file's original sequence number and could use that. We would need to not error when `flushExternalTable` is called with files that extend below the current logSeqNum though. Not sure if there's any consistency consequences to the missing context that there are committed, unflushed values in the memtable.

**Pull request merged**
