### PR TITLE
*: avoid various range key iteration allocations

### PR DESCRIPTION
**Pull request by jbowens**
Avoid various allocations during range key iteration by including additional buffers and slices on the pooled `iteratorRangeKeyState` type.

```
name                                                                      old speed      new speed      delta
MVCCScan_Pebble/rows=1/versions=1/valueSize=64/numRangeKeys=0-24          6.61MB/s ± 3%  6.76MB/s ± 3%   +2.29%  (p=0.005 n=9+10)
MVCCScan_Pebble/rows=1/versions=1/valueSize=64/numRangeKeys=1-24          4.00MB/s ± 2%  4.09MB/s ± 3%   +2.22%  (p=0.014 n=9+9)
MVCCScan_Pebble/rows=1/versions=1/valueSize=64/numRangeKeys=100-24         420kB/s ± 0%   452kB/s ± 3%   +7.62%  (p=0.000 n=6+10)
MVCCScan_Pebble/rows=1/versions=2/valueSize=64/numRangeKeys=0-24          5.49MB/s ± 2%  5.52MB/s ± 4%     ~     (p=0.540 n=10+10)
MVCCScan_Pebble/rows=1/versions=2/valueSize=64/numRangeKeys=1-24          3.34MB/s ± 3%  3.43MB/s ± 3%   +2.64%  (p=0.008 n=10+10)
MVCCScan_Pebble/rows=1/versions=2/valueSize=64/numRangeKeys=100-24         454kB/s ± 1%   484kB/s ± 1%   +6.61%  (p=0.000 n=10+10)
MVCCScan_Pebble/rows=1/versions=10/valueSize=64/numRangeKeys=0-24         3.48MB/s ± 3%  3.46MB/s ± 3%     ~     (p=0.364 n=10+10)
MVCCScan_Pebble/rows=1/versions=10/valueSize=64/numRangeKeys=1-24         2.33MB/s ± 1%  2.34MB/s ± 3%     ~     (p=0.562 n=9+10)
MVCCScan_Pebble/rows=1/versions=10/valueSize=64/numRangeKeys=100-24        448kB/s ± 3%   482kB/s ± 3%   +7.64%  (p=0.000 n=10+9)
MVCCScan_Pebble/rows=1/versions=100/valueSize=64/numRangeKeys=0-24        1.69MB/s ± 3%  1.67MB/s ± 2%     ~     (p=0.159 n=10+9)
MVCCScan_Pebble/rows=1/versions=100/valueSize=64/numRangeKeys=1-24        1.35MB/s ± 2%  1.36MB/s ± 3%     ~     (p=0.700 n=10+10)
MVCCScan_Pebble/rows=1/versions=100/valueSize=64/numRangeKeys=100-24       506kB/s ± 3%   549kB/s ± 2%   +8.48%  (p=0.000 n=10+9)
MVCCScan_Pebble/rows=10/versions=1/valueSize=64/numRangeKeys=0-24         44.6MB/s ± 2%  45.1MB/s ± 3%     ~     (p=0.256 n=10+10)
MVCCScan_Pebble/rows=10/versions=1/valueSize=64/numRangeKeys=1-24         29.2MB/s ± 2%  29.4MB/s ± 2%     ~     (p=0.356 n=9+10)
MVCCScan_Pebble/rows=10/versions=1/valueSize=64/numRangeKeys=100-24       5.88MB/s ± 2%  6.55MB/s ± 2%  +11.38%  (p=0.000 n=10+10)
MVCCScan_Pebble/rows=10/versions=2/valueSize=64/numRangeKeys=0-24         34.5MB/s ± 2%  35.0MB/s ± 4%     ~     (p=0.055 n=8+10)
MVCCScan_Pebble/rows=10/versions=2/valueSize=64/numRangeKeys=1-24         23.2MB/s ± 4%  23.5MB/s ± 2%   +1.28%  (p=0.033 n=10+9)
MVCCScan_Pebble/rows=10/versions=2/valueSize=64/numRangeKeys=100-24       6.46MB/s ± 4%  7.21MB/s ± 1%  +11.71%  (p=0.000 n=10+9)
MVCCScan_Pebble/rows=10/versions=10/valueSize=64/numRangeKeys=0-24        18.3MB/s ± 3%  18.5MB/s ± 2%     ~     (p=0.353 n=10+10)
MVCCScan_Pebble/rows=10/versions=10/valueSize=64/numRangeKeys=1-24        12.7MB/s ± 2%  12.7MB/s ± 2%     ~     (p=0.826 n=9+10)
MVCCScan_Pebble/rows=10/versions=10/valueSize=64/numRangeKeys=100-24      5.02MB/s ± 3%  5.41MB/s ± 4%   +7.87%  (p=0.000 n=10+10)
MVCCScan_Pebble/rows=10/versions=100/valueSize=64/numRangeKeys=0-24       7.28MB/s ± 3%  7.31MB/s ± 3%     ~     (p=0.643 n=10+10)
MVCCScan_Pebble/rows=10/versions=100/valueSize=64/numRangeKeys=1-24       6.03MB/s ± 2%  5.97MB/s ± 3%     ~     (p=0.283 n=8+10)
MVCCScan_Pebble/rows=10/versions=100/valueSize=64/numRangeKeys=100-24     3.19MB/s ± 4%  3.45MB/s ± 2%   +8.22%  (p=0.000 n=10+10)
MVCCScan_Pebble/rows=100/versions=1/valueSize=64/numRangeKeys=0-24         135MB/s ± 3%   136MB/s ± 1%     ~     (p=0.720 n=10+9)
MVCCScan_Pebble/rows=100/versions=1/valueSize=64/numRangeKeys=1-24        94.0MB/s ± 1%  94.4MB/s ± 2%     ~     (p=0.211 n=9+10)
MVCCScan_Pebble/rows=100/versions=1/valueSize=64/numRangeKeys=100-24      38.2MB/s ± 3%  40.4MB/s ± 1%   +5.63%  (p=0.000 n=10+9)
MVCCScan_Pebble/rows=100/versions=2/valueSize=64/numRangeKeys=0-24         101MB/s ± 2%   102MB/s ± 1%     ~     (p=0.123 n=10+10)
MVCCScan_Pebble/rows=100/versions=2/valueSize=64/numRangeKeys=1-24        68.3MB/s ± 1%  68.9MB/s ± 4%     ~     (p=0.082 n=9+10)
MVCCScan_Pebble/rows=100/versions=2/valueSize=64/numRangeKeys=100-24      35.9MB/s ± 2%  37.6MB/s ± 1%   +4.70%  (p=0.000 n=10+10)
MVCCScan_Pebble/rows=100/versions=10/valueSize=64/numRangeKeys=0-24       39.8MB/s ± 2%  39.3MB/s ± 3%     ~     (p=0.255 n=10+10)
MVCCScan_Pebble/rows=100/versions=10/valueSize=64/numRangeKeys=1-24       26.0MB/s ± 2%  25.9MB/s ± 2%     ~     (p=0.496 n=10+9)
MVCCScan_Pebble/rows=100/versions=10/valueSize=64/numRangeKeys=100-24     17.2MB/s ± 3%  17.6MB/s ± 3%   +2.58%  (p=0.002 n=10+9)
MVCCScan_Pebble/rows=100/versions=100/valueSize=64/numRangeKeys=0-24      12.2MB/s ± 4%  12.0MB/s ± 2%   -1.52%  (p=0.030 n=10+10)
MVCCScan_Pebble/rows=100/versions=100/valueSize=64/numRangeKeys=1-24      9.90MB/s ± 3%  9.76MB/s ± 4%     ~     (p=0.085 n=10+10)
MVCCScan_Pebble/rows=100/versions=100/valueSize=64/numRangeKeys=100-24    7.21MB/s ± 3%  7.18MB/s ± 3%     ~     (p=0.697 n=10+10)
MVCCScan_Pebble/rows=1000/versions=1/valueSize=64/numRangeKeys=0-24        189MB/s ± 2%   189MB/s ± 2%     ~     (p=0.912 n=10+10)
MVCCScan_Pebble/rows=1000/versions=1/valueSize=64/numRangeKeys=1-24        129MB/s ± 2%   131MB/s ± 2%   +1.73%  (p=0.004 n=10+9)
MVCCScan_Pebble/rows=1000/versions=1/valueSize=64/numRangeKeys=100-24     91.3MB/s ± 0%  93.3MB/s ± 2%   +2.20%  (p=0.000 n=8+10)
MVCCScan_Pebble/rows=1000/versions=2/valueSize=64/numRangeKeys=0-24        137MB/s ± 2%   138MB/s ± 2%     ~     (p=0.127 n=10+10)
MVCCScan_Pebble/rows=1000/versions=2/valueSize=64/numRangeKeys=1-24       91.2MB/s ± 2%  91.1MB/s ± 3%     ~     (p=0.912 n=10+10)
MVCCScan_Pebble/rows=1000/versions=2/valueSize=64/numRangeKeys=100-24     71.6MB/s ± 3%  73.4MB/s ± 3%   +2.50%  (p=0.006 n=9+10)
MVCCScan_Pebble/rows=1000/versions=10/valueSize=64/numRangeKeys=0-24      46.6MB/s ± 2%  47.4MB/s ± 2%   +1.66%  (p=0.008 n=10+10)
MVCCScan_Pebble/rows=1000/versions=10/valueSize=64/numRangeKeys=1-24      29.9MB/s ± 2%  30.1MB/s ± 2%     ~     (p=0.128 n=10+10)
MVCCScan_Pebble/rows=1000/versions=10/valueSize=64/numRangeKeys=100-24    23.2MB/s ± 5%  23.8MB/s ± 4%   +2.60%  (p=0.022 n=10+10)
MVCCScan_Pebble/rows=1000/versions=100/valueSize=64/numRangeKeys=0-24     13.9MB/s ± 3%  13.8MB/s ± 2%     ~     (p=0.078 n=10+8)
MVCCScan_Pebble/rows=1000/versions=100/valueSize=64/numRangeKeys=1-24     11.3MB/s ± 2%  11.0MB/s ± 3%   -2.29%  (p=0.003 n=10+10)
MVCCScan_Pebble/rows=1000/versions=100/valueSize=64/numRangeKeys=100-24   8.86MB/s ± 3%  8.72MB/s ± 3%   -1.52%  (p=0.045 n=10+10)
MVCCScan_Pebble/rows=10000/versions=1/valueSize=64/numRangeKeys=0-24       206MB/s ± 2%   209MB/s ± 1%   +1.77%  (p=0.001 n=10+10)
MVCCScan_Pebble/rows=10000/versions=1/valueSize=64/numRangeKeys=1-24       139MB/s ± 2%   142MB/s ± 2%   +2.73%  (p=0.000 n=10+10)
MVCCScan_Pebble/rows=10000/versions=1/valueSize=64/numRangeKeys=100-24     114MB/s ± 3%   116MB/s ± 1%   +1.25%  (p=0.032 n=10+8)
MVCCScan_Pebble/rows=10000/versions=2/valueSize=64/numRangeKeys=0-24       148MB/s ± 2%   148MB/s ± 2%     ~     (p=1.000 n=9+10)
MVCCScan_Pebble/rows=10000/versions=2/valueSize=64/numRangeKeys=1-24      96.7MB/s ± 2%  98.2MB/s ± 3%   +1.56%  (p=0.029 n=10+10)
```

### CODE REVIEW

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 9 of 9 files at r3, 9 of 9 files at r4, 10 of 10 files at r5, 3 of 3 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2131#-:-NH9zTP11oYEUOJjsEl0:bg7igkv)* status: all files reviewed, 5 unresolved discussions (waiting on @jbowens)

___
*[`iterator.go` line 362 at r4](https://reviewable.io/reviews/cockroachdb/pebble/2131#-NH9t0gS7XO4AilKk1WN:-NH9t0gS7XO4AilKk1WO:bvl8t8) ([raw file](https://github.com/cockroachdb/pebble/blob/4f2f9a8e4dc10585690ad19c3f253538453b0979/iterator.go#L362)):*
> ```Go
> 	// Start and end boundaries, suffixes and values are all copied into buf.
> 	buf      []byte
> 	internal rangekey.Buffers
> ```

Can you add a comment for `internal` -- the name is not self-explanatory.
___
*[`iterator.go` line 2042 at r4](https://reviewable.io/reviews/cockroachdb/pebble/2131#-NH9vAar1Kd_UC6umfLI:-NH9vAar1Kd_UC6umfLJ:b-81ptvh) ([raw file](https://github.com/cockroachdb/pebble/blob/4f2f9a8e4dc10585690ad19c3f253538453b0979/iterator.go#L2042)):*
> ```Go
> 		i.rangeKey.rangeKeyBuffers.internal.PrepareForReuse()
> 		*i.rangeKey = iteratorRangeKeyState{
> 			rangeKeyBuffers: i.rangeKey.rangeKeyBuffers,
> ```

why is the `keys: i.rangeKey.keys[:0]` not translated into `i.rangeKey.rangeKeyBuffers.keys = i.rangeKey.rangeKeyBuffers.keys[:0]`. Consider adding a `PrepareForReuse` method for `rangeKeyBuffers` and in that have a code comment for whatever is not touched (justifying why we can get away with it).
___
*[`iterator.go` line 362 at r6](https://reviewable.io/reviews/cockroachdb/pebble/2131#-NH9ysolD3AbeD8kobHA:-NH9ysolD3AbeD8kobHB:b69zo4e) ([raw file](https://github.com/cockroachdb/pebble/blob/acc16a1527ca5611872a638e7062f58414bc6dc7/iterator.go#L362)):*
> ```Go
> 	// buf is used to save range-key data before moving the range-key iterator.
> 	// Start and end boundaries, suffixes and values are all copied into buf.
> 	buf      bytealloc.A
> ```

I had forgotten about `bytealloc.A`. Do we need to audit the code to see if there are other places it can be used?
___
*[`internal/keyspan/defragment.go` line 161 at r4](https://reviewable.io/reviews/cockroachdb/pebble/2131#-NH9tl3ABGPHz3bcumPc:-NH9tl3ABGPHz3bcumPd:bf8sboj) ([raw file](https://github.com/cockroachdb/pebble/blob/4f2f9a8e4dc10585690ad19c3f253538453b0979/internal/keyspan/defragment.go#L161)):*
> ```Go
> 	if cap(bufs.currBuf) > bufferReuseMaxCapacity {
> 		bufs.currBuf = nil
> 	}
> ```

what about the len of `keysBuf`?
___
*[`internal/keyspan/merging_iter.go` line 251 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2131#-NH9wCNd6ryr1Smjz-oE:-NH9wCNd6ryr1Smjz-oF:b-47o0vn) ([raw file](https://github.com/cockroachdb/pebble/blob/ceb7ee63eb2d125333d6680705503f37f4e1c35e/internal/keyspan/merging_iter.go#L251)):*
> ```Go
> 	// be directly modified.
> 	keys   keysBySeqNumKind
> 	levels []mergingIterLevel
> ```

can you add code comments for levels and heap.

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2131)* status: all files reviewed, 5 unresolved discussions (waiting on @sumeerbhola)

___
*[`iterator.go` line 362 at r4](https://reviewable.io/reviews/cockroachdb/pebble/2131#-NH9t0gS7XO4AilKk1WN:-NHRWNUeAiwpyYEqhYhd:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/4f2f9a8e4dc10585690ad19c3f253538453b0979/iterator.go#L362)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Can you add a comment for `internal` -- the name is not self-explanatory.
</blockquote></details>

Done.
___
*[`iterator.go` line 2042 at r4](https://reviewable.io/reviews/cockroachdb/pebble/2131#-NH9vAar1Kd_UC6umfLI:-NHRZjWDBoyZ1kd9ONVI:bdkjage) ([raw file](https://github.com/cockroachdb/pebble/blob/4f2f9a8e4dc10585690ad19c3f253538453b0979/iterator.go#L2042)):*
> why is the keys: i.rangeKey.keys[:0] not translated into i.rangeKey.rangeKeyBuffers.keys = i.rangeKey.rangeKeyBuffers.keys[:0].

the `i.rangeKey.keys` is using the same field/slice, it's just a shorthand for the embedded `rangeKeyBuffers.keys`. 

> Consider adding a PrepareForReuse method for rangeKeyBuffers and in that have a code comment for whatever is not touched (justifying why we can get away with it).

Good call, done. 
___
*[`internal/keyspan/defragment.go` line 161 at r4](https://reviewable.io/reviews/cockroachdb/pebble/2131#-NH9tl3ABGPHz3bcumPc:-NHRWuz3DagIVVrSAGuP:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/4f2f9a8e4dc10585690ad19c3f253538453b0979/internal/keyspan/defragment.go#L161)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

what about the len of `keysBuf`?
</blockquote></details>

Done.
___
*[`internal/keyspan/merging_iter.go` line 251 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2131#-NH9wCNd6ryr1Smjz-oE:-NHRXX5VBbG10OQ8vLqs:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/ceb7ee63eb2d125333d6680705503f37f4e1c35e/internal/keyspan/merging_iter.go#L251)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

can you add code comments for levels and heap.
</blockquote></details>

Done.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 10 files at r9, 2 of 3 files at r10, 8 of 10 files at r13, 2 of 3 files at r14, 3 of 3 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2131#-:-NHVWfVa98IfNo-EYmTC:bg7igkv)* status: all files reviewed, 5 unresolved discussions (waiting on @jbowens)

**Comment by jbowens** [comment]
tftr!

**Pull request merged**
