### PR TITLE
bump snappy to v0.0.3

### PR DESCRIPTION
**Pull request by dt**
This bumps snappy to v0.0.3 which incldes arm64 assembly, including
the fix for go's new register usage.

### CODE REVIEW

**Review by petermattis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1074#-:-MUhtOJvEGLpTN1vdWeW:bnfp4nl)* status: 0 of 10 files reviewed, all discussions resolved (waiting on @jbowens)

**Comment by dt** [comment]
Rebased this to include `go mod tidy` so I think it is actually good to go now

**Review by itsbilal — APPROVED** [review]
:lgtm:

> Reviewed 13 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1074#-:-McKR3Qe5oBnpjOOQz7Q:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jbowens)

**Comment by dt** [comment]
TFTRs!

**Pull request merged**
