### PR TITLE
db: fix levelIter boundaryContext comment

### PR DESCRIPTION
**Pull request by jbowens**
The comment about levelIter.boundaryContext was outdated and only discussed the use of sstable boundary keys to truncate untruncated range tombstones at read time. With the current version of Pebble, untruncated range tombstones no longer exist and the boundaryContext's usage is more constrained.

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3511)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @jbowens and @sumeerbhola)

___
*[`level_iter.go` line 120 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3511#-NvJXj6eDrRGLu7GJOXG:-NvJXj6eDrRGLu7GJOXH:b-f08w1o) ([raw file](https://github.com/cockroachdb/pebble/blob/4aa3a30ce7c94d9077370e9d481ccea731a35ee9/level_iter.go#L120)):*
> ```Go
> 	//   has paused to avoid unnecessarily loading sstables outside the bounds.
> 	// - isIgnorableBoundaryKey is set to true when the levelIter returns a
> 	//   fake key at one of the bounds of an sstable with the level. It does
> ```

"within the level"?

These two sound very similar, from this description I can't tell in what way they are handled differently

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3511)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @RaduBerinde and @sumeerbhola)

___
*[`level_iter.go` line 120 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3511#-NvJXj6eDrRGLu7GJOXG:-NvJnFMG8yj3Bid0aw2Z:bi96znm) ([raw file](https://github.com/cockroachdb/pebble/blob/4aa3a30ce7c94d9077370e9d481ccea731a35ee9/level_iter.go#L120)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

"within the level"?

These two sound very similar, from this description I can't tell in what way they are handled differently
</blockquote></details>

Reworded a bit; the types of bounds are different. The first is the user-imposed iteration bounds, whereas the second is the bounds of an sstable within the level.

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3511#-:-NvK-0w55RgkYkpezCQF:bnfp4nl)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @jbowens and @sumeerbhola)

___
*[`level_iter.go` line 120 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3511#-NvJXj6eDrRGLu7GJOXG:-NvJzsc80v4An-ySS19T:b-ybkfp3) ([raw file](https://github.com/cockroachdb/pebble/blob/4aa3a30ce7c94d9077370e9d481ccea731a35ee9/level_iter.go#L120)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

Reworded a bit; the types of bounds are different. The first is the user-imposed iteration bounds, whereas the second is the bounds of an sstable within the level.
</blockquote></details>

Oh, I see, much better now, thanks!

**Comment by jbowens** [comment]
TFTR!

**Pull request merged**
