### PR TITLE
internal/metamorphic: log ops and options when panic

### PR DESCRIPTION
**Pull request by hueypark**
This change provides additional information to determine the cause such as #560 on CI.

### CODE REVIEW

**Comment by petermattis** [comment]
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/575)

**Comment by petermattis** [comment]
Huh, and just like that you got a reproduction of #560. @hueypark mind seeing if you can track down that problem?

**Comment by hueypark** [comment]
Wow, we found it very quickly. I'll check out #560 before the end of the week.

Can you merge this before?

**Comment by petermattis** [comment]
Sure. I'll merge it now. I'll also link the failure into #560.

**Pull request merged**
