### PR TITLE
metamorphic: generate IngestAndExcise op on prefix keys

### LINKED ISSUE #3113: github.com/cockroachdb/pebble/internal/metamorphic: TestMeta failed
github.com/cockroachdb/pebble/internal/metamorphic.TestMeta [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_Pebble_Metamorphic/12908272?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_Pebble_Metamorphic/12908272?buildTab=artifacts#meta) on refs/heads/master @ [4fc6ccd93ae2](https://github.com/cockroachdb/pebble/commits/4fc6ccd93ae2):

```
        snap29.Get("nuatsf@86") // [""] pebble: not found #3070
        iter28.SeekLT("xdlgtbn@23", "xdlgtbn@55") // [invalid] <nil> #3066
        db1.Set("fcylw@59", "jiqdhprwamipqzqozhw") // <nil> #3075
        db1.Set("fcylw@110", "fbqwhhlzcykseblqql") // <nil> #3085
        db1.Set("tajsdbi@77", "vtxyxjsjkw") // <nil> #3090
        db1.RangeKeyUnset("fcylw", "rleqb", "@111") // <nil> #3094
        iter37.Next("") // [true,"oqpa@51","udwndkhwwmuuqekyw",["oqpa@97","oqpa@36")=>{"@109"="xcnuzun","@105"="tiwjfzbjkdjcuqdlj"}] <nil> #3025
        iter37.SeekLT("xdlgtbn@45", "eehhcjtbdq@64") // [valid,"tajsdbi@108","haglhsuhtuxcbmu",["tajsdbi","tajsdbi@97")=>{""="qhwok","@105"="tiwjfzbjkdjcuqdlj","@104"="lmhxrf"}*] <nil> #3029
        iter37.SetBounds("kicfsyxild@71", "komvltqws@82") // <nil> #3033
        iter37.SeekLT("komvltqws@82", "") // [true,"komvltqws@89","jikzzmrfwo",["komvltqws","komvltqws@82")=>{"@109"="xcnuzun","@105"="tiwjfzbjkdjcuqdlj","@47"="segsq"}*] <nil> #3034
        iter35.SeekPrefixGE("oqpa@31") // [false] pebble: SeekPrefixGE supplied with key outside of upper bound #3130
        iter37.Next("") // [false] <nil> #3035
        iter37.First() // [true,"kicfsyxild@71","ndvremjnujyzmwyhqp",["kicfsyxild@71","komvltqws")=>{"@109"="xcnuzun","@47"="segsq"}*] <nil> #3039
        iter35.Prev("") // [false] pebble: SeekPrefixGE supplied with key outside of upper bound #3133
        iter37.SeekLT("tajsdbi@69", "") // [true,"komvltqws@89","jikzzmrfwo",["komvltqws","komvltqws@82")=>{"@109"="xcnuzun","@105"="tiwjfzbjkdjcuqdlj","@47"="segsq"}*] <nil> #3046
        iter37.Prev("qukudex@77") // [invalid] <nil> #3048
        iter35.Prev("xdlgtbn@1") // [invalid] pebble: SeekPrefixGE supplied with key outside of upper bound #3153
        iter37.Prev("kicfsyxild@45") // [valid,"komvltqws@90","vjpvhlf",["komvltqws","komvltqws@82")=>{"@109"="xcnuzun","@105"="tiwjfzbjkdjcuqdlj","@47"="segsq"}*] <nil> #3059
        iter37.SetBounds("oqpa@35", "qukudex@84") // <nil> #3060
        iter35.Prev("") // [false] pebble: SeekPrefixGE supplied with key outside of upper bound #3155
        iter35.SeekLT("komvltqws@6", "") // [true,"eehhcjtbdq@14","sxbiqkxhcw",["eehhcjtbdq","fcylw@110")=>{"@47"="segsq"}*] <nil> #3157
        iter37.SeekGE("oqpa@35", "") // [true,"oqpa@35",<no point>,["oqpa@35","owzuwjyif")=>{"@109"="xcnuzun","@105"="tiwjfzbjkdjcuqdlj","@101"="iw"}*] <nil> #3061
        iter35.SeekLT("xdlgtbn@4", "") // [true,"eehhcjtbdq@14","sxbiqkxhcw",["eehhcjtbdq","fcylw@110")=>{"@47"="segsq"}] <nil> #3174
        iter37.Prev("") // [false] <nil> #3062
        iter35.SeekGE("kicfsyxild@43", "") // [false] <nil> #3180
        iter35.Next("") // [false] <nil> #3187
        iter35.Prev("") // [true,"eehhcjtbdq@14","sxbiqkxhcw",["eehhcjtbdq","fcylw@110")=>{"@47"="segsq"}*] <nil> #3206
        iter28.Prev("") // [true,"xdlgtbn@62","nyohtqztoxds",["xdlgtbn","xdlgtbn@59")=>{"@103"="qhalfpswiibnaynmjhi"}*] <nil> #3078
        iter35.Prev("") // [true,"eehhcjtbdq@20","nmitcvqqf",["eehhcjtbdq","fcylw@110")=>{"@47"="segsq"}] <nil> #3214
        iter35.Next("") // [true,"eehhcjtbdq@14","sxbiqkxhcw",["eehhcjtbdq","fcylw@110")=>{"@47"="segsq"}] <nil> #3215
        iter28.SeekPrefixGE("zgtu@80") // [false] pebble: SeekPrefixGE supplied with key outside of upper bound #3081
        iter28.Last() // [true,"xdlgtbn@62","nyohtqztoxds",["xdlgtbn","xdlgtbn@59")=>{"@103"="qhalfpswiibnaynmjhi"}*] <nil> #3086
        snap28.Close() // <nil> #3095
        iter28.SeekLT("tajsdbi@50", "") // [true,"tajsdbi@76","wfehffiszp",["tajsdbi","uulpm")=>{"@104"="lmhxrf"}*] <nil> #3100
        iter28.SeekPrefixGE("eehhcjtbdq@79") // [true,"eehhcjtbdq@20","nmitcvqqf",<no range>*] <nil> #3102
        iter28.First() // [true,"eehhcjtbdq@20","nmitcvqqf",<no range>] <nil> #3112
        iter28.SeekPrefixGE("komvltqws@33") // [false] <nil> #3118
        iter28.SetBounds("zgtu@81", "zgtu@46") // <nil> #3121
        iter28.SeekGE("zgtu@81", "") // [true,"zgtu@81","kgwo",<no range>] <nil> #3122
        iter28.Prev("") // [false] <nil> #3123
        iter28.SetBounds("kicfsyxild@96", "komvltqws@33") // <nil> #3126
        iter28.SeekLT("komvltqws@33", "") // [true,"komvltqws@67","bmng",<no range>] <nil> #3127
        iter28.Next("") // [false] <nil> #3128
        iter28.Prev("") // [true,"komvltqws@67","bmng",<no range>] <nil> #3129
        iter28.SeekLT("kicfsyxild@45", "") // [true,"kicfsyxild@70","iqgggnxmzkhnogoykwr",<no range>] <nil> #3141
        iter28.Next("zgtu@76") // [valid,"kicfsyxild@45","hmtvaks",<no range>] <nil> #3148
        iter28.SeekGE("tajsdbi@57", "") // [false] <nil> #3151
        iter28.SetBounds("longzuolff@83", "xdlgtbn") // <nil> #3168
        iter28.SeekGE("oqpa@103", "qgdlmjs@104") // [valid,"oqpa@38","fuqatuikschfbdgvj",<no range>] <nil> #3172
        --- FAIL: TestMeta/execution/standard-009 (0.22s)
```
<details><summary>Help</summary>
<p>
To reproduce, try:

```bash
go test -tags 'invariants' -exec 'stress -p 1' -timeout 0 -test.v -run TestMeta$ ./internal/metamorphic -seed 1701322945034781021 -ops "uniform:5000-10000"
```
</p>
</details>
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestMeta.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### LINKED ISSUE #3121: internal/metamorphic/crossversion/crossversion_test: TestMetaCrossVersion failed
internal/metamorphic/crossversion/crossversion_test.TestMetaCrossVersion [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_NightlyPebbleMetamorphicCrossversion/12942548?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_NightlyPebbleMetamorphicCrossversion/12942548?buildTab=artifacts#/) on refs/heads/master @ [51fca96df08f](https://github.com/cockroachdb/pebble/commits/51fca96df08f):

```
        iter47.SetBounds("xldjuavwgbd", "zqktnvgfpir")
        iter47.SeekGE("xldjuavwgbd", "")
        iter47.Prev("")
        iter47.SeekPrefixGE("dfkljc@9")
        iter47.SeekGE("rdvv@1", "")
        db1.Merge("aokxojk@8", "x")
        iter47.First()
        iter47.SeekPrefixGE("qvkrjvqryc@5")
        iter47.SetBounds("xamwadlomxq", "xuafflagstb")
        iter47.SeekGE("xamwadlomxq", "")
        iter47.Prev("")
        db1.DeleteRange("aukbnb@12", "cgsurakub@10")
        db1.Set("ashwvmpx", "qjkkb")
        iter47.SeekGE("tdzco@4", "")
        db1.Set("aiurcil@11", "ruqmvfpkz")
        iter47.Last()
        iter47.First()
        iter47.Last()
        db1.Merge("hvbxs@5", "qqawqnfitgsadmolx")
        db1.Merge("phpedymkze", "goktdmxqrtbnr")
        iter47.Next("")
        iter47.Prev("")
        iter47.Prev("")
        iter47.Next("")
        iter47.SeekPrefixGE("ykzg@5")
        snap33.Close()
        snap34.Close()
        iter47.SetBounds("rgxhleaicgi", "rrschoufbln")
        iter47.SeekLT("rrschoufbln", "")
        iter47.Next("")
        db1.Set("rxgu@12", "yzmckuwtowbuaqobhnk")
        iter47.First()
        iter47.Next("")
        iter47.SeekGE("pdbzsuqxhkb@12", "")
        iter47.SeekLT("jhvcgssrytc@9", "")
        iter47.SeekLT("wwmvdzcfdt@6", "")
        iter47.SeekPrefixGE("ctmm@3")
        iter47.Next("")
        iter47.Last()
        iter47.Prev("")
        db1.Set("snyaltnb@10", "pyejag")
        iter47.First()
        iter47.NextPrefix()
        iter47.SeekGE("cpsi@12", "gubrdy@4")
        iter47.Close()
        snap32.Close()
        db1.Close()
        
        		
        --- FAIL: TestMetaCrossVersion/execution-master/sha=043c3795-seed=17566230953064403068-opts=standard-003(sha=db91e5c9-seed=14568938406240756923-opts=random-011(sha=ffd5ce9c-seed=15943457679926996197-opts=standard-017(sha=4ddacdaf-seed=1313704048112502034-opts=standard-015(<empty>)))) (357.77s)
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/test-eng
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestMetaCrossVersion.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### PR DESCRIPTION
**Pull request by itsbilal**
This change adds an invariant-gated assertion that all range key operations are on suffix-less keys, as having range key operations on suffixed keys can break NextPrefix(). It also updates the metamorphic IngestAndExcise operation to only generate prefixes, as it does a RangeKeyDelete in
the non-excise case.

Fixes #3113.
Fixes #3121.

### CODE REVIEW

**Review by jbowens — COMMENTED** [review]
Looks like the metamorphic test failed in Mac CI. A separate issue with 4fc6ccd?:

https://github.com/cockroachdb/pebble/actions/runs/7064997678/job/19234124917?pr=3119#step:4:45

> Reviewed 4 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3119#-:-NkbKzfTAV_HPyRuvVfp:b-297m6d)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @itsbilal)

___
*[`metamorphic/key_manager.go` line 414 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3119#-NkbMBOE5ssqiBjKtdIy:-NkbMBOE5ssqiBjKtdIz:b-k9cu45) ([raw file](https://github.com/cockroachdb/pebble/blob/96b784e985f7d21e5999fe633d73fd511bc11243/metamorphic/key_manager.go#L414)):*
> ```Go
> 		k.checkForDelOrSingleDelTransitionInDB(s.dbID)
> 	case *replicateOp:
> 		k.mergeKeysInto(s.source, s.dest)
> ```

I don't think this is right. This will merge _all_ key histories from the source DB into the destination DB, but we're only replicating state between between `s.start` and `s.end`. Also, we don't want to want to merge the histories, we want to completely replace the destination's histories with the source's histories.

**Comment by itsbilal** [comment]
*[`metamorphic/key_manager.go` line 414 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3119#-NkbMBOE5ssqiBjKtdIy:-NkbcBD2EYCEUjyvP-Ts:blseszh) ([raw file](https://github.com/cockroachdb/pebble/blob/96b784e985f7d21e5999fe633d73fd511bc11243/metamorphic/key_manager.go#L414)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

I don't think this is right. This will merge _all_ key histories from the source DB into the destination DB, but we're only replicating state between between `s.start` and `s.end`. Also, we don't want to want to merge the histories, we want to completely replace the destination's histories with the source's histories.
</blockquote></details>

Good point. I'll address this shortly.

**Review by sumeerbhola — DISMISSED** [review]
> Reviewed 5 of 6 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3119)* status: all files reviewed, 4 unresolved discussions (waiting on @itsbilal and @jbowens)

___
*[`metamorphic/key_manager.go` line 411 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3119#-NkqbQttCLRs3T16g-Bj:-NkqbQttCLRs3T16g-Bk:b-puugrr) ([raw file](https://github.com/cockroachdb/pebble/blob/96b784e985f7d21e5999fe633d73fd511bc11243/metamorphic/key_manager.go#L411)):*
> ```Go
> 	case *ingestAndExciseOp:
> 		// Merge all keys in the batch with the keys in the DB.
> 		k.mergeKeysInto(s.batchID, s.dbID)
> ```

Is this removal meant to be in this commit. I can't quite correlate it to the message in the second commit in this PR.
___
*[`metamorphic/ops.go` line 860 at r3](https://reviewable.io/reviews/cockroachdb/pebble/3119#-NkqcMgA7BPW2iw8CCYq:-NkqcMgA7BPW2iw8CCYr:b-89hldc) ([raw file](https://github.com/cockroachdb/pebble/blob/d1b824581ac34c14f892aac61aa0e77ed5db7ef1/metamorphic/ops.go#L860)):*
> ```Go
> 	t *test, h historyRecorder, b *pebble.Batch, i int,
> ) (string, *sstable.WriterMetadata, error) {
> 	return buildForIngest(t, o.dbID, h, b, i, true /* removeSingleDel */)
> ```

why do we need to replace SingleDel with Del for the ingest sst?
___
*[`data_test.go` line 581 at r3](https://reviewable.io/reviews/cockroachdb/pebble/3119#-NkqaOqGEpuSMTS2cAma:-NkqaOqHCtkGdgMYMJ27:bqebhii) ([raw file](https://github.com/cockroachdb/pebble/blob/d1b824581ac34c14f892aac61aa0e77ed5db7ef1/data_test.go#L581)):*
> ```Go
> 
> func runBuildCmd(td *datadriven.TestData, d *DB, fs vfs.FS) error {
> 	b := newIndexedBatch(nil, d.opts.Comparer)
> ```

why this change?

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3119)* status: all files reviewed, 4 unresolved discussions (waiting on @itsbilal and @sumeerbhola)

___
*[`metamorphic/key_manager.go` line 414 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3119#-NkbMBOE5ssqiBjKtdIy:-NkuR7ND1sMdRL4z47bv:b-ga7xjz) ([raw file](https://github.com/cockroachdb/pebble/blob/96b784e985f7d21e5999fe633d73fd511bc11243/metamorphic/key_manager.go#L414)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

I've just replaced this block of code and replaced it with a TODO to have these operations work better with the keyManager. I'll take a look at this once #3116 is in, but it seems like this test passes reliably even without any interaction with keyManager.

Also, `deleteRangeOp` seems like it does nothing here as well?
</blockquote></details>

Excluding delete range is "harmless" in that we'll use single delete in fewer circumstances than we otherwise could.

I'd expect `ingestAndExciseOp` and `replicateOp` to not be harmless, because these ops have the potential to add new `SET`s to the DB without recording them. I think this probably doesn't fail just because the current key accounting is global and we're leaking the keys indefinitely. Any user keys that are `SET` or `MERGE`d in a table ingested through `ingestAndExcise` will just always be excluded for single deletion. I think similarly replicate op ends up being harmless because we're enforcing the singledel invariants at the global level right now. We will never single delete if both of the DBs have the same key SET because we don't know that the two SETs aren't on the same database.

I can fix this in #3116
___
*[`metamorphic/ops.go` line 860 at r3](https://reviewable.io/reviews/cockroachdb/pebble/3119#-NkqcMgA7BPW2iw8CCYq:-NkuTpW0AVkUvNHybgH9:b-o0o456) ([raw file](https://github.com/cockroachdb/pebble/blob/d1b824581ac34c14f892aac61aa0e77ed5db7ef1/metamorphic/ops.go#L860)):*
> And also in disagg storage we won't be doing excises in any part of the keyspace that has singledels anyway.

nit: Aren't we still excising the non-meta keyspaces even if we're not ingesting external sstables into them? I don't think that's material for this. I can fix this in #3116.

**Review by itsbilal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3119)* status: 6 of 7 files reviewed, 4 unresolved discussions (waiting on @jbowens and @sumeerbhola)

___
*[`metamorphic/key_manager.go` line 414 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3119#-NkbMBOE5ssqiBjKtdIy:-NkuhkSOBka6sXbPE0Mm:b-qf0cwy) ([raw file](https://github.com/cockroachdb/pebble/blob/96b784e985f7d21e5999fe633d73fd511bc11243/metamorphic/key_manager.go#L414)):*
That's a good point. I think I was trying to imagine IngestAndExcise as a combination of an Ingest plus a DeleteRange, and from that perspective doing the merge makes a bit more sense as it'd have the exact same effect on keyManager as if we just had those operations in sequence one after the other.

> I can fix this in #3116 

Thank you! If it ends up being too much work, feel free to punt it to a follow-up issue instead of tackling it all in #3116. I'll also pay more thought to how to accurately track sets/etc in the key manager given excises, replicate operations and multiple DBs.
___
*[`metamorphic/ops.go` line 860 at r3](https://reviewable.io/reviews/cockroachdb/pebble/3119#-NkqcMgA7BPW2iw8CCYq:-Nkubo1f9fsCiZf_bD2H:b-kd0wqe) ([raw file](https://github.com/cockroachdb/pebble/blob/d1b824581ac34c14f892aac61aa0e77ed5db7ef1/metamorphic/ops.go#L860)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

> And also in disagg storage we won't be doing excises in any part of the keyspace that has singledels anyway.

nit: Aren't we still excising the non-meta keyspaces even if we're not ingesting external sstables into them? I don't think that's material for this. I can fix this in #3116.
</blockquote></details>

We're not; if we flip the cluster setting on, we only excise the user/table part of the keyspace and put down rangedels for the others. That's something we can revisit though; we'd just need to update `IngestAndExcise` to take multiple excise spans.

I've removed this `removeSingleDel` flag btw.

**Review by jbowens — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3119#-:-Nkvp9E08VxthvIBqgQO:b593vm9)* status: 6 of 7 files reviewed, 4 unresolved discussions (waiting on @sumeerbhola)

**Comment by itsbilal** [comment]
TFTR!

**Pull request merged**
