### PR TITLE
sstable: adds a test which checks for a specific Writer race

### PR DESCRIPTION
**Pull request by bananabrick**
The test makes sure that the Writer.Metadata doesn't hold a reference to a buffer owned
by an older dataBlockBuf. On the current master, this test passes because the Writer
only has a single dataBlockBuf.

Since the test depends on order of execution of goroutines it only fails intermittently in
the commit prior to https://github.com/cockroachdb/pebble/commit/69a82fe41c311e441cca3c963f5cac13c7f1dd50.

### CODE REVIEW

**Review by bananabrick — COMMENTED** [review]
This isn't as good as having a generalized test which can test for any race, but it does successfully check for the recent race we saw.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1554#-:-MxBbbaH7KcJZQC7XGuv:bklfiyh)* status: 0 of 1 files reviewed, all discussions resolved

**Comment by bananabrick** [comment]
Can hold off on review, making some changes.

**Review by bananabrick — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1554)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @itsbilal and @jbowens)

___
*[sstable/writer_test.go, line 535 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1554#-MxBjztZ-vIYBCJJ5ug4:-MxBjztZ-vIYBCJJ5ug5:b4e64iz) ([raw file](https://github.com/cockroachdb/pebble/blob/6ae8d05ff612830d2897908c4522e931512d3043/sstable/writer_test.go#L535)):*
> ```Go
> 					// goroutine, this shouldn't trigger a race as no other goroutine should be accessing this
> 					// Writer.
> 					w.meta.Largest.UserKey[i] = 'c'
> ```

This part will cause the test run with the `-race` flag to fail in a commit prior to https://github.com/cockroachdb/pebble/commit/69a82fe41c311e441cca3c963f5cac13c7f1dd50.

**Review by bananabrick — COMMENTED** [review]
Should be good for review now.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1554#-:-MxBkDaA7nG9goQtLIhR:b-ry85gl)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @itsbilal and @jbowens)

**Review by jbowens — COMMENTED** [review]
How about something like this for a more generalized test:

```
// Tests for race in https://github.com/cockroachdb/cockroach/issues/77194 which
// was fixed in https://github.com/cockroachdb/pebble/pull/1547.
func TestDataBlockBufferOwnership(t *testing.T) {
	ks := testkeys.Alpha(5)
	ks = ks.EveryN(ks.Count() / 1_000)
	keys := make([][]byte, ks.Count())
	for ki := 0; ki < len(keys); ki++ {
		keys[ki] = testkeys.Key(ks, ki)
	}
	readerOpts := ReaderOptions{
		Comparer: testkeys.Comparer,
		Filters:  map[string]base.FilterPolicy{},
	}

	var wg sync.WaitGroup
	for i := 0; i < 16; i++ {
		wg.Add(1)
		go func() {
			val := make([]byte, rand.Intn(1000))
			opts := WriterOptions{
				Comparer:    testkeys.Comparer,
				BlockSize:   rand.Intn(1 << 10),
				Compression: NoCompression,
			}
			defer wg.Done()
			f := &memFile{}
			w := NewWriter(f, opts)
			for ki := 0; ki < len(keys); ki++ {
				require.NoError(t, w.Add(base.MakeInternalKey(keys[ki], uint64(ki), InternalKeyKindSet), val))
				require.Equal(t, w.meta.Largest.UserKey, keys[ki])
			}
			require.NoError(t, w.Close())
			require.Equal(t, w.meta.Largest.UserKey, keys[len(keys)-1])
			r, err := NewMemReader(f.Bytes(), readerOpts)
			require.NoError(t, err)
			defer r.Close()
			it, err := r.NewIter(nil, nil)
			require.NoError(t, err)
			defer it.Close()
			ki := 0
			for k, v := it.First(); k != nil; k, v = it.Next() {
				require.Equal(t, k.UserKey, keys[ki])
				require.Equal(t, v, val)
				ki++
			}
		}()
	}
	wg.Wait()
}
```
The above test doesn't _always_ fail, but it's very flaky and reliably fails under `stress`:

```
go test -race -c
stress ./sstable.test -test.run  'TestDataBlockBufferOwnership'
```

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1554#-:-MxdyYe40xF3KRJj7epU:b-4blx4)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @itsbilal)

**Review by bananabrick — COMMENTED** [review]
What is the `Reader` being used for? The test seems to work without it.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1554#-:-MxeifMKA__EtSvIKn-E:b-33p4mg)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @itsbilal)

**Review by jbowens — COMMENTED** [review]
It increases the test coverage. It ensures we wrote what we expected to write and none of our writes were clobbered by another goroutine.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1554#-:-Mxf0JUd5KZDJuAMMRVs:b-2od1lu)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @itsbilal)

**Comment by bananabrick** [comment]
Moved test to different pr.

**Pull request closed without merging**
