### PR TITLE
[crl-release-21.1]: tool: fix find to support custom comparers and mergers

### PR DESCRIPTION
**Pull request by petermattis**
Add support for custom comparers and mergers to `find`. This involved
plumbing through the mergers from the top-level tool as was already
being done for the other tool commands.

### CODE REVIEW

**Comment by petermattis** [comment]
This change only affects debugging tooling, but it does fix an important bug in the `find` tool.

**Comment by petermattis** [comment]
@itsbilal can you give this a stamp of approval?

**Review by itsbilal — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, 19 of 19 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1106#-:-MXbaBZ606nRrymD8JiQ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @petermattis)

**Comment by petermattis** [comment]
TFTR!

I'm going to let this change piggyback on the version bump you'll do for #1110.

**Pull request merged**
