### PR TITLE
db: minor cleanup in Open

### PR DESCRIPTION
**Pull request by RaduBerinde**
Some of the error paths were very hard to read through.

### CODE REVIEW

**Review by jbowens — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2247)* status: all files reviewed, 1 unresolved discussion (waiting on @RaduBerinde)

___
*[`open.go` line 233 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2247#-NM4gAILC_5iijW0Cfnw:-NM4gAILC_5iijW0Cfnx:bz8mslc) ([raw file](https://github.com/cockroachdb/pebble/blob/0c2f82093c8761d74487379b024d39fc83c83d5f/open.go#L233)):*
> ```Go
> 	if err != nil {
> 		return nil, errors.Wrapf(err, "pebble: database %q", dirname)
> 	}
> ```

I think this conditional was previously below the defer because `findCurrentManifest` can return `err != nil` and a non-nil `manifestMarker`, which if not closed will leak a file descriptor. It's gross and I think we can fix up `findCurrentManifest` to take responsibility of closing the `manifestMarker` if it returns a `err != nil`.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2247)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @jbowens)

___
*[`open.go` line 233 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2247#-NM4gAILC_5iijW0Cfnw:-NM5sac72kcJrHiuFwFH:b-yenbva) ([raw file](https://github.com/cockroachdb/pebble/blob/0c2f82093c8761d74487379b024d39fc83c83d5f/open.go#L233)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

I think this conditional was previously below the defer because `findCurrentManifest` can return `err != nil` and a non-nil `manifestMarker`, which if not closed will leak a file descriptor. It's gross and I think we can fix up `findCurrentManifest` to take responsibility of closing the `manifestMarker` if it returns a `err != nil`.
</blockquote></details>

Ah, I moved it a bit too much, fixed.

**Review by jbowens — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2247#-:-NM9fY8B1n2H9h-pUI0z:bnfp4nl)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @RaduBerinde)

**Comment by RaduBerinde** [comment]
TFTR!

**Pull request merged**
