### PR TITLE
doc: fix typo(flushables->flushable)

### PR DESCRIPTION
**Pull request by caicancai**

### CODE REVIEW

**Comment by caicancai** [comment]
@RaduBerinde @jbowens If you have time, could you help me take a look? Thanks

**Comment by RaduBerinde** [comment]
Hi @caicancai,

Thanks for your contribution. We have merged several PRs with only one or two minor fixes. Would you mind coalescing these into bigger PRs? We'd like to avoid having many trivial PRs/commits.  Thank you!

**Comment by RaduBerinde** [comment]
Oh, also this wasn't a typo, it's the queue of flushables.

**Comment by caicancai** [comment]
Thanks for your reminder, I'll try it.

**Pull request closed without merging**
