### PR TITLE
*: Fix race in compactMarkedFilesLocked with concurrent compactions

### LINKED ISSUE #2044: crossversion: investigate timeout
Running the cross-version metamorphic tests w/ 21.2->22.1->22.2 on my gceworker, runs took on average 6 minutes. After 24 hours, one run of the crossversion metamorphic tests hit the 1hr timeout that I set. We should investigate why and determine if this configuration is exercising some pathological behavior.

```
=== RUN   TestMetaCrossVersion
    crossversion_test.go:73: Test directory: /tmp/TestMetaCrossVersion3415907446/001
    crossversion_test.go:74: Reproduction:
          go test -v -run 'TestMetaCrossVersion' --seed 1666464515427976089 --factor 10 --version 21.2,09f3473d,/home/jackson/go/src/github.com/cockroachdb/pebble/meta.21.2.test --version 22.1,292cba9b,/home/jackson/go/src/github.com/cockroachdb/pebble/meta.22.1.test --version 22.2,0d8cae91,/home/jackson/go/src/github.com/cockroachdb/pebble/meta.22.2.test

    crossversion_test.go:92: 0: 21.2,09f3473d,/home/jackson/go/src/github.com/cockroachdb/pebble/meta.21.2.test (Mode = -rwxrwxr-x)
    crossversion_test.go:92: 1: 22.1,292cba9b,/home/jackson/go/src/github.com/cockroachdb/pebble/meta.22.1.test (Mode = -rwxrwxr-x)
    crossversion_test.go:92: 2: 22.2,0d8cae91,/home/jackson/go/src/github.com/cockroachdb/pebble/meta.22.2.test (Mode = -rwxrwxr-x)
    crossversion_test.go:151: Running tests with version 09f3473d with 1 initial state(s).
    crossversion_test.go:157:   Running test with version 09f3473d with initial state <empty>.
    crossversion_test.go:151: Running tests with version 292cba9b with 10 initial state(s).
    crossversion_test.go:157:   Running test with version 292cba9b with initial state sha=09f3473d-seed=4910346648737122976-opts=standard-010(<empty>).
    crossversion_test.go:157:   Running test with version 292cba9b with initial state sha=09f3473d-seed=4910346648737122976-opts=standard-020(<empty>).
    crossversion_test.go:157:   Running test with version 292cba9b with initial state sha=09f3473d-seed=4910346648737122976-opts=standard-012(<empty>).
    crossversion_test.go:157:   Running test with version 292cba9b with initial state sha=09f3473d-seed=4910346648737122976-opts=random-001(<empty>).
    crossversion_test.go:157:   Running test with version 292cba9b with initial state sha=09f3473d-seed=4910346648737122976-opts=random-007(<empty>).
    crossversion_test.go:157:   Running test with version 292cba9b with initial state sha=09f3473d-seed=4910346648737122976-opts=standard-006(<empty>).
    crossversion_test.go:157:   Running test with version 292cba9b with initial state sha=09f3473d-seed=4910346648737122976-opts=standard-015(<empty>).
    crossversion_test.go:157:   Running test with version 292cba9b with initial state sha=09f3473d-seed=4910346648737122976-opts=random-009(<empty>).
    crossversion_test.go:157:   Running test with version 292cba9b with initial state sha=09f3473d-seed=4910346648737122976-opts=standard-018(<empty>).
    crossversion_test.go:157:   Running test with version 292cba9b with initial state sha=09f3473d-seed=4910346648737122976-opts=standard-000(<empty>).
    crossversion_test.go:151: Running tests with version 0d8cae91 with 10 initial state(s).
    crossversion_test.go:157:   Running test with version 0d8cae91 with initial state sha=292cba9b-seed=2889797296425809833-opts=random-009(sha=09f3473d-seed=4910346648737122976-opts=standard-010(<empty>)).
panic: test timed out after 1h0m0s
```

[TestMetaCrossVersion3415907446.tar.gz](https://github.com/cockroachdb/pebble/files/9847493/TestMetaCrossVersion3415907446.tar.gz)

### PR DESCRIPTION
**Pull request by itsbilal**
Presently there's a race with concurrent compactions and the logic in `compactMarkedFilesLocked` where we expect each call to `maybeScheduleCompactionPicker` to create at least one compaction, when that is not guaranteed especially around concurrent compactions.

This change updates the logic there to only wait on compactions if we actually scheduled one.

Fixes #2044.

### CODE REVIEW

**Review by bananabrick — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2060)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @itsbilal and @jbowens)

___
*[`format_major_version.go` line 421 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2060#-NFKP4hV-1UUBOJWunmZ:-NFKP4hV-1UUBOJWunm_:baorddo) ([raw file](https://github.com/cockroachdb/pebble/blob/9223dd54044219aa5c17b510de31ffa062c0f262/format_major_version.go#L421)):*
> ```Go
> 		// NB: Waiting on this condition variable drops d.mu while blocked.
> 		if compactionPicked {
> 			if d.mu.compact.compactingCount == 0 {
> ```

I believe the usual method is:

```
				for d.mu.compact.compactingCount > 0 {
					d.mu.compact.cond.Wait()
				}
```

**Review by bananabrick — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2060)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @itsbilal and @jbowens)

___
*[`format_major_version.go` line 421 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2060#-NFKP4hV-1UUBOJWunmZ:-NFKSdqc0OvKVq75oC1r:by8d288) ([raw file](https://github.com/cockroachdb/pebble/blob/9223dd54044219aa5c17b510de31ffa062c0f262/format_major_version.go#L421)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

I believe the usual method is:

```
				for d.mu.compact.compactingCount > 0 {
					d.mu.compact.cond.Wait()
				}
```
</blockquote></details>

Or, use the following to wait for one compaction to finish.

```
if d.mu.compact.compactingCount > 0 {
    d.mu.compact.cond.Wait()
}
```

I'm a bit confused why we need the compactionPicked variable.

**Comment by itsbilal** [comment]
*[`format_major_version.go` line 421 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2060#-NFKP4hV-1UUBOJWunmZ:-NFKhGT_Dl6XiGbYjYkv:bvr2i5e) ([raw file](https://github.com/cockroachdb/pebble/blob/9223dd54044219aa5c17b510de31ffa062c0f262/format_major_version.go#L421)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

Or, use the following to wait for one compaction to finish.

```
if d.mu.compact.compactingCount > 0 {
    d.mu.compact.cond.Wait()
}
```

I'm a bit confused why we need the compactionPicked variable.
</blockquote></details>

The thing is that we aren't necessarily waiting for all compactions to finish, there could be some happening that are unrelated to the kind of rewrite compactions that we want to wait on. So it's best to just loop until all MarkedForCompacting files are compacted, which is why it's preferable to loop on the outer loop instead of creating another inside loop.

**Review by bananabrick — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2060)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @itsbilal and @jbowens)

___
*[`format_major_version.go` line 421 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2060#-NFKP4hV-1UUBOJWunmZ:-NFKp8NU-iT6oiuRhYMW:bu74oe0) ([raw file](https://github.com/cockroachdb/pebble/blob/9223dd54044219aa5c17b510de31ffa062c0f262/format_major_version.go#L421)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

The thing is that we aren't necessarily waiting for all compactions to finish, there could be some happening that are unrelated to the kind of rewrite compactions that we want to wait on. So it's best to just loop until all MarkedForCompacting files are compacted, which is why it's preferable to loop on the outer loop instead of creating another inside loop.
</blockquote></details>

The `if` statement would only wait for one. Even if we use the `compactionPicked` variable, and wait for 1, we don't know which compaction will finish, anyway. I'm nitpicking, though.

**Review by itsbilal — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2060#-:-NFL2-17E-PupBx9VI52:b-814g8k)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @bananabrick and @jbowens)

___
*[`format_major_version.go` line 421 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2060#-NFKP4hV-1UUBOJWunmZ:-NFL1x627G6RGm20EJZ0:bvm23mr) ([raw file](https://github.com/cockroachdb/pebble/blob/9223dd54044219aa5c17b510de31ffa062c0f262/format_major_version.go#L421)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

The loop variable is `curr.Stats.MarkedFor Compaction > 0` which is what we're interested in and not all compactions terminating, so it's okay if we don't wait for all the compactions (some of which could be non-rewrite).
</blockquote></details>

I made this more explicit, which also fixes a spinlock situation. PTAL!

**Review by jbowens — APPROVED** [review]
Fix :lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2060#-:-NFLXyGMAOt-Ur6vDVii:b-ct0ro)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @bananabrick and @itsbilal)

___
*[`format_major_version_test.go` line 526 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2060#-NFLULMj04fE1p00eSr2:-NFLULMj04fE1p00eSr3:b6mfquq) ([raw file](https://github.com/cockroachdb/pebble/blob/1e6979de941b468c0f90371c2bc158b07672163d/format_major_version_test.go#L526)):*
> ```Go
> // Regression test for #2044, where multiple concurrent compactions can lead
> // to an indefinite wait on the compaction goroutine in compactMarkedFilesLocked.
> func TestPebblev1MigrationConcurrencyRace(t *testing.T) {
> ```

were you able to reproduce the deadlock with this unit test? I wasn't able locally on my macbook.
___
*[`format_major_version_test.go` line 557 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2060#-NFLUyms8TK6VAHf85EX:-NFLUyms8TK6VAHf85EY:b-9tkusv) ([raw file](https://github.com/cockroachdb/pebble/blob/1e6979de941b468c0f90371c2bc158b07672163d/format_major_version_test.go#L557)):*
> ```Go
> 	d, err := Open("", opts)
> 	require.NoError(t, err)
> 	require.NoError(t, d.RatchetFormatMajorVersion(FormatPrePebblev1MarkedCompacted))
> ```

this is redundant with setting `opts.FormatMajorVersion` up above, right?

**Review by bananabrick — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2060)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @itsbilal)

___
*[`format_major_version.go` line 421 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2060#-NFKP4hV-1UUBOJWunmZ:-NFPYQHw8j9_2Oomjaps:bqhyp2t) ([raw file](https://github.com/cockroachdb/pebble/blob/9223dd54044219aa5c17b510de31ffa062c0f262/format_major_version.go#L421)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

I made this more explicit, which also fixes a spinlock situation. PTAL!
</blockquote></details>

Even if there are files marked for compaction, the pickRewriteCompaction function can still return `nil`, I believe. In which case, the `compactingCount` can still be 0, and we'll panic unnecessarily.

Am I missing an invariant?

**Review by bananabrick — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2060)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @itsbilal)

___
*[`format_major_version.go` line 421 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2060#-NFKP4hV-1UUBOJWunmZ:-NFP_nW35NkidOkR1_eg:b-fezks4) ([raw file](https://github.com/cockroachdb/pebble/blob/9223dd54044219aa5c17b510de31ffa062c0f262/format_major_version.go#L421)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

Even if there are files marked for compaction, the pickRewriteCompaction function can still return `nil`, I believe. In which case, the `compactingCount` can still be 0, and we'll panic unnecessarily.

Am I missing an invariant?
</blockquote></details>

I think the`pickRewriteCompaction` function will only return `nil` if there are other ongoing compactions, in which case the `compactingCount` won't be 0. It seems like a subtle invariant to rely on.

**Review by itsbilal — COMMENTED** [review]
TFTR! I am going to give up investigating why I haven't been able to repro this issue in a unit test, but a 22.2 metamorphic test binary before the fix and with an initial state copied from the failing run enters the deadlock around 1 every 20-30 runs, and with the fix I've yet to see a failure after ~5000 runs.

Made some test improvements regardless. I'll merge and backport since fix is LGTM'd already.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2060#-:-NFPaUPk0Qra7is45hji:b-pqs36p)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @bananabrick)

___
*[`format_major_version.go` line 421 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2060#-NFKP4hV-1UUBOJWunmZ:-NFP_4AJ3_sJLUpC-4jQ:b-e6pysw) ([raw file](https://github.com/cockroachdb/pebble/blob/9223dd54044219aa5c17b510de31ffa062c0f262/format_major_version.go#L421)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

Even if there are files marked for compaction, the pickRewriteCompaction function can still return `nil`, I believe. In which case, the `compactingCount` can still be 0, and we'll panic unnecessarily.

Am I missing an invariant?
</blockquote></details>

The only case where `pickRewriteCompaction` will return nil is if marked files are already compacting, so compactingCount > 0. The mutex is not dropped between the pickFunc() call and this point. If that logic ever changes, this panic will fire, and will be a good reason to revisit this accordingly.

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2060)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @bananabrick and @itsbilal)

___
*[`format_major_version.go` line 421 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2060#-NFKP4hV-1UUBOJWunmZ:-NFPb9ud5FQQ6UKIX4Py:b-eola6d) ([raw file](https://github.com/cockroachdb/pebble/blob/9223dd54044219aa5c17b510de31ffa062c0f262/format_major_version.go#L421)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

The only case where `pickRewriteCompaction` will return nil is if marked files are already compacting, so compactingCount > 0. The mutex is not dropped between the pickFunc() call and this point. If that logic ever changes, this panic will fire, and will be a good reason to revisit this accordingly.
</blockquote></details>

Agree with the panic. We need to compact all marked-for-compaction files before the format major version is updated. If we're failing to schedule these compactions, it will block the version upgrade. We're already relying on the invariant, and so it's preferable to panic if the invariant breaks.

**Pull request merged**
