### PR TITLE
objstorage: delete obsolete objects through provider

### PR DESCRIPTION
**Pull request by RaduBerinde**
Update obsolete object deletion to go through objstorage.

### CODE REVIEW

**Review by bananabrick — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2297#-:-NNIHA7JEhDHB7r93Z7h:bnfp4nl)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @RaduBerinde)

___
*[`compaction.go` line 3199 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2297#-NNIHEghD2GuqPSsbEkF:-NNIHEghD2GuqPSsbEkG:byhl5ga) ([raw file](https://github.com/cockroachdb/pebble/blob/465450325f73a3ebfbc294e31023eea896ef3474/compaction.go#L3199)):*
> ```Go
> }
> 
> func (d *DB) deleteObsoleteObject(fileType fileType, jobID int, fileNum FileNum) {
> ```

nit: We could have a `if fileType != fileTypeTable { panic("not an object") } at the top of the function if you want. Then we can guarantee that we're not accidentally calling `Remove` on the wrong filetype.

**Review by bananabrick — COMMENTED** [review]
Do we really want deletion of all sstables to go through object storage btw? Even non L5-L6?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2297#-:-NNIK6aL-bfA-JydHJf-:bmoqyes)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @RaduBerinde)

**Review by RaduBerinde — COMMENTED** [review]
Yes, all SST access should go through `objstorage`. Most of the code should be unconcerned with what objects are stored where.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2297#-:-NNIVjJl3XNAmj1EWVwK:bbyjrmf)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @bananabrick)

___
*[`compaction.go` line 3199 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2297#-NNIHEghD2GuqPSsbEkF:-NNIW8uT9nvs1h3pB7JR:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/465450325f73a3ebfbc294e31023eea896ef3474/compaction.go#L3199)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

nit: We could have a `if fileType != fileTypeTable { panic("not an object") } at the top of the function if you want. Then we can guarantee that we're not accidentally calling `Remove` on the wrong filetype.
</blockquote></details>

Done.

**Review by jbowens — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2297#-:-NNId_iT6eGUkm9xGLyn:bnfp4nl)* status: 1 of 3 files reviewed, all discussions resolved (waiting on @bananabrick)

**Pull request merged**
