### PR TITLE
db: introduce format major version

### PR DESCRIPTION
**Pull request by jbowens**
Introduce the concept of a 'format major version' behind which backwards
incompatible changes may be gated. A database's format major version may
be bumped by passing a higher version in Options at Open, or explicitly
by calling RatchetFormatMajorVersion.

Once a database's format major version has been upgraded, it cannot be
downgraded. Versions of Pebble that don't understand the new format
major version will refuse to open the database.

This commit also uses the new format major version to migrate how we
indicate which manifest file is active. RocksDB and previous versions of
Pebble used the special CURRENT file, which contained the active
manifest's filename within the file's contents. This change introduces a
new mechanic using 'atomic markers'. This scheme does not require
filesystem renames to be atomic. This ensures manifest rotation is
atomic, including on CockroachDB's encryption-at-rest implementation
which does not support atomic renames.

### CODE REVIEW

**Review by jbowens — COMMENTED** [review]
@sumeerbhola I missed this one until just now: https://github.com/cockroachdb/cockroach/blob/master/pkg/ccl/storageccl/engineccl/pebble_key_manager.go#L394-L396

`SafeWriteToFile` requires atomic renames and `m.fs` is the "store FS" `encryptedFS`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1227#-:-MhUkSix6L5JaWqjvk5e:bpe1tjg)* status: 0 of 14 files reviewed, all discussions resolved (waiting on @sumeerbhola)

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> SafeWriteToFile requires atomic renames and m.fs is the "store FS" encryptedFS.

Glad you noticed it! I'm assuming the `WriteMinVersionFile` use case can use the unwrapped FS?

IIRC, this `DataKeyRegistry` only grows since we don't have currently have a way to cleanup unused DataKeys. How about we use the same approach as the `FileRegistry` and turn it into a recordio file? We'd need another incompatible change, but we're already making one in this release, so that seems ok.

In general we should always be writing files once and the already written parts should be immutable, since that leads to simpler correctness behavior -- so I'm not worried that this removal of atomic rename will be unsustainable longer term.

> Reviewed 5 of 5 files at r1, 3 of 3 files at r2, 5 of 11 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1227#-:-MhYXJBS5xcOa3j3R7jd:b-nhrpq5)* status: 9 of 14 files reviewed, 1 unresolved discussion (waiting on @jbowens)

___
*[version_set.go, line 236 at r4](https://reviewable.io/reviews/cockroachdb/pebble/1227#-MhY_pBD8Q_ujZDcT_wx:-MhY_pBD8Q_ujZDcT_wy:b-hbf4a2) ([raw file](https://github.com/cockroachdb/pebble/blob/055afc81b06735801e6b5a393d997a68eff50990/version_set.go#L236)):*
> ```Go
> 	manifestV1, err1 := readCurrentFile(dirname, vs.fs, fileTypeCurrent)
> 	manifestV2, err2 := readCurrentFile(dirname, vs.atomicRenameFS, fileTypeCurrentV2)
> 	if err1 != nil && err2 != nil {
> ```

How about a TODO that we currently cannot ignore CURRENT file corruption even if we have a CURRENT-v2 because we don't know which one is more recent.
Eventually we do want to not have this CURRENT that could be corrupt. Should we do a "migration" to stop writing it?

Maybe the simpler thing would be to keep writing it, but use Stat to decide that CURRENT-v2 is at least as recent as CURRENT, and use that to ignore a corrupt CURRENT. We would need to rearrange the order of writing such that CURRENT-v2 gets written second. Hmm, that doesn't work because the problem is a crash happening during the writing of CURRENT, so the problem exists whether we write it first or second.
At some additional cost we could use Link/Remove instead of Rename using the temp file. Create temp-current; create temp-current-v2; rename current-v2; link current; remove temp-current. If the crash happens during `link current` we have a corrupt file, but there is a corresponding byte identical temp-current that is older than current-v2 so we can ignore it. Checking for whether the bytes are identical could be done using the atomicRenameFS since it won't decrypt. An explicit migration seems simpler, but we don't have such support for non-CockroachDB users of Pebble.

**Review by jbowens — COMMENTED** [review]
> Glad you noticed it! I'm assuming the `WriteMinVersionFile` use case can use the unwrapped FS?

Yeah, that's right.

> IIRC, this `DataKeyRegistry` only grows since we don't have currently have a way to cleanup unused DataKeys. How about we use the same approach as the `FileRegistry` and turn it into a recordio file? We'd need another incompatible change, but we're already making one in this release, so that seems ok.

Using the record package for the `DataKeyRegistry` makes sense, but it doesn't address the atomic rename problem since it's stored on the store-FS. I guess we need to add a monotonically increasing number to the data key registry filename, and choose the highest numbered one on `Load`.

> In general we should always be writing files once and the already written parts should be immutable, since that leads to simpler correctness behavior -- so I'm not worried that this removal of atomic rename will be unsustainable longer term.

Don't immutable files increase the dependency on atomic renames, because you need some atomic operation to switch to a new set of immutable files? That said, I think the monotonically increasing number in filename approach is a fine for the handful of instances where we need an atomic filesystem operation.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1227#-:-MhZfuzp3rebnw1_IH6X:b-3n56vg)* status: 9 of 14 files reviewed, 1 unresolved discussion (waiting on @sumeerbhola)

___
*[version_set.go, line 236 at r4](https://reviewable.io/reviews/cockroachdb/pebble/1227#-MhY_pBD8Q_ujZDcT_wx:-MhZjpJ11Hj9PS4cJ262:b28qzpg) ([raw file](https://github.com/cockroachdb/pebble/blob/055afc81b06735801e6b5a393d997a68eff50990/version_set.go#L236)):*
> Checking for whether the bytes are identical could be done using the atomicRenameFS since it won't decrypt. 

I don't love that this makes assumptions about the wrapping `FS`. I could imagine a `vfs.FS` that performs a 1:1 translation of filenames for the purpose of encoding additional information, and a translation like that would break this.

> An explicit migration seems simpler, but we don't have such support for non-CockroachDB users of Pebble.

I started down a path like this, adding a `CompatibilityLevel` to `Options`. If the compatibility level was set appropriately, we could perform the explicit migration on start. CockroachDB would set the compatibility level once the version was finalized. I thought the broader compatibility of maintaining both files was less tricky.

> How about a TODO that we currently cannot ignore CURRENT file corruption even if we have a CURRENT-v2 because we don't know which one is more recent.

To make sure we're on the same page, we're talking about the case where:
* the database is opened with a recent Pebble version that creates a `CURRENT-v2` file.
* the database is opened with an old Pebble version that only updates the `CURRENT` file.
* the `CURRENT` file becomes corrupted, from disk rot or whatever.
* the database is opened again with a recent Pebble version, which mistakenly tries to use the `CURRENT-v2` file, pointing to an old manifest.

If the old manifest still exists, we might successfully start up from an old state.

In CockroachDB, this problem only exists when we're bouncing between CockroachDB versions. In that context, we can't yet perform the explicit migration because we need to maintain compatibility with the previous version. But we could continue to use exclusively the non-atomic `CURRENT` until the version finalization, which removes all possibility of accidental reversion to a previous manifest.

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1227)* status: 9 of 14 files reviewed, 1 unresolved discussion (waiting on @jbowens)

___
*[version_set.go, line 236 at r4](https://reviewable.io/reviews/cockroachdb/pebble/1227#-MhY_pBD8Q_ujZDcT_wx:-Mh_QTpM5IrJ7binvOjX:bbf2268) ([raw file](https://github.com/cockroachdb/pebble/blob/055afc81b06735801e6b5a393d997a68eff50990/version_set.go#L236)):*
> To make sure we're on the same page, we're talking about the case where

I misread the conjunction in `err1 != nil && err2 != nil` as a disjunction so I was thinking of a different problem, but we have a similar issue with the conjunction, as you outlined in your example -- we don't know when it is safe to ignore an error because the file that didn't produce the error may be stale.
It seems the `CompatibilityLevel` solution is the simplest and cleanest, and after it is advanced we would stop writing CURRENT (and delete the existing CURRENT) and only write CURRENT-v2. If it can only happen when the DB is opened, it is not as featureful as a CockroachDB migration, and it is possible that a node does not get started in a long time. How about allowing the CompatibilityLevel to be bumped up in an already open DB?

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1227)* status: 5 of 22 files reviewed, 1 unresolved discussion (waiting on @sumeerbhola)

___
*[version_set.go, line 236 at r4](https://reviewable.io/reviews/cockroachdb/pebble/1227#-MhY_pBD8Q_ujZDcT_wx:-MhuCJW-3l568ItmTy4t:b-bm69h9) ([raw file](https://github.com/cockroachdb/pebble/blob/055afc81b06735801e6b5a393d997a68eff50990/version_set.go#L236)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

> To make sure we're on the same page, we're talking about the case where

I misread the conjunction in `err1 != nil && err2 != nil` as a disjunction so I was thinking of a different problem, but we have a similar issue with the conjunction, as you outlined in your example -- we don't know when it is safe to ignore an error because the file that didn't produce the error may be stale.
It seems the `CompatibilityLevel` solution is the simplest and cleanest, and after it is advanced we would stop writing CURRENT (and delete the existing CURRENT) and only write CURRENT-v2. If it can only happen when the DB is opened, it is not as featureful as a CockroachDB migration, and it is possible that a node does not get started in a long time. How about allowing the CompatibilityLevel to be bumped up in an already open DB? 

</blockquote></details>

I updated the code to perform an explicit migration. I ended up renaming `CompatibilityLevel` to `FormatMajorVersion` because I wanted to convey that the compatibility relates to the on-disk format, and I had some trouble naming the `CompatibilityLevel` constants. Happy to iterate some more on the naming too.

The explicit migration can happen either through passing a higher `FormatMajorVersion` to `Options`, _or_ calling `RatchetFormatMajorVersion` during runtime.

One tricky bit I ran into is that upgrading the format major version also needs to be atomic. I decided to take advantage of the fact that we're already changing the `CURRENT` filename and encode the format version in that filename. Since the current file is _the_ first file that must be read while opening the database, it's early enough that we should be able to use it for backwards incompatible changes across all other files.

PTAL

**Comment by sumeerbhola** [comment]
> I'm distant from the implementation, but I would imagine that encryptedFS.Rename could add an entry for the new name to the encrypted manifest, perform the rename on disk, then remove the old entry. If a crash occurs before the on disk file has been renamed, the old manifest would be used. If a crash occurs before the old entry is removed, then we'd simply have a dangling entry in the encrypted manifest that needs to be cleaned up at startup. It is very possible I'm missing some complexity here.

Just to be explicit, the hard case is when we are doing rename(a, b), and b already exists. Say the previous version was b1 and now will become b2. Sequence of operations
1. manifest b points to b2
2. do fs rename
3. remove manifest entry for a
A crash can occur after 1. I realize you meant something more sophisticated since you said "If a crash occurs before the on disk file has been renamed, the old manifest would be used" -- the trick is knowing if the crash occurred before step 2 has finished, and we don't know that in the above trivial approach. One solution is to explicitly model renames in the file registry, as @jbowens said in his comment.

> If we migrate to a monotonically increasing scheme, how would we handle future backwards incompatible change? eg, where do we stick the format major version or equivalent?
> Part of the appeal of the CURRENT-XXXXXX file is that since the current file is the first one read when opening a database, it can be used to change the interpretation of every other file.

Those are compelling points for keeping the CURRENT file.

> We could encode renames to the file registry as a rename, including both the src and dst path. While replaying the file registry, the last record's operation may be incompletely applied to the filesystem. If the rename's src path still exists, we complete the rename.

If this rename at startup time fails for some reason do we crash the node? Normally an error on rename would be handled by the caller and perhaps without crashing. Also, I'm feeling vaguely nervous about changing the state of the filesystem at restart, but I don't have any clear concerns. 

My original suggestion about removing atomic renames was somewhat based on a distaste for exposing functionality that may not be present in a "distributed file system" (e.g. I believe s3 does not have atomic renames). I realize this is not actually compelling since the file operations we are exposing will continue to be done over "local" files since we are unlikely to move all Pebble files to something like s3. So if @jbowens @petermattis are convinced that offering atomic renames is the way to go, I'm fine with it.

**Review by jbowens — COMMENTED** [review]
> Also, I'm feeling vaguely nervous about changing the state of the filesystem at restart, but I don't have any clear concerns.

I hear you. It also makes me nervous that multiple `encryptedFS` write to the file registry. Both happen to use the same underlying FS, which means completing an incomplete rename on start is OK, but I don't like relying on it.

My biggest concerns with dropping rename atomicity right now is:
1. It necessitates backwards incompatiible changes that need to be made in several locations. I don't want to rush any backwards-incompatible changes out during stability period that we aren't completely confident in.
2. One of the code paths relying on rename atomicity wasn't found until recently. I'm not sure how to guard against new code paths being introduced. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1227#-:-MiMtDZDCpU5keF5m_UI:boqqqgm)* status: 23 of 24 files reviewed, 21 unresolved discussions (waiting on @itsbilal, @jbowens, @petermattis, and @sumeerbhola)

**Comment by sumeerbhola** [comment]
I'll try to summarize how I see things, just to make sure we are mostly consistent.
- We have 3 problematic rename cases: Manifest and current; file registry; data keys registry.
- We can deal with the current and file registry cases by using the unencrypted FS, but for the current case it requires the atomicRenameFS plumbing. The data keys registry needs to be an encrypted FS so we need a better solution for it.
- All of these cases also require the replacement file to contain a snapshot of the state. There is the danger of writing the snapshot in place, and a failure happening while writing, since a partial snapshot would cause corruption. This is regardless of the use of encrypted FS. We have two different solutions:
        - CURRENT file recording latest snapshot and using monotonic filenums: But we need to read the CURRENT file to figure out what is the latest, which creates the atomic rename issue for CURRENT.
        - Write to a tmp file, then rename tmp file, and reopen for append: This reopen increases the FS interface surface area. The rename of the tmp file can be to a monotonic name, but that is not currently the case for these use cases. So they currently need atomic rename.

Solution approaches: 
 - Support atomic rename in encrypted FS: this is the solution that involves completing the rename after restart, which we were getting nervous about. One concrete source of nervousness is read-only tools that as part of instantiating a file registry to read the files will cause mutations (and what if 2 such tools are running concurrently).
 - Switching everything over to a monotonic filename approach: Two options here
    - No explicit record of which is the latest: This means we do have to write to a tmp file and then rename, and then reopen for append. It does rely on a partial atomicity guarantee that if the destination filename exists, it must be complete. So it can't be used in some hypothetical FS that does rename via a non-atomic copy.
    - Explicit record of the latest, with the record in a filename: This is the the atomic marker solution. It doesn't need any guarantees from the FS; we don't need a tmp file; the atomic marker file does not need to be read. It does require listing the directory to find the atomic marker file. I have a small preference towards moving the marker name to the prefix, so that if we are working with a directory with a huge number of files and an FS where the names themselves are distributed (like colossus), then we can later optimize the listing using a glob where the prefix is specified.

We will eventually need a more complete key rotation solution. Could atomic rename have helped us do this transparently? Possibly not, since a transparent rotation solution may not know if the file being rewritten is also being written by the application (though we can fix that by tracking what is open for writes). Also, rewriting for key rotation is being done on the base-FS. We could decide (later) that we want to require the base-FS to support atomic renames. So I don't think we are going down a design path now that is worse for the key rotation future.

Overall, I'm leaning towards the atomic marker solution since it doesn't need any FS guarantees. I have a mild preference to also use it as a replacement for CURRENT rather than have a different custom implementation for CURRENT. We can use a separate VERSION-<versionnum> file for the versioning information.

**Comment by jbowens** [comment]
Thanks for the thorough writeup @sumeerbhola. I think we're on the same page. The prefix-glob point is a good one, and I think it's worth doing.

**Comment by jbowens** [comment]
>  If I'm understanding the marker correctly, we create the marker, sync, create the file the marker is for, sync, remove the marker.

The marker scheme that we had in mind is to maintain a single sidecar file that indicates which file is 'current'. In the case of Pebble manifest rotations, it moves the active manifest filename from the contents of the `CURRENT` file into the file _name_. During a manifest rotation, Pebble would create a new manifest file `MANIFEST-YYYYYY` and write its initial version edit. It would then rename the 'marker file' from its old position of `marker.current.MANIFEST-XXXXXX` to `marker.current.MANIFEST-YYYYYY` and sync the directory. On Open, Pebble needs to list the data directory and find the file with the marker's prefix, in this case `marker.current.`.

This scheme still requires rename to a destination that does not exist to be atomic. The requirement of listing the directory contents is one small downside. It also has the advantage that switching which manifest is active is only a `rename` and a `fsync`, rather than a `create`, `write`, `sync`, `rename`, `sync`.

**Comment by petermattis** [comment]
> This scheme still requires rename to a destination that does not exist to be atomic. The requirement of listing the directory contents is one small downside. It also has the advantage that switching which manifest is active is only a rename and a fsync, rather than a create, write, sync, rename, sync.

Thanks for the explanation, @jbowens. What happens if more than one marker file exists? Using the most recent sounds like the right heuristic, but I haven't thought this through. The "atomic marker" approach seems similar to the existing `CURRENT` approach, but with the difference that the indirection is contained in the file name instead of the file contents.

**Comment by jbowens** [comment]
> What happens if more than one marker file exists?

That should be treated as a programming error. The atomic marker should be created once when the database is created or migrated to begin using the marker. From then on, it should only be moved via rename. We're relying on the rename being atomic in the sense that _if the destination path doesn't exist_, no crash should leave both the old and new path present. I believe we have that guarantee.

I'm interpreting this section as only pertaining to the condition where _newpath already exists_:
>       If newpath already exists, it will be atomically replaced, so
>       that there is no point at which another process attempting to
>       access newpath will find it missing.  However, there will
>       probably be a window in which both oldpath and newpath refer to
>       the file being renamed.

**Comment by petermattis** [comment]
> I'm interpreting this section as only pertaining to the condition where newpath already exists:

Ok, though I have a small concern that may be an overly precise reading. Is it difficult to handle the situation of the marker existing multiple times? Seems like you can always use the marker corresponding to the highest sequence number and safely remove the other markers.

**Comment by jbowens** [comment]
> Ok, though I have a small concern that may be an overly precise reading. Is it difficult to handle the situation of the marker existing multiple times? Seems like you can always use the marker corresponding to the highest sequence number and safely remove the other markers.

Yeah, that's fair. I ended up going with a monotonically increasing sequence number in #1247.

**Review by sumeerbhola — APPROVED** [review]
:lgtm_strong: 

> Reviewed 30 of 30 files at r13, 3 of 3 files at r14, 5 of 5 files at r15, 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1227#-:-Mj6M3ElD8qv0nqN4Cic:b-uwkowd)* status: all files reviewed, 28 unresolved discussions (waiting on @itsbilal, @jbowens, @petermattis, and @sumeerbhola)

___
*[checkpoint.go, line 200 at r13](https://reviewable.io/reviews/cockroachdb/pebble/1227#-Mj6CESOC_2RUFXQx0cQ:-Mj6CESOC_2RUFXQx0cR:bx2yscp) ([raw file](https://github.com/cockroachdb/pebble/blob/f3727d02b1c73f23257cdff0179d768fcca62f31/checkpoint.go#L200)):*
> ```Go
> 		if ckErr != nil {
> 			return ckErr
> 		}
> ```

in this case there is no actual file with the name `formatVers.String()`, yes? It deserves a code comment.
___
*[format_major_version.go, line 34 at r13](https://reviewable.io/reviews/cockroachdb/pebble/1227#-Mj6DyA0AUQbSoIkgmKj:-Mj6DyA0AUQbSoIkgmKk:bfx5qxm) ([raw file](https://github.com/cockroachdb/pebble/blob/f3727d02b1c73f23257cdff0179d768fcca62f31/format_major_version.go#L34)):*
> ```Go
> 	// on-disk version marker file. Specifically, this value must always
> 	// parse as a 10-digit uint64.
> 	return fmt.Sprintf("%03d", v)
> ```

width 3? The code comment says 10 digit.
___
*[format_major_version.go, line 75 at r13](https://reviewable.io/reviews/cockroachdb/pebble/1227#-Mj6F3XQ4t7rLlxckOJe:-Mj6F3XQ4t7rLlxckOJf:b-bgttft) ([raw file](https://github.com/cockroachdb/pebble/blob/f3727d02b1c73f23257cdff0179d768fcca62f31/format_major_version.go#L75)):*
> ```Go
> // to set the new format major version.  RatchetFormatMajorVersion will
> // panic if a migration returns a non-nil error but fails to finalize
> // the new format major version.
> ```

I didn't understand this "... will panic ..." sentence. Why is the "but fails ..." relevant if it returned a non-nil error? Did you mean nil error?
___
*[format_major_version.go, line 120 at r13](https://reviewable.io/reviews/cockroachdb/pebble/1227#-Mj6FQoM7qa8XYP-GQ5m:-Mj6FQoM7qa8XYP-GQ5n:b-wqunbd) ([raw file](https://github.com/cockroachdb/pebble/blob/f3727d02b1c73f23257cdff0179d768fcca62f31/format_major_version.go#L120)):*
> ```Go
> 		return nil
> 	},
> 	FormatVersioned: func(d *DB) error {
> ```

Can you explain why we need to go through 2 versions to do this?
___
*[format_major_version_test.go, line 36 at r13](https://reviewable.io/reviews/cockroachdb/pebble/1227#-Mj6HSY8B6OlHvj8RhCa:-Mj6HSY8B6OlHvj8RhCb:bxaus1n) ([raw file](https://github.com/cockroachdb/pebble/blob/f3727d02b1c73f23257cdff0179d768fcca62f31/format_major_version_test.go#L36)):*
> ```Go
> 
> 	// If we Open the database again, still specifying the default
> 	// FormatMostCompatible format, the database should Open using the
> ```

should this say FormatDefault?

Can you add some cases in this test where it refuses to open?
___
*[format_major_version_test.go, line 90 at r13](https://reviewable.io/reviews/cockroachdb/pebble/1227#-Mj6I9q_3QljGh6fHSXv:-Mj6I9q_3QljGh6fHSXw:b-uqnv2f) ([raw file](https://github.com/cockroachdb/pebble/blob/f3727d02b1c73f23257cdff0179d768fcca62f31/format_major_version_test.go#L90)):*
> ```Go
> 
> 			t.Run("upgrade-at-open", func(t *testing.T) {
> 				for upgradeVers := vers + 1; upgradeVers <= FormatNewest; upgradeVers++ {
> ```

So this is also testing when the upgrade version is more than 1 higher than the current version?
___
*[options.go, line 929 at r11](https://reviewable.io/reviews/cockroachdb/pebble/1227#-Mi6csBFEJW3cdjdTbbM:-Mj6JlR17beUldqRp03M:b-aowqlz) ([raw file](https://github.com/cockroachdb/pebble/blob/95ac914bd66369589cdd6d53ae308c03ecffb0aa/options.go#L929)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

> and there's no mechanism for determining which OPTIONS-XXXXXX file is the most recent.
> I'm now wondering if a crash while writing the OPTIONS file during Open might cause subsequent opens to fail if the incomplete OPTIONS-XXXXXX file doesn't contain the comparer field. 

I guess we've been very lucky!
At least there is a monotonic suffix, so we can fix this with the `rename(tmp file, new file name)` pattern.
We should clarify in vfs.go that even non-atomic renames guarantee that in the above case if you find "new file name" it will be what you expect.
</blockquote></details>

Is there an issue for tracking corruption of the OPTIONS file?
___
*[options.go, line 395 at r13](https://reviewable.io/reviews/cockroachdb/pebble/1227#-Mj6JVSw7SlHXq0DoHV0:-Mj6JVSw7SlHXq0DoHV1:b-xbpgu3) ([raw file](https://github.com/cockroachdb/pebble/blob/f3727d02b1c73f23257cdff0179d768fcca62f31/options.go#L395)):*
> ```Go
> 	// the existing database's version is unknown, the caller may use
> 	// FormatMostCompatible and will be able to open the database
> 	// regardless of its actual version.
> ```

FormatMostCompatible or FormatDefault?

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1227)* status: 25 of 35 files reviewed, 28 unresolved discussions (waiting on @itsbilal, @jbowens, @petermattis, and @sumeerbhola)

___
*[checkpoint.go, line 200 at r13](https://reviewable.io/reviews/cockroachdb/pebble/1227#-Mj6CESOC_2RUFXQx0cQ:-MjA1f-vBvNb3-ZD8ba2:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/f3727d02b1c73f23257cdff0179d768fcca62f31/checkpoint.go#L200)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

in this case there is no actual file with the name `formatVers.String()`, yes? It deserves a code comment.
</blockquote></details>

Done.
___
*[format_major_version.go, line 34 at r13](https://reviewable.io/reviews/cockroachdb/pebble/1227#-Mj6DyA0AUQbSoIkgmKj:-MjA2RG804OwXAqlBaq7:b-s5hr5y) ([raw file](https://github.com/cockroachdb/pebble/blob/f3727d02b1c73f23257cdff0179d768fcca62f31/format_major_version.go#L34)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

width 3? The code comment says 10 digit.
</blockquote></details>

thanks, I meant to say base 10. fixed the comment.
___
*[format_major_version.go, line 75 at r13](https://reviewable.io/reviews/cockroachdb/pebble/1227#-Mj6F3XQ4t7rLlxckOJe:-MjA2ifV0pwsGMS5diC4:b-aq6ut7) ([raw file](https://github.com/cockroachdb/pebble/blob/f3727d02b1c73f23257cdff0179d768fcca62f31/format_major_version.go#L75)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I didn't understand this "... will panic ..." sentence. Why is the "but fails ..." relevant if it returned a non-nil error? Did you mean nil error?
</blockquote></details>

yeah, I meant a nil error. fixed!
___
*[format_major_version.go, line 120 at r13](https://reviewable.io/reviews/cockroachdb/pebble/1227#-Mj6FQoM7qa8XYP-GQ5m:-MjA4wjC66dLX5MEBWx8:b-ffcuim) ([raw file](https://github.com/cockroachdb/pebble/blob/f3727d02b1c73f23257cdff0179d768fcca62f31/format_major_version.go#L120)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Can you explain why we need to go through 2 versions to do this?
</blockquote></details>

Added a comment above this migration. It's necessary to make sure the replacement of the `CURRENT` file happens if there's a crash after the version is finalized, but before replacement of the current file.
___
*[format_major_version_test.go, line 36 at r13](https://reviewable.io/reviews/cockroachdb/pebble/1227#-Mj6HSY8B6OlHvj8RhCa:-MjA7BFP2SIlqmL89rbk:bf1yxbw) ([raw file](https://github.com/cockroachdb/pebble/blob/f3727d02b1c73f23257cdff0179d768fcca62f31/format_major_version_test.go#L36)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

should this say FormatDefault?

Can you add some cases in this test where it refuses to open?
</blockquote></details>

`FormatDefault` gets replaced by `FormatMostComptabile` by `(*Options).EnsureDefaults` so both are correct.
___
*[format_major_version_test.go, line 90 at r13](https://reviewable.io/reviews/cockroachdb/pebble/1227#-Mj6I9q_3QljGh6fHSXv:-MjA9Ort9AqbEjQ6eG5F:bsd2y6r) ([raw file](https://github.com/cockroachdb/pebble/blob/f3727d02b1c73f23257cdff0179d768fcca62f31/format_major_version_test.go#L90)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

So this is also testing when the upgrade version is more than 1 higher than the current version?
</blockquote></details>

yeah, that's right.
___
*[options.go, line 929 at r11](https://reviewable.io/reviews/cockroachdb/pebble/1227#-Mi6csBFEJW3cdjdTbbM:-MjA6rt98TCvBHBna3kL:bni3c9j) ([raw file](https://github.com/cockroachdb/pebble/blob/95ac914bd66369589cdd6d53ae308c03ecffb0aa/options.go#L929)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Is there an issue for tracking corruption of the OPTIONS file?
</blockquote></details>

Yeah, #1243.
___
*[options.go, line 395 at r13](https://reviewable.io/reviews/cockroachdb/pebble/1227#-Mj6JVSw7SlHXq0DoHV0:-MjA9Xmh5mrx4U-SOXAf:b-6w7ks9) ([raw file](https://github.com/cockroachdb/pebble/blob/f3727d02b1c73f23257cdff0179d768fcca62f31/options.go#L395)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

FormatMostCompatible or FormatDefault?
</blockquote></details>

FormatMostCompatible is right. FormatDefault defaults to FormatMostCompatible, so that existing users of Pebble will continue to operate at the un-upgraded, RocksDB-compatible format version without making any code changes. These two separate constants allow us to eventually update the default, if for example we decide to drop support for the `CURRENT` file from the Pebble codebase because it cleans up our code.

If the `FormatDefault == FormatMostCompatible` is confusing, we could unexport `FormatDefault`. That would still ensure that the zero value `FormatMajorVersion` has its own value that we can populate in `EnsureDefaults`.
___
*[version_set.go, line 219 at r12](https://reviewable.io/reviews/cockroachdb/pebble/1227#-Mi7n1-U1NxPHjmghFfK:-MjA75_g9_dVll4nUtVS:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/d622d6e7e15a4f5b8569000382592914ebc7db45/version_set.go#L219)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

the gap between FormatMostCompatible and vs.formatVers can be many versions. If we are indeed upgrading the version on opening this DB, then the actual current file that needs deletion is for a version later than FormatMostCompatible.

btw, perhaps we should require that callers only upgrade one version at a time.
</blockquote></details>

Done.

**Review by jbowens — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1227#-:-MjALrVFBcUD824TSgkH:b-814g8k)* status: 25 of 35 files reviewed, 28 unresolved discussions (waiting on @itsbilal, @jbowens, @petermattis, and @sumeerbhola)

**Pull request merged**
