### PR TITLE
objstorage: introduce shared object catalog

### PR DESCRIPTION
**Pull request by RaduBerinde**
This commit adds code for a shared object catalog. It is implemented very similarly to the manifest: the catalog file contains multiple records, where each record is an encoded version edit. A marker file is used to keep track of the latest file.

The new code is not yet used.

### CODE REVIEW

**Comment by bananabrick** [comment]
Will leave the review to bilal, but a minor nit: Could we use the rebase + merge option for the pr, instead of just merge? We don't have a rule either way, but it keeps the commit history clean.

**Comment by RaduBerinde** [comment]
Sure. I usually rebase before merging just to make sure the tests still pass

**Review by jbowens — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2291)* status: 0 of 5 files reviewed, 6 unresolved discussions (waiting on @itsbilal and @RaduBerinde)

___
*[`objstorage/sharedobjcat/catalog.go` line 79 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2291#-NNMnsTo2TibOlF2uPHg:-NNMnsTo2TibOlF2uPHh:b6prtbp) ([raw file](https://github.com/cockroachdb/pebble/blob/a0c5bb91cffac0e9dd51bf073f70c62d9db51f77/objstorage/sharedobjcat/catalog.go#L79)):*
> ```Go
> 		// TODO(radu): remove obsolete catalog files.
> 	}
> 	return c, c.mu.objects, nil
> ```

since `c.mu.objects` is guarded by `c.mu`, should it escape to the caller? it seems easy to accidentally misuse
___
*[`objstorage/sharedobjcat/catalog.go` line 99 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2291#-NNMuIda2XmWV7in0n0G:-NNMuIda2XmWV7in0n0H:b-bangvq) ([raw file](https://github.com/cockroachdb/pebble/blob/a0c5bb91cffac0e9dd51bf073f70c62d9db51f77/objstorage/sharedobjcat/catalog.go#L99)):*
> ```Go
> // AddObject adds a shared object to the catalog; returns after the change is
> // stably recorded on storage.
> func (c *Catalog) AddObject(fileNum base.FileNum, meta SharedObjectMetadata) {
> ```

when a compaction is creating a series of _N_ files in shared storage, and removing _M_ files, does it need to suffer _N_+_M_ additional fsyncs? Could we avoid that by using a batched API?
___
*[`objstorage/sharedobjcat/catalog.go` line 114 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2291#-NNMsApi6asRjaCs40Xh:-NNMsApi6asRjaCs40Xi:b-u4rowp) ([raw file](https://github.com/cockroachdb/pebble/blob/a0c5bb91cffac0e9dd51bf073f70c62d9db51f77/objstorage/sharedobjcat/catalog.go#L114)):*
> ```Go
> }
> 
> // DeleteObject deletes a shared object to the catalog; returns after the change
> ```

nit: s/to the catalog/from the catalog/
___
*[`objstorage/sharedobjcat/catalog.go` line 132 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2291#-NNMvq6e2U_9bY-cRjzR:-NNMvq6e2U_9bY-cRjzS:bs8ifsu) ([raw file](https://github.com/cockroachdb/pebble/blob/a0c5bb91cffac0e9dd51bf073f70c62d9db51f77/objstorage/sharedobjcat/catalog.go#L132)):*
> ```Go
> 
> func (c *Catalog) loadFromCatalogFile(filename string) error {
> 	c.mu.objects = make(CatalogContents)
> ```

nit: `Open` also initializes `c.mu.objects`; should the responsibility to initialize it lie with `loadFromCatalogFile` and `createNewCatalogFileLocked`, or exclusively `Open`?
___
*[`objstorage/sharedobjcat/version_edit.go` line 19 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2291#-NNMxBEXA4NuSbXkxReh:-NNMxBEXA4NuSbXkxRei:bypf994) ([raw file](https://github.com/cockroachdb/pebble/blob/a0c5bb91cffac0e9dd51bf073f70c62d9db51f77/objstorage/sharedobjcat/version_edit.go#L19)):*
> ```Go
> type versionEdit struct {
> 	NewObjects     map[base.FileNum]SharedObjectMetadata
> 	DeletedObjects map[base.FileNum]struct{}
> ```

how will the global file numbers be assigned? the ordinary manifest tracks which filenums have already been used.
___
*[`objstorage/sharedobjcat/testdata/catalog` line 16 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2291#-NNMzbEn1dPzk-9HiLaa:-NNMzbEn1dPzk-9HiLab:bjhmutf) ([raw file](https://github.com/cockroachdb/pebble/blob/a0c5bb91cffac0e9dd51bf073f70c62d9db51f77/objstorage/sharedobjcat/testdata/catalog#L16)):*
> ```
> 
> add 2 20 200
> ----
> ```

nit: because the sequence of fsyncing of the manifest (and the directory when rotating) is important for durability, we could consider using a logging VFS that includes these low-level file operations in the command output, (eg, like the [checkpoint](https://github.com/cockroachdb/pebble/blob/master/testdata/checkpoint) test)

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2291)* status: 0 of 5 files reviewed, 6 unresolved discussions (waiting on @itsbilal and @jbowens)

___
*[`objstorage/sharedobjcat/catalog.go` line 99 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2291#-NNMuIda2XmWV7in0n0G:-NNNl4mpAIcwCN2wTGdm:b-eps34v) ([raw file](https://github.com/cockroachdb/pebble/blob/a0c5bb91cffac0e9dd51bf073f70c62d9db51f77/objstorage/sharedobjcat/catalog.go#L99)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

when a compaction is creating a series of _N_ files in shared storage, and removing _M_ files, does it need to suffer _N_+_M_ additional fsyncs? Could we avoid that by using a batched API?
</blockquote></details>

A batched API would be easy to add here. The problem is that currently we create and remove objects one at a time, the hard part is changing how things work in compaction code.

I think we could design an "operation context" in the Provider where any object creation or deletion is only guaranteed to become durable when you finish that context. I think that way we could perform all catalog operations at the end. Will give this some more thought (and maybe add a batch API here).
___
*[`objstorage/sharedobjcat/version_edit.go` line 19 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2291#-NNMxBEXA4NuSbXkxReh:-NNNmWFx-q8N2oalfwKR:bkkeck8) ([raw file](https://github.com/cockroachdb/pebble/blob/a0c5bb91cffac0e9dd51bf073f70c62d9db51f77/objstorage/sharedobjcat/version_edit.go#L19)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

how will the global file numbers be assigned? the ordinary manifest tracks which filenums have already been used.
</blockquote></details>

The file numbers always come from higher-level code (i.e.`versions.getNextFileNum()`).
___
*[`objstorage/sharedobjcat/testdata/catalog` line 16 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2291#-NNMzbEn1dPzk-9HiLaa:-NNNn-RLAnE3rWIAOg8F:b-dktmie) ([raw file](https://github.com/cockroachdb/pebble/blob/a0c5bb91cffac0e9dd51bf073f70c62d9db51f77/objstorage/sharedobjcat/testdata/catalog#L16)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

nit: because the sequence of fsyncing of the manifest (and the directory when rotating) is important for durability, we could consider using a logging VFS that includes these low-level file operations in the command output, (eg, like the [checkpoint](https://github.com/cockroachdb/pebble/blob/master/testdata/checkpoint) test)
</blockquote></details>

Great idea, will work on that.

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2291)* status: 0 of 5 files reviewed, 6 unresolved discussions (waiting on @itsbilal and @RaduBerinde)

___
*[`objstorage/sharedobjcat/version_edit.go` line 19 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2291#-NNMxBEXA4NuSbXkxReh:-NNO87BZ9YnIPsIsnS90:bj2qea3) ([raw file](https://github.com/cockroachdb/pebble/blob/a0c5bb91cffac0e9dd51bf073f70c62d9db51f77/objstorage/sharedobjcat/version_edit.go#L19)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

The file numbers always come from higher-level code (i.e.`versions.getNextFileNum()`).
</blockquote></details>

I was confused and was thinking that we would be providing globally unique file numbers for shared objects. But we're not, we're guaranteeing global uniqueness on (CreatorID,FileNum) tuples, right? So then the keys in these maps (and in `CatalogContents`) are local `FileNum`s. Probably worth a comment declaring them as locally-assigned file nums.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2291)* status: 0 of 5 files reviewed, 6 unresolved discussions (waiting on @itsbilal and @jbowens)

___
*[`objstorage/sharedobjcat/version_edit.go` line 19 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2291#-NNMxBEXA4NuSbXkxReh:-NNODct10HJEnzQFJmK8:b-1nxxmc) ([raw file](https://github.com/cockroachdb/pebble/blob/a0c5bb91cffac0e9dd51bf073f70c62d9db51f77/objstorage/sharedobjcat/version_edit.go#L19)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

I was confused and was thinking that we would be providing globally unique file numbers for shared objects. But we're not, we're guaranteeing global uniqueness on (CreatorID,FileNum) tuples, right? So then the keys in these maps (and in `CatalogContents`) are local `FileNum`s. Probably worth a comment declaring them as locally-assigned file nums.
</blockquote></details>

Correct. We are using `FileNum` just as it is documented: "identifier of a file within a database"

**Review by itsbilal — COMMENTED** [review]
Mostly looking great! Just some minor comments. Thanks for doing this!

> Reviewed 2 of 5 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2291#-:-NNY1SLEEau01jzOvjUK:b-i1nwvb)* status: all files reviewed, 10 unresolved discussions (waiting on @jbowens and @RaduBerinde)

___
*[`objstorage/sharedobjcat/catalog.go` line 99 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2291#-NNMuIda2XmWV7in0n0G:-NNY-8VfDnb_7ayfL8wB:baos2k9) ([raw file](https://github.com/cockroachdb/pebble/blob/a0c5bb91cffac0e9dd51bf073f70c62d9db51f77/objstorage/sharedobjcat/catalog.go#L99)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

A batched API would be easy to add here. The problem is that currently we create and remove objects one at a time, the hard part is changing how things work in compaction code.

I think we could design an "operation context" in the Provider where any object creation or deletion is only guaranteed to become durable when you finish that context. I think that way we could perform all catalog operations at the end. Will give this some more thought (and maybe add a batch API here).
</blockquote></details>

The ingestion case will create multiple shared objects at a time - sometimes lots at once. I think we should add an AddObjects that takes in SharedObjectMetadatas (or some struct that combines that and the local `FileNum`.
___
*[`objstorage/sharedobjcat/catalog.go` line 29 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2291#-NNY0o4Z6Ylf5uErumUz:-NNY0o4Z6Ylf5uErumV-:bxx3w4k) ([raw file](https://github.com/cockroachdb/pebble/blob/498695d40724776bcab6662e9aac2a045a345879/objstorage/sharedobjcat/catalog.go#L29)):*
> ```Go
> 		sync.Mutex
> 
> 		objects CatalogContents
> ```

Instead of having this as a public map that we return, it might be a good idea to make the mutex an `RWMutex` and add a `GetObject` that returns `Catalog.mu.objects[fileNum]` (if it exists), where `GetObject` can do the grabbing/releasing of the RWMutex. That way the external user doesn't need to be aware of the map internals or any concurrency stuff.
___
*[`objstorage/sharedobjcat/catalog.go` line 53 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2291#-NNY-lPtCGDQgmZJbPcw:-NNY-lPtCGDQgmZJbPcx:b8cj68h) ([raw file](https://github.com/cockroachdb/pebble/blob/498695d40724776bcab6662e9aac2a045a345879/objstorage/sharedobjcat/catalog.go#L53)):*
> ```Go
> 
> const (
> 	catalogFilenameBase = "SHARED-OBJ-CATALOG"
> ```

nit: I prefer `SHARED-CATALOG` but okay with this too
___
*[`objstorage/sharedobjcat/catalog.go` line 149 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2291#-NNY1IN6AUR0VodFWbqS:-NNY1IN6AUR0VodFWbqT:bv1jndo) ([raw file](https://github.com/cockroachdb/pebble/blob/498695d40724776bcab6662e9aac2a045a345879/objstorage/sharedobjcat/catalog.go#L149)):*
> ```Go
> 
> // ApplyBatch applies a batch of updates; returns after the change is stably recorded on storage.
> func (c *Catalog) ApplyBatch(b *Batch) {
> ```

Can probably be unexported if we are only gonna interact with the other methods like Add/DeleteObject?
___
*[`objstorage/sharedobjcat/version_edit.go` line 18 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2291#-NNY-Xhk4FeRQiU2ITeo:-NNY-Xhk4FeRQiU2ITep:b204yss) ([raw file](https://github.com/cockroachdb/pebble/blob/498695d40724776bcab6662e9aac2a045a345879/objstorage/sharedobjcat/version_edit.go#L18)):*
> ```Go
> // into a record.
> type versionEdit struct {
> 	NewObjects     map[base.FileNum]SharedObjectMetadata
> ```

This can just be []SharedObjectMetadata (which I'm convinced should probably contain the local FileNum). A map is somewhat expensive for little extra utility.

**Review by RaduBerinde — COMMENTED** [review]
TFTRs! Great feedback! Will work on it a bit more. I will implement file rotation as well so we don't have to come back to that later.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2291#-:-NNZphm42SqcF7LUBvh7:b-enub4e)* status: all files reviewed, 10 unresolved discussions (waiting on @itsbilal and @jbowens)

___
*[`objstorage/sharedobjcat/catalog.go` line 99 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2291#-NNMuIda2XmWV7in0n0G:-NNYIyEK2yUm-D0k4G8B:b-ii3e7d) ([raw file](https://github.com/cockroachdb/pebble/blob/a0c5bb91cffac0e9dd51bf073f70c62d9db51f77/objstorage/sharedobjcat/catalog.go#L99)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

The ingestion case will create multiple shared objects at a time - sometimes lots at once. I think we should add an AddObjects that takes in SharedObjectMetadatas (or some struct that combines that and the local `FileNum`.
</blockquote></details>

That's what `Batch / ApplyBatch` is for - doing multiple operations. Actually I think I will remove the `AddObject / DeleteObject` altogether so that the batch is the only way. And I think the plan for the higher level objstorage API will be that you have to call a `Provider.Sync()` method to guarantee object creations and deletions are durable; the `Sync` method will call  `Sync()` on the local dir and apply a batch to the catalog as needed. That maps nicely to what we are doing now.
___
*[`objstorage/sharedobjcat/catalog.go` line 29 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2291#-NNY0o4Z6Ylf5uErumUz:-NNYIBa8BJHn69UuLefh:b-r1ie1c) ([raw file](https://github.com/cockroachdb/pebble/blob/498695d40724776bcab6662e9aac2a045a345879/objstorage/sharedobjcat/catalog.go#L29)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Instead of having this as a public map that we return, it might be a good idea to make the mutex an `RWMutex` and add a `GetObject` that returns `Catalog.mu.objects[fileNum]` (if it exists), where `GetObject` can do the grabbing/releasing of the RWMutex. That way the external user doesn't need to be aware of the map internals or any concurrency stuff.
</blockquote></details>

We can just return a copy here (it can be a `[]SharedObjectMetadata`) - the higher layer needs a list of all the FileNums in the catalog on init so a `GetObject` wouldn't suffice. Other than initialization, it's all up to the higher layer what changes in the catalog. That this layer maintains the current contents internally is a consequence of the implementation (specifically that it has to be able to rotate the catalog file).

**Review by itsbilal — COMMENTED** [review]
For some reason I had one comment in my review that didn't get published, so sending that again. But sounds good!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2291#-:-NNbIvyF23FnH6DnQ5WE:b-cizbuv)* status: 0 of 5 files reviewed, 11 unresolved discussions (waiting on @jbowens and @RaduBerinde)

___
*[`objstorage/sharedobjcat/catalog.go` line 5 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2291#-NNbJ-F73iKK_aETJThy:-NNbJ-F73iKK_aETJThz:b-wemc5c) ([raw file](https://github.com/cockroachdb/pebble/blob/9a5494fb12a8d23e5d89ffd99c82b326aab9e86f/objstorage/sharedobjcat/catalog.go#L5)):*
> ```Go
> // the LICENSE file.
> 
> package sharedobjcat
> ```

Maybe the package name should just be `shared` - that way `objstorage.shared.Catalog` just makes sense without repeating words. We can put anything else that's relevant to shared obj storage inside this package.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2291)* status: 2 of 5 files reviewed, 13 unresolved discussions (waiting on @itsbilal, @jbowens, and @sumeerbhola)

___
*[`objstorage/sharedobjcat/catalog.go` line 79 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2291#-NNMnsTo2TibOlF2uPHg:-NNZtxuT0XzbiN2cFIO_:b1cr95h) ([raw file](https://github.com/cockroachdb/pebble/blob/a0c5bb91cffac0e9dd51bf073f70c62d9db51f77/objstorage/sharedobjcat/catalog.go#L79)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

since `c.mu.objects` is guarded by `c.mu`, should it escape to the caller? it seems easy to accidentally misuse
</blockquote></details>

Changed to return a copy, as `[]SharedObjectMetadata`
___
*[`objstorage/sharedobjcat/catalog.go` line 5 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2291#-NNbJ-F73iKK_aETJThy:-NNbso6G6raNVmIjOiy_:b-au275v) ([raw file](https://github.com/cockroachdb/pebble/blob/9a5494fb12a8d23e5d89ffd99c82b326aab9e86f/objstorage/sharedobjcat/catalog.go#L5)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Maybe the package name should just be `shared` - that way `objstorage.shared.Catalog` just makes sense without repeating words. We can put anything else that's relevant to shared obj storage inside this package.
</blockquote></details>

But we'd never use `objstorage.shared.Catalog`, the code would just show `shared.Catalog` which is pretty generic. I'd really like to keep this a separate package since it has a clean external interface.
___
*[`objstorage/sharedobjcat/catalog.go` line 70 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2291#-NNbJMSZD1TCSky6fS4x:-NNbt8CI51fA2eidkHMG:b-pox4gf) ([raw file](https://github.com/cockroachdb/pebble/blob/9a5494fb12a8d23e5d89ffd99c82b326aab9e86f/objstorage/sharedobjcat/catalog.go#L70)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

what is the caller expected to do with `CatalogContents`? Is this just for testing?
</blockquote></details>

The Provider needs to maintain a map of the current objects (at least to know which FileNum is local and which is shared). We initialize the local objects by Listing the directory, and we initialize the shared objects with what this function returns.
___
*[`objstorage/sharedobjcat/catalog.go` line 207 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2291#-NNbKTtT-Q_CgAps1dCb:-NNbrevA6wNcDWhI8B3i:b-fxllmw) ([raw file](https://github.com/cockroachdb/pebble/blob/9a5494fb12a8d23e5d89ffd99c82b326aab9e86f/objstorage/sharedobjcat/catalog.go#L207)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

The delta records are likely to be tiny (single file creation or deletion), so if the baseline catalog file becomes huge (when writing the snapshot) then a few (8) delta records will trigger this rollover. We had a similar problem with the Pebble MANIFEST. There is some discussion in https://github.com/cockroachdb/pebble/blob/4eba71e57532f72b87f81cede09a9a88997f91fe/version_set.go#L400-L457 on how this was fixed. We could do something similar here. It is also fine to leave a TODO and do this as a followup PR.
</blockquote></details>

Yeah, I was thinking about this issue too. I came up with a simple heuristic that is along the lines of what you quoted here but less sophisticated. I will see if maybe I can extract the existing heuristic into something that can be reused.
___
*[`objstorage/sharedobjcat/catalog.go` line 248 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2291#-NNbIo6Q4uQvNLp3ekz_:-NNbsbewCOfan9W0ZxKF:bygn1p) ([raw file](https://github.com/cockroachdb/pebble/blob/9a5494fb12a8d23e5d89ffd99c82b326aab9e86f/objstorage/sharedobjcat/catalog.go#L248)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

is `numRecords` 0 after this, so `numRecords` only tracks the deltas? If yes, worth a code comment where it is declared.
</blockquote></details>

It was an omission, the latest version has a `numRecords = 1` below.
___
*[`objstorage/sharedobjcat/version_edit.go` line 18 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2291#-NNY-Xhk4FeRQiU2ITeo:-NNZu6JNAqJIWfTQfdaw:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/498695d40724776bcab6662e9aac2a045a345879/objstorage/sharedobjcat/version_edit.go#L18)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

This can just be []SharedObjectMetadata (which I'm convinced should probably contain the local FileNum). A map is somewhat expensive for little extra utility.
</blockquote></details>

Done.
___
*[`objstorage/sharedobjcat/version_edit.go` line 18 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2291#-NNbGWgK6seDx7N8UYWn:-NNbu8pg6h3OCpB6-SAJ:bxqdz0z) ([raw file](https://github.com/cockroachdb/pebble/blob/9a5494fb12a8d23e5d89ffd99c82b326aab9e86f/objstorage/sharedobjcat/version_edit.go#L18)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

How about adding the "creation time" to the SharedObjectMetadata, i.e., the time this file became known to the catalog.
And the deletion time to the deleted objects.
Can be useful for debugging.
</blockquote></details>

The deletion time would only ever be visible if we looked at individual `versionEdit` records in the file, right? (not saying it's not useful, just want to make sure we're on the same page)

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2291)* status: 2 of 5 files reviewed, 13 unresolved discussions (waiting on @itsbilal, @jbowens, and @RaduBerinde)

___
*[`objstorage/sharedobjcat/catalog.go` line 70 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2291#-NNbJMSZD1TCSky6fS4x:-NNc498_DAo2HXsEBZD-:b-wertg) ([raw file](https://github.com/cockroachdb/pebble/blob/9a5494fb12a8d23e5d89ffd99c82b326aab9e86f/objstorage/sharedobjcat/catalog.go#L70)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

The Provider needs to maintain a map of the current objects (at least to know which FileNum is local and which is shared). We initialize the local objects by Listing the directory, and we initialize the shared objects with what this function returns.
</blockquote></details>

Does it need to maintain its own map when the catalog has a map?
I suppose the answer is yes since it would keep both local and shared in the same map. And I'm assuming the consistency story is straightforward: update its own map and call `ApplyBatch` while holding a mutex. Sound right?
___
*[`objstorage/sharedobjcat/version_edit.go` line 18 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2291#-NNbGWgK6seDx7N8UYWn:-NNc5Kn90AQGEj8Ah2A6:b1pdbcm) ([raw file](https://github.com/cockroachdb/pebble/blob/9a5494fb12a8d23e5d89ffd99c82b326aab9e86f/objstorage/sharedobjcat/version_edit.go#L18)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

The deletion time would only ever be visible if we looked at individual `versionEdit` records in the file, right? (not saying it's not useful, just want to make sure we're on the same page)
</blockquote></details>

Yep. We could do something like `NumPrevManifest`, where we keep some obsolete catalog files around.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2291)* status: 2 of 5 files reviewed, 13 unresolved discussions (waiting on @itsbilal, @jbowens, and @sumeerbhola)

___
*[`objstorage/sharedobjcat/catalog.go` line 70 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2291#-NNbJMSZD1TCSky6fS4x:-NNc9J8T8FzzAOVQHl9M:b76k7er) ([raw file](https://github.com/cockroachdb/pebble/blob/9a5494fb12a8d23e5d89ffd99c82b326aab9e86f/objstorage/sharedobjcat/catalog.go#L70)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Does it need to maintain its own map when the catalog has a map?
I suppose the answer is yes since it would keep both local and shared in the same map. And I'm assuming the consistency story is straightforward: update its own map and call `ApplyBatch` while holding a mutex. Sound right?
</blockquote></details>

I think we'll want to apply the batch explicitly, similarly to how we call `Sync` on the FS dir. That will allow us to coalesce multiple object changes into a single I/O to the catalog (I consider the catalog analogous to the FS dir metadata).

So on object create or delete, we update its own map  plus add to an internal `Batch` (protected by the mutex), and then inside a later `Sync()` function call we do `ApplyBatch` (also while holding the mutex).

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2291)* status: 0 of 10 files reviewed, 13 unresolved discussions (waiting on @itsbilal, @jbowens, and @sumeerbhola)

___
*[`objstorage/sharedobjcat/catalog.go` line 207 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2291#-NNbKTtT-Q_CgAps1dCb:-NNcCWpT6PJkhTjm5LZe:b-pywpcu) ([raw file](https://github.com/cockroachdb/pebble/blob/9a5494fb12a8d23e5d89ffd99c82b326aab9e86f/objstorage/sharedobjcat/catalog.go#L207)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Yeah, I was thinking about this issue too. I came up with a simple heuristic that is along the lines of what you quoted here but less sophisticated. I will see if maybe I can extract the existing heuristic into something that can be reused.
</blockquote></details>

I extracted out the core logic into a `record.RotationHelper` (in a separate commit) and I switched to using that here. We should probably use it in the encrypted file registry as well. PTAL

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2291)* status: 0 of 10 files reviewed, 13 unresolved discussions (waiting on @itsbilal, @jbowens, and @sumeerbhola)

___
*[`objstorage/sharedobjcat/testdata/catalog` line 16 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2291#-NNMzbEn1dPzk-9HiLaa:-NNchTT4ARfk1ZrCbt9-:b-wc615k) ([raw file](https://github.com/cockroachdb/pebble/blob/a0c5bb91cffac0e9dd51bf073f70c62d9db51f77/objstorage/sharedobjcat/testdata/catalog#L16)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Great idea, will work on that.
</blockquote></details>

I hooked up the logging FS to the test.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2291)* status: 0 of 10 files reviewed, 13 unresolved discussions (waiting on @itsbilal, @jbowens, and @sumeerbhola)

___
*[`objstorage/sharedobjcat/catalog.go` line 151 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2291#-NNbJ5nc7sDeJCHF2_6q:-NNciuDb1335m5nyyMrC:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/9a5494fb12a8d23e5d89ffd99c82b326aab9e86f/objstorage/sharedobjcat/catalog.go#L151)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I think we need some error checking to ensure that the batch is adding files that are not already in the catalog and removing files that are in the catalog.
</blockquote></details>

Done.
___
*[`objstorage/sharedobjcat/version_edit.go` line 18 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2291#-NNbGWgK6seDx7N8UYWn:-NNciwR_ELExxhwtguMP:bp0muha) ([raw file](https://github.com/cockroachdb/pebble/blob/9a5494fb12a8d23e5d89ffd99c82b326aab9e86f/objstorage/sharedobjcat/version_edit.go#L18)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Yep. We could do something like `NumPrevManifest`, where we keep some obsolete catalog files around.
</blockquote></details>

I added a TODO for now.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2291)* status: 8 of 10 files reviewed, 15 unresolved discussions (waiting on @itsbilal, @jbowens, and @sumeerbhola)

___
*[`record/rotation.go` line 54 at r4](https://reviewable.io/reviews/cockroachdb/pebble/2291#-NNglJpkAU5ce1zpV1DY:-NNh2mgICfzoRLnd8sVh:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/55ff7ecdb866c486c1a4488f710743be04e18904/record/rotation.go#L54)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

should this be 0.9S?
</blockquote></details>

Done.
___
*[`record/rotation.go` line 63 at r4](https://reviewable.io/reviews/cockroachdb/pebble/2291#-NNglfDB1IsHjsgeLaIW:-NNh47ikBhWxYN6odKRt:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/55ff7ecdb866c486c1a4488f710743be04e18904/record/rotation.go#L63)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

... writing a new snapshot, if we required that E > the current size, that is E > 10S. This is not desirable. 
</blockquote></details>

Done.

**Pull request merged**
