### PR TITLE
db: allow method db.SSTables to return sstable properties

### PR DESCRIPTION
**Pull request by glorv**
~Add an interface to `DB` to get all sst table properties. The interface is like rocksdb's `DB.GetPropertiesOfAllTables`.~

Extend to `DB.SSTables` function to allow return sstable.Properties in each TableInfo

This is useful in case there are  customized `TablePropertyCollector`s in the db, so we can use this API to fetch all the user properties.

### CODE REVIEW

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/963)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @glorv)

___
*[db.go, line 1191 at r1](https://reviewable.io/reviews/cockroachdb/pebble/963#-MJlDe3h8uszvxkIzi_M:-MJlDe3h8uszvxkIzi_N:b-eo3n57) ([raw file](https://github.com/cockroachdb/pebble/blob/9e202fb8089fe0119cdca1d1a87a30bbfc1cdba1/db.go#L1191)):*
> ```Go
> 
> // GetPropertiesOfAllTables return the properties of all tables. The keys in the returned
> // may are the sst file number, the values are the tables' properties.
> ```

It's worth mentioning that this method may be quite slow if the properties need to be read from disk.
___
*[db.go, line 1192 at r1](https://reviewable.io/reviews/cockroachdb/pebble/963#-MJlD32m4sPZjN1OVuYU:-MJlD32m4sPZjN1OVuYV:bd4gqc5) ([raw file](https://github.com/cockroachdb/pebble/blob/9e202fb8089fe0119cdca1d1a87a30bbfc1cdba1/db.go#L1192)):*
> ```Go
> // GetPropertiesOfAllTables return the properties of all tables. The keys in the returned
> // may are the sst file number, the values are the tables' properties.
> func (d *DB) GetPropertiesOfAllTables() (map[FileNum]*sstable.Properties, error) {
> ```

If the desire is to get user properties, I wonder if a more targeted API would be better. Right now, there is no external API for retrieving the `sstable.Properties` from a running `DB` other than opening the sstables manually.

Another thought: perhaps we should extend `manifest.TableInfo` with a `Properties interface{}`and then extend `DB.SSTables` to optionally populate that field.

**Comment by glorv** [comment]
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/963)_ status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @glorv)
> 
> It's worth mentioning that this method may be quite slow if the properties need to be read from disk.

I updated the interface to `GetTablePropertiesInRange` so if we only want to retrieve `sstable`s in range, we can avoid visiting other files since they are likes not in the table cache making this function quite slow.  And I also add a `NOTE` to want this func may be slow if the range is cold.


> If the desire is to get user properties, I wonder if a more targeted API would be better. Right now, there is no external API for retrieving the `sstable.Properties` from a running `DB` other than opening the sstables manually.

In our use case, change this to a more specific func is ok since currently we only depend on the user properties. Not sure if there are other use case that can benefit from this function. 

> Another thought: perhaps we should extend `manifest.TableInfo` with a `Properties interface{}`and then extend `DB.SSTables` to optionally populate that field.

Currnetly the `TableInfo` is mainly created from `FileMetaData`, in this way, we may need to include the `Properties` in `FileMetaData`?

**Review by petermattis — COMMENTED** [review]
> Currnetly the TableInfo is mainly created from FileMetaData, in this way, we may need to include the Properties in FileMetaData?

My thinking was about keeping the API streamlined. `DB.SSTables` already returns info for all sstables. What we'd need to do is to add additional annotation:

```

type SSTablesOption interface{
  sstablesOption()
}

type propertiesOption struct {
}

func (o propertiesOption) sstablesOption() {
}

func WithProperties() SSTablesOption{
  return propertiesOption{}
}

func (d *DB) SSTables(opts ...SSTablesOption) [][]TableInfo {
	// Grab and reference the current readState.
	readState := d.loadReadState()
	defer readState.unref()

	// TODO(peter): This is somewhat expensive, especially on a large
	// database. It might be worthwhile to unify TableInfo and FileMetadata and
	// then we could simply return current.Files. Note that RocksDB is doing
	// something similar to the current code, so perhaps it isn't too bad.
	srcLevels := readState.current.Levels
	var totalTables int
	for i := range srcLevels {
		// TODO(jackson): Use metrics on the LevelMetadata once available
		// rather than Slice().Len().
		totalTables += srcLevels[i].Slice().Len()
	}

	destTables := make([]TableInfo, totalTables)
	destLevels := make([][]TableInfo, len(srcLevels))
	for i := range destLevels {
		iter := srcLevels[i].Iter()
		j := 0
		for m := iter.First(); m != nil; m = iter.Next() {
			destTables[j] = m.TableInfo()
			// TODO: if opts contains the propertiesOption, populate destTables[j].Properties
			j++
		}
		destLevels[i] = destTables[:j]
		destTables = destTables[j:]
	}
	return destLevels
}
```

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/963#-:-MJlVnW-2SnCyAvGQxGg:b-15zpej)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @glorv)

**Comment by glorv** [comment]
@petermattis  Ok, I changed the implementation to include sstable properties in SSTables with opt. But this needs to change the return table with an error. And  directly include `sstable.Properties` in `TableInfo` will cause circular dependency problem, I also change the return type. 

PTAL again, thanks~

**Review by petermattis — COMMENTED** [review]
The approach generally looks good. A few small comments below.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/963#-:-MK0fHvS7YY9l0nFEuz1:b-4ov99d)* status: 0 of 4 files reviewed, 5 unresolved discussions (waiting on @glorv)

___
*[db.go, line 1146 at r3](https://reviewable.io/reviews/cockroachdb/pebble/963#-MK0edhGB2bgg_dywg_S:-MK0edhGB2bgg_dywg_T:b-4eciqo) ([raw file](https://github.com/cockroachdb/pebble/blob/8763675f77cb2d2c4b77e4fe906abfd2b923b87a/db.go#L1146)):*
> ```Go
> 	for i := range srcLevels {
> 		// TODO(jackson): Use metrics on the LevelMetadata once available
> 		// rather than Slice().Len().
> ```

I think you can address this TODO now. I believe this can be `totalTables += srcLevels[i].Len()`.
___
*[db.go, line 1160 at r3](https://reviewable.io/reviews/cockroachdb/pebble/963#-MK0eNZ--BCwqd8FIZuC:-MK0eNZ--BCwqd8FIZuD:b-lpgo1k) ([raw file](https://github.com/cockroachdb/pebble/blob/8763675f77cb2d2c4b77e4fe906abfd2b923b87a/db.go#L1160)):*
> ```Go
> 				p, err := d.tableCache.getTableProperties(m)
> 				if err != nil {
> 					return destLevels, err
> ```

Should this be `return nil, err`? I'm not sure what I'd do with `destLevels` if `err != nil`.
___
*[table_cache.go, line 241 at r3](https://reviewable.io/reviews/cockroachdb/pebble/963#-MK0ezve0JfzSGW8TJFo:-MK0ezve0JfzSGW8TJFp:bnch9sl) ([raw file](https://github.com/cockroachdb/pebble/blob/8763675f77cb2d2c4b77e4fe906abfd2b923b87a/table_cache.go#L241)):*
> ```Go
> func (c *tableCacheShard) getTableProperties(file *fileMetadata) (*sstable.Properties, error) {
> 	// Calling findNode gives us the responsibility of decrementing v's
> 	// refCount. If opening the underlying table resulted in error, then we
> ```

The second and third sentences of this comment do not seem to apply in this context.

**Review by petermattis — COMMENTED** [review]
One more comment: this new functionality needs a test.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/963#-:-MK0fRGbAE-8lrHvYV51:bmbggv0)* status: 0 of 4 files reviewed, 5 unresolved discussions (waiting on @glorv)

**Comment by glorv** [comment]
@petermattis  PTAL again, thanks~

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/963)* status: 0 of 5 files reviewed, 8 unresolved discussions (waiting on @glorv)

___
*[db.go, line 1108 at r4](https://reviewable.io/reviews/cockroachdb/pebble/963#-MKA3TlH1K4zLyEh1DPl:-MKA3TlI0pA8IVx_ZxzB:bfk4rs1) ([raw file](https://github.com/cockroachdb/pebble/blob/f81e15126d7498a34ca5fbf7c35af5f1919252f0/db.go#L1108)):*
> ```Go
> // WithProperties enable return sstable properties in each TableInfo.
> //
> // NOTE: if the and most of the sstable properties need to be read from disk,
> ```

There is something fouled up with the grammar in this sentence.
___
*[db.go, line 1116 at r4](https://reviewable.io/reviews/cockroachdb/pebble/963#-MKA3YAJABWNxhZcHhMq:-MKA3YAJABWNxhZcHhMr:bhg2nmi) ([raw file](https://github.com/cockroachdb/pebble/blob/f81e15126d7498a34ca5fbf7c35af5f1919252f0/db.go#L1116)):*
> ```Go
> }
> 
> // SSTableInfo export  manifest.TableInfo with sstable.Properties
> ```

Nit: there should be only one space between `export` and `manifest`.
___
*[db_test.go, line 1115 at r4](https://reviewable.io/reviews/cockroachdb/pebble/963#-MKA3uaa3nfVQBzVMVge:-MKA3uaa3nfVQBzVMVgf:bte6l9r) ([raw file](https://github.com/cockroachdb/pebble/blob/f81e15126d7498a34ca5fbf7c35af5f1919252f0/db_test.go#L1115)):*
> ```Go
> 	require.NoError(t, err)
> 
> 	require.NoError(t, d.Flush())
> ```

I think the important part of the above are the two `Flush` calls which will create 2 sstables. It would be clearer to simplify this down to the essential:

```
// Create two sstables.
require.NoError(t, d.Set([]byte("hello"), nil, nil))
require.NoError(t, d.Flush())
require.NoError(t, d.Set([]byte("world"), nil, nil))
require.NoError(t, d.Flush())
```

**Comment by glorv** [comment]
@petermattis  PTAL again

**Review by petermattis — COMMENTED** [review]
:lgtm: Thanks for the contribution!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/963#-:-MKKLZHw-aO55pbs1Pb_:b-e8djwd)* status: 0 of 5 files reviewed, 8 unresolved discussions (waiting on @glorv)

**Comment by SWDevAngel** [comment]
@glorv LAST DAY TO ORDER!!!
Hi Glorv. Thank you for contributing to CockroachDB this year. As a token of our appreciation we would like to send you a gift. We tried to reach you via GitHub or on email, but if you didn’t see the message please DM me on our [community Slack](https://cockroa.ch/slack) `@lisa` so I can send you a link to order your gift. (If you don’t want a gift, we also have a charitable contribution choice.) All orders must be in by December 13 (that’s tomorrow!), so please send this asap. :)

**Pull request merged**
