### PR TITLE
*: optimize external iters for single-file, no-rangekey cases

### PR DESCRIPTION
**Pull request by itsbilal**
This change updates NewExternalIter to skip creation of a point-key
mergingIter if there is only one merging iter level and there are
no range dels. It also skips creation of a simpleLevelIter if there
is only one file that would be contained in it. And it skips
creation of a rangeKey interleaving iterator if there are no range
keys. These optimizations avoid overhead that's only necessary for
multi-file, range-key cases.

Together, these optimizations produce a ~45% performance gain
for forward iteration:

```
name                                                   old time/op  new time/op  delta
SSTIterator/keys=10000/variant=pebble/verify=false-10  1.22ms ± 0%  0.67ms ± 0%  -45.27%  (p=0.001 n=5+10)
```

### CODE REVIEW

**Comment by itsbilal** [comment]
The same benchmark before this change (old = legacy iter, new = new iter before this change):

```
name                                                   old time/op  new time/op  delta
SSTIterator/keys=10000/variant=pebble/verify=false-10   660µs ± 1%  1224µs ± 0%  +85.54%  (p=0.008 n=5+5)
```

Vs after this change (old is still the legacy iterator)
```
name                                                   old time/op  new time/op  delta
SSTIterator/keys=10000/variant=pebble/verify=false-10   660µs ± 1%   990µs ± 0%  +50.15%  (p=0.008 n=5+5)
```

There's still a noticeable performance overhead and while we'll not be able to get to 0 because we need the toplevel `Iterator` for figuring out range key presence/overlaps etc, there are possibly other things I can keep digging into after this change.

**Review by itsbilal — COMMENTED** [review]
TFTR! Also optimized away the `interleavedIter` when there are no range keys for sure.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1925#-:-NAB7R_P42F6IBqWyf6K:b-lygeq)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @jbowens)

___
*[`external_iterator.go` line 230 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1925#-NAAI63m-JapNwz4nbsj:-NAB41AL3TRZsRP8kLTD:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/d661637dfdb842446a17c92de04c50a57a44ec04/external_iterator.go#L230)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

i think it'd read a little clearer to outdent this block, eg
```
if len(combinedIters) == 1 {
    /* ... */
} else if len(combinedIters) > 1 {
   /* ... */
}
```
</blockquote></details>

Done.
___
*[`external_iterator.go` line 249 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1925#-NAAIn5n4N2CH3bntLD3:-NAB1UJJ-1x_cTlPzR04:b2zgl12) ([raw file](https://github.com/cockroachdb/pebble/blob/d661637dfdb842446a17c92de04c50a57a44ec04/external_iterator.go#L249)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

this pointIter is still a `simpleLevelIter` which adds some overhead, right? Since the case we care about right now is the single sstable case, maybe we should special case the case where `len(readers) == 1 && len(readers[0]) == 1` up above. this would probably be easier to special case if we factor point iterator construction into a separate method.
</blockquote></details>

Not necessarily - if we elided the `simpleLevelIter` because there was only one iter under it, we'd be threading through the interleaving iterator directly here.
___
*[`external_iterator.go` line 256 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1925#-NAAIXg08QcrqmjeWGor:-NAB6ROV8pSZviVEmquz:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/d661637dfdb842446a17c92de04c50a57a44ec04/external_iterator.go#L256)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

maybe it's time to factor point iterator construction out into its own method so we can early return out with an `errorIter` if we hit an error, or if we encouter a single-iter fast path.
</blockquote></details>

Done.
___
*[`iterator.go` line 609 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1925#-NA9qW9j5gU99DSGOUCL:-NAB6WQK9R2pjKxebswm:byqw4rx) ([raw file](https://github.com/cockroachdb/pebble/blob/d661637dfdb842446a17c92de04c50a57a44ec04/iterator.go#L609)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

how much of the performance improvement is attributable to avoiding this key comparison versus omitting the merging iterator? i’m a little wary of special casing external iterator optimizations within `*pebble.Iterator`. I expect the key copy into `keyBuf` to be more substantial than this `i.equal`, but I'd also rather not complicate the `*pebble.Iterator` with preventing it if we can avoid it.
</blockquote></details>

Good point. Let me get a concrete # on how expensive this copy is; I remember the overhead in nextUserKey showing up pretty significantly so this was the most obvious place to optimize. I also removed the key copy into `keyBuf` in this method as its' unnecessary when `allowDuplicates` is true.

**Review by itsbilal — COMMENTED** [review]
Added another optimization around skipping the interleaving iter and the `iterator.rangeKey` alloc struct (which speeds up some conditionals inside `Iterator`), and now we're at a more significant performance difference compared to `master`:

```
name                                                   old time/op  new time/op  delta
SSTIterator/keys=10000/variant=pebble/verify=false-10  1.22ms ± 0%  0.67ms ± 0%  -45.27%  (p=0.001 n=5+10)
```

Compared to pre-range key support we're now at a <20% regression:

```
name                                                   old time/op  new time/op  delta
SSTIterator/keys=10000/variant=pebble/verify=false-10   568µs ± 0%   671µs ± 0%  +18.23%  (p=0.000 n=9+9)
```

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1925#-:-NABMCXw8mZpl159yT8r:b-3wtysb)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @jbowens)

___
*[`iterator.go` line 609 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1925#-NA9qW9j5gU99DSGOUCL:-NABMMA_8-SbwGuUtDoe:b-98c53) ([raw file](https://github.com/cockroachdb/pebble/blob/d661637dfdb842446a17c92de04c50a57a44ec04/iterator.go#L609)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Good point. Let me get a concrete # on how expensive this copy is; I remember the overhead in nextUserKey showing up pretty significantly so this was the most obvious place to optimize. I also removed the key copy into `keyBuf` in this method as its' unnecessary when `allowDuplicates` is true.
</blockquote></details>

There was no statistically significant difference in dropping `allowDuplicates` and this key comparison, so I undid this optimization.

**Review by sumeerbhola — COMMENTED** [review]
> ExternalIterAllowDuplicates, that skips duplicate checking and
> deduplication in the outer Iterator if the caller can guarantee that
> the files passed in will at most contain one version for each user
> key.

what use cases will be able to make this guarantee?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1925#-:-NABDL-LDz-Ct44uOkhd:b-o6i6g2)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @jbowens and @sumeerbhola)

___
*[`iterator.go` line 609 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1925#-NA9qW9j5gU99DSGOUCL:-NABPRva5poDW_rZKBhp:b-82kujq) ([raw file](https://github.com/cockroachdb/pebble/blob/d661637dfdb842446a17c92de04c50a57a44ec04/iterator.go#L609)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

There was no statistically significant difference in dropping `allowDuplicates` and this key comparison, so I undid this optimization.
</blockquote></details>

So we don't even need to avoid that key copy to get performance parity with the old sst iterators?

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1925)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @itsbilal, @jbowens, and @sumeerbhola)

___
*[`external_iterator.go` line 299 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1925#-NAFBKGE-mLdhH9LASAY:-NAFBKGF8xcnEqzDK80E:bufytd5) ([raw file](https://github.com/cockroachdb/pebble/blob/477b7e7aa635097a1efc094663dc1b3a972808dc/external_iterator.go#L299)):*
> ```Go
> 			*it.rangeKey = iteratorRangeKeyState{buf: it.rangeKey.buf}
> 			iterRangeKeyStateAllocPool.Put(it.rangeKey)
> 			it.rangeKey = nil
> ```

can we avoid ever retrieving the `iteratorRangeKeyState` in this case? eg, only when we're about to add a level call a helper like `maybeInitRangeKeys`. In the ordinary MVCC benchmarks zeroing and returning the iteratorRangeKeyState to the pool had a non-negligible performance cost.

**Review by itsbilal — COMMENTED** [review]
> what use cases will be able to make this guarantee?

Backup restores would definitely be able to make that guarantee. Either way I dropped that optimization.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1925#-:-NAFaMto8hnKLzloxAkf:b-90q2x3)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @jbowens and @sumeerbhola)

___
*[`external_iterator.go` line 299 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1925#-NAFBKGE-mLdhH9LASAY:-NAFsh_A1QZJBpyI6sXU:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/477b7e7aa635097a1efc094663dc1b3a972808dc/external_iterator.go#L299)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

can we avoid ever retrieving the `iteratorRangeKeyState` in this case? eg, only when we're about to add a level call a helper like `maybeInitRangeKeys`. In the ordinary MVCC benchmarks zeroing and returning the iteratorRangeKeyState to the pool had a non-negligible performance cost.
</blockquote></details>

Done.
___
*[`iterator.go` line 609 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1925#-NA9qW9j5gU99DSGOUCL:-NAFsiTM795SdMMjLTq0:bxscwjp) ([raw file](https://github.com/cockroachdb/pebble/blob/d661637dfdb842446a17c92de04c50a57a44ec04/iterator.go#L609)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

So we don't even need to avoid that key copy to get performance parity with the old sst iterators?
</blockquote></details>

We aren't at parity, but we're getting close enough without this that we can defer the more intricate optimizations.

**Review by jbowens — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1925#-:-NAKD2J60n134pJLrFMm:b593w57)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @jbowens and @sumeerbhola)

**Comment by itsbilal** [comment]
TFTR!

**Pull request merged**
