### PR TITLE
internal/cache: add additional asserts, debugging context

### PR DESCRIPTION
**Pull request by jbowens**
**internal/cache: add hot, cold, test entry counts**

Add hot, cold and test counts to block cache shard. Use `coldCount` to
assert that `coldSize` matches expectations.

This is intended to help gain more insight out of any future
reproductions of the infinite loop encountered in
cockroachdb/cockroach#70154

**internal/cache: include sizeCold in runHandCold stack traces**

Add sizeCold as a parameter to runHandCold so that stack traces from any
future cockroachdb/cockroach#70154 reproductions will include it.

These are @petermattis's ideas from https://github.com/cockroachdb/cockroach/issues/70154#issuecomment-923291288.

### CODE REVIEW

**Review by petermattis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1284#-:-Mk8vcLp9NWpyoIjmvqV:bnfp4nl)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @bananabrick and @jbowens)

___
*[-- commits, line 5 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1284#-Mk8u4XD3KH_wglPL40G):*
Nit: `s/coldSize/sizeCold/g`
___
*[internal/cache/clockpro.go, line 219 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1284#-Mk8uGYW97cKsgOnb3qX:-Mk8uGYW97cKsgOnb3qY:b-x30p8u) ([raw file](https://github.com/cockroachdb/pebble/blob/719870736d4644afcc656e0f32e03de081c75c49/internal/cache/clockpro.go#L219)):*
> ```Go
> 		panic(fmt.Sprintf("pebble: mismatch %d test size, %d test count", c.sizeTest, c.countTest))
> 	}
> 	if c.countHot < 0 || c.countCold < 0 || c.countTest < 0 {
> ```

Should we also panic if `size{Hot,Cold,Test} < 0`?
___
*[internal/cache/clockpro.go, line 412 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1284#-Mk8v-RK9K2F0vGbaO6F:-Mk8v-RK9K2F0vGbaO6G:b8lzzy9) ([raw file](https://github.com/cockroachdb/pebble/blob/719870736d4644afcc656e0f32e03de081c75c49/internal/cache/clockpro.go#L412)):*
> ```Go
> 		// NB: c.hand{Hot,Cold,Test} are pointers into a single linked list. We
> 		// only have to traverse one of them to check all of them.
> 		for t := c.handHot.next(); t != c.handHot; t = t.next() {
> ```

Btw, in my explorations yesterday I noticed that this loop is flawed and doesn't perform an iteration for `c.handHot`. I think the for-loop needs to look something like:

```
for t := c.handHot.next(); ; t = t.next() {
  ...
  if t == c.handHot {
    break
  }
}
```
___
*[internal/cache/clockpro.go, line 418 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1284#-Mk8unpM8qZZrOjcazpy:-Mk8unpM8qZZrOjcazpz:b-jv6833) ([raw file](https://github.com/cockroachdb/pebble/blob/719870736d4644afcc656e0f32e03de081c75c49/internal/cache/clockpro.go#L418)):*
> ```Go
> 				os.Exit(1)
> 			}
> 		}
> ```

I wonder if we should extend `metaCheck` to recompute `{size,count}{Hot,Cold,Test}` from the entry list and verify them against the `shard.{size,count}{Hot,Cold,Test}` fields. This would only be done when invariants are enabled.
___
*[internal/cache/clockpro.go, line 445 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1284#-Mk8uTlo1gG3KrpoWSmS:-Mk8uTlo1gG3KrpoWSmT:b-51pfmg) ([raw file](https://github.com/cockroachdb/pebble/blob/719870736d4644afcc656e0f32e03de081c75c49/internal/cache/clockpro.go#L445)):*
> ```Go
> }
> 
> func (c *shard) runHandCold(sizeColdDebug int64) {
> ```

If the infinite loop re-occurs, I'd want to know what `countCold` is as well. Let's add it as a second parameter.

**Review by bananabrick — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1284)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @bananabrick, @jbowens, and @petermattis)

___
*[internal/cache/clockpro.go, line 134 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1284#-Mk8xL8F3y6zshqzgCXw:-Mk8xL8F3y6zshqzgCXx:b-1i20p5) ([raw file](https://github.com/cockroachdb/pebble/blob/81c4b887c46dc8ba61aa9f01dc5f836541bfac50/internal/cache/clockpro.go#L134)):*
> ```Go
> }
> 
> func (c *shard) Set(id uint64, fileNum base.FileNum, offset uint64, value *Value) Handle {
> ```

If we want, we can add a panic if `Set` or `metaAdd` is called after `Free`. Context: https://github.com/cockroachdb/cockroach/issues/70154#issuecomment-924340646

**Review by bananabrick — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1284)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @bananabrick, @jbowens, and @petermattis)

___
*[internal/cache/clockpro.go, line 286 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1284#-Mk91EG73Zg0anHT5CEL:-Mk91EG73Zg0anHT5CEM:b-e8o6mn) ([raw file](https://github.com/cockroachdb/pebble/blob/81c4b887c46dc8ba61aa9f01dc5f836541bfac50/internal/cache/clockpro.go#L286)):*
> ```Go
> }
> 
> func (c *shard) Reserve(n int) {
> ```

Also due to this: https://github.com/cockroachdb/cockroach/issues/70154#issuecomment-924340646, if you think we should, maybe a log entry if reserve is called after `shard.Free` could be helpful.

We can add `handHot, handCold, handTest, sizeCold` in the log entry.


This won't pollute the logs because `shard.Free` will probably only be called when the DB is shutting down.

**Review by bananabrick — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1284)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @bananabrick, @jbowens, and @petermattis)

___
*[internal/cache/clockpro.go, line 286 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1284#-Mk91EG73Zg0anHT5CEL:-Mk92-DUE1gvbMrNNDl6:b7jv7q5) ([raw file](https://github.com/cockroachdb/pebble/blob/81c4b887c46dc8ba61aa9f01dc5f836541bfac50/internal/cache/clockpro.go#L286)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

Also due to this: https://github.com/cockroachdb/cockroach/issues/70154#issuecomment-924340646, if you think we should, maybe a log entry if reserve is called after `shard.Free` could be helpful.

We can add `handHot, handCold, handTest, sizeCold` in the log entry.


This won't pollute the logs because `shard.Free` will probably only be called when the DB is shutting down.
</blockquote></details>

This can also be a panic. I think the condition should be, `sizeCold > 0, `shard.Free` has been called, `handHot != nil`, then panic.

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1284)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @bananabrick, @jbowens, and @petermattis)

___
*[internal/cache/clockpro.go, line 134 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1284#-Mk8xL8F3y6zshqzgCXw:-MkEOlOZ0E-UxeYldKtl:b-dg7mik) ([raw file](https://github.com/cockroachdb/pebble/blob/81c4b887c46dc8ba61aa9f01dc5f836541bfac50/internal/cache/clockpro.go#L134)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

If we want, we can add a panic if `Set` or `metaAdd` is called after `Free`. Context: https://github.com/cockroachdb/cockroach/issues/70154#issuecomment-924340646
</blockquote></details>

I might followup with something in this vein. I went down a rabbit hole with this one, discovering that many pkg/storage cockroachdb unit tests leak pebble iterators (cockroachdb/cockroach#70577).
___
*[internal/cache/clockpro.go, line 219 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1284#-Mk8uGYW97cKsgOnb3qX:-Mk9TWWQ-jVSoObI9WZ5:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/719870736d4644afcc656e0f32e03de081c75c49/internal/cache/clockpro.go#L219)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Should we also panic if `size{Hot,Cold,Test} < 0`?
</blockquote></details>

Done.
___
*[internal/cache/clockpro.go, line 412 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1284#-Mk8v-RK9K2F0vGbaO6F:-MkELpTaDVzNGu5MkGXa:b-oz8o77) ([raw file](https://github.com/cockroachdb/pebble/blob/719870736d4644afcc656e0f32e03de081c75c49/internal/cache/clockpro.go#L412)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Btw, in my explorations yesterday I noticed that this loop is flawed and doesn't perform an iteration for `c.handHot`. I think the for-loop needs to look something like:

```
for t := c.handHot.next(); ; t = t.next() {
  ...
  if t == c.handHot {
    break
  }
}
```
</blockquote></details>

Good catch
___
*[internal/cache/clockpro.go, line 418 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1284#-Mk8unpM8qZZrOjcazpy:-MkEOe9v1wOB4CGT_Scp:b-21w2pp) ([raw file](https://github.com/cockroachdb/pebble/blob/719870736d4644afcc656e0f32e03de081c75c49/internal/cache/clockpro.go#L418)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I wonder if we should extend `metaCheck` to recompute `{size,count}{Hot,Cold,Test}` from the entry list and verify them against the `shard.{size,count}{Hot,Cold,Test}` fields. This would only be done when invariants are enabled.
</blockquote></details>

good idea, done.
___
*[internal/cache/clockpro.go, line 445 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1284#-Mk8uTlo1gG3KrpoWSmS:-Mk9V4j54zmCZfvvVebw:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/719870736d4644afcc656e0f32e03de081c75c49/internal/cache/clockpro.go#L445)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

If the infinite loop re-occurs, I'd want to know what `countCold` is as well. Let's add it as a second parameter.
</blockquote></details>

Done.

**Review by petermattis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1284#-:-MkFGop_6qxd6z3b7gT9:bnfp4nl)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @bananabrick, @jbowens, and @petermattis)

**Comment by jbowens** [comment]
TFTRs!

**Pull request merged**
