### PR TITLE
cut compaction outputs at grandparent boundaries

### LINKED ISSUE #167: db: sstable output size during compactions should consider range tombstones
See https://github.com/facebook/rocksdb/issues/3977 for the similar issue in RocksDB. The TLDR is the the sstable output size does not truncate range tombstones. This can result in an sstable covering an excessively large number of sstables in the level below, resulting in an excessively large compaction. There is a [comment](https://github.com/petermattis/pebble/blob/master/compaction.go#L994-L995) in the code about this:

		// TODO(peter,rangedel): Need to incorporate the range tombstones in the
		// shouldStopBefore decision.

I'm not clear on exactly how I'd want to incorporate range tombstones in the `shouldStopBefore` decision. See the RocksDB issues for a problematic scenario. It is possible that we need to truncate and split range tombstones to avoid creating sstables which overlap too much in the grandparent level.

### PR DESCRIPTION
**Pull request by ajkr**
Previously range tombstones could cause output files that would later
undergo excessively large compactions due to overlap with the
grandparent level. This happened because only point keys were considered
for cutting output files according to grandparent overlap. Thus if a
range tombstone extended over a region devoid of point keys, compaction
would never split files within that region.

To fix this we now split output files at grandparent boundaries
regardless of the presence of point keys. That means a region covered by
a range tombstone and devoid of point keys can be split at grandparent
boundaries if needed to prevent future huge compactions.

Fixes #167.

### CODE REVIEW

**Comment by petermattis** [comment]
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/382)

**Comment by ajkr** [comment]
@petermattis you mentioned in our 1:1 that some problematic case was discovered in this PR, but I can't seem to think of what it is. Do you mind elaborating?

**Comment by petermattis** [comment]
> @petermattis you mentioned in our 1:1 that some problematic case was discovered in this PR, but I can't seem to think of what it is. Do you mind elaborating?

Must have been some sort of miscommunication. I don't recall saying that and don't recall there being any problematic case with this PR.

**Comment by ajkr** [comment]
> Must have been some sort of miscommunication. I don't recall saying that and don't recall there being any problematic case with this PR.

Got it, thanks for the clarification.

**Pull request merged**
