### PR TITLE
db: implement min-overlapping ratio heuristic

### PR DESCRIPTION
**Pull request by jbowens**
Implement a variant of RocksDB's min-overlapping ratio compaction heuristic.

### CODE REVIEW

**Comment by petermattis** [comment]
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/707)

**Comment by jbowens** [comment]
Here are some numbers collected via a handful of `pebble bench compact` workloads:

```
                                master           75b3493e
replicate-rebalance-3to5
  test time                     20.72m             16.20m  ( -21.81%)
  read amp                           4                  4       -
  write amp                       3.50               3.36  (  -4.00%)
  space amp                       1.24               1.08  ( -12.90%)
  avg db size                    8.1 G              7.1 G  ( -12.35%)

tpccbench
  test time                     47.63m             50.09m  (  +5.16%)
  read amp                           6                  6       -
  write amp                       2.08               2.04  (  -1.92%)
  space amp                       1.07               1.07       -
  avg db size                     39 G               39 G       -

clearrange
  test time                      6.84m              7.01m  (  +2.49%)
  read amp                           4                  2  (-100.00%)
  write amp                       1.06               1.06       -
  space amp                   55961.61               1.11  (- 99.99%)
  avg db size                     32 G               32 G       -

tpcc-headroom-n4cpu16
  test time                     62.44m            71.60m  ( +14.67%)
  read amp                           6                 6       -
  write amp                       2.61              2.73  (  +4.60%)
  space amp                       1.09              1.09       -
  avg db size                     41 G              41 G       -

composite*
  test time                     20.72m            16.73m  (- 19.26%)
  read amp                           4                 3  (- 25.00%)
  write amp                       5.96              5.40  (-  9.40%)
  space amp                      33.68              1.96  (- 94.18%)
  avg db size                    2.8 G             2.8 G       -

* composite was simulataneous tpcc, bank, queue, movr and ledger
  workoads run against the same cluster, with the databases
  dropped at varying times to create range tombstones.
```

The tpcc workloads suffer some on the new heuristic. It makes sense that the workloads with range deletions throughout would fair better, since freeing space earlier can save you from performing unnecessary compactions. I'm a little surprised at the tpcc numbers though. An earlier prototype of just the min-overlapping ratio change saw a marked decrease in both time and write amplification on a tpcc workload. I'm going to experiment a little more.

**Comment by jbowens** [comment]
roachtest `tpccbench/nodes=3/cpu=4` using this branch for pebble got 736 max warehouses

**Comment by jbowens** [comment]
TFTR!

**Pull request merged**
