### PR TITLE
crl-release-23.2: db: ensure Metrics.WAL.BytesWritten is nondecreasing

### PR DESCRIPTION
**Pull request by jbowens**
23.2 backport of #3555

### CODE REVIEW

**Review by dhartunian — COMMENTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3569)* status: 2 of 6 files reviewed, 1 unresolved discussion (waiting on @jbowens and @RaduBerinde)

___
*[`testdata/metrics` line 487 at r2](https://reviewable.io/reviews/cockroachdb/pebble/3569#-NxDRyLJDOsdPC_dCjRi:-NxDRyLJDOsdPC_dCjRj:b4bts5t) ([raw file](https://github.com/cockroachdb/pebble/blob/15346844e0ce410694c4c81407e93dd264f59135/testdata/metrics#L487)):*
> ```
> unknown command: <<<<<<<
> 
> >>>>>>> 9027c15f (db: update flushableEntry.logSize during flushable ingest)
> ```

I think you have merge conflicts that need resolution

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3569)* status: 2 of 6 files reviewed, 1 unresolved discussion (waiting on @dhartunian and @RaduBerinde)

___
*[`testdata/metrics` line 487 at r2](https://reviewable.io/reviews/cockroachdb/pebble/3569#-NxDRyLJDOsdPC_dCjRi:-NxDbK787ZTHnxhz2iOU:b9pojyc) ([raw file](https://github.com/cockroachdb/pebble/blob/15346844e0ce410694c4c81407e93dd264f59135/testdata/metrics#L487)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

I think you have merge conflicts that need resolution
</blockquote></details>

embarassing, thanks

**Comment by jbowens** [comment]
bumping

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3569#-:-NxU6959-dFlc3u0F1-F:bnfp4nl)* status: 2 of 6 files reviewed, 1 unresolved discussion (waiting on @dhartunian)

___
*[`testdata/metrics` line 487 at r2](https://reviewable.io/reviews/cockroachdb/pebble/3569#-NxDRyLJDOsdPC_dCjRi:-NxU65QrAmc05yLvz-U2:bj66in1) ([raw file](https://github.com/cockroachdb/pebble/blob/15346844e0ce410694c4c81407e93dd264f59135/testdata/metrics#L487)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

embarassing, thanks
</blockquote></details>

[nit] These are fixed in the subsequent commit but not this one

**Comment by jbowens** [comment]
TFTR!

**Pull request merged**
