### PR TITLE
db: more invariant checking for InternalKeyKind in compactionIter

### PR DESCRIPTION
**Pull request by sumeerbhola**
Informs https://github.com/cockroachdb/cockroach/issues/114421

### CODE REVIEW

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3089)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @jbowens)

___
*[`compaction_iter.go` line 605 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3089#-NjhqxZg6DsWr6cSdWCH:-NjhqxZg6DsWr6cSdWCI:b-wpm46p) ([raw file](https://github.com/cockroachdb/pebble/blob/2b849638632c7e91a05c0d0d61257f77aaa1da94/compaction_iter.go#L605)):*
> ```Go
> //
> // TODO(sumeer): skipInStripe() can return with i.err != nil and i.iterKey set
> // to nil, but callers don't look at i.err.
> ```

I believe the call to `i.iterNext()` in `nextInStripeHelper()` could cause this even prior to this PR.

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3089)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @jbowens)

___
*[`compaction_iter.go` line 605 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3089#-NjhqxZg6DsWr6cSdWCH:-Nji66Ju0GbcmIWbQWZu:b-tv8fy2) ([raw file](https://github.com/cockroachdb/pebble/blob/2b849638632c7e91a05c0d0d61257f77aaa1da94/compaction_iter.go#L605)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I believe the call to `i.iterNext()` in `nextInStripeHelper()` could cause this even prior to this PR.
</blockquote></details>

I've removed this TODO after auditing the callers, and adding some comments.

**Review by jbowens — APPROVED** [review]
:lgtm_strong: 

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3089#-:-NjiCmSc-OLQvZykkCQw:b-yncq6h)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @sumeerbhola)

___
*[`compaction_iter.go` line 622 at r2](https://reviewable.io/reviews/cockroachdb/pebble/3089#-NjiCB4_9sOlBwaDD-TS:-NjiCB4_9sOlBwaDD-TT:b6fbcj0) ([raw file](https://github.com/cockroachdb/pebble/blob/72a0b419362865176d2b23e7b1690d837fdc2659/compaction_iter.go#L622)):*
> ```Go
> func (i *compactionIter) iterNext() bool {
> 	var iterValue LazyValue
> 	i.iterKey, iterValue = i.iter.Next()
> ```

Whose responsibility is it to check `i.iter.Error()` if `i.iterKey` is nil after this `Next`? Some of our iterators implement `Error()` with `firstError(i.err, i.iter.Error())`, but `compactionIter` implements `Error()` by directly returning `i.err`.

**Comment by itsbilal** [comment]
This will also need to be backported to 23.2 right?

**Review by sumeerbhola — COMMENTED** [review]
> This will also need to be backported to 23.2 right?

Yep

TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3089#-:-NjiZmV74dMciFdnQ5K9:b2i769v)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @jbowens)

___
*[`compaction_iter.go` line 622 at r2](https://reviewable.io/reviews/cockroachdb/pebble/3089#-NjiCB4_9sOlBwaDD-TS:-NjiZ5GSC1Kd-Cf-ooOj:b-ycrb55) ([raw file](https://github.com/cockroachdb/pebble/blob/72a0b419362865176d2b23e7b1690d837fdc2659/compaction_iter.go#L622)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

Whose responsibility is it to check `i.iter.Error()` if `i.iterKey` is nil after this `Next`? Some of our iterators implement `Error()` with `firstError(i.err, i.iter.Error())`, but `compactionIter` implements `Error()` by directly returning `i.err`.
</blockquote></details>

Good question.
(just repeating in-person discussion) we check in `compactionIter.Close()` which will get called because the iter is exhausted. I was going to add more defensive code, but noticed that `compaction.go` never calls `compactionIter.Error()` and relies on exhaustion.

**Pull request merged**
