### PR TITLE
cmd/pebble: add bench replay command

### PR DESCRIPTION
**Pull request by jbowens**
Add a `pebble bench replay` command for replaying workloads for
compaction benchmarking.

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2161)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @jbowens and @nicktrav)

___
*[`cmd/pebble/replay.go` line 1 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2161#-NLRrSbn0babcbOUQkRg:-NLRrSbn0babcbOUQkRh:b-n41o25) ([raw file](https://github.com/cockroachdb/pebble/blob/693f5d5df6a17edf33847f1b7379b63382edcbad/cmd/pebble/replay.go#L1)):*
> ```Go
> // Copyright 2022 The LevelDB-Go and Pebble Authors. All rights reserved. Use
> ```

[nit] 2023 :fireworks: 
___
*[`cmd/pebble/replay.go` line 50 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2161#-NLRsXx4-FBaQo2XPBQ3:-NLRsXx4-FBaQo2XPBQ4:bnjtsiz) ([raw file](https://github.com/cockroachdb/pebble/blob/693f5d5df6a17edf33847f1b7379b63382edcbad/cmd/pebble/replay.go#L50)):*
> ```Go
> 		&c.streamLogs, "stream-logs", c.streamLogs, "stream the Pebble logs to stdout during replay")
> 	cmd.Flags().BoolVar(
> 		&c.useCheckpoint, "use-checkpoint", c.useCheckpoint, "initialize the run directory with the workload's accompanying checkpoint, if it exists")
> ```

The "if it exists" semantics are error prone (if there's a typo or some other mistake, it can go unnoticed). If it's necessary, consider using another flag (e.g. `--ignore-missing-checkpoint`).
___
*[`cmd/pebble/replay.go` line 143 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2161#-NLRsJO0-kJ5vw0zkdOX:-NLRsJO0-kJ5vw0zkdOY:biwdsye) ([raw file](https://github.com/cockroachdb/pebble/blob/693f5d5df6a17edf33847f1b7379b63382edcbad/cmd/pebble/replay.go#L143)):*
> ```Go
> 	// the provided checkpoint.
> 	// TODO(jackson): Allow overriding the OPTIONS.
> 	ls, err := r.WorkloadFS.List(r.WorkloadFS.PathJoin(r.WorkloadPath, "checkpoint"))
> ```

[nit] isn't it cleaner to use `useCheckpoint` (we can set it to `false` in the "skipping" path of `initRunDir`).
___
*[`cmd/pebble/replay.go` line 212 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2161#-NLRw7_70guuK3qAz0i8:-NLRw7_70guuK3qAz0i9:b-7uf8yk) ([raw file](https://github.com/cockroachdb/pebble/blob/693f5d5df6a17edf33847f1b7379b63382edcbad/cmd/pebble/replay.go#L212)):*
> ```Go
> 		merger := new(pebble.Merger)
> 		merger.Merge = func(key, value []byte) (pebble.ValueMerger, error) {
> 			return &overwriteValueMerger{}, nil
> ```

Don't we need to initialize `value` in the merger?

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2161#-:-NLXPsbZ9rj2fhp92pHh:bnfp4nl)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @jbowens and @nicktrav)

___
*[`cmd/pebble/replay.go` line 212 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2161#-NLRw7_70guuK3qAz0i8:-NLXPoFr8eg-Oven7bp2:bc7a6yv) ([raw file](https://github.com/cockroachdb/pebble/blob/693f5d5df6a17edf33847f1b7379b63382edcbad/cmd/pebble/replay.go#L212)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

Good catch, done.
</blockquote></details>

[nit] Consider moving to a `newOverwriteValueMerger` constructor.
___
*[`cmd/pebble/replay.go` line 176 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2161#-NLXPTydCMsns3hTQNo6:-NLXPTydCMsns3hTQNo7:bt230ln) ([raw file](https://github.com/cockroachdb/pebble/blob/f8a480cc839ed9eb3834db4186abd27eefd634d2/cmd/pebble/replay.go#L176)):*
> ```Go
> 	// manifests and pull the comparer out of them.
> 	//
> 	// r.Opts.Comparer should be non-nil as long as !useCheckpoint.
> ```

[nit] `should be non-nil unless ignoreCheckpoint is set`.

**Review by jbowens — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2161#-:-NLaxZKb1g9dMuNuXCek:b-814g8k)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @nicktrav)

___
*[`cmd/pebble/replay.go` line 176 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2161#-NLXPTydCMsns3hTQNo6:-NLaxLaN07ybEAq15AxF:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/f8a480cc839ed9eb3834db4186abd27eefd634d2/cmd/pebble/replay.go#L176)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] `should be non-nil unless ignoreCheckpoint is set`.
</blockquote></details>

Done.

**Review by nicktrav — APPROVED** [review]
Nice!  :lgtm:

> Reviewed 3 of 4 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2161#-:-NLb4H6l32RW7AiYHitZ:b-ypbbbp)* status: all files reviewed, 2 unresolved discussions (waiting on @jbowens)

___
*[`cmd/pebble/replay.go` line 36 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2161#-NLb3izO8VmIHrn3HhAZ:-NLb3izO8VmIHrn3HhA_:btyzqy8) ([raw file](https://github.com/cockroachdb/pebble/blob/b8243a1c1bf5f5f86f26ced6929437e9a9a47a16/cmd/pebble/replay.go#L36)):*
> ```Go
> 		Use:   "replay <workload>",
> 		Short: "run the provided captured write workload",
> 		Long:  ``,
> ```

nit: remove? Or fill out?

**Pull request merged**
