### PR TITLE
sstable: add range key support to BlockIntervalCollector

### PR DESCRIPTION
**Pull request by nicktrav**
Currently, the `sstable.BlockIntervalCollector` exists as a helper
struct to which an implementation of
`sstable.DataBlockIntervalCollector` is passed. The latter contains the
user-defined logic for converting a key and value in an associated
interval that can be maintained.

The `BlockIntervalCollector` struct handles the logic required to
implement `sstable.BlockPropertyCollector`, encoding the interval as a
property when the data block is completed, and maintaining index-block-
and table-level intervals.

Update `sstable.Writer` to pass through range keys to each block
property collector as they are added to the writer.

As range and point keys can be thought of as existing in separate
keyspaces within the same LSM, range keys only contribute to table level
intervals (unioned with the point key interval), rather than block- and
index-level intervals.

Another way to rationalize this decision is to consider that range keys
are contained in a single, dedicated block in the SSTable, while the
point keys can span multiple blocks and have an associated index entry
into which the properties for the specific block are encoded. Block
level filtering applies to point keys only, whereas table-level
filtering takes the union of the point and range key intervals for the
table.

One downside of taking the union of the range and point keys for the
table level interval is an increased rate of false positives when
filtering tables based on an interval and the range key interval is
wider than the point key interval.

This change alters the `NewBlockIntervalCollector` function to take in
two `DataBlockIntervalCollector`s, one for point and range keys. This is
required to track the intervals separately within the
`BlockIntervalCollector`. The caller has the flexibility of passing in
`nil` for one (or both) of the collectors, in which case either point or
range keys (or both) will be ignored by the collector. This can be used,
for example, to construct a collectors that apply exclusively to either
point or range keys.

### CODE REVIEW

**Comment by nicktrav** [comment]
This is an alternative implementation to the one in #1426 which feels both simpler and more flexible.

I made a simplifying assumption that range keys should never affect point key block properties. Put another way, I couldn't think of a case where one would want to a collector that encodes range key properties into a data block, given that the range keys will never appear in the data blocks (they have a single, dedicated block).

There's a minor API change that requires callers to specify a collector for both point and range keys separately. Given implementations tend to maintain two uints for upper / lower bounds, there's minimal cost to doing this.

The nice thing is that this implementation gives the flexibility to construct a collector that:
- only applies to point keys (passing a `nil` range key collector)
- only applies to range keys (passing a `nil` point key collector)
- applies to both point and range keys

For the above cases, this implementation seems strictly better than the alternative of constructing two separate collectors for point and range keys, which would double up on the space used required to store the collector name and encode up to two properties instead of just the one.

**Review by jbowens — COMMENTED** [review]
> One downside of taking the union of the range and point keys for the
> table level interval is an increased rate of false positives when
> filtering tables based on an interval and the range key interval is
> wider than the point key interval.

In CockroachDB, the practical concern here is that you may have a broad swath of old data in the span `[a, z)` at timestamps `<10`. Then you write a MVCCDeleteRange range key `[a,z)@100` and its compacted into the same table(s) as the point keys. A time-bound iterator with a read timestamp ≤ `@100` will construct a point iterator `levelIter` that still needs to visit every table, even though there's zero points within the interval. [The rangekey `levelIter` for the same time-bound iterator does need to visit every table in order to read the rangekey].

It's not a huge deal, because the index-level block properties will still allow us to skip over all the point blocks. But broadly if we stick with a split iterator implementation such that point and range key iterators belonging to the same `pebble.Iterator` may be looking at different tables, I wonder if we should lean towards recording separate properties. [I think we should also do this with the `FileMetadata.{Smallest,Largest}`]

> Reviewed 1 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1452#-:-MthkkVLCs-w-MDl3Xmq:brvursw)* status: 1 of 5 files reviewed, 3 unresolved discussions (waiting on @nicktrav and @sumeerbhola)

___
*[sstable/block_property.go, line 132 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1452#-MthdIql90Sr9MkSs1Ru:-MthdIql90Sr9MkSs1Rv:b-ikhzfo) ([raw file](https://github.com/cockroachdb/pebble/blob/445976e459f2f9fe74a1491b7beaf17e5caf7368/sstable/block_property.go#L132)):*
> ```Go
> 
> // NewBlockIntervalCollector constructs a BlockIntervalCollector, with the
> // given name and data block collector.
> ```

nit: expand the comment to describe the role of the two collectors and that either is permitted to be nil?
___
*[sstable/writer.go, line 625 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1452#-MthejfF0kbUAvbOEpE1:-MthejfF0kbUAvbOEpE2:b-80yivq) ([raw file](https://github.com/cockroachdb/pebble/blob/445976e459f2f9fe74a1491b7beaf17e5caf7368/sstable/writer.go#L625)):*
> ```Go
> 			return err
> 		}
> 	}
> ```

I'm wondering whether we should even bother add range keys to the _table_-property collectors. None of the existing implementations will correctly extract suffixes from range-key internal values, and I think the table-property collectors interface is made obsolete by block-property collectors, which also record a table level property. In CockroachDB, we won't write range keys until a CockroachDB cluster version is finalized that knows about block-property collectors. Then after the next release, it seems like we could remove table-property collectors altogether.
___
*[sstable/testdata/block_properties, line 122 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1452#-MthiPRfB6I6P1eUJV2P:-MthiPRfB6I6P1eUJV2Q:b-4w3vh6) ([raw file](https://github.com/cockroachdb/pebble/blob/445976e459f2f9fe74a1491b7beaf17e5caf7368/sstable/testdata/block_properties#L122)):*
> ```
> point:    [a@5#1,1,c@15#3,1]
> rangedel: [#0,0,#0,0]
> rangekey: [d@20#4,21,z#72057594037927935,21]
> ```

This test collector is a little confusing, because in the context of CockroachDB MVCC timestamps, the suffix on the start key isn't the one that matters*. We care about the suffix(es) encoded within the values.

*The suffix on the start key eg, `d@20` only matters for the purpose of specifying the start bound user key. In CockroachDB, a rangekey `d@20.RANGEKEYSET.4:d@15 [(@10=foo)]` takes effect in the user key range `[d@20,d@15)` but has a MVCC timestamp of `@10`, which is what we should record to the interval collector. In practice, a CockroachDB MVCCDeleteRange range key with those bounds and suffix value has no real effect because there exist no keys within the range `[d@20,d@15)` also at timestamps `<@10`.

**Review by nicktrav — COMMENTED** [review]
> I wonder if we should lean towards recording separate properties.

This implementation would support that, via registering _two_ interval collectors: one with a non-nil point key collector and nil range key collector; and a second with a nil point key collector and a non-nil range key collector. They would have two similar, but different names.

What's not clear to me is whether there may exist a use-case in the future where an interval collector is constructed with both a non-nil point and range key collector with the one name. This implementation is flexible enough to support that, if we ever wanted something like that.

> [I think we should also do this with the FileMetadata.{Smallest,Largest}]

Agree. This is on our TODO list.

I wonder if using these bounds for point keys would be enough to filter at the table level in the case that you mention?

Another option is to move the existing `DataBlockIntervalCollector` interface, `BlockIntervalCollector` struct, and "interval" concept up into Cockroach, and let the caller have full control over how a block property collector works - that could be a combined collector, or it could be two separate collectors.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1452#-:-MtiB8-k5Am8tXk1SQqT:b-xt8f62)* status: 1 of 5 files reviewed, 3 unresolved discussions (waiting on @jbowens, @nicktrav, and @sumeerbhola)

___
*[sstable/writer.go, line 625 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1452#-MthejfF0kbUAvbOEpE1:-MtiDOUm2vD90Urxv3gQ:b-gxedn0) ([raw file](https://github.com/cockroachdb/pebble/blob/445976e459f2f9fe74a1491b7beaf17e5caf7368/sstable/writer.go#L625)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

I'm wondering whether we should even bother add range keys to the _table_-property collectors. None of the existing implementations will correctly extract suffixes from range-key internal values, and I think the table-property collectors interface is made obsolete by block-property collectors, which also record a table level property. In CockroachDB, we won't write range keys until a CockroachDB cluster version is finalized that knows about block-property collectors. Then after the next release, it seems like we could remove table-property collectors altogether.
</blockquote></details>

Sounds good. Removed.
___
*[sstable/testdata/block_properties, line 122 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1452#-MthiPRfB6I6P1eUJV2P:-MtiE0Ux-ZscroJyCkwd:b-wnt3c2) ([raw file](https://github.com/cockroachdb/pebble/blob/445976e459f2f9fe74a1491b7beaf17e5caf7368/sstable/testdata/block_properties#L122)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

This test collector is a little confusing, because in the context of CockroachDB MVCC timestamps, the suffix on the start key isn't the one that matters*. We care about the suffix(es) encoded within the values.

*The suffix on the start key eg, `d@20` only matters for the purpose of specifying the start bound user key. In CockroachDB, a rangekey `d@20.RANGEKEYSET.4:d@15 [(@10=foo)]` takes effect in the user key range `[d@20,d@15)` but has a MVCC timestamp of `@10`, which is what we should record to the interval collector. In practice, a CockroachDB MVCCDeleteRange range key with those bounds and suffix value has no real effect because there exist no keys within the range `[d@20,d@15)` also at timestamps `<@10`.
</blockquote></details>

I'll rework this to use the suffixes present in the values.

**Review by jbowens — COMMENTED** [review]
> They would have two similar, but different names.

I don't think this could be used to avoid unnecessary sstable reads in the scenario described above, at least without additional changes to the block property filter interface, because the combined `pebble.Iterator` over point and range keys would have one set of block property filters. It'd have to supply both filters. 

> I wonder if using these bounds for point keys would be enough to filter at the table level in the case that you mention?

It may be enough if the user key span over which range keys are written is much wider than the point keys', but it doesn't help in the case that they have similar user key spans but very different mvcc timestamp ranges.

Maybe the interface simplicity of this approach is worth the slightly reduced filtering effectiveness. Curious if @sumeerbhola has thoughts

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1452#-:-MtiM-Jr6Bg3omUMrw62:b-utyehb)* status: 1 of 5 files reviewed, 3 unresolved discussions (waiting on @jbowens, @nicktrav, and @sumeerbhola)

**Review by nicktrav — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1452)* status: 1 of 5 files reviewed, 3 unresolved discussions (waiting on @jbowens, @nicktrav, and @sumeerbhola)

___
*[sstable/testdata/block_properties, line 122 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1452#-MthiPRfB6I6P1eUJV2P:-MtieV70C7N3AZoXgCzC:b-gayz24) ([raw file](https://github.com/cockroachdb/pebble/blob/445976e459f2f9fe74a1491b7beaf17e5caf7368/sstable/testdata/block_properties#L122)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

I'll rework this to use the suffixes present in the values.
</blockquote></details>

Updated to pluck the suffix from the value in the case that it's a range key set or unset. I kept the cases for the point keys as this illustrates how the same collector can be used for point-, range-keys, or both.

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
- I agree that the integration with CockroachDB should have different block property collectors for point and range keys. I don't mind the generality here of the `BlockIntervalCollector`. I could also live with a `BlockIntervalCollector` that can do one or the other but not both if there are strong opinions against this current approach.
- I am not keen on moving `BlockIntervalCollector` to the CockroachDB code. The way we did TBI in CockroachDB seems hacky from a code cleanliness perspective, and we have a clean separation of concerns here that we can unit test thoroughly.
- I didn't understand the concern about the combined `pebble.Iterator`. It would be configured with `IterOptions.{PointFilters,RangeKeyFilters}`.

> Reviewed 3 of 5 files at r1, 1 of 1 files at r2, 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1452#-:-Mtigniu5IVoIS8b1FgI:bq0ubiz)* status: 4 of 5 files reviewed, 4 unresolved discussions (waiting on @jbowens, @nicktrav, and @sumeerbhola)

___
*[sstable/block_property.go, line 108 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1452#-MtiecWHBnRpfOHLES4F:-MtiecWHBnRpfOHLES4G:bt1qzy8) ([raw file](https://github.com/cockroachdb/pebble/blob/136b1e0467a745e342ac83bcbc7fd862f358780e/sstable/block_property.go#L108)):*
> ```Go
> 	name   string
> 	points DataBlockIntervalCollector
> 	ranges DataBlockIntervalCollector
> ```

Consider adding a comment like:
A BlockIntervalCollector that collects over point and range keys needs to have both of these DataBlockIntervalCollectors since range keys are fed to the BlockIntervalCollector as they get fed to the Writer, which means they are interleaved with point keys.

(since someone may wonder why we can't reuse one DataBlockIntervalCollector the way we reuse it for different point data blocks)

**Review by jbowens — COMMENTED** [review]
> I didn't understand the concern about the combined pebble.Iterator. It would be configured with IterOptions.{PointFilters,RangeKeyFilters}.

That sounds good to me.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1452#-:-MtikGlm6tkxCCo2c6dB:b-a0a938)* status: 4 of 5 files reviewed, 4 unresolved discussions (waiting on @jbowens, @nicktrav, and @sumeerbhola)

**Review by nicktrav — COMMENTED** [review]
Summarizing a few conversations we had internally. tldr: I think the approach in this PR is sufficient.

> I agree that the integration with CockroachDB should have different block property collectors for point and range keys. I don't mind the generality here of the BlockIntervalCollector.

There's a subtle point here in that even though the implementation in this PR provides the ability to specify both a point and range interval collector _with the same name_, we don't have an immediate use-case for such a collector. Instead, the typical use case (at least in Cockroach), will be to instantiate _two_ interval collectors with _different_ names - one for point keys only, the other for range keys only. The instantiation (in Cockroach) will look like:

```go
const (
  pointKeyCollectorName  = "foo"
  rangeKeyCollectorName = "bar"
)

var PebbleBlockPropertyCollectors = []func() pebble.BlockPropertyCollector{
	func() pebble.BlockPropertyCollector {
		return sstable.NewBlockIntervalCollector(
                        pointKeyCollectorName,
			&pebbleDataBlockMVCCTimeIntervalCollector{}, // point key collector
                        nil, // range key collector
                )
	},
	func() pebble.BlockPropertyCollector {
		return sstable.NewBlockIntervalCollector(
                        rangeKeyCollectorName,
                        nil, // point key collector
			&rangeKeyCollector{}, // range key collector
                )
	},
}
```

> I didn't understand the concern about the combined pebble.Iterator. It would be configured with IterOptions.{PointFilters,RangeKeyFilters}.

Building on from the previous point, as we'll typically have _two_ collectors (one each for points and ranges exclusively), `PointFilters` will filter only for point keys (with the same `pointKeyCollectorName` name as above), and `RangeKeyFilters` will filter only for range keys (with the same `rangeKeyCollectorName` as above).

This will allow for the independent point and range key filtering that we require.

The filtering code is still a TODO for this PR.

> I am not keen on moving BlockIntervalCollector to the CockroachDB code. 

Will keep things as they are in Pebble, so as to avoid exposing too much of the internals to Cockroach.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1452#-:-MtjIWuXAtvK9AzoygIt:b-7kc2ub)* status: 4 of 5 files reviewed, 4 unresolved discussions (waiting on @jbowens, @nicktrav, and @sumeerbhola)

**Review by nicktrav — COMMENTED** [review]
Added another series of test cases to demonstrate how filtering works and verify that the point / range filters will work independently.

I might punt the API change to the top-level iterator options (to take in a slice each for point and range keys) to a second PR, so as to keep this one focused on just the collector changes.

All other feedback addressed, so this should be good for another pass.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1452#-:-MtkHCIKB47j8374IXvM:b-sjw3y2)* status: 2 of 5 files reviewed, 3 unresolved discussions (waiting on @jbowens and @sumeerbhola)

___
*[sstable/block_property.go, line 132 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1452#-MthdIql90Sr9MkSs1Ru:-MtjNBw9-mB58HwO64Iw:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/445976e459f2f9fe74a1491b7beaf17e5caf7368/sstable/block_property.go#L132)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

nit: expand the comment to describe the role of the two collectors and that either is permitted to be nil?
</blockquote></details>

Done.
___
*[sstable/block_property.go, line 108 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1452#-MtiecWHBnRpfOHLES4F:-MtjPEkw29dmrcRIGlSl:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/136b1e0467a745e342ac83bcbc7fd862f358780e/sstable/block_property.go#L108)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Consider adding a comment like:
A BlockIntervalCollector that collects over point and range keys needs to have both of these DataBlockIntervalCollectors since range keys are fed to the BlockIntervalCollector as they get fed to the Writer, which means they are interleaved with point keys.

(since someone may wonder why we can't reuse one DataBlockIntervalCollector the way we reuse it for different point data blocks)

</blockquote></details>

Done.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1452#-:-MttFW-iB_Pq8Nfzabct:bg7igkv)* status: all files reviewed (commit messages unreviewed), 4 unresolved discussions (waiting on @jbowens, @nicktrav, and @sumeerbhola)

___
*[sstable/block_property.go, line 144 at r4](https://reviewable.io/reviews/cockroachdb/pebble/1452#-MttF4UQ82oJu-P1QCRE:-MttF4UQ82oJu-P1QCRF:b-vz5icw) ([raw file](https://github.com/cockroachdb/pebble/blob/609c9de4810d8c2ae9c29e08a209405ddbcbe058/sstable/block_property.go#L144)):*
> ```Go
> // respectively.
> //
> // The caller may pass a nil DataBlockIntervalCollector for either (or both) of
> ```

or both? what purpose would both being nil serve?

**Review by nicktrav — COMMENTED** [review]
TFTRs!

> Dismissed @jbowens and @sumeerbhola from 4 discussions.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1452#-:-MttOKG-El7eDkIgbAcL:bz5mair)* status: 2 of 5 files reviewed, all discussions resolved (waiting on @sumeerbhola)

___
*[sstable/block_property.go, line 144 at r4](https://reviewable.io/reviews/cockroachdb/pebble/1452#-MttF4UQ82oJu-P1QCRE:-MttHKTbD5pT7mj1Dj7m:bser5ld) ([raw file](https://github.com/cockroachdb/pebble/blob/609c9de4810d8c2ae9c29e08a209405ddbcbe058/sstable/block_property.go#L144)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

or both? what purpose would both being nil serve?
</blockquote></details>

No purpose. The comment was more for completeness. Given it's a non-sensical input, we can just panic if it's misconfigured, as that's user-error. Updated and removed parenthetical.

**Pull request merged**
