### PR TITLE
compaction: don't split outputs within a user key

### LINKED ISSUE #734: compaction: Don't split user keys during compactions
Currently, there are some cases in [the compaction loop](https://github.com/cockroachdb/pebble/blob/master/compaction.go#L1516) where user keys could be output to two different sstables, like this:

```
000157.sst:
a.RANGEDEL.6:f
b.SET.15:foo
b.MERGE.8:bar

000158.sst:
b.RANGEDEL.6:f
b.SET.5:baz
b.DEL.3

```

This results in the implicit creation of an "atomic compaction group"; both these SSTables must
be present in compactions together, or it's possible for deleted keys to reappear after a sequence of compactions (see [the comment above](https://github.com/cockroachdb/pebble/blob/master/compaction.go#L306) `expandInputs` on how and why this happens).

These implications of splitting user keys are ultimately unhelpful in increasing compaction parallelization and reducing compaction sizes. The only reason why we split user keys is to maintain similarity in behaviour with RocksDB. We should explore not splitting user keys across different sstables for all compactions (something we already do for flushes as of #675). This should help simplify some compaction logic.

### PR DESCRIPTION
**Pull request by jbowens**
During a compaction, if the current sstable hits the file size limit, defer
finishing the sstable if the next sstable would share a user key. This is the
current behavior of flushes, and this change brings parity between the two.

This change is motivated by introduction of range keys (see #1339). This
ensures we can always cleanly truncate range keys that span sstable boundaries.

This commit also removes (keyspan.Fragmenter).FlushTo. Now that we prohibit
splitting sstables in the middle of a user key, the Fragmenter's FlushTo
function is unnecessary. Compactions and flushes always use the
TruncateAndFlushTo variant.

This change required a tweak to the way grandparent limits are applied, in
order to switch the grandparent splitter's comparison into a >= comparsion.
This was necessary due to the shift in interpreting `splitterSuggestion`s as
exclusive boundaries.

Close #734.

### CODE REVIEW

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1470)* status: 0 of 15 files reviewed, 2 unresolved discussions

___
*[compaction.go, line 161 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1470#-MuH9ikt9xyYCU7H30Tt:-MuH9ikt9xyYCU7H30Tu:bwxjr5j) ([raw file](https://github.com/cockroachdb/pebble/blob/28db1fc52d5be0c2b65472eedd68f7431a0e99e0/compaction.go#L161)):*
> ```Go
> 	// serve as an *exclusive* end boundary truncation point. If we used > then,
> 	// we may have already added a key with the user key `g.limit` to the
> 	// previous sstable.
> ```

We never hit this with L0 outputs because if `key == nil && splitL0Outputs`, we flush all of the tombstones to the current sstable.
___
*[compaction.go, line 2477 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1470#-MuH8gKH9TLDnFQ-yIqU:-MuH8gKH9TLDnFQ-yIqV:bf9kz8d) ([raw file](https://github.com/cockroachdb/pebble/blob/28db1fc52d5be0c2b65472eedd68f7431a0e99e0/compaction.go#L2477)):*
> ```Go
> 			//    (like the grandparent limit is), so that we're guaranteed
> 			//    that splitterSuggestion is greater than the previous user key
> 			//    added to the sstable.
> ```

Is this possible? When the sublevels return an L0 limit `x` is `x` the first key that we _don't_ want to overlap, or the last key of the interval that we _may_ overlap?

If we can rework it such that _x_ is the first key that we _don't_ want our current output to overlap with and enforce it as such, then it's safe to use `splitKey = x` even when we we've exhausted point keys, because we'll know the previous user key must have been < `x`.

**Review by nicktrav — COMMENTED** [review]
Love this cleanup / consolidation. Did a first pass and left some comment

> Reviewed 15 of 15 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1470#-:-MuHf7qOEhOcMkZqtf9i:bdr8c9o)* status: all files reviewed, 10 unresolved discussions (waiting on @itsbilal, @jbowens, and @sumeerbhola)

___
*[-- commits, line 2 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1470#-MuHVyd_71RIhCwJk3UM):*
Can probably link #734 to this too, yeah? Would this close that issue completely?
___
*[-- commits, line 4 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1470#-MuHVhC854ixcv1WPLVb):*
nit: s/is hit/hits/
___
*[compaction.go, line 858 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1470#-MuHWOckCqvJ_VYx2OvN:-MuHWOckCqvJ_VYx2OvO:bu0r80z) ([raw file](https://github.com/cockroachdb/pebble/blob/ca9b45229a2facbe89999eb41da51bbbaf4d7d8c/compaction.go#L858)):*
> ```Go
> // level N. See maxGrandparentOverlapBytes.
> //
> // TODO(peter): Stopping compaction output in the middle of a user-key creates
> ```

`TODO--` nice!
___
*[compaction_picker.go, line 381 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1470#-MuHZV4g7mG0Qb4VG5W4:-MuHZV4g7mG0Qb4VG5W5:b-fh7gzh) ([raw file](https://github.com/cockroachdb/pebble/blob/28db1fc52d5be0c2b65472eedd68f7431a0e99e0/compaction_picker.go#L381)):*
> ```Go
> // sstables. We could perform a migration, re-compacting any sstables with split
> // user keys, which would allow us to remove atomic compaction unit expansion
> // code.
> ```

Seems reasonable. Worth opening a ticket that we can track this against?
___
*[docs/range_deletions.md, line 3 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1470#-MuH_6K-44tD_1BQK7GJ:-MuH_6K-44tD_1BQK7GK:b-h2gxm0) ([raw file](https://github.com/cockroachdb/pebble/blob/28db1fc52d5be0c2b65472eedd68f7431a0e99e0/docs/range_deletions.md#L3)):*
> ```Markdown
> # Range Deletions
> 
> TODO: The following explanation of range deletions does not take into account
> ```

Is this like a follow-up thing? Could that section be removed here?
___
*[internal/keyspan/fragmenter.go, line 286 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1470#-MuH_bz_Bz1zmhmyXvRm:-MuH_bz_Bz1zmhmyXvRn:b-f04bd7) ([raw file](https://github.com/cockroachdb/pebble/blob/ca9b45229a2facbe89999eb41da51bbbaf4d7d8c/internal/keyspan/fragmenter.go#L286)):*
> ```Go
> //
> // The span [a,f) does not cover the key f.
> func (f *Fragmenter) FlushTo(key []byte) {
> ```

Given we're removing this method, is worth rebranding the existing method as `FlushTo` or just `Flush`, now that there's no ambiguity?
___
*[testdata/manual_compaction, line 447 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1470#-MuHhD591yak7x4_kSCe:-MuHhD591yak7x4_kSCf:b-usr9v2) ([raw file](https://github.com/cockroachdb/pebble/blob/28db1fc52d5be0c2b65472eedd68f7431a0e99e0/testdata/manual_compaction#L447)):*
> ```
> ----
> 2:
>   000007:[a#4,SET-a#4,SET]
> ```

The comment mentions sstable (8) and sstable (9). That didn't seem accurate?

Also, we no longer seem to be adjusting the seqnum of the RANGEDEL.
___
*[testdata/manual_compaction, line 579 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1470#-MuHgmrV6fMJvyKZT06F:-MuHgmrV6fMJvyKZT06G:b-nsle29) ([raw file](https://github.com/cockroachdb/pebble/blob/28db1fc52d5be0c2b65472eedd68f7431a0e99e0/testdata/manual_compaction#L579)):*
> ```
> 2:
>   000007:[a#3,SET-c#72057594037927935,RANGEDEL]
>   000008:[c#3,RANGEDEL-e#72057594037927935,RANGEDEL]
> ```

The test comment above mentions "sstable 8". And are we still tweaking the key kind?
___
*[testdata/manual_compaction, line 614 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1470#-MuHgac28mWpsJUMy4Cb:-MuHgac28mWpsJUMy4Cc:b8c1flo) ([raw file](https://github.com/cockroachdb/pebble/blob/28db1fc52d5be0c2b65472eedd68f7431a0e99e0/testdata/manual_compaction#L614)):*
> ```
> ----
> 2:
>   000006:[a#3,SET-e#72057594037927935,RANGEDEL]
> ```

Is the comment block for this test still accurate? We are no longer "cutting", instead outputting a single table.
___
*[testdata/manual_compaction_set_with_del, line 95 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1470#-MuHejbK2WnFXHkjMTNH:-MuHejbK2WnFXHkjMTNI:b-n57xzh) ([raw file](https://github.com/cockroachdb/pebble/blob/28db1fc52d5be0c2b65472eedd68f7431a0e99e0/testdata/manual_compaction_set_with_del#L95)):*
> ```
> ----
> 2:
>   000008:[a#3,SETWITHDEL-c#72057594037927935,RANGEDEL]
> ```

The copy pasta in this file from the previous one probably means "ditto" for all my previous comments :(

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1470)* status: 12 of 15 files reviewed, 5 unresolved discussions (waiting on @itsbilal, @jbowens, @nicktrav, and @sumeerbhola)

___
*[-- commits, line 2 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1470#-MuHVyd_71RIhCwJk3UM):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

Can probably link #734 to this too, yeah? Would this close that issue completely?
</blockquote></details>

Good call, done.
___
*[docs/range_deletions.md, line 3 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1470#-MuH_6K-44tD_1BQK7GJ:-MuIJYhl4hzdsqaqNAa8:b-exvgsh) ([raw file](https://github.com/cockroachdb/pebble/blob/28db1fc52d5be0c2b65472eedd68f7431a0e99e0/docs/range_deletions.md#L3)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

Is this like a follow-up thing? Could that section be removed here?
</blockquote></details>

Yeah, I think much of the discussion of how range deletions work in this document should be updated. We probably to also want to preserve some of the historical discussion of how they used to work, at least for as long as we're supporting stores that may contain them.

**Review by itsbilal — APPROVED** [review]
:lgtm: really nice cleanup!

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1470#-:-MuMxGkl4lySNLR8svKw:b-qygyue)* status: all files reviewed, 6 unresolved discussions (waiting on @jbowens, @nicktrav, and @sumeerbhola)

___
*[compaction.go, line 2477 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1470#-MuH8gKH9TLDnFQ-yIqU:-MuMucV6ABOLzjhZ6ZXG:b2hrl3u) ([raw file](https://github.com/cockroachdb/pebble/blob/28db1fc52d5be0c2b65472eedd68f7431a0e99e0/compaction.go#L2477)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

Is this possible? When the sublevels return an L0 limit `x` is `x` the first key that we _don't_ want to overlap, or the last key of the interval that we _may_ overlap?

If we can rework it such that _x_ is the first key that we _don't_ want our current output to overlap with and enforce it as such, then it's safe to use `splitKey = x` even when we we've exhausted point keys, because we'll know the previous user key must have been < `x`.
</blockquote></details>

We should change the L0 limit splitter to also return splitNow/true if key >= limit (currently it's just key > limit). That's actually more in line with how we want L0 limits to work; we want `limit` to _not_ be in the left-side sstable. We didn't address this well in the past because a lot of this code had the expectation baked in that we only cut the output once you exceed `limit`.
___
*[compaction.go, line 197 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1470#-MuMwz1o-OZ-fGhB-T6M:-MuMwz1o-OZ-fGhB-T6N:bmc5wsj) ([raw file](https://github.com/cockroachdb/pebble/blob/7268416400f450ec91611ec201614075d3dc41e8/compaction.go#L197)):*
> ```Go
> 		// beginning of the first file.
> 		n := len(g.ve.NewFiles)
> 		g.limit = g.c.findGrandparentLimit(g.ve.NewFiles[n-1].Meta.Largest.UserKey)
> ```

Given the simpler semantics of output splitting now, maybe we can replace this line with this line from below:

```
g.limit = g.c.findGrandparentLimit(g.c.rangeDelFrag.Start())
```

Thoughts?
___
*[compaction.go, line 2289 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1470#-MuMu0u42UU3aGcw2uua:-MuMu0u52irdoOeEkEsQ:b-83sjoh) ([raw file](https://github.com/cockroachdb/pebble/blob/7268416400f450ec91611ec201614075d3dc41e8/compaction.go#L2289)):*
> ```Go
> 					// equal to the previous table's largest key user key, and
> 					// the previous table's largest key is not exclusive. This
> 					// violates the invariant that tables are key-space
> ```

Nice!
___
*[internal/keyspan/fragmenter.go, line 286 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1470#-MuH_bz_Bz1zmhmyXvRm:-MuMuS0p3DSVibCd_jHi:b-r7l3v8) ([raw file](https://github.com/cockroachdb/pebble/blob/ca9b45229a2facbe89999eb41da51bbbaf4d7d8c/internal/keyspan/fragmenter.go#L286)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

Given we're removing this method, is worth rebranding the existing method as `FlushTo` or just `Flush`, now that there's no ambiguity?
</blockquote></details>

I think it's still a good idea to keep it `TruncateAndFlushTo`, just to make it clear that we're also truncating range tombstones.

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> Reviewed 4 of 15 files at r1, 1 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1470)* status: all files reviewed, 12 unresolved discussions (waiting on @jbowens and @nicktrav)

___
*[compaction.go, line 161 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1470#-MuH9ikt9xyYCU7H30Tt:-MuNlO2PAhcbyaKtwpkE:b-piv6r4) ([raw file](https://github.com/cockroachdb/pebble/blob/28db1fc52d5be0c2b65472eedd68f7431a0e99e0/compaction.go#L161)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

We never hit this with L0 outputs because if `key == nil && splitL0Outputs`, we flush all of the tombstones to the current sstable.
</blockquote></details>

Isn't that a deficiency of our L0 splitting scheme?
___
*[compaction.go, line 2477 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1470#-MuH8gKH9TLDnFQ-yIqU:-MuNsD0A9mZQGAWX2jp4:bnbyjtt) ([raw file](https://github.com/cockroachdb/pebble/blob/28db1fc52d5be0c2b65472eedd68f7431a0e99e0/compaction.go#L2477)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

We should change the L0 limit splitter to also return splitNow/true if key >= limit (currently it's just key > limit). That's actually more in line with how we want L0 limits to work; we want `limit` to _not_ be in the left-side sstable. We didn't address this well in the past because a lot of this code had the expectation baked in that we only cut the output once you exceed `limit`.
</blockquote></details>

This will unify the two cases, and cause L0 outputs to also split tombstones across many sstables (even if we've run out of point keys), yes? If so, that's what I was hoping we were going to get with this simplification.
___
*[compaction.go, line 168 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1470#-MuNlup184-LKySQN4Tt:-MuNlup184-LKySQN4Tu:b-hrbqk7) ([raw file](https://github.com/cockroachdb/pebble/blob/7268416400f450ec91611ec201614075d3dc41e8/compaction.go#L168)):*
> ```Go
> }
> 
> func (g *grandparentLimitSplitter) onNewOutput(key *InternalKey) []byte {
> ```

`l0LimitSplitter.onNewOutput` is simple because it doesn't need to be worry about a user key spanning sstables. I was hoping this PR would make `grandparentLimitSplitter` be essentially identical to that except that it uses `findGrandparentLimit`. We could even combine the two splitters and parameterize it with a func. Am I missing something?
___
*[compaction.go, line 871 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1470#-MuNmmmP0gUj7BKYwQzm:-MuNmmmP0gUj7BKYwQzn:bqyxmqg) ([raw file](https://github.com/cockroachdb/pebble/blob/7268416400f450ec91611ec201614075d3dc41e8/compaction.go#L871)):*
> ```Go
> 		// this function for how this is used.
> 		if overlappedBytes > c.maxOverlapBytes && c.cmp(start, f.Smallest.UserKey) < 0 {
> 			return f.Smallest.UserKey
> ```

why this change to use `f.Smallest`? Also, we've included this sstable in the `overlappedBytes` when comparing with the threshold, and now we are not allowing the compaction sstable to overlap with this. That seems wrong.
Maybe this is a consequence of the `>=` change in `shouldSplitBefore` but I don't see how.
___
*[compaction.go, line 2309 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1470#-MuNqOzhBIC6oJYt-1BZ:-MuNqOzhBIC6oJYt-1B_:bjl7eux) ([raw file](https://github.com/cockroachdb/pebble/blob/7268416400f450ec91611ec201614075d3dc41e8/compaction.go#L2309)):*
> ```Go
> 			// purposes of bounds computation -- the current sstable will end up with a Largest key
> 			// of c#7,1 so the range tombstone in the current file will be able to delete c#7.
> 			if d.cmp(writerMeta.LargestRangeDel.UserKey, splitKey) >= 0 {
> ```

I think this comment and code is obsolete. But we should verify that `d.cmp(writerMeta.LargestRangeDel.UserKey, splitKey) <= 0`.
___
*[compaction.go, line 2361 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1470#-MuNqtzJ2clngmVtBDNN:-MuNqtzJ2clngmVtBDNO:bq2i8en) ([raw file](https://github.com/cockroachdb/pebble/blob/7268416400f450ec91611ec201614075d3dc41e8/compaction.go#L2361)):*
> ```Go
> 	// L0 splits) L0 limits, before wrapping them in an splitterGroup.
> 	outputSplitters := []compactionOutputSplitter{
> 		&fileSizeSplitter{maxFileSize: c.maxOutputFileSize},
> ```

we could also have wrapper only the `fileSizeSplitter` using the `userKeyChangeSplitter`, like we used to, yes?
Would that be "cheaper" since we would need to compare with `unsafePrevUserKey` only when that splitter was proposing a split?
___
*[compaction.go, line 2443 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1470#-MuNr_Dp7fN84TXce2PG:-MuNr_Dp7fN84TXce2PH:b68hzld) ([raw file](https://github.com/cockroachdb/pebble/blob/7268416400f450ec91611ec201614075d3dc41e8/compaction.go#L2443)):*
> ```Go
> 			// The next key either has a greater user key than the previous
> 			// key, or if not, the previous key must not have had a zero
> 			// sequence number.
> ```

Can we now remove the "or if not ..." part?
___
*[compaction.go, line 2448 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1470#-MuNrq4_70LyonVbNOUS:-MuNrq4_70LyonVbNOUT:b-yb3sd5) ([raw file](https://github.com/cockroachdb/pebble/blob/7268416400f450ec91611ec201614075d3dc41e8/compaction.go#L2448)):*
> ```Go
> 			// grandparent's smallest key may be less than the current key.
> 			// Splitting at the current key will cause this output to overlap
> 			// a potentially unbounded number of grandparents.
> ```

I can't remember the details regarding this TODO -- can you remind me?

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1470)* status: 13 of 15 files reviewed, 9 unresolved discussions (waiting on @itsbilal, @nicktrav, and @sumeerbhola)

___
*[compaction.go, line 161 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1470#-MuH9ikt9xyYCU7H30Tt:-MukkWJL-I3lA64nibQ6:b-ddbbad) ([raw file](https://github.com/cockroachdb/pebble/blob/28db1fc52d5be0c2b65472eedd68f7431a0e99e0/compaction.go#L161)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Isn't that a deficiency of our L0 splitting scheme?
</blockquote></details>

Yeah, it is.
___
*[compaction.go, line 168 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1470#-MuNlup184-LKySQN4Tt:-MulIrPtDy7xhT_qJtrG:b-bbbbyg) ([raw file](https://github.com/cockroachdb/pebble/blob/7268416400f450ec91611ec201614075d3dc41e8/compaction.go#L168)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

`l0LimitSplitter.onNewOutput` is simple because it doesn't need to be worry about a user key spanning sstables. I was hoping this PR would make `grandparentLimitSplitter` be essentially identical to that except that it uses `findGrandparentLimit`. We could even combine the two splitters and parameterize it with a func. Am I missing something?
</blockquote></details>

Nice, that's great.
___
*[compaction.go, line 871 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1470#-MuNmmmP0gUj7BKYwQzm:-Mul--9w9NrpPw5pxD0M:bi47f4g) ([raw file](https://github.com/cockroachdb/pebble/blob/7268416400f450ec91611ec201614075d3dc41e8/compaction.go#L871)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

why this change to use `f.Smallest`? Also, we've included this sstable in the `overlappedBytes` when comparing with the threshold, and now we are not allowing the compaction sstable to overlap with this. That seems wrong.
Maybe this is a consequence of the `>=` change in `shouldSplitBefore` but I don't see how.
</blockquote></details>

Isn't the `overlappedBytes` behavior consistent with the description above?

```
// such large overlaps because they translate into large compactions. The
// current heuristic stops output of a table if the addition of another key
// would cause the table to overlap more than 10x the target file size at
// level N. See maxGrandparentOverlapBytes.
```

If overlapping `f` would increase `overlappedBytes` to be `> c.maxOverlapBytes`, then we _don't_ want to overlap `f`, and we should return `f.Smallest.UserKey`. 

----

The change to `f.Smallest` did fall out out of the `>=` change. When a grandparent's `Largest` is inclusive (not a `RANGEDEL` sentinel), the `>=` would cause us to put a key equal to the `Largest` in the next sstable output. That means the next output sstable would also overlap the grandparent that set the limit, unnecessarily.

The switch to using `f.Smallest` avoids all the inclusivity/exclusivity considerations, since `f.Smallest` is always inclusive, which plays well with `>= limit` splitting logic.
___
*[compaction.go, line 2309 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1470#-MuNqOzhBIC6oJYt-1BZ:-MukqxCQ96uq3B14IBna:b-4pj5my) ([raw file](https://github.com/cockroachdb/pebble/blob/7268416400f450ec91611ec201614075d3dc41e8/compaction.go#L2309)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I think this comment and code is obsolete. But we should verify that `d.cmp(writerMeta.LargestRangeDel.UserKey, splitKey) <= 0`.
</blockquote></details>

Nice, done.
___
*[compaction.go, line 2361 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1470#-MuNqtzJ2clngmVtBDNN:-MukyorF33SFcBxvGtuG:bb6un1j) ([raw file](https://github.com/cockroachdb/pebble/blob/7268416400f450ec91611ec201614075d3dc41e8/compaction.go#L2361)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

we could also have wrapper only the `fileSizeSplitter` using the `userKeyChangeSplitter`, like we used to, yes?
Would that be "cheaper" since we would need to compare with `unsafePrevUserKey` only when that splitter was proposing a split?
</blockquote></details>

Done
___
*[compaction.go, line 2443 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1470#-MuNr_Dp7fN84TXce2PG:-MukzB3E1fe6pw_WJmXV:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/7268416400f450ec91611ec201614075d3dc41e8/compaction.go#L2443)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Can we now remove the "or if not ..." part?
</blockquote></details>

Done.
___
*[compaction.go, line 2448 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1470#-MuNrq4_70LyonVbNOUS:-MukoeZGBC2imtfJa-7G:b-lhqjfh) ([raw file](https://github.com/cockroachdb/pebble/blob/7268416400f450ec91611ec201614075d3dc41e8/compaction.go#L2448)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I can't remember the details regarding this TODO -- can you remind me?
</blockquote></details>

This is talking about a scenario like: The grandparent limit is `b` and `key` is `x` and there's an existing broad range tombstone in the fragmenter with bounds `[a,x)`. The grandparent splitter requests a split before `x`. We fall into this case, and use `x` as the split boundary which creates an sstable that extends well beyond the grandparent limit of `b`.

I think to fix this, we could use `splitKey = min(key.UserKey, splitterSuggestion)`.
___
*[compaction_picker.go, line 381 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1470#-MuHZV4g7mG0Qb4VG5W4:-MukzkS17Yl15AIUTpsD:b-ndsehs) ([raw file](https://github.com/cockroachdb/pebble/blob/28db1fc52d5be0c2b65472eedd68f7431a0e99e0/compaction_picker.go#L381)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

Seems reasonable. Worth opening a ticket that we can track this against?
</blockquote></details>

Yeah, I'll create one once this PR merges.

**Review by nicktrav — APPROVED** [review]
Did another pass. :lgtm:

> Reviewed 3 of 3 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1470#-:-MulUJXM4Diaypv6_vef:bi6thwy)* status: all files reviewed, 7 unresolved discussions (waiting on @sumeerbhola)

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1470)* status: 12 of 15 files reviewed, 7 unresolved discussions (waiting on @itsbilal, @nicktrav, and @sumeerbhola)

___
*[compaction.go, line 2448 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1470#-MuNrq4_70LyonVbNOUS:-Mum0kr6DiECI_oHM3rY:b-3qkvjs) ([raw file](https://github.com/cockroachdb/pebble/blob/7268416400f450ec91611ec201614075d3dc41e8/compaction.go#L2448)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

This is talking about a scenario like: The grandparent limit is `b` and `key` is `x` and there's an existing broad range tombstone in the fragmenter with bounds `[a,x)`. The grandparent splitter requests a split before `x`. We fall into this case, and use `x` as the split boundary which creates an sstable that extends well beyond the grandparent limit of `b`.

I think to fix this, we could use `splitKey = min(key.UserKey, splitterSuggestion)`.
</blockquote></details>

Added a second commit that fixes this and simplifies this code to remove the `switch`.

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1470)* status: 13 of 15 files reviewed, 8 unresolved discussions (waiting on @itsbilal, @jbowens, @nicktrav, and @sumeerbhola)

___
*[compaction.go, line 871 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1470#-MuNmmmP0gUj7BKYwQzm:-MurD74zDSXEA4Bb8dd8:b-kmctzz) ([raw file](https://github.com/cockroachdb/pebble/blob/7268416400f450ec91611ec201614075d3dc41e8/compaction.go#L871)):*
> If overlapping f would increase overlappedBytes to be > c.maxOverlapBytes, then we don't want to overlap f, and we should return f.Smallest.UserKey.

If the file sizes are roughly S and the target file size is 10S, then on average we were splitting at 10.5S earlier and now we are splitting at 9.5S. I agree it doesn't matter much what we do.
But what if this file happens to be huge for whatever reason (ingested file; many seqnums for a user key which prevented a compaction from stopping at the size guideline) and is > 10S by itself. Seems safer to include it and use Largest. Also, will using Smallest potentially get us stuck at this smallest key, say k. We return k, so stop writing to the current sstable when we reach key k. Then ask for a grandparent limit with k, which again returns k.

Thanks for clarifying how this interacts with >= comparison elsewhere. Can you add a detailed code comment here -- this is very easy to miss. Unless there is a correctness issue (the "get us stuck" part above), I'm fine with this change.
___
*[compaction.go, line 2448 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1470#-MuNrq4_70LyonVbNOUS:-MurGmql3BZzB9Urs8wU:b-i952e8) ([raw file](https://github.com/cockroachdb/pebble/blob/7268416400f450ec91611ec201614075d3dc41e8/compaction.go#L2448)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

Added a second commit that fixes this and simplifies this code to remove the `switch`.
</blockquote></details>

Great. Can you add a code comment with this example to motivate why we are choosing the smaller.
___
*[compaction.go, line 179 at r5](https://reviewable.io/reviews/cockroachdb/pebble/1470#-MurCEo06R5OH9HtWxmO:-MurCEo06R5OH9HtWxmP:br35d1m) ([raw file](https://github.com/cockroachdb/pebble/blob/3ea1111afcc4f4d422d3232c8db1549ba3e72a3d/compaction.go#L179)):*
> ```Go
> 		//
> 		// a.SET.3
> 		// (L0 limit at b)
> ```

nit: L0 limit is stale

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1470)* status: 12 of 15 files reviewed, 7 unresolved discussions (waiting on @itsbilal, @nicktrav, and @sumeerbhola)

___
*[compaction.go, line 871 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1470#-MuNmmmP0gUj7BKYwQzm:-MuvL7qR2Ue5-80973Ys:burs0dq) ([raw file](https://github.com/cockroachdb/pebble/blob/7268416400f450ec91611ec201614075d3dc41e8/compaction.go#L871)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

> If overlapping f would increase overlappedBytes to be > c.maxOverlapBytes, then we don't want to overlap f, and we should return f.Smallest.UserKey.

If the file sizes are roughly S and the target file size is 10S, then on average we were splitting at 10.5S earlier and now we are splitting at 9.5S. I agree it doesn't matter much what we do.
But what if this file happens to be huge for whatever reason (ingested file; many seqnums for a user key which prevented a compaction from stopping at the size guideline) and is > 10S by itself. Seems safer to include it and use Largest. Also, will using Smallest potentially get us stuck at this smallest key, say k. We return k, so stop writing to the current sstable when we reach key k. Then ask for a grandparent limit with k, which again returns k.

Thanks for clarifying how this interacts with >= comparison elsewhere. Can you add a detailed code comment here -- this is very easy to miss. Unless there is a correctness issue (the "get us stuck" part above), I'm fine with this change.

</blockquote></details>

I think we're okay, because of the existing requirement that `findGrandparentLimit` always return a key greater than `start`. I believe that requirement was added to handle a similar problem of being 'stuck' but with the `Largest`.

I added a comment explaining the rationale for using `Smallest`, and also adjusted the logic enforcing that we return a key `> start` so that we avoid the key comparison once we've seen a file with a `Smallest > start`.
___
*[compaction.go, line 2448 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1470#-MuNrq4_70LyonVbNOUS:-Muv7Pn54p7N2LsXwlsM:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/7268416400f450ec91611ec201614075d3dc41e8/compaction.go#L2448)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Great. Can you add a code comment with this example to motivate why we are choosing the smaller.
</blockquote></details>

Done.
___
*[compaction.go, line 179 at r5](https://reviewable.io/reviews/cockroachdb/pebble/1470#-MurCEo06R5OH9HtWxmO:-Muv7dBJA3Vm11QdziUG:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/3ea1111afcc4f4d422d3232c8db1549ba3e72a3d/compaction.go#L179)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nit: L0 limit is stale
</blockquote></details>

Done.

**Review by sumeerbhola — APPROVED** [review]
:lgtm_strong: 

> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1470#-:-Mv-dCJn3hRBvBClV8rr:b-uwkowd)* status: 13 of 15 files reviewed, 7 unresolved discussions (waiting on @itsbilal, @nicktrav, and @sumeerbhola)

**Review by jbowens — COMMENTED** [review]
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1470#-:-Mv-ieT4ETR-isxm5Oku:bz5mair)* status: 13 of 15 files reviewed, 7 unresolved discussions (waiting on @itsbilal, @nicktrav, and @sumeerbhola)

**Pull request merged**
