### PR TITLE
sstable: fix comments about the sstable format

### PR DESCRIPTION
**Pull request by sumeerbhola**

### CODE REVIEW

**Review by sumeerbhola — COMMENTED** [review]
Since some of us are fiddling with the sstable format, we should fix the existing comments.
Please make sure I've not misstated something.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1402#-:-MqQWXq77ynMO0CpVk3K:bdd42h2)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @jbowens and @nicktrav)

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1402)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @jbowens, @nicktrav, and @sumeerbhola)

___
*[sstable/table.go, line 95 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1402#-MqQc2l64NlnPmx3cwRv:-MqQc2l64NlnPmx3cwRw:b37wto7) ([raw file](https://github.com/cockroachdb/pebble/blob/6ffdd32f2d43ea608a4e569c37c86e5726fc1815/sstable/table.go#L95)):*
> ```Go
> 
> A Reader eagerly loads the footer, metaindex block and meta properties block,
> which is why they are a suffix of the file, for better locality. The metaindex
> ```

Does the locality matter here? IMO, the Reader eagerly loads the footer, metaindex block, and meta properties block because the data contained in those blocks is needed on every read, and even before reading. For example, the meta properties block is used to verify the comparer and merger are compatible, and the metaindex block contains the locations of all other blocks. Lazily loading this information would add code to the read path, but we can reasonably assume that creating a Reader is an indication that we'll be creating an Iterator on that Reader shortly.
___
*[sstable/table.go, line 99 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1402#-MqQcIqC9iXVFHxfqK9S:-MqQcIqC9iXVFHxfqK9T:b-5anw53) ([raw file](https://github.com/cockroachdb/pebble/blob/6ffdd32f2d43ea608a4e569c37c86e5726fc1815/sstable/table.go#L99)):*
> ```Go
> 
> TODO(sumeer): is there a reason for placing the meta filter block before the
> index block?
> ```

I think this was done to match RocksDB/LevelDB behavior. If I recall correctly, we have a test somewhere that looks for byte-for-byte identical creation of sstables with RocksDB.
___
*[sstable/table.go, line 141 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1402#-MqQbv8F5M581M91eydV:-MqQbv8F5M581M91eydW:b-440eqp) ([raw file](https://github.com/cockroachdb/pebble/blob/6ffdd32f2d43ea608a4e569c37c86e5726fc1815/sstable/table.go#L141)):*
> ```Go
> 100 bytes.
> 
> Instead of a single index block, one could have a two-level index which consist
> ```

We already support this two-level index structure. Is this comment trying to indicate that? The "one could" phrasing makes it sound like this is something we might do in the future, but it already exists today, pretty much just as you describe.

**Review by nicktrav — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1402)* status: all files reviewed, 5 unresolved discussions (waiting on @jbowens and @sumeerbhola)

___
*[sstable/table.go, line 88 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1402#-MqQneFJAYTdR6S9OC9A:-MqQneFJAYTdR6S9OC9B:b-h6vyu8) ([raw file](https://github.com/cockroachdb/pebble/blob/6ffdd32f2d43ea608a4e569c37c86e5726fc1815/sstable/table.go#L88)):*
> ```Go
> [meta filter block]
> [index block]
> [meta rangedel block]
> ```

Some of these blocks will be optional (i.e. for rangdels now and soon to be for range keys). Worth calling that out so one is not surprised when they do not encounter them.
___
*[sstable/table.go, line 146 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1402#-MqQnFQ73g3Ytt56QoF9:-MqQnFQ73g3Ytt56QoFA:b-gkw855) ([raw file](https://github.com/cockroachdb/pebble/blob/6ffdd32f2d43ea608a4e569c37c86e5726fc1815/sstable/table.go#L146)):*
> ```Go
> index blocks.
> 
> The metaindex block also contains block handles as values, referring to the
> ```

Maybe mention the keys are the "names" of the blocks they point to?

**Review by nicktrav — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1402)* status: all files reviewed, 3 unresolved discussions (waiting on @jbowens and @sumeerbhola)

**Review by sumeerbhola — COMMENTED** [review]
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1402#-:-MqR5IthEkRp8JgtqhHT:bz5mair)* status: all files reviewed, 3 unresolved discussions (waiting on @jbowens and @petermattis)

___
*[sstable/table.go, line 88 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1402#-MqQneFJAYTdR6S9OC9A:-MqR1ua-BHzYKKLZnYVz:bsf4o88) ([raw file](https://github.com/cockroachdb/pebble/blob/6ffdd32f2d43ea608a4e569c37c86e5726fc1815/sstable/table.go#L88)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

Some of these blocks will be optional (i.e. for rangdels now and soon to be for range keys). Worth calling that out so one is not surprised when they do not encounter them.
</blockquote></details>

added optional to the comment.
___
*[sstable/table.go, line 95 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1402#-MqQc2l64NlnPmx3cwRv:-MqR1zvB5wjwsKJ2Y19Q:bfgjbkw) ([raw file](https://github.com/cockroachdb/pebble/blob/6ffdd32f2d43ea608a4e569c37c86e5726fc1815/sstable/table.go#L95)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Does the locality matter here? IMO, the Reader eagerly loads the footer, metaindex block, and meta properties block because the data contained in those blocks is needed on every read, and even before reading. For example, the meta properties block is used to verify the comparer and merger are compatible, and the metaindex block contains the locations of all other blocks. Lazily loading this information would add code to the read path, but we can reasonably assume that creating a Reader is an indication that we'll be creating an Iterator on that Reader shortly.
</blockquote></details>

- I've rephrased the locality comment and made it more casual. This now includes the case where one wants to minimize the number of read requests to load these 3 (like in the S3 case) by reading say a 50KB suffix of the file.
- Added part of your text regarding why the Reader loads them eagerly.
___
*[sstable/table.go, line 99 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1402#-MqQcIqC9iXVFHxfqK9S:-MqR2l6wAjBUctuy-khA:b-8b11j9) ([raw file](https://github.com/cockroachdb/pebble/blob/6ffdd32f2d43ea608a4e569c37c86e5726fc1815/sstable/table.go#L99)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I think this was done to match RocksDB/LevelDB behavior. If I recall correctly, we have a test somewhere that looks for byte-for-byte identical creation of sstables with RocksDB.
</blockquote></details>

Added
___
*[sstable/table.go, line 141 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1402#-MqQbv8F5M581M91eydV:-MqR4Ca84xMGrX2EBuCM:b-b9uu67) ([raw file](https://github.com/cockroachdb/pebble/blob/6ffdd32f2d43ea608a4e569c37c86e5726fc1815/sstable/table.go#L141)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

We already support this two-level index structure. Is this comment trying to indicate that? The "one could" phrasing makes it sound like this is something we might do in the future, but it already exists today, pretty much just as you describe.
</blockquote></details>

Removed the "one could" phrasing.
___
*[sstable/table.go, line 146 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1402#-MqQnFQ73g3Ytt56QoF9:-MqR4gXj5MOrSs8wM_y0:bb6un1j) ([raw file](https://github.com/cockroachdb/pebble/blob/6ffdd32f2d43ea608a4e569c37c86e5726fc1815/sstable/table.go#L146)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

Maybe mention the keys are the "names" of the blocks they point to?
</blockquote></details>

Done

**Review by petermattis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1402#-:-MqURaaPABiVBh9Iksuu:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jbowens)

**Pull request merged**
