### PR TITLE
db: write manifest before creating WAL during Open 

### PR DESCRIPTION
**Pull request by jbowens**
Write out the new manifest file before creating a new WAL file during
Open. Previously, a crash between the creation of the WAL and the
MANIFEST could leave the second most recent WAL with an unclean tail.
The unclean tail would be considered corruption on a subsequent Open.

See cockroachdb/cockroach#68319.

### CODE REVIEW

**Review by petermattis — APPROVED** [review]
:lgtm: nice find!

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1212#-:-MgB0IIV6gI2K9prJOgR:b-klf2oc)* status: 3 of 8 files reviewed, all discussions resolved (waiting on @itsbilal and @sumeerbhola)

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1212)* status: all files reviewed, 4 unresolved discussions (waiting on @itsbilal and @jbowens)

___
*[open_test.go, line 663 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1212#-MgAyX2fDzphqdflXst4:-MgAyX2fDzphqdflXst5:b-a1jh99) ([raw file](https://github.com/cockroachdb/pebble/blob/5cb4d08ce2869d8b69583255934f7e2d9cac69f7/open_test.go#L663)):*
> ```Go
> 
> 		// Ignore syncs during close to simulate a crash. This will leave the WAL
> 		// with an unclean tail.
> ```

It's not completely clear to me what is happening here:
- The Set specified Sync, so the chunk corresponding to the mutation must be in the WAL. So we have a partial block with a chunk, yes?
- This SetIgnoreSyncs(true) will ensure we don't manage to write the EOF trailer (the chunk header with the different log number).
- When we read this WAL, it will encounter a complete chunk and then no more bytes (if it was not a recycled WAL, since this is a new DB) in the file. Will record.Reader return an error in this case, and if yes, why?

Ah, maybe it is because the comment says "unclean tail" when it is not actually unclean, and you are explicitly making it unclean below by appending garbage.
___
*[open_test.go, line 712 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1212#-MgB0O-e-_zxR6Am8CVQ:-MgB0O-e-_zxR6Am8CVR:b4wz2ye) ([raw file](https://github.com/cockroachdb/pebble/blob/5cb4d08ce2869d8b69583255934f7e2d9cac69f7/open_test.go#L712)):*
> ```Go
> 					atomic.StoreUint32(&atomicWALCreated, 1)
> 				}
> 				if op == errorfs.OpFileSync && path == "" && atomic.LoadUint32(&atomicWALCreated) == 1 {
> ```

Can you add a comment that path == "" tells us this is a directory sync since it is equal to the path passed to Open?
___
*[open_test.go, line 727 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1212#-MgB1U-ZENjheP-ihOln:-MgB1U-ZENjheP-ihOlo:bds3i29) ([raw file](https://github.com/cockroachdb/pebble/blob/5cb4d08ce2869d8b69583255934f7e2d9cac69f7/open_test.go#L727)):*
> ```Go
> 	if n := len(getLogs()); n != 2 {
> 		t.Fatalf("expected two logs, found %d\n", n)
> 	}
> ```

Nice test!
___
*[internal/errorfs/errorfs.go, line 145 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1212#-MgAsRqHEXOXNle7LfnX:-MgAsRqHEXOXNle7LfnY:beftaaf) ([raw file](https://github.com/cockroachdb/pebble/blob/558cb0bc6c4f7ef5657df356f1c169e5016f6df0/internal/errorfs/errorfs.go#L145)):*
> ```Go
> // Injector injects errors into FS operations.
> type Injector interface {
> 	MaybeError(Op, string) error
> ```

can you name the parameters here so that one can immediately know that the string is the path.

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1212)* status: 2 of 8 files reviewed, 4 unresolved discussions (waiting on @itsbilal, @petermattis, and @sumeerbhola)

___
*[open_test.go, line 663 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1212#-MgAyX2fDzphqdflXst4:-MgBHPTaCexryKdfGb86:b-bmz6i8) ([raw file](https://github.com/cockroachdb/pebble/blob/5cb4d08ce2869d8b69583255934f7e2d9cac69f7/open_test.go#L663)):*
> Ah, maybe it is because the comment says "unclean tail" when it is not actually unclean, and you are explicitly making it unclean below by appending garbage.

Yeah, that's right. I adjusted the commentary to make this explicit. The first bit creates a WAL without an EOF trailer. The second bit appends garbage to make it unclean.
___
*[open_test.go, line 712 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1212#-MgB0O-e-_zxR6Am8CVQ:-MgBGZ979uHbbHRlibow:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/5cb4d08ce2869d8b69583255934f7e2d9cac69f7/open_test.go#L712)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Can you add a comment that path == "" tells us this is a directory sync since it is equal to the path passed to Open?
</blockquote></details>

Done.
___
*[open_test.go, line 727 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1212#-MgB1U-ZENjheP-ihOln:-MgBGZtzA1I7cjGsLxLN:b-ucfknh) ([raw file](https://github.com/cockroachdb/pebble/blob/5cb4d08ce2869d8b69583255934f7e2d9cac69f7/open_test.go#L727)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Nice test!
</blockquote></details>

Thanks!
___
*[internal/errorfs/errorfs.go, line 145 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1212#-MgAsRqHEXOXNle7LfnX:-MgBGaQEBeTjRstDk_lX:b-48vilg) ([raw file](https://github.com/cockroachdb/pebble/blob/558cb0bc6c4f7ef5657df356f1c169e5016f6df0/internal/errorfs/errorfs.go#L145)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

can you name the parameters here so that one can immediately know that the string is the path.
</blockquote></details>

Good call, done.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 6 files at r3, 2 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1212#-:-MgBRmkMCjGBxFTpOs8X:bg7igkv)* status: 5 of 8 files reviewed, 5 unresolved discussions (waiting on @itsbilal, @jbowens, and @sumeerbhola)

___
*[open_test.go, line 663 at r4](https://reviewable.io/reviews/cockroachdb/pebble/1212#-MgBRZ6X4cfz4Q6YshEC:-MgBRZ6X4cfz4Q6YshED:b-og8r19) ([raw file](https://github.com/cockroachdb/pebble/blob/641d20967884c028252d9f279e0a2487dfbf0f69/open_test.go#L663)):*
> ```Go
> 
> 		// Ignore syncs during close to simulate a crash. This will leave the WAL
> 		// without an EOF trailer. It won't be an 'unclean tail' yet since it
> ```

nit: since the log ...

**Review by jbowens — COMMENTED** [review]
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1212#-:-MgBYT2H82YOB-wB0Vrd:bz5mair)* status: 4 of 8 files reviewed, 5 unresolved discussions (waiting on @itsbilal, @jbowens, and @sumeerbhola)

**Pull request merged**
