### PR TITLE
*: Set isIgnorableBoundaryKey=true for rangedel boundaries in levelIter

### LINKED ISSUE #2118: github.com/cockroachdb/pebble/internal/metamorphic: TestMeta failed
github.com/cockroachdb/pebble/internal/metamorphic.TestMeta [failed](https://buildConfiguration/Cockroach_Nightlies_Pebble_Metamorphic/7423668?buildTab=log) with [artifacts](https://buildConfiguration/Cockroach_Nightlies_Pebble_Metamorphic/7423668?buildTab=artifacts#meta) on refs/heads/master @ [7b30bd86ff65](https://github.com/cockroachdb/pebble/commits/7b30bd86ff65):

```
=== CONT  TestMeta/execution/standard-023
=== RUN   TestMeta/compare/standard-012
=== RUN   TestMeta/execution
=== RUN   TestMeta/execution/standard-010
=== PAUSE TestMeta/execution/standard-010
=== CONT  TestMeta/execution/standard-010
=== RUN   TestMeta/execution/random-024
=== PAUSE TestMeta/execution/random-024
=== CONT  TestMeta/execution/random-024
=== RUN   TestMeta/execution/random-013
=== PAUSE TestMeta/execution/random-013
=== CONT  TestMeta/execution/random-013
=== RUN   TestMeta/execution/random-023
=== PAUSE TestMeta/execution/random-023
=== CONT  TestMeta/execution/random-023
=== RUN   TestMeta/execution/random-015
=== PAUSE TestMeta/execution/random-015
=== CONT  TestMeta/execution/random-015
=== RUN   TestMeta/execution/random-020
=== PAUSE TestMeta/execution/random-020
=== CONT  TestMeta/execution/random-020
=== RUN   TestMeta/execution/standard-021
=== PAUSE TestMeta/execution/standard-021
=== CONT  TestMeta/execution/standard-021
=== RUN   TestMeta/execution/random-007
=== PAUSE TestMeta/execution/random-007
=== CONT  TestMeta/execution/random-007
=== RUN   TestMeta/execution/random-012
=== PAUSE TestMeta/execution/random-012
=== CONT  TestMeta/execution/random-012
=== RUN   TestMeta/execution/random-006
=== PAUSE TestMeta/execution/random-006
=== CONT  TestMeta/execution/random-006
=== RUN   TestMeta/execution/standard-011
=== PAUSE TestMeta/execution/standard-011
=== CONT  TestMeta/execution/standard-011
=== RUN   TestMeta/execution/standard-020
=== PAUSE TestMeta/execution/standard-020
=== CONT  TestMeta/execution/standard-020
=== RUN   TestMeta/compare/standard-007
=== RUN   TestMeta/compare/standard-008
=== RUN   TestMeta/execution/standard-002
=== PAUSE TestMeta/execution/standard-002
=== CONT  TestMeta/execution/standard-002
=== RUN   TestMeta/execution/random-008
=== PAUSE TestMeta/execution/random-008
=== CONT  TestMeta/execution/random-008
=== RUN   TestMeta/execution/random-014
=== PAUSE TestMeta/execution/random-014
=== CONT  TestMeta/execution/random-014
```
<details><summary>Help</summary>
<p>
To reproduce, try:

```bash
go test -mod=vendor -tags 'invariants' -exec 'stress -p 1' -timeout 0 -test.v -run TestMeta$ ./internal/metamorphic -seed 1668072880985143374 -ops "uniform:5000-10000"
```
</p>
</details>
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestMeta.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### PR DESCRIPTION
**Pull request by itsbilal**
Merge keys put the top level Iterator's position to `iterPosNext`, and
    in the process of Next()ing to the next user key, one of the child
    levelIters could have advanced past the sstable that contained the
    Merge that is being returned.

  If that sstable contained a range delete covering a key in an sstable
  in a lower level, and the lower level's key was not exposed to the
  mergingIter due to a bloom filter mismatch, and we do two consecutive
  SeekPrefixGEs where the second one gets TrySeekUsingNext, we could
  end up surfacing the deleted key in the lower sstable as the
  higher level's levelIter has already moved past the sstable
  containing the range deletion.

  This change sets isIgnorableBoundaryKey = true when returning
  largestBoundary in the levelIter to prevent the mergingIter from
  next()ing past it in the first SeekPrefixGE.

Fixes https://github.com/cockroachdb/pebble/issues/2118.

### CODE REVIEW

**Comment by itsbilal** [comment]
@jbowens happy to hear your thoughts on this; maybe this is an overly-defensive disabling of the optimization when we can do something like setting `isIgnorableBoundaryKey` to true in the `levelIter.skipEmptyFileForward` case that pauses at the rangedel sentinel key. For some reason `levelIter` flips that flag to true in `SeekPrefixGE`'s rangedel-sentinel pausing case but not in `Next()/skipEmptyFileForward()`.

**Review by jbowens — COMMENTED** [review]
I'm having a hard time wrapping my head around what the bug is. It looks like the unit test doesn't exercise the bug, because the test still passes after reverting `iterator.go`?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2123#-:-NGckq7K1YE1tUILHTq6:br4uq1f)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @itsbilal)

**Review by itsbilal — COMMENTED** [review]
@jbowens you were right. I found the last missing piece of the puzzle; the lower level SST has to have a bloom filter mismatch in the first SeekPrefixGE, otherwise the deleted key gets surfaced to the mergingIter and we don't double-next() the higher level sstable. The test fails now if you revert the other change. I also made the `isIgnorableBoundaryKey` change as that passes the test too.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2123#-:-NGlZ8JQ1Mx0Mphvuy-6:bkgv3lu)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @itsbilal)

**Comment by itsbilal** [comment]
Nevermind, this trips up another test. I'll revert to the previous fix soon.

**Comment by itsbilal** [comment]
Reverted to the original fix and test improved, PTAL!

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2123)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @itsbilal and @jbowens)

___
*[`iterator.go` line 1298 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2123#-NGq_HPb6YpGq6DO_oNB:-NGq_HPb6YpGq6DO_oNC:b-hv8aim) ([raw file](https://github.com/cockroachdb/pebble/blob/f740894165b27ce2a677c07c2dbbda48070d9dce/iterator.go#L1298)):*
> ```Go
> 	}
> 	if lastPositioningOp == seekPrefixGELastPositioningOp && i.pos != iterPosNext {
> 		// iterPosNext is unsafe to optimize for TrySeekUsingNext. This is because
> ```

I'm having some difficulty with this change, both in understanding and whether this ought to be the fix. Ideally we should be able to state an invariant about the `InternalIterator` tree and use that to decide on the optimization here (like we do in our current optimizations in iterator.go) and not have to reason about the details about the `InternalIterator` implementation. I worry that with the latter we will move much closer to not being able to understand or improve these optimizations in the future.
I don't quite understand the gap in the current pausing logic in level_iter.go and merging_iter.go that is causing this -- I suspect the fix belongs there and not in iterator.go.

btw, I'm unsure about how this works in the presence of `InterleavingIter`. `nextPointCurrentUserKey` can set `i.pos = iterPosNext` because the range key iterator is the current position and the point iter it at the next position. I guess this is harmless from a correctness perspective, but will mean we don't use `TrySeekUsingNext`?

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2123)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @itsbilal and @sumeerbhola)

___
*[`iterator.go` line 1298 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2123#-NGq_HPb6YpGq6DO_oNB:-NGqvi5w-q9SbDQwnHT5:b1piurx) ([raw file](https://github.com/cockroachdb/pebble/blob/f740894165b27ce2a677c07c2dbbda48070d9dce/iterator.go#L1298)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I'm having some difficulty with this change, both in understanding and whether this ought to be the fix. Ideally we should be able to state an invariant about the `InternalIterator` tree and use that to decide on the optimization here (like we do in our current optimizations in iterator.go) and not have to reason about the details about the `InternalIterator` implementation. I worry that with the latter we will move much closer to not being able to understand or improve these optimizations in the future.
I don't quite understand the gap in the current pausing logic in level_iter.go and merging_iter.go that is causing this -- I suspect the fix belongs there and not in iterator.go.

btw, I'm unsure about how this works in the presence of `InterleavingIter`. `nextPointCurrentUserKey` can set `i.pos = iterPosNext` because the range key iterator is the current position and the point iter it at the next position. I guess this is harmless from a correctness perspective, but will mean we don't use `TrySeekUsingNext`?

</blockquote></details>

Ditto. Is the bug that we don't do [this logic](https://github.com/cockroachdb/pebble/blob/1bda21f14fc2d77b95097edab4869e768c56f5a6/level_iter.go#L731-L757) when the level iter gets Next-ed during prefix iteration mode?

And currently we don't have knowledge of whether we're in prefix mode during `levelIter.Next`, so we can't readily just add that logic to the `Next` exhaustion case?

**Comment by itsbilal** [comment]
*[`iterator.go` line 1298 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2123#-NGq_HPb6YpGq6DO_oNB:-NGqwZJm6uI4nRfYk-7F:bksx2x0) ([raw file](https://github.com/cockroachdb/pebble/blob/f740894165b27ce2a677c07c2dbbda48070d9dce/iterator.go#L1298)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

Ditto. Is the bug that we don't do [this logic](https://github.com/cockroachdb/pebble/blob/1bda21f14fc2d77b95097edab4869e768c56f5a6/level_iter.go#L731-L757) when the level iter gets Next-ed during prefix iteration mode?

And currently we don't have knowledge of whether we're in prefix mode during `levelIter.Next`, so we can't readily just add that logic to the `Next` exhaustion case?
</blockquote></details>

Just pushed a detailed example into the comments, hope that helps. Also reverted to the `isIgnorableBoundaryKey` fix that I had yesterday, which is in line with Sumeer's comment. It changed some other datadriven tests like I had mentioned earlier but it seems safe to me (more eyes here would help).

Not sure if levelIter needs to know about prefix iteration, but we shouldn't be double-Nexting past the sstable containing the range delete in any case (I think).

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2123)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @itsbilal and @sumeerbhola)

___
*[`level_iter.go` line 960 at r4](https://reviewable.io/reviews/cockroachdb/pebble/2123#-NGr1SIVCdxvRzE3LsHT:-NGr1SIW49sQWemplao7:bo0woig) ([raw file](https://github.com/cockroachdb/pebble/blob/7ca96e072eb586d3f97993337fa322059be4cbfb/level_iter.go#L960)):*
> ```Go
> 				if l.boundaryContext != nil {
> 					l.boundaryContext.isIgnorableBoundaryKey = true
> 				}
> ```

This `isIgnorableBoundaryKey` change makes sense to me.

If I'm not mistaken, we could adjust the handling of range tombstones to always rely on `isIgnorableBoundaryKey` and remove `mergingIter.elideRangeTombstones`. We've be relying on the levelIter always setting `isIgnorableBoundaryKey = true` whenever it returns one of these boundary keys (including in `skipEmptyFileBackward`). The mergingIter would not need to perform any checks for range deletion key kinds. When using within an `Iterator`, the mergingIter will never return range tombstone keys, as it does today with `elideRangeTombstones=true`. When used in compactions, it will continue to return interleaved range deletions, just not any of the artificial boundary keys.
___
*[`iterator.go` line 1298 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2123#-NGq_HPb6YpGq6DO_oNB:-NGr4AT_33D68u1mOJlE:b-50mirs) ([raw file](https://github.com/cockroachdb/pebble/blob/f740894165b27ce2a677c07c2dbbda48070d9dce/iterator.go#L1298)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Just pushed a detailed example into the comments, hope that helps. Also reverted to the `isIgnorableBoundaryKey` fix that I had yesterday, which is in line with Sumeer's comment. It changed some other datadriven tests like I had mentioned earlier but it seems safe to me (more eyes here would help).

Not sure if levelIter needs to know about prefix iteration, but we shouldn't be double-Nexting past the sstable containing the range delete in any case (I think).
</blockquote></details>

Thanks, this example helped.

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2123)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @itsbilal and @jbowens)

___
*[`level_iter.go` line 960 at r4](https://reviewable.io/reviews/cockroachdb/pebble/2123#-NGr1SIVCdxvRzE3LsHT:-NGrOFXDDcfxAE9m6UCq:b-1ju5v1) ([raw file](https://github.com/cockroachdb/pebble/blob/7ca96e072eb586d3f97993337fa322059be4cbfb/level_iter.go#L960)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

This `isIgnorableBoundaryKey` change makes sense to me.

If I'm not mistaken, we could adjust the handling of range tombstones to always rely on `isIgnorableBoundaryKey` and remove `mergingIter.elideRangeTombstones`. We've be relying on the levelIter always setting `isIgnorableBoundaryKey = true` whenever it returns one of these boundary keys (including in `skipEmptyFileBackward`). The mergingIter would not need to perform any checks for range deletion key kinds. When using within an `Iterator`, the mergingIter will never return range tombstone keys, as it does today with `elideRangeTombstones=true`. When used in compactions, it will continue to return interleaved range deletions, just not any of the artificial boundary keys.
</blockquote></details>

I went and reread https://github.com/cockroachdb/pebble/issues/1725#issuecomment-1139741524. Is the improvement you are suggesting changing the bullet "Pausing when reach a file bound that is a rangedel: mergingIter skips these keys since it ignores based on InternalKeyKindRangeDelete"?

btw, while we are here I think we should improve the commentary around `isSyntheticIterBoundsKey` and `isIgnorableBoundaryKey`. I tend to forget why both concepts are needed, and maybe others do too.
My understanding is that the former (a) plays a role in switching directions that needs it to be a separate concept (but the details for that I have forgotten), (b) allows for stating an invariant for the whole mergingIter when the synthetic key is at the top, since the bounds that are reached apply to the whole iterator heap (in comparison `isIgnorableBoundaryKey` is a local pause for a level). (b) is why we can break here https://github.com/cockroachdb/pebble/blob/1bda21f14fc2d77b95097edab4869e768c56f5a6/merging_iter.go#L687-L688 while we can't do so for `isIgnorableBoundaryKey`

**Comment by jbowens** [comment]
> I went and reread https://github.com/cockroachdb/pebble/issues/1725#issuecomment-1139741524. Is the improvement you are suggesting changing the bullet "Pausing when reach a file bound that is a rangedel: mergingIter skips these keys since it ignores based on InternalKeyKindRangeDelete"?

Yeah. Instead of skipping them based on `InternalKeyKindRangeDelete`, it'd skip them based on `isIgnorableBoundaryKey`.

My understanding is that `isIgnorableBoundaryKey` is set to indicate that a key is an artificial boundary key that exists only to prevent the level iterator from proceeding to the next file before the merging iterator is done with its range deletions. The merging iterator skips these ignorable boundary keys. Previously, before the introduction of `isIgnorableBoundaryKey`, we would always use `Kind() == InternalKeyKindRangeDelete` to determine whether a way as a boundary key that could be skipped. Currently, on master, we use both, inconsistently.

----

I'm having a hard time recalling when `isSyntheticIterBoundsKey` (https://github.com/cockroachdb/pebble/commit/879f3bfeef077b895c9dae801ac97383a93e258e) is necessary.

**Comment by itsbilal** [comment]
> My understanding is that isIgnorableBoundaryKey is set to indicate that a key is an artificial boundary key that exists only to prevent the level iterator from proceeding to the next file before the merging iterator is done with its range deletions. The merging iterator skips these ignorable boundary keys. Previously, before the introduction of isIgnorableBoundaryKey, we would always use Kind() == InternalKeyKindRangeDelete to determine whether a way as a boundary key that could be skipped. Currently, on master, we use both, inconsistently.

There's one additional use of `isIgnorableBoundaryKey` and it's in `mergingIter.findNextEntry` where we check if we're in prefix iteration and at an ignorable boundary key that's at a different prefix than the prefix we're searching for. See:

https://github.com/cockroachdb/pebble/blob/1bda21f14fc2d77b95097edab4869e768c56f5a6/merging_iter.go#L722

I'll make the change to remove `elideRangeTombstones` in a separate commit just to keep the bugfix isolated in history.

**Review by itsbilal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2123)* status: 0 of 10 files reviewed, 2 unresolved discussions (waiting on @itsbilal, @jbowens, and @sumeerbhola)

___
*[`level_iter.go` line 960 at r4](https://reviewable.io/reviews/cockroachdb/pebble/2123#-NGr1SIVCdxvRzE3LsHT:-NGrvVwQ9DNQE-X2VWC9:b-btd1i3) ([raw file](https://github.com/cockroachdb/pebble/blob/7ca96e072eb586d3f97993337fa322059be4cbfb/level_iter.go#L960)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I went and reread https://github.com/cockroachdb/pebble/issues/1725#issuecomment-1139741524. Is the improvement you are suggesting changing the bullet "Pausing when reach a file bound that is a rangedel: mergingIter skips these keys since it ignores based on InternalKeyKindRangeDelete"?

btw, while we are here I think we should improve the commentary around `isSyntheticIterBoundsKey` and `isIgnorableBoundaryKey`. I tend to forget why both concepts are needed, and maybe others do too.
My understanding is that the former (a) plays a role in switching directions that needs it to be a separate concept (but the details for that I have forgotten), (b) allows for stating an invariant for the whole mergingIter when the synthetic key is at the top, since the bounds that are reached apply to the whole iterator heap (in comparison `isIgnorableBoundaryKey` is a local pause for a level). (b) is why we can break here https://github.com/cockroachdb/pebble/blob/1bda21f14fc2d77b95097edab4869e768c56f5a6/merging_iter.go#L687-L688 while we can't do so for `isIgnorableBoundaryKey`
</blockquote></details>

@jbowens made the change, PTAL!

**Review by jbowens — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2123#-:-NGygYfy0VuxOArS9kC9:bg7igkv)* status: 0 of 10 files reviewed, 2 unresolved discussions (waiting on @itsbilal and @sumeerbhola)

**Review by jbowens — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2123#-:-NGygffi77EiKHOd_XPT:bnfp4nl)* status: 0 of 10 files reviewed, 2 unresolved discussions (waiting on @itsbilal and @sumeerbhola)

**Comment by itsbilal** [comment]
TFTR @jbowens ! 

Should we backport the first commit to 22.2? I think we should.

**Review by sumeerbhola — COMMENTED** [review]
> Reviewed 1 of 4 files at r2, 1 of 4 files at r4, 1 of 1 files at r5, 6 of 7 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2123)* status: all files reviewed, 3 unresolved discussions

___
*[`merging_iter.go` line 736 at r7](https://reviewable.io/reviews/cockroachdb/pebble/2123#-NH0-A2S4nvqxISBE1mS:-NH0-A2S4nvqxISBE1mT:bc5ku3k) ([raw file](https://github.com/cockroachdb/pebble/blob/7b30bd86ff65c3edadda1fea4f1f34f1106193aa/merging_iter.go#L736)):*
> ```Go
> 		if item.key.Visible(m.snapshot, m.batchSnapshot) &&
> 			(!m.levels[item.index].isIgnorableBoundaryKey) &&
> 			(item.key.Kind() != InternalKeyKindRangeDelete || !m.elideRangeTombstones) {
> ```

liking the simplification!

**Pull request merged**
