### PR TITLE
objstorage: use provider in table cache, ingest link-or-copy

### PR DESCRIPTION
**Pull request by RaduBerinde**
~Ignore the first commit, it is #2267.~

#### pebble: add a test for fatal message when table cache hits "no such file"

The `tableCacheValue.filename` field is used to generate a useful
fatal message if the table cache hits a "no such file" error. This
change adds a test for this (currently, no tests fail if we don't set
`filename` at all).

#### objstorage: use provider in table cache

We now create the `objstorage.Provider` when we `Open` and the table
cache code uses only the provider.

#### objstorage: add link-or-copy functionality

Introduce a `LinkOrCopyFromLocal` method on `Provider` and use it for
ingestion.

### CODE REVIEW

**Comment by RaduBerinde** [comment]
This is ready for review.

**Review by jbowens — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 10 of 10 files at r2, 4 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2277#-:-NNDLunF0wGDGoYZTj4J:bnfp4nl)* status: 12 of 13 files reviewed, 1 unresolved discussion (waiting on @itsbilal and @RaduBerinde)

___
*[`vfs/syncing_file.go` line 212 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2277#-NNDKX6f2UxAYpdSDfdG:-NNDKX6f2UxAYpdSDfdH:b-yfybcx) ([raw file](https://github.com/cockroachdb/pebble/blob/914fbc08c7194f67bac23d6fee4883ea84d7ff0b/vfs/syncing_file.go#L212)):*
> ```Go
> 	}
> 	return NewSyncingFile(f, fs.syncOpts), nil
> }
> ```

nit: None of the `NewSyncingFS` call sites use it, but `FS.ReuseForWrite` can also open a file for writing. I think it'd be worthwhile to be extra explicit in the `NewSyncingFS` comment that only files returned by `Create` will be wrapped with `NewSyncingFile`. That, or implement `ReuseForWrite` with wrapping.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2277)* status: 12 of 13 files reviewed, 1 unresolved discussion (waiting on @itsbilal and @jbowens)

___
*[`vfs/syncing_file.go` line 212 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2277#-NNDKX6f2UxAYpdSDfdG:-NNDN31PCY6PQWfyzxAn:b-fhxfmy) ([raw file](https://github.com/cockroachdb/pebble/blob/914fbc08c7194f67bac23d6fee4883ea84d7ff0b/vfs/syncing_file.go#L212)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

nit: None of the `NewSyncingFS` call sites use it, but `FS.ReuseForWrite` can also open a file for writing. I think it'd be worthwhile to be extra explicit in the `NewSyncingFS` comment that only files returned by `Create` will be wrapped with `NewSyncingFile`. That, or implement `ReuseForWrite` with wrapping. 
</blockquote></details>

I added a ReuseForWrite implementation that panics.

**Comment by RaduBerinde** [comment]
TFTR!

**Pull request merged**
