### PR TITLE
sstable: skip readahead ramp-up for compactions

### LINKED ISSUE #854: perf: Have compaction sstable readers skip readahead ramp up
Currently, as of #817, the readahead code in `sstable.singleLevelIterator` and `sstable.Reader` has some ramp-up logic that checks for a sequential access pattern and gradually increases readahead sizes until a max is reached. After that, if the sequential access pattern continues, the file descriptor has `fadvise(FADV_SEQUENTIAL)` called on it to let the OS handle readahead.

As a sequential access pattern for data blocks is all but guaranteed with compaction iterators, we can skip the ramp-up phase and jump straight to creating a file descriptor with `FADV_SEQUENTIAL` called on it. This should speed up compactions, especially on IOPS-constrained devices like EBS volumes.

### PR DESCRIPTION
**Pull request by aadityasondhi**
Previously, sstable.reader was performing readahead ramp-up for reads.
Given that compactions always read entire input files, the ramp-up
can be skipped to reduce disk read ops.

This change adds additional setup for compactions, which lets the reader
skip the readahead ramp-up by setting the `sequentialFile` parameter of
the iterator.

Fixes #854.

### CODE REVIEW

**Review by itsbilal — APPROVED** [review]
:lgtm: but I paired with @aadityasondhi on this, so it would be a better idea to have someone else do a review too.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/957#-:-MIaFXCaClYrsnDAmK4h:b-iwjeeo)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jbowens)

**Review by petermattis — APPROVED** [review]
The code :lgtm: but perhaps there should be some simple test or verification in an existing test that both single-level and two-level compaction iterators have read-ahead enabled. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/957#-:-MIaR3RQ6b3Z1UPJ50fM:b-p7mo4e)* status: all files reviewed, 1 unresolved discussion (waiting on @aadityasondhi and @jbowens)

___
*[sstable/reader.go, line 171 at r1](https://reviewable.io/reviews/cockroachdb/pebble/957#-MIaQhf78-yEvfX2KwFq:-MIaQhf83skrp8xu9oPx:byvfzux) ([raw file](https://github.com/cockroachdb/pebble/blob/2d5e477119bfe33ef1493a5e3877480f8292d7d1/sstable/reader.go#L171)):*
> ```Go
> 		f, err := i.reader.fs.Open(i.reader.filename, vfs.SequentialReadsOption)
> 		if err == nil {
> 			// Given that this is for a compaction, we can assume that it will be
> ```

Nit: `s/this is/this iterator is/g`

**Review by petermattis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/957#-:-MJ2E1mt-QuA3DD9Vc9G:bnfp4nl)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @aadityasondhi, @itsbilal, @jbowens, and @petermattis)

___
*[sstable/reader_test.go, line 467 at r2](https://reviewable.io/reviews/cockroachdb/pebble/957#-MJ2DaJL-e4rsVwpuJp7:-MJ2DaJL-e4rsVwpuJp8:buc19vc) ([raw file](https://github.com/cockroachdb/pebble/blob/1c5476cef5ff27820ecac38e35ee49869a430b31/sstable/reader_test.go#L467)):*
> ```Go
> 				citer, err := r.NewCompactionIter(&bytesIterated)
> 				require.NoError(t, err)
> 				if iter, ok := citer.(*compactionIterator); ok {
> ```

I think this would be mildly cleaner as a type switch:

```
switch i := citer.(type) {
case *compactionIterator:
  require.NotNil(t, i.dataRS.sequentialFile)
case *twoLevelCompactionIterator:
  require.NotNil(t, i.dataRS.sequentialFile)
default:
  require.Failf(t, "unknown compaction iterator type: %T", citer)
}
```

**Review by aadityasondhi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/957)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @itsbilal, @jbowens, and @petermattis)

___
*[sstable/reader_test.go, line 467 at r2](https://reviewable.io/reviews/cockroachdb/pebble/957#-MJ2DaJL-e4rsVwpuJp7:-MJ2SFQyAE9u06UWJI0v:b-u6dbq2) ([raw file](https://github.com/cockroachdb/pebble/blob/1c5476cef5ff27820ecac38e35ee49869a430b31/sstable/reader_test.go#L467)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I think this would be mildly cleaner as a type switch:

```
switch i := citer.(type) {
case *compactionIterator:
  require.NotNil(t, i.dataRS.sequentialFile)
case *twoLevelCompactionIterator:
  require.NotNil(t, i.dataRS.sequentialFile)
default:
  require.Failf(t, "unknown compaction iterator type: %T", citer)
}
```
</blockquote></details>

Thanks, made the change.

**Pull request merged**
