### PR TITLE
internal/keyspan: correct and document MergingIter key stability

### LINKED ISSUE #1663: keyspan: merging iter's span bounds can change when child iter is repositioned
Currently, the `keyspan.MergingIter` assumes that spans returned by child iters are stable. It relies on this assumption when storing the start key.

https://github.com/cockroachdb/pebble/blob/d8ca1fc6fddd196d72c5a5e77ce005cd8cbf742a/internal/keyspan/merging_iter.go#L530-L549

 #1662 diverges from this assumption where a `DefragmentingIter` is wrapped by a `MergingIter`. As the defragmenting iter returns Spans that are only valid until the next positioning method, when the `MergingIter` pulls from the heap to find the end key, the `DefragmentingIter` can be repositioned, causing the start key to be updated.

Full reproduction:

```go
package pebble

import (
	"bytes"
	"strings"
	"testing"

	"github.com/cockroachdb/pebble/internal/base"
	"github.com/cockroachdb/pebble/internal/keyspan"
	"github.com/cockroachdb/pebble/internal/testkeys"
	"github.com/cockroachdb/pebble/sstable"
	"github.com/cockroachdb/pebble/vfs"
	"github.com/stretchr/testify/require"
)

func Test(t *testing.T) {
	equal := func(_ base.Compare, a, b keyspan.Span) bool { return true }
	transform := func(cmp base.Compare, in keyspan.Span, out *keyspan.Span) error {
		out.Start, out.End = in.Start, in.End
		out.Keys = append(out.Keys[:0], in.Keys...)
		return nil
	}

	var keys = []string{
		"a b",
		"b c",
		"c d",
		"x y",
		"y z",
	}

	// Create a table.
	fs := vfs.NewMem()
	f, err := fs.Create("test.sst")
	require.NoError(t, err)
	w := sstable.NewWriter(f, sstable.WriterOptions{TableFormat: sstable.TableFormatMax})

	for _, k := range keys {
		parts := strings.Split(k, " ")
		start, end := []byte(parts[0]), []byte(parts[1])
		err = w.Add(base.MakeInternalKey(start, 0, base.InternalKeyKindRangeDelete), end)
		require.NoError(t, err)
	}
	err = w.Close()
	require.NoError(t, err)

	// Construct an iterator over range keys in the table.
	f, err = fs.Open("test.sst")
	require.NoError(t, err)
	r, err := sstable.NewReader(f, sstable.ReaderOptions{})
	require.NoError(t, err)

	iter, err := r.NewRawRangeDelIter()
	require.NoError(t, err)

	cmp := testkeys.Comparer.Compare
	dIter := &keyspan.DefragmentingIter{}
	dIter.Init(cmp, iter, equal, keyspan.StaticDefragmentReducer)
	iter = dIter

	_ = transform
	// Using a merging iter results in a panic.
	//mIter := &keyspan.MergingIter{}
	//mIter.Init(cmp, transform, iter)
	//iter = mIter

	var b bytes.Buffer
	for s := iter.First(); s.Valid(); s = iter.Next() {
		b.WriteString(s.String() + "\n")
	}
	err = iter.Close()
	require.NoError(t, err)

	const want = `
a-d:{(#0,RANGEDEL)}
x-z:{(#0,RANGEDEL)}
`
	require.Equal(t, strings.TrimSpace(want), strings.TrimSpace(b.String()))
}
```

```shell
$ go test -tags invariants -run Test$ .
```

### PR DESCRIPTION
**Pull request by jbowens**
**internal/keyspan: collapse fragmentBoundIterator into MergingIter**

Remove the fragmentBoundIterator type, instead collapsing the
fragmentBoundIterator's boundary logic into the MergingIter and its
mergingIterLevel types. This is helpful in the subsequent commit where the
MergingIter requires direct knowledge of when the child FragmentIterator will
be stepped to the next Span.

**internal/keyspan: correct and document MergingIter key stability**

Fix an issue where MergingIter sometimes depended on stability of a child
iterator Span's start or end boundary beyond the next positioning call on the
iterator.

Fix #1663.

### CODE REVIEW

**Review by jbowens — COMMENTED** [review]
The metamorphic tests fail on this branch because compactions currently depend on _total_ key stability of spans surfaced by `MergingIter`, which this does not implement. I'm going to dig a little deeper for an alternative structure that avoids any copying at all. I believe it's possible, it's just more work to step the heap correctly.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1664#-:-N0D2Fkc8vxDj9ondG2i:bhmztkk)* status: 0 of 6 files reviewed, all discussions resolved

**Review by nicktrav — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1664)* status: all files reviewed, 4 unresolved discussions (waiting on @jbowens)

___
*[internal/keyspan/merging_iter.go, line 78 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1664#-N0Cz0mg0x3to5nhtvbM:-N0Cz0mg0x3to5nhtvbN:blke6fg) ([raw file](https://github.com/cockroachdb/pebble/blob/c2c351b6b234f12635595244ebddf918ecc0f554/internal/keyspan/merging_iter.go#L78)):*
> ```Go
> // Each level (i0, i1, ...) has a user-provided input FragmentIterator. The
> // merging iterator steps through individual boundaries of the underlying
> // fspans separately. If the underlying FragmentIterator has fragments
> ```

typo: "fspans"
___
*[internal/keyspan/merging_iter.go, line 581 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1664#-N0D0QHx94Mly3pW_C-Q:-N0D0QHx94Mly3pW_C-R:blw6tdu) ([raw file](https://github.com/cockroachdb/pebble/blob/c2c351b6b234f12635595244ebddf918ecc0f554/internal/keyspan/merging_iter.go#L581)):*
> ```Go
> 		// boundary, then we need to copy the start key before advancing the
> 		// underlying iterator to the next Span.
> 		if m.heap.items[0].boundKey.kind == boundKindFragmentEnd {
> ```

nit: could use `m.start` here instead? Same comment for the reverse iteration case.
___
*[internal/keyspan/merging_iter.go, line 582 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1664#-N0D-QDS3rztAOpIlR-o:-N0D-QDT0X43VK54FbJg:bb5iy2) ([raw file](https://github.com/cockroachdb/pebble/blob/c2c351b6b234f12635595244ebddf918ecc0f554/internal/keyspan/merging_iter.go#L582)):*
> ```Go
> 		// underlying iterator to the next Span.
> 		if m.heap.items[0].boundKey.kind == boundKindFragmentEnd {
> 			m.buf = append(m.buf[:0], m.start...)
> ```

I wonder if this is going to end up showing up as a hotspot in the benchmarking. I don't have any good suggestions - maybe it's just unavoidable :/

edit: I just saw your comment about the tests failing. Disregard.
___
*[internal/keyspan/iter_test.go, line 102 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1664#-N0D2Hfc38RsFVL0ynOO:-N0D2Hfc38RsFVL0ynOP:b-83sjo4) ([raw file](https://github.com/cockroachdb/pebble/blob/c2c351b6b234f12635595244ebddf918ecc0f554/internal/keyspan/iter_test.go#L102)):*
> ```Go
> // zeroed by sbubsequent iterator positioning calls. This is intended to help
> // surface bugs in improper lifetime expectations of Spans.
> type invalidatingIter struct {
> ```

Nice.

**Review by jbowens — COMMENTED** [review]
We're in a bit of an awkward pickle right now. Compactions requires total key stability of spans and their keys for range deletions. We should eventually be able to lift that requirement, but not until 23.1. User iteration only requires key stability until the next op.

I added an awkward hack to make this behavior configurable by passing a `KeyStability` enum for now, but I'm open to alternatives. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1664#-:-N0DJ3Vf12XgV6ve-y2U:bie0jrj)* status: 4 of 12 files reviewed, 2 unresolved discussions (waiting on @nicktrav)

___
*[internal/keyspan/merging_iter.go, line 581 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1664#-N0D0QHx94Mly3pW_C-Q:-N0DIHDm52DVPfKFXpPw:bk5cnxz) ([raw file](https://github.com/cockroachdb/pebble/blob/c2c351b6b234f12635595244ebddf918ecc0f554/internal/keyspan/merging_iter.go#L581)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

nit: could use `m.start` here instead? Same comment for the reverse iteration case.
</blockquote></details>

`m.start` is just the byte slice without access to the kind
___
*[internal/keyspan/merging_iter.go, line 582 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1664#-N0D-QDS3rztAOpIlR-o:-N0DIQX8CfEMvLsuKPNV:bxeqfc2) ([raw file](https://github.com/cockroachdb/pebble/blob/c2c351b6b234f12635595244ebddf918ecc0f554/internal/keyspan/merging_iter.go#L582)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

I wonder if this is going to end up showing up as a hotspot in the benchmarking. I don't have any good suggestions - maybe it's just unavoidable :/

edit: I just saw your comment about the tests failing. Disregard.
</blockquote></details>

Unfortunately, that didn't pan out and this seems unavoidable. I'm not too worried about this particular key-copy right now, because we already perform a bunch of key copies across the range key iterator stack (eg, defragmenting iter, saving range keys in `Iterator.saveRangeKey`, etc). I think it will likely be helpful to remove as many of them as we reasonably can.

**Review by nicktrav — COMMENTED** [review]
> The metamorphic tests fail on this branch because compactions currently depend on total key stability of spans surfaced by MergingIter, which this does not implement.

Just to make sure I'm understanding this part - _prior_ to this change, there is no mutation of keys slices, as we're not wrapping an iterator that mutates slices for keys (the _defragmenting_ iter reuses slices, and that's where things are getting fouled up). However, if we make the change here to reuse slices in the _merging iter_ to solve the issue in #1663, we're just pushing that instability up into this iter, which will then foul up things elsewhere that rely on stability for the duration the iterator's lifetime. A pickle indeed! Hopefully I got that right.

A thought - given that the contract of the `FragmentIter` is stated as:

```
// A Span returned by a FragmentIterator is only valid until the next
// positioning method. Some implementations (eg, keyspan.Iter) may provide
// longer lifetimes but implementations need only guarantee stability until the
// next positioning method.
```

I wonder if an alternative would be to adapt the call sites where we use keys returned by a `FragmentIter` _and_ rely on longer lifetimes to do the key copies, as they are the one's asking for a "stronger guarantee"? I think that would prevent having to worry about lugging around the `KeyStability`.

The other advantage to inverting the dependency is that those call sites are, iiuc, limited only to situations where we're handling range dels catering for the pre-split user keys scenario (i.e. range keys will not have this issue)? And this situation should clean up nicely for range dels in 23.1, as you mention.

Thoughts?

> Reviewed 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1664#-:-N0DRpb1EjSL6xkhVudm:b8w5rm8)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jbowens)

___
*[internal/keyspan/merging_iter.go, line 581 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1664#-N0D0QHx94Mly3pW_C-Q:-N0DOW914Rdt2fhJByL4:btmv6n5) ([raw file](https://github.com/cockroachdb/pebble/blob/c2c351b6b234f12635595244ebddf918ecc0f554/internal/keyspan/merging_iter.go#L581)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

`m.start` is just the byte slice without access to the kind
</blockquote></details>

Woops. Mistook `key` and `kind`.

**Review by jbowens — COMMENTED** [review]
Yeah, that's right, and placing the burden on the caller is okay by me. We should make sure we benchmark range deletions (and range keys) in compactions before 22.2 release, and finish off the TODO to prevent the clone if necessary.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1664#-:-N0gsBYgEiTmAt_nPKcQ:b-th02bv)* status: 3 of 14 files reviewed, all discussions resolved (waiting on @nicktrav)

**Review by nicktrav — APPROVED** [review]
Nice. This feels like a decent compromise for now. :lgtm:

> Reviewed 11 of 11 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1664#-:-N0h4ksI7ZlVB05WBNEn:b-mnslq1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jbowens)

**Review by jbowens — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1664#-:-N0hYpCe52gwunTQ6-3v:b-814g8k)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jbowens)

**Pull request merged**
