### PR TITLE
cmd/pebble: avoid bursts in `pebble bench write`

### PR DESCRIPTION
**Pull request by nicktrav**
Currently, each goroutine driving load as part of the `pebble bench
write` benchmark is configured with a burst of `incBase`, which by
default is 100. In aggregate, when multiplied by the number of
goroutines (typically 1024), large bursts occur when the test has been
in the cooldown period and not driving load (i.e. all goroutines idle).

Reduce the configured burst value for each rate limiter to the minimum
value to avoid excessive bursting.

### CODE REVIEW

**Review by sumeerbhola — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1355)* status: all files reviewed, 1 unresolved discussion (waiting on @nicktrav)

___
*[cmd/pebble/write_bench.go, line 388 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1355#-Mn2k-nM7sNtb9H1SrZ6:-MnCoQcs7kJCtd707CmM:b-pifxnj) ([raw file](https://github.com/cockroachdb/pebble/blob/2484ff058cdb753611b8badb42590197cb459a7a/cmd/pebble/write_bench.go#L388)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

Setting the burst value to `0` seemed to disable the rate limiter entirely.
</blockquote></details>

I think `burst` is also the initial and maximum number of tokens in the bucket. Even using 1 may not be great depending on how the code is written (if it is ticking at a fixed interval and overflowing)  -- I've forgotten the code details so I'd recommend reading it to satisfy yourself that is doing something reasonable.

**Review by nicktrav — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1355)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @sumeerbhola)

___
*[cmd/pebble/write_bench.go, line 388 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1355#-Mn2k-nM7sNtb9H1SrZ6:-MnS7tQuAFtb1i8eXi-y:b-clvqdt) ([raw file](https://github.com/cockroachdb/pebble/blob/2484ff058cdb753611b8badb42590197cb459a7a/cmd/pebble/write_bench.go#L388)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I think `burst` is also the initial and maximum number of tokens in the bucket. Even using 1 may not be great depending on how the code is written (if it is ticking at a fixed interval and overflowing)  -- I've forgotten the code details so I'd recommend reading it to satisfy yourself that is doing something reasonable.
</blockquote></details>

I did another read through, and I think what we have here is ok. Ideally, a zero burst would mean precisely that, but it looks like the implementation returns `+Inf`, and that return value is relied upon in various places.

The current value of `1` does still allow for a little bit of overshoot when ramping from zero with many goroutines, but within a second we're back at the desired value, and when calculated as a percentage of an ops / sec figure of O(10^3), it's fairly inconsequential.

I added a comment.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1355#-:-MnT1LSp2brAWIQBmCmh:bg7igkv)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @nicktrav)

**Comment by nicktrav** [comment]
TFTR!

**Pull request merged**
