### PR TITLE
Metamorphic test

### PR DESCRIPTION
**Pull request by petermattis**
Randomly generate a sequence of operations, and then replay this
sequence repeatedly with random options, flushes, and compactions,
verifying the test history is the same on each run.

The output from running a sequence of operations is recored in a
`history`. The format of this output looks similar to Go code. The
operations themselves look like method invocations. The results from an
operation are recorded in comments. Event logs from Pebble are also
recorded in comments. This output can be parsed to regenerate the
sequence of ops that led to a failure or discrepancy between runs.

### CODE REVIEW

**Comment by petermattis** [comment]
This change is [Reviewable](https://reviewable.io/reviews/petermattis/pebble/126)

**Comment by ajkr** [comment]
Is there a plan to verify baseline correctness? For example we could implement the DB interface using `std::map` equivalent in Go to get the first test history and compare against that. Also I wonder how we can test parallel operations since the sequence of operations will presumably need to be replayed in order. Also crash-recovery will need correctness testing.

**Comment by petermattis** [comment]
(I really need to finish off this PR)

> Is there a plan to verify baseline correctness? For example we could implement the DB interface using std::map equivalent in Go to get the first test history and compare against that. 

My plan was to side-step verifying baseline correctness by instead only verifying equivalence of the output of two runs. If there is any divergence we'd have to investigate to determine which is correct. The thinking here is that this will catch discrepancies in implementation between the various implementations of equivalent functionality, such as memtable iterators vs sstable iterators vs indexed batch interators vs flushable batch iterators. That's just one example. I think there are many.

Verifying baseline correctness is hard because the model of a DB is more than just a std::map due to the presence of snapshots and multiple versions. Not impossible, but something I was hoping to side-step in the work here (at least initially). 

> Also I wonder how we can test parallel operations since the sequence of operations will presumably need to be replayed in order. Also crash-recovery will need correctness testing.

I think crash-recovery is possible. There just has to be a fairly clear line for when the crash occurs. Parallel operations seem possible if the operations touch distinct keys.

**Comment by petermattis** [comment]
CI is green and approval is given. I'm going to merge this beast. It definitely isn't "finished", but it is useful and usable.

**Pull request merged**
