### PR TITLE
sstable: adapt EstimateDiskUsage to be agnostic to index block impl

### PR DESCRIPTION
**Pull request by jbowens**
Adapt Reader.EstimateDiskUsage to be generic over the index block iterator type.

### CODE REVIEW

**Review by jbowens — COMMENTED** [review]
bumpin' that

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3890#-:-O5tbvyh6tS8DRF1sI7w:b-85a38g)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @RaduBerinde)

**Review by jbowens — COMMENTED** [review]
friendly ping!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3890#-:-O61dvjDCA3301TwxPv5:b-dmo58h)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @RaduBerinde)

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3890#-:-O63MYloBpgp3zcfEzYc:bg7igkv)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @jbowens and @RaduBerinde)

___
*[`sstable/reader.go` line 841 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3890#-O63M9moEfBIf3n21bP6:-O63M9moEfBIf3n21bP7:bb17ezo) ([raw file](https://github.com/cockroachdb/pebble/blob/9cc543eecc6020068be616059f7d0d90f39639a7/sstable/reader.go#L841)):*
> ```Go
> 	if !startIdxIter.SeekGE(start) {
> 		// The range falls completely after this file, or an error occurred.
> 		return 0, nil
> ```

why is the error being swallowed here? Doesn't seem to be an `Error() error` method in `IndexBlockIterator` which seems odd.
___
*[`sstable/reader.go` line 866 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3890#-O63MSZY7ss46NQd6XPl:-O63MSZY7ss46NQd6XPm:b-42ccbs) ([raw file](https://github.com/cockroachdb/pebble/blob/9cc543eecc6020068be616059f7d0d90f39639a7/sstable/reader.go#L866)):*
> ```Go
> 		return includeInterpolatedValueBlocksSize(r.Properties.DataSize - startBH.Offset), nil
> 	}
> 	if !endIdxIter.SeekGE(end) {
> ```

the error handling code is removed here too.

**Review by jbowens — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3890#-:-O6759Dk9I652Edognsc:b-814g8k)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @RaduBerinde and @sumeerbhola)

___
*[`sstable/reader.go` line 841 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3890#-O63M9moEfBIf3n21bP6:-O674kwz95Ra_jV-87Ux:b-5rihjt) ([raw file](https://github.com/cockroachdb/pebble/blob/9cc543eecc6020068be616059f7d0d90f39639a7/sstable/reader.go#L841)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

why is the error being swallowed here? Doesn't seem to be an `Error() error` method in `IndexBlockIterator` which seems odd.
</blockquote></details>

Updated the comment to remove "or an error occurred." Both implementations of IndexBlockIterator are 'infallible' during seeks. The only errors that can occur are a) during initialization and handled above by Init, and b) when decoding the value as a block handle, which is handled explicitly down below.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3890#-:-O68OTQE6ZMxJoAB18an:bg7igkv)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @jbowens and @RaduBerinde)

**Comment by jbowens** [comment]
tftr!

**Pull request merged**
