### PR TITLE
iterator: read sampling for keys on file boundary

### LINKED ISSUE #1029: compaction: read sampling skips files if located at the file boundary
This was an edge case pointed out in https://github.com/cockroachdb/pebble/pull/1009.

For Iterator.Last(), Iterator.SeekLT() and Iterator.Prev(), if the key is the first key of the file or the only key, sampling skips it because the iterator has already moved past it. The solution would be to check for this, and then seek to the correct file to sample it. This could have a performance impact which needs to be tested in benchmarks.

### PR DESCRIPTION
**Pull request by itsbilal**
This PR subsumes #1031, but makes it sublevels-aware by going with a different approach
to find the right file: namely, cloning the levelIter's files `LevelIterator`, and then positioning that
in the opposite direction of the iterators position. First commit is identical to that PR, and the
second commit is the `iter.Clone` change. Description copied below.

----

Previously, for Iterator.Last(), Iterator.SeekLT() and Iterator.Prev(),
if a key was the first key or the only key in the file, sampling would
skip it as the iterator would have moved past it.

This change checks for both an invalid iterator and an iterator pointing
to the wrong file. It then seeks to the correct file if necessary based
on the direction of `mergingiter`. The tests have been fixed to reflect
this new behavior.

Fixes #1029.

### CODE REVIEW

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 1 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1041)* status: 1 of 5 files reviewed, 3 unresolved discussions (waiting on @itsbilal, @jbowens, @petermattis, and @sumeerbhola)

___
*[iterator.go, line 218 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1041#-MQP_Ea6EUq5uyHjo6a-:-MQP_Ea6EUq5uyHjo6a0:b-hc2eh1) ([raw file](https://github.com/cockroachdb/pebble/blob/f3a26c19a0a4d69fa65820c52d92ffce0dc3ad62/iterator.go#L218)):*
> ```Go
> 					}
> 				}
> 				if !containsKey && (i.pos == iterPosNext || i.pos == iterPosPrev) {
> ```

Do we need to do this for both iterator directions? The TODO suggested it is only for reverse iteration. I may be forgetting something -- can `iterPosNext` also happen in reverse iteration?

I suspect it is likely to have no file overlapping with `i.key` in certain levels, and here we would wastefully search in the `btree`. Do we know the peformance implications of doing this?
___
*[iterator.go, line 234 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1041#-MQPZ6aeDH9TX9eQxftR:-MQPZ6aeDH9TX9eQxftS:b-rjsai6) ([raw file](https://github.com/cockroachdb/pebble/blob/f614b5ad0faa88f794548581b80ad05f99e044ba/iterator.go#L234)):*
> ```Go
> 			})
> 		}
> 	}
> ```

I am missing something when reading the existing logic. Why do we need `readSampling.topFile`? And where do we write to it?
It seems none of the following matters unless `numOverlappingLevels >= 2` in which case we will have initialized `topLevel` and `topFile` -- so why we do need this `if topFile == nil ...` block?
___
*[iterator.go, line 247 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1041#-MQPcg3K2rhv-SE5M8U8:-MQPcg3K2rhv-SE5M8U9:be6jjr3) ([raw file](https://github.com/cockroachdb/pebble/blob/a0918659623fd5d217d56d2f3a234533b05d7ebb/iterator.go#L247)):*
> ```Go
> 				start: topFile.Smallest.UserKey,
> 				end:   topFile.Largest.UserKey,
> 				level: topLevel,
> ```

When an L0 sub-level file gets picked here, the actual L0 compaction will go bottom up in the sub-levels in accumulating the files to compact, so the actual `topFile` may not get compacted, yes? This is not necessarily harmful, but it is not something that is intuitively obvious, so would be worth a comment here.

**Review by itsbilal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1041)* status: 1 of 5 files reviewed, 3 unresolved discussions (waiting on @jbowens, @petermattis, and @sumeerbhola)

___
*[iterator.go, line 218 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1041#-MQP_Ea6EUq5uyHjo6a-:-MQTXwOH7G2mYbWOPrOy:b83nd6k) ([raw file](https://github.com/cockroachdb/pebble/blob/f3a26c19a0a4d69fa65820c52d92ffce0dc3ad62/iterator.go#L218)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Do we need to do this for both iterator directions? The TODO suggested it is only for reverse iteration. I may be forgetting something -- can `iterPosNext` also happen in reverse iteration?

I suspect it is likely to have no file overlapping with `i.key` in certain levels, and here we would wastefully search in the `btree`. Do we know the peformance implications of doing this?
</blockquote></details>

Yep, the TODO was slightly inaccurate; it's also possible with forward iteration (which will always have iterPosNext/iterPosCurForward) and MERGEs. The test cases include one example of that. I do expect it to be mostly iterPosCurForward instead of iterPosNext for usual forward iteration, which will probably mask the performance hit of this, but we don't want reverse iteration to be significantly less efficient than forward iteration either.

I'm in the midst of measuring performance implications of this, but yeah I do see the issue with doing a btree seek in all cases. It might be more efficient to do an `li.files.Clone().{opposite-direction-of-i.pos}` than to do a seek in the btree. The results from that experimentation will guide the way this code goes.
___
*[iterator.go, line 234 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1041#-MQPZ6aeDH9TX9eQxftR:-MQTmFfb1bjVAz2xRwL8:b-pugh8s) ([raw file](https://github.com/cockroachdb/pebble/blob/f614b5ad0faa88f794548581b80ad05f99e044ba/iterator.go#L234)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I am missing something when reading the existing logic. Why do we need `readSampling.topFile`? And where do we write to it?
It seems none of the following matters unless `numOverlappingLevels >= 2` in which case we will have initialized `topLevel` and `topFile` -- so why we do need this `if topFile == nil ...` block?
</blockquote></details>

We just save the bounds of the top file instead of storing a reference to it. And yes this if statement is likely unnecessary.
___
*[iterator.go, line 247 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1041#-MQPcg3K2rhv-SE5M8U8:-MQTmS6N8rLLunPgN6g_:b-jc36jw) ([raw file](https://github.com/cockroachdb/pebble/blob/a0918659623fd5d217d56d2f3a234533b05d7ebb/iterator.go#L247)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

When an L0 sub-level file gets picked here, the actual L0 compaction will go bottom up in the sub-levels in accumulating the files to compact, so the actual `topFile` may not get compacted, yes? This is not necessarily harmful, but it is not something that is intuitively obvious, so would be worth a comment here.
</blockquote></details>

So read compaction picking doesn't actually go through L0SubLevels.PickBaseCompaction, instead it just directly calls `Overlaps` on the range (see `pickReadTriggeredCompactionHelper`). Maybe we should add a `seedFile` parameter to `pickL0` and use the sublevel logic, but we didn't expect the difference to matter that much for read compactions.

**Comment by itsbilal** [comment]
___
*[iterator.go, line 247 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1041#-MQPcg3K2rhv-SE5M8U8:-MQToWSY5wexGm7quCtc:b-emf000) ([raw file](https://github.com/cockroachdb/pebble/blob/a0918659623fd5d217d56d2f3a234533b05d7ebb/iterator.go#L247)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

So read compaction picking doesn't actually go through L0SubLevels.PickBaseCompaction, instead it just directly calls `Overlaps` on the range (see `pickReadTriggeredCompactionHelper`). Maybe we should add a `seedFile` parameter to `pickL0` and use the sublevel logic, but we didn't expect the difference to matter that much for read compactions.
</blockquote></details>

Correction, it would likely be `seedRange` more than `seedFile`, for the same reason as before, can't hold onto file references between readers and compaction-picking.

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1041)* status: 1 of 5 files reviewed, 3 unresolved discussions (waiting on @itsbilal, @jbowens, and @petermattis)

___
*[iterator.go, line 218 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1041#-MQP_Ea6EUq5uyHjo6a-:-MQYgm-P4OgbkgrHB9Pb:b-hxks7g) ([raw file](https://github.com/cockroachdb/pebble/blob/f3a26c19a0a4d69fa65820c52d92ffce0dc3ad62/iterator.go#L218)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Yep, the TODO was slightly inaccurate; it's also possible with forward iteration (which will always have iterPosNext/iterPosCurForward) and MERGEs. The test cases include one example of that. I do expect it to be mostly iterPosCurForward instead of iterPosNext for usual forward iteration, which will probably mask the performance hit of this, but we don't want reverse iteration to be significantly less efficient than forward iteration either.

I'm in the midst of measuring performance implications of this, but yeah I do see the issue with doing a btree seek in all cases. It might be more efficient to do an `li.files.Clone().{opposite-direction-of-i.pos}` than to do a seek in the btree. The results from that experimentation will guide the way this code goes.
</blockquote></details>

I don't remember how expensive `Clone()` is, but if that is costly we could just meddle with the existing `levelIter.Files` by stepping it and then restoring it to its original position. It would not be very clean, but this is Go and we are all one happy package :)
___
*[iterator.go, line 234 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1041#-MQPZ6aeDH9TX9eQxftR:-MQYezfD4mRrWvLZU6mU:b-vd56i9) ([raw file](https://github.com/cockroachdb/pebble/blob/f614b5ad0faa88f794548581b80ad05f99e044ba/iterator.go#L234)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

We just save the bounds of the top file instead of storing a reference to it. And yes this if statement is likely unnecessary.
</blockquote></details>

I was also asking about the need for the `topFile` field in `readSampling`. It seems only to be read and never written to.
___
*[iterator.go, line 247 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1041#-MQPcg3K2rhv-SE5M8U8:-MQYi6tqB3mw24lXFqoC:bu88r0w) ([raw file](https://github.com/cockroachdb/pebble/blob/a0918659623fd5d217d56d2f3a234533b05d7ebb/iterator.go#L247)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Correction, it would likely be `seedRange` more than `seedFile`, for the same reason as before, can't hold onto file references between readers and compaction-picking.
</blockquote></details>

I agree -- since we already know the interval we want to compact, the sub-levels logic, which is primarily about identifying an interval (and keeping file widths narrow), shouldn't be relevant here.

**Review by itsbilal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1041)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @jbowens, @petermattis, and @sumeerbhola)

___
*[iterator.go, line 218 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1041#-MQP_Ea6EUq5uyHjo6a-:-MQo-RohBHsIGDyMuHqd:b4ljc76) ([raw file](https://github.com/cockroachdb/pebble/blob/f3a26c19a0a4d69fa65820c52d92ffce0dc3ad62/iterator.go#L218)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I don't remember how expensive `Clone()` is, but if that is costly we could just meddle with the existing `levelIter.Files` by stepping it and then restoring it to its original position. It would not be very clean, but this is Go and we are all one happy package :)
</blockquote></details>

Haha, makes sense. Making a state change in an operation that's supposed to not do that (read sampling) makes me a little uneasy, but I'll try that approach too to see how much of a difference that makes. For now I've made the Clone change, as that one had no statistically significant performance differences in ycsb-* compared to the original state of this PR.

Let me try another set of runs before this change, and one with the way you suggested, to see if something significantly stands out.
___
*[iterator.go, line 234 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1041#-MQPZ6aeDH9TX9eQxftR:-MQnM_o71GxiNNWgraX8:b-j51p24) ([raw file](https://github.com/cockroachdb/pebble/blob/f614b5ad0faa88f794548581b80ad05f99e044ba/iterator.go#L234)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I was also asking about the need for the `topFile` field in `readSampling`. It seems only to be read and never written to.
</blockquote></details>

Ah right, missed that too. Removed.

**Comment by itsbilal** [comment]
The `iter.Clone` change shows no significant performance difference (base = current master):

```
name              old ops/sec  new ops/sec  delta
ycsb/A/values=64    267k ± 2%    263k ± 4%   ~     (p=0.310 n=5+5)
ycsb/B/values=64    945k ± 3%    925k ± 5%   ~     (p=0.690 n=5+5)
ycsb/C/values=64   2.19M ± 5%   2.14M ±11%   ~     (p=1.000 n=5+5)
ycsb/D/values=64    760k ± 4%    764k ± 7%   ~     (p=0.548 n=5+5)
ycsb/E/values=64    202k ± 5%    199k ± 6%   ~     (p=0.548 n=5+5)

name              old read     new read     delta
ycsb/A/values=64   72.3G ± 4%   71.1G ± 7%   ~     (p=1.000 n=5+5)
ycsb/B/values=64   50.3G ± 2%   49.4G ± 5%   ~     (p=0.690 n=5+5)
ycsb/C/values=64   3.00G ± 7%   2.88G ± 4%   ~     (p=0.151 n=5+5)
ycsb/D/values=64   48.7G ± 4%   49.0G ± 7%   ~     (p=0.548 n=5+5)
ycsb/E/values=64   18.4G ± 4%   18.1G ± 9%   ~     (p=0.690 n=5+5)

name              old write    new write    delta
ycsb/A/values=64   82.1G ± 3%   80.8G ± 7%   ~     (p=0.841 n=5+5)
ycsb/B/values=64   53.8G ± 2%   52.8G ± 5%   ~     (p=0.690 n=5+5)
ycsb/C/values=64   2.91G ± 7%   2.79G ± 4%   ~     (p=0.151 n=5+5)
ycsb/D/values=64   53.3G ± 4%   53.7G ± 7%   ~     (p=0.548 n=5+5)
ycsb/E/values=64   19.6G ± 4%   19.2G ± 9%   ~     (p=0.421 n=5+5)

name              old r-amp    new r-amp    delta
ycsb/A/values=64    4.13 ± 1%    4.17 ± 1%   ~     (p=0.286 n=5+5)
ycsb/B/values=64    3.58 ± 1%    3.53 ± 1%   ~     (p=0.087 n=5+5)
ycsb/C/values=64    1.27 ± 0%    1.29 ± 7%   ~     (p=0.635 n=5+5)
ycsb/D/values=64    4.13 ± 1%    4.12 ± 1%   ~     (p=0.897 n=5+5)
ycsb/E/values=64    2.58 ± 1%    2.58 ± 1%   ~     (p=1.000 n=5+5)

name              old w-amp    new w-amp    delta
ycsb/A/values=64    8.31 ± 3%    8.30 ± 4%   ~     (p=0.548 n=5+5)
ycsb/B/values=64    15.4 ± 1%    15.4 ± 1%   ~     (p=0.579 n=5+5)
ycsb/C/values=64    0.00         0.00        ~     (all equal)
ycsb/D/values=64    18.9 ± 1%    19.0 ± 1%   ~     (p=0.730 n=5+5)
ycsb/E/values=64    26.2 ± 2%    26.1 ± 3%   ~     (p=1.000 n=5+5)
```

If I get rid of the iter.Clone and reset the iter to its original position, there's a slight perf benefit:


```
name              old ops/sec  new ops/sec  delta
ycsb/A/values=64    267k ± 2%    267k ± 1%    ~     (p=0.841 n=5+5)
ycsb/B/values=64    945k ± 3%    991k ± 8%    ~     (p=0.151 n=5+5)
ycsb/C/values=64   2.19M ± 5%   2.28M ± 5%    ~     (p=0.222 n=5+5)
ycsb/D/values=64    760k ± 4%    802k ± 4%  +5.60%  (p=0.016 n=5+5)
ycsb/E/values=64    202k ± 5%    209k ± 3%    ~     (p=0.222 n=5+5)

name              old read     new read     delta
ycsb/A/values=64   72.3G ± 4%   74.3G ±11%    ~     (p=0.151 n=5+5)
ycsb/B/values=64   50.3G ± 2%   52.7G ± 7%    ~     (p=0.151 n=5+5)
ycsb/C/values=64   3.00G ± 7%   3.03G ± 8%    ~     (p=0.841 n=5+5)
ycsb/D/values=64   48.7G ± 4%   51.9G ± 4%  +6.77%  (p=0.016 n=5+5)
ycsb/E/values=64   18.4G ± 4%   19.1G ± 4%    ~     (p=0.151 n=5+5)

name              old write    new write    delta
ycsb/A/values=64   82.1G ± 3%   84.1G ±10%    ~     (p=0.151 n=5+5)
ycsb/B/values=64   53.8G ± 2%   56.2G ± 7%    ~     (p=0.151 n=5+5)
ycsb/C/values=64   2.91G ± 7%   2.93G ± 8%    ~     (p=0.841 n=5+5)
ycsb/D/values=64   53.3G ± 4%   56.8G ± 4%  +6.68%  (p=0.016 n=5+5)
ycsb/E/values=64   19.6G ± 4%   20.3G ± 4%    ~     (p=0.151 n=5+5)

name              old r-amp    new r-amp    delta
ycsb/A/values=64    4.13 ± 1%    4.14 ± 1%    ~     (p=1.000 n=5+5)
ycsb/B/values=64    3.58 ± 1%    3.58 ± 1%    ~     (p=1.000 n=5+5)
ycsb/C/values=64    1.27 ± 0%    1.25 ± 5%    ~     (p=1.000 n=5+4)
ycsb/D/values=64    4.13 ± 1%    4.14 ± 1%    ~     (p=0.516 n=5+5)
ycsb/E/values=64    2.58 ± 1%    2.60 ± 2%    ~     (p=0.484 n=5+5)

name              old w-amp    new w-amp    delta
ycsb/A/values=64    8.31 ± 3%    8.50 ± 9%    ~     (p=0.151 n=5+5)
ycsb/B/values=64    15.4 ± 1%    15.3 ± 0%    ~     (p=0.516 n=5+5)
ycsb/C/values=64    0.00         0.00         ~     (all equal)
ycsb/D/values=64    18.9 ± 1%    19.1 ± 1%  +1.02%  (p=0.040 n=5+5)
ycsb/E/values=64    26.2 ± 2%    26.3 ± 2%    ~     (p=0.746 n=5+5)
```

The original BTree-based fix to this, with `FileInLevel`, was slightly less performant than all of the above but also not significantly so:

```
name              old ops/sec  new ops/sec  delta
ycsb/A/values=64    267k ± 2%    262k ± 1%   ~     (p=0.056 n=5+5)
ycsb/B/values=64    945k ± 3%    912k ± 7%   ~     (p=0.151 n=5+5)
ycsb/C/values=64   2.19M ± 5%   2.03M ±10%   ~     (p=0.095 n=5+5)
ycsb/D/values=64    760k ± 4%    746k ± 8%   ~     (p=0.841 n=5+5)
ycsb/E/values=64    202k ± 5%    198k ± 7%   ~     (p=0.841 n=5+5)

name              old read     new read     delta
ycsb/A/values=64   72.3G ± 4%   70.5G ± 9%   ~     (p=0.690 n=5+5)
ycsb/B/values=64   50.3G ± 2%   49.1G ± 6%   ~     (p=0.421 n=5+5)
ycsb/C/values=64   3.00G ± 7%   2.90G ± 9%   ~     (p=0.421 n=5+5)
ycsb/D/values=64   48.7G ± 4%   48.5G ± 6%   ~     (p=0.841 n=5+5)
ycsb/E/values=64   18.4G ± 4%   18.0G ± 9%   ~     (p=0.548 n=5+5)

name              old write    new write    delta
ycsb/A/values=64   82.1G ± 3%   80.2G ± 8%   ~     (p=0.690 n=5+5)
ycsb/B/values=64   53.8G ± 2%   52.4G ± 6%   ~     (p=0.421 n=5+5)
ycsb/C/values=64   2.91G ± 7%   2.81G ± 9%   ~     (p=0.421 n=5+5)
ycsb/D/values=64   53.3G ± 4%   53.0G ± 6%   ~     (p=0.841 n=5+5)
ycsb/E/values=64   19.6G ± 4%   19.2G ± 9%   ~     (p=0.548 n=5+5)

name              old r-amp    new r-amp    delta
ycsb/A/values=64    4.13 ± 1%    4.15 ± 3%   ~     (p=0.500 n=5+5)
ycsb/B/values=64    3.58 ± 1%    3.60 ± 2%   ~     (p=0.516 n=5+5)
ycsb/C/values=64    1.27 ± 0%    1.30 ± 7%   ~     (p=0.635 n=5+5)
ycsb/D/values=64    4.13 ± 1%    4.13 ± 2%   ~     (p=0.968 n=5+5)
ycsb/E/values=64    2.58 ± 1%    2.58 ± 1%   ~     (p=0.952 n=5+5)

name              old w-amp    new w-amp    delta
ycsb/A/values=64    8.31 ± 3%    8.27 ± 8%   ~     (p=1.000 n=5+5)
ycsb/B/values=64    15.4 ± 1%    15.5 ± 2%   ~     (p=0.167 n=5+5)
ycsb/C/values=64    0.00         0.00        ~     (all equal)
ycsb/D/values=64    18.9 ± 1%    19.2 ± 2%   ~     (p=0.056 n=5+5)
ycsb/E/values=64    26.2 ± 2%    26.1 ± 2%   ~     (p=1.000 n=5+5)
```

In the end, it seems like the performance difference is a wash. I'm good with going with the current `iter.Clone` solution as it's both the simplest (requiring no sublevels-specific logic), is reasonably performant at fixing the edge case, and is also pretty safe.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 5 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1041#-:-MQxsMPr4AFi8ozaIa0n:bg7igkv)* status: all files reviewed, 4 unresolved discussions (waiting on @itsbilal, @jbowens, @petermattis, and @sumeerbhola)

___
*[iterator.go, line 218 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1041#-MQP_Ea6EUq5uyHjo6a-:-MQxravs7k6geXdoM1sy:b-ji2nc) ([raw file](https://github.com/cockroachdb/pebble/blob/f3a26c19a0a4d69fa65820c52d92ffce0dc3ad62/iterator.go#L218)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Haha, makes sense. Making a state change in an operation that's supposed to not do that (read sampling) makes me a little uneasy, but I'll try that approach too to see how much of a difference that makes. For now I've made the Clone change, as that one had no statistically significant performance differences in ycsb-* compared to the original state of this PR.

Let me try another set of runs before this change, and one with the way you suggested, to see if something significantly stands out.
</blockquote></details>

Can you add a code comment derived from the earlier TODO explaining why we need the code in this if-block. It will be hard for a future reader without some motivation.
___
*[iterator.go, line 218 at r4](https://reviewable.io/reviews/cockroachdb/pebble/1041#-MQxrroyAtEqtFzECYrP:-MQxrroyAtEqtFzECYrQ:b9w3x0e) ([raw file](https://github.com/cockroachdb/pebble/blob/6784e16d71c61d4dc0ac79344a3a9cb861ec951d/iterator.go#L218)):*
> ```Go
> 				if file != nil {
> 					if i.pos == iterPosNext || i.pos == iterPosCurForward {
> 						containsKey = i.cmp(file.Smallest.UserKey, i.key) <= 0
> ```

why we care about `containsKey` could use a code comment.

**Comment by itsbilal** [comment]
Realized I didn't leave a comment about newer, more accurate performance testing numbers in the PR. I forced the roachtest to reuse the same cluster multiple times instead of building new ones, to reduce per-cluster variance, and ran the benchmarks 10 times instead of 5 times.

Turns out, any of the potential solutions to this edge case induces a performance regression in read sampling that more than negates any benefit of the increased accuracy. The most efficient thing is to just do nothing when the bounds don't match (so the state of things in master).

Current master vs this change:

```
name                old ops/sec  new ops/sec  delta
ycsb/A/values=1024   57.0k ± 2%   52.3k ± 4%   -8.23%  (p=0.000 n=9+10)
ycsb/B/values=1024   89.9k ± 5%   69.8k ± 7%  -22.36%  (p=0.000 n=9+10)
ycsb/C/values=1024   96.0k ± 7%   72.9k ±10%  -23.97%  (p=0.000 n=10+10)
ycsb/D/values=1024   29.8k ± 5%   24.5k ± 8%  -17.99%  (p=0.000 n=9+10)
ycsb/E/values=1024   19.3k ± 0%   15.8k ±10%  -18.50%  (p=0.000 n=7+10)
ycsb/A/values=64      274k ± 1%    248k ± 7%   -9.67%  (p=0.000 n=10+9)
ycsb/B/values=64     1.06M ± 1%   0.87M ± 8%  -17.69%  (p=0.000 n=10+10)
ycsb/C/values=64     2.37M ± 3%   1.90M ± 8%  -19.94%  (p=0.000 n=10+9)
ycsb/D/values=64      835k ± 1%    700k ± 7%  -16.19%  (p=0.000 n=10+10)
ycsb/E/values=64      209k ± 0%    187k ± 8%  -10.32%  (p=0.000 n=9+10)
```

Current master vs @aadityasondhi 's original fix:

```
name                old ops/sec  new ops/sec  delta
ycsb/A/values=1024   57.0k ± 2%   52.0k ± 4%   -8.71%  (p=0.000 n=9+10)
ycsb/B/values=1024   89.9k ± 5%   69.4k ± 5%  -22.82%  (p=0.000 n=9+9)
ycsb/C/values=1024   96.0k ± 7%   75.0k ± 9%  -21.84%  (p=0.000 n=10+10)
ycsb/D/values=1024   29.8k ± 5%   25.2k ± 5%  -15.57%  (p=0.000 n=9+9)
ycsb/E/values=1024   19.3k ± 0%   16.6k ± 9%  -14.04%  (p=0.000 n=7+10)
ycsb/A/values=64      274k ± 1%    258k ± 7%   -5.73%  (p=0.000 n=10+10)
ycsb/B/values=64     1.06M ± 1%   0.92M ± 6%  -12.43%  (p=0.000 n=10+10)
ycsb/C/values=64     2.37M ± 3%   2.13M ±12%  -10.25%  (p=0.000 n=10+10)
ycsb/D/values=64      835k ± 1%    769k ± 5%   -7.97%  (p=0.000 n=10+10)
ycsb/E/values=64      209k ± 0%    204k ± 6%     ~     (p=0.968 n=9+10)
```

Current master vs the iterator positional fix (where we Next() the iterator, look at the file there, then Prev() again):

```
name                old ops/sec  new ops/sec  delta
ycsb/A/values=1024   57.0k ± 2%   51.0k ± 3%  -10.48%  (p=0.000 n=9+9)
ycsb/B/values=1024   89.9k ± 5%   69.8k ± 8%  -22.34%  (p=0.000 n=9+10)
ycsb/C/values=1024   96.0k ± 7%   73.9k ±10%  -22.98%  (p=0.000 n=10+10)
ycsb/D/values=1024   29.8k ± 5%   24.5k ± 8%  -18.00%  (p=0.000 n=9+10)
ycsb/E/values=1024   19.3k ± 0%   16.0k ± 8%  -17.12%  (p=0.000 n=7+10)
ycsb/A/values=64      274k ± 1%    256k ± 7%   -6.46%  (p=0.000 n=10+10)
ycsb/B/values=64     1.06M ± 1%   0.87M ± 5%  -17.61%  (p=0.000 n=10+10)
ycsb/C/values=64     2.37M ± 3%   1.95M ±11%  -17.99%  (p=0.000 n=10+10)
ycsb/D/values=64      835k ± 1%    719k ± 5%  -13.91%  (p=0.000 n=10+10)
ycsb/E/values=64      209k ± 0%    191k ± 5%   -8.75%  (p=0.000 n=9+10)
```

I couldn't think of many other optimizations either that'd speed that up, so I think the right thing here is to just do nothing. I'll write a new PR to remove the TODOs around this area.

**Pull request closed without merging**
