### PR TITLE
internal/rangekey: refactor iterators to implement FragmentIterator

### PR DESCRIPTION
**Pull request by jbowens**
Refactor the InterleavingIter and DefragmentingIter to both implement the
FragmentInterator interface, eliminating the rangekey.Iterator interface and
rangekey.Iter type.

Besides the return value, the `rangekey.Iterator` interface differed from the
FragmentIterator interface in seeking semantics. A `rangekey.Iterator`
SeekGE(k) seeked to the first span that covered a key greater than or equal to
k. A `keyspan.FragmentIterator` seeks to the first span with a start key
greater than or equal to k. This commit adapts InterleavingIter and
DefragmentingIter to implement the `FragmentIterator` semantics.

### CODE REVIEW

**Review by nicktrav — COMMENTED** [review]
Done with `keyspan`. Flushing some comments.

> Reviewed 5 of 25 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1607#-:-MzN9HsV9xNu_VOYs2mL:bqda0co)* status: 2 of 26 files reviewed, 5 unresolved discussions (waiting on @itsbilal, @jbowens, @nicktrav, and @sumeerbhola)

___
*[internal/keyspan/merging_iter.go, line 31 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1607#-MzN5vfICSlt1o5t3e6v:-MzN5vfICSlt1o5t3e6w:bh5vqsx) ([raw file](https://github.com/cockroachdb/pebble/blob/1c06b83ac9a7b06ac7cefe1a2e7ff2b5a95b116c/internal/keyspan/merging_iter.go#L31)):*
> ```Go
> // *Span pointer. The output Span's Keys slice may be reused by Transform to
> // reduce allocations.
> type Transform func(cmp base.Compare, in Span, out *Span) error
> ```

I didn't dig into the usage of this too deeply, but would it be more conventional to return an `(out Span, err error)`, and then have the caller handle updating any deref'd pointer it had? Or is the idea here encapsulate all the update logic in this transform function (e.g. it might only update some fields on the `out *Span` pointer?).
___
*[internal/rangekey/interleaving_iter.go, line 32 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1607#-MzMxg1p5i4NAERfsl_L:-MzMxg1p5i4NAERfsl_M:b-s5d9t5) ([raw file](https://github.com/cockroachdb/pebble/blob/1c06b83ac9a7b06ac7cefe1a2e7ff2b5a95b116c/internal/rangekey/interleaving_iter.go#L32)):*
> and an arbitrary contained key's kind

This read a little funny. Perhaps "... and an arbitrary key kind, selected from one of the contained keys"?
___
*[internal/rangekey/interleaving_iter.go, line 51 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1607#-MzMyLPjDN5azN5xBF3J:-MzMyLPjDN5azN5xBF3K:b-sdercr) ([raw file](https://github.com/cockroachdb/pebble/blob/1c06b83ac9a7b06ac7cefe1a2e7ff2b5a95b116c/internal/rangekey/interleaving_iter.go#L51)):*
> ```Go
> // by a SeekGE or SeekPrefixGE search key (eg, in the earlier example after
> // returning the synthetic span marker `d#72057594037927935,21`,
> // Span would still return [a, z).
> ```

I'm a little confused reading this as to what happens in the case when:
- bounds are set to say `[c, e)`
- `SeekGE(d)` returns a truncated synthetic key `d#inf,21`
- what does `Span` return? Is it truncated to the set bounds `[d-e)`, or is the original span `[a, z) returned?

For completeness, can the comment also include this example of setting bounds then calling a positioning method?
___
*[internal/rangekey/interleaving_iter.go, line 53 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1607#-MzMymJ7A6Hg-besGEyg:-MzMymJ7A6Hg-besGEyh:bm9kpr6) ([raw file](https://github.com/cockroachdb/pebble/blob/1c06b83ac9a7b06ac7cefe1a2e7ff2b5a95b116c/internal/rangekey/interleaving_iter.go#L53)):*
> ```Go
> // Span would still return [a, z).
> //
> // InterleavedIter does not interleave synthetic markers for spans that do not
> ```

Wondering if we detail this concept of "empty spans" somewhere and how they come to be (perhaps it belongs here) - i.e. between two point keys there may not be an overlapping range key, we'd still have a span, but it would contain no keys.

Perhaps that's too much of an implementation detail, in which case ignore.
___
*[internal/rangekey/interleaving_iter.go, line 91 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1607#-MzN0h5F68CXXZy9JF1J:-MzN0h5F68CXXZy9JF1K:b-cq942g) ([raw file](https://github.com/cockroachdb/pebble/blob/1c06b83ac9a7b06ac7cefe1a2e7ff2b5a95b116c/internal/rangekey/interleaving_iter.go#L91)):*
I was thinking of another way of communicating the effect of range key masks (or are we calling them span key mask now?), along the lines of:

> Another way of thinking about masking: a mask with threshold `_t_` "activates" span keys `_r_` at or above it (i.e. spans `_r_` activated if `_t_` <= `_r_`). Point keys `_p_` that exist above "activated" span keys are elided (i.e. `_r_ < _p_`).

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
(interleaving_iter.go and tests are remaining)

> Reviewed 13 of 25 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1607#-:-MzNTUaO4F2YQ4rGVV61:buam2x9)* status: 9 of 26 files reviewed, 8 unresolved discussions (waiting on @itsbilal, @jbowens, @nicktrav, and @sumeerbhola)

___
*[iterator.go, line 216 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1607#-MzNSAeS-K0PILztdboJ:-MzNSAeS-K0PILztdboK:b-c7dt55) ([raw file](https://github.com/cockroachdb/pebble/blob/1c06b83ac9a7b06ac7cefe1a2e7ff2b5a95b116c/iterator.go#L216)):*
> ```Go
> 	// range key iterator.
> 	rangeKeyIter keyspan.FragmentIterator
> 	merging      keyspan.MergingIter
> ```

why does it need to know that something is a MergingIter? Isn't FragmentIterator sufficient?
___
*[internal/rangekey/defragment.go, line 170 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1607#-MzNQ-SW-XyJvwp7KxNV:-MzNQ-SW-XyJvwp7KxNW:b8zkqvg) ([raw file](https://github.com/cockroachdb/pebble/blob/1c06b83ac9a7b06ac7cefe1a2e7ff2b5a95b116c/internal/rangekey/defragment.go#L170)):*
> ```Go
> 
> // SeekLT seeks the iterator to the first span covering a key less than key and
> // returns it.
> ```

nit: stating this as
// SeekLT seeks the iterator to the last span with a start key less than key and returns it.

would be more consistent with how we explain SeekGE
___
*[internal/rangekey/interleaving_iter.go, line 26 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1607#-MzNT-YuBEwANEp5jr52:-MzNT-YuBEwANEp5jr53:b-m0l4hh) ([raw file](https://github.com/cockroachdb/pebble/blob/1c06b83ac9a7b06ac7cefe1a2e7ff2b5a95b116c/internal/rangekey/interleaving_iter.go#L26)):*
> ```Go
> // A span is considered to 'cover' a returned key if the span's [start, end)
> // bounds include the key's user key. Covering is determined independent of the
> // keys contained within the Span, so a Span with a lower sequence numbered Key
> ```

"independent of keys contained within the Span" is not clear.
Naively, one could say that the span contains the user keys that are ordered within [start, end), but this comment seems to be saying something else.

**Review by nicktrav — COMMENTED** [review]
Done with the non-test code. Onto the test code.

> Reviewed 6 of 25 files at r1, 2 of 12 files at r2, 4 of 5 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1607#-:-MzW1O_i5MGORR4gNK9X:bt2zdrf)* status: 14 of 26 files reviewed, 4 unresolved discussions (waiting on @itsbilal, @jbowens, and @sumeerbhola)

___
*[internal/rangekey/coalesce.go, line 65 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1607#-MzVrIgs4zRdyr_O5fP1:-MzVrIgs4zRdyr_O5fP2:b-y34ew1) ([raw file](https://github.com/cockroachdb/pebble/blob/1c06b83ac9a7b06ac7cefe1a2e7ff2b5a95b116c/internal/rangekey/coalesce.go#L65)):*
> ```Go
> 				continue
> 			default:
> 				base.CorruptionErrorf("pebble: unrecognized range key kind %s", keys[i].Kind())
> ```

Missing `return`.
___
*[internal/keyspan/interleaving_iter.go, line 26 at r4](https://reviewable.io/reviews/cockroachdb/pebble/1607#-MzVmEMsEu9XYW9UzJ_T:-MzVlQ26BGhJMtC2B7Qd:b1vmca6) ([raw file](https://github.com/cockroachdb/pebble/blob/a4deaf73b751b6afa55c261b154bcfff598e630c/internal/keyspan/interleaving_iter.go#L26)):*
> The InterleavingIterator a point iterator and span iterator,

"is both a point and span iterator"?

**Review by nicktrav — APPROVED** [review]
Very nice! :lgtm: 

> Reviewed 14 of 25 files at r1, 10 of 12 files at r2, 1 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1607#-:-MzW8ffuD486io90_0rz:bup7q37)* status: all files reviewed, 6 unresolved discussions (waiting on @itsbilal, @jbowens, and @sumeerbhola)

___
*[internal/keyspan/testdata/defragmenting_iter, line 1 at r4](https://reviewable.io/reviews/cockroachdb/pebble/1607#-MzW5HYWAXzrPphzQLg7:-MzW5HYWAXzrPphzQLg8:bz6mviz) ([raw file](https://github.com/cockroachdb/pebble/blob/a4deaf73b751b6afa55c261b154bcfff598e630c/internal/keyspan/testdata/defragmenting_iter#L1)):*
> ```
> define
> ```

Maybe a comment here to say that this is testing the case where we can't defrag?
___
*[internal/keyspan/testdata/defragmenting_iter, line 107 at r4](https://reviewable.io/reviews/cockroachdb/pebble/1607#-MzW6XyB7hI94hBgg_nV:-MzW6XyB7hI94hBgg_nW:b1nzf2d) ([raw file](https://github.com/cockroachdb/pebble/blob/a4deaf73b751b6afa55c261b154bcfff598e630c/internal/keyspan/testdata/defragmenting_iter#L107)):*
> ```
> 
> iter
> seekge r
> ```

For some additional coverage, we could seek to some / all of the start keys of the fragmented spans (e.g. `f, h, p, t`)?

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 25 files at r1, 5 of 12 files at r2, 4 of 5 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1607#-:-MzWSGJj62LDsg0XDe6i:bg7igkv)* status: all files reviewed, 7 unresolved discussions (waiting on @itsbilal, @jbowens, and @sumeerbhola)

___
*[internal/keyspan/interleaving_iter.go, line 38 at r4](https://reviewable.io/reviews/cockroachdb/pebble/1607#-MzWJvDlAuNiozDB66qt:-MzWJvDlAuNiozDB66qu:b-5sp2z9) ([raw file](https://github.com/cockroachdb/pebble/blob/a4deaf73b751b6afa55c261b154bcfff598e630c/internal/keyspan/interleaving_iter.go#L38)):*
> ```Go
> // special InternalKey at span start boundaries. Start boundaries are surfaced
> // as a synthetic span marker: an InternalKey with the boundary as the user key,
> // the infinite sequence number and a key kind selected from an arbitrary key
> ```

so the key kind should not be used by the caller?

**Review by jbowens — COMMENTED** [review]
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1607#-:-MzWnvxNCQk30hvHrd9O:bz5mair)* status: 24 of 26 files reviewed, 4 unresolved discussions (waiting on @itsbilal, @nicktrav, and @sumeerbhola)

___
*[internal/rangekey/coalesce.go, line 65 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1607#-MzVrIgs4zRdyr_O5fP1:-MzWj8U41j1Rl4oL9yQj:b-tburtn) ([raw file](https://github.com/cockroachdb/pebble/blob/1c06b83ac9a7b06ac7cefe1a2e7ff2b5a95b116c/internal/rangekey/coalesce.go#L65)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

Missing `return`.
</blockquote></details>

good catch. scary.
___
*[internal/keyspan/interleaving_iter.go, line 38 at r4](https://reviewable.io/reviews/cockroachdb/pebble/1607#-MzWJvDlAuNiozDB66qt:-MzWiG0r8ZwQOTcNuwvU:b-mzqjo3) ([raw file](https://github.com/cockroachdb/pebble/blob/a4deaf73b751b6afa55c261b154bcfff598e630c/internal/keyspan/interleaving_iter.go#L38)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

so the key kind should not be used by the caller?
</blockquote></details>

yeah, added a couple sentences calling this out

**Pull request merged**
