### PR TITLE
release readers that failed to open from table cache

### PR DESCRIPTION
**Pull request by ajkr**
This allows readers to retry operations without hitting the same error
every time due to a cached table reader in error state. This PR also
fixes a segfault when `sstable.NewReader` fails.

### CODE REVIEW

**Comment by petermattis** [comment]
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/451)

**Comment by ajkr** [comment]
The test plan is the metamorphic test changes I'm working on in #438. Am fixing some of the issues it turns up before submitting it since right now it's unclear which of the failures are meaningful vs. deficiencies in my test changes.

**Comment by ajkr** [comment]
> we shouldn't retry over and over in the hopes of success. These semantics were inherited from the go-leveldb code (I'm not particularly attached to them). I'm curious what RocksDB does in this circumstance.

In this case RocksDB won't cache the table reader so it will try opening it again next time: https://github.com/facebook/rocksdb/blob/37fd2b9694052323d5867f1dc56174202023c016/db/table_cache.cc#L159-L162 (ignore the comment about repairing the file, that never actually happens). It only retries as often as the user tries to read from the file; it shouldn't enter an infinite loop of retry or anything like that. If the read error happened during compaction the DB would enter read-only mode so it doesn't automatically retry.

> Also, my general modus operandi with metamorphic failures is to add a specific test to that demonstrates the problem being fixed. I think this could be done in this case with a tableCache test that tries to open an sstable that doesn't exist, verifies an error occurs, and then creates the sstable and tries to open it again. The second open should succeed, while with the current code it would fail as we'd cache the error state.

Thanks, will try it out.

**Comment by ajkr** [comment]
Thought about it more. I think avoiding retry makes sense if the process will crash on seeing even a read error. Otherwise it could be inconvenient. Not sure what Cockroach does.

For example, imagine a read tries to load a table into cache but fails due to file descriptor limit. Then maybe a compaction finishes which frees up a bunch of file descriptors, or perhaps the user increases their limit, or deletes files elsewhere in the system. Still, from that point on any reads involving our file that failed to open once will all fail. If the application does not crash on failed reads it could stay in a crippled state for a while.

**Comment by petermattis** [comment]
> Thought about it more. I think avoiding retry makes sense if the process will crash on seeing even a read error. Otherwise it could be inconvenient. Not sure what Cockroach does.

CRDB likely does not handle IO errors at the storage level well. The error would likely be propagated up to the KV operation and eventually transformed into something the user sees. Not sure if that is desirable or not. 

> For example, imagine a read tries to load a table into cache but fails due to file descriptor limit. Then maybe a compaction finishes which frees up a bunch of file descriptors, or perhaps the user increases their limit, or closes files elsewhere in the system. Still, from that point on any reads involving our file that failed to open once will all fail. If the application does not crash on failed reads it could stay in a crippled state for a while.

Ok, I agree we shouldn't persist the error into the `tableCache`. I'm a bit confused about your first paragraph, though. Are you thinking that `Pebble` should internally retry on certain IO errors during read? That doesn't sound good. If a read takes too long, timeouts will kick in at the CRDB level. Seems better to return the error so we can get visibility into what is going on, and let CRDB retry if it wants to. I'm not sure if I'm accurately representing your position, though.

**Comment by ajkr** [comment]
In the first paragraph s/avoiding retry/preventing user retry from
succeeding/. I think we're trying to say the same thing.

**Pull request merged**
