### PR TITLE
db: reduce allocations of Iterator.prefixOrFullSeekKey

### PR DESCRIPTION
**Pull request by moredure**

### CODE REVIEW

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
Thanks for spotting and improving this.
Can you change the commit text and PR description to:

db: reduce allocations of Iterator.prefixOrFullSeekKey

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1078#-:-MUsR-VFDI6_BIh72lXy:b-xc21fs)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @moredure)

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1078#-:-MUsj4_y2rBP7LIdOxVV:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @moredure)

**Comment by moredure** [comment]
Looks like the failed build fails before this change as well.

**Comment by moredure** [comment]
:lgtm: ?

**Review by moredure — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1078)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @moredure)

**Comment by moredure** [comment]
Anything is required from me to make this change merged? Code changes, etc?

**Comment by sumeerbhola** [comment]
> Anything is required from me to make this change merged? Code changes, etc?

No, no more changes needed. The `TestCacheEvict` failure under race looks unrelated, and I can't reproduce it locally after patching this change.

**Comment by moredure** [comment]
My pprof SeekGE free)

**Pull request merged**
