### PR TITLE
db: add per-compaction type counts to Metrics.Compact

### LINKED ISSUE #1145: db: add visibility into read compactions in Metrics
`Metrics.Compact` currently lacks a count of queued read compactions. Since read compactions are queued on a specific level we could also add a per-level count to `LevelMetrics`.

### PR DESCRIPTION
**Pull request by petermattis**
Fixes #1145

### CODE REVIEW

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1150)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @itsbilal and @sumeerbhola)

___
*[compaction.go, line 419 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1150#-M_uSqZMCAiLlzFI3B40:-M_uSqZN9FdO8jQJLG5Q:bj3onvn) ([raw file](https://github.com/cockroachdb/pebble/blob/9609733fcb8ece2fc5147c85412399f1227543f7/compaction.go#L419)):*
> ```Go
> 
> const (
> 	compactionKindDefault compactionKind = iota
> ```

I'm not sure if this part of the change was worthwhile. It was motivated by not having a switch statement on a string type while holding the DB mutex at the end of a compaction. Probably a micro-optimization that has no impact.

**Review by itsbilal — APPROVED** [review]
:lgtm:

Is there an easy way to add one test where the ctypes aren't all 0's in the metrics output?

> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1150#-:-Ma-6C6Y7-YPqBZJiqgq:bcqqjlq)* status: all files reviewed, 1 unresolved discussion (waiting on @sumeerbhola)

**Comment by petermattis** [comment]
TFTR!

> Is there an easy way to add one test where the ctypes aren't all 0's in the metrics output?

Oh, good point. I enhanced `TestMetricsFormat` to populate every `Metrics` field which is the intent of that test. PTAL.

**Review by itsbilal — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1150#-:-Ma-Oz4l7ZjLbl1KJAt7:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @sumeerbhola)

**Pull request merged**
