### PR TITLE
crl-release-22.2: vfs: add SyncData,SyncTo,Preallocate to vfs.File 

### PR DESCRIPTION
**Pull request by jbowens**
Expand the vfs.File interface to expose SyncData, SyncTo and Preallocate as
first-class methods. Previously, the file created through vfs.NewSyncingFile
would perform analagous I/O operations (eg, `Fdatasync`, `sync_file_range`,
`Fallocate`) outside the context of the interface. This easily allowed the
accidental loss of the disk-health checking over these operations by minor
tweaks to the interface of the disk-health checking implementation or by adding
intermediary VFS wrappers between the disk-health checking FS and the syncing
file.

See https://github.com/cockroachdb/cockroach/issues/94373 where the introduction of an additional VFS
wrapper resulted in these I/O operations being uncovered by disk-stall
detection.

### CODE REVIEW

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r1, 11 of 22 files at r2, 11 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2276)* status: all files reviewed, 3 unresolved discussions (waiting on @jbowens)

___
*[`vfs/mem_fs.go` line 684 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2276#-NMfxjIp5PTB7ny-BQJA:-NMfxjIp5PTB7ny-BQJB:b-2or9ma) ([raw file](https://github.com/cockroachdb/pebble/blob/37154b0f749c6c6aa297bb50a62d06570c41f354/vfs/mem_fs.go#L684)):*
> ```Go
> 
> func (f *memFile) Capabilities() Capabilities {
> 	return Capabilities{}
> ```

how about we set `CanSyncTo: true` and make `SyncTo` a noop. That way any logic bugs we may have where we accidentally believe `SyncTo` is durable can be caught with testing with the strict MemFS.
___
*[`vfs/syncing_file.go` line 161 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2276#-NMftXMI5ARJfSIQZiO1:-NMftXMI5ARJfSIQZiO2:b1suncw) ([raw file](https://github.com/cockroachdb/pebble/blob/37154b0f749c6c6aa297bb50a62d06570c41f354/vfs/syncing_file.go#L161)):*
> ```Go
> 	//
> 	// Additionally, if the file is capable of 'SyncTo'-ing, syncOffset will be
> 	// less than atomic.offset. In this case, we should also sync to
> ```

incomplete sentence
___
*[`vfs/syncing_file.go` line 176 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2276#-NMfwcrB0Bh4aRiBbth9:-NMfwcrB0Bh4aRiBbthA:b-gmat3i) ([raw file](https://github.com/cockroachdb/pebble/blob/37154b0f749c6c6aa297bb50a62d06570c41f354/vfs/syncing_file.go#L176)):*
> ```Go
> 				return err
> 			}
> 		} else if !f.noSyncOnClose {
> ```

why is this in an else-if.
Shouldn't it be
```
if !f.noSyncOnClose {
  // Do the real sync for durability
} else if f.capabilities.CanSyncTo {
  // Do the SyncTo which does not provide a durability guarantee
}
```

**Review by jbowens — COMMENTED** [review]
PTAL—I removed the `Capabilities` and updated the `SyncTo` signature to allow implementors to indicate whether the implementation performed a full sync. This ensures we can update the offset appropriately, and avoid the extraneous Sync on close if the file has been full syncing the entire time.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2276#-:-NMjKZepETTzdiLEgEJy:b-3mtfnz)* status: 10 of 31 files reviewed, 3 unresolved discussions (waiting on @sumeerbhola)

___
*[`vfs/mem_fs.go` line 684 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2276#-NMfxjIp5PTB7ny-BQJA:-NMjK5GlAsLXYiTg-pwn:b-3ttkmq) ([raw file](https://github.com/cockroachdb/pebble/blob/37154b0f749c6c6aa297bb50a62d06570c41f354/vfs/mem_fs.go#L684)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

how about we set `CanSyncTo: true` and make `SyncTo` a noop. That way any logic bugs we may have where we accidentally believe `SyncTo` is durable can be caught with testing with the strict MemFS.
</blockquote></details>

I eliminated the `Capabilities` method, but I added a no-op `SyncTo` implementation here that gets us this coverage. Good idea.
___
*[`vfs/syncing_file.go` line 161 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2276#-NMftXMI5ARJfSIQZiO1:-NMii1cQ3C47e4Scc8tB:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/37154b0f749c6c6aa297bb50a62d06570c41f354/vfs/syncing_file.go#L161)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

incomplete sentence
</blockquote></details>

Done.
___
*[`vfs/syncing_file.go` line 176 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2276#-NMfwcrB0Bh4aRiBbth9:-NMjKFuu8RotW3IozGPq:bz8epfl) ([raw file](https://github.com/cockroachdb/pebble/blob/37154b0f749c6c6aa297bb50a62d06570c41f354/vfs/syncing_file.go#L176)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

why is this in an else-if.
Shouldn't it be
```
if !f.noSyncOnClose {
  // Do the real sync for durability
} else if f.capabilities.CanSyncTo {
  // Do the SyncTo which does not provide a durability guarantee
}
```
</blockquote></details>

This was confusion over the offset. This is fixed up.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 15 of 21 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2276#-:-NMjiR96Au2PuMLqSeMk:bg7igkv)* status: 25 of 31 files reviewed, 6 unresolved discussions (waiting on @jbowens)

___
*[`vfs/syncing_file.go` line 167 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2276#-NMjgJWr8lJZotkaUy1q:-NMjgJWs5BQthfwB2Il8:b-mzd9tk) ([raw file](https://github.com/cockroachdb/pebble/blob/1854784ccd9822922f5ebec5c5ef9974ffecd343/vfs/syncing_file.go#L167)):*
> ```Go
> 	// has noSyncOnClose option explicitly set.
> 	//
> 	// NB: If the file is capable of non-durability-guarantee SyncTos,
> ```

... non-durability-guarantee SyncTos, and the caller has not called `Sync` since the last write, syncOffset is guaranteed ...
___
*[`vfs/syncing_file.go` line 182 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2276#-NMjgni66w3LfA3wRxO8:-NMjgni66w3LfA3wRxO9:bcyoik5) ([raw file](https://github.com/cockroachdb/pebble/blob/1854784ccd9822922f5ebec5c5ef9974ffecd343/vfs/syncing_file.go#L182)):*
> ```Go
> 				return err
> 			}
> 			f.ratchetSyncOffset(off)
> ```

do we need to bother with this `ratchedSyncOffset` call given the file is closing? If we do, it's odd that we don't do the same in the else block if the `f.Sync` does not return an error.
___
*[`vfs/vfs.go` line 42 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2276#-NMjhINDCZXz9pEOwyXo:-NMjhINDCZXz9pEOwyXp:b3kswdk) ([raw file](https://github.com/cockroachdb/pebble/blob/1854784ccd9822922f5ebec5c5ef9974ffecd343/vfs/vfs.go#L42)):*
> ```Go
> 	// storage. The caller passes provides a `length`, indicating how many bytes
> 	// to sync from the beginning of the file. SyncTo is a no-op for
> 	// directories.
> ```

... directories, and therefore always returns false.

**Review by jbowens — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2276#-:-NMjvm7DAB10ZDRZ1eZO:b-814g8k)* status: 25 of 31 files reviewed, 6 unresolved discussions (waiting on @sumeerbhola)

___
*[`vfs/syncing_file.go` line 167 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2276#-NMjgJWr8lJZotkaUy1q:-NMjvNa32UTgyn-2v41S:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/1854784ccd9822922f5ebec5c5ef9974ffecd343/vfs/syncing_file.go#L167)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

... non-durability-guarantee SyncTos, and the caller has not called `Sync` since the last write, syncOffset is guaranteed ...
</blockquote></details>

Done.
___
*[`vfs/syncing_file.go` line 182 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2276#-NMjgni66w3LfA3wRxO8:-NMjvPHq9y5PG6LprDB8:b-6oqma5) ([raw file](https://github.com/cockroachdb/pebble/blob/1854784ccd9822922f5ebec5c5ef9974ffecd343/vfs/syncing_file.go#L182)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

do we need to bother with this `ratchedSyncOffset` call given the file is closing? If we do, it's odd that we don't do the same in the else block if the `f.Sync` does not return an error.
</blockquote></details>

it helps with testing. The below `f.Sync` calls `syncingFile.Sync` which will also ratchet the offset
___
*[`vfs/vfs.go` line 42 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2276#-NMjhINDCZXz9pEOwyXo:-NMjvbX6CSJ__yDzKspV:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/1854784ccd9822922f5ebec5c5ef9974ffecd343/vfs/vfs.go#L42)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

... directories, and therefore always returns false.
</blockquote></details>

Done.

**Pull request merged**
