### PR TITLE
db: refactor TestRangeKeys into TestIterHistories 

### PR DESCRIPTION
**Pull request by jbowens**
**db: refactor TestRangeKeys into TestIterHistories**

Refactor the TestRangeKeys datadriven unit test into a more generalized
TestIterHistories that executes all the datadriven test files in the
testdata/iter_histories directory. The single testdata/rangekeys file
was becoming unwieldly. The separate file organization is a little
easier to work with.

**db: expand iter_histories test coverage**

Add a new IterHistories unit test for the merge operator, expand some existing
test cases around Clone and RangeKeyChanged.

### CODE REVIEW

**Review by bananabrick — COMMENTED** [review]
It seems as if the test files added in the first commit are the old tests with some minor changed. So, I didn't look into the tests from the first commit carefully.

> Reviewed 12 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1962#-:-NCVpolo0wLSamZDZXe6:bn4ysfc)* status: 10 of 13 files reviewed, 3 unresolved discussions (waiting on @bananabrick and @jbowens)

___
*[`iterator_histories_test.go` line 35 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1962#-NCWE4NY77Mw99whTEmb:-NCWE4NY77Mw99whTEmc:b5owpnq) ([raw file](https://github.com/cockroachdb/pebble/blob/eebb0425179fc779679bfaaac4f093481ebe6892/iterator_histories_test.go#L35)):*
> ```Go
> 			if reader != nil {
> 				it = reader.NewIter(o)
> 			} else {
> ```

nit: Do we need this else condition? Looks like we always pass in at least `d` as the `reader` in this function? If `d` was `nil`, then the `d.NewIter` call will fail anyway.
___
*[`iterator_histories_test.go` line 146 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1962#-NCWGHER4FGcB941ZyQt:-NCWGHER4FGcB941ZyQu:b-yboawp) ([raw file](https://github.com/cockroachdb/pebble/blob/eebb0425179fc779679bfaaac4f093481ebe6892/iterator_histories_test.go#L146)):*
> ```Go
> 					}
> 				}
> 				b := d.NewIndexedBatch()
> ```

Would we have the same behaviour here now that we're using an indexed batch for every single testcase which uses `batch`?
___
*[`iterator_histories_test.go` line 253 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1962#-NCWIZ2K4ISlxAHhHKOU:-NCWIZ2K4ISlxAHhHKOV:ba9he) ([raw file](https://github.com/cockroachdb/pebble/blob/eebb0425179fc779679bfaaac4f093481ebe6892/iterator_histories_test.go#L253)):*
> ```Go
> 				count := b.Count()
> 				require.NoError(t, d.Apply(b, nil))
> 				delete(batches, name)
> ```

Did this batch have to be closed first? Or is that unnecessary?

**Review by bananabrick — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1962#-:-NCWM5yo9QbMLEhokQO1:bnfp4nl)* status: 10 of 13 files reviewed, 3 unresolved discussions (waiting on @bananabrick and @jbowens)

**Review by jbowens — COMMENTED** [review]
> It seems as if the test files added in the first commit are the old tests with some minor changed. 

That's right.

TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1962#-:-NCWWjb706QC_Sjg9ssE:b-iu0q6d)* status: 8 of 13 files reviewed, 3 unresolved discussions (waiting on @bananabrick)

___
*[`iterator_histories_test.go` line 35 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1962#-NCWE4NY77Mw99whTEmb:-NCWWiSlEznOEeO4AETU:b-48vilg) ([raw file](https://github.com/cockroachdb/pebble/blob/eebb0425179fc779679bfaaac4f093481ebe6892/iterator_histories_test.go#L35)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

nit: Do we need this else condition? Looks like we always pass in at least `d` as the `reader` in this function? If `d` was `nil`, then the `d.NewIter` call will fail anyway.
</blockquote></details>

Good call, done.
___
*[`iterator_histories_test.go` line 146 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1962#-NCWGHER4FGcB941ZyQt:-NCWWJ3n38s5wgJfku5n:b-7fcmfn) ([raw file](https://github.com/cockroachdb/pebble/blob/eebb0425179fc779679bfaaac4f093481ebe6892/iterator_histories_test.go#L146)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

Would we have the same behaviour here now that we're using an indexed batch for every single testcase which uses `batch`?
</blockquote></details>

yeah, the I don't think the distinction is meaningful here
___
*[`iterator_histories_test.go` line 253 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1962#-NCWIZ2K4ISlxAHhHKOU:-NCWWFOdARsHpbRhIi03:byfkg8w) ([raw file](https://github.com/cockroachdb/pebble/blob/eebb0425179fc779679bfaaac4f093481ebe6892/iterator_histories_test.go#L253)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

Did this batch have to be closed first? Or is that unnecessary? 
</blockquote></details>

It should be closed to return it to the pool. Done.

**Comment by jbowens** [comment]
TFTR!

**Pull request merged**
