### PR TITLE
internal/cache: replace robinHoodMap with swiss.Map

### PR DESCRIPTION
**Pull request by petermattis**
- **internal/cache: replace robinHoodMap with swiss.Map**
- **internal/cache: remove `robinHoodMap`**

### CODE REVIEW

**Comment by petermattis** [comment]
I doubt this moves the needle on any high-level Pebble benchmarks. Main motivation is to get rid of a bespoke hash table implementation.

**Comment by petermattis** [comment]
`fatal error: checkptr: converted pointer straddles multiple allocations` in race builds. Looks like I need to figure out how to silence/work-around that check.

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3352#-:-NrcYVU30YVwyrxyK56k:bnfp4nl)* status: 0 of 7 files reviewed, 3 unresolved discussions (waiting on @petermattis)

___
*[`internal/cache/block_map.go` line 1 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3352#-NrcXcP4CNYiifgTL7-s:-NrcXcP4CNYiifgTL7-t:btnj092) ([raw file](https://github.com/cockroachdb/pebble/blob/307a630b65faf78c991455192ee5016ef64f7dcb/internal/cache/block_map.go#L1)):*
> ```Go
> // Copyright 2020 The LevelDB-Go and Pebble Authors. All rights reserved. Use
> ```

[nit] 2024
___
*[`internal/cache/block_map_test.go` line 1 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3352#-NrcXeiGAFU_0Hd8y3IQ:-NrcXeiGAFU_0Hd8y3IR:bb6ht39) ([raw file](https://github.com/cockroachdb/pebble/blob/307a630b65faf78c991455192ee5016ef64f7dcb/internal/cache/block_map_test.go#L1)):*
> ```Go
> // Copyright 2020 The LevelDB-Go and Pebble Authors. All rights reserved. Use
> ```

2024
___
*[`internal/cache/block_map_test.go` line 24 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3352#-NrcXvkj01-S7NvLu3QZ:-NrcXvkkAcqyO0tlLBCU:btonhfp) ([raw file](https://github.com/cockroachdb/pebble/blob/307a630b65faf78c991455192ee5016ef64f7dcb/internal/cache/block_map_test.go#L24)):*
> ```Go
> // almost certainly have more than one CPU making 32K a reasonable upper limit
> // for the number of entries in a shard.
> const benchSize = 1 << 15
> ```

[nit] 32 * 1024 is much easier to read

**Comment by petermattis** [comment]
Tests are all green after bumping the cockroachdb/swiss pointer to pick up the 32-bit and race-build fixes.

**Review by jbowens — APPROVED** [review]
:lgtm_strong: 

> Reviewed 1 of 7 files at r1, 2 of 4 files at r3, 2 of 2 files at r4, 1 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3352#-:-Ns9F-XqAGhiybok0qSz:b-uwkowd)* status: 6 of 7 files reviewed, all discussions resolved (waiting on @RaduBerinde)

**Comment by petermattis** [comment]
TFTR!

**Pull request merged**
