### PR TITLE
[wip] compaction : Prevent compaction if it has happened already

### PR DESCRIPTION
**Pull request by bananabrick**
If a file associated with a compaction has its level changed, or
if the file is no longer in the version, then prevent the compaction.

This is trying to implement fix 2 here: https://docs.google.com/document/d/1qnhunjPrR1FSgRQ8MgwDay_FGgd8CoRpcsoK0Iybu2o/edit

### CODE REVIEW

**Review by bananabrick — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1199)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @bananabrick)

___
*[compaction_picker.go, line 1368 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1199#-MegQZBm0ITdTX4GPe2Q:-MegQZBm0ITdTX4GPe2R:bh82pge) ([raw file](https://github.com/cockroachdb/pebble/blob/14e9fe1c41dd79fb3cc31f3503db571f7c7e9160/compaction_picker.go#L1368)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> 	// TODO(bananabrick): Do we want to still check if the original file associated
> 	// with the compaction still belongs in the version?
> 	// We know that the range associated with that file belongs to
> 	// p.vers.
> ```
</details>


^

**Comment by itsbilal** [comment]
___
*[compaction_picker.go, line 1372 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1199#-Mekazuo5XWoVbkhJPrR:-Mekazuo5XWoVbkhJPrS:b919k7a) ([raw file](https://github.com/cockroachdb/pebble/blob/14e9fe1c41dd79fb3cc31f3503db571f7c7e9160/compaction_picker.go#L1372)):*
> ```Go
> 	// with the compaction still belongs in the version?
> 	// We know that the range associated with that file belongs to
> 	// p.vers.
> ```

Yes, you probably want to check for this and see how much that improves things.  Should be as simple as storing the file num and searching for it here.

**Review by itsbilal — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1199#-:-Mf-nYf71ndrtUSbU-XO:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @bananabrick)

___
*[compaction_picker.go, line 1372 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1199#-Mf-mvqZ2_Aoqk4tPukK:-Mf-mvqZ2_Aoqk4tPukL:b-8uhel9) ([raw file](https://github.com/cockroachdb/pebble/blob/475d2629381dc933b24560633ea85acca1471015/compaction_picker.go#L1372)):*
> ```Go
> 	}
> 	iter := overlapSlice.Iter()
> 	for f := iter.First(); f != nil; f = iter.Next() {
> ```

No need to check len and all; this could be as simple as `if f := overlapSlice.Iter().First(); f == nil || f.FileNum != rc.fileNum { ... }`

**Review by itsbilal — COMMENTED** [review]
(LGTM is assuming benchmarks are favourable for this change, as with the others).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1199#-:-Mf-noEA3c88_jW8Lis_:bgf2vd)* status: all files reviewed, 2 unresolved discussions (waiting on @bananabrick)

**Pull request closed without merging**
