### PR TITLE
metamorphic: run the level checker less frequently

### PR DESCRIPTION
**Pull request by RaduBerinde**
The level checker can significantly slow down downloads and background
compactions in the metamorphic test.

This change makes the level checker run only once per 500ms (on
average).

Informs #3460

### CODE REVIEW

**Review by jbowens — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3467#-:-Nu13v2K3VJZAlsmatCz:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @itsbilal)

**Comment by RaduBerinde** [comment]
Another idea is to make the checker run at most once per second in the meta test, what do you think?

**Comment by jbowens** [comment]
> Another idea is to make the checker run at most once per second in the meta test, what do you think?

that sounds reasonable to me

**Comment by RaduBerinde** [comment]
Done, I like that general solution more.

**Comment by RaduBerinde** [comment]
Hm, I still see some Downloads taking more than 5 minutes when running under `stress -p 3` locally :/

**Comment by RaduBerinde** [comment]
If I try to rerun just the one that failed, the entire test completes in 1-2s.. I wonder if there's some kind of race condition that makes it get stuck.

**Comment by RaduBerinde** [comment]
Indeed, wrote up the problem here: https://github.com/cockroachdb/pebble/issues/3470

**Review by jbowens — APPROVED** [review]
makes sense

> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3467#-:-Nu5BVTF3I3N4p_Ysm1B:b-pqov82)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @itsbilal)

**Pull request merged**
