### PR TITLE
db: don't wait on compaction cond lock if db is closed

### PR DESCRIPTION
**Pull request by itsbilal**
Previously, if the db was closed and a Download() call was waiting on a download to finish, we could see an indefinite wait because `maybeScheduleCompactionPicker` would not schedule any compactions, and the cond lock would never be broadcasted to. This change addresses this by checking for db closure before waiting on the compaction cond lock in downloadSpan().

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
Why is it legal to call `db.Close()` while `db.Download()` is also running?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3342#-:-NrMlkaW8XTi4lK0YhA6:bsi4m5w)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @itsbilal and @msbutler)

___
*[`db.go` line 1999 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3342#-NrMkgCfBxCL6YkG427f:-NrMkgCfBxCL6YkG427g:b-j0jne4) ([raw file](https://github.com/cockroachdb/pebble/blob/85f6cea7e345b60f52b09972481170a5c6f47678/db.go#L1999)):*
> ```Go
> 				}
> 				d.maybeScheduleCompaction()
> 				if d.closed.Load() != nil {
> ```

This works because the only way to not have a compaction running here is if `maybeScheduleCompaction` noticed that `closed.Load() != nil`, is this right? Seems very fragile, couldn't we just check the `compactingCount` instead?

**Review by itsbilal — COMMENTED** [review]
@RaduBerinde It happened in a crdb test and I imagine it could happen as another means of cancelling downloads. Probably best to support it.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3342#-:-NrfyKRA1HHED_yiFFEn:bf8amv2)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @msbutler and @RaduBerinde)

___
*[`db.go` line 1999 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3342#-NrMkgCfBxCL6YkG427f:-NrfyTOTACNjoT3KqU2V:b-1w6lnd) ([raw file](https://github.com/cockroachdb/pebble/blob/85f6cea7e345b60f52b09972481170a5c6f47678/db.go#L1999)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This works because the only way to not have a compaction running here is if `maybeScheduleCompaction` noticed that `closed.Load() != nil`, is this right? Seems very fragile, couldn't we just check the `compactingCount` instead?
</blockquote></details>

Good point. Made the change; ptal!

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3342#-:-NrgJqeZ3skW0CwLJUcz:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @msbutler)

**Comment by itsbilal** [comment]
TFTR!

**Pull request merged**
