### PR TITLE
db: fix L0 to LBase compaction picking bug with shared largest user keys

### LINKED ISSUE #944: internal/metamorphic: L6 files 001561 and 001568 have overlapping ranges
I was running the metamorphic tests on my gceworker on 5cfd1db5e359d357f0260d250adbefd683bb1217 and after 4 hours it hit another overlapping ranges invariant violation.

```
    TestMeta/random-018: meta_test.go:224:
        ===== SEED =====
        1600989092662222105
        ===== ERR =====
        exit status 1
        ===== OUT =====
        pebble: internal error: L6 files 001561 and 001568 have overlapping ranges: [yopclcg#0,SET-yopclcg#0,SET] vs [elkcjliadux#1259,DEL-yxmkeodguz#1253,DEL]

        ===== OPTIONS =====
        [Version]
          pebble_version=0.1

        [Options]
          bytes_per_sync=32
          cache_size=512
          cleaner=delete
          comparer=leveldb.BytewiseComparator
          delete_range_flush_delay=0s
          disable_wal=true
          flush_split_bytes=4
          l0_compaction_concurrency=2
          l0_compaction_threshold=3
          l0_stop_writes_threshold=74
          l0_sublevel_compactions=true
          lbase_max_bytes=2097152
          max_concurrent_compactions=2
          max_manifest_file_size=2097152
          max_open_files=1000
          mem_table_size=1024
          mem_table_stop_writes_threshold=4
          min_compaction_rate=4194304
          min_flush_rate=1048576
          merger=pebble.concatenate
          table_property_collectors=[]
          wal_dir=wal
          wal_bytes_per_sync=0

        [Level "0"]
          block_restart_interval=19
          block_size=16
          compression=Default
          filter_policy=none
          filter_type=table
          index_block_size=16384
          target_file_size=256
```

```
        iter33.First() // [true,"ajunqza","fg"] <nil> #3075
        // INFO: [JOB 1374] flushed 2 memtables to L0 [001569] (778 B), in 0.0s, output rate 7.5 M/s
        iter35.First() // [true,"mjpp","ufrianrsipmg"] <nil> #3076
        iter35.First() // [true,"mjpp","ufrianrsipmg"] <nil> #3077
        iter35.SeekGE("ozttv") // [true,"pvjjpvgfyv","ikoexpsuaiwiorzzm"] <nil> #3078
        db.Set("lcmsz", "uxw") // <nil> #3079
        iter33.Prev() // [false] <nil> #3080
        iter35.Prev() // [true,"nfgaeu","fxl"] <nil> #3081
        // INFO: [JOB 1375] flushing 2 memtables to L0
        iter33.SeekPrefixGE("rvuakoh") // [false] <nil> #3082
        iter35.SeekPrefixGE("duur") // [false] pebble: SeekPrefixGE supplied with key outside of lower bound #3083
        // INFO: [JOB 1375] flushing: sstable created 001570
        db.Merge("mjpp", "lvub") // <nil> #3084
        // INFO: write stall beginning: memtable count limit reached
        // INFO: [JOB 1372] compaction to L6 error: pebble: internal error: L6 files 001561 and 001568 have overlapping ranges: [yopclcg#0,SET-yopclcg#0,SET] vs [elkcjliadux#1259,DEL-yxmkeodguz#1253,DEL]
```

### PR DESCRIPTION
**Pull request by jbowens**
The compaction picker expands the L0 inputs of a compaction as long as
adding new files doesn't introduce overlap with additional base files.
The compaction picker must find the smallest key of the first base file
not included in the compaction to determine the exclusive upper bound
for expansion.

Previously, the compaction picker would seek to the compaction's largest
user key within the base level and then advance as long as a file's
largest key's user key was equal to the compaction's largest key's in
order to advance past the compaction's atomic compaction unit. This
correctly handled the case where the picked compaction included multiple
files with the same user key bounds. However, it didn't handle the case
where the picked compaction's last base file ended in a range deletion
sentinel AND the subsequent files ending in the same user key were _not_
included in the picked compaction.

Fix #944.

### CODE REVIEW

**Review by itsbilal — APPROVED** [review]
:lgtm: save for two minor comments, thanks for getting to the bottom of this quick!

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/955#-:-MIZQ5l2BxvbD3bIJ968:b-7gj7yy)* status: all files reviewed, 2 unresolved discussions (waiting on @jbowens and @petermattis)

___
*[compaction_picker.go, line 263 at r1](https://reviewable.io/reviews/cockroachdb/pebble/955#-MIZJ9T10wixAGJmIQBk:-MIZJ9T22H8w4MIKaJOU:b-xfzwwi) ([raw file](https://github.com/cockroachdb/pebble/blob/8c081e898f0a5ee29f82054d177d3dba0a0658c1/compaction_picker.go#L263)):*
> ```Go
> 			// bound. The file to use to set the largest base key would always
> 			// be the next one on that unbounded iterator.
> 			if pc.largest.Kind() == base.InternalKeyKindRangeDelete {
> ```

 I think the canonical RangeDel sentinel check is `pc.largest.Trailer == base.InternalKeyRangeDelSentinel`. 
___
*[compaction_picker.go, line 266 at r1](https://reviewable.io/reviews/cockroachdb/pebble/955#-MIZJg86AJnNt23Hgu2B:-MIZJg86AJnNt23Hgu2C:b-vv2iv2) ([raw file](https://github.com/cockroachdb/pebble/blob/8c081e898f0a5ee29f82054d177d3dba0a0658c1/compaction_picker.go#L266)):*
> ```Go
> 				// Advance exactly once to get to the first file after the
> 				// included base file.
> 				la = baseIter.Next()
> ```

Whoops. This was quite the oversight. Sorry for missing this in the earlier CR!
___
*[testdata/compaction_picker_L0, line 310 at r1](https://reviewable.io/reviews/cockroachdb/pebble/955#-MIZQBcv-xGoGy7TBuEc:-MIZQBcv-xGoGy7TBuEd:b-juah59) ([raw file](https://github.com/cockroachdb/pebble/blob/8c081e898f0a5ee29f82054d177d3dba0a0658c1/testdata/compaction_picker_L0#L310)):*
> ```
> define
> L0
>   001621:voooyd.MERGE.1261-voooyd.MERGE.1261
> ```

This seems like a test example pulled straight off of the metamorphic test example. Mind keeping it the same but changing keys to be single letters to make the ordering clearer?

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/955)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @itsbilal and @petermattis)

___
*[compaction_picker.go, line 263 at r1](https://reviewable.io/reviews/cockroachdb/pebble/955#-MIZJ9T10wixAGJmIQBk:-MIZagzBEQaZUOGnFUcv:bb6un1j) ([raw file](https://github.com/cockroachdb/pebble/blob/8c081e898f0a5ee29f82054d177d3dba0a0658c1/compaction_picker.go#L263)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

 I think the canonical RangeDel sentinel check is `pc.largest.Trailer == base.InternalKeyRangeDelSentinel`. 
</blockquote></details>

Done
___
*[compaction_picker.go, line 266 at r1](https://reviewable.io/reviews/cockroachdb/pebble/955#-MIZJg86AJnNt23Hgu2B:-MIZajFY-hK1eMzmfe0Q:b-4bdik3) ([raw file](https://github.com/cockroachdb/pebble/blob/8c081e898f0a5ee29f82054d177d3dba0a0658c1/compaction_picker.go#L266)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Whoops. This was quite the oversight. Sorry for missing this in the earlier CR!
</blockquote></details>

No worries, I missed it too!

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/955)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @itsbilal)

___
*[compaction_picker.go, line 266 at r1](https://reviewable.io/reviews/cockroachdb/pebble/955#-MIZJg86AJnNt23Hgu2B:-MIZuVrO-xRhUg0UvQtq:b-2x0qo2) ([raw file](https://github.com/cockroachdb/pebble/blob/8c081e898f0a5ee29f82054d177d3dba0a0658c1/compaction_picker.go#L266)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

No worries, I missed it too!
</blockquote></details>

Is this a bug in 20.2?

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/955)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @itsbilal)

___
*[compaction_picker.go, line 266 at r1](https://reviewable.io/reviews/cockroachdb/pebble/955#-MIZJg86AJnNt23Hgu2B:-MI_YvZA7jbCwHGMWXAI:b-ddbbad) ([raw file](https://github.com/cockroachdb/pebble/blob/8c081e898f0a5ee29f82054d177d3dba0a0658c1/compaction_picker.go#L266)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Is this a bug in 20.2?
</blockquote></details>

Yeah, it is.

**Pull request merged**
