### PR TITLE
db: update newIters callers to use new interface

### PR DESCRIPTION
**Pull request by jbowens**
Update the remaining users of tableNewIters.TODO to use the new interface and delete the TODO method.

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3525)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @jbowens)

___
*[`ingest.go` line 2055 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3525#-Nvmf3m78D13Xp1o35Uj:-Nvmf3m78D13Xp1o35Uk:b-zh1579) ([raw file](https://github.com/cockroachdb/pebble/blob/2f9b5ecdf60fa4c0b3b87b793913c681c3c60e32/ingest.go#L2055)):*
> ```Go
> 		}
> 		largestPointKey := m.LargestPointKey
> 		if !itersLoaded {
> ```

Won't itersLoaded always be true here?

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3525)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @RaduBerinde)

___
*[`ingest.go` line 2055 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3525#-Nvmf3m78D13Xp1o35Uj:-Nvmmpk6El64u3wpjtlE:b-h20hrv) ([raw file](https://github.com/cockroachdb/pebble/blob/2f9b5ecdf60fa4c0b3b87b793913c681c3c60e32/ingest.go#L2055)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Won't itersLoaded always be true here?
</blockquote></details>

ah yeah this is a vestige of an intermediary revision :sweat_smile: thanks

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3525#-:-Nvn8i--D2KJgca1nyL7:bnfp4nl)* status: 0 of 7 files reviewed, all discussions resolved

**Comment by jbowens** [comment]
tftr!

**Pull request merged**
