### PR TITLE
Replace `github.com/codahale/hdrhistogram` with `github.com/HdrHistogram/hdrhistogram-go`

### PR DESCRIPTION
**Pull request by muXxer**
The module was moved to another repository. See also #1224 

I used the chance to update all other modules to the latest version.

### CODE REVIEW

**Comment by nicktrav** [comment]
Thanks for the contribution, @muXxer!

It might be simpler for now to keep this PR focused just on the package rename, addressing https://github.com/cockroachdb/pebble/issues/1224.

There are some outstanding issues around some of our existing dependencies that we need to work through before we can update those, plus we'll probably want to do a bunch of benchmarking / sanity checks before bumping the versions. For example, #1706 is currently a blocker.

Does that sound reasonable?

**Comment by muXxer** [comment]
Alright, I will revert the update of the other modules in that case :)
Will do today :+1:

**Comment by muXxer** [comment]
Alright @nicktrav !
I replaced the `github.com/codahale/hdrhistogram` in the code, an then ran a `go mod tidy`.
The testify module was automatically updated by the `go mod tidy`. I guess that is fine.
Afterwards I ran a `go mod vendor`, to update the vendor folder.

**Comment by muXxer** [comment]
No other reviewers available? :smile:

**Comment by nicktrav** [comment]
Thanks for your contribution, @muXxer!

**Pull request merged**
