### PR TITLE
db: truncate range tombstones to containing file's atomic unit

### PR DESCRIPTION
**Pull request by jbowens**
Previous versions of Pebble (corresponding to CockroachDB v21.2 and earlier) did not truncate the range tombstones physically persisted to sstables and instead relied on read-time truncation. The same versions of Pebble could also split sstables within a level with a user key.

During compactions, Pebble previously would load the range deletion blocks for all input sstables upfront. All the input sstables' range deletion iterators would be included within the compaction merging iterator. Each of the files' range tombstones would be truncated to the contaning file's atomic compaction unit, and range tombstones outside the bounds of the file would be skipped.

In 37558663 we refactored this logic to use a "level iterator" to avoid opening all the files' range tombstones blocks upfront. This change accidentally began truncating the tombstones to the *compaction*'s atomic compaction unit, rather than the individual file's. This could allow an untruncated range deletion to delete newer keys within the range deletion's untruncated bounds.

Out of an abundance of caution, this commit reverts the change to compactions, reverting to the original logic that loads all files' range tombstones blocks upfront and fixes truncation to use the individual file's atomic compaction unit.

Informs cockroachdb/cockroach#89777.

### CODE REVIEW

**Comment by jbowens** [comment]
I'm still working on randomized tests to exercise this; it's a little tricky to force un-truncated bounds onto current Pebble.

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2015)* status: all files reviewed, 7 unresolved discussions (waiting on @itsbilal, @jbowens, and @nicktrav)

___
*[`compaction.go` line 1158 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2015#-NEfjEai3KzNxO2X1Dp4:-NEfjEai3KzNxO2X1Dp5:bty99s4) ([raw file](https://github.com/cockroachdb/pebble/blob/87d39b5179394f8f8f095c54cc5bfd76a6f0787f/compaction.go#L1158)):*
> ```Go
> 
> 			// Truncate the range tombstones returned by the iterator to the
> 			// upper bound of the atomic compaction unit. Note that we need do
> ```

I think we should expand this to say "atomic compaction unit of the file" (and why we do this -- we need to find a different user key so that we can truncate at that as an exclusive bound). And add an example with say one file ending at f#200 (and having a tombstone [c,k)) and the next one starting at f#190 and then the following starting at g#500. And maybe highlight why we should not use slice itself because [c,k) should not extend into the third file.
___
*[`compaction.go` line 1193 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2015#-NEfk8EhCQhTy-pwUPjm:-NEfk8EhCQhTy-pwUPjn:b-shwz4l) ([raw file](https://github.com/cockroachdb/pebble/blob/7e037ade079af01379d73915f9f8497162b25262/compaction.go#L1193)):*
> ```Go
> 		// rangedel iterators. This is safe now that range deletions are truncated
> 		// at file bounds; the merging iterator no longer needs to see all range
> 		// deletes for correctness.
> ```

Can you add a TODO for the LevelIter approach?
The correctness of the LevelIter relies on the fact that we don't have any more files where user keys straddle two files. That is, it requires that the earlier `expandToAtomicUnit` call be a noop, otherwise the rangedel (after truncation) will spill over from one file to another. Should we check that it is a noop and crash if it is? Alternatively we could check that it is a noop for `invariants.Enabled`.
___
*[`testdata/manual_compaction` line 1036 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2015#-NEfmPUh4_thyjYNcNTP:-NEfmPUi-h2-ab4TCLnD:b-8cht4l) ([raw file](https://github.com/cockroachdb/pebble/blob/87d39b5179394f8f8f095c54cc5bfd76a6f0787f/testdata/manual_compaction#L1036)):*
> ```
>   b.RANGEDEL.1:z
> L6
>   b.SET.0:b0
> ```

This files data should be deleted by the rangedel, yes?
___
*[`testdata/manual_compaction` line 1052 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2015#-NEfm_-Q8Y0itbPLoTrt:-NEfm_-Q8Y0itbPLoTru:b-v8rvyq) ([raw file](https://github.com/cockroachdb/pebble/blob/87d39b5179394f8f8f095c54cc5bfd76a6f0787f/testdata/manual_compaction#L1052)):*
> ```
> ----
> 6:
>   000010:[b#0,SET-b#0,SET]
> ```

Can we print the kv pairs in the LSM too, so it is obvious what survived?
___
*[`testdata/manual_compaction` line 1056 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2015#-NEfmhMqBVm83IVha7XU:-NEfmhMqBVm83IVha7XV:b-l59hnx) ([raw file](https://github.com/cockroachdb/pebble/blob/87d39b5179394f8f8f095c54cc5bfd76a6f0787f/testdata/manual_compaction#L1056)):*
> ```
> # Ensure an untruncated range tombstone (eg, written by an earlier version of
> # Pebble, Cockroach v21.2 or earlier) cannot delete newer keys outside the
> # contianing file's bounds.
> ```

containing
___
*[`testdata/manual_compaction` line 1065 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2015#-NEfnZdICLNH8L6aQbtY:-NEfnZdICLNH8L6aQbtZ:bb0vekg) ([raw file](https://github.com/cockroachdb/pebble/blob/87d39b5179394f8f8f095c54cc5bfd76a6f0787f/testdata/manual_compaction#L1065)):*
> ```
>   m.SET.1:bar
> L6
>   m.SET.0:bax
> ```

this m.SET.0 ought to be deleted, yes?
___
*[`testdata/manual_compaction` line 1110 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2015#-NEfnv3cDQKn_3-SBhzQ:-NEfnv3cDQKn_3-SBhzR:bsplnw5) ([raw file](https://github.com/cockroachdb/pebble/blob/87d39b5179394f8f8f095c54cc5bfd76a6f0787f/testdata/manual_compaction#L1110)):*
> ```
>   000016:[y#8,SET-y#8,SET]
> 6:
>   000006:[a#1,SET-g#72057594037927935,RANGEDEL]
> ```

this contains the [a,z) rangedel?

Can you also add a test where there are multiple files in L5 and an untruncated rangedel in L5 that should be limited in how much it expands.

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2015)* status: 1 of 3 files reviewed, 7 unresolved discussions (waiting on @itsbilal, @nicktrav, and @sumeerbhola)

___
*[`compaction.go` line 1158 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2015#-NEfjEai3KzNxO2X1Dp4:-NEgQrfc5N8k3osIB0UR:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/87d39b5179394f8f8f095c54cc5bfd76a6f0787f/compaction.go#L1158)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I think we should expand this to say "atomic compaction unit of the file" (and why we do this -- we need to find a different user key so that we can truncate at that as an exclusive bound). And add an example with say one file ending at f#200 (and having a tombstone [c,k)) and the next one starting at f#190 and then the following starting at g#500. And maybe highlight why we should not use slice itself because [c,k) should not extend into the third file.
</blockquote></details>

Done.
___
*[`compaction.go` line 1193 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2015#-NEfk8EhCQhTy-pwUPjm:-NEgRaQR5S97Jsyli81H:bkfvifw) ([raw file](https://github.com/cockroachdb/pebble/blob/7e037ade079af01379d73915f9f8497162b25262/compaction.go#L1193)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Can you add a TODO for the LevelIter approach?
The correctness of the LevelIter relies on the fact that we don't have any more files where user keys straddle two files. That is, it requires that the earlier `expandToAtomicUnit` call be a noop, otherwise the rangedel (after truncation) will spill over from one file to another. Should we check that it is a noop and crash if it is? Alternatively we could check that it is a noop for `invariants.Enabled`.

</blockquote></details>

Done.

I think we actually now have that guarantee in Cockroach starting in 23.1, since 22.2 blocks cluster version finalization on the compaction of all remaining split-user key files.
___
*[`testdata/manual_compaction` line 1036 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2015#-NEfmPUh4_thyjYNcNTP:-NEgS98nAX-QxYAmSiCk:b-koex8) ([raw file](https://github.com/cockroachdb/pebble/blob/87d39b5179394f8f8f095c54cc5bfd76a6f0787f/testdata/manual_compaction#L1036)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

This files data should be deleted by the rangedel, yes?
</blockquote></details>

That's right
___
*[`testdata/manual_compaction` line 1052 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2015#-NEfm_-Q8Y0itbPLoTrt:-NEgTSkG3gVAqXFh9m37:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/87d39b5179394f8f8f095c54cc5bfd76a6f0787f/testdata/manual_compaction#L1052)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Can we print the kv pairs in the LSM too, so it is obvious what survived?
</blockquote></details>

Done.
___
*[`testdata/manual_compaction` line 1056 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2015#-NEfmhMqBVm83IVha7XU:-NEgTT3-5PXA0ZrRytsN:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/87d39b5179394f8f8f095c54cc5bfd76a6f0787f/testdata/manual_compaction#L1056)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

containing
</blockquote></details>

Done.
___
*[`testdata/manual_compaction` line 1065 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2015#-NEfnZdICLNH8L6aQbtY:-NEgTd1JB9gLe4UO8wlP:bnjviix) ([raw file](https://github.com/cockroachdb/pebble/blob/87d39b5179394f8f8f095c54cc5bfd76a6f0787f/testdata/manual_compaction#L1065)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

this m.SET.0 ought to be deleted, yes?
</blockquote></details>

yeah, that's right. it only exists to prevent a trivial move compaction
___
*[`testdata/manual_compaction` line 1110 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2015#-NEfnv3cDQKn_3-SBhzQ:-NEgUF9C5z_7LsKC9VOL:b-v0pdba) ([raw file](https://github.com/cockroachdb/pebble/blob/87d39b5179394f8f8f095c54cc5bfd76a6f0787f/testdata/manual_compaction#L1110)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

this contains the [a,z) rangedel?

Can you also add a test where there are multiple files in L5 and an untruncated rangedel in L5 that should be limited in how much it expands.
</blockquote></details>

that's right.

**Review by sumeerbhola — APPROVED** [review]
:lgtm_strong: 

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2015#-:-NEgk5yu0cf0CgeDMY2h:b-uwkowd)* status: all files reviewed, 8 unresolved discussions (waiting on @itsbilal, @jbowens, and @nicktrav)

___
*[`compaction.go` line 1193 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2015#-NEfk8EhCQhTy-pwUPjm:-NEgjAraAC3VhwYavlpe:b-qeyp3w) ([raw file](https://github.com/cockroachdb/pebble/blob/7e037ade079af01379d73915f9f8497162b25262/compaction.go#L1193)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

Done.

I think we actually now have that guarantee in Cockroach starting in 23.1, since 22.2 blocks cluster version finalization on the compaction of all remaining split-user key files.
</blockquote></details>

Ah, so v22.2 Pebble code should not have been doing this LevelIter optimization, since it would be incorrect when the v22.2 code was running on a mixed version cluster that had not yet finished the migration. 
___
*[`compaction.go` line 1219 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2015#-NEgix4M-7CJcXOWhAc1:-NEgix4M-7CJcXOWhAc2:b-47tq2q) ([raw file](https://github.com/cockroachdb/pebble/blob/735463fe5971b3a9d9a62a812842afef8c131d41/compaction.go#L1219)):*
> ```Go
> 		// TODO(jackson): Use keyspan.LevelIter to avoid loading all the range
> 		// deletions into memory upfront. (See #2015, which reverted this.) This
> 		// requires there to be no user keys that are split between sstables
> ```

there will be...

**Review by jbowens — COMMENTED** [review]
tftr!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2015#-:-NEh-HhK-1pB4cYAnZPc:b-7ixx6c)* status: 2 of 3 files reviewed, 8 unresolved discussions (waiting on @itsbilal, @nicktrav, and @sumeerbhola)

___
*[`compaction.go` line 1219 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2015#-NEgix4M-7CJcXOWhAc1:-NEh-6OzDxNyy2bI6OZV:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/735463fe5971b3a9d9a62a812842afef8c131d41/compaction.go#L1219)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

there will be...
</blockquote></details>

Done.

**Pull request merged**
