### PR TITLE
db: reduce getInternal allocations of getIter and Iterator

### PR DESCRIPTION
**Pull request by moredure**

### CODE REVIEW

**Comment by moredure** [comment]
@sumeerbhola Fixed I guess, same error as before, please check maybe we need custom pool for iterators with getIter?

**Review by sumeerbhola — COMMENTED** [review]
Could you rebase on master and squash the commits -- currently the changes are spread across r2, r4, r5 all of which are tiny changes to `db.go` that are related, and r3 is empty. It is easier to see them in the same commit.

> please check maybe we need custom pool for iterators with getIter?

Yes, let's make a `getIterAllocPool`, instead of adding `getIter` to `iterAlloc`. 

And while you are here, can you also change `Iterator.Clone` in `iterator.go` to reuse the `prefixOrFullSeekKey`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1082#-:-MV1hEXz3ZDJbwgcDqbc:b823a5p)* status: 0 of 1 files reviewed, all discussions resolved

**Comment by moredure** [comment]
Yes, I'll try to squash them, I will leave getIter inside iterAlloc in my fork) But ok, I'll add an alternative pool for getIter structs and will fix  `prefixOrFullSeekKey` in Clone. Regarding getIter maybe we need custom Iterator? for getIter not for mergingIter?

**Review by sumeerbhola — COMMENTED** [review]
> Regarding getIter maybe we need custom Iterator? for getIter not for mergingIter, because of accessing many pools inside single code block seems may become slow?
> Yeap, getIterAllocPool sounds good, but why not to add getIter to iterAlloc and just not fill it when using IterAllocPull, it will be much cleaner to reside getIter and mergingIter inside iterAlloc.

I was imagining
```
type getIterAlloc struct {
	dbi                  Iterator
	getIter             getIter
}
```
I'm not sure where we would be "accessing many pools inside single code block". Can you elaborate?

This is sufficiently simpler than `iterAlloc` that putting it there seems like a hack.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1082#-:-MVSqq57D-9S-bFasmqo:b-qvf5bf)* status: 0 of 2 files reviewed, all discussions resolved

**Comment by moredure** [comment]
Recreated pull request for this https://github.com/cockroachdb/pebble/pull/1094

**Pull request closed without merging**
