### PR TITLE
db: refactor merging iterator's prefix handling for TrySeekUsingNext

### LINKED ISSUE #2174: github.com/cockroachdb/pebble/internal/metamorphic: TestMeta failed
github.com/cockroachdb/pebble/internal/metamorphic.TestMeta [failed](https://buildConfiguration/Cockroach_Nightlies_Pebble_Metamorphic/7866913?buildTab=log) with [artifacts](https://buildConfiguration/Cockroach_Nightlies_Pebble_Metamorphic/7866913?buildTab=artifacts#meta) on refs/heads/master @ [0d6d19018632](https://github.com/cockroachdb/pebble/commits/0d6d19018632):

```
=== PAUSE TestMeta/execution/random-012
=== CONT  TestMeta/execution/random-012
=== RUN   TestMeta/execution/random-014
=== PAUSE TestMeta/execution/random-014
=== CONT  TestMeta/execution/random-014
=== RUN   TestMeta/compare/standard-012
=== RUN   TestMeta/compare/standard-015
=== RUN   TestMeta/compare/standard-018
=== RUN   TestMeta/execution/random-025
=== PAUSE TestMeta/execution/random-025
=== CONT  TestMeta/execution/random-025
=== RUN   TestMeta/execution/standard-003
=== PAUSE TestMeta/execution/standard-003
=== CONT  TestMeta/execution/standard-003
=== RUN   TestMeta/execution/standard-010
=== PAUSE TestMeta/execution/standard-010
=== CONT  TestMeta/execution/standard-010
=== RUN   TestMeta/compare/random-006
=== RUN   TestMeta/compare/random-008
=== RUN   TestMeta/compare/standard-017
=== RUN   TestMeta/execution/random-006
=== PAUSE TestMeta/execution/random-006
=== CONT  TestMeta/execution/random-006
=== RUN   TestMeta/execution/random-017
=== PAUSE TestMeta/execution/random-017
=== CONT  TestMeta/execution/random-017
=== RUN   TestMeta/execution/standard-000
=== PAUSE TestMeta/execution/standard-000
=== CONT  TestMeta/execution/standard-000
=== RUN   TestMeta/execution/standard-009
=== PAUSE TestMeta/execution/standard-009
=== CONT  TestMeta/execution/standard-009
=== RUN   TestMeta/execution/standard-023
=== PAUSE TestMeta/execution/standard-023
=== CONT  TestMeta/execution/standard-023
=== RUN   TestMeta/execution/random-023
=== PAUSE TestMeta/execution/random-023
=== CONT  TestMeta/execution/random-023
=== RUN   TestMeta/execution/standard-007
=== PAUSE TestMeta/execution/standard-007
=== CONT  TestMeta/execution/standard-007
=== RUN   TestMeta/execution/standard-021
=== PAUSE TestMeta/execution/standard-021
=== CONT  TestMeta/execution/standard-021
=== RUN   TestMeta/compare/standard-003
=== RUN   TestMeta/compare/standard-004
=== RUN   TestMeta/compare/standard-008
=== RUN   TestMeta/execution/random-001
=== PAUSE TestMeta/execution/random-001
=== CONT  TestMeta/execution/random-001
```
<details><summary>Help</summary>
<p>
To reproduce, try:

```bash
go test -tags 'invariants' -exec 'stress -p 1' -timeout 0 -test.v -run TestMeta$ ./internal/metamorphic -seed 1670393323768375675 -ops "uniform:5000-10000"
```
</p>
</details>
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestMeta.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### PR DESCRIPTION
**Pull request by jbowens**
Builds off of #2151. This commit refactors the merging iterator's
handling of prefix-related invariants for enabling TrySeekUsingNext
optimizations when using SeekPrefixGE.

The TrySeekUsingNext optimization notes successively larger seek keys,
and attempts to use next to find the appropriate key in the later seeks,
avoiding seeking from scratch. In a level's file metadata, we now use
the presence of the TrySeekUsingNext flag to signal that we can Next
through the file metadata. This saves key comparisons, especially in
larger LSMs with many files within a level.

Ever since the introduction of #2048, we've encountered a slew of
metamorphic test failures due to interactions between this optimization
and prefix iteration. We've made various fixes in #2087, #2111, #2123
and #2151.

Most of these failures revolve around the progression of a level
iterator beyond the iterator's current iteration prefix. This is
problematic, because the incomplete view of the LSM during prefix
iteration can result in inconsistent positioning outside of the current
iterator prefix. The internal iterators do not guarantee that keys or
range deletions outside the prefix are observed.

This commit fixes the latest instance of this (#2174), and attempts to
restructure the code to clarify the required invariants. Now, any method
that may advance the iterator during prefix iteration (eg, nextEntry or
isNextEntryDeleted) check that the iteration prefix has not already been
exceeded. This check is only performed when the merging iterator is
advancing internal iterators of its own volition (eg, due to non-visible
keys or keys deleted by range tombstones). It does NOT perform this
check when the top-level Iterator Nexts the merging iterator because
of a user Next, a point-delete, etc. This means these prefix checks are
only redundant with the top-level Iterator Nexts in two cases:

  a) the heap root is deleted by a range tombstone
  b) the heap root is not visible at the iterator's sequence number

Both of these cases are expected to be rare, and the redundant prefix
check is expected to be insignificant.

Additionally, to obey these new stricter invariants, the interleaving
iterator is adjusted to exhaust the iterator when the remainder of a
prefix is masked by a range key. Besides ensuring invariants are
respected, this change provides a large benefit to prefix iteration
within a large swath of masked point keys.

```
name                                                                     old time/op  new time/op  delta
Iterator_RangeKeyMasking/range-keys-suffixes=@10/forward/seekprefix-24   59.8ms ± 2%  60.3ms ± 2%   +0.92%  (p=0.013 n=25+25)
Iterator_RangeKeyMasking/range-keys-suffixes=@10/forward/next-24         4.50ms ± 6%  4.52ms ± 3%     ~     (p=0.388 n=25+24)
Iterator_RangeKeyMasking/range-keys-suffixes=@10/backward-24             5.64ms ± 7%  5.51ms ± 3%   -2.26%  (p=0.001 n=25+25)
Iterator_RangeKeyMasking/range-keys-suffixes=@50/forward/seekprefix-24   64.0ms ± 5%  60.2ms ± 4%   -5.89%  (p=0.000 n=25+25)
Iterator_RangeKeyMasking/range-keys-suffixes=@50/forward/next-24         4.11ms ± 3%  4.16ms ± 5%   +1.06%  (p=0.040 n=25+24)
Iterator_RangeKeyMasking/range-keys-suffixes=@50/backward-24             4.94ms ± 3%  4.89ms ± 3%   -0.97%  (p=0.011 n=25+24)
Iterator_RangeKeyMasking/range-keys-suffixes=@75/forward/seekprefix-24   69.0ms ± 2%  60.1ms ± 2%  -12.88%  (p=0.000 n=22+24)
Iterator_RangeKeyMasking/range-keys-suffixes=@75/forward/next-24         2.55ms ± 2%  2.59ms ± 3%   +1.90%  (p=0.000 n=25+25)
Iterator_RangeKeyMasking/range-keys-suffixes=@75/backward-24             3.20ms ± 2%  3.21ms ± 3%     ~     (p=0.418 n=25+25)
Iterator_RangeKeyMasking/range-keys-suffixes=@100/forward/seekprefix-24   2.19s ± 3%   0.06s ± 2%  -97.27%  (p=0.000 n=24+25)
Iterator_RangeKeyMasking/range-keys-suffixes=@100/forward/next-24         346µs ± 2%   346µs ± 2%     ~     (p=0.898 n=24+25)
Iterator_RangeKeyMasking/range-keys-suffixes=@100/backward-24             687µs ± 3%   696µs ± 2%   +1.31%  (p=0.000 n=25+25)
```

Fix #2174.

### CODE REVIEW

**Review by nicktrav — APPROVED** [review]
Nice. Thanks for sprinkling the extra documentation around too.

:lgtm: - though perhaps wait for a second set of :eyes:.

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2178#-:-NIjI7dG64qwBdKcm9UZ:b1j8kqm)* status: all files reviewed, 2 unresolved discussions (waiting on @itsbilal, @jbowens, and @sumeerbhola)

___
*[`-- commits` line 18 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2178#-NIjFw_J7DGccMI-4Zzq):*
nit: final `,` -> `.`.
___
*[`merging_iter.go` line 559 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2178#-NIjGY5iAjs8QH8x9SbY:-NIjGY5iAjs8QH8x9SbZ:b-2n7jhf) ([raw file](https://github.com/cockroachdb/pebble/blob/a502d7a742d59df0937e37c60879b329b3f3665c/merging_iter.go#L559)):*
> ```Go
> 	if m.prefix != nil {
> 		n := m.split(key)
> 		return !bytes.Equal(m.prefix, key[:n])
> ```

nit: I realize the equality check is sufficient here. However, in a strict sense, isn't this method behaving more like `equalsPrefix`? Worth updating the method, or actually doing the comparison for `prefix(key) > m.prefix`?

**Review by jbowens — COMMENTED** [review]
The new invariant checking in `nextEntry` revealed another problem. Range key masking may result in the interleaving iterator Next-ing beyond the current iteration prefix. I made a fix to avoid Next-ing beyond a masked point if the masked point is already beyond the iteration prefix. I also documented this new variant we're adding on the internal iterator comment. I expect this change to have a large benefit to MVCCGets that are retrieving within a large swath of masked point keys. Previously, we'd next until we exhausted the merging iterator stopped surfacing keys or we found a non-masked point key. I'll try to get some numbers from a benchmark today.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2178#-:-NImadob4iHOKqjFJqB8:b-u4dg19)* status: 6 of 9 files reviewed, 2 unresolved discussions (waiting on @itsbilal, @nicktrav, and @sumeerbhola)

___
*[`merging_iter.go` line 559 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2178#-NIjGY5iAjs8QH8x9SbY:-NImfAP32quXwxzb4aDI:bv5qtd) ([raw file](https://github.com/cockroachdb/pebble/blob/a502d7a742d59df0937e37c60879b329b3f3665c/merging_iter.go#L559)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

nit: I realize the equality check is sufficient here. However, in a strict sense, isn't this method behaving more like `equalsPrefix`? Worth updating the method, or actually doing the comparison for `prefix(key) > m.prefix`?
</blockquote></details>

adjusted to `unequalPrefix`. I want to keep it in the negative (eg, as opposed to `equalsPrefix`) since if we're not in prefix iteration mode, it's a little nonsensical to return `true` from `equalsPrefix`.

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2178)* status: all files reviewed, 4 unresolved discussions (waiting on @nicktrav and @sumeerbhola)

___
*[`-- commits` line 38 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2178#-NInBiUXDipLVF3MeoAX):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

is b) rare?
This was a concern raised in https://github.com/cockroachdb/pebble/pull/2151#pullrequestreview-1201603747
</blockquote></details>

i'm not sure. i originally thought it was because snapshots are rare in Cockroach (and prefix iteration through a snapshot more rare, I believe), and the mutable memtable keys make up a small portion of the keys in a database. in thinking about it some more, i realized that successful bloom filter exclusions make it more likely that the next key in the mutable memtable will be a heap root.

an alternative: we require `InternalIterator` to return keys within the iteration prefix. if _n_ levels are unable to efficiently exclude the level through bloom filter checks, etc, then we must perform _n_ new prefix equality checks. however if _k_ prefix equality checks then exclude those levels, we reduce the size of the merging iterator heap to _n_-_k_, which reduces the heapify key comparisons by O(_k_).

in the (typical?) case that there are 0 or 1 keys with the prefix (even if _n_ is large), there's no regression. instead of our current O(_n_) heapify key _comparisons_ plus one prefix check in the top-level Iterator, we'd perform O(_n_) faster prefix checks.

in the case where _n_-_k_ ≥ 2 (multiple levels contain keys with the iteration prefix), i don't see how we'd avoid some regression, at least on seeks that do not then scan the remainder of the prefix.
___
*[`merging_iter.go` line 556 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2178#-NInCQEX2F2ZIChYVufK:-NInOsj89KliTbLBd0Zc:bdyudsh) ([raw file](https://github.com/cockroachdb/pebble/blob/41160ce452681839f0d144116e07530b7d719b3d/merging_iter.go#L556)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

is this performance sensitive? If yes, does this inline?
</blockquote></details>

it did not inline, so I manually inlined it.
___
*[`merging_iter.go` line 568 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2178#-NInDQyKBgjRm0YK0noY:-NInOxWJByWzfA47H_jy:b-u78rlh) ([raw file](https://github.com/cockroachdb/pebble/blob/41160ce452681839f0d144116e07530b7d719b3d/merging_iter.go#L568)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

same inlining question.
</blockquote></details>

this one also did not inline. I refactored it into a separate method that's only invoked within prefix iteration mode, so that only prefix-iteration mode needs to suffer the function call overhead.

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2178)* status: 9 of 10 files reviewed, 5 unresolved discussions (waiting on @itsbilal, @nicktrav, and @sumeerbhola)

___
*[`internal/keyspan/interleaving_iter.go` line 687 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2178#-NIoSr3V5SPAehT80uu6:-NIoSr3V5SPAehT80uu7:b-6khy5q) ([raw file](https://github.com/cockroachdb/pebble/blob/b83901c5b4ac6bb5edb83ef2235fa58fa82ebbff/internal/keyspan/interleaving_iter.go#L687)):*
> ```Go
> 						// all subsequent keys with the same prefix must also be
> 						// masked according to the key ordering. We can stop and
> 						// return nil.
> ```

missed this opportunity the first time around

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 3 of 6 files at r1, 1 of 3 files at r2, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2178#-:-NIt9Y1h65j3VJfCS5Oo:bg7igkv)* status: all files reviewed, 7 unresolved discussions (waiting on @itsbilal, @jbowens, and @nicktrav)

___
*[`-- commits` line 38 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2178#-NInBiUXDipLVF3MeoAX):*
> i realized that successful bloom filter exclusions make it more likely that the next key in the mutable memtable will be a heap root.

Hmm, I am a bit confused. What I was concerned about earlier is
```
		if !item.key.Visible(m.snapshot, m.batchSnapshot) {
			if m.prefix == nil {
				m.nextEntry(item)
			} else {
				m.maybeNextEntryWithinPrefix(item)
			}
			continue
		}
```
where the key found repeatedly matches the prefix and is not visible. And so we are doing repeated prefix comparisons when previously we did not. I buy the fact that we shouldn't be concerned about snapshots. So the remaining concern is a batch where the key is not visible due to the value of `m.batchSnapshot`. I didn't quite follow what that has to do with mutable memtables. Also, I think my worry was contrived -- I suspect this is not a real concern.

You raised a good point in that to keep iterating we are doing O(log heap-size) comparisons for each iteration step. And we are adding 1 more prefix comparison. 
If the top element is a prefix and not visible, it is likely to keep coming from the same level, so there are 2 heap comparisons involved (if there are >= 3 element in the heap) per step. So 2 heap comparisons + 1 prefix comparison. If that level would have its `InternalIterator` do the prefix comparison instead (as you outlined), it would just shift that prefix comparison into that `InternalIterator`. So it doesn't really save during iteration.

> in the (typical?) case that there are 0 or 1 keys with the prefix (even if n is large), there's no regression. instead of our current O(n) heapify key comparisons plus one prefix check in the top-level Iterator, we'd perform O(n) faster prefix checks.

This is compelling. I am not sure we need to do this now -- perhaps you could make an issue for a future optimization?
___
*[`-- commits` line 47 at r6](https://reviewable.io/reviews/cockroachdb/pebble/2178#-NIt3jvBDzydoW8_g0MX):*
nice
___
*[`merging_iter.go` line 555 at r6](https://reviewable.io/reviews/cockroachdb/pebble/2178#-NIt2lK23Qw9B-oNlkRC:-NIt2lK23Qw9B-oNlkRD:b-bc29s2) ([raw file](https://github.com/cockroachdb/pebble/blob/923535f4d10f5ac3a08910a490f8e2f8e9c3b399/merging_iter.go#L555)):*
> ```Go
> 
> // maybeNextEntryWithinPrefix steps to the next entry, as long as the iteration
> // prefix has not alreday been exceeded. If it has, it exhausts the iterator by
> ```

nit: already

**Review by jbowens — COMMENTED** [review]
tftrs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2178#-:-NJ6CTZUDh_Db7N04XAt:b-k7vcjh)* status: all files reviewed, 6 unresolved discussions (waiting on @itsbilal, @nicktrav, and @sumeerbhola)

___
*[`-- commits` line 38 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2178#-NInBiUXDipLVF3MeoAX):*
>  I didn't quite follow what that has to do with mutable memtables.

I think an iterator's mutable memtable iterator can encounter keys (in the arenaskl skiplist) committed after the iterator was opened, so these newer keys would be filtered out here.

> perhaps you could make an issue for a future optimization?

filed #2182.

**Pull request merged**
