### PR TITLE
colblk: implement block.DataBlockIterator

### PR DESCRIPTION
**Pull request by jbowens**
Add a DataBlockIterConfig type that wraps a colblk.DataBlockIter and completes
the remainder of the block.DataBlockIterator interface. We choose to implement
the interface on this wrapper type to maintain configuration state (the
KeySchema and lazy value retriever) across usages of for individual blocks,
leaving DataBlockIter to be completely reset for each new block use.

### CODE REVIEW

**Comment by RaduBerinde** [comment]
It feels a bit strange that the iterator interface is implemented by a type named "Config". Could we rename the inner DataBlockInner type instead? Does that type still need to be exported?

**Comment by jbowens** [comment]
> It feels a bit strange that the iterator interface is implemented by a type named "Config". Could we rename the inner DataBlockInner type instead? Does that type still need to be exported?

It's also used. The inner type is really best described as the iterator; it implements the logic of iteration. The outer type is adds the sugar of retaining a block handle and maintaining its reference count until `Close`. We could rename the outer type to something more explicit, like `DataBlockIterWithHandle` or the like?

**Comment by RaduBerinde** [comment]
What do you think about "MultiDataBlockIter"?

**Review by jbowens — COMMENTED** [review]
> What do you think about "MultiDataBlockIter"?

sgtm

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3937#-:-O7UIE9D-DCWtnPmesEo:b-gmt1mc)* status: 0 of 8 files reviewed, all discussions resolved (waiting on @itsbilal and @sumeerbhola)

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r1, 1 of 6 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3937#-:-O7UQ4tv2u3f2SXJoViA:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @itsbilal, @jbowens, and @sumeerbhola)

___
*[`-- commits` line 12 at r4](https://reviewable.io/reviews/cockroachdb/pebble/3937#-O7UPwfG-rUS75Q9jM6i):*
[nit] MultiDataBlockIter

**Review by itsbilal — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r1, 1 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3937#-:-O7UUnpU9046EkkRjQH_:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @jbowens and @sumeerbhola)

___
*[`sstable/colblk/data_block.go` line 652 at r4](https://reviewable.io/reviews/cockroachdb/pebble/3937#-O7UTEET4rDvIS4qmPL6:-O7UTEET4rDvIS4qmPL7:bbpna62) ([raw file](https://github.com/cockroachdb/pebble/blob/74d34bb6d7e5f96ab8344f929200d049300ae5ea/sstable/colblk/data_block.go#L652)):*
> ```Go
> // MultiDataBlockIter wraps a DataBlockIter, implementing the block package's
> // DataBlockIterator. MultiDataBlockIter retains configuration (the KeySchema
> // and lazy value retriever) across inititalization for additional blocks. It
> ```

nit: initialization

**Comment by jbowens** [comment]
TFTRs!

**Pull request merged**
