### PR TITLE
db: reduce getInternal allocations of getIter and Iterator

### PR DESCRIPTION
**Pull request by moredure**
@sumeerbhola
In theory repeated conditions and two iterAlloc and getIterAlloc fields inside Iterator structure can be ommited by utilizing interface with three methods SetKeyBuf and SetPrefixKey... and Release to release struct to specific pool (iterAllocPool or getIterAllocPool),   if it's ok for you I can modify this.
Smth like this? https://github.com/cockroachdb/pebble/pull/1096

### CODE REVIEW

**Comment by moredure** [comment]
In theory repeated conditions for getIterAlloc and iterAlloc can be ommited by utilizing interface with two methods SetKeyBuf and SetPrefixKey..., if it's ok for you I can modify this.

**Comment by moredure** [comment]
Smth like this? https://github.com/cockroachdb/pebble/pull/1096

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
was on vacation, hence the delay. Only some minor comments.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1094#-:-MX2lxB0AsGwRi1cREvK:b3muw0k)* status: all files reviewed, 4 unresolved discussions (waiting on @moredure)

___
*[db.go, line 382 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1094#-MX2mURiBrS3rDEua1yr:-MX2mURiBrS3rDEua1ys:b5cdhyo) ([raw file](https://github.com/cockroachdb/pebble/blob/9db7363a7a8fe73785514d8f795821781bd85765/db.go#L382)):*
> ```Go
> 	dbi                 Iterator
> 	keyBuf              []byte
> 	prefixOrFullSeekKey []byte
> ```

we never seek the `Iterator` in the code called from `DB.getInternal` so we don't need to bother with including `prefixOrFullSeekKey` here.
___
*[iterator.go, line 1040 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1094#-MX2n82B48b9XMTuTHC7:-MX2n82B48b9XMTuTHC8:bl8k1lm) ([raw file](https://github.com/cockroachdb/pebble/blob/9db7363a7a8fe73785514d8f795821781bd85765/iterator.go#L1040)):*
> ```Go
> 		iterAllocPool.Put(alloc)
> 	} else if alloc := i.getIterAlloc; alloc != nil {
> 		const maxKeyBufCacheSize = 4 << 10 // 4 KB
> ```

can you hoist this const before the if-else block since it is the same in both paths.
___
*[iterator.go, line 1046 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1094#-MX2n1ap59fA1pVzTebT:-MX2n1ap59fA1pVzTebU:b-o3l3pu) ([raw file](https://github.com/cockroachdb/pebble/blob/9db7363a7a8fe73785514d8f795821781bd85765/iterator.go#L1046)):*
> ```Go
> 			alloc.keyBuf = i.keyBuf
> 		}
> 		if cap(i.prefixOrFullSeekKey) >= maxKeyBufCacheSize {
> ```

this code for `prefixOrFullSeekKey` will go away based on my previous comment
___
*[iterator.go, line 1148 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1094#-MX2nz4nA4wN02TfBloZ:-MX2nz4nA4wN02TfBlo_:b-h48k8o) ([raw file](https://github.com/cockroachdb/pebble/blob/9db7363a7a8fe73785514d8f795821781bd85765/iterator.go#L1148)):*
> ```Go
> 		readState:           readState,
> 		keyBuf:              buf.keyBuf,
> 		prefixOrFullSeekKey: buf.prefixOrFullSeekKey,
> ```

Glad you noticed this.

**Comment by moredure** [comment]
Hi, @sumeerbhola, what do you think of version with interface https://github.com/cockroachdb/pebble/pull/1096 ?

**Comment by moredure** [comment]
___
*[db.go, line 382 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1094#-MX2mURiBrS3rDEua1yr:-MXWLyidAVkSGyJs_pu0:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/9db7363a7a8fe73785514d8f795821781bd85765/db.go#L382)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

we never seek the `Iterator` in the code called from `DB.getInternal` so we don't need to bother with including `prefixOrFullSeekKey` here.
</blockquote></details>

Done.

**Comment by moredure** [comment]
___
*[iterator.go, line 1040 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1094#-MX2n82B48b9XMTuTHC7:-MXWM2u93JRVQ77329U-:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/9db7363a7a8fe73785514d8f795821781bd85765/iterator.go#L1040)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

can you hoist this const before the if-else block since it is the same in both paths.
</blockquote></details>

Done.

**Comment by moredure** [comment]
___
*[iterator.go, line 1046 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1094#-MX2n1ap59fA1pVzTebT:-MXWM3xU8pGCCEOX8FFO:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/9db7363a7a8fe73785514d8f795821781bd85765/iterator.go#L1046)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

this code for `prefixOrFullSeekKey` will go away based on my previous comment
</blockquote></details>

Done.

**Comment by moredure** [comment]
___
*[iterator.go, line 1148 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1094#-MX2nz4nA4wN02TfBloZ:-MXWM5og1S5tTb4hJ926:b-ucfkn4) ([raw file](https://github.com/cockroachdb/pebble/blob/9db7363a7a8fe73785514d8f795821781bd85765/iterator.go#L1148)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Glad you noticed this.
</blockquote></details>

Thanks.

**Review by moredure — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1094)* status: all files reviewed, 4 unresolved discussions (waiting on @sumeerbhola)

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1094#-:-MXX5nsf2Iny5K0BHzte:bg7igkv)* status: all files reviewed, 4 unresolved discussions (waiting on @sumeerbhola)

**Comment by moredure** [comment]
Feel free to merge :)

**Comment by sumeerbhola** [comment]
@moredure Thanks for contributing this.

**Pull request merged**
