### PR TITLE
sstable: support Zstandard

### PR DESCRIPTION
**Pull request by kennytm**
Supports reading and writing SST files compressed with Zstd algorithm (using [DataDog/zstd](https://pkg.go.dev/github.com/DataDog/zstd) when CGO is enabled, and [klauspost/compress/zstd](https://pkg.go.dev/github.com/klauspost/compress/zstd) when CGO is disabled). The reader is compatible with SSTs generated from RocksDB.

### CODE REVIEW

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
Thanks for contributing this!

> Reviewed 3 of 3 files at r1, 30 of 157 files at r2, 5 of 5 files at r3, 3 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1058#-:-MRwVm3s3pm1Qqq4K8sP:bcxdqhg)* status: 41 of 170 files reviewed, 6 unresolved discussions (waiting on @kennytm)

___
*[sstable/compression.go, line 29 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1058#-MRvtQNB4mDdOaK7CNhN:-MRvtQNB4mDdOaK7CNhO:bok1067) ([raw file](https://github.com/cockroachdb/pebble/blob/b7fb62f3040166c3cee710d0fc7b7a03a76cbad0/sstable/compression.go#L29)):*
> ```Go
> 		decodedLen, err = snappy.DecodedLen(b)
> 	case zstdCompressionBlockType:
> 		// this is also used by zlib, bzip2 and lz4
> ```

I don't understand this comment about "also used". Where is it "also used", since here it is only for `zstdCompressionBlockType`?
___
*[sstable/compression.go, line 40 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1058#-MRvu1FG-87_syDfEvnf:-MRvu1FG-87_syDfEvng:b-15tduq) ([raw file](https://github.com/cockroachdb/pebble/blob/b7fb62f3040166c3cee710d0fc7b7a03a76cbad0/sstable/compression.go#L40)):*
> ```Go
> 	}
> 
> 	// allocate sufficient space from the cache.
> ```

nit: can you capitalize the start of the sentence in all these comments.
___
*[sstable/compression.go, line 49 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1058#-MRvuHp5CUPQs0c8-X6d:-MRvuHp5CUPQs0c8-X6e:b-5om68l) ([raw file](https://github.com/cockroachdb/pebble/blob/b7fb62f3040166c3cee710d0fc7b7a03a76cbad0/sstable/compression.go#L49)):*
> ```Go
> 	}()
> 
> 	// perform decompression.
> ```

Can you add a comment like the following
// NB: the value of `b` for snappy is different than the other cases since it includes the length varint at the front, while for the others it has already been stripped off. The implementation of snappy.Decode handles this correctly.
___
*[sstable/compression_cgo.go, line 20 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1058#-MRwS23l7dNTXi9Js-Zw:-MRwS23l7dNTXi9Js-Zx:basyyvc) ([raw file](https://github.com/cockroachdb/pebble/blob/b7fb62f3040166c3cee710d0fc7b7a03a76cbad0/sstable/compression_cgo.go#L20)):*
> ```Go
> 	return zstd.Decompress(decodedBuf, b)
> }
> ```

can you add a comment like
// encodeZstd compresses b, into a byte slice prefixed by compressedBuf[:varIntLen]. It reuses compressedBuf, if it has sufficient sufficient length.
// It returns the encoded byte slice.

Similarly for the function in `compression_nocgo.go`. 
___
*[sstable/table.go, line 161 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1058#-MRva8eB40JsTsMkwaTi:-MRva8eB40JsTsMkwaTj:bn365xm) ([raw file](https://github.com/cockroachdb/pebble/blob/4bb8422d0515fdcd5722f7e484eeedc8427e5aef/sstable/table.go#L161)):*
> ```Go
> 	// They are different from the Compression constants because the latter
> 	// are designed so that the zero value of the Compression type means to
> 	// use the default compression (which is snappy).
> ```

can you add a comment that not all compression types listed here are supported.
___
*[sstable/writer.go, line 477 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1058#-MRwSrzg4094EOkZAEYY:-MRwSrzg4094EOkZAEYZ:bg1vmi1) ([raw file](https://github.com/cockroachdb/pebble/blob/b7fb62f3040166c3cee710d0fc7b7a03a76cbad0/sstable/writer.go#L477)):*
> ```Go
> 	blockType, compressed := compressBlock(compression, b, w.compressedBuf)
> 	if blockType != noCompressionBlockType && cap(compressed) > cap(w.compressedBuf) {
> 		w.compressedBuf = compressed
> ```

I think this needs to be
`w.compressedBuf = compressed[:cap(compressed)]`
as it was in the old code, since
- snappy.Encode only uses the length of the `dst` parameter, and not the capacity.
- The varint writing code in `compressBlock` is also looking at `len(compressedBuf)`.

Otherwise we'll not use all of what was allocated previously and then have to reallocate unnecessarily.

I think it would be good to run BenchmarkWriter and add a case for zstd. I realize that benchmark is very simplistic but having before/after numbers for Snappy and Snappy/Zstd comparison numbers would be helpful.
And if you are feeling up to it, adding a BenchmarkReader that just ploughs through all the keys (can be as trivial as BenchmarkReader) would be a good starting point.

**Review by kennytm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1058)* status: 36 of 171 files reviewed, 5 unresolved discussions (waiting on @sumeerbhola)

___
*[sstable/compression.go, line 29 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1058#-MRvtQNB4mDdOaK7CNhN:-MSPWZs--HHSu4OPomND:bkgmb65) ([raw file](https://github.com/cockroachdb/pebble/blob/b7fb62f3040166c3cee710d0fc7b7a03a76cbad0/sstable/compression.go#L29)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I don't understand this comment about "also used". Where is it "also used", since here it is only for `zstdCompressionBlockType`?
</blockquote></details>

oh, this is if in the future we also support zlib/bzip2/lz4 compressed SSTs, the same code will be used for them too. improved the comment.
___
*[sstable/compression.go, line 49 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1058#-MRvuHp5CUPQs0c8-X6d:-MSPXFSCAVQZCwoqAohf:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/b7fb62f3040166c3cee710d0fc7b7a03a76cbad0/sstable/compression.go#L49)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Can you add a comment like the following
// NB: the value of `b` for snappy is different than the other cases since it includes the length varint at the front, while for the others it has already been stripped off. The implementation of snappy.Decode handles this correctly.
</blockquote></details>

Done.
___
*[sstable/compression_cgo.go, line 20 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1058#-MRwS23l7dNTXi9Js-Zw:-MSPd4e75MllrRwWihgl:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/b7fb62f3040166c3cee710d0fc7b7a03a76cbad0/sstable/compression_cgo.go#L20)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

can you add a comment like
// encodeZstd compresses b, into a byte slice prefixed by compressedBuf[:varIntLen]. It reuses compressedBuf, if it has sufficient sufficient length.
// It returns the encoded byte slice.

Similarly for the function in `compression_nocgo.go`. 
</blockquote></details>

Done.
___
*[sstable/table.go, line 161 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1058#-MRva8eB40JsTsMkwaTi:-MSPdHeL8r90GUsGib5V:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/4bb8422d0515fdcd5722f7e484eeedc8427e5aef/sstable/table.go#L161)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

can you add a comment that not all compression types listed here are supported.
</blockquote></details>

Done.
___
*[sstable/writer.go, line 477 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1058#-MRwSrzg4094EOkZAEYY:-MSPdkeJ9So3F_iSiBbB:b-jngdq1) ([raw file](https://github.com/cockroachdb/pebble/blob/b7fb62f3040166c3cee710d0fc7b7a03a76cbad0/sstable/writer.go#L477)):*
> adding a BenchmarkReader that just ploughs through all the keys (can be as trivial as BenchmarkReader) would be a good starting point.

hmm seems this is equivalent to the existing BenchmarkTableIterNext, so i've repurposed those 4 benchmarks to include zstd benchmarks too.

**Comment by kennytm** [comment]
Benchmark output:

```console
$ go test ./sstable -bench='Benchmark(Writer|TableIter)'
goos: windows
goarch: amd64
pkg: github.com/cockroachdb/pebble/sstable
BenchmarkTableIterSeekGE/restart=16,compression=Snappy-8                  655915              1766 ns/op
BenchmarkTableIterSeekGE/restart=16,compression=ZSTD-8                    616974              2033 ns/op
BenchmarkTableIterSeekLT/restart=16,compression=Snappy-8                  552733              1860 ns/op
BenchmarkTableIterSeekLT/restart=16,compression=ZSTD-8                    659402              1697 ns/op
BenchmarkTableIterNext/restart=16,compression=Snappy-8                  42579070                27.3 ns/op
BenchmarkTableIterNext/restart=16,compression=ZSTD-8                    38866500                27.7 ns/op
BenchmarkTableIterPrev/restart=16,compression=Snappy-8                  24703309                46.1 ns/op
BenchmarkTableIterPrev/restart=16,compression=ZSTD-8                    25080805                46.3 ns/op
BenchmarkWriter/Default-8                                                      9         137806867 ns/op
BenchmarkWriter/Zstd-8                                                         3         397259533 ns/op
PASS
ok      github.com/cockroachdb/pebble/sstable   60.488s

$ CGO_ENABLED=0 go test ./sstable -bench='Benchmark(Writer|TableIter)'
goos: windows
goarch: amd64
pkg: github.com/cockroachdb/pebble/sstable
BenchmarkTableIterSeekGE/restart=16,compression=Snappy-8                  603267              1696 ns/op
BenchmarkTableIterSeekGE/restart=16,compression=ZSTD-8                    535596              1940 ns/op
BenchmarkTableIterSeekLT/restart=16,compression=Snappy-8                  688657              1627 ns/op
BenchmarkTableIterSeekLT/restart=16,compression=ZSTD-8                    546931              1834 ns/op
BenchmarkTableIterNext/restart=16,compression=Snappy-8                  41347694                27.4 ns/op
BenchmarkTableIterNext/restart=16,compression=ZSTD-8                    35871962                29.6 ns/op
BenchmarkTableIterPrev/restart=16,compression=Snappy-8                  15585882                65.6 ns/op
BenchmarkTableIterPrev/restart=16,compression=ZSTD-8                    21016876                51.8 ns/op
BenchmarkWriter/Default-8                                                      9         131863667 ns/op
BenchmarkWriter/Zstd-8                                                         1        3839603700 ns/op
PASS
ok      github.com/cockroachdb/pebble/sstable   105.508s
```

Basically:

* No significant difference on *read* speed between snappy and zstd. Seek with zstd seems slower when CGo is disabled.
* Zstd compression is 3× as slow as snappy when CGo enabled, and 30× as slow when CGo disabled. This is somewhat expected since Zstd is mainly about space, not speed. The [RocksDB wiki](https://github.com/facebook/rocksdb/wiki/Compression) recommends LZ4 if speed is a concern.

**Review by sumeerbhola — APPROVED** [review]
This looks great!
:lgtm: 

> Reviewed 1 of 157 files at r2, 1 of 5 files at r4, 5 of 5 files at r5, 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1058#-:-MScO6nA78TdeLd3zBUM:b-tetsux)* status: 45 of 171 files reviewed, 6 unresolved discussions (waiting on @kennytm and @sumeerbhola)

___
*[sstable/reader_test.go, line 439 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1058#-MScLkYZ2TgD3mcga7aI:-MScLkYZ2TgD3mcga7aJ:b97jdoo) ([raw file](https://github.com/cockroachdb/pebble/blob/6949ae578cafc25d9a9549482f56110159010eec/sstable/reader_test.go#L439)):*
> ```Go
> }
> 
> func TestBytesIterated(t *testing.T) {
> ```

Can you hoist the `blockSizes` variable from `testBytesIteratedWithCompression` into this function and pass it as a parameter. It is confusing to not see `blockSizes` and the `maxNumEntries` in the same place given that they need to have the same length. That change will also make your comment below about zstd slowness easier to comprehend for the reader.

**Review by kennytm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1058)* status: 44 of 171 files reviewed, 6 unresolved discussions (waiting on @sumeerbhola)

___
*[sstable/reader_test.go, line 439 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1058#-MScLkYZ2TgD3mcga7aI:-MSeKe015s-p3CHlwslS:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/6949ae578cafc25d9a9549482f56110159010eec/sstable/reader_test.go#L439)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Can you hoist the `blockSizes` variable from `testBytesIteratedWithCompression` into this function and pass it as a parameter. It is confusing to not see `blockSizes` and the `maxNumEntries` in the same place given that they need to have the same length. That change will also make your comment below about zstd slowness easier to comprehend for the reader.
</blockquote></details>

Done.

**Review by sumeerbhola — APPROVED** [review]
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1058)* status: 45 of 171 files reviewed, 6 unresolved discussions (waiting on @sumeerbhola)

**Pull request merged**
