### PR TITLE
db: fix up a few more tests

### PR DESCRIPTION
**Pull request by RaduBerinde**
Add `CheckOrdering` and fix violations for some compaction tests.

### CODE REVIEW

**Review by jbowens — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3533)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @RaduBerinde)

___
*[`compaction_test.go` line 2362 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3533#-Nw57oqW4EOpbWIQo6qU:-Nw57oqW4EOpbWIQo6qV:bu0dtie) ([raw file](https://github.com/cockroachdb/pebble/blob/f2b32707c751710c196ba5893c5600f7a240b98e/compaction_test.go#L2362)):*
> ```Go
> 
> 		// TODO(radu): this is a hack, make the test specify correct keys or
> 		// simplify the input to just provide user keys.
> ```

I didn't follow why this is necessary. Seems like we'd want the test definition to specify internal key bounds, so that we can test that InuseKeyRanges properly handles them?

**Comment by RaduBerinde** [comment]
*[`compaction_test.go` line 2362 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3533#-Nw57oqW4EOpbWIQo6qU:-Nw5FssR6nQ7ShTAD1sz:bm8er3z) ([raw file](https://github.com/cockroachdb/pebble/blob/f2b32707c751710c196ba5893c5600f7a240b98e/compaction_test.go#L2362)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

I didn't follow why this is necessary. Seems like we'd want the test definition to specify internal key bounds, so that we can test that InuseKeyRanges properly handles them?
</blockquote></details>

Yeah, that was what I meant by "specify correct keys". We should just switch to the regular meta parsing function, but all the tests will need to be fixed up. I'm making more changes on the in-use ranges so I plan to fix them up later.

**Comment by RaduBerinde** [comment]
*[`compaction_test.go` line 2362 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3533#-Nw57oqW4EOpbWIQo6qU:-Nw5N6jEDMPgJ3KxRAQ_:b4ah0z1) ([raw file](https://github.com/cockroachdb/pebble/blob/f2b32707c751710c196ba5893c5600f7a240b98e/compaction_test.go#L2362)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Yeah, that was what I meant by "specify correct keys". We should just switch to the regular meta parsing function, but all the tests will need to be fixed up. I'm making more changes on the in-use ranges so I plan to fix them up later.
</blockquote></details>

Actually, maybe this is the better time to do it, let me give it a shot.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3533)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @jbowens)

___
*[`compaction_test.go` line 2362 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3533#-Nw57oqW4EOpbWIQo6qU:-Nw5futp68l3MwBhRGRo:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/f2b32707c751710c196ba5893c5600f7a240b98e/compaction_test.go#L2362)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Actually, maybe this is the better time to do it, let me give it a shot.
</blockquote></details>

Done.

**Review by jbowens — APPROVED** [review]
:lgtm_strong: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3533#-:-Nw5ilWI1l5zjzkiqqq-:b-uwkowd)* status: 0 of 4 files reviewed, 1 unresolved discussion

**Comment by RaduBerinde** [comment]
TFTR!

**Pull request merged**
