### PR TITLE
db: add format major versions and migrations for min table format

### PR DESCRIPTION
**Pull request by nicktrav**
In order to allow table properties to be deprecated, and ultimately
removed, all SSTables in a DB must have a table format of at least
Pebblev1 (block properties).

Add a format major version and associated migration to mark all
pre-Pebblev1 SSTables for compaction. In the absence of regular
compaction activity, compactions will be scheduled to rewrite the marked
tables. This format major version migration will appear in 22.2.

Add a second format major version and migration to compact all tables
marked by the previous migration. This migration blocks upgrading to
subsequent format major versions until the marked tables have been
re-written. This format major version is planned for 23.1, along with
the removal of the table properties code.

Touches cockroachdb/cockroach#82678.

### CODE REVIEW

**Comment by nicktrav** [comment]
Seems like I might have missed something with the locking (see #1833). Going to keep digging there.

**Review by jbowens — COMMENTED** [review]
> Reviewed 2 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1832)* status: 2 of 9 files reviewed, 3 unresolved discussions (waiting on @jbowens and @nicktrav)

___
*[`-- commits` line 23 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1832#-N8Prj6x0t-vqFIaQtw_):*
good catch
___
*[`format_major_version.go` line 86 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1832#-N8PnDwH90Mad61csNqf:-N8PnDwH90Mad61csNqg:b6q4270) ([raw file](https://github.com/cockroachdb/pebble/blob/e2802d743e0f5735f6bd42f86e5df6ae53bb9304/format_major_version.go#L86)):*
> ```Go
> 	FormatSplitUserKeysMarked
> 
> 	// 22.2 versions.
> ```

good idea to segment these
___
*[`format_major_version.go` line 547 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1832#-N8PovgPBk4MI30i4G1F:-N8PovgPBk4MI30i4G1G:bjpihth) ([raw file](https://github.com/cockroachdb/pebble/blob/e2802d743e0f5735f6bd42f86e5df6ae53bb9304/format_major_version.go#L547)):*
> ```Go
> 			// and move compactions only apply to compactions with a single file
> 			// in the start level, but we already know these files have
> 			// multi-file atomic compaction units.
> ```

This argument doesn't apply to these sstables. I wonder if instead of this tactic where we try to `Find` the file in the LSM, we can refactor the `fileMetadata.Compacting` field into an enum. That field is set to true while a file is party to a compaction [not sure, but it's probably left as true indefinitely]. We could add a new enum state that represents that the file _was_ compacted and is now unlinked from the most-recent LSM.

**Review by nicktrav — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1832)* status: 2 of 9 files reviewed, 3 unresolved discussions (waiting on @jbowens and @nicktrav)

___
*[`format_major_version.go` line 547 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1832#-N8PovgPBk4MI30i4G1F:-N8VhpwlCbQdXmt2UXsr:bicov21) ([raw file](https://github.com/cockroachdb/pebble/blob/e2802d743e0f5735f6bd42f86e5df6ae53bb9304/format_major_version.go#L547)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

This argument doesn't apply to these sstables. I wonder if instead of this tactic where we try to `Find` the file in the LSM, we can refactor the `fileMetadata.Compacting` field into an enum. That field is set to true while a file is party to a compaction [not sure, but it's probably left as true indefinitely]. We could add a new enum state that represents that the file _was_ compacted and is now unlinked from the most-recent LSM.
</blockquote></details>

Ah - good catch. There's a bug here. A table being marked as pre-Pebblev1 could be moved-compacted to a lower level. The existing check only considers the table's original level, in which case we'd not mark it.

Here's how I'm interpreting your proposal:

- we keep `findFn` to collect the slice of files to mark (this comes from a possibly stale version) - i.e. the "found files" slice of `[]*fileMetadata`
- we re-acquire the `DB.mu`, which guards the `fileMetadata.Compacting` field
- for each found file, check if this file was compacted already (using new enum state)
  - if compacted, continue - nothing to do, a compaction did the work already and this file is no longer part of the LSM
  - if not compacted - mark it as eligible for compaction; increment stats

Possible enum states:
- `notCompacting` (the `false` / default case of the field in its current form)
- `needsCompaction` (a signal that the file has been "marked but not yet compacted")
- `compacting` (the `true` case of the field in its current form)
- `compacted` (a new, post-compaction state, after which the file will eventually fall out of the LSM - after refs fall to zero)

Valid state transitions:

- `notCompacting` -> `needsCompaction` - covers the case where we're marking files
- `needsCompaction` -> `compacting` and `notCompacting -> compacting` - when a compaction is picked and scheduled, the field is unconditionally set to `compacting` via `addInProgressCompaction`.
- `compacting -> compacted` - compaction is complete. This table was the input to a compaction, with an output table that renders this table obsolete.
- `compacting -> notCompacting` - a special case for a move compaction - in the future it could be compacted again (move-d, or a traditional compaction)

It looks like `removeInProgressCompaction` currently unconditionally sets `f.Compacting = false` when a compaction is done, so there may be implications to leaving a compacted table's state as `compacted` (i.e. the semantics change a bit).

There's also the MANIFEST to consider. However, if we went with the enum, which now encodes a `needsCompaction` state, this might make `MarkedForCompaction` obsolete.

Thoughts? I'll probably want to split this enum piece out.

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1832)* status: 2 of 9 files reviewed, 3 unresolved discussions (waiting on @jbowens and @nicktrav)

___
*[`format_major_version.go` line 547 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1832#-N8PovgPBk4MI30i4G1F:-N8YyRWKELKaczmlMOVn:b-nqir2b) ([raw file](https://github.com/cockroachdb/pebble/blob/e2802d743e0f5735f6bd42f86e5df6ae53bb9304/format_major_version.go#L547)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

Ah - good catch. There's a bug here. A table being marked as pre-Pebblev1 could be moved-compacted to a lower level. The existing check only considers the table's original level, in which case we'd not mark it.

Here's how I'm interpreting your proposal:

- we keep `findFn` to collect the slice of files to mark (this comes from a possibly stale version) - i.e. the "found files" slice of `[]*fileMetadata`
- we re-acquire the `DB.mu`, which guards the `fileMetadata.Compacting` field
- for each found file, check if this file was compacted already (using new enum state)
  - if compacted, continue - nothing to do, a compaction did the work already and this file is no longer part of the LSM
  - if not compacted - mark it as eligible for compaction; increment stats

Possible enum states:
- `notCompacting` (the `false` / default case of the field in its current form)
- `needsCompaction` (a signal that the file has been "marked but not yet compacted")
- `compacting` (the `true` case of the field in its current form)
- `compacted` (a new, post-compaction state, after which the file will eventually fall out of the LSM - after refs fall to zero)

Valid state transitions:

- `notCompacting` -> `needsCompaction` - covers the case where we're marking files
- `needsCompaction` -> `compacting` and `notCompacting -> compacting` - when a compaction is picked and scheduled, the field is unconditionally set to `compacting` via `addInProgressCompaction`.
- `compacting -> compacted` - compaction is complete. This table was the input to a compaction, with an output table that renders this table obsolete.
- `compacting -> notCompacting` - a special case for a move compaction - in the future it could be compacted again (move-d, or a traditional compaction)

It looks like `removeInProgressCompaction` currently unconditionally sets `f.Compacting = false` when a compaction is done, so there may be implications to leaving a compacted table's state as `compacted` (i.e. the semantics change a bit).

There's also the MANIFEST to consider. However, if we went with the enum, which now encodes a `needsCompaction` state, this might make `MarkedForCompaction` obsolete.

Thoughts? I'll probably want to split this enum piece out.
</blockquote></details>

Looks good. My one thought is that we probably shouldn't roll `MarkedForCompaction` into the enum, since `MarkedForCompaction` is persistent state recorded to the manifest, whereas `Compacting` is ephemeral,  in-memory state local to the process.

I'm imagining a sequence like:
1. There exists a file _f_.
2. A compaction to compact _f_ begins, transitioning the enum from either `notCompacting` or `needsCompaction` to compacting.
3. While the compaction is in progress, the manifest rotates. The manifest needs to record the `MarkedForCompaction` bit (or the new enum, if we were to replace it). We've now lost information about whether the file _must_ be compacted or was just chosen for compaction according to ordinary compaction heuristics.

**Comment by nicktrav** [comment]
I'll rebase this on #1864, once that lands.

**Comment by nicktrav** [comment]
Rebased to pick up the enum. This is good for another look.

**Review by jbowens — APPROVED** [review]
nice! :lgtm:

> Reviewed 4 of 8 files at r1, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1832#-:-N9DRLUS48VCc568QBO4:bbixqh9)* status: 8 of 9 files reviewed, 3 unresolved discussions (waiting on @itsbilal and @nicktrav)

**Review by nicktrav — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1832#-:-N9DRfYi4s157-Hy305E:b-814g8k)* status: 8 of 9 files reviewed, 3 unresolved discussions (waiting on @itsbilal and @nicktrav)

**Pull request merged**
