### PR TITLE
internal/manifest: add helper for comparing B-Tree iterator positions

### PR DESCRIPTION
**Pull request by jbowens**
When using the B-Tree implementation to back the LevelSlice and
LevelIterator data structures, B-Tree iterators will need to be compared
to enforce bounds. This add a cmpIter function for comparing two B-Tree
iterators by comparing their positions within their stacks, starting
from the root.

### CODE REVIEW

**Review by petermattis — COMMENTED** [review]
The approach looks good to me. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/897#-:-MHNKbZb-0KBUlpHJ3Ru:bkyvyzg)* status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @jbowens)

___
*[internal/manifest/btree.go, line 781 at r1](https://reviewable.io/reviews/cockroachdb/pebble/897#-MHNKGCE7iVWfBAmOYLc:-MHNKGCE7iVWfBAmOYLd:b61ev6x) ([raw file](https://github.com/cockroachdb/pebble/blob/4b9d632a556f3bea9b5ca94e519ff2b90da08e6c/internal/manifest/btree.go#L781)):*
> ```Go
> 
> 	an, apos := a.n, a.pos
> 	bn, bpos := b.n, b.pos
> ```

Can you comment on the need for this initialization? I think it is needed when an iterator is pointing at the root node. 
___
*[internal/manifest/btree.go, line 782 at r1](https://reviewable.io/reviews/cockroachdb/pebble/897#-MHNJ0Ll35X29oKYxy-o:-MHNJ0Ll35X29oKYxy-p:b-bmzxiu) ([raw file](https://github.com/cockroachdb/pebble/blob/4b9d632a556f3bea9b5ca94e519ff2b90da08e6c/internal/manifest/btree.go#L782)):*
> ```Go
> 	an, apos := a.n, a.pos
> 	bn, bpos := b.n, b.pos
> 	var aok, bok bool
> ```

I find the use of `aok` and `bok` a bit confusing. It took me a bit to decipher what was going on. I think it would be useful to add some commentary around what this is doing: you're walking down both stacks starting from the root until you reach a point where the iterators point to different pages, or one iterator is in a lower-level of the tree than the other.
___
*[internal/manifest/btree.go, line 784 at r1](https://reviewable.io/reviews/cockroachdb/pebble/897#-MHIj1nzCr8S63er6HHO:-MHIj1nzCr8S63er6HHP:b-2i6frx) ([raw file](https://github.com/cockroachdb/pebble/blob/4b9d632a556f3bea9b5ca94e519ff2b90da08e6c/internal/manifest/btree.go#L784)):*
> ```Go
> 	var aok, bok bool
> 
> 	// Examine stack frames starting from the root.
> ```

Aren't these "iterator frames", not "stack frames"? I suppose "stack frames" is not wrong, but that term makes me thing of the runtime stacks.
___
*[internal/manifest/btree.go, line 809 at r1](https://reviewable.io/reviews/cockroachdb/pebble/897#-MHNITfqEYHVtiretz_S:-MHNITfr-V87KqR0LhLG:b-wlbj0y) ([raw file](https://github.com/cockroachdb/pebble/blob/4b9d632a556f3bea9b5ca94e519ff2b90da08e6c/internal/manifest/btree.go#L809)):*
> ```Go
> 			return +1
> 		default:
> 			// continue up both stacks
> ```

Nit: capitalize and punctuate.

Nit 2: You're walking from the root down the tree, so this feels like walking down the stacks. Interesting that we have different mental views of this.
___
*[internal/manifest/btree.go, line 813 at r1](https://reviewable.io/reviews/cockroachdb/pebble/897#-MHNJtQh3UU4ZHdIbnwN:-MHNJtQh3UU4ZHdIbnwO:b-rdlafw) ([raw file](https://github.com/cockroachdb/pebble/blob/4b9d632a556f3bea9b5ca94e519ff2b90da08e6c/internal/manifest/btree.go#L813)):*
> ```Go
> 	}
> 
> 	if an != bn {
> ```

Another invariant to check: `!aok || !bok`. 
___
*[internal/manifest/btree_test.go, line 349 at r1](https://reviewable.io/reviews/cockroachdb/pebble/897#-MHM3wDv0V5HYJL0IFDo:-MHM3wDv0V5HYJL0IFDp:by3roj6) ([raw file](https://github.com/cockroachdb/pebble/blob/4b9d632a556f3bea9b5ca94e519ff2b90da08e6c/internal/manifest/btree_test.go#L349)):*
> ```Go
> 	}
> 	sort.Stable(iterCmpSorted)
> 	sort.Stable(itemCmpSorted)
> ```

Nit: `iterCmpSorted` and `itemCmpSorted` differ by only a single letter. I initially thought those were the same variable.

Is stable sort needed here?

I think it would be clearer and less code to use `sort.Slice` or `sort.StableSlice`:

```
sort.StableSlice(iter1, func(a, b *iterator) bool { return cmpIter(*a, *b) < 0 })
sort.StableSlice(iter2, func(a, b *iterator) bool { return cmp(*a, *b) < 0 })
```

Another possibility is to sort once and then use `SliceIsSorted`:

```
sort.StableSlice(iter1, func(a, b *iterator) bool { return cmpIter(*a, *b) < 0 })
require.True(t, sort.SliceIsSorted(iter1, func(a, b *iterator) bool { return cmp(*a, *b) < 0 })
```

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/897)* status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @petermattis)

___
*[internal/manifest/btree.go, line 781 at r1](https://reviewable.io/reviews/cockroachdb/pebble/897#-MHNKGCE7iVWfBAmOYLc:-MHNUlX1CWpKhWNANHu2:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/4b9d632a556f3bea9b5ca94e519ff2b90da08e6c/internal/manifest/btree.go#L781)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Can you comment on the need for this initialization? I think it is needed when an iterator is pointing at the root node. 
</blockquote></details>

Done.
___
*[internal/manifest/btree.go, line 782 at r1](https://reviewable.io/reviews/cockroachdb/pebble/897#-MHNJ0Ll35X29oKYxy-o:-MHN_s7J9zmFD_5JWpv4:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/4b9d632a556f3bea9b5ca94e519ff2b90da08e6c/internal/manifest/btree.go#L782)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I find the use of `aok` and `bok` a bit confusing. It took me a bit to decipher what was going on. I think it would be useful to add some commentary around what this is doing: you're walking down both stacks starting from the root until you reach a point where the iterators point to different pages, or one iterator is in a lower-level of the tree than the other.
</blockquote></details>

Done.
___
*[internal/manifest/btree.go, line 784 at r1](https://reviewable.io/reviews/cockroachdb/pebble/897#-MHIj1nzCr8S63er6HHO:-MHNReZA0ND-BZEC8eUm:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/4b9d632a556f3bea9b5ca94e519ff2b90da08e6c/internal/manifest/btree.go#L784)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Aren't these "iterator frames", not "stack frames"? I suppose "stack frames" is not wrong, but that term makes me thing of the runtime stacks.
</blockquote></details>

Done.
___
*[internal/manifest/btree.go, line 809 at r1](https://reviewable.io/reviews/cockroachdb/pebble/897#-MHNITfqEYHVtiretz_S:-MHNRfb0DTl2rppwCgnK:b-90vd0h) ([raw file](https://github.com/cockroachdb/pebble/blob/4b9d632a556f3bea9b5ca94e519ff2b90da08e6c/internal/manifest/btree.go#L809)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Nit: capitalize and punctuate.

Nit 2: You're walking from the root down the tree, so this feels like walking down the stacks. Interesting that we have different mental views of this.
</blockquote></details>

I thought of it as up since the iterator's stack has the root node at the very bottom of the stack and the node with the deepest height on top of the stack. I think we're going down the tree but up the iterator's stack. I made this comment a little more explicit :+1: 
___
*[internal/manifest/btree.go, line 813 at r1](https://reviewable.io/reviews/cockroachdb/pebble/897#-MHNJtQh3UU4ZHdIbnwN:-MHNUkFm8zcns1F2J8Pn:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/4b9d632a556f3bea9b5ca94e519ff2b90da08e6c/internal/manifest/btree.go#L813)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Another invariant to check: `!aok || !bok`. 
</blockquote></details>

Done.
___
*[internal/manifest/btree_test.go, line 349 at r1](https://reviewable.io/reviews/cockroachdb/pebble/897#-MHM3wDv0V5HYJL0IFDo:-MHNfD_r4k520RFhiWjL:b5p885y) ([raw file](https://github.com/cockroachdb/pebble/blob/4b9d632a556f3bea9b5ca94e519ff2b90da08e6c/internal/manifest/btree_test.go#L349)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Nit: `iterCmpSorted` and `itemCmpSorted` differ by only a single letter. I initially thought those were the same variable.

Is stable sort needed here?

I think it would be clearer and less code to use `sort.Slice` or `sort.StableSlice`:

```
sort.StableSlice(iter1, func(a, b *iterator) bool { return cmpIter(*a, *b) < 0 })
sort.StableSlice(iter2, func(a, b *iterator) bool { return cmp(*a, *b) < 0 })
```

Another possibility is to sort once and then use `SliceIsSorted`:

```
sort.StableSlice(iter1, func(a, b *iterator) bool { return cmpIter(*a, *b) < 0 })
require.True(t, sort.SliceIsSorted(iter1, func(a, b *iterator) bool { return cmp(*a, *b) < 0 })
```
</blockquote></details>

Nice! I didn't know about `sort.Slice`/`sort.SliceStable`.

**Review by petermattis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/897#-:-MHNg0uTC-lLLy-LH8VO:bnfp4nl)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @jbowens)

___
*[internal/manifest/btree.go, line 782 at r1](https://reviewable.io/reviews/cockroachdb/pebble/897#-MHNJ0Ll35X29oKYxy-o:-MHNfkbr2N336i8NxX9y:bxyje41) ([raw file](https://github.com/cockroachdb/pebble/blob/4b9d632a556f3bea9b5ca94e519ff2b90da08e6c/internal/manifest/btree.go#L782)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Excellent comment!
___
*[internal/manifest/btree.go, line 785 at r2](https://reviewable.io/reviews/cockroachdb/pebble/897#-MHNf_IkA7DZ4Np0HIb_:-MHNf_IkA7DZ4Np0HIba:b9dzh15) ([raw file](https://github.com/cockroachdb/pebble/blob/a594ff05f89dce2dccb68ba591e8ffc07cec3ca4/internal/manifest/btree.go#L785)):*
> ```Go
> 	// always comparing nodes at the same level in the tree.
> 	//
> 	// If the iterators' paths ever diverge and point to different pages, the
> ```

`s/pages/nodes/g`
___
*[internal/manifest/btree.go, line 805 at r2](https://reviewable.io/reviews/cockroachdb/pebble/897#-MHNfcgP8zLVHXwGFD0j:-MHNfcgP8zLVHXwGFD0k:b-kqg2in) ([raw file](https://github.com/cockroachdb/pebble/blob/a594ff05f89dce2dccb68ba591e8ffc07cec3ca4/internal/manifest/btree.go#L805)):*
> ```Go
> 	// +------------------------+      +--------------------------+
> 
> 	// Iniitalize with the iterator's current node and position. These are
> ```

`s/Iniitialize/Initialize/g`

**Comment by jbowens** [comment]
TFTR!

**Pull request merged**
