### PR TITLE
db: stress rangekey masking implementation in a randomized test

### PR DESCRIPTION
**Pull request by bananabrick**
The range key masking implementation can be subtle. Especially if
we use a block property filter to make iteration faster.

This pr introduces a randomzied test which varies target file sizes,
block sizes, and whether the iterator uses a filter or not for the
masking.

It compares the results from a simple configuration with the random
configuration.

### CODE REVIEW

**Comment by bananabrick** [comment]
Aside from improving the code, the randomization aspects can probably be improved here. Feedback welcome.

**Review by itsbilal — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1940)* status: all files reviewed, 5 unresolved discussions (waiting on @bananabrick and @jbowens)

___
*[`iterator_test.go` line 2200 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1940#-NBOiSXd8I1zTXCzUIg1:-NBOiSXd8I1zTXCzUIg2:b-72z82l) ([raw file](https://github.com/cockroachdb/pebble/blob/7bcb863bfe5e66da32ccd65c30db98fd598356bd/iterator_test.go#L2200)):*
> ```Go
> 	var timestamps []int
> 	for i := 0; i <= 100; i++ {
> 		timestamps = append(timestamps, 10*i)
> ```

nit: Could probably also generate these randomly
___
*[`iterator_test.go` line 2209 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1940#-NBOjB0I0WsrGlcPJ98V:-NBOjB0J107j_deFM1aY:b-kmak2b) ([raw file](https://github.com/cockroachdb/pebble/blob/7bcb863bfe5e66da32ccd65c30db98fd598356bd/iterator_test.go#L2209)):*
> ```Go
> 		keys[i] = make([]byte, 5+testkeys.MaxSuffixLen)
> 		testkeys.WriteKey(keys[i][:5], ks, rng.Intn(ks.Count()))
> 		n := testkeys.WriteSuffix(keys[i][5:], timestamps[rng.Intn(len(timestamps))])
> ```

nit: you could combine these two with `WriteKeyAt`, but up to you if you want to make that change.
___
*[`iterator_test.go` line 2270 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1940#-NBOjcjB2coVfeueOtDW:-NBOjcjB2coVfeueOtDX:boq0arh) ([raw file](https://github.com/cockroachdb/pebble/blob/7bcb863bfe5e66da32ccd65c30db98fd598356bd/iterator_test.go#L2270)):*
> ```Go
> 	maxProcs := runtime.GOMAXPROCS(0)
> 
> 	opts1 := &Options{
> ```

We should be setting `blockSize` both here and for `opts2`?
___
*[`iterator_test.go` line 2360 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1940#-NBOl1TIE-Ijoe0-RHxi:-NBOl1TJ2mjYkLg-iOFk:b22ab9f) ([raw file](https://github.com/cockroachdb/pebble/blob/7bcb863bfe5e66da32ccd65c30db98fd598356bd/iterator_test.go#L2360)):*
> ```Go
> 		}
> 
> 		// Confirm some range key things.
> ```

nit: can instead say `Confirm exposed range key state is identical`.
___
*[`iterator_test.go` line 2375 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1940#-NBOlAw09k12RcxU6KLK:-NBOlAw09k12RcxU6KLL:b7dt17q) ([raw file](https://github.com/cockroachdb/pebble/blob/7bcb863bfe5e66da32ccd65c30db98fd598356bd/iterator_test.go#L2375)):*
> ```Go
> 			if !bytes.Equal(b1, b2) || !bytes.Equal(e1, e2) {
> 				t.Fatalf(fmt.Sprintf(
> 					"iteration didn't produce identical range keys: [%s, %s], [%s, %s]",
> ```

This is good as a bit of a metamorphic test, but one thing you could also consider is to check if all the keys you expect to be exposed, are exposed. You could iterate through `rkeys`, mark all overlapping values in `keys` with timestamps less than each `rkey` as deleted in your own array, and then when you iterate here, you could confirm that no key that you marked as deleted in `keys` gets returned.

**Review by bananabrick — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1940)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @itsbilal and @jbowens)

___
*[`iterator_test.go` line 2270 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1940#-NBOjcjB2coVfeueOtDW:-NBTtcGg2mBkQP-Pxrz3:bflgdtb) ([raw file](https://github.com/cockroachdb/pebble/blob/7bcb863bfe5e66da32ccd65c30db98fd598356bd/iterator_test.go#L2270)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

We should be setting `blockSize` both here and for `opts2`?
</blockquote></details>

Passing that into levelOpts now.
___
*[`iterator_test.go` line 2375 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1940#-NBOlAw09k12RcxU6KLK:-NBU108s2v3s7MfBgzGI:bq1os80) ([raw file](https://github.com/cockroachdb/pebble/blob/7bcb863bfe5e66da32ccd65c30db98fd598356bd/iterator_test.go#L2375)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

This is good as a bit of a metamorphic test, but one thing you could also consider is to check if all the keys you expect to be exposed, are exposed. You could iterate through `rkeys`, mark all overlapping values in `keys` with timestamps less than each `rkey` as deleted in your own array, and then when you iterate here, you could confirm that no key that you marked as deleted in `keys` gets returned.
</blockquote></details>

Done. Although un-optimally. Should be ok for a test.

**Review by itsbilal — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1940#-:-NB_MYxH4WwKN4zJ5Xd7:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jbowens)

**Pull request merged**
