### PR TITLE
db: fix some iterator error paths

### LINKED ISSUE #3234: db: TestIteratorErrors failed [iterator is valid with non-nil Error]
https://github.com/cockroachdb/pebble/actions/runs/7568342774/job/20609357007
```
=== RUN   TestIteratorErrors
    external_test.go:31: Using seed 1705572529975016370
```

```
--- FAIL: TestIteratorErrors (1.79s)
panic: pebble: iterator is valid with non-nil Error [recovered]
	panic: pebble: iterator is valid with non-nil Error

goroutine 121985 [running]:
testing.tRunner.func1.2({0xd72be0, 0xc00136b940})
	/opt/hostedtoolcache/go/1.21.5/x64/src/testing/testing.go:1545 +0x238
testing.tRunner.func1()
	/opt/hostedtoolcache/go/1.21.5/x64/src/testing/testing.go:1548 +0x397
panic({0xd72be0?, 0xc00136b940?})
	/opt/hostedtoolcache/go/1.21.5/x64/src/runtime/panic.go:914 +0x21f
github.com/cockroachdb/pebble.(*Iterator).Valid(0xc001e22800?)
	/home/runner/work/pebble/pebble/iterator.go:2241 +0x87
github.com/cockroachdb/pebble/metamorphic.(*retryableIter).withRetry(0xc0034426c0, 0xc000ca1960)
	/home/runner/work/pebble/pebble/metamorphic/retryable.go:57 +0x66
github.com/cockroachdb/pebble/metamorphic.(*retryableIter).SeekGE(0xc003529820?, {0xc002071e37?, 0xc002720090?, 0xe09e58?})
	/home/runner/work/pebble/pebble/metamorphic/retryable.go:147 +0x5e
github.com/cockroachdb/pebble/metamorphic.(*iterSeekGEOp).run(0xc004390c40, 0x4131c5?, {0xc003529820?, 0xd3f980?, 0xc002720100?})
	/home/runner/work/pebble/pebble/metamorphic/ops.go:1356 +0xd1
github.com/cockroachdb/pebble/metamorphic.(*Test).step(0xc000d76960, 0xc00022b340?, 0x2c?)
	/home/runner/work/pebble/pebble/metamorphic/test.go:352 +0x48
github.com/cockroachdb/pebble/metamorphic.(*Test).Step(0xc000d76960)
	/home/runner/work/pebble/pebble/metamorphic/test.go:341 +0x75
github.com/cockroachdb/pebble_test.TestIteratorErrors(0xc00057b380)
	/home/runner/work/pebble/pebble/external_test.go:86 +0x898
testing.tRunner(0xc00057b380, 0xe5c3d8)
	/opt/hostedtoolcache/go/1.21.5/x64/src/testing/testing.go:1595 +0xff
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.21.5/x64/src/testing/testing.go:1648 +0x3ad
```

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### db: fix some iterator error paths

Fixes `TestIteratorErrors` failures.

We also improve the `Counter` injector to keep track of the stack
trace when the last error was injected.

Fixes #3234

#### db: remove panic when cleanup jobs queue is full

This assertion was hit while stress-testing `TestIteratorErrors`. It
is not necessary, since the code is designed to block as needed. It
was there to make sure we never block under normal circumstances.

### CODE REVIEW

**Comment by RaduBerinde** [comment]
I haven't verified that every single one of the changes is necessary, if you see one that isn't I will replace it with a comment.

**Comment by RaduBerinde** [comment]
I still see an error after ~9000 runs, I'll keep investigating.

**Comment by RaduBerinde** [comment]
Ok, this version seems to work:
`14683 runs so far, 0 failures, over 38m40s`

**Review by jbowens — APPROVED** [review]
Thanks for tracking these down!

:lgtm:

> Reviewed 9 of 9 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3250#-:-NpQEvyf8zNc7y1mCutI:bk994dq)* status: all files reviewed, 4 unresolved discussions (waiting on @RaduBerinde)

___
*[`iterator.go` line 643 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3250#-NpQCag4EaRAi5LngioI:-NpQCag4EaRAi5LngioJ:b96g95h) ([raw file](https://github.com/cockroachdb/pebble/blob/6aaa382f0b83bad02a8af64f1cf198f2971f88da/iterator.go#L643)):*
> ```Go
> 
> 	// Is iterKey nil due to an error?
> 	if i.err = i.iter.Error(); i.err != nil {
> ```

I think it's possible `i.err != nil` and not due to `i.iter.Error()` being non-nil, so we shouldn't overwrite `i.err` unconditionally here. 
___
*[`iterator.go` line 1626 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3250#-NpQBW6YD08eBcT2sIjI:-NpQBW6Z7edWh0PzODIy:b-pmpw8g) ([raw file](https://github.com/cockroachdb/pebble/blob/6aaa382f0b83bad02a8af64f1cf198f2971f88da/iterator.go#L1626)):*
> ```Go
> 			i.iterValidityState = IterExhausted
> 			return i.iterValidityState
> 		}
> ```

I think all these cases that fall into `findNextEntry`/`findPrevEntry` should've been okay but only as a consequence of very subtle control flow. `findNextEntry` should leave the iter where it is if `i.iterKey` is nil, and `Iterator.Error()` returns `i.iter.Error()` if it's non-nil. Maybe we weren't setting `iterValidityState = IterExhausted` though? Promoting these into explicit err checks makes it clearer they're being handled, so lgtm regardless.
___
*[`internal/keyspan/merging_iter.go` line 963 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3250#-NpQDpdu8e76M6L3ooOh:-NpQDpdu8e76M6L3ooOi:b-u12cqi) ([raw file](https://github.com/cockroachdb/pebble/blob/6aaa382f0b83bad02a8af64f1cf198f2971f88da/internal/keyspan/merging_iter.go#L963)):*
> ```Go
> 			if err := m.prevEntry(); err != nil {
> 				return nil, err
> 			}
> ```

Oops, thanks for cleaning this up.
___
*[`vfs/errorfs/errorfs.go` line 237 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3250#-NpQDwGs8rqk8NWwt3Hv:-NpQDwGs8rqk8NWwt3Hw:bm3zm4q) ([raw file](https://github.com/cockroachdb/pebble/blob/6aaa382f0b83bad02a8af64f1cf198f2971f88da/vfs/errorfs/errorfs.go#L237)):*
> ```Go
> 	c.mu.Lock()
> 	defer c.mu.Unlock()
> 	return c.mu.lastErr
> ```

The `LabelledError.MaybeError` method uses `errors.WithStack` to wrap the error with a stack trace. Should we use that to extract the stack trace? We can also use the verbose format specifier to print the error with its stack in TestIteratorErrors.

**Review by RaduBerinde — COMMENTED** [review]
Updated. I modified the test to run 5000 read ops instead of 500. It takes about the same amount of time since we already run 10k operations to set up the store.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3250#-:-NpQhHloEiTl_EqFsWUj:b-v1oxbe)* status: 6 of 10 files reviewed, 4 unresolved discussions (waiting on @jbowens)

___
*[`iterator.go` line 643 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3250#-NpQCag4EaRAi5LngioI:-NpQbZ_W6S1R1j1ruj6I:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/6aaa382f0b83bad02a8af64f1cf198f2971f88da/iterator.go#L643)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

I think it's possible `i.err != nil` and not due to `i.iter.Error()` being non-nil, so we shouldn't overwrite `i.err` unconditionally here.
</blockquote></details>

Done.
___
*[`iterator.go` line 1626 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3250#-NpQBW6YD08eBcT2sIjI:-NpQbefaDi1e9CduBhnf:b-ithqw8) ([raw file](https://github.com/cockroachdb/pebble/blob/6aaa382f0b83bad02a8af64f1cf198f2971f88da/iterator.go#L1626)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

I think all these cases that fall into `findNextEntry`/`findPrevEntry` should've been okay but only as a consequence of very subtle control flow. `findNextEntry` should leave the iter where it is if `i.iterKey` is nil, and `Iterator.Error()` returns `i.iter.Error()` if it's non-nil. Maybe we weren't setting `iterValidityState = IterExhausted` though? Promoting these into explicit err checks makes it clearer they're being handled, so lgtm regardless.
</blockquote></details>

Yes, the state not being set to `IterExhausted` was the problem (at least in some of these paths) - it led to the "iterator is valid with non-nil Error" panic.
___
*[`vfs/errorfs/errorfs.go` line 237 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3250#-NpQDwGs8rqk8NWwt3Hv:-NpQcMQhAbLrOWdr6A_V:b-h72rob) ([raw file](https://github.com/cockroachdb/pebble/blob/6aaa382f0b83bad02a8af64f1cf198f2971f88da/vfs/errorfs/errorfs.go#L237)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

The `LabelledError.MaybeError` method uses `errors.WithStack` to wrap the error with a stack trace. Should we use that to extract the stack trace? We can also use the verbose format specifier to print the error with its stack in TestIteratorErrors.
</blockquote></details>

Ha, nice, I totally missed that. Switched to printing that error with `%+v`.

**Review by jbowens — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3250#-:-NpRAtsD9K-EtsXqDzxg:bnfp4nl)* status: 6 of 10 files reviewed, 4 unresolved discussions (waiting on @RaduBerinde)

**Comment by RaduBerinde** [comment]
TFTR!

**Pull request merged**
