### PR TITLE
db: track files' pre-zeroing largest sequence numbers

### PR DESCRIPTION
**Pull request by jbowens**
When there exist no keys beneath a compaction's key range, Pebble performs sequence number zeroing. This is an optimization that allows for easier detection of new user keys during iteration. This commit introduces a new FileMetadata field LargestSeqNumAbsolute that provides an upper bound on the sequence numbers of a sstables' keys before they were zeroed. This is useful as a stable upper bound on the recency of an sstable's keys.

In this commit we use this new upper bound to provide an alternative solution to the interaction between delete-only compactions and sequence number zeroing. Previously any compaction that zeroed sequence numbers and overlapped a delete-only compaction hint was required to clear the conflicting hints to ensure a delete-only compaction did not accidentally drop a table containing keys more recent than any of the hint's constituent tombstones. This interaction was a bit indirect and subtle. Encoding the pre-zeroing sequence number on the file metadata is more direct, and will allow us to use the sequence number for recency ordering of sstables' keys more generally, including in #2112.

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
Could you briefly describe in the commit message how this works after a restart?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3576#-:-Nwu7rrw3jYxvANhU5Pg:bxsytjo)* status: 0 of 14 files reviewed, 1 unresolved discussion (waiting on @jbowens and @sumeerbhola)

___
*[`testdata/compaction_delete_only_hints` line 264 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3576#-Nwu7eBQCJLzEeHkjklq:-Nwu7eBQCJLzEeHkjklr:bjt1f6n) ([raw file](https://github.com/cockroachdb/pebble/blob/d2010d4074e6cbc91528058d45709408875fa54c/testdata/compaction_delete_only_hints#L264)):*
> ```
> # sequence numbers higher than the lowest tombstone sequence number.
> #
> # In the current code, the hint remains but when the hint is resolved. Instead
> ```

[nit] incomplete sentence

**Review by jbowens — COMMENTED** [review]
> Could you briefly describe in the commit message how this works after a restart?

Done

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3576#-:-NwuGyErEAKXHXMLQCGj:b-5k7wa0)* status: 0 of 14 files reviewed, all discussions resolved (waiting on @sumeerbhola)

___
*[`testdata/compaction_delete_only_hints` line 264 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3576#-Nwu7eBQCJLzEeHkjklq:-NwuOAObCl-lPV1n_x81:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/d2010d4074e6cbc91528058d45709408875fa54c/testdata/compaction_delete_only_hints#L264)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] incomplete sentence
</blockquote></details>

Done.

**Review by RaduBerinde — APPROVED** [review]
Very nice explanation, thanks!

:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3576#-:-NwuPqyEC2cwXcl_pAGX:b-fesjn9)* status: 0 of 14 files reviewed, all discussions resolved (waiting on @sumeerbhola)

**Review by jbowens — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3576#-:-NwypMjx98zBvV4h7WtV:b-814g8k)* status: 0 of 14 files reviewed, all discussions resolved (waiting on @sumeerbhola)

**Pull request merged**
