### PR TITLE
metamorphic: enhance iterSetBounds and position iter when setting bounds

### PR DESCRIPTION
**Pull request by sumeerbhola**
This tries to model CockroachDB behavior when using bounds and
the subsequent seek. There is some additional iteration that
tries to exercise corner cases around the bounds.

These changes can consistently reproduce the
bugs in https://github.com/sumeerbhola/pebble/commit/a24bc6c83054489b1bb0d9f53bcdd4ad8ec75
after a few minutes.

### CODE REVIEW

**Review by petermattis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/946#-:-MIM2lWp9jNBdgoJV3t4:bnfp4nl)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @itsbilal, @jbowens, @petermattis, and @sumeerbhola)

___
*[internal/metamorphic/generator.go, line 439 at r1](https://reviewable.io/reviews/cockroachdb/pebble/946#-MIM1zdaCTY8cZiCaN9Z:-MIM1zdaCTY8cZiCaN9_:b-lxlpp) ([raw file](https://github.com/cockroachdb/pebble/blob/887ad18a5b30e95ce2bb109e3cbc889415f929e3/internal/metamorphic/generator.go#L439)):*
> ```Go
> 			})
> 		}
> 	} else if lower != nil && g.rng.Float64() < 0.5 {
> ```

Is the `else if` intentional? Seems like this will make seeking on the lower bound less likely than the upper bound, but perhaps I'm not thinking this through fully.

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/946)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @itsbilal, @jbowens, and @petermattis)

___
*[internal/metamorphic/generator.go, line 439 at r1](https://reviewable.io/reviews/cockroachdb/pebble/946#-MIM1zdaCTY8cZiCaN9Z:-MIMKGWA2s-zHCOP--kN:bbf0irh) ([raw file](https://github.com/cockroachdb/pebble/blob/887ad18a5b30e95ce2bb109e3cbc889415f929e3/internal/metamorphic/generator.go#L439)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Is the `else if` intentional? Seems like this will make seeking on the lower bound less likely than the upper bound, but perhaps I'm not thinking this through fully.
</blockquote></details>

Only the first seek matters for the iterator optimization, so I thought doing one or the other was sufficient (otherwise we are secretly adding even more operations as part of constructing one operation).
If both lower and upper are non-nil, we have 0.5 probability of SeekLT and 0.5 * 0.5 of SeekGE and the remaining 0.25 is no seek. So you are right that there is a bias. I've changed the code to remove the bias.

**Review by sumeerbhola — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/946#-:-MIMN-_OCMJf0yhSISGy:b-814g8k)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @itsbilal, @jbowens, and @petermattis)

**Review by petermattis — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/946)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @itsbilal, @jbowens, @petermattis, and @sumeerbhola)

___
*[internal/metamorphic/generator.go, line 429 at r2](https://reviewable.io/reviews/cockroachdb/pebble/946#-MIP75Yj2t7gusdFvUE0:-MIP75Yj2t7gusdFvUE1:b-yp3u8y) ([raw file](https://github.com/cockroachdb/pebble/blob/8fc778e286d20512d6a937547e5d27c5ab01e29f/internal/metamorphic/generator.go#L429)):*
> ```Go
> 		}
> 	}
> 	if upper != nil && g.rng.Float64() < 0.5 {
> ```

Shouldn't this be changed to `if doSeekLT`, and the other conditional to `else if doSeekGE`?

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/946)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @itsbilal, @jbowens, and @petermattis)

___
*[internal/metamorphic/generator.go, line 429 at r2](https://reviewable.io/reviews/cockroachdb/pebble/946#-MIP75Yj2t7gusdFvUE0:-MIQE2YJ6SC0GnYMGCij:b-h8nkq) ([raw file](https://github.com/cockroachdb/pebble/blob/8fc778e286d20512d6a937547e5d27c5ab01e29f/internal/metamorphic/generator.go#L429)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Shouldn't this be changed to `if doSeekLT`, and the other conditional to `else if doSeekGE`?
</blockquote></details>

duh. Done

**Pull request merged**
