### PR TITLE
replay: use benchfmt pkg, expose additional metrics

### PR DESCRIPTION
**Pull request by jbowens**
This commit refactors some of the replay package's exposed metrics, adds new ones and exposes some ascii graphs as a part of the output.

The code to construct Go benchmark-style result output is refactored to use the golang.org/x/perf/benchfmt package (also used by benchstat).  Additional metrics are added for test runtime, throughput, compaction debt, read amplification and database size. Some metrics that lend themselves to measurement over time are now printed as an ascii graph as well.

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
Cool! :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2319#-:-NOAzr_m3P0uyFNRxZQm:b-dp13x5)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @itsbilal and @jbowens)

___
*[`replay/replay.go` line 119 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2319#-NOAycLE-lB1kkNDfyU2:-NOAycLE-lB1kkNDfyU3:b-xx8cmj) ([raw file](https://github.com/cockroachdb/pebble/blob/d51b5eaea48c071e12f993e4957e033bec812cca/replay/replay.go#L119)):*
> ```Go
> 	}
> 	ReadAmp SampledMetric
> 	// QuiesceDur is the time between completing application of the workload and
> ```

[nit] existing field uses `Duration`, we should keep them consistent
___
*[`replay/replay.go` line 207 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2319#-NOAzdBP-ET_k4MZfE9t:-NOAzdBP-ET_k4MZfE9u:b-hnhc2d) ([raw file](https://github.com/cockroachdb/pebble/blob/d51b5eaea48c071e12f993e4957e033bec812cca/replay/replay.go#L207)):*
> ```Go
> 		}},
> 		{label: "Throughput", values: []benchfmt.Value{
> 			{Value: float64(m.WriteBytes/1024/1024) / (m.WorkloadDur + m.QuiesceDur).Seconds(), Unit: "MB/s"},
> ```

[nit] all the other stats use bytes, why not keep it bytes / sec

**Review by jbowens — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2319#-:-NOBdHzs5Sj00qV3FXBR:b-814g8k)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @itsbilal)

___
*[`replay/replay.go` line 119 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2319#-NOAycLE-lB1kkNDfyU2:-NOBbwmqAvhU5NNJumAW:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/d51b5eaea48c071e12f993e4957e033bec812cca/replay/replay.go#L119)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] existing field uses `Duration`, we should keep them consistent
</blockquote></details>

Done.
___
*[`replay/replay.go` line 207 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2319#-NOAzdBP-ET_k4MZfE9t:-NOBc6Nd-CCp-LMl4VRb:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/d51b5eaea48c071e12f993e4957e033bec812cca/replay/replay.go#L207)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] all the other stats use bytes, why not keep it bytes / sec
</blockquote></details>

Done.
___
*[`replay/sampled_metric.go` line 41 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2319#-NOBdNvW5zTa8MBpalvv:-NOBdNvW5zTa8MBpalvw:b-b2yigp) ([raw file](https://github.com/cockroachdb/pebble/blob/41ccd542890aeea4155243e67ce58d525ddcc920/replay/sampled_metric.go#L41)):*
> ```Go
> // points. All values are first
> // multiplied by the provided scale parameter before graphing.
> func (m *SampledMetric) Plot(width, height int, scale float64) string {
> ```

shoutout to @irfansharif for the `asciigraph` inspiration

**Review by jbowens — COMMENTED** [review]
@RaduBerinde looks like it still needs the github :heavy_check_mark: stamp if it still looks good

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2319#-:-NOBehjaALgWudGgvLqr:bu13qyf)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @itsbilal)

**Review by RaduBerinde — APPROVED** [review]

**Comment by jbowens** [comment]
TFTR!

**Pull request merged**
