### PR TITLE
ingest: narrow transition of EFOS to file-only, delay excise panic

### LINKED ISSUE #3258: github.com/cockroachdb/pebble/internal/metamorphic: TestMetaTwoInstance failed
github.com/cockroachdb/pebble/internal/metamorphic.TestMetaTwoInstance [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_NightlyPebbleMetamorphicTwoInstance/13776604?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_NightlyPebbleMetamorphicTwoInstance/13776604?buildTab=artifacts#meta) on refs/heads/master @ [e53e09a9edbe](https://github.com/cockroachdb/pebble/commits/e53e09a9edbe):

```
        // INFO: [JOB 37] sstable deleted 000047
        // INFO: [JOB 37] sstable deleted 000049
        // INFO: [JOB 7] flushing: sstable created 000128
        // INFO: [JOB 37] sstable deleted 000050
        // INFO: [JOB 37] sstable deleted 000052
        // INFO: [JOB 37] sstable deleted 000053
        // INFO: [JOB 37] sstable deleted 000065
        // INFO: [JOB 37] sstable deleted 000066
        // INFO: [JOB 37] sstable deleted 000068
        // INFO: [JOB 37] sstable deleted 000069
        // INFO: [JOB 7] flushing: sstable created 000129
        // INFO: [JOB 37] sstable deleted 000070
        // INFO: [JOB 37] sstable deleted 000071
        // INFO: [JOB 37] sstable deleted 000072
        // INFO: [JOB 37] sstable deleted 000073
        // INFO: [JOB 37] sstable deleted 000082
        db1.Get("stjzvq@4") // [""] pebble: not found #1770
        // INFO: [JOB 37] sstable deleted 000083
        db1.Set("yqoycwbzp@1", "pahhbkgmlm") // <nil> #1771
        db1.Set("yrxcstgj@1", "knyagqjqmt") // <nil> #1774
        // INFO: [JOB 37] sstable deleted 000084
        db1.Delete("fatlkq@4") // <nil> #1778
        db1.Delete("cxcrwtekd@3") // <nil> #1781
        // INFO: [JOB 37] sstable deleted 000085
        db1.DeleteRange("bbtyvmqnut@6", "imbmqppeb@4") // <nil> #1782
        db1.Set("dolgaek@5", "k") // <nil> #1784
        // INFO: [JOB 7] flushing: sstable created 000130
        db1.DeleteRange("toquyqwflm@1", "xhnperzlxj@4") // <nil> #1786
        db1.Set("zaslhv", "qc") // <nil> #1789
        db1.RangeKeyDelete("fatlkq", "vffxhwlxvr") // <nil> #1791
        db1.Delete("voev@2") // <nil> #1796
        db1.Set("qguahklek", "dtjznojpu") // <nil> #1800
        db1.DeleteRange("fokurxk@5", "jytnccv@4") // <nil> #1807
        db1.Delete("istqjbw@2") // <nil> #1810
        db1.Set("caioijorn@1", "gteopry") // <nil> #1811
        db1.RangeKeySet("hjntenemx", "naahtmn", "@7", "lyojvhrx") // <nil> #1813
        // INFO: [JOB 7] flushing: sstable created 000131
        // INFO: [JOB 7] flushing: sstable created 000132
        // INFO: [JOB 7] flushing: sstable created 000133
        // INFO: [JOB 7] flushing: sstable created 000134
        // INFO: [JOB 7] flushing: sstable created 000135
        // INFO: [JOB 7] flushed 1 memtable (1.1KB) to L0 [000124 000125 000126 000127 000128 000129 000130 000131 000132 000133 000134 000135] (11KB), in 0.0s (0.0s total), output rate 1.4MB/s
        // INFO: [JOB 9] ingesting: sstable created 000136
        // INFO: [JOB 9] ingesting: sstable created 000137
        // INFO: [JOB 7] WAL deleted 000118
        // INFO: [JOB 10] flushing 1 ingested table
        // INFO: [JOB 10] flushed 1 ingested flushable L0:000121 (1.1KB) in 0.0s (0.0s total), output rate 25MB/s
        
        To reduce:  go test ./internal/metamorphic -tags invariants -run 'TestMetaTwoInstance$' --run-dir /artifacts/meta/240201-051930.646115143200/random-024 --try-to-reduce -v
        --- FAIL: TestMetaTwoInstance/execution/random-024 (0.81s)
```
<details><summary>Help</summary>
<p>
To reproduce, try:

```bash
go test -tags 'invariants' -exec 'stress -p 1' -timeout 0 -test.v -run 'TestMetaTwoInstance$' ./internal/metamorphic -seed 1706764770646603780 -ops "uniform:5000-10000"
```
</p>
</details>
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestMetaTwoInstance.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### PR DESCRIPTION
**Pull request by itsbilal**
Previously, we'd panic on an excise excising under an EventuallyFileOnlySnapshot even if the excise's version edit was slated to come after the flush that would transition the EFOS to a file-only snapshot. This change moves this check to after the logAndApply, so that the check happens after the excise is complete.

Also, previously we were not transitioning an EFOS to file-only if there were any memtables with any unflushed keys with seqnums lower than an EFOS' seqnum, even if that memtable had no keys within the EFOS' protected bounds. This change relaxes the criteria to transition an EFOS to a file-only snapshot to mimic the logic in the ingestion side, eliminating cases where we were expecting a flush to transition an EFOS but it didn't, resulting in a panic.

Fixes #3258.

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3272)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @aadityasondhi and @itsbilal)

___
*[`compaction.go` line 2069 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3272#-NpwH8GICZk9IDdZyWq8:-NpwH8GICZk9IDdZyWq9:bzeta8g) ([raw file](https://github.com/cockroachdb/pebble/blob/9df35027d7d506f2172e1511fd499707615fd7bb/compaction.go#L2069)):*
> ```Go
> 				// than the EFOS contain keys within a protected range of the EFOS. If
> 				// yes, flip canTransition back to false.
> 				canTransition = true
> ```

[nit] The flipping of the flag is a bit confusing, consider defining a separate `overlapsFlushable := false` before the loop and then `if overlapsFlushable { s = s.next; continue }`. We could also move this to a separate function.
___
*[`compaction.go` line 2080 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3272#-NpwGfdM6TM9TolvyetD:-NpwGfdM6TM9TolvyetE:b-ozz4px) ([raw file](https://github.com/cockroachdb/pebble/blob/9df35027d7d506f2172e1511fd499707615fd7bb/compaction.go#L2080)):*
> ```Go
> 						continue
> 					}
> 					d.mu.mem.queue[i].computePossibleOverlaps(func(b bounded) shouldContinue {
> ```

From the `computePossibleOverlaps` documentation, it sounds like it might call the function when there is no overlap, so it feels wrong to rely on whether the function was called. Maybe add a comment explaining why this is ok?

**Review by RaduBerinde — COMMENTED** [review]
Thanks for fixing this so quickly!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3272#-:-NpwHe1AE_nWDb77donH:bhlinxv)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @aadityasondhi and @itsbilal)

**Review by itsbilal — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3272#-:-NpwLSlI3Q5f14dlpnXX:b-814g8k)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @aadityasondhi)

___
*[`compaction.go` line 2069 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3272#-NpwH8GICZk9IDdZyWq8:-NpwLUMKDYVKf_TH50n4:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/9df35027d7d506f2172e1511fd499707615fd7bb/compaction.go#L2069)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] The flipping of the flag is a bit confusing, consider defining a separate `overlapsFlushable := false` before the loop and then `if overlapsFlushable { s = s.next; continue }`. We could also move this to a separate function.
</blockquote></details>

Done.
___
*[`compaction.go` line 2080 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3272#-NpwGfdM6TM9TolvyetD:-NpwLUhv1WUm2n4fY0Qt:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/9df35027d7d506f2172e1511fd499707615fd7bb/compaction.go#L2080)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

From the `computePossibleOverlaps` documentation, it sounds like it might call the function when there is no overlap, so it feels wrong to rely on whether the function was called. Maybe add a comment explaining why this is ok?
</blockquote></details>

Done.

**Comment by RaduBerinde** [comment]
:lgtm:

**Review by RaduBerinde — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3272)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @aadityasondhi and @itsbilal)

___
*[`compaction.go` line 2092 at r2](https://reviewable.io/reviews/cockroachdb/pebble/3272#-NpwQ2UD9FFptcVNJdvm:-NpwQ2UD9FFptcVNJdvn:bm2fjq2) ([raw file](https://github.com/cockroachdb/pebble/blob/43184cc6e450dfad7b5fad3e7155ababb2d7c68a/compaction.go#L2092)):*
> ```Go
> 			}
> 			if overlapsFlushable {
> 				s = s.next
> ```

small nit: this can be moved inside the block above

**Review by itsbilal — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3272#-:-NpwQlDK1Dp5DPPJkyuZ:b-814g8k)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @aadityasondhi and @RaduBerinde)

___
*[`compaction.go` line 2092 at r2](https://reviewable.io/reviews/cockroachdb/pebble/3272#-NpwQ2UD9FFptcVNJdvm:-NpwQhqTAvem_kTdnJpD:btabcck) ([raw file](https://github.com/cockroachdb/pebble/blob/43184cc6e450dfad7b5fad3e7155ababb2d7c68a/compaction.go#L2092)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

small nit: this can be moved inside the block above
</blockquote></details>

slight counterpoint would be that the `continue` is less confusing out here, so I'll keep it

**Pull request merged**
