### PR TITLE
.*: support async stats for virtual sstables

### PR DESCRIPTION
**Pull request by bananabrick**
Currently, virtual sstables lack stats unless they're set upon
creation. Even if these stats are set upon creation, they will
be lost upon a db restart.

This pr adds support to compute virtual sstable table stats
asynchronously.

To easily support this with minimal code changes, we introduce a
CommonReader interface meant to be used by those who don't care
if they're reading from a virtual or a physical sstable.

To support the CommonReader, we introduce a CommonProps type which
contains either virtual or physical sstable properties which are
useful to the users of the CommonReader.

Fixes: https://github.com/cockroachdb/pebble/issues/2558

### CODE REVIEW

**Review by bananabrick — COMMENTED** [review]
I owe tests. But before that I want some feedback on the approach.

It feels dubious to compute table stats for virtual sstables which are already approximations, from `VirtualProperties` which is already an approximation. Maybe a good enough first step?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2911#-:-Ne_PYdvE6hqbyGPWJ2a:b-rhu7jn)* status: 0 of 6 files reviewed, all discussions resolved (waiting on @jbowens)

**Review by jbowens — COMMENTED** [review]
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2911)* status: 1 of 6 files reviewed, 4 unresolved discussions (waiting on @bananabrick)

___
*[`sstable/reader.go` line 953 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2911#-Neno6_s2n33lrDyXC7b:-Neno6_s2n33lrDyXC7c:bhw4dvc) ([raw file](https://github.com/cockroachdb/pebble/blob/cd3ffd1c1a64d893425e19953c90997348e63c10/sstable/reader.go#L953)):*
> ```Go
> 
> // PhysicalToTableProps can be used to get a CommonProps from a Properties struct.
> func PhysicalToTableProps(props *Properties) *CommonProps {
> ```

Hrm, could we embed `CommonProperties` into the `Properties` struct to avoid the duplication and boiler plate? We might need to adjust some of the reflection to handle the embedded struct, but it seems doable.
___
*[`sstable/reader_virtual.go` line 22 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2911#-NennqgH5u2VHeD99saQ:-NennqgH5u2VHeD99saR:b8c7d80) ([raw file](https://github.com/cockroachdb/pebble/blob/cd3ffd1c1a64d893425e19953c90997348e63c10/sstable/reader_virtual.go#L22)):*
> ```Go
> // if NumRangeKeySets == 0, but the sstable actually contains range keys, then
> // the iterators will behave incorrectly.
> type VirtualProperties struct {
> ```

Do we need a separate struct definition for VirtualProperties, or can we just use `CommonProperties` directly?
___
*[`sstable/reader_virtual.go` line 28 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2911#-NenngGT2Hc_IO_-XD6j:-NenngGT2Hc_IO_-XD6k:b-iivv0r) ([raw file](https://github.com/cockroachdb/pebble/blob/cd3ffd1c1a64d893425e19953c90997348e63c10/sstable/reader_virtual.go#L28)):*
> ```Go
> 	// TODO(bananabrick): Check if any code relies on accurate values of these
> 	// properties for correctness. Especially the 0 vs non-0 case. Just wire this
> 	// up, and then trace the influence of these variables.
> ```

I was going to mention the NumRangeKeySets case, but I see in the comment above you found it.
___
*[`sstable/reader_virtual.go` line 97 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2911#-NenoVb101Etr_bIOvYf:-NenoVb101Etr_bIOvYg:bjeuzvh) ([raw file](https://github.com/cockroachdb/pebble/blob/cd3ffd1c1a64d893425e19953c90997348e63c10/sstable/reader_virtual.go#L97)):*
> ```Go
> 	v.Properties.NumRangeDeletions = ceilDiv(reader.Properties.NumRangeDeletions*meta.Size, meta.FileBacking.Size)
> 	v.Properties.NumRangeKeyDels = ceilDiv(reader.Properties.NumRangeKeyDels*meta.Size, meta.FileBacking.Size)
> 	v.Properties.NumRangeKeySets = ceilDiv(reader.Properties.NumRangeKeySets*meta.Size, meta.FileBacking.Size)
> ```

nit: Can you add a comment here about the necessity of making this ≥1 if it's possible the virtual SST contains any range key sets?

**Review by bananabrick — COMMENTED** [review]
@jbowens Writing some tests for this now. I did the Properties reflection in a separate commit in this pr. Seems kinda complex.

PTAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2911#-:-NfCCRAO8SFBOh8tzTXz:bvyojns)* status: 1 of 8 files reviewed, 4 unresolved discussions (waiting on @jbowens)

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2911)* status: 1 of 11 files reviewed, 8 unresolved discussions (waiting on @bananabrick)

___
*[`sstable/properties.go` line 46 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2911#-NfCc5ReA_pHWTRzQKAF:-NfCc5ReA_pHWTRzQKAG:bsukeap) ([raw file](https://github.com/cockroachdb/pebble/blob/0983b6f129543b7a47a7e3965a45cd014c420fa6/sstable/properties.go#L46)):*
> ```Go
> 			}
> 			propTagMap[tag] = f
> 			propOffsetTagMap[f.Offset] = tag
> ```

I'm confused here. For fields within `CommonProps` is `f.Offset` relative to the `Properties` struct or the `CommonProps` struct? Maintaining separate maps for the two types would be less subtle.
___
*[`sstable/properties.go` line 66 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2911#-NfCcGDBBUSXPx7fLNRQ:-NfCcGDBBUSXPx7fLNRR:b-6z7bgt) ([raw file](https://github.com/cockroachdb/pebble/blob/0983b6f129543b7a47a7e3965a45cd014c420fa6/sstable/properties.go#L66)):*
> ```Go
> // if NumRangeKeySets == 0, but the sstable actually contains range keys, then
> // the iterators will behave incorrectly.
> type CommonProps struct {
> ```

nit: rename to `CommonProperties` for parity with `Properties`?
___
*[`sstable/reader.go` line 953 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2911#-Neno6_s2n33lrDyXC7b:-NfCdLdNDETrMUfy-hrj:b-4ozmtz) ([raw file](https://github.com/cockroachdb/pebble/blob/cd3ffd1c1a64d893425e19953c90997348e63c10/sstable/reader.go#L953)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

Hrm, could we embed `CommonProperties` into the `Properties` struct to avoid the duplication and boiler plate? We might need to adjust some of the reflection to handle the embedded struct, but it seems doable.
</blockquote></details>

This func seems unnecessary now, as callers can directly take a reference themselves.
___
*[`sstable/reader_virtual.go` line 97 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2911#-NenoVb101Etr_bIOvYf:-NfCcgWL4MeBGQYX1c0r:b-13aza4) ([raw file](https://github.com/cockroachdb/pebble/blob/cd3ffd1c1a64d893425e19953c90997348e63c10/sstable/reader_virtual.go#L97)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

nit: Can you add a comment here about the necessity of making this ≥1 if it's possible the virtual SST contains any range key sets?
</blockquote></details>

nit: this nit still stands
___
*[`sstable/properties_test.go` line 44 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2911#-NfCcnvx80qmZ20wFLzu:-NfCcnvx80qmZ20wFLzv:bfwu4l2) ([raw file](https://github.com/cockroachdb/pebble/blob/0983b6f129543b7a47a7e3965a45cd014c420fa6/sstable/properties_test.go#L44)):*
> ```Go
> 	expected.NumRangeDeletions = 17
> 	expected.RawKeySize = 23938
> 	expected.RawValueSize = 1912
> ```

nit: couldn't this be
```
expected := Properties{
    CommonProps: CommonProps{
        NumEntries: 1727,
        // ...
    },
    ComparerName:            "leveldb.BytewiseComparator",
    // ...
}
```
___
*[`sstable/properties_test.go` line 102 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2911#-NfCdBXGAsS5r7BVw_Hi:-NfCdBXH67Iurps-DiK8:b-iipjm8) ([raw file](https://github.com/cockroachdb/pebble/blob/0983b6f129543b7a47a7e3965a45cd014c420fa6/sstable/properties_test.go#L102)):*
> ```Go
> 	expected.NumRangeKeySets = 20
> 	expected.RawKeySize = 25
> 	expected.RawValueSize = 26
> ```

nit: ditto

**Review by bananabrick — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2911)* status: 1 of 13 files reviewed, 7 unresolved discussions (waiting on @jbowens)

___
*[`sstable/properties.go` line 46 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2911#-NfCc5ReA_pHWTRzQKAF:-NfCgCC423lgeEfqIi3x:b-arfnia) ([raw file](https://github.com/cockroachdb/pebble/blob/0983b6f129543b7a47a7e3965a45cd014c420fa6/sstable/properties.go#L46)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

I'm confused here. For fields within `CommonProps` is `f.Offset` relative to the `Properties` struct or the `CommonProps` struct? Maintaining separate maps for the two types would be less subtle.
</blockquote></details>

CommonProps is at the top of the Properties, so it will be the offset within Properties. I'll look into making this less subtle.
___
*[`sstable/reader.go` line 953 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2911#-Neno6_s2n33lrDyXC7b:-NfIQjFW5zV5qr881YgL:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/cd3ffd1c1a64d893425e19953c90997348e63c10/sstable/reader.go#L953)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

This func seems unnecessary now, as callers can directly take a reference themselves.
</blockquote></details>

Done.
___
*[`sstable/reader_virtual.go` line 22 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2911#-NennqgH5u2VHeD99saQ:-NfCgAPzDpJjGgGgE0Kj:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/cd3ffd1c1a64d893425e19953c90997348e63c10/sstable/reader_virtual.go#L22)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

Do we need a separate struct definition for VirtualProperties, or can we just use `CommonProperties` directly?
</blockquote></details>

Done.
___
*[`sstable/reader_virtual.go` line 28 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2911#-NenngGT2Hc_IO_-XD6j:-NfCgA3VAEw6OSX7PTnw:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/cd3ffd1c1a64d893425e19953c90997348e63c10/sstable/reader_virtual.go#L28)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

I was going to mention the NumRangeKeySets case, but I see in the comment above you found it.
</blockquote></details>

Done.
___
*[`sstable/reader_virtual.go` line 97 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2911#-NenoVb101Etr_bIOvYf:-NfCfW1zA8StCPbHsoOi:bii3q6u) ([raw file](https://github.com/cockroachdb/pebble/blob/cd3ffd1c1a64d893425e19953c90997348e63c10/sstable/reader_virtual.go#L97)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

nit: this nit still stands
</blockquote></details>

There was a comment. Maybe I pushed it after you started the review on an older revision. Either way, there should be comment now.
___
*[`testdata/table_stats` line 573 at r10](https://reviewable.io/reviews/cockroachdb/pebble/2911#-NfIQsZA-DRvSc0D5Cub:-NfIQsZA-DRvSc0D5Cuc:b3vmqqt) ([raw file](https://github.com/cockroachdb/pebble/blob/4f3e9945eb23010e61a3c7db23ec17dfd9e500aa/testdata/table_stats#L573)):*
> ```
> keys.missized-tombstones-count: 1
> 
> # Virtual sstables tests. Note that these tests are just for sanity checking
> ```

1. These tests are useful for sanity checking reasons, but aren't interesting because the virtual sstables are tiny. My plan is to do some testing with larger virtual sstables in a follow up pr.

2. Also needs some testing for delete compaction hints, which will also happen in a future pr.
___
*[`sstable/properties_test.go` line 44 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2911#-NfCcnvx80qmZ20wFLzu:-NfIR_ysE6YGA33vr3cS:biz0h0u) ([raw file](https://github.com/cockroachdb/pebble/blob/0983b6f129543b7a47a7e3965a45cd014c420fa6/sstable/properties_test.go#L44)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

nit: couldn't this be
```
expected := Properties{
    CommonProps: CommonProps{
        NumEntries: 1727,
        // ...
    },
    ComparerName:            "leveldb.BytewiseComparator",
    // ...
}
```
</blockquote></details>

Oh yea. I forgot that was a thing.

**Review by bananabrick — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2911)* status: 1 of 13 files reviewed, 7 unresolved discussions (waiting on @jbowens)

___
*[`sstable/properties.go` line 46 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2911#-NfCc5ReA_pHWTRzQKAF:-NfIaNCU4GL6kHzMI4JM:b-8rgqqn) ([raw file](https://github.com/cockroachdb/pebble/blob/0983b6f129543b7a47a7e3965a45cd014c420fa6/sstable/properties.go#L46)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

CommonProps is at the top of the Properties, so it will be the offset within Properties. I'll look into making this less subtle.
</blockquote></details>

I made the generateTagMaps function more robust, and added a comment.

**Review by bananabrick — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2911)* status: 1 of 13 files reviewed, 7 unresolved discussions (waiting on @jbowens)

___
*[`sstable/properties.go` line 46 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2911#-NfCc5ReA_pHWTRzQKAF:-NfIaXw26bU1HFy7YS0a:b4ehmxg) ([raw file](https://github.com/cockroachdb/pebble/blob/0983b6f129543b7a47a7e3965a45cd014c420fa6/sstable/properties.go#L46)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

I made the generateTagMaps function more robust, and added a comment.
</blockquote></details>

Imo, maintaining two maps is equally subtle. We'd have to look for the offset of CommonProperties field in Properties, and add to that the offset of the field within CommonProperties.

**Review by bananabrick — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2911)* status: 1 of 13 files reviewed, 7 unresolved discussions (waiting on @jbowens)

___
*[`sstable/properties.go` line 46 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2911#-NfCc5ReA_pHWTRzQKAF:-NfJ3kpr7D_TnX7DIRv7:b-q9i1tp) ([raw file](https://github.com/cockroachdb/pebble/blob/0983b6f129543b7a47a7e3965a45cd014c420fa6/sstable/properties.go#L46)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

Imo, maintaining two maps is equally subtle. We'd have to look for the offset of CommonProperties field in Properties, and add to that the offset of the field within CommonProperties.
</blockquote></details>

Made another change where the `generateTagMaps` function now asserts that the embedded struct is placed at index 0.

**Review by jbowens — APPROVED** [review]
:lgtm_strong: 

> Reviewed 2 of 6 files at r6, 1 of 3 files at r7, 4 of 6 files at r8, 1 of 5 files at r11, 1 of 1 files at r12, 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2911#-:-NfMhbph73JE2LAS4vcN:b-uwkowd)* status: 12 of 13 files reviewed, 4 unresolved discussions (waiting on @bananabrick)

___
*[`sstable/properties.go` line 46 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2911#-NfCc5ReA_pHWTRzQKAF:-NfMgmLyBi-psj_f0QoD:b-gxbmbs) ([raw file](https://github.com/cockroachdb/pebble/blob/0983b6f129543b7a47a7e3965a45cd014c420fa6/sstable/properties.go#L46)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

Made another change where the `generateTagMaps` function now asserts that the embedded struct is placed at index 0.
</blockquote></details>

Thanks, the comment and assertions make this clearer.
___
*[`sstable/reader.go` line 953 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2911#-Neno6_s2n33lrDyXC7b:-NfMgujd9WPmx_Qkf9ga:biinipd) ([raw file](https://github.com/cockroachdb/pebble/blob/cd3ffd1c1a64d893425e19953c90997348e63c10/sstable/reader.go#L953)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Maybe reviewable is acting up, but I still see this func
___
*[`table_stats_test.go` line 30 at r13](https://reviewable.io/reviews/cockroachdb/pebble/2911#-NfMhP4p-vDrAj5grq6o:-NfMhP4p-vDrAj5grq6p:b-kxph4k) ([raw file](https://github.com/cockroachdb/pebble/blob/ef3225577eb8a0203065d97f6ab97860eb91eafb/table_stats_test.go#L30)):*
> ```Go
> // as expected.
> func TestLargeTableStats(t *testing.T) {
> ```

is this empty TestLargeTableStats test intended for a followup?

**Review by bananabrick — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2911)* status: 12 of 13 files reviewed, 4 unresolved discussions (waiting on @jbowens)

___
*[`sstable/reader.go` line 953 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2911#-Neno6_s2n33lrDyXC7b:-NfMieY19aXcgmgcnB48:bn3mm2c) ([raw file](https://github.com/cockroachdb/pebble/blob/cd3ffd1c1a64d893425e19953c90997348e63c10/sstable/reader.go#L953)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

Maybe reviewable is acting up, but I still see this func
</blockquote></details>

I don't see it. Just the `CommonProperties` function. If you were referring to the `CommonProperties` function, then it is necessary for the interface.
___
*[`table_stats_test.go` line 30 at r13](https://reviewable.io/reviews/cockroachdb/pebble/2911#-NfMhP4p-vDrAj5grq6o:-NfMjfoo-n2XSAtOI626:bwve1kw) ([raw file](https://github.com/cockroachdb/pebble/blob/ef3225577eb8a0203065d97f6ab97860eb91eafb/table_stats_test.go#L30)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

is this empty TestLargeTableStats test intended for a followup?
</blockquote></details>

It is, but I removed it from this pr. I was initially going to add that test in this pr.

**Review by bananabrick — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2911)* status: 11 of 13 files reviewed, 4 unresolved discussions (waiting on @jbowens)

___
*[`sstable/properties.go` line 46 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2911#-NfCc5ReA_pHWTRzQKAF:-NfMkA1R2V6P6x2046q_:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/0983b6f129543b7a47a7e3965a45cd014c420fa6/sstable/properties.go#L46)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

Thanks, the comment and assertions make this clearer.
</blockquote></details>

Done.

**Comment by bananabrick** [comment]
Failure is this: `MANIFEST cannot contain virtual sstable records due to format major version`.

Bilals change will fix. And I'm once again reminded that the CI rebases our prs on top of master before running.

**Pull request merged**
