### PR TITLE
db: add FormatColumnarBlocks

### PR DESCRIPTION
**Pull request by jbowens**
Add a new format major version enabling use of columnar blocks and a knob to disable columnar blocks. FormatNewest is left pointing to the previous format major version for now until a few remaining issues are resolved.

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/4039)* status: 0 of 19 files reviewed, 1 unresolved discussion (waiting on @jbowens)

___
*[`format_major_version.go` line 356 at r1](https://reviewable.io/reviews/cockroachdb/pebble/4039#-O8xGXh49Rvd3jnOj3wU:-O8xGXh49Rvd3jnOj3wV:bnfzpxh) ([raw file](https://github.com/cockroachdb/pebble/blob/06471b7f1734c94573eae8606309e6ada2cac931/format_major_version.go#L356)):*
> ```Go
> 		}
> 	case sstable.TableFormatPebblev5:
> 		if d.opts.Experimental.EnableColumnarBlocks != nil && !d.opts.Experimental.EnableColumnarBlocks() {
> ```

Shouldn't `EnableColumnarBlocks == nil` map to "don't use them"? (like `EnableValueBlocks` below?). We want them disabled by default for now, right?

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/4039)* status: 0 of 19 files reviewed, 1 unresolved discussion (waiting on @RaduBerinde)

___
*[`format_major_version.go` line 356 at r1](https://reviewable.io/reviews/cockroachdb/pebble/4039#-O8xGXh49Rvd3jnOj3wU:-O8xJ-wH3xRwmDJ-VT9K:b-790x7f) ([raw file](https://github.com/cockroachdb/pebble/blob/06471b7f1734c94573eae8606309e6ada2cac931/format_major_version.go#L356)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Shouldn't `EnableColumnarBlocks == nil` map to "don't use them"? (like `EnableValueBlocks` below?). We want them disabled by default for now, right?
</blockquote></details>

I was thinking they should be enabled by default on Pebble master so that Pebble tests exercise them by default, but when we hook up `FormatColumnarBlocks` in Cockroach we'll default to disabling in the implementation of `EnableColumnarBlocks`

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/4039#-:-O8xJshc8mKZvdGIVdIw:bnfp4nl)* status: 0 of 19 files reviewed, 2 unresolved discussions (waiting on @jbowens)

___
*[`format_major_version.go` line 356 at r1](https://reviewable.io/reviews/cockroachdb/pebble/4039#-O8xGXh49Rvd3jnOj3wU:-O8xJtfm1Q-k7Oz7FN3T:b-rqcxci) ([raw file](https://github.com/cockroachdb/pebble/blob/06471b7f1734c94573eae8606309e6ada2cac931/format_major_version.go#L356)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

I was thinking they should be enabled by default on Pebble master so that Pebble tests exercise them by default, but when we hook up `FormatColumnarBlocks` in Cockroach we'll default to disabling in the implementation of `EnableColumnarBlocks`
</blockquote></details>

I would think we want the default to match CRDB default, but it's up to you - the code change LGTM.

With this change, would the metamorphic tests exercise both row and column formats?
___
*[`options.go` line 695 at r1](https://reviewable.io/reviews/cockroachdb/pebble/4039#-O8xK9-FAoZ3fZFsyvOU:-O8xK9-FAoZ3fZFsyvOV:b-9b46f5) ([raw file](https://github.com/cockroachdb/pebble/blob/06471b7f1734c94573eae8606309e6ada2cac931/options.go#L695)):*
> ```Go
> 		// FormatColumnarBlocks. In lower format major versions, the
> 		// TableFormatPebblev5 format is prohibited.
> 		EnableColumnarBlocks func() bool
> ```

Mention the default when this function is nil. If the default is "enabled", then maybe this should be `DisableColumnarBlocks()` so a `nil` value more naturally maps to "don't disable".

**Review by jbowens — COMMENTED** [review]
Rebased on top of #4042 and #4043. I think there's still a lingering issue that can cause the tests to hang that I need to address before merging.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/4039#-:-O91CF4aCNz4tcpmn1SB:bpem78)* status: 0 of 26 files reviewed, 1 unresolved discussion (waiting on @RaduBerinde)

___
*[`format_major_version.go` line 356 at r1](https://reviewable.io/reviews/cockroachdb/pebble/4039#-O8xGXh49Rvd3jnOj3wU:-O91ByYg0wgysvhchPte:b-3es8de) ([raw file](https://github.com/cockroachdb/pebble/blob/06471b7f1734c94573eae8606309e6ada2cac931/format_major_version.go#L356)):*
Ok, I defaulted to disabled and updated a few tests to explicitly set EnableColumnarBlocks.

> With this change, would the metamorphic tests exercise both row and column formats?

Not yet; only once we bump FormatNewest too
___
*[`options.go` line 695 at r1](https://reviewable.io/reviews/cockroachdb/pebble/4039#-O8xK9-FAoZ3fZFsyvOU:-O91CDeeC4IJeXRN6Bkh:bb6un1j) ([raw file](https://github.com/cockroachdb/pebble/blob/06471b7f1734c94573eae8606309e6ada2cac931/options.go#L695)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Mention the default when this function is nil. If the default is "enabled", then maybe this should be `DisableColumnarBlocks()` so a `nil` value more naturally maps to "don't disable".
</blockquote></details>

Done

**Review by jbowens — COMMENTED** [review]
Ok this is ready for a final look. I also pushed a commit to point FormatNewest to FormatColumnarBlocks and enable the metamorphic tests use as well. It ended up being less work than anticipated.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/4039#-:-O91ake3A4UDxuq-9Dwb:b-u1e921)* status: 0 of 31 files reviewed, 1 unresolved discussion (waiting on @RaduBerinde)

**Comment by RaduBerinde** [comment]
The CI failure is interesting:
```
--- FAIL: TestCheckLevelsCornerCases (0.00s)
    datadriven.go:144: 
        testdata/level_checker:190:
         L
        a.SET.3 e.SET.4
        e.SET.4:e a.SET.3:a
        L
        d.SET.1 f.SET.2
        d.SET.1:d f.SET.2:f
        expected:
        Level 1
          file 0: [a#3,SET-e#4,SET]
        Level 2
          file 0: [d#1,SET-f#2,SET]
        
        found:
        pebble: keys must be added in strictly increasing order: a#3,SET
```

**Review by RaduBerinde — APPROVED** [review]
:lgtm: Very cool!!

> Reviewed 11 of 19 files at r1, 11 of 12 files at r2, 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/4039#-:-O92srjd3vUu77nRNW-Y:b1g9y04)* status: all files reviewed, 2 unresolved discussions (waiting on @jbowens)

___
*[`compaction_test.go` line 624 at r2](https://reviewable.io/reviews/cockroachdb/pebble/4039#-O92s29Y3bhp_pU2ZmLg:-O92s29Y3bhp_pU2ZmLh:b-zfiz8j) ([raw file](https://github.com/cockroachdb/pebble/blob/c579a4d34ac70bb1866b110ffb1d0e53f0b6ef5c/compaction_test.go#L624)):*
> ```Go
> 		MemTableSize:          memTableSize,
> 	}
> 	opts.Experimental.EnableColumnarBlocks = func() bool { return true }
> ```

`testingRandomized` already sets this
___
*[`options_test.go` line 37 at r2](https://reviewable.io/reviews/cockroachdb/pebble/4039#-O92s_X59ZiM9bDiysXI:-O92s_X59ZiM9bDiysXJ:b-hhgw7j) ([raw file](https://github.com/cockroachdb/pebble/blob/c579a4d34ac70bb1866b110ffb1d0e53f0b6ef5c/options_test.go#L37)):*
> ```Go
> 		t.Logf("Running %s with format major version %s", t.Name(), o.FormatMajorVersion.String())
> 	}
> 	// Enable columnar blocks if using a format major version that supports it.
> ```

[nit] maybe do this after a coin flip?

**Review by jbowens — COMMENTED** [review]
> The CI failure is interesting:

Whoops, was failing to propagate the disableKeyOrderChecks setting (and that test is only run NOT under `-invariants`). There were a couple more issues in the test that I fixed up.

TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/4039#-:-O95nSCnAUH_EnFUxRiB:b-baaer0)* status: 20 of 33 files reviewed, 1 unresolved discussion (waiting on @RaduBerinde)

___
*[`compaction_test.go` line 624 at r2](https://reviewable.io/reviews/cockroachdb/pebble/4039#-O92s29Y3bhp_pU2ZmLg:-O95nbFcClQSiHHUsKeC:bb6un1j) ([raw file](https://github.com/cockroachdb/pebble/blob/c579a4d34ac70bb1866b110ffb1d0e53f0b6ef5c/compaction_test.go#L624)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

`testingRandomized` already sets this
</blockquote></details>

Done
___
*[`options_test.go` line 37 at r2](https://reviewable.io/reviews/cockroachdb/pebble/4039#-O92s_X59ZiM9bDiysXI:-O95ncQz1NkOa2MjppPk:b-olkmw7) ([raw file](https://github.com/cockroachdb/pebble/blob/c579a4d34ac70bb1866b110ffb1d0e53f0b6ef5c/options_test.go#L37)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] maybe do this after a coin flip?
</blockquote></details>

Did a biased coin flip

**Pull request merged**
