### PR TITLE
db: genericize rangeDel{Cache,Frags} into keySpan{Cache,Frags}

### PR DESCRIPTION
**Pull request by jbowens**
Rename the memtable's `rangeDelCache` and `rangeDelFrags` types to
`keySpanCache` and `keySpanFrags` so they may be used for caching range
key fragments too.

In addition to the pure renames, I made a small refactor to decouple the
dependency on `memTable.tombstones` by adding a pointer to the skiplist
in a `keySpanCache` field.

### CODE REVIEW

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1356)* status: all files reviewed, 1 unresolved discussion (waiting on @jbowens)

___
*[mem_table.go, line 371 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1356#-MnCfXO02HCDzQrovnTP:-MnCfXO02HCDzQrovnTQ:bpia7sx) ([raw file](https://github.com/cockroachdb/pebble/blob/02b3c8b71c2fd45f1579f3a42c97b9c7e25d56e6/mem_table.go#L371)):*
> ```Go
> 		return nil
> 	}
> 	return frags.get(c.skl, c.cmp, c.formatKey)
> ```

Can't the code in this method extract these from `m` like the callee used to do, and then call `frags.get`. I am trying to understand why we need the member variables in `keySpanCache`.

Or is this just the first step in the refactor and `get` will eventually not take a `memTable` parameter. Should it be removed now itself, since it is unused?

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1356)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @sumeerbhola)

___
*[mem_table.go, line 371 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1356#-MnCfXO02HCDzQrovnTP:-MnCoIDcCTsIhrvGyYsX:bks4mp9) ([raw file](https://github.com/cockroachdb/pebble/blob/02b3c8b71c2fd45f1579f3a42c97b9c7e25d56e6/mem_table.go#L371)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Can't the code in this method extract these from `m` like the callee used to do, and then call `frags.get`. I am trying to understand why we need the member variables in `keySpanCache`.

Or is this just the first step in the refactor and `get` will eventually not take a `memTable` parameter. Should it be removed now itself, since it is unused?
</blockquote></details>

Oops, yeah, I forgot to remove the `memTable` parameter when extracting this change from another branch. Thanks :)

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1356#-:-MnQfqi-4EqoZGDqBtk2:bg7igkv)* status: all files reviewed, 1 unresolved discussion (waiting on @sumeerbhola)

**Review by jbowens — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1356#-:-MnR3a1CAsIW6gAJMzRD:b-814g8k)* status: all files reviewed, 1 unresolved discussion (waiting on @sumeerbhola)

**Pull request merged**
