### PR TITLE
sstable: add LoadBlockSema option

### PR DESCRIPTION
**Pull request by RaduBerinde**
Add option to use a semaphore to limit the number of block loads in
parallel.

### CODE REVIEW

**Review by sean- — APPROVED** [review]
LGTM, thank you!

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3649#-:-O-26hzh6-fNRYlpnPeP:b-5kvqwr)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jbowens and @sumeerbhola)

**Review by jbowens — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3649#-:-O-2Ba92Dwe8aGHSn969:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @sumeerbhola)

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3649#-:-O-2C-399EtGySZMN9Fp:bg7igkv)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RaduBerinde)

**Comment by RaduBerinde** [comment]
TFTRs!

**Pull request merged**
