### PR TITLE
sstable: support block checksum validation for entire SSTables

### PR DESCRIPTION
**Pull request by nicktrav**
To provide better detection of corruption upon ingestion of an SSTable,
add the ability for an `sstable.Reader` to validate the checksums of all
blocks in the underlying file for the SSTable.

The new `(*sstable.Reader).ValidateBlockChecksums` will be used by a
subsequent change to perform validation of an SSTable upon ingestion,
with any corruption that may be detected detected passed to the
corruption reporting and recovery mechanism outlined in
cockroachdb/cockroach#67568.

See also: #1203.

### CODE REVIEW

**Review by itsbilal — APPROVED** [review]
:lgtm: though one clarification about the PR description: this change can live pretty independently of cockroachdb/cockroach#67568, or at least it can be connected into cockroach before any of that is done. I'm imagining a post-`Ingest` step where we call this method from Cockroach in the background, and panic if we see any `ErrCorruption`s, in line with existing corruption behaviour.

I'm not sure if we want corruption-detected-at-ingestion-time to follow the same semantics as general occurrences of on-disk corruption; that's a conversation we haven't had yet.

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1240#-:-MiNmHlh9ELSAJCbb45J:byebo0u)* status: all files reviewed, 3 unresolved discussions (waiting on @jbowens and @sumeerbhola)

___
*[sstable/reader.go, line 2174 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1240#-Mi8-c7fEf5iJILSW-dK:-MiNj-IZEOvHNHG8oQgO:b7wpboa) ([raw file](https://github.com/cockroachdb/pebble/blob/32c3fb4d8357a2cfaafa6c6da587f009f2b70541/sstable/reader.go#L2174)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

Ah. I meant to ask earlier how to correctly use the `readAheadState`. The only use I could find was [here](https://github.com/cockroachdb/pebble/blob/ff43a5880febae79a229ba1cdbfa666d25056005/sstable/reader_test.go#L483-L490) and [here](https://github.com/cockroachdb/pebble/blob/ff43a5880febae79a229ba1cdbfa666d25056005/sstable/reader.go#L86) (with zero value).

cc @itsbilal - do you have thoughts on whether `initialReadaheadSize` would be fine to use here as an initial value?
</blockquote></details>

Yes, you'd want `blockRS.size` to be set to `initialReadaheadSize` over here. We actually don't use the zero value anywhere - you'll notice we set `i.dataRS.size = initialReadaheadSize` when the iterator is init'd.

**Review by nicktrav — COMMENTED** [review]
> I'm imagining a post-Ingest step where we call this method from Cockroach in the background, and panic if we see any ErrCorruptions, in line with existing corruption behaviour.

I think this lines up with what @sumeerbhola and I had discussed in that once a table is ingested, we queue it up to be checked. Currently, this will happen in a background task, similar to how the table stats are computed.

It sounds like you're suggesting that we could also expose a way for Cockroach to explicitly force the checking of one or more files, post-ingestion.

The next PR I have queued up will wire up the background task approach, but it shouldn't be too hard to also expose / export something to Cockroach too, like you mentioned. I'll leave that for a follow up.

For now, I will fix up the commit message to mention this.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1240#-:-MiNofMn5LlB3GtIiqM3:b-r4xvxs)* status: all files reviewed, 3 unresolved discussions (waiting on @jbowens and @sumeerbhola)

**Comment by itsbilal** [comment]
> It sounds like you're suggesting that we could also expose a way for Cockroach to explicitly force the checking of one or more files, post-ingestion.

I guess my emphasis wasn't on the cockroach side of it, but rather the fact that _something_ does it in the background. Giving that responsibility to Pebble seems to make more sense. What you and Sumeer discussed sounds good; looking forward to seeing that in the subsequent PR!

**Review by nicktrav — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> Dismissed @sumeerbhola from 3 discussions.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1240)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jbowens)

___
*[sstable/reader.go, line 2161 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1240#-Mi7ybpB-fXDMZzOFIVi:-MiNyrzi2BtO6aFXkRf5:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/32c3fb4d8357a2cfaafa6c6da587f009f2b70541/sstable/reader.go#L2161)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

Done :+1: 
</blockquote></details>

Done.
___
*[sstable/reader.go, line 2174 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1240#-Mi8-c7fEf5iJILSW-dK:-MiNyb6v6Z3qtNQOPfUA:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/32c3fb4d8357a2cfaafa6c6da587f009f2b70541/sstable/reader.go#L2174)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Yes, you'd want `blockRS.size` to be set to `initialReadaheadSize` over here. We actually don't use the zero value anywhere - you'll notice we set `i.dataRS.size = initialReadaheadSize` when the iterator is init'd.
</blockquote></details>

Done.
___
*[sstable/reader_test.go, line 624 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1240#-Mi80XsE9-oB_C7NymU1:-MiNydsa7jCHHj2EbmlW:b-a57hjb) ([raw file](https://github.com/cockroachdb/pebble/blob/32c3fb4d8357a2cfaafa6c6da587f009f2b70541/sstable/reader_test.go#L624)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

:+1: - let me know if you think there are other scenarios that should be covered.
</blockquote></details>

Followed up offline. This should be sufficient.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1240#-:-MiSJm-s-Sfdmw9VUPPE:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jbowens)

**Pull request merged**
