### PR TITLE
colblk: fix UintsBuilder bug in default mode

### PR DESCRIPTION
**Pull request by RaduBerinde**
When we are in `useDefault` mode, the slice can be smaller than the
number of rows. In that case, the existing code was reading outside
the underlying slice and writing out garbage.

We should reconsider the use of `UnsafeSlice` here, as I don't think
it's buying us much performance-wise.

Informs https://github.com/cockroachdb/cockroach/issues/132964

### CODE REVIEW

**Comment by RaduBerinde** [comment]
It's worth noting that `TestCockroachDataBlock` finds this issue on `master` (now that we also generate some logical times):

```
go test -tags invariants --exec 'stress -p 4' -timeout 0 -v ./sstable/colblk -run CockroachDataBlock

=== RUN   TestCockroachDataBlock
    cockroach_test.go:27: seed: 1729349928313842000
--- FAIL: TestCockroachDataBlock (0.00s)
panic: incorrect target width [recovered]
        panic: incorrect target width
```

The test passes reliably with the fix.

**Review by jbowens — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/4078#-:-O9b-P6t1x7DR2nXzSoQ:bg7igkv)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RaduBerinde)

**Review by jbowens — COMMENTED** [review]
Good catch!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/4078#-:-O9b-SFT0c5MouxO-V2h:b6zrrk4)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RaduBerinde)

**Comment by RaduBerinde** [comment]
TFTR!

**Pull request merged**
