### PR TITLE
Configurable initial and max retained batch sizes

### PR DESCRIPTION
**Pull request by lahsivjar**
Closes: https://github.com/cockroachdb/pebble/issues/2780

### CODE REVIEW

**Comment by lahsivjar** [comment]
@jbowens Would appreciate a quick review whenever you have time.

**Comment by lahsivjar** [comment]
@jbowens Friendly ping, any feedback on the PR is appreciated.

**Comment by inge4pres** [comment]
This is very cool and I also have a similar use case 👍🏼 
Plus, there is no breaking change to the public API so it would be nice to have this landed 🙏🏼

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3139)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @jbowens and @lahsivjar)

___
*[`batch.go` line 275 at r4](https://reviewable.io/reviews/cockroachdb/pebble/3139#-NvCvqCl0RWOmVnsOQXH:-NvCwY_ZCgr9K4WndMzX:b-gfmz9p) ([raw file](https://github.com/cockroachdb/pebble/blob/43fd2e881a983e8dcc431eccf1fc878fdf79bb19/batch.go#L275)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

I think this should not be a pointer—otherwise, we'll suffer an additional heap allocation for every new batch initialization
</blockquote></details>

+1. `ensureDefaults` should just modify in-place and return nothing.
___
*[`batch.go` line 2421 at r4](https://reviewable.io/reviews/cockroachdb/pebble/3139#-NvCwbUvD-6Ljics6F4j:-NvCwbUvD-6Ljics6F4k:b-oo9i76) ([raw file](https://github.com/cockroachdb/pebble/blob/43fd2e881a983e8dcc431eccf1fc878fdf79bb19/batch.go#L2421)):*
> ```Go
> func WithInitialSizeBytes(s int) BatchOption {
> 	return func(opts *batchOptions) {
> 		if s > 0 {
> ```

[nit] The special handling of s <= 0 is odd here, it shouldn't be valid to use such a value.

**Comment by lahsivjar** [comment]
@jbowens @RaduBerinde Thanks both for your reviews. I have addressed the comments now.

**Review by RaduBerinde — COMMENTED** [review]
Thanks! Can you squash the commits?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3139#-:-NvD6fwi3-MkIFCIsW1a:b-nkc2z)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @jbowens and @lahsivjar)

___
*[`batch_test.go` line 1744 at r5](https://reviewable.io/reviews/cockroachdb/pebble/3139#-NvD6e0o4KI2eHvFcLr-:-NvD6e0o4KI2eHvFcLr0:b-s3vmj1) ([raw file](https://github.com/cockroachdb/pebble/blob/b0e5e0c8163332f393990119b8492b759eec4792/batch_test.go#L1744)):*
> ```Go
> 		},
> 		{
> 			name: "with_invalid_values",
> ```

I think we need to remove this test.

**Comment by lahsivjar** [comment]
> Thanks! Can you squash the commits?

@RaduBerinde Done! Also removed the bad test.

**Review by RaduBerinde — APPROVED** [review]
Thank you!

**Pull request merged**
