### PR TITLE
db: add format major version for flushable ingests

### LINKED ISSUE #2292: db: add format major version gating for flushable ingests

### PR DESCRIPTION
**Pull request by jbowens**
Introduce a new format major version that gates uses of flushable ingests and the corresponding backwards-incompatible changes to the write-ahead log.

Close #2292.

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]
:lgtm: modulo some nits

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2363#-:-NPJEboQ7pkhwHguuHdG:bia0nl7)* status: 0 of 8 files reviewed, 3 unresolved discussions (waiting on @bananabrick and @jbowens)

___
*[`format_major_version.go` line 125 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2363#-NPJDcjc5hMgz1NZ7qYu:-NPJDcjc5hMgz1NZ7qYv:b-f5ihil) ([raw file](https://github.com/cockroachdb/pebble/blob/74f40ed1593ee567bf1af8e7bb6c807a8c4b9f48/format_major_version.go#L125)):*
> ```Go
> 	// major version.
> 	//
> 	// WARNING: In development, so no production code should upgrade to this
> ```

[nit] Unrelated, but this comment needs an update? @sumeerbhola 
___
*[`format_major_version.go` line 149 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2363#-NPJDI3y6KsUeSNEj1J8:-NPJDI3y6KsUeSNEj1J9:bk6wmiw) ([raw file](https://github.com/cockroachdb/pebble/blob/74f40ed1593ee567bf1af8e7bb6c807a8c4b9f48/format_major_version.go#L149)):*
> ```Go
> 	// updated to return the maximum allowable version for the new
> 	// FormatMajorVersion.
> 	FormatNewest FormatMajorVersion = FormatFlushableIngest
> ```

[nit] this can be `iota - 1` so it doesn't need to be updated
___
*[`ingest.go` line 847 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2363#-NPJE0rB-mheUxO3_nyp:-NPJE0rB-mheUxO3_nyq:b-76bo0n) ([raw file](https://github.com/cockroachdb/pebble/blob/74f40ed1593ee567bf1af8e7bb6c807a8c4b9f48/ingest.go#L847)):*
> ```Go
> 			m := d.mu.mem.queue[i]
> 			if ingestMemtableOverlaps(d.cmp, m, meta) {
> 				if (len(d.mu.mem.queue) > d.opts.MemTableStopWritesThreshold-1) ||
> ```

[nit] I would invert the two branches, it's easier to reason about a list of conditions that all have to be true. And maybe put the checks in reverse order so we start with the version, then the flag

**Review by nicktrav — APPROVED** [review]
Nice. :lgtm:

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2363#-:-NPKJPg17QCu3cBs4-I1:bxsbkqo)* status: all files reviewed, 4 unresolved discussions (waiting on @bananabrick and @jbowens)

___
*[`options.go` line 636 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2363#-NPKJDCn4oMV_A4DODRS:-NPKJDCn4oMV_A4DODRT:b-zg7f10) ([raw file](https://github.com/cockroachdb/pebble/blob/74f40ed1593ee567bf1af8e7bb6c807a8c4b9f48/options.go#L636)):*
> ```Go
> 		//
> 		// TODO(bananabrick,jackson): Remove this field and unconditionally
> 		// ingest as flushable.
> ```

Do we have an issue tracking unconditionally enabling this?

**Review by bananabrick — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2363#-:-NPKKqVOEhFIqQ54Av-Q:bg7igkv)* status: all files reviewed, 5 unresolved discussions (waiting on @jbowens)

___
*[`options.go` line 635 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2363#-NPKKZXqA8nwfS8Msl0f:-NPKKZXqA8nwfS8Msl0g:b-m0jd7v) ([raw file](https://github.com/cockroachdb/pebble/blob/74f40ed1593ee567bf1af8e7bb6c807a8c4b9f48/options.go#L635)):*
> ```Go
> 		// version is also at least `FormatFlushableIngest`.
> 		//
> 		// TODO(bananabrick,jackson): Remove this field and unconditionally
> ```

I don't think we want to remove this field anymore as it's also used in metamorphic tests. Disabling/enabling this gives us coverage for cases where flushable ingestions are corrupting data.

**Comment by RaduBerinde** [comment]
*[`options.go` line 635 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2363#-NPKKZXqA8nwfS8Msl0f:-NPK_PLU1s1LgZbrRghv:bz37ywj) ([raw file](https://github.com/cockroachdb/pebble/blob/74f40ed1593ee567bf1af8e7bb6c807a8c4b9f48/options.go#L635)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

I don't think we want to remove this field anymore as it's also used in metamorphic tests. Disabling/enabling this gives us coverage for cases where flushable ingestions are corrupting data.
</blockquote></details>

It might make sense to flip its meaning (`DisableIngestSSTTablesAsFlushable`) so that the zero value is the default.

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2363)* status: 5 of 10 files reviewed, 4 unresolved discussions (waiting on @bananabrick, @nicktrav, and @RaduBerinde)

___
*[`format_major_version.go` line 149 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2363#-NPJDI3y6KsUeSNEj1J8:-NPNUoWI8-miMFan0nsA:b-4pj5my) ([raw file](https://github.com/cockroachdb/pebble/blob/74f40ed1593ee567bf1af8e7bb6c807a8c4b9f48/format_major_version.go#L149)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] this can be `iota - 1` so it doesn't need to be updated
</blockquote></details>

Nice, done.
___
*[`ingest.go` line 847 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2363#-NPJE0rB-mheUxO3_nyp:-NPNVrmo-xmrwmBo4Xtn:b-5e2aff) ([raw file](https://github.com/cockroachdb/pebble/blob/74f40ed1593ee567bf1af8e7bb6c807a8c4b9f48/ingest.go#L847)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] I would invert the two branches, it's easier to reason about a list of conditions that all have to be true. And maybe put the checks in reverse order so we start with the version, then the flag
</blockquote></details>

Reversed the order of the checks but kept the branch ordering; I like the removal of the 'exceptional' cases, leaving the outer body the common path.
___
*[`options.go` line 635 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2363#-NPKKZXqA8nwfS8Msl0f:-NPNWFCGEhXqsI8isc2c:biz1rl9) ([raw file](https://github.com/cockroachdb/pebble/blob/74f40ed1593ee567bf1af8e7bb6c807a8c4b9f48/options.go#L635)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

It might make sense to flip its meaning (`DisableIngestSSTTablesAsFlushable`) so that the zero value is the default.
</blockquote></details>

Inverted the setting.

It doesn't look like this was active in the metamorphic tests, because it wasn't serialized to the OPTIONS file. I'm going to follow up with adding a unit test that ensures the metamorphic test's `randomOptions` survive a serialization roundtrip.

**Comment by jbowens** [comment]
TFTRs!

**Pull request merged**
