### PR TITLE
replay: add replay with pacing

### PR DESCRIPTION
**Pull request by coolcom200**
Add pacer interface, and three pacers  `PaceByReferenceReadAmp` ,
`PaceByFixedReadAmp` and `Unpaced`. The pacer is designed to ensure that
workloads are processed in a similar manner to the load when being
collected. This allows collection to be performed, and replayed on
machines with different performance characteristics.

The pacer implementations checks the  `pebble.Metrics` on the  `Runner`
in order to determine if an operation should be applied during replay.
The metrics on the runner are updated by a separate goroutine that is
signaled by the `compactionNotified` goroutine when a compaction ends.

The `compactionNotified` goroutine ensures that we synchronizes the
compaction end events and metric updates. That is we don’t miss updating
metrics when compactions do occur.

Additionally add a compaction tracker for testing purposes that keeps
track of the number of compactions and allows for waiting till a
compaction reaches a desired threshold.

Resolves:  #2057

### CODE REVIEW

**Review by jbowens — COMMENTED** [review]
> Reviewed 1 of 8 files at r1, 1 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2152)* status: 2 of 12 files reviewed, 7 unresolved discussions (waiting on @coolcom200)

___
*[`replay/replay.go` line 43 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2152#-NIDP9b7AJmISZf1YV0d:-NIDP9b7AJmISZf1YV0e:b-gongzn) ([raw file](https://github.com/cockroachdb/pebble/blob/b619cd9abcfe9b2cb7ac14d848f38018650d0e71/replay/replay.go#L43)):*
> ```Go
> // computeReadAmp calculates the read amplification from a manifest.Version
> func computeReadAmp(v *manifest.Version) int {
> 	refRAmp := v.L0Sublevels.ReadAmplification()
> ```

nit: s/refRamp/rAmp/
___
*[`replay/replay.go` line 55 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2152#-NIDPEuCCwrhdU-_gkgq:-NIDPEuCCwrhdU-_gkgr:buor1eq) ([raw file](https://github.com/cockroachdb/pebble/blob/b619cd9abcfe9b2cb7ac14d848f38018650d0e71/replay/replay.go#L55)):*
> ```Go
> // PaceByFixedReadAmp to wait on the dbMetricsNotifier condition variable if the
> // read amplification observed is greater than the specified target (refRAmp).
> func waitAndCompare(r *Runner, refRAmp int) {
> ```

nit:  s/`waitAndCompare`/`waitForReadAmpLE`?
___
*[`replay/replay.go` line 85 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2152#-NIDPiHzCtYCBFEsWv0j:-NIDPiI-2PiUAVrMjeCj:b-82vitv) ([raw file](https://github.com/cockroachdb/pebble/blob/b619cd9abcfe9b2cb7ac14d848f38018650d0e71/replay/replay.go#L85)):*
> ```Go
> // PaceByFixedReadAmp implements Pacer by applying each new write following a
> // fixed read amplification.
> type PaceByFixedReadAmp struct {
> ```

nit: can make this `type PaceByFixedReadAmp int`
___
*[`replay/replay.go` line 106 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2152#-NIDPs2A8wXOf84_b098:-NIDPs2B4WjBC2f0JhU8:bxou6nn) ([raw file](https://github.com/cockroachdb/pebble/blob/b619cd9abcfe9b2cb7ac14d848f38018650d0e71/replay/replay.go#L106)):*
> ```Go
> 	// Internal state.
> 	cancel            func()
> 	workloadExhausted chan struct{}
> ```

can you add a comment explaining the meaning of 'workload exhausted' (we've applied all of the workload's modifications but might not have finished compacting). And also that only a single item is sent to the channel when exhausted, so it should only be read from the `refreshMetrics` goroutine
___
*[`replay/replay.go` line 325 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2152#-NIDRKiQ-EioJNH-jmWI:-NIDRKiQ-EioJNH-jmWJ:b1knw9o) ([raw file](https://github.com/cockroachdb/pebble/blob/b619cd9abcfe9b2cb7ac14d848f38018650d0e71/replay/replay.go#L325)):*
> ```Go
> 		}
> 
> 		r.Pacer.pace(r, step)
> ```

mind leaving a TODO to sum all the paced durations to report as a statistic at the end?
___
*[`replay/replay.go` line 455 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2152#-NIDRf3P56pLxvril0e-:-NIDRf3P56pLxvril0e0:b-8ehobc) ([raw file](https://github.com/cockroachdb/pebble/blob/b619cd9abcfe9b2cb7ac14d848f38018650d0e71/replay/replay.go#L455)):*
> ```Go
> 				// database at this point when the workload was collected. This
> 				// can be useful for pacing.
> 				pv := s.v // save the previous version
> ```

s.v should be nil, because it's a local variable, no? I think we need save the current version to a global variable with a scope outside this step's iteration
___
*[`replay/testdata/corpus/findManifestStart` line 26 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2152#-NIDSJKvD2qkcyFIRBKH:-NIDSJKvD2qkcyFIRBKI:b-eb15iq) ([raw file](https://github.com/cockroachdb/pebble/blob/b619cd9abcfe9b2cb7ac14d848f38018650d0e71/replay/testdata/corpus/findManifestStart#L26)):*
> ```
> 0188001729f6a822d807280901b42e00000000008a5cb45d0605d8fff39b
> 0601670014c4ff84011ef089fd0b53825747ac000188001729f6a826a109
> 900901c12e00000000001ef089fd0b5382580a
> ```

we generally try to have binary data be generated by the test itself, so it's programmatically able to be reconstructed. it also helps with understanding the test itself

**Review by jbowens-alt — COMMENTED** [review]
> Reviewed 1 of 11 files at r3, 1 of 10 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2152)* status: 2 of 13 files reviewed, 18 unresolved discussions (waiting on @coolcom200 and @jbowens)

___
*[`internal/datatest/datatest.go` line 96 at r7](https://reviewable.io/reviews/cockroachdb/pebble/2152#-NJfTYcy8D4h9UXrDIy0:-NJfTYcy8D4h9UXrDIy1:b-8so11) ([raw file](https://github.com/cockroachdb/pebble/blob/3b107a1a7bcd923a189b7430cd487ba4db62764d/internal/datatest/datatest.go#L96)):*
> ```Go
> }
> 
> // CompactionTracker is a listener that tracks the number of compactions
> ```

nit: period
___
*[`internal/datatest/datatest.go` line 103 at r7](https://reviewable.io/reviews/cockroachdb/pebble/2152#-NJfTc6dCfH7cB6By9um:-NJfTc6e1MULoUCWBq-7:b-1h31wy) ([raw file](https://github.com/cockroachdb/pebble/blob/3b107a1a7bcd923a189b7430cd487ba4db62764d/internal/datatest/datatest.go#L103)):*
> ```Go
> }
> 
> // NewCompactionTracker setups the necessary to keep track of the
> ```

nit: necessary .. "options"?
___
*[`internal/datatest/datatest.go` line 104 at r7](https://reviewable.io/reviews/cockroachdb/pebble/2152#-NJfTZTY8bA5n9lK0KbO:-NJfTZTY8bA5n9lK0KbP:b-8so11) ([raw file](https://github.com/cockroachdb/pebble/blob/3b107a1a7bcd923a189b7430cd487ba4db62764d/internal/datatest/datatest.go#L104)):*
> ```Go
> 
> // NewCompactionTracker setups the necessary to keep track of the
> // compactions that are in flight
> ```

nit: period
___
*[`internal/datatest/datatest.go` line 106 at r7](https://reviewable.io/reviews/cockroachdb/pebble/2152#-NJfTkNk1P2W95fFkO6i:-NJfTkNk1P2W95fFkO6j:bitiefc) ([raw file](https://github.com/cockroachdb/pebble/blob/3b107a1a7bcd923a189b7430cd487ba4db62764d/internal/datatest/datatest.go#L106)):*
> ```Go
> // compactions that are in flight
> func NewCompactionTracker(options *pebble.Options) *CompactionTracker {
> 	cql := CompactionTracker{}
> ```

nit: s/cql/ct/?
___
*[`internal/datatest/datatest.go` line 131 at r7](https://reviewable.io/reviews/cockroachdb/pebble/2152#-NJfU9-L9nRs72EID8KH:-NJfU9-L9nRs72EID8KI:bkw7tnf) ([raw file](https://github.com/cockroachdb/pebble/blob/3b107a1a7bcd923a189b7430cd487ba4db62764d/internal/datatest/datatest.go#L131)):*
> ```Go
> 	} else {
> 		options.EventListener = &el
> 	}
> ```

let's copy over `Options.AddEventListener` from [here](https://github.com/cockroachdb/pebble/pull/2161/files#diff-4eec45b6a922746411c0f8aea183e30f77af1b0a5bea1688eaf343a5f9c23703) and use that
___
*[`internal/datatest/datatest.go` line 135 at r7](https://reviewable.io/reviews/cockroachdb/pebble/2152#-NJfUGLD4ie_RRE4FmAI:-NJfUGLD4ie_RRE4FmAJ:b7f4bbp) ([raw file](https://github.com/cockroachdb/pebble/blob/3b107a1a7bcd923a189b7430cd487ba4db62764d/internal/datatest/datatest.go#L135)):*
> ```Go
> }
> 
> // WaitForInflightCompactionsToEqual waits until compactions meet the specified target
> ```

nit: missing period
___
*[`replay/replay.go` line 108 at r7](https://reviewable.io/reviews/cockroachdb/pebble/2152#-NJfWLAL-sDmDCxYb_mq:-NJfWLAL-sDmDCxYb_mr:b-77yz5d) ([raw file](https://github.com/cockroachdb/pebble/blob/3b107a1a7bcd923a189b7430cd487ba4db62764d/replay/replay.go#L108)):*
> ```Go
> 	// have been applied. However once this channel is closed the replayer could
> 	// still not be finished as there could still be compactions running in the
> 	// background.
> ```

this comment needs to be updated now that this channel is no longer closed; it's sent to when the workload is finished. can you add that workloadExhausted is a buffered channel of size 1, so only `refreshMetrics` can read from it.
___
*[`replay/replay.go` line 188 at r7](https://reviewable.io/reviews/cockroachdb/pebble/2152#-NJfVk9r2RgF8HE-0FN8:-NJfVk9r2RgF8HE-0FN9:b39jt4s) ([raw file](https://github.com/cockroachdb/pebble/blob/3b107a1a7bcd923a189b7430cd487ba4db62764d/replay/replay.go#L188)):*
> ```Go
> 		l = r.eventListener()
> 	}
> 	r.Opts.EventListener = &l
> ```

we can use the new `Options.AddEventListener` here too
___
*[`replay/replay.go` line 223 at r7](https://reviewable.io/reviews/cockroachdb/pebble/2152#-NJfW0EI8sXjvr2gA2el:-NJfW0EI8sXjvr2gA2em:bqzronm) ([raw file](https://github.com/cockroachdb/pebble/blob/3b107a1a7bcd923a189b7430cd487ba4db62764d/replay/replay.go#L223)):*
> ```Go
> 	for !done {
> 		select {
> 		case <-r.workloadExhausted:
> ```

can you add a comment here explaining that `r.workloadExhausted` does not get closed; it just gets an empty value sent to it, so this case will trigger at most once.
___
*[`replay/replay.go` line 373 at r7](https://reviewable.io/reviews/cockroachdb/pebble/2152#-NJfeu-_EXspaKoUQdke:-NJfeu-_EXspaKoUQdkf:bi4d3yb) ([raw file](https://github.com/cockroachdb/pebble/blob/3b107a1a7bcd923a189b7430cd487ba4db62764d/replay/replay.go#L373)):*
> ```Go
> 	var v *manifest.Version
> 	var previousVersion *manifest.Version
> 	var bve manifest.BulkVersionEdit
> ```

I forgot to set `bve.AddedByFileNum`. We should initialize it to `make(map[base.FileNum]*FileMetadata)`

This map will keep track of all the file metadata so that when a file is deleted, it can look up the deleted file's metadata from the map. i'm a little surprised our unit tests haven't caught this yet. 
___
*[`replay/replay.go` line 387 at r7](https://reviewable.io/reviews/cockroachdb/pebble/2152#-NJff2h00x5sdVDorKER:-NJff2h00x5sdVDorKES:b-gr0d1n) ([raw file](https://github.com/cockroachdb/pebble/blob/3b107a1a7bcd923a189b7430cd487ba4db62764d/replay/replay.go#L387)):*
> ```Go
> 			r.Opts.FlushSplitBytes,
> 			r.Opts.Experimental.ReadCompactionRate)
> 		bve = manifest.BulkVersionEdit{}
> ```

and then we should `AddedByFileNum` here, eg:
```
bve = manifest.BulkVersionEdit{AddedByFileNum: bve.AddedByFileNum}
```

**Review by coolcom200 — COMMENTED** [review]
> Reviewed 1 of 8 files at r1, 1 of 11 files at r3, 1 of 11 files at r6, 10 of 10 files at r7, 1 of 4 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2152)* status: 11 of 14 files reviewed, 10 unresolved discussions (waiting on @jbowens and @jbowens-alt)

___
*[`internal/datatest/datatest.go` line 131 at r7](https://reviewable.io/reviews/cockroachdb/pebble/2152#-NJfU9-L9nRs72EID8KH:-NJfiUs33x_c2v7GOfrX:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/3b107a1a7bcd923a189b7430cd487ba4db62764d/internal/datatest/datatest.go#L131)):*
<details><summary><i>Previously, jbowens-alt (Jackson Owens (v2)) wrote…</i></summary><blockquote>

let's copy over `Options.AddEventListener` from [here](https://github.com/cockroachdb/pebble/pull/2161/files#diff-4eec45b6a922746411c0f8aea183e30f77af1b0a5bea1688eaf343a5f9c23703) and use that
</blockquote></details>

Done.
___
*[`replay/replay.go` line 106 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2152#-NIDPs2A8wXOf84_b098:-NIEl3Fm0XJdty6SVq3F:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/b619cd9abcfe9b2cb7ac14d848f38018650d0e71/replay/replay.go#L106)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

can you add a comment explaining the meaning of 'workload exhausted' (we've applied all of the workload's modifications but might not have finished compacting). And also that only a single item is sent to the channel when exhausted, so it should only be read from the `refreshMetrics` goroutine
</blockquote></details>

Done.
___
*[`replay/replay.go` line 325 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2152#-NIDRKiQ-EioJNH-jmWI:-NIEYAHU9GjDVl-jQzXH:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/b619cd9abcfe9b2cb7ac14d848f38018650d0e71/replay/replay.go#L325)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

mind leaving a TODO to sum all the paced durations to report as a statistic at the end?
</blockquote></details>

Done.
___
*[`replay/replay.go` line 455 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2152#-NIDRf3P56pLxvril0e-:-NIEjM4n74EZbF29yCvo:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/b619cd9abcfe9b2cb7ac14d848f38018650d0e71/replay/replay.go#L455)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

s.v should be nil, because it's a local variable, no? I think we need save the current version to a global variable with a scope outside this step's iteration
</blockquote></details>

Done.
___
*[`replay/replay.go` line 108 at r7](https://reviewable.io/reviews/cockroachdb/pebble/2152#-NJfWLAL-sDmDCxYb_mq:-NJfj16N3qjfgsfLuY6x:b-ka6s57) ([raw file](https://github.com/cockroachdb/pebble/blob/3b107a1a7bcd923a189b7430cd487ba4db62764d/replay/replay.go#L108)):*
<details><summary><i>Previously, jbowens-alt (Jackson Owens (v2)) wrote…</i></summary><blockquote>

this comment needs to be updated now that this channel is no longer closed; it's sent to when the workload is finished. can you add that workloadExhausted is a buffered channel of size 1, so only `refreshMetrics` can read from it.
</blockquote></details>

The comment I think is still accurate as the channel is closed. I have changed the channel to not be a initialized as buffered channel. 
___
*[`replay/replay.go` line 188 at r7](https://reviewable.io/reviews/cockroachdb/pebble/2152#-NJfVk9r2RgF8HE-0FN8:-NJfjhKD1JppzaJ3eDxo:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/3b107a1a7bcd923a189b7430cd487ba4db62764d/replay/replay.go#L188)):*
<details><summary><i>Previously, jbowens-alt (Jackson Owens (v2)) wrote…</i></summary><blockquote>

we can use the new `Options.AddEventListener` here too
</blockquote></details>

Done.
___
*[`replay/replay.go` line 223 at r7](https://reviewable.io/reviews/cockroachdb/pebble/2152#-NJfW0EI8sXjvr2gA2el:-NJfjim829MshtPPlPeS:bc2m16d) ([raw file](https://github.com/cockroachdb/pebble/blob/3b107a1a7bcd923a189b7430cd487ba4db62764d/replay/replay.go#L223)):*
<details><summary><i>Previously, jbowens-alt (Jackson Owens (v2)) wrote…</i></summary><blockquote>

can you add a comment here explaining that `r.workloadExhausted` does not get closed; it just gets an empty value sent to it, so this case will trigger at most once.
</blockquote></details>

This channel does get closed. 
___
*[`replay/replay.go` line 373 at r7](https://reviewable.io/reviews/cockroachdb/pebble/2152#-NJfeu-_EXspaKoUQdke:-NJflG-z8nqZeZaMh6Qn:b-8zugrg) ([raw file](https://github.com/cockroachdb/pebble/blob/3b107a1a7bcd923a189b7430cd487ba4db62764d/replay/replay.go#L373)):*
I think we already have the metadata saved above  (line 367) I think we just don't use it
> metas := make(map[base.FileNum]*manifest.FileMetadata)

I think that we can just do this. Please correct me if I misunderstood. 
```diff
@@ -384,7 +378,7 @@ func (r *Runner) prepareWorkloadSteps(ctx context.Context) error {
                        r.Opts.Comparer.FormatKey,
                        r.Opts.FlushSplitBytes,
                        r.Opts.Experimental.ReadCompactionRate)
-               bve = manifest.BulkVersionEdit{}
+               bve = manifest.BulkVersionEdit{AddedByFileNum: metas}
                return v, err
        }
```
___
*[`replay/replay.go` line 387 at r7](https://reviewable.io/reviews/cockroachdb/pebble/2152#-NJff2h00x5sdVDorKER:-NJfmY890WW4QoIuwzzc:bwoykjg) ([raw file](https://github.com/cockroachdb/pebble/blob/3b107a1a7bcd923a189b7430cd487ba4db62764d/replay/replay.go#L387)):*
<details><summary><i>Previously, jbowens-alt (Jackson Owens (v2)) wrote…</i></summary><blockquote>

and then we should `AddedByFileNum` here, eg:
```
bve = manifest.BulkVersionEdit{AddedByFileNum: bve.AddedByFileNum}
```
</blockquote></details>

See above comment.

**Review by jbowens-alt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2152)* status: 11 of 14 files reviewed, 8 unresolved discussions (waiting on @coolcom200 and @jbowens)

___
*[`replay/replay.go` line 108 at r7](https://reviewable.io/reviews/cockroachdb/pebble/2152#-NJfWLAL-sDmDCxYb_mq:-NJfrmZe6pCYK1LlVTMq:b-pw60m4) ([raw file](https://github.com/cockroachdb/pebble/blob/3b107a1a7bcd923a189b7430cd487ba4db62764d/replay/replay.go#L108)):*
<details><summary><i>Previously, coolcom200 (Leon Fattakhov) wrote…</i></summary><blockquote>

The comment I think is still accurate as the channel is closed. I have changed the channel to not be a initialized as buffered channel. 
</blockquote></details>

Hrm, I'm confused. I thought we deliberately used a buffered channel and a send so that the select in `refreshMetrics` doesn't always fall into the `r.workloadExhausted` case once the workload is complete.
___
*[`replay/replay.go` line 373 at r7](https://reviewable.io/reviews/cockroachdb/pebble/2152#-NJfeu-_EXspaKoUQdke:-NJfsgAtE984FM2L5moj:b-ddmdh3) ([raw file](https://github.com/cockroachdb/pebble/blob/3b107a1a7bcd923a189b7430cd487ba4db62764d/replay/replay.go#L373)):*
<details><summary><i>Previously, coolcom200 (Leon Fattakhov) wrote…</i></summary><blockquote>

I think we already have the metadata saved above  (line 367) I think we just don't use it
> metas := make(map[base.FileNum]*manifest.FileMetadata)

I think that we can just do this. Please correct me if I misunderstood. 
```diff
@@ -384,7 +378,7 @@ func (r *Runner) prepareWorkloadSteps(ctx context.Context) error {
                        r.Opts.Comparer.FormatKey,
                        r.Opts.FlushSplitBytes,
                        r.Opts.Experimental.ReadCompactionRate)
-               bve = manifest.BulkVersionEdit{}
+               bve = manifest.BulkVersionEdit{AddedByFileNum: metas}
                return v, err
        }
```
</blockquote></details>

I forgot about `metas`—I don't think we need to manually accumulate them in `applyVE` then. `BulkVersionEdit.Accumulate` will already do that for us.

**Review by coolcom200 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2152)* status: 11 of 14 files reviewed, 8 unresolved discussions (waiting on @jbowens and @jbowens-alt)

___
*[`replay/replay.go` line 108 at r7](https://reviewable.io/reviews/cockroachdb/pebble/2152#-NJfWLAL-sDmDCxYb_mq:-NJpsLhM1TW3oKfHl82E:bc0kyvk) ([raw file](https://github.com/cockroachdb/pebble/blob/3b107a1a7bcd923a189b7430cd487ba4db62764d/replay/replay.go#L108)):*
<details><summary><i>Previously, jbowens-alt (Jackson Owens (v2)) wrote…</i></summary><blockquote>

Hrm, I'm confused. I thought we deliberately used a buffered channel and a send so that the select in `refreshMetrics` doesn't always fall into the `r.workloadExhausted` case once the workload is complete.
</blockquote></details>

Updated comment and changed it to send a single message a message.
___
*[`replay/replay.go` line 373 at r7](https://reviewable.io/reviews/cockroachdb/pebble/2152#-NJfeu-_EXspaKoUQdke:-NJpsVQcAehc4QCfGHIA:b-l8lif7) ([raw file](https://github.com/cockroachdb/pebble/blob/3b107a1a7bcd923a189b7430cd487ba4db62764d/replay/replay.go#L373)):*
<details><summary><i>Previously, jbowens-alt (Jackson Owens (v2)) wrote…</i></summary><blockquote>

I forgot about `metas`—I don't think we need to manually accumulate them in `applyVE` then. `BulkVersionEdit.Accumulate` will already do that for us.
</blockquote></details>

Sounds good. Added an issue to make a test for this https://github.com/cockroachdb/pebble/issues/2200
___
*[`replay/testdata/corpus/findManifestStart` line 26 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2152#-NIDSJKvD2qkcyFIRBKH:-NJpvFFAEWQGIOQ8eZT4:b-dukadb) ([raw file](https://github.com/cockroachdb/pebble/blob/b619cd9abcfe9b2cb7ac14d848f38018650d0e71/replay/testdata/corpus/findManifestStart#L26)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

we generally try to have binary data be generated by the test itself, so it's programmatically able to be reconstructed. it also helps with understanding the test itself
</blockquote></details>

Added an issue to change this test: https://github.com/cockroachdb/pebble/issues/2201

**Review by jbowens — APPROVED** [review]
:lgtm: modulo the nit and the use of atomics for the compaction start count

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2152#-:-NJunsfk8H-C4BXuO-HP:b-9d8sbp)* status: 11 of 14 files reviewed, 6 unresolved discussions (waiting on @coolcom200 and @jbowens-alt)

___
*[`replay/replay.go` line 255 at r9](https://reviewable.io/reviews/cockroachdb/pebble/2152#-NJumwYBBdWRYDllOHJ1:-NJumwYBBdWRYDllOHJ2:brw3kto) ([raw file](https://github.com/cockroachdb/pebble/blob/b64a6d9dbe56640116108d37f2107f9b2601e3d0/replay/replay.go#L255)):*
> ```Go
> 
> func (r *Runner) stopCompactionNotifier() {
> 	// Close the channel which will cause the compactionNotified to exit
> ```

`compactionNotified goroutine`

**Review by coolcom200 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2152)* status: 11 of 14 files reviewed, 6 unresolved discussions (waiting on @jbowens and @jbowens-alt)

___
*[`replay/replay.go` line 129 at r9](https://reviewable.io/reviews/cockroachdb/pebble/2152#-NJukDAx5Uj4ozq4I2Fx:-NJv3YzX-KuGVdO8w8Qy:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/b64a6d9dbe56640116108d37f2107f9b2601e3d0/replay/replay.go#L129)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

let's use atomics instead of a mutex for `compactionStartCount`
</blockquote></details>

Done.
___
*[`replay/replay.go` line 255 at r9](https://reviewable.io/reviews/cockroachdb/pebble/2152#-NJumwYBBdWRYDllOHJ1:-NJv-vwl3D004Mfdi9-r:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/b64a6d9dbe56640116108d37f2107f9b2601e3d0/replay/replay.go#L255)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

`compactionNotified goroutine`
</blockquote></details>

Done.

**Comment by coolcom200** [comment]
TFTRs!!!

**Pull request merged**
