### PR TITLE
db: fix TestVirtualReadsWiring flake

### LINKED ISSUE #3364: db: lower bound violation in pebble tests
```
panic: lower bound f#12,21 violated by key f#14,21; wraps *keyspan.assertIter

goroutine 78074 [running]:
github.com/cockroachdb/pebble/internal/keyspan.(*assertIter).panicf(0xc00097dc20, {0x10f22786e?, 0x1?}, {0xc0008ac648?, 0x1?, 0x1?})
	/Users/runner/work/pebble/pebble/internal/keyspan/assert_iter.go:82 +0xa8
github.com/cockroachdb/pebble/internal/keyspan.(*assertIter).check(0xc00097dc20, 0xc0008074b0)
	/Users/runner/work/pebble/pebble/internal/keyspan/assert_iter.go:99 +0x1d4
github.com/cockroachdb/pebble/internal/keyspan.(*assertIter).First(0xc00097dc20)
	/Users/runner/work/pebble/pebble/internal/keyspan/assert_iter.go:134 +0x45
github.com/cockroachdb/pebble/internal/keyspan.(*filteringIter).First(0xc000807500)
	/Users/runner/work/pebble/pebble/internal/keyspan/filter.go:82 +0x23
github.com/cockroachdb/pebble/internal/keyspan.(*assertIter).First(0xc00097dcb0)
	/Users/runner/work/pebble/pebble/internal/keyspan/assert_iter.go:133 +0x23
github.com/cockroachdb/pebble/internal/keyspan.(*DefragmentingIter).First(0xc0002acb40)
	/Users/runner/work/pebble/pebble/internal/keyspan/defragment.go:289 +0x24
github.com/cockroachdb/pebble/internal/keyspan/keyspanimpl.(*MergingIter).First(0xc0003b9508)
	/Users/runner/work/pebble/pebble/internal/keyspan/keyspanimpl/merging_iter.go:615 +0x6a
github.com/cockroachdb/pebble.(*DB).loadTableRangeDelStats(0xc0008e4008, {0x10f5220b8, 0xc0009043c0}, 0xc0008f4c08, 0x6, 0xc0002856c0, 0xc0008acc08)
	/Users/runner/work/pebble/pebble/table_stats.go:375 +0xfb
github.com/cockroachdb/pebble.(*DB).loadTableStats.func1({0x10f5220b8, 0xc0009043c0})
	/Users/runner/work/pebble/pebble/table_stats.go:316 +0xf9
github.com/cockroachdb/pebble.(*tableCacheContainer).withCommonReader(0xc000072188?, 0xc0002856c0, 0xc0008acc50)
	/Users/runner/work/pebble/pebble/table_cache.go:295 +0xf3
github.com/cockroachdb/pebble.(*DB).loadTableStats(0x5?, 0x0?, 0x0?, 0x0?)
	/Users/runner/work/pebble/pebble/table_stats.go:305 +0xd4
github.com/cockroachdb/pebble.(*DB).scanReadStateTableStats(0xc0008e4008, 0xc0000b4d20, {0xc00019f490, 0x0, 0x32})
	/Users/runner/work/pebble/pebble/table_stats.go:281 +0x925
github.com/cockroachdb/pebble.(*DB).collectTableStats(0xc0008e4008)
	/Users/runner/work/pebble/pebble/table_stats.go:113 +0x236
created by github.com/cockroachdb/pebble.(*DB).maybeCollectTableStatsLocked in goroutine 78089
FAIL	github.com/cockroachdb/pebble	44.976s
```

https://github.com/cockroachdb/pebble/actions/runs/8102029032/job/22143601288?pr=3363

### PR DESCRIPTION
**Pull request by RaduBerinde**
Fixes #3364

### CODE REVIEW

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3367)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @RaduBerinde)

___
*[`table_cache_test.go` line 313 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3367#-NruOsZ48DOUVVoZy_Mg:-NruOsZ48DOUVVoZy_Mh:b-86t1o5) ([raw file](https://github.com/cockroachdb/pebble/blob/52a70a9357e572216b51dbe2d3d53249c45a0c90/table_cache_test.go#L313)):*
> ```Go
> 		SmallestSeqNum:   parentFile.SmallestSeqNum,
> 		LargestSeqNum:    parentFile.LargestSeqNum,
> 		Smallest:         base.MakeInternalKey([]byte{'d'}, parentFile.Smallest.SeqNum()+100, InternalKeyKindRangeDelete),
> ```

I am having trouble understanding this test and the failure `
panic: lower bound f#12,21 violated by key f#14,21; wraps *keyspan.assertIter
`

My current understanding:
- we are writing 7 keys in the batch so the range of seqnums should be `[parentFile.Smallest.SeqNum(), parentFile.Smallest.SeqNum()+7)`. To simplify, say the smallest seqnum was 1.
- The `d` point is the second thing written to the batch so it should have seqnum 2. The RANGEDEL containing `d` is the third thing written to the batch so has seqnum 3. So both are included in this sst when `SmallestPointKey: base.MakeInternalKey([]byte{'d'}, parentFile.Smallest.SeqNum()+100, InternalKeyKindRangeDelete)`? Why did +2 not work? It would be d@3, so [c, e)@3 would be cleanly split into [c,d)@3 and [d,e)@3 for the virtualization.

Some code comments would help.

**Comment by RaduBerinde** [comment]
*[`table_cache_test.go` line 313 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3367#-NruOsZ48DOUVVoZy_Mg:-NruRxKA-E50OnGShxgn:b-2c77va) ([raw file](https://github.com/cockroachdb/pebble/blob/52a70a9357e572216b51dbe2d3d53249c45a0c90/table_cache_test.go#L313)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I am having trouble understanding this test and the failure `
panic: lower bound f#12,21 violated by key f#14,21; wraps *keyspan.assertIter
`

My current understanding:
- we are writing 7 keys in the batch so the range of seqnums should be `[parentFile.Smallest.SeqNum(), parentFile.Smallest.SeqNum()+7)`. To simplify, say the smallest seqnum was 1.
- The `d` point is the second thing written to the batch so it should have seqnum 2. The RANGEDEL containing `d` is the third thing written to the batch so has seqnum 3. So both are included in this sst when `SmallestPointKey: base.MakeInternalKey([]byte{'d'}, parentFile.Smallest.SeqNum()+100, InternalKeyKindRangeDelete)`? Why did +2 not work? It would be d@3, so [c, e)@3 would be cleanly split into [c,d)@3 and [d,e)@3 for the virtualization.

Some code comments would help.
</blockquote></details>

I can't say I understand this test very much either..  

The failure reproduces rarely, and only when there are a lot of things running in parallel.

I made a change to copy the sst, this is what it looks like when the test passes:
```
a#10,SET [61]
c-e#12,RANGEDEL
f#13,SET [66]
z#16,SET [7a]
[f-j):
  #14,RANGEKEYSET:  [63]
[j-k):
  #15,RANGEKEYUNSET: 
```

It seems to look exactly the same even when it fails:
```
a#10,SET [61]
c-e#12,RANGEDEL
f#13,SET [66]
z#16,SET [7a]
[f-j):
  #14,RANGEKEYSET:  [63]
[j-k):
  #15,RANGEKEYUNSET: 
```

I'll investigate more.

**Comment by RaduBerinde** [comment]
*[`table_cache_test.go` line 313 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3367#-NruOsZ48DOUVVoZy_Mg:-NruZUYm-gpJRdCiO4EU:bcm0auw) ([raw file](https://github.com/cockroachdb/pebble/blob/52a70a9357e572216b51dbe2d3d53249c45a0c90/table_cache_test.go#L313)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I can't say I understand this test very much either..  

The failure reproduces rarely, and only when there are a lot of things running in parallel.

I made a change to copy the sst, this is what it looks like when the test passes:
```
a#10,SET [61]
c-e#12,RANGEDEL
f#13,SET [66]
z#16,SET [7a]
[f-j):
  #14,RANGEKEYSET:  [63]
[j-k):
  #15,RANGEKEYUNSET: 
```

It seems to look exactly the same even when it fails:
```
a#10,SET [61]
c-e#12,RANGEDEL
f#13,SET [66]
z#16,SET [7a]
[f-j):
  #14,RANGEKEYSET:  [63]
[j-k):
  #15,RANGEKEYUNSET: 
```

I'll investigate more.
</blockquote></details>

Oh.. The problem is with the range key. We set `f#12` as the lower bound. Nothing in the test causes us to read it, but a background `collectTableStats` does.

**Comment by RaduBerinde** [comment]
*[`table_cache_test.go` line 313 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3367#-NruOsZ48DOUVVoZy_Mg:-NrubKvwDfQJoMuxT0Zw:b-31vuav) ([raw file](https://github.com/cockroachdb/pebble/blob/52a70a9357e572216b51dbe2d3d53249c45a0c90/table_cache_test.go#L313)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Oh.. The problem is with the range key. We set `f#12` as the lower bound. Nothing in the test causes us to read it, but a background `collectTableStats` does.
</blockquote></details>

Updated. This should make a lot more sense now. I will also separately try to update `InternalKey.String()` to show the kind as a string, it would have helped to see that instead of `,21`.

**Review by sumeerbhola — APPROVED** [review]
:lgtm_strong: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3367#-:-NrvpOOFDVjl_K4E3iLH:b-uwkowd)* status: 0 of 1 files reviewed, 1 unresolved discussion

**Comment by RaduBerinde** [comment]
TFTR!

**Pull request merged**
