### PR TITLE
sstable: fix race in sstable when parallelism is enabled

### PR DESCRIPTION
**Pull request by bananabrick**
The buffer used to compute separator keys cannot be stored in the indexBlockBuf,
because the same indexBlockBuf can be accessed by the Writer client and the
writeQueue. Instead, we store it in the dataBlockBuf, since a dataBlockBuf is
guaranteed to be only accessed by either the Writer client or the writeQueue.

### CODE REVIEW

**Review by nicktrav — COMMENTED** [review]
Is this something we can test?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1542#-:-Mx0erlt9zZ-h-9El3Ak:b-r4ydy6)* status: 0 of 1 files reviewed, all discussions resolved

**Review by bananabrick — COMMENTED** [review]
I came across this while manually running some benchmarks on Friday with the race detector on. The race goes away as expected, when we make sure that the buffer is exclusively only accessed by one goroutine at any given time.

If I enable parallelism, then a bunch of unit tests which run with the race detector on will fail. I didn't catch this, because when I merged this, we didn't have the capability to turn on parallelism in the Writer.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1542#-:-Mx0fxMPA1hsOkTPGr2o:bx75sca)* status: 0 of 1 files reviewed, all discussions resolved

**Review by bananabrick — COMMENTED** [review]
I'm going to enable Writer parallelism in the metamorphic tests in my next pr, and that would also fail when run under `-race` with Writer parallelism enabled.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1542#-:-Mx0h5sj6fLQyeTOnIAW:b-4s2j9g)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @nicktrav)

**Comment by itsbilal** [comment]
In addition to the metamorphic tests, it also makes sense to copy some of the regular Writer tests and run them with parallelization enabled. That would add a more direct point of test failure / catchment of future regressions than in having to dig into a metamorphic test failure.

**Review by bananabrick — COMMENTED** [review]
Yea, I plan to do that. But not in this pr.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1542#-:-Mx0tuADEoKUAhEh_MNl:b-rzxk0c)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @nicktrav)

**Review by itsbilal — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1542#-:-Mx0wBcn-x7IgKkRC5qo:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nicktrav)

**Comment by bananabrick** [comment]
TFTR

**Pull request merged**
