### PR TITLE
stable: reenable fragmentBlockIter pool

### LINKED ISSUE #3678: TestMetaCrossVersion and TestMeta with no invariants failure
https://github.com/cockroachdb/pebble/actions/runs/9601942213/job/26481618161?pr=3677

```
        -iter20.SeekLT("dlrsqhqtkugm@10", "") // [true,"cearmwwagb@15","ojtyravuafvuep",["cearmwwagb","gsohc")=>{"@13"="jkzofmypok"}*] <nil> #1700
        +iter20.SeekLT("dlrsqhqtkugm@10", "") // [true,"cearmwwagb@3","dwyydffdbimw",["cearmwwagb","gsohc")=>{"@13"="jkzofmypok"}*] <nil> #1700
```

```
SEED=1718905245421630211 FACTOR=10 ./scripts/run-crossversion-meta.sh crl-release-24.1 HEAD
```

### PR DESCRIPTION
**Pull request by RaduBerinde**
Fixes #3678

I ran the meta test a bunch on this, I will run it some more before merging.

### CODE REVIEW

**Review by jbowens — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3697#-:-O0Gp0qq5lnoDAYqtVmX:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3697)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @RaduBerinde)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3697#-O0Gp91QD2wm3U95dMVR):*
nit: "sstable"

**Comment by RaduBerinde** [comment]
```
4870 runs so far, 0 failures, over 12h49m15s
```

**Review by RaduBerinde — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3697#-:-O0JylB0AUC4sir_douu:b-814g8k)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @jbowens)

**Pull request merged**
