### PR TITLE
db: use datadriven convenience utilities where beneficial 

### PR DESCRIPTION
**Pull request by jbowens**
**go.mod: update cockroachdb/datadriven dependency**

**db: use datadriven convenience utilities where beneficial**

Use convenience utilities for scanning command arguments where beneficial.

### CODE REVIEW

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2449)* status: 0 of 13 files reviewed, 1 unresolved discussion

___
*[`batch_test.go` line 895 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2449#-NSwZpM_AIp16sTlLGgD:-NSwZpM_AIp16sTlLGgE:bof9oxf) ([raw file](https://github.com/cockroachdb/pebble/blob/60cfeb46143b4c93c72c7f345d1c0e92c2326773/batch_test.go#L895)):*
> ```Go
> 					defer fragmentIter.Close()
> 				default:
> 					return fmt.Sprintf("%s unknown argument %s", td.Cmd, td.CmdArgs[0])
> ```

I'm somewhat regretting not making an interface that allows easily checking for unknown/unused arguments. Eg, maybe something like:

```
td.ScanAll(t,
    datadriven.Required("kind", &kind),
    datadriven.Optional("seq", &seq),
    datadriven.Exists("range-del", &rangeDel),
    datadriven.Unknown(func(unknown datadriven.CmdArg) error {
       // custom handling of fields not named above
   }))
```

**Review by bananabrick — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2449#-:-NTRmJWNEVMo-lqHXflK:bg7igkv)* status: 0 of 13 files reviewed, 1 unresolved discussion

**Comment by jbowens** [comment]
TFTR! — @bananabrick mind hitting the github approval button?

**Review by nicktrav — APPROVED** [review]
Proxy-LGTM ✅

**Pull request merged**
