### PR TITLE
crossversion: parallelize metamorphic test runs

### LINKED ISSUE #2079: crossversion: parallelize metamorphic runs
The crossversion metamorphic tests are relatively slow. Each of the subruns with separate initial states are perfectly parallelizable. Running the `--factor` subruns in parallel can improve the utilization of the host machine and reduce the wall time of the test, improving coverage.

### PR DESCRIPTION
**Pull request by jbowens**
Run the metamorphic test runs on the individual initial states in parallel, with a maximum parallelism set through a new `--parallelism` command-line flag. This can reduce the wall-time for a run of the crossversion metamorphic test, and improve utilization of the host machine. Default to using half the available CPUs to account for the metamorphic tests' own parallelism when running with `--max-threads` > 1.

Close #2079.

### CODE REVIEW

**Review by nicktrav — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2080)* status: all files reviewed, 1 unresolved discussion (waiting on @jbowens)

___
*[`internal/metamorphic/crossversion/crossversion_test.go` line 201 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2080#-NFinOT53TcFZiD1kKH4:-NFinOT53TcFZiD1kKH5:b-2zpakj) ([raw file](https://github.com/cockroachdb/pebble/blob/dc914d59e174339e78a85b4b825150ca75cfc1ad/internal/metamorphic/crossversion/crossversion_test.go#L201)):*
> ```Go
> ) (histories []string, nextInitialStates []initialState, err error) {
> 	var mu sync.Mutex
> 	sem := make(chan struct{}, maxParallelism)
> ```

Can't `maxParallelism` be `0` (i.e. no parallelism) in the case where max procs is `1` (or if configured to `0` or `1` via the flag)? That would make this channel unbuffered. Wouldn't the channel send below hang in that case?

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2080)* status: all files reviewed, 1 unresolved discussion (waiting on @nicktrav)

___
*[`internal/metamorphic/crossversion/crossversion_test.go` line 201 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2080#-NFinOT53TcFZiD1kKH4:-NFjNVcD53t2K-dwd2UZ:bwxoolb) ([raw file](https://github.com/cockroachdb/pebble/blob/dc914d59e174339e78a85b4b825150ca75cfc1ad/internal/metamorphic/crossversion/crossversion_test.go#L201)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

Can't `maxParallelism` be `0` (i.e. no parallelism) in the case where max procs is `1` (or if configured to `0` or `1` via the flag)? That would make this channel unbuffered. Wouldn't the channel send below hang in that case?
</blockquote></details>

Hmm, I think "parallelism" usually means the number of concurrent operations to allow, which must always a positive integer, but I see how that can be confusing. I'm going to look at moving this parallelism down a level into the metamorphic test, and I'll consider a different name for the CLI flag.

**Review by jbowens — COMMENTED** [review]
Updated to use `t.Parallel` for the parallelism. I originally thought this could be superseded by #2093, but since some of the individual options runs have dramatically longer run times, I think there's still benefit to parallelizing within the crossversion metamorphic tests too.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2080#-:-NG2bsKv0M5i5Oc6BZQh:bd3fj0x)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @nicktrav)

**Review by nicktrav — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2080#-:-NG2cY6xCL29ly-RPHcy:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jbowens)

**Comment by jbowens** [comment]
TFTR!

**Pull request merged**
