### PR TITLE
colblk: add index block writer, reader, iterator

### PR DESCRIPTION
**Pull request by jbowens**
Add writer, reader and iterator types for index blocks.

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]
:lgtm_strong: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3856#-:-O4MXIPN7GYs4B3VzSqr:b-uwkowd)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @itsbilal and @jbowens)

___
*[`sstable/colblk/index_block.go` line 23 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3856#-O4MUSeD4QxqycFprA3Q:-O4MUSeD4QxqycFprA3R:b-z9qv3t) ([raw file](https://github.com/cockroachdb/pebble/blob/7d5a247d8233967f7582c748cf79196e090c60d4/sstable/colblk/index_block.go#L23)):*
> ```Go
> // consists of three primary columns:
> //   - Separators: a user key that is ≥ the largest user key in the corresponding
> //     entry.
> ```

[nit] and < than the smallest key in the next entry ?
___
*[`sstable/colblk/index_block.go` line 24 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3856#-O4MUb-eAFNKFzuKQ-2D:-O4MUb-eAFNKFzuKQ-2E:bigu79f) ([raw file](https://github.com/cockroachdb/pebble/blob/7d5a247d8233967f7582c748cf79196e090c60d4/sstable/colblk/index_block.go#L24)):*
> ```Go
> //   - Separators: a user key that is ≥ the largest user key in the corresponding
> //     entry.
> //   - BlockEndOffset: the offset of the end of the corresponding block.
> ```

[nit] BlockEndOffsets (for consistency)?
___
*[`sstable/colblk/index_block.go` line 30 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3856#-O4MUuX19nRtyko5YC2P:-O4MUuX21LClwZlAhJEm:b-a58a7j) ([raw file](https://github.com/cockroachdb/pebble/blob/7d5a247d8233967f7582c748cf79196e090c60d4/sstable/colblk/index_block.go#L30)):*
> ```Go
> // iterators infer the start offset of the block by looking at the end offset of
> // the previous block. This is possible because data blocks are written
> // sequentially without any other interleaved blocks between first-level index
> ```

Do we want to lock ourselves into this constraint? There's an argument for not keeping all index blocks in memory when building ssts. Are the savings here significant? It's just 2 bytes per ~32KB data block no?
___
*[`sstable/colblk/index_block.go` line 244 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3856#-O4MX9Su88rjBFOjzrlA:-O4MX9Su88rjBFOjzrlB:b-hhqgzq) ([raw file](https://github.com/cockroachdb/pebble/blob/7d5a247d8233967f7582c748cf79196e090c60d4/sstable/colblk/index_block.go#L244)):*
> ```Go
> }
> 
> // SeekGE seeks the index iterator to the block entry with a separator key
> ```

[nit] the first block entry

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3856)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @itsbilal, @jbowens, and @RaduBerinde)

___
*[`sstable/colblk/index_block.go` line 30 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3856#-O4MUuX19nRtyko5YC2P:-O4Q3k8iCL-4qLkExIf7:bdg6ios) ([raw file](https://github.com/cockroachdb/pebble/blob/7d5a247d8233967f7582c748cf79196e090c60d4/sstable/colblk/index_block.go#L30)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Do we want to lock ourselves into this constraint? There's an argument for not keeping all index blocks in memory when building ssts. Are the savings here significant? It's just 2 bytes per ~32KB data block no?
</blockquote></details>

Do we need to store the lengths at all? (Is this what your question is Radu?) I seem to recall that RocksDB created a new index block format which had an alternate encoding for block handles which computed the length of a block from the offset of the next block. Perhaps I'm misremembering, but that idea should work here. Isn't it true that `BlockLength(i) = BlockOffset(i+1) - BlockOffset(i)`?

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3856)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @itsbilal, @petermattis, and @RaduBerinde)

___
*[`sstable/colblk/index_block.go` line 23 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3856#-O4MUSeD4QxqycFprA3Q:-O4QBYeD6jksOA-88M4x:buyvwt8) ([raw file](https://github.com/cockroachdb/pebble/blob/7d5a247d8233967f7582c748cf79196e090c60d4/sstable/colblk/index_block.go#L23)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] and < than the smallest key in the next entry ?
</blockquote></details>

it's not guaranteed, because with snapshots we can have many versions of the same user key at different sequence numbers, which can cause adjacent blocks to have the same separator
___
*[`sstable/colblk/index_block.go` line 24 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3856#-O4MUb-eAFNKFzuKQ-2D:-O4QBXeU7t09R7DQJtWk:bb6un1j) ([raw file](https://github.com/cockroachdb/pebble/blob/7d5a247d8233967f7582c748cf79196e090c60d4/sstable/colblk/index_block.go#L24)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] BlockEndOffsets (for consistency)?
</blockquote></details>

Done
___
*[`sstable/colblk/index_block.go` line 30 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3856#-O4MUuX19nRtyko5YC2P:-O4QBtfKBjVv-cJZcARG:bdqhife) ([raw file](https://github.com/cockroachdb/pebble/blob/7d5a247d8233967f7582c748cf79196e090c60d4/sstable/colblk/index_block.go#L30)):*
> By the way, can't value blocks be interspersed between data blocks?

Naw, today they're all buffered and then written at the tail of the sstable, with the intention of preserving locality of key data (eg, for readahead).

> Do we need to store the lengths at all? (Is this what your question is Radu?) I seem to recall that RocksDB created a new index block format which had an alternate encoding for block handles which computed the length of a block from the offset of the next block. Perhaps I'm misremembering, but that idea should work here. Isn't it true that `BlockLength(i) = BlockOffset(i+1) - BlockOffset(i)`?

@petermattis the original commit (7d5a247d8233967f7582c748cf79196e090c60d4) here implemented what you described, but it was a little cumbersome because second-level indexes don't have that guarantee `BlockLength(i) = BlockOffset(i+1) - BlockOffset(i)`, and first-level index blocks other than the first also need to encode an initial start offset.

Like @RaduBerinde mentioned, our uint encoding does ensure that in the common case of blocks all around ~32KB, the lengths column will be just 2-bytes per block
___
*[`sstable/colblk/index_block.go` line 244 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3856#-O4MX9Su88rjBFOjzrlA:-O4QBX5QE8Ru6YqR7Z9J:bb6un1j) ([raw file](https://github.com/cockroachdb/pebble/blob/7d5a247d8233967f7582c748cf79196e090c60d4/sstable/colblk/index_block.go#L244)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] the first block entry
</blockquote></details>

Done

**Comment by RaduBerinde** [comment]
*[`sstable/colblk/index_block.go` line 23 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3856#-O4MUSeD4QxqycFprA3Q:-O4QFtiH6sq0XxRAXh5c:b963jyf) ([raw file](https://github.com/cockroachdb/pebble/blob/7d5a247d8233967f7582c748cf79196e090c60d4/sstable/colblk/index_block.go#L23)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

it's not guaranteed, because with snapshots we can have many versions of the same user key at different sequence numbers, which can cause adjacent blocks to have the same separator
</blockquote></details>

then let's say "and <= the smallest key in the next" and add the explanation above for the equality case.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3856)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @itsbilal, @jbowens, and @RaduBerinde)

___
*[`sstable/colblk/index_block.go` line 30 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3856#-O4MUuX19nRtyko5YC2P:-O4R7evjEco4oZlVQpVs:bma1p3k) ([raw file](https://github.com/cockroachdb/pebble/blob/7d5a247d8233967f7582c748cf79196e090c60d4/sstable/colblk/index_block.go#L30)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

> By the way, can't value blocks be interspersed between data blocks?

Naw, today they're all buffered and then written at the tail of the sstable, with the intention of preserving locality of key data (eg, for readahead).

> Do we need to store the lengths at all? (Is this what your question is Radu?) I seem to recall that RocksDB created a new index block format which had an alternate encoding for block handles which computed the length of a block from the offset of the next block. Perhaps I'm misremembering, but that idea should work here. Isn't it true that `BlockLength(i) = BlockOffset(i+1) - BlockOffset(i)`?

@petermattis the original commit (7d5a247d8233967f7582c748cf79196e090c60d4) here implemented what you described, but it was a little cumbersome because second-level indexes don't have that guarantee `BlockLength(i) = BlockOffset(i+1) - BlockOffset(i)`, and first-level index blocks other than the first also need to encode an initial start offset.

Like @RaduBerinde mentioned, our uint encoding does ensure that in the common case of blocks all around ~32KB, the lengths column will be just 2-bytes per block
</blockquote></details>

Got it. Thanks for the context. Carry on.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3856)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @itsbilal and @jbowens)

___
*[`sstable/colblk/index_block.go` line 32 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3856#-O4RDitq02mEstpuAOQk:-O4RDitq02mEstpuAOQl:b-sfn1f2) ([raw file](https://github.com/cockroachdb/pebble/blob/7d5a247d8233967f7582c748cf79196e090c60d4/sstable/colblk/index_block.go#L32)):*
> ```Go
> // sequentially without any other interleaved blocks between first-level index
> // blocks.
> //
> ```

Will we add a column for block props here?

**Review by jbowens — COMMENTED** [review]
Updated so that the `colblk.IndexBlockIter` satisfies the new `block.IndexBlockIterator` constraint

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3856#-:-O4vUF2uErkN10hcefX2:bcagx7v)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @itsbilal and @RaduBerinde)

___
*[`sstable/colblk/index_block.go` line 23 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3856#-O4MUSeD4QxqycFprA3Q:-O4vUNQu6ADQ_FlCHv9S:bb6un1j) ([raw file](https://github.com/cockroachdb/pebble/blob/7d5a247d8233967f7582c748cf79196e090c60d4/sstable/colblk/index_block.go#L23)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

then let's say "and <= the smallest key in the next" and add the explanation above for the equality case.
</blockquote></details>

Done
___
*[`sstable/colblk/index_block.go` line 32 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3856#-O4RDitq02mEstpuAOQk:-O4vUOqFAGqEGNVKS61j:bb6un1j) ([raw file](https://github.com/cockroachdb/pebble/blob/7d5a247d8233967f7582c748cf79196e090c60d4/sstable/colblk/index_block.go#L32)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Will we add a column for block props here?
</blockquote></details>

Done

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3856#-:-O4wC8UkBTSMDXBfQn15:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @itsbilal and @jbowens)

**Comment by jbowens** [comment]
TFTR!

**Pull request merged**
