### PR TITLE
db: categorized stats for sstable iterators

### PR DESCRIPTION
**Pull request by sumeerbhola**
Informs #3014

### CODE REVIEW

**Review by jbowens — COMMENTED** [review]
Approach looks good to me. I also now think it could be reasonable to elevate the combined Category/QualityOfService into an explicit non-Context type that we explicitly propagate separately from the context, so that we can avoid the alloc in all cases and providing a value becomes a requirement of the type system. Using the context also LGTM.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3015#-:-Ni00ARG3ZOI2Pj_Z-2q:b-2tkeam)* status: 0 of 25 files reviewed, 2 unresolved discussions (waiting on @sumeerbhola)

___
*[`sstable/category_stats.go` line 116 at r2](https://reviewable.io/reviews/cockroachdb/pebble/3015#-Ni08Jco3IhpNVoA3273:-Ni04ZlIEau9HOZhxOgs:bdbjwoq) ([raw file](https://github.com/cockroachdb/pebble/blob/10445c1218ff9605e7492a2669995d70f9d157e0/sstable/category_stats.go#L116)):*
> ```Go
> 	v, ok := c.statsMap.Load(category)
> 	if !ok {
> 		c.mu.Lock()
> ```

probably excessive, but food for thought:

We could make `Category` a runtime-populated enum with clients calling `sstable.NewCategory(name string, qos QosLevel)` in package init funcs to assign values to the enum. We could then turn the `statsMap` into a slice to avoid the `sync.Map`, constructed at collector creation?

**Review by sumeerbhola — COMMENTED** [review]
TFTR!
I've added a test and this is ready for a proper review.

> I also now think it could be reasonable to elevate the combined Category/QualityOfService into an explicit non-Context type that we explicitly propagate separately from the context, so that we can avoid the alloc in all cases and providing a value becomes a requirement of the type system.

Done. I added to `IterOptions` since that doesn't change the method signature for anyone creating `pebble.Iterator`. That also resulted in minimal signature changes to the internal methods since they usually already have `IterOptions`. It does mean it is easier to forget to pass it.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3015#-:-Ni5PDUc1WU1h-WwScUI:b-c3w6us)* status: 0 of 32 files reviewed, 2 unresolved discussions (waiting on @jbowens)

___
*[`sstable/category_stats.go` line 116 at r2](https://reviewable.io/reviews/cockroachdb/pebble/3015#-Ni08Jco3IhpNVoA3273:-Ni5PwCO1n8OT4m-yiJf:b-52q33i) ([raw file](https://github.com/cockroachdb/pebble/blob/10445c1218ff9605e7492a2669995d70f9d157e0/sstable/category_stats.go#L116)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

probably excessive, but food for thought:

We could make `Category` a runtime-populated enum with clients calling `sstable.NewCategory(name string, qos QosLevel)` in package init funcs to assign values to the enum. We could then turn the `statsMap` into a slice to avoid the `sync.Map`, constructed at collector creation?
</blockquote></details>

I didn't do this, since it seems like an unnecessary complication. If we find that the map lookup is showing up in CPU profiles, we can revisit.

**Review by jbowens — APPROVED** [review]
:lgtm:

> Reviewed 2 of 25 files at r1, 30 of 30 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3015#-:-NiaTIkjDGEzMvnM0cCY:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @sumeerbhola)

___
*[`options.go` line 195 at r3](https://reviewable.io/reviews/cockroachdb/pebble/3015#-NiaOlp3Bky8kC47q13S:-NiaOlp4D-Ao7wEVljbc:b-5lt742) ([raw file](https://github.com/cockroachdb/pebble/blob/8c566397cd86914a12875fa24a05c0a24f4be779/options.go#L195)):*
> ```Go
> 	// existing iterator, such as OnlyReadGuaranteedDurable, UseL6Filters, if
> 	// the point iterator has already been initialized. Add comments regarding
> 	// which can be changed.
> ```

We have logic in SetOptions that forces the point iterator to be reconstructed if `OnlyReadGuaranteedDurable` or `UseL6Filters`. Alternatively we could add similar logic for `CategroyAndQoS`
___
*[`sstable/category_stats.go` line 135 at r3](https://reviewable.io/reviews/cockroachdb/pebble/3015#-NiaQiXr4LYXBj3CmcBo:-NiaQiXr4LYXBj3CmcBp:bjq8oko) ([raw file](https://github.com/cockroachdb/pebble/blob/8c566397cd86914a12875fa24a05c0a24f4be779/sstable/category_stats.go#L135)):*
> ```Go
> 		if len(s.Category) == 0 {
> 			// { makes it sort last.
> 			s.Category = "{unknown}"
> ```

will this be okay when converted into a timeseries name? I don't know what restrictions prometheus or the like have on series names, but in promql I know braces are used to filter on series metadata. Did a bit searching and it looks like the only non-alphanumeric characters that prometheus allows are underscores or colons: https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels I think we define metric names in Cockroach using hypens, so something must automatically translate? Anyways maybe underscores or colons will play nicer.
___
*[`sstable/reader_iter_single_lvl.go` line 60 at r3](https://reviewable.io/reviews/cockroachdb/pebble/3015#-NiaSt0q-YOWCdfkYjp3:-NiaSt0q-YOWCdfkYjp4:b-c9tamn) ([raw file](https://github.com/cockroachdb/pebble/blob/8c566397cd86914a12875fa24a05c0a24f4be779/sstable/reader_iter_single_lvl.go#L60)):*
> ```Go
> 	// being reused). It is currently only provided when the iterator tree is
> 	// rooted at pebble.Iterator. iterStats is this sstable iterators private
> 	// stats that are not reported to a CategoryStatsCollector when this
> ```

s/are not reported/are reported/?

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3015)* status: 14 of 32 files reviewed, 4 unresolved discussions (waiting on @jbowens and @sumeerbhola)

___
*[`options.go` line 195 at r3](https://reviewable.io/reviews/cockroachdb/pebble/3015#-NiaOlp3Bky8kC47q13S:-Nj9OZFE1XjM-sjijJEb:b-9tifpf) ([raw file](https://github.com/cockroachdb/pebble/blob/8c566397cd86914a12875fa24a05c0a24f4be779/options.go#L195)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

We have logic in SetOptions that forces the point iterator to be reconstructed if `OnlyReadGuaranteedDurable` or `UseL6Filters`. Alternatively we could add similar logic for `CategroyAndQoS`
</blockquote></details>

I've simply removed this TODO. I didn't add any logic to `SetOptions` to recreate the point iterator if this is changed -- I am slightly worried that someone will forget to set `CategoryAndQoS` when calling `SetOptions` and cause a performance regression *and* stop collecting stats in the proper category. And we don't currently have a reuse use case that needs changing `CategoryAndQos`.
___
*[`sstable/category_stats.go` line 135 at r3](https://reviewable.io/reviews/cockroachdb/pebble/3015#-NiaQiXr4LYXBj3CmcBo:-Nj9Pnx0Eylr5a-BYXLa:b-jxm4wr) ([raw file](https://github.com/cockroachdb/pebble/blob/8c566397cd86914a12875fa24a05c0a24f4be779/sstable/category_stats.go#L135)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

will this be okay when converted into a timeseries name? I don't know what restrictions prometheus or the like have on series names, but in promql I know braces are used to filter on series metadata. Did a bit searching and it looks like the only non-alphanumeric characters that prometheus allows are underscores or colons: https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels I think we define metric names in Cockroach using hypens, so something must automatically translate? Anyways maybe underscores or colons will play nicer.
</blockquote></details>

Changed to `_unknown`.
___
*[`sstable/reader_iter_single_lvl.go` line 60 at r3](https://reviewable.io/reviews/cockroachdb/pebble/3015#-NiaSt0q-YOWCdfkYjp3:-Nj9Q9Xd0g42KkP_MoKX:bb6un1j) ([raw file](https://github.com/cockroachdb/pebble/blob/8c566397cd86914a12875fa24a05c0a24f4be779/sstable/reader_iter_single_lvl.go#L60)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

s/are not reported/are reported/?
</blockquote></details>

Done

**Pull request merged**
