### PR TITLE
db: add stress test of snapshots and range deletions

### PR DESCRIPTION
**Pull request by jbowens**
Add a unit test that exercises interactions between snapshots and range
deletions.

### CODE REVIEW

**Comment by petermattis** [comment]
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/645)

**Comment by jbowens** [comment]
CI hit a metamorphic test failure, which is a little concerning: https://travis-ci.org/github/cockroachdb/pebble/jobs/682381616

**Comment by petermattis** [comment]
> CI hit a metamorphic test failure, which is a little concerning: https://travis-ci.org/github/cockroachdb/pebble/jobs/682381616

Agreed that is concerning. It is unfortunate that we're not printing the ops and options in this failure mode like we are if a run actually crashes. Would be good to unify that. Care to make that change to `meta_test.go`? (Separate PR please).

**Comment by jbowens** [comment]
> Agreed that is concerning. It is unfortunate that we're not printing the ops and options in this failure mode like we are if a run actually crashes. Would be good to unify that. Care to make that change to meta_test.go? (Separate PR please).

Sounds good. Will do.

**Pull request merged**
