### PR TITLE
internal/manifest: use a line sweep to optimize NewL0Sublevels 

### PR DESCRIPTION
**Pull request by bananabrick**
We do some duplicate work in calculating the {min,max}IntervalIndex for a file
which can be avoided. This pr uses a line sweep algorithm to process the file
intervals, and avoids the binary search used to calculate {min, max}IntervalIndex.

Improvement in L0Sublevels creation:
```
name                old time/op    new time/op    delta
L0SublevelsInit-24    9.44ms ± 5%    7.30ms ± 5%  -22.66%  (p=0.010 n=4+6)

name                old alloc/op   new alloc/op   delta
L0SublevelsInit-24    2.98MB ± 0%    3.08MB ± 0%   +3.58%  (p=0.029 n=4+4)

name                old allocs/op  new allocs/op  delta
L0SublevelsInit-24     33.8k ± 0%     33.8k ± 0%     ~     (all equal)
```

### CODE REVIEW

**Review by itsbilal — COMMENTED** [review]
Great work, thanks for taking a stab at this! Just some minor comments

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1482#-:-Mul9AgGBqvjG7Nm4QJ8:b4awcod)* status: all files reviewed, 4 unresolved discussions (waiting on @bananabrick and @sumeerbhola)

___
*[internal/manifest/l0_sublevels.go, line 56 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1482#-Mul5yo54cYqO--zsZcq:-Mul5yo54cYqO--zsZcr:b-ya3gz2) ([raw file](https://github.com/cockroachdb/pebble/blob/e49a8d20cdaef2582cb726a0e1c043333bf6c875/internal/manifest/l0_sublevels.go#L56)):*
> ```Go
> 	// and have no meaning beyond that.
> 	fileMeta *FileMetadata
> 	remove   bool
> ```

`endKey` would be a better name for this, as this doesn't mean anything about whether it'll be removed or not.
___
*[internal/manifest/l0_sublevels.go, line 100 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1482#-MulB-n56h1v8JPEpmtT:-MulB-n66LwrqFjk4KTU:bpcxo2g) ([raw file](https://github.com/cockroachdb/pebble/blob/e49a8d20cdaef2582cb726a0e1c043333bf6c875/internal/manifest/l0_sublevels.go#L100)):*
> ```Go
> 		keys[j] = keys[i]
> 
> 		for i < len(keys) && intervalKeyCompare(cmp, fi, keys[i]) == 0 {
> ```

Nit: you could replace `fi` with `keys[j]` and it'd be more readable.
___
*[internal/manifest/l0_sublevels.go, line 104 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1482#-MulB9nL-8-sFr_sKH26:-MulB9nL-8-sFr_sKH27:bqlfjlr) ([raw file](https://github.com/cockroachdb/pebble/blob/e49a8d20cdaef2582cb726a0e1c043333bf6c875/internal/manifest/l0_sublevels.go#L104)):*
> ```Go
> 			if consider.remove {
> 				// This is the right endpoint of some file interval, so the
> 				// file.maxIntervalIndex must be j - 1.
> ```

Nit: end this comment with " as maxIntervalIndex is inclusive".
___
*[internal/manifest/l0_sublevels.go, line 259 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1482#-MulBU3E-yQM-gqT76PD:-MulBU3E-yQM-gqT76PE:b-83sjoh) ([raw file](https://github.com/cockroachdb/pebble/blob/b958d9a7760badf3158fa650c23850de4292c7d3/internal/manifest/l0_sublevels.go#L259)):*
> ```Go
> 	for f := iter.First(); f != nil; f = iter.Next() {
> 		// Set f.minIntervalIndex and f.maxIntervalIndex.
> 		f.minIntervalIndex = sort.Search(len(keys), func(index int) bool {
> ```

Nice!
___
*[internal/manifest/l0_sublevels.go, line 273 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1482#-MulBPlzAq9MgCgpHriC:-MulBPlzAq9MgCgpHriD:bb6e7oa) ([raw file](https://github.com/cockroachdb/pebble/blob/e49a8d20cdaef2582cb726a0e1c043333bf6c875/internal/manifest/l0_sublevels.go#L273)):*
> ```Go
> 		s.orderedIntervals[i] = fileInterval{
> 			index:                 i,
> 			startKey:              keys[i],
> ```

Since we store `intervalKeys` here in its entirety, it might be a good idea to make a separate `intervalFileTemp` struct that is:

```
type intervalKeyTemp struct {
  intervalKey
  fileMeta *FileMetadata
  remove bool
}
```

and define `sortAndSweep` on `[]intervalKeyTemp`, and here when we convert it into `fileIntervals` you could just do `keys[i].intervalKey`.

I'm also good with this way; there are already a lot of types defined in this file and maybe adding more is a bad idea. Thoughts?

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1482)* status: all files reviewed, 8 unresolved discussions (waiting on @bananabrick and @itsbilal)

___
*[internal/manifest/l0_sublevels.go, line 55 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1482#-MumOH9oEZErOukmlETW:-MumOH9oEZErOukmlETX:brbfa5p) ([raw file](https://github.com/cockroachdb/pebble/blob/e49a8d20cdaef2582cb726a0e1c043333bf6c875/internal/manifest/l0_sublevels.go#L55)):*
> ```Go
> 	// The following fields are only used during L0Sublevels construction
> 	// and have no meaning beyond that.
> 	fileMeta *FileMetadata
> ```

we should set this to nil when we no longer need it.
___
*[internal/manifest/l0_sublevels.go, line 56 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1482#-Mul5yo54cYqO--zsZcq:-MumRYde3T_Dxg8VRfbG:bqtkaii) ([raw file](https://github.com/cockroachdb/pebble/blob/e49a8d20cdaef2582cb726a0e1c043333bf6c875/internal/manifest/l0_sublevels.go#L56)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

`endKey` would be a better name for this, as this doesn't mean anything about whether it'll be removed or not.
</blockquote></details>

+1. Perhaps `isEndKey` since it is a bool
___
*[internal/manifest/l0_sublevels.go, line 86 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1482#-MumOSd_1qRzin9V5DdD:-MumOSd_1qRzin9V5DdE:b-y0n0jz) ([raw file](https://github.com/cockroachdb/pebble/blob/e49a8d20cdaef2582cb726a0e1c043333bf6c875/internal/manifest/l0_sublevels.go#L86)):*
> ```Go
> 
> // sortAndSweep will sort the intervalKeys using intervalKeySorter, remove the
> // duplicate fileIntervals, and set the {min, max}IntervalIndex for the files.
> ```

This could use a code comment explaining the algorithm.
IIUC, the main insight here is that there are two intervalKeys for each file in keys, corresponding to the start and end key. So when we are de-duplicating, we will encounter the bounds of the file, and we can use that to initialize the file interval indexes in the same pass as de-duping.
___
*[internal/manifest/l0_sublevels.go, line 93 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1482#-MumSC4a4jmTT4zvIQSW:-MumSC4a4jmTT4zvIQSX:bi4lwy3) ([raw file](https://github.com/cockroachdb/pebble/blob/e49a8d20cdaef2582cb726a0e1c043333bf6c875/internal/manifest/l0_sublevels.go#L93)):*
> ```Go
> 	sorter := intervalKeySorter{keys: keys, cmp: cmp}
> 	sort.Sort(sorter)
> ```

// INVARIANT: j <= i
___
*[internal/manifest/l0_sublevels.go, line 100 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1482#-MulB-n56h1v8JPEpmtT:-MumSOK3AmIl67BdlVT5:b-jp15nd) ([raw file](https://github.com/cockroachdb/pebble/blob/e49a8d20cdaef2582cb726a0e1c043333bf6c875/internal/manifest/l0_sublevels.go#L100)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Nit: you could replace `fi` with `keys[j]` and it'd be more readable.
</blockquote></details>

or s/fi/keyJ/ if the compiler is not smart enough to figure out that `keys[j]` is not changing due to the loop.
___
*[internal/manifest/l0_sublevels.go, line 100 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1482#-MumSaKOE-jT5mrq0cqx:-MumSaKOE-jT5mrq0cqy:bk7e9vg) ([raw file](https://github.com/cockroachdb/pebble/blob/e49a8d20cdaef2582cb726a0e1c043333bf6c875/internal/manifest/l0_sublevels.go#L100)):*
> ```Go
> 		keys[j] = keys[i]
> 
> 		for i < len(keys) && intervalKeyCompare(cmp, fi, keys[i]) == 0 {
> ```

you could change this to
```
for {
   ...
  i++
  if i >= len(keys) || intervalKeyCompare(cmp, fi, keys[i]) != 0 {
    break
  }
}
```
and avoid an unnecessary key comparison for the first iteration.
___
*[internal/manifest/l0_sublevels.go, line 273 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1482#-MulBPlzAq9MgCgpHriC:-MumRt8rE_rGKrY0JJKf:b-umbzxf) ([raw file](https://github.com/cockroachdb/pebble/blob/e49a8d20cdaef2582cb726a0e1c043333bf6c875/internal/manifest/l0_sublevels.go#L273)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Since we store `intervalKeys` here in its entirety, it might be a good idea to make a separate `intervalFileTemp` struct that is:

```
type intervalKeyTemp struct {
  intervalKey
  fileMeta *FileMetadata
  remove bool
}
```

and define `sortAndSweep` on `[]intervalKeyTemp`, and here when we convert it into `fileIntervals` you could just do `keys[i].intervalKey`.

I'm also good with this way; there are already a lot of types defined in this file and maybe adding more is a bad idea. Thoughts?
</blockquote></details>

I like this idea of using a temp struct.

**Review by bananabrick — COMMENTED** [review]
Thanks for the reviews.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1482#-:-MuqIAPk9E3ETmBm3ZXF:b-hlc8b9)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @itsbilal and @sumeerbhola)

___
*[internal/manifest/l0_sublevels.go, line 55 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1482#-MumOH9oEZErOukmlETW:-MuqJGiV319rdfYePdpf:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/e49a8d20cdaef2582cb726a0e1c043333bf6c875/internal/manifest/l0_sublevels.go#L55)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

we should set this to nil when we no longer need it.
</blockquote></details>

Done.
___
*[internal/manifest/l0_sublevels.go, line 56 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1482#-Mul5yo54cYqO--zsZcq:-MuqJHJC7PlvZ87Ztfku:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/e49a8d20cdaef2582cb726a0e1c043333bf6c875/internal/manifest/l0_sublevels.go#L56)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

+1. Perhaps `isEndKey` since it is a bool
</blockquote></details>

Done.
___
*[internal/manifest/l0_sublevels.go, line 86 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1482#-MumOSd_1qRzin9V5DdD:-MuqJHz61wCP4hkuRU-q:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/e49a8d20cdaef2582cb726a0e1c043333bf6c875/internal/manifest/l0_sublevels.go#L86)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

This could use a code comment explaining the algorithm.
IIUC, the main insight here is that there are two intervalKeys for each file in keys, corresponding to the start and end key. So when we are de-duplicating, we will encounter the bounds of the file, and we can use that to initialize the file interval indexes in the same pass as de-duping.
</blockquote></details>

Done.
___
*[internal/manifest/l0_sublevels.go, line 93 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1482#-MumSC4a4jmTT4zvIQSW:-MuqJVi-EkW2_AoqZfYT:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/e49a8d20cdaef2582cb726a0e1c043333bf6c875/internal/manifest/l0_sublevels.go#L93)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

// INVARIANT: j <= i
</blockquote></details>

Done.
___
*[internal/manifest/l0_sublevels.go, line 100 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1482#-MumSaKOE-jT5mrq0cqx:-MuqMfMK7ZXP6_4gaxpI:b-ubkzlq) ([raw file](https://github.com/cockroachdb/pebble/blob/e49a8d20cdaef2582cb726a0e1c043333bf6c875/internal/manifest/l0_sublevels.go#L100)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

you could change this to
```
for {
   ...
  i++
  if i >= len(keys) || intervalKeyCompare(cmp, fi, keys[i]) != 0 {
    break
  }
}
```
and avoid an unnecessary key comparison for the first iteration.

</blockquote></details>

Neat. Most `intervalKeys` probably won't have duplicates, so this will help a lot.

**Review by bananabrick — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1482)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @itsbilal and @sumeerbhola)

___
*[internal/manifest/l0_sublevels.go, line 57 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1482#-MuqVe3cC48lRBXNgTD0:-MuqVe3cC48lRBXNgTD1:bg9n9ii) ([raw file](https://github.com/cockroachdb/pebble/blob/327ebe08a431461179700d5d9d121f472f4d2e77/internal/manifest/l0_sublevels.go#L57)):*
> ```Go
> // which is used to generate the {min,max}IntervalIndex for files.
> type intervalKeyTemp struct {
> 	intervalKey intervalKey
> ```

I didn't embed this struct, cause embedding structs leads to awkward syntax for struct initialization.

**Review by bananabrick — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1482)* status: 0 of 1 files reviewed, 8 unresolved discussions (waiting on @itsbilal and @sumeerbhola)

___
*[internal/manifest/l0_sublevels.go, line 100 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1482#-MumSaKOE-jT5mrq0cqx:-Mur8gsr8Pg2HcKA3npz:b-xp1puy) ([raw file](https://github.com/cockroachdb/pebble/blob/e49a8d20cdaef2582cb726a0e1c043333bf6c875/internal/manifest/l0_sublevels.go#L100)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

yep, that's what I was thinking. Any change in the benchmark numbers?
</blockquote></details>

I thought about this, and the comparison must still be done exactly once for each key. The only comparison we save on is the first comparison for keys[0].

But there is somehow a `5%` perf win, for an overall 20% win in that function:
```
name                old time/op    new time/op    delta
L0SublevelsInit-24    9.44ms ± 5%    7.30ms ± 5%  -22.66%  (p=0.010 n=4+6)

name                old alloc/op   new alloc/op   delta
L0SublevelsInit-24    2.98MB ± 0%    3.08MB ± 0%   +3.58%  (p=0.029 n=4+4)

name                old allocs/op  new allocs/op  delta
L0SublevelsInit-24     33.8k ± 0%     33.8k ± 0%     ~     (all equal)
```
___
*[internal/manifest/l0_sublevels.go, line 98 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1482#-MuqgYlFDI_PFPWySDHH:-Mur97Vy9TeMw8ep3qLZ:b8i16ux) ([raw file](https://github.com/cockroachdb/pebble/blob/327ebe08a431461179700d5d9d121f472f4d2e77/internal/manifest/l0_sublevels.go#L98)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I was imagining something more detailed like:

// intervalKeys are generated using the file bounds. Specifically, there are 2 intervalKeys for each file, and len(keys) = 2 * number of files.
// We have stored a reference to the corresponding file in each intervalKeyTemp. This allows us the following approach to do de-duping and computing the {min,max}IntervalIndex in a single pass:
// - When we encounter a start key, its file has a minIntervalIndex equal to the corresponding de-duped index.
// - When we encounter an end key, the corresponding de-duped index, which represents the inclusive start key of an interval, is one ahead of the maxIntervalIndex.
</blockquote></details>

Wrote a more detailed explanation.
___
*[internal/manifest/l0_sublevels.go, line 119 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1482#-MuqiNQq1vE9pefzmzLT:-Mur8rneBksK3yfsVWzH:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/327ebe08a431461179700d5d9d121f472f4d2e77/internal/manifest/l0_sublevels.go#L119)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

This won't do anything since this a copy of the intervalKeyTemp struct.
We shouldn't need to nil these pointers since we are going to throw away `[]intervalKeyTemp` soon after this method returns.
</blockquote></details>

Done.

**Pull request merged**
