### PR TITLE
metamorphic: consolidate key manager per-object structures

### PR DESCRIPTION
**Pull request by RaduBerinde**
This commit merges the `byObj`, `byObjMap` and `bounds` maps into a
single map to a consolidated `*objKeyMeta`.

We no longer store keys in two structures; we only use a map.  We
simplify and improve `mergeKeysInto` to use the target map instead of
sorting and merging all keys; this should be much faster when the
target is the database.

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Actually, let me work on this some more and reopen.

**Comment by RaduBerinde** [comment]
Ok, ready for review.

**Review by jbowens — APPROVED** [review]
Nice :lgtm:

> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3253#-:-NpVK9GMCxugLqbUjpi1:b-qcmwly)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @RaduBerinde)

___
*[`metamorphic/key_manager.go` line 235 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3253#-NpVI5-F3E8dLVQmDAqt:-NpVI5-F3E8dLVQmDAqu:b-oa5er9) ([raw file](https://github.com/cockroachdb/pebble/blob/689f96754fb8c3c97abfd3a9322affb0557c7b77/metamorphic/key_manager.go#L235)):*
> ```Go
> 	}
> 	slices.SortFunc(res, func(a, b *keyMeta) int {
> 		return bytes.Compare(a.key, b.key)
> ```

Using `bytes.Compare` doesn't seem to be a new behavior, but it seems like this should be a problem for `generator.randKeyToReadWithinBounds` which generate keys to fall within bounds according to `base.Compare`.

Ah, I see, `randKeyToReadWithinBounds` isn't actually making use of the sorted property. Maybe we should thread the `Compare` func through and always sort according to it to avoid confusion?

**Comment by RaduBerinde** [comment]
*[`metamorphic/key_manager.go` line 235 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3253#-NpVI5-F3E8dLVQmDAqt:-NpVKmDX-PP9dY42BZPO:bt96px2) ([raw file](https://github.com/cockroachdb/pebble/blob/689f96754fb8c3c97abfd3a9322affb0557c7b77/metamorphic/key_manager.go#L235)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

Using `bytes.Compare` doesn't seem to be a new behavior, but it seems like this should be a problem for `generator.randKeyToReadWithinBounds` which generate keys to fall within bounds according to `base.Compare`.

Ah, I see, `randKeyToReadWithinBounds` isn't actually making use of the sorted property. Maybe we should thread the `Compare` func through and always sort according to it to avoid confusion?
</blockquote></details>

Good point, I will work on that. I believe that currently we only use this to avoid nondeterminism (but I agree we might as well do it right). In the previous use, we sorted just to merge-join, the particular ordering didn't actually matter.

**Comment by RaduBerinde** [comment]
*[`metamorphic/key_manager.go` line 235 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3253#-NpVI5-F3E8dLVQmDAqt:-NpW6MCtA54XzSJgsmO3:bprgsbe) ([raw file](https://github.com/cockroachdb/pebble/blob/689f96754fb8c3c97abfd3a9322affb0557c7b77/metamorphic/key_manager.go#L235)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Good point, I will work on that. I believe that currently we only use this to avoid nondeterminism (but I agree we might as well do it right). In the previous use, we sorted just to merge-join, the particular ordering didn't actually matter.
</blockquote></details>

Done. Also renamed `randKeyToReadWithinBounds` to `inRangeKeys`.

**Pull request merged**
