### PR TITLE
wal: implement failoverManager.{Obsolete,Stats} and log recycling

### PR DESCRIPTION
**Pull request by sumeerbhola**
Informs #3230

Informs CRDB-35401

### CODE REVIEW

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3328)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @jbowens)

___
*[`wal/failover_manager_test.go` line 496 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3328#-NrCEgCQEjyfOIGhXEPe:-NrCEgCQEjyfOIGhXEPf:b-fuoaj1) ([raw file](https://github.com/cockroachdb/pebble/blob/724bb36f4b7c17f2f2b1a5ad966d74b45c2af641/wal/failover_manager_test.go#L496)):*
> ```Go
> 
> // TODO(sumeer): test failoverManager.{List,Obsolete,Stats}
> // TODO(sumeer): test failoverWriter.getLog
> ```

The todos to test the new code. Existing tests pass.
If you need these changes merged to get unblocked, I can write the tests in a followup PR.

**Review by jbowens — APPROVED** [review]
:lgtm_strong: 

> Reviewed 5 of 8 files at r1, 2 of 5 files at r2, 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3328#-:-NrGXNGVD59fZSB-4cWc:b-uwkowd)* status: 8 of 11 files reviewed, 2 unresolved discussions (waiting on @sumeerbhola)

___
*[`wal/failover_manager.go` line 602 at r3](https://reviewable.io/reviews/cockroachdb/pebble/3328#-NrGSuQU-P2s7znyJf6D:-NrGSuQU-P2s7znyJf6E:bcvx4dp) ([raw file](https://github.com/cockroachdb/pebble/blob/0b6f1a0a32156b4f9198c06ae99c0dadd5b2eae4/wal/failover_manager.go#L602)):*
> ```Go
> 	wm.mu.Lock()
> 	defer wm.mu.Unlock()
> 	wm.mu.closedWALs = append(wm.mu.closedWALs, wm.mu.ww.getLog())
> ```

wdyt of passing the `logicalLogWithSizesEtc` in to the `writerClosed` callback to make this control flow a little more explicit?

**Review by sumeerbhola — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3328#-:-NrGjpvw33T9Y_uMiYNT:b-814g8k)* status: 5 of 11 files reviewed, 2 unresolved discussions (waiting on @jbowens)

___
*[`wal/failover_manager.go` line 602 at r3](https://reviewable.io/reviews/cockroachdb/pebble/3328#-NrGSuQU-P2s7znyJf6D:-NrGjoi97Lsf4UdcXcla:bb6un1j) ([raw file](https://github.com/cockroachdb/pebble/blob/0b6f1a0a32156b4f9198c06ae99c0dadd5b2eae4/wal/failover_manager.go#L602)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

wdyt of passing the `logicalLogWithSizesEtc` in to the `writerClosed` callback to make this control flow a little more explicit?
</blockquote></details>

Done

**Comment by sumeerbhola** [comment]
following test failure is unrelated:
```
--- FAIL: TestGeneratorRandom (0.08s)
    --- FAIL: TestGeneratorRandom/config=default (0.08s)
panic: could not generate unique key [recovered]
	panic: could not generate unique key [recovered]
	panic: could not generate unique key
```

**Pull request merged**
