### PR TITLE
Adding badger fixes on seekLT and Scans.

### PR DESCRIPTION
**Pull request by souravDgraph**
Adding SeekLT function and fixing scan function for badger

### CODE REVIEW

**Comment by petermattis** [comment]
@souravDgraph This badger support was only for benchmarking purposes. We don't plan to maintain it and I was actually thinking it should be removed. Are you trying to do more comparative benchmarking between Badger and Pebble?

**Comment by souravDgraph** [comment]
@petermattis Yes I am planning to do more comparative benchmarking between Badger and pebble. So I think it is better if the changes are part it.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1092)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @souravDgraph)

___
*[go.mod, line 9 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1092#-MWOrcbb9_e4ZOqhcnii:-MWOrcbb9_e4ZOqhcnij:b-sp30vc) ([raw file](https://github.com/cockroachdb/pebble/blob/2e3d02038430b5a908fd4281ff169c7acfc3f560/go.mod#L9)):*
> ```XML
> 	github.com/cockroachdb/redact v1.0.8
> 	github.com/codahale/hdrhistogram v0.0.0-20161010025455-3a0bb77429bd
> 	github.com/dgraph-io/badger/v3 v3.2011.1
> ```

We've avoided adding this dependency in the past. Pebble itself isn't dependent on badger and I think it would be a shame to indicate that in the `go.mod` file. We usually update module dependencies via `make mod-update`. For badger, boltdb, and rocksdb, we arrange to have those packages present in the GOPATH when building with the associated build tags. I haven't tried this in a while, but I'm assuming that technique still works. 
___
*[cmd/pebble/badger.go, line 57 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1092#-MWOrQx3CFddvLhoVv5L:-MWOrQx3CFddvLhoVv5M:b-mswr8t) ([raw file](https://github.com/cockroachdb/pebble/blob/2e3d02038430b5a908fd4281ff169c7acfc3f560/cmd/pebble/badger.go#L57)):*
> ```Go
> 	}
> 	it := txn.NewIterator(badger.DefaultIteratorOptions)
>         for it.Rewind(); it.Valid(); it.Next() {
> ```

The indentation of this line appears to be off. Have you run `gofmt`?
___
*[cmd/pebble/badger.go, line 81 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1092#-MWOrNBGBq84l6nUGw3n:-MWOrNBGBq84l6nUGw3o:b-p033rj) ([raw file](https://github.com/cockroachdb/pebble/blob/2e3d02038430b5a908fd4281ff169c7acfc3f560/cmd/pebble/badger.go#L81)):*
> ```Go
> }
> 
> func (i *badgerIterator) SeekLT(key []byte) bool {
> ```

It isn't useful to implement `SeekLT` unless you also implement `Prev`.

**Comment by ahothan** [comment]
I am (also) stuck with this build issue as I'd like to build the cli to introspect a pebble instance.
I also think it would be better to avoid having dependencies on badger just for this tool, so perhaps move this comparative tool to a different repo and trim this one to have a true pebble-only cli?
I was wondering if anybody would need a pebble cli to introspect pebble instances?

**Comment by petermattis** [comment]
@ahothan Why is badger support preventing you from building the Pebble cli? You should be able to build the Pebble cli using `go install github.com/cockroachdb/pebble/cmd/pebble`. By default, the badger code is not linked in (you need to pass `-tags badger` to have it built). The badger code is only present for comparative benchmarking purposes and is not needed for any of the introspection tools.

**Comment by ahothan** [comment]
@petermattis thanks for pointing this out, I was not building it correctly, it does build now without badger.

**Comment by jbowens** [comment]
Hi @souravDgraph, we've removed badger support from cmd/pebble, so I'm going to close this out.

**Pull request closed without merging**
