### PR TITLE
sstable: move block property collector calls to the Writer client gor…

### PR DESCRIPTION
**Pull request by bananabrick**
…outine

When we decide to finish a data block, all the appropriate calls to the BlockPropertyCollector
like FinishDataBlock, FinishIndexBlock, AddPrevDataBlockToIndexBlock, must be made before
any more calls to BlockPropertyCollector.Add are made. To maintain this invariant, we don't
make any calls to the BlockPropertyCollector from the writeQueue, since the writeQueue could
perform writes in parallel to the Writer client.

### CODE REVIEW

**Review by bananabrick — COMMENTED** [review]
Should be ready for review

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1532#-:-MwcM0WG9OBKm-ouaOXk:btimhy9)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @itsbilal and @jbowens)

**Review by mufeez-amjad — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1532)* status: all files reviewed, 4 unresolved discussions (waiting on @bananabrick, @itsbilal, and @jbowens)

___
*[sstable/write_queue.go, line 66 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1532#-MweLl-fDFeZUcon8lo2:-MweLl-fDFeZUcon8lo3:bbj73r) ([raw file](https://github.com/cockroachdb/pebble/blob/a46cf0785dd14a5426c0fe2e01053fa27306e499/sstable/write_queue.go#L66)):*
> ```Go
> 	)
> 
> 	bhp = BlockHandleWithProperties{bh, task.buf.dataBlockProps}
> ```

nit: consider using `BlockHandleWithProperties{BlockHandle: bh, Props: task.buf.dataBlockProps}` for consistency - looks like you instantiated in `maybeAddBlockPropertiesToBlockHandle` with named fields.
___
*[sstable/writer.go, line 483 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1532#-MweIVVS6NYKP7N145bG:-MweIVVS6NYKP7N145bH:bid9xy6) ([raw file](https://github.com/cockroachdb/pebble/blob/a46cf0785dd14a5426c0fe2e01053fa27306e499/sstable/writer.go#L483)):*
> ```Go
> 
> 	// We're making calls to BlockPropertyCollectors from the Writer client goroutine. We need to
> 	// pass the encoded block properties over to the write queue. To prevent copied, and allocations,
> ```

nit: s/To prevent copied/To prevent being copied
___
*[sstable/writer.go, line 1026 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1532#-MweJ8Y4DLv18QI7avww:-MweJ8Y4DLv18QI7avwx:b-rbw7lg) ([raw file](https://github.com/cockroachdb/pebble/blob/a46cf0785dd14a5426c0fe2e01053fa27306e499/sstable/writer.go#L1026)):*
> ```Go
> 
> 	// We're finishing a data block.
> 	err = w.finishDataBlockProps(w.dataBlockBuf)
> ```

naive question - is there a reason not to use `err :=` in place of `var err error`? it seems to be deliberately used here.
___
*[sstable/writer.go, line 1205 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1532#-MweO1eICvwC2POngBVg:-MweO1eICvwC2POngBVh:b-p7275w) ([raw file](https://github.com/cockroachdb/pebble/blob/a46cf0785dd14a5426c0fe2e01053fa27306e499/sstable/writer.go#L1205)):*
> ```Go
> 		props, err = w.finishIndexBlockProps()
> 	}
> 	if err != nil {
> ```

nit: in `Writer.flush` the error from `w.finishIndexBlockProps` is handled inside the if, but handled outside here.

**Review by itsbilal — APPROVED** [review]
:lgtm:

Code looks great! Just some comments about... comments. 

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1532#-:-MwhSDty2ah25EsGUSpu:b-z22rqp)* status: all files reviewed, 9 unresolved discussions (waiting on @bananabrick, @jbowens, and @mufeez-amjad)

___
*[sstable/writer.go, line 483 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1532#-MweIVVS6NYKP7N145bG:-MwhAohn7lXi4RyCkuqb:bc4wpqo) ([raw file](https://github.com/cockroachdb/pebble/blob/a46cf0785dd14a5426c0fe2e01053fa27306e499/sstable/writer.go#L483)):*
<details><summary><i>Previously, mufeez-amjad (Mufeez Amjad) wrote…</i></summary><blockquote>

nit: s/To prevent copied/To prevent being copied
</blockquote></details>

Or `to prevent copies` works too.
___
*[sstable/writer.go, line 1059 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1532#-MwhIz-90DAKZsiN5PJQ:-MwhIz-90DAKZsiN5PJR:b7j1uem) ([raw file](https://github.com/cockroachdb/pebble/blob/a46cf0785dd14a5426c0fe2e01053fa27306e499/sstable/writer.go#L1059)):*
> ```Go
> 
> 	// We've called BlockPropertyCollector.FinishDataBlock, and, if necessary, BlockPropertyCollector.FinishIndexBlock.
> 	// Since, we've decided to finish the data block, so we can call BlockPropertyCollector.AddPrevDataBlockToIndexBlock.
> ```

Nit: "Since we've decided to finish this data block, we can call...."

Also we could expand this comment to include that 
___
*[sstable/writer.go, line 1100 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1532#-MwhS5QRBUKcqNFh0J20:-MwhS5QRBUKcqNFh0J21:bhgm40r) ([raw file](https://github.com/cockroachdb/pebble/blob/a46cf0785dd14a5426c0fe2e01053fa27306e499/sstable/writer.go#L1100)):*
> ```Go
> }
> 
> // The byte slice returned by this method must be encoded before any future use of the
> ```

The function isn't directly returning any byte slice, so you want to instead say the byte slice inside `buf` must be encoded before ...
___
*[sstable/writer.go, line 1153 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1532#-MwhRJ1L5BWrvgOLIGkT:-MwhRJ1L5BWrvgOLIGkU:b-whbzvy) ([raw file](https://github.com/cockroachdb/pebble/blob/a46cf0785dd14a5426c0fe2e01053fa27306e499/sstable/writer.go#L1153)):*
> ```Go
> 
> // addIndexEntry adds an index entry for the specified key and block handle. addIndexEntry can be called from
> // both the Writer client goroutine, and the writeQueue goroutine.
> ```

Add to this comment that the presence of a non-nil flushIndexBuf means that that index block will be flushed, and any relevant indexProps must be specified if that's happening. Would also help to clarify that indexProps is for the flushed index block, not the writeTo index block.
___
*[sstable/writer.go, line 1257 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1532#-MwhPtpI1f6UYFZvUhTL:-MwhPtpI1f6UYFZvUhTM:b-sqg6x9) ([raw file](https://github.com/cockroachdb/pebble/blob/a46cf0785dd14a5426c0fe2e01053fa27306e499/sstable/writer.go#L1257)):*
> ```Go
> }
> 
> func (w *Writer) finishIndexBlockProps() ([]byte, error) {
> ```

A clarifying comment here would be good, that this must be called before finishIndexBlock and in the Writer goroutine.
___
*[sstable/writer.go, line 1299 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1532#-MwhKijO5yGargduW8W2:-MwhKijP2ZCJtXN9ikFI:b-mpuu2) ([raw file](https://github.com/cockroachdb/pebble/blob/a46cf0785dd14a5426c0fe2e01053fa27306e499/sstable/writer.go#L1299)):*
> ```Go
> 	}
> 	// Add the final unfinished index.
> 	if err := w.finishIndexBlock(w.indexBlock, props); err != nil {
> ```

Nit: could reuse err instead of redeclaring with :=

**Comment by itsbilal** [comment]
In one of these PRs, it would also be good to add some tests that verify sstables for equivalence between some simple parallel and non-parallel sstable writer uses. Simple enough that the non-determinism of sstable size estimation and concurrency doesn't become an issue.

**Review by bananabrick — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1532)* status: all files reviewed, 4 unresolved discussions (waiting on @itsbilal, @jbowens, and @mufeez-amjad)

___
*[sstable/writer.go, line 1026 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1532#-MweJ8Y4DLv18QI7avww:-MwhZ7WvCaitM3_q6BDr:b-wdrfvf) ([raw file](https://github.com/cockroachdb/pebble/blob/a46cf0785dd14a5426c0fe2e01053fa27306e499/sstable/writer.go#L1026)):*
<details><summary><i>Previously, mufeez-amjad (Mufeez Amjad) wrote…</i></summary><blockquote>

naive question - is there a reason not to use `err :=` in place of `var err error`? it seems to be deliberately used here.
</blockquote></details>

Yea, `err` is set inside an `if` later.
___
*[sstable/writer.go, line 1100 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1532#-MwhS5QRBUKcqNFh0J20:-MwhZS2K6BEGxwKp7KiJ:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/a46cf0785dd14a5426c0fe2e01053fa27306e499/sstable/writer.go#L1100)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

The function isn't directly returning any byte slice, so you want to instead say the byte slice inside `buf` must be encoded before ...
</blockquote></details>

Done.
___
*[sstable/writer.go, line 1153 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1532#-MwhRJ1L5BWrvgOLIGkT:-MwhZhLz70EFqP5Eyqh3:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/a46cf0785dd14a5426c0fe2e01053fa27306e499/sstable/writer.go#L1153)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Add to this comment that the presence of a non-nil flushIndexBuf means that that index block will be flushed, and any relevant indexProps must be specified if that's happening. Would also help to clarify that indexProps is for the flushed index block, not the writeTo index block.
</blockquote></details>

Done.
___
*[sstable/writer.go, line 1257 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1532#-MwhPtpI1f6UYFZvUhTL:-MwhZzFL8uwOpAvC4wQx:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/a46cf0785dd14a5426c0fe2e01053fa27306e499/sstable/writer.go#L1257)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

A clarifying comment here would be good, that this must be called before finishIndexBlock and in the Writer goroutine.
</blockquote></details>

Done.

**Comment by bananabrick** [comment]
TFTRs

**Pull request merged**
