### PR TITLE
colblk: implement synthetic prefix and suffix

### PR DESCRIPTION
**Pull request by RaduBerinde**
First commit is #3996

#### colblk: implement synthetic prefix and suffix

`DataBlockIter` now takes into account the synthetic prefix and suffix
transforms.

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Forgot to add some benchmarks and compare the no-transform case before/after, will do that soon.

**Review by RaduBerinde — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3997#-:-O8JO35M6EHE9ezsrShZ:b-814g8k)* status: 2 of 9 files reviewed, 1 unresolved discussion (waiting on @jbowens)

___
*[`sstable/colblk/data_block.go` line 947 at r2](https://reviewable.io/reviews/cockroachdb/pebble/3997#-O8IVDbn7R3zXJ4QwzZB:-O8JNrdM5sBgFlgWZ-3v:bfbq99i) ([raw file](https://github.com/cockroachdb/pebble/blob/46ab43cab85a54e00790d574d1f53828e6b54269/sstable/colblk/data_block.go#L947)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

should we put this on a `AnySet()` `Transforms` method or the like?
</blockquote></details>

Good point, done.

**Comment by RaduBerinde** [comment]
Updated benchmark as well.
Short benchmark before/after:
```
name                                                                                old time/op    new time/op    delta
CockroachDataBlockIterShort/AlphaLen=8,Prefix=8,Shared=4,ValueLen=8/Next-10           12.2ns ± 0%    12.6ns ± 0%  +3.05%  (p=0.001 n=7+7)
CockroachDataBlockIterShort/AlphaLen=8,Prefix=8,Shared=4,ValueLen=8/SeekGE-10          114ns ± 0%     114ns ± 1%    ~     (p=0.454 n=8+8)
CockroachDataBlockIterShort/AlphaLen=8,Prefix=128,Shared=64,ValueLen=128/Next-10      10.5ns ± 0%    10.5ns ± 0%  -0.28%  (p=0.024 n=8+8)
CockroachDataBlockIterShort/AlphaLen=8,Prefix=128,Shared=64,ValueLen=128/SeekGE-10    91.0ns ± 0%    91.1ns ± 1%    ~     (p=0.555 n=8+8)
```

Transform benchmark shows very little difference, which is pretty cool!
```
name                                                                                                     time/op
CockroachDataBlockIterTransforms/AlphaLen=8,Prefix=8,Shared=4,ValueLen=8/Next-10                         12.6ns ± 1%
CockroachDataBlockIterTransforms/AlphaLen=8,Prefix=8,Shared=4,ValueLen=8/SeekGE-10                        114ns ± 1%
CockroachDataBlockIterTransforms/AlphaLen=8,Prefix=8,Shared=4,ValueLen=8,SynthSeqNum/Next-10             12.8ns ± 0%
CockroachDataBlockIterTransforms/AlphaLen=8,Prefix=8,Shared=4,ValueLen=8,SynthSeqNum/SeekGE-10            114ns ± 0%
CockroachDataBlockIterTransforms/AlphaLen=8,Prefix=8,Shared=4,ValueLen=8,HideObsolete/Next-10            13.6ns ± 0%
CockroachDataBlockIterTransforms/AlphaLen=8,Prefix=8,Shared=4,ValueLen=8,HideObsolete/SeekGE-10           116ns ± 0%
CockroachDataBlockIterTransforms/AlphaLen=8,Prefix=8,Shared=4,ValueLen=8,SyntheticPrefix/Next-10         12.6ns ± 0%
CockroachDataBlockIterTransforms/AlphaLen=8,Prefix=8,Shared=4,ValueLen=8,SyntheticPrefix/SeekGE-10        116ns ± 0%
CockroachDataBlockIterTransforms/AlphaLen=8,Prefix=8,Shared=4,ValueLen=8,SyntheticSuffix/Next-10         13.0ns ± 4%
CockroachDataBlockIterTransforms/AlphaLen=8,Prefix=8,Shared=4,ValueLen=8,SyntheticSuffix/SeekGE-10        117ns ± 0%
CockroachDataBlockIterTransforms/AlphaLen=8,Prefix=128,Shared=64,ValueLen=128/Next-10                    10.8ns ± 0%
CockroachDataBlockIterTransforms/AlphaLen=8,Prefix=128,Shared=64,ValueLen=128/SeekGE-10                  91.6ns ± 0%
CockroachDataBlockIterTransforms/AlphaLen=8,Prefix=128,Shared=64,ValueLen=128,SynthSeqNum/Next-10        10.8ns ± 0%
CockroachDataBlockIterTransforms/AlphaLen=8,Prefix=128,Shared=64,ValueLen=128,SynthSeqNum/SeekGE-10      91.7ns ± 0%
CockroachDataBlockIterTransforms/AlphaLen=8,Prefix=128,Shared=64,ValueLen=128,HideObsolete/Next-10       11.3ns ± 1%
CockroachDataBlockIterTransforms/AlphaLen=8,Prefix=128,Shared=64,ValueLen=128,HideObsolete/SeekGE-10     94.2ns ± 1%
CockroachDataBlockIterTransforms/AlphaLen=8,Prefix=128,Shared=64,ValueLen=128,SyntheticPrefix/Next-10    10.7ns ± 0%
CockroachDataBlockIterTransforms/AlphaLen=8,Prefix=128,Shared=64,ValueLen=128,SyntheticPrefix/SeekGE-10  94.1ns ± 0%
CockroachDataBlockIterTransforms/AlphaLen=8,Prefix=128,Shared=64,ValueLen=128,SyntheticSuffix/Next-10    10.9ns ± 0%
CockroachDataBlockIterTransforms/AlphaLen=8,Prefix=128,Shared=64,ValueLen=128,SyntheticSuffix/SeekGE-10  95.6ns ± 0%
```

**Comment by RaduBerinde** [comment]
Merged with the recent `DataBlockIter` changes, PTAL.

**Review by jbowens — APPROVED** [review]
:lgtm:

> Reviewed 3 of 9 files at r2, 2 of 3 files at r3, 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3997#-:-O8Y-V5e4I6O3q29Rf1G:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @RaduBerinde)

___
*[`sstable/colblk/data_block.go` line 868 at r5](https://reviewable.io/reviews/cockroachdb/pebble/3997#-O8Xydaj4Jj_5TLXeoZa:-O8Xydaj4Jj_5TLXeoZb:b1p54k5) ([raw file](https://github.com/cockroachdb/pebble/blob/6744ef2902cb414e9275c5c2cec25a580aa71871/sstable/colblk/data_block.go#L868)):*
> ```Go
> 	i.split = split
> 	i.getLazyValuer = getLazyValuer
> 	i.keySeeker = i.keySchema.NewKeySeeker()
> ```

Hrm, I didn't think we could do this in InitOnce because we're making the assumption that we won't `Init`/`InitHandle` after a call `Close` (which is then we release the seeker back to the pool).
___
*[`sstable/colblk/data_block.go` line 1026 at r5](https://reviewable.io/reviews/cockroachdb/pebble/3997#-O8Y-9wbBZuO-udj7H-W:-O8Y-9wbBZuO-udj7H-X:b-fc07jl) ([raw file](https://github.com/cockroachdb/pebble/blob/6744ef2902cb414e9275c5c2cec25a580aa71871/sstable/colblk/data_block.go#L1026)):*
> ```Go
> 	if i.noTransforms {
> 		// Fast path.
> 		i.row, _ = i.keySeeker.SeekGE(key, i.row, searchDir)
> ```

code coverage is saying the fast path isn't covered by our tests; is that right? I thought our datadriven unit tests covered the no transform SeekGE case?
___
*[`sstable/colblk/data_block.go` line 1123 at r5](https://reviewable.io/reviews/cockroachdb/pebble/3997#-O8Y-ByY5vTxs5l8VBaG:-O8Y-ByY5vTxs5l8VBaH:b-8rcl8x) ([raw file](https://github.com/cockroachdb/pebble/blob/6744ef2902cb414e9275c5c2cec25a580aa71871/sstable/colblk/data_block.go#L1123)):*
> ```Go
> 	// Inline decodeKey(), adding obsolete points logic.
> 	if i.noTransforms {
> 		// Fast path.
> ```

ditto re: no-transform code coverage

**Comment by RaduBerinde** [comment]
*[`sstable/colblk/data_block.go` line 1026 at r5](https://reviewable.io/reviews/cockroachdb/pebble/3997#-O8Y-9wbBZuO-udj7H-W:-O8YHzaDCktBbgpjxaLx:bzid3ue) ([raw file](https://github.com/cockroachdb/pebble/blob/6744ef2902cb414e9275c5c2cec25a580aa71871/sstable/colblk/data_block.go#L1026)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

code coverage is saying the fast path isn't covered by our tests; is that right? I thought our datadriven unit tests covered the no transform SeekGE case?
</blockquote></details>

Wow, great catch!! I missed a few ! in NoTransforms()

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3997)* status: 9 of 12 files reviewed, 3 unresolved discussions (waiting on @jbowens)

___
*[`sstable/colblk/data_block.go` line 868 at r5](https://reviewable.io/reviews/cockroachdb/pebble/3997#-O8Xydaj4Jj_5TLXeoZa:-O8YkhUEAj7ikYU0Ga8c:b183f9t) ([raw file](https://github.com/cockroachdb/pebble/blob/6744ef2902cb414e9275c5c2cec25a580aa71871/sstable/colblk/data_block.go#L868)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

Hrm, I didn't think we could do this in InitOnce because we're making the assumption that we won't `Init`/`InitHandle` after a call `Close` (which is then we release the seeker back to the pool).
</blockquote></details>

Reverted this part.
___
*[`sstable/colblk/data_block.go` line 1123 at r5](https://reviewable.io/reviews/cockroachdb/pebble/3997#-O8Y-ByY5vTxs5l8VBaG:-O8YkjX79YnSK-uQHTVY:bt2vr1b) ([raw file](https://github.com/cockroachdb/pebble/blob/6744ef2902cb414e9275c5c2cec25a580aa71871/sstable/colblk/data_block.go#L1123)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

ditto re: no-transform code coverage
</blockquote></details>

Fixed.

**Pull request merged**
