### PR TITLE
internal/rawalloc: add benchmarks to show performance gain compare to…

### PR DESCRIPTION
**Pull request by choleraehyq**
… make

goos: darwin
goarch: amd64
pkg: github.com/cockroachdb/pebble/internal/rawalloc
BenchmarkRawalloc16-12      	81675024	        14.6 ns/op
BenchmarkRawalloc100-12     	45012530	        25.5 ns/op
BenchmarkRawalloc1K-12      	 8933536	       124 ns/op
BenchmarkRawalloc10K-12     	 1515319	       774 ns/op
BenchmarkRawalloc100K-12    	  214456	      5842 ns/op
BenchmarkRawalloc1M-12      	   30844	     35806 ns/op
BenchmarkMake16-12          	62534037	        18.0 ns/op
BenchmarkMake100-12         	37792303	        29.8 ns/op
BenchmarkMake1K-12          	 8321911	       142 ns/op
BenchmarkMake10K-12         	 1282270	       935 ns/op
BenchmarkMake100K-12        	  137275	      8766 ns/op
BenchmarkMake1M-12          	   13593	     79304 ns/op
PASS
ok  	github.com/cockroachdb/pebble/internal/rawalloc	19.015s

Signed-off-by: Cholerae Hu <choleraehyq@gmail.com>

### CODE REVIEW

**Review by petermattis — COMMENTED** [review]
[benchstat](https://godoc.org/golang.org/x/perf/cmd/benchstat) is our preferred tool for displaying benchmark output. It will be somewhat more readable than the above. Additionally, you should run the benchmarks 10x each (using `go test -bench . -count 10`) in order to toss out outliers. `benchstat` will perform that outlier elision.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/898#-:-MHXFmVT9xCL0QhOiP6W:bftq5o9)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @choleraehyq)

___
*[internal/rawalloc/rawalloc_test.go, line 22 at r1](https://reviewable.io/reviews/cockroachdb/pebble/898#-MHXG8UR77l03MpTeSBk:-MHXG8UR77l03MpTeSBl:b-9ch8uh) ([raw file](https://github.com/cockroachdb/pebble/blob/7f5bfb1aef8137d2f79fa0a5982521091fffde1c/internal/rawalloc/rawalloc_test.go#L22)):*
> ```Go
> 
> func BenchmarkRawalloc16(b *testing.B) {
> 	benchmarkRawalloc(b, 16)
> ```

Using sub-benchmarks can reduce this boilerplate:

```
for _, size := range []int{16, 100, 1024, ... } {
  b.Run(fmt.Sprintf("%d", size), func(b *testing.B) {
    for i := 0; i < b.N; i++ {
      _ = New(size, size)
    }
  })
}
```

**Review by choleraehyq — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/898)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @petermattis)

___
*[internal/rawalloc/rawalloc_test.go, line 22 at r1](https://reviewable.io/reviews/cockroachdb/pebble/898#-MHXG8UR77l03MpTeSBk:-MHdque22E8HBBiNcG4h:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/7f5bfb1aef8137d2f79fa0a5982521091fffde1c/internal/rawalloc/rawalloc_test.go#L22)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Using sub-benchmarks can reduce this boilerplate:

```
for _, size := range []int{16, 100, 1024, ... } {
  b.Run(fmt.Sprintf("%d", size), func(b *testing.B) {
    for i := 0; i < b.N; i++ {
      _ = New(size, size)
    }
  })
}
```
</blockquote></details>

Done.

**Comment by choleraehyq** [comment]
Benchmark output in the commit message is using benchstat now.

**Review by petermattis — APPROVED** [review]
:lgtm: Thanks for the contribution!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/898#-:-MHfhsiJ0fieCx6Nzq7_:b-e8djwd)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @petermattis)

**Pull request merged**
