### PR TITLE
db: export keyspan.Span and keyspan.Key

### PR DESCRIPTION
**Pull request by nicktrav**
Export two additional types for use in Cockroach.

See #1774.

### CODE REVIEW

**Review by erikgrinaker — APPROVED** [review]
Thanks! Is `Key` too general a name here, since this is exported in the root `pebble` package? Not sure how the different key types relate to each other.

**Comment by nicktrav** [comment]
> Is Key too general a name here, since this is exported in the root pebble package? Not sure how the different key types relate to each other.

Yeah, very good point. This probably needs a rethink. How about `SpanKey`? That said, if we re-aliased it, does that get reflected in the fields of the re-exported `Span` type? 🤔 I'll have to play around with it some more.

**Comment by erikgrinaker** [comment]
Sure, no rush at all.

**Comment by nicktrav** [comment]
Looks like the compiler will let us do something like this, so I think re-aliasing is fine:

```go
	s := pebble.Span{}
	s.Keys = append(s.Keys, pebble.SpanKey{
		Trailer: 123,
		Suffix:  []byte("@1"),
		Value:   []byte("foo"),
	})

```

I'm sure we do that elsewhere in Pebble. I'll amend.

**Comment by erikgrinaker** [comment]
LGTM, thanks again!

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1787)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @jbowens and @nicktrav)

___
*[`range_keys.go` line 16 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1787#-N5_WUPcBNChDYD6MXpX:-N5_WUPcBNChDYD6MXpY:b-dkx68p) ([raw file](https://github.com/cockroachdb/pebble/blob/06307d92945513bf3d8a46c194b710850fa1daad/range_keys.go#L16)):*
> ```Go
> 
> // Span exports the keyspan.Span type.
> type Span = keyspan.Span
> ```

Should we export these from the `sstable` package, like we did in #1782? Or alternatively we could create a public `pebble/rangekey` package to re-export all the necessary range-key specific types and utilities (including whatever facilities we end up needing [for detecting fragmenting/defragmenting](https://github.com/cockroachdb/cockroach/pull/78085#pullrequestreview-1020274483) within Cockroach.

I'm wary of exporting these types from the `pebble` package when they're never returned or used directly by any of the other exported `pebble` types or functions.

**Review by nicktrav — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1787)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @jbowens)

___
*[`range_keys.go` line 16 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1787#-N5_WUPcBNChDYD6MXpX:-N5a9uf65zH1nW_gY-QP:b-jkykfs) ([raw file](https://github.com/cockroachdb/pebble/blob/06307d92945513bf3d8a46c194b710850fa1daad/range_keys.go#L16)):*
>  create a public pebble/rangekey package

SGTM. Amended this change to create this new package. I also moved the existing range key helpers from `sstable` into this new package.

**Review by jbowens — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1787#-:-N5aTneP3Vcn_V0_fr-M:bnfp4nl)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @jbowens and @nicktrav)

___
*[`rangekey/rangekey.go` line 29 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1787#-N5aTgtD7lo82NlNBhYM:-N5aTgtD7lo82NlNBhYN:b-538pl2) ([raw file](https://github.com/cockroachdb/pebble/blob/81aaa734a14f65247eb36a82be81bbbd92b0a321/rangekey/rangekey.go#L29)):*
> ```Go
> // key. If keysDst is provided, keys will be appended to keysDst to reduce
> // allocations.
> func DecodeRangeKey(
> ```

nit: just `Decode` to avoid the stutter of `rangekey.DecodeRangeKey`?

**Review by nicktrav — COMMENTED** [review]
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1787#-:-N5bUJfi92AC3uSbFwgd:bz5mair)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @jbowens)

___
*[`rangekey/rangekey.go` line 29 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1787#-N5aTgtD7lo82NlNBhYM:-N5bUHwU9vG6rSvBwQRt:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/81aaa734a14f65247eb36a82be81bbbd92b0a321/rangekey/rangekey.go#L29)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

nit: just `Decode` to avoid the stutter of `rangekey.DecodeRangeKey`?
</blockquote></details>

Done.

**Pull request merged**
