### PR TITLE
internal/metamorphic: add range key iteration

### PR DESCRIPTION
**Pull request by jbowens**
**db: fix determinism of limited reverse iteration with range keys**

During limited reverse iteration, the iterator may exceed a limit that is
straddled by a range key. Previously, to ensure that the iterator exposes range
keys that covers the keyspace within the limit, the iterator would not pause at
a limit if there was a covering a range key.

This condition was too broad, because the range key might not cover the
keyspace within the limit. This introduced nondeterminism. An iterator over one
LSM state could stop at a deleted point key beyond the limit but before the
next range key. An iterator over an equivalent LSM state could proceed all the
way to the next range key and surface it without pausing.

**db: move range keys from memtable to global arena atomically**

Previously, when a flush completed, the flush first updated the read state and
then copied range keys from flushed memtables into the global arena. An
iterator that acquired a read state (an operation that does not require D.mu)
and read from it between these two steps would fail to see the flushed range
keys.

This commit adds a temporary closure parameter to d.updateReadStateLocked that
is invoked while holding an exclusive lock on the read state. This ensures the
all readers observe the flushing range keys as either within a memtable or
within the global arena.

**db: avoid levelIter invariant violation on exhausted mergingIter**

The commit b34dbe97d33432dad78f9404983ebeb2cacb7560 solved an issue where the
levelIter's bounds invariants could be violated by cascading tombstone seeks.
That commit solved the issue only for levels that were not the current heap
root. This was sufficient because if the current heap root was exhausted, the
mergingIter was exhausted, and the pebble.Iterator would seek the merging
iterator to reposition it.

The range key interleaving iterator however had different behavior. It expected
to always be able to Next/Prev an exhausted merging iterator onto the

**internal/rangekey: seek exhausted iters when switching directions**

When a point key iterator is exhausted, seek it when switching directions. This
matches pebble.Iterator's treatment of these cases and ensures the range
tombstone cascading seek optimization applies.

**internal/metamorphic: add range key iteration**

Configure the metamorphic NewIter operation to randomly create iterators over
just points, just range keys, or points and range keys. When an iterator is
configured to iterate over both point and range keys, randomly enable range key
masking as well.

This required a few tweaks outside of the metamorphic tests. Previously, during
Open while replaying the WALs, any range keys written to the WAL were dropped
since there's a different code path than ordinary flushes. Also, the
metamorphic tests test some DB restart operations as hard crashes, using the
MemFS's SetIgnoreSyncs method to revert the DB to pre-Close state. This would
cause some WAL replays to fail when adding a range key second time, because the
original keys were not reverted to pre-Close state.

### CODE REVIEW

**Review by jbowens — COMMENTED** [review]
There's at least one bug, likely a legitimate bug within the range-key iterator stack itself, that causes intermittent failures. I'll track that down before merging this.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1567#-:-MxjYTGq3n6JFywcBhsM:b-wqr1io)* status: 0 of 15 files reviewed, all discussions resolved

**Review by nicktrav — APPROVED** [review]
Very nice! And great that we're already getting some hits. :lgtm: 

> Reviewed 15 of 15 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1567#-:-Mxjbd91965whR3FtLHo:b78pw0a)* status: all files reviewed, 2 unresolved discussions (waiting on @jbowens)

___
*[internal/metamorphic/generator.go, line 203 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1567#-MxjYkvS07q8arYopDf4:-MxjYkvS07q8arYopDf5:bd5gf8j) ([raw file](https://github.com/cockroachdb/pebble/blob/6a0dfaf5187c2ac66fb6b7c4c69601315ac93ba2/internal/metamorphic/generator.go#L203)):*
> uniform distribution

Would a typical workload tend to skew towards reading more recent records? Or does using a uniform distribution give us better coverage by potentially looking back further into the suffix-space? I don't have an opinion, just curious.
___
*[internal/metamorphic/generator.go, line 503 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1567#-MxjZjtU3MBORMEV3inr:-MxjZjtU3MBORMEV3ins:b-1xa3wv) ([raw file](https://github.com/cockroachdb/pebble/blob/6a0dfaf5187c2ac66fb6b7c4c69601315ac93ba2/internal/metamorphic/generator.go#L503)):*
> ```Go
> 	p := g.rng.Float64()
> 	switch {
> 	case p < 0.2: // 20% probability
> ```

Could these parameters be metamorphic themselves, to emulate different types of workloads?

**Review by nicktrav — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1567)* status: all files reviewed, 2 unresolved discussions (waiting on @jbowens)

**Review by nicktrav — COMMENTED** [review]
> Reviewed 3 of 3 files at r5, 1 of 1 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1567)* status: all files reviewed, 3 unresolved discussions (waiting on @jbowens)

___
*[-- commits, line 30 at r7](https://reviewable.io/reviews/cockroachdb/pebble/1567#-MxpiCxk6hIh7OoRUbAH):*
nit: ... that cover _the_ keyspace ...?

**Review by jbowens — COMMENTED** [review]
So this turned into a bit of a range-key bug fix omnibus. I'd be happy to split the commits out into separate PRs if that makes review easier. There might be remaining issues, but if there are they're not produced by the metamorphic tests readily and hopefully the nightly will surface them.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1567#-:-Mxq73Hp4FSdImakavQD:bfjvpi8)* status: 1 of 24 files reviewed, 2 unresolved discussions (waiting on @jbowens and @nicktrav)

**Review by nicktrav — APPROVED** [review]
> Reviewed 16 of 16 files at r9, 8 of 8 files at r10, 15 of 15 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1567)* status: all files reviewed, 3 unresolved discussions (waiting on @itsbilal, @jbowens, and @sumeerbhola)

___
*[-- commits, line 32 at r11](https://reviewable.io/reviews/cockroachdb/pebble/1567#-MxqB9tNDqm0yEIuhoh1):*
nit: ensures that

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1567)* status: 2 of 25 files reviewed, 5 unresolved discussions (waiting on @itsbilal, @nicktrav, and @sumeerbhola)

___
*[iterator.go, line 1340 at r9](https://reviewable.io/reviews/cockroachdb/pebble/1567#-MxtgVIJEYSeaFj56SMr:-Mxu3YbyAG72s9xQs516:b-bvykbs) ([raw file](https://github.com/cockroachdb/pebble/blob/1f57a333a1de018d8e1d8911753258dc220545f8/iterator.go#L1340)):*
> ... over a point key beyond ...?

It could also be a interleaved range key start key.

> Could you add something analogous here.

Done.
___
*[iterator.go, line 1343 at r9](https://reviewable.io/reviews/cockroachdb/pebble/1567#-MxtjLlZ-O0U4mEo8dfT:-Mxu3jug7ODrni2Iyvbu:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/1f57a333a1de018d8e1d8911753258dc220545f8/iterator.go#L1343)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Worth saying that the limit is inclusive.

Also, I forgot to put proper method comments on the four public limit methods. While you are here, could you add something.
</blockquote></details>

Done.
___
*[range_keys.go, line 79 at r11](https://reviewable.io/reviews/cockroachdb/pebble/1567#-MxtkquAEVojo-Yaak2m:-Mxu8YPM8wMv9oZRhruh:bqprtju) ([raw file](https://github.com/cockroachdb/pebble/blob/57a1e66072b211a25c7ea648828daa5dbf9320ec/range_keys.go#L79)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

TODO to remove?
</blockquote></details>

Added a TODO to remove this function altogether. I think this particular wart will need to exist until we support persistence of range keys.
___
*[internal/metamorphic/generator.go, line 203 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1567#-MxjYkvS07q8arYopDf4:-Mxu8ey6AQaaXTO9V7TG:bfbhhi8) ([raw file](https://github.com/cockroachdb/pebble/blob/6a0dfaf5187c2ac66fb6b7c4c69601315ac93ba2/internal/metamorphic/generator.go#L203)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

> uniform distribution

Would a typical workload tend to skew towards reading more recent records? Or does using a uniform distribution give us better coverage by potentially looking back further into the suffix-space? I don't have an opinion, just curious.
</blockquote></details>

Yeah, a typical real-world workload would use a recent read-timestamp, resulting in most range keys serving as masks. I think the uniform distribution improves coverage, ensuring we get a mix of masked and unmasked points. 
___
*[internal/rangekey/interleaving_iter.go, line 259 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1567#-Mxtfj9v812uyX_ELbWW:-MxuGV1ZAS87lXuYydkp:bjfz5ao) ([raw file](https://github.com/cockroachdb/pebble/blob/643dba743570a266d7f4756e3af382a1a81762f6/internal/rangekey/interleaving_iter.go#L259)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

could you elaborate on why this change was needed?
I couldn't quite understand based on the commit description.
</blockquote></details>

Updated with two commits that both solve this issue: 2275f3a2f22e3bda49c2853f59d1471c10d842da and b7e242d71e724429a19d225a1b0bdbc48b54b131.

The crux of the problem is that the `levelIter` enforces invariants that all keys returned are within the configured bounds. It's the same problem as https://github.com/cockroachdb/pebble/commit/b34dbe97d33432dad78f9404983ebeb2cacb7560. If the point iterator is at an exhausted position, it's possible the `mergingIter` has a single heap item at a sstable boundary sentinel. The levelIter corresponding to that single heap item might've been seeked past a bound because of a rangedel. Using relative positioning to reposition it would cause it return a key outside the bounds and violate the invariant check.

We don't ever encounter this problem without range keys, because the `pebble.Iterator` never uses relative positioning if the internal iterator is exhausted. It always seeks. So b7e242d71e724429a19d225a1b0bdbc48b54b131 solves the issue by altering the interleaving iterator to also use absolute positioning on _its_ point internal iterator to match `pebble.Iterator`'s behavior (it's also more performant, since we don't need to relative position through all the  points covered by the rangedel). The commit 2275f3a2f22e3bda49c2853f59d1471c10d842da solves it by also altering the merging iterator to seek the level iterator from within the merging iterator.

Unfortunately, I've been unsuccessful in producing a unit test for this case.

**Review by sumeerbhola — COMMENTED** [review]
> Reviewed 1 of 1 files at r15, 2 of 14 files at r16.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1567)* status: 5 of 25 files reviewed, 5 unresolved discussions (waiting on @itsbilal, @jbowens, @nicktrav, and @sumeerbhola)

___
*[internal/rangekey/interleaving_iter.go, line 259 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1567#-Mxtfj9v812uyX_ELbWW:-MxuYAax8BQzzqLmhOjH:b-3jhg8q) ([raw file](https://github.com/cockroachdb/pebble/blob/643dba743570a266d7f4756e3af382a1a81762f6/internal/rangekey/interleaving_iter.go#L259)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

Updated with two commits that both solve this issue: 2275f3a2f22e3bda49c2853f59d1471c10d842da and b7e242d71e724429a19d225a1b0bdbc48b54b131.

The crux of the problem is that the `levelIter` enforces invariants that all keys returned are within the configured bounds. It's the same problem as https://github.com/cockroachdb/pebble/commit/b34dbe97d33432dad78f9404983ebeb2cacb7560. If the point iterator is at an exhausted position, it's possible the `mergingIter` has a single heap item at a sstable boundary sentinel. The levelIter corresponding to that single heap item might've been seeked past a bound because of a rangedel. Using relative positioning to reposition it would cause it return a key outside the bounds and violate the invariant check.

We don't ever encounter this problem without range keys, because the `pebble.Iterator` never uses relative positioning if the internal iterator is exhausted. It always seeks. So b7e242d71e724429a19d225a1b0bdbc48b54b131 solves the issue by altering the interleaving iterator to also use absolute positioning on _its_ point internal iterator to match `pebble.Iterator`'s behavior (it's also more performant, since we don't need to relative position through all the  points covered by the rangedel). The commit 2275f3a2f22e3bda49c2853f59d1471c10d842da solves it by also altering the merging iterator to seek the level iterator from within the merging iterator.

Unfortunately, I've been unsuccessful in producing a unit test for this case.
</blockquote></details>

Thanks for the explanation.
- I think we should try to solve this at the lowest possible level, since this iterator shouldn't have to understand the implementation details of levelIter and mergingIter.
- Could you add a code comment with an example wherever we solve this.

**Review by nicktrav — COMMENTED** [review]
> Reviewed 22 of 22 files at r12, 9 of 9 files at r13, 1 of 1 files at r14, 1 of 1 files at r15, 14 of 14 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1567)* status: all files reviewed, 4 unresolved discussions (waiting on @itsbilal, @jbowens, and @sumeerbhola)

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1567)* status: 9 of 25 files reviewed, 4 unresolved discussions (waiting on @itsbilal, @nicktrav, and @sumeerbhola)

___
*[internal/rangekey/interleaving_iter.go, line 259 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1567#-Mxtfj9v812uyX_ELbWW:-Mxuv4QqA79ApeoDTQtE:btff56k) ([raw file](https://github.com/cockroachdb/pebble/blob/643dba743570a266d7f4756e3af382a1a81762f6/internal/rangekey/interleaving_iter.go#L259)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Thanks for the explanation.
- I think we should try to solve this at the lowest possible level, since this iterator shouldn't have to understand the implementation details of levelIter and mergingIter.
- Could you add a code comment with an example wherever we solve this.

</blockquote></details>

I think the change to the merging iterator is the lowest level possible, but we should still keep the change to the interleaving iterator for consistency with `pebble.Iterator` and the performance benefit of the cascading seeks. I think the existing example in the merging iterator code explains this exact situation. I updated the comment immediately next to the updated code to refer to those examples a few lines up.

**Review by jbowens — COMMENTED** [review]
Looks like I might need to do something about the race builds being slower now... The race build frequently times out.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1567#-:-Mxv8fd753_Lb37KrjAM:b-k0n69y)* status: 9 of 25 files reviewed, 4 unresolved discussions (waiting on @itsbilal, @nicktrav, and @sumeerbhola)

**Review by jbowens — COMMENTED** [review]
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1567#-:-MyDc0ZjCjoE4QGr_Dnq:bz5mair)* status: all files reviewed, 4 unresolved discussions (waiting on @itsbilal and @sumeerbhola)

**Pull request merged**
