### PR TITLE
metamorphic: add support for external ingestions in replicateOp

### PR DESCRIPTION
**Pull request by itsbilal**
This change updates the two-instance metamorphic test to test fast external snapshotting added in #3348.

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3438)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @itsbilal and @stevendanna)

___
*[`metamorphic/ops.go` line 2078 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3438#-NtXU83B7Vy2zDSChiUH:-NtXU83B7Vy2zDSChiUI:bhhyltc) ([raw file](https://github.com/cockroachdb/pebble/blob/e6e86e78c101873bd945433c897c6d96bbbf92f6/metamorphic/ops.go#L2078)):*
> ```Go
> 		return
> 	}
> 	if useExternalIngest {
> ```

Both shared and external can be true..

**Comment by itsbilal** [comment]
*[`metamorphic/ops.go` line 2078 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3438#-NtXU83B7Vy2zDSChiUH:-NtXWpPbDpq4yu8RTgCK:bwdrtat) ([raw file](https://github.com/cockroachdb/pebble/blob/e6e86e78c101873bd945433c897c6d96bbbf92f6/metamorphic/ops.go#L2078)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Both shared and external can be true..
</blockquote></details>

ScanInternal doesn't support passing in both visitors, so we have to pick and choose one path here.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3438)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @itsbilal and @stevendanna)

___
*[`metamorphic/ops.go` line 2078 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3438#-NtXU83B7Vy2zDSChiUH:-NtXYXLV3SAcNuFN8cZQ:b9qlpo9) ([raw file](https://github.com/cockroachdb/pebble/blob/e6e86e78c101873bd945433c897c6d96bbbf92f6/metamorphic/ops.go#L2078)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

ScanInternal doesn't support passing in both visitors, so we have to pick and choose one path here.
</blockquote></details>

Oh, so we'll either copy the shared data or the external data? That's fine. Maybe randomize which path we choose, or prefer the external one since we care about that one more right now.

**Review by itsbilal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3438)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @RaduBerinde and @stevendanna)

___
*[`metamorphic/ops.go` line 2078 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3438#-NtXU83B7Vy2zDSChiUH:-NtXblo35ypb3QyyJhIn:bkfraic) ([raw file](https://github.com/cockroachdb/pebble/blob/e6e86e78c101873bd945433c897c6d96bbbf92f6/metamorphic/ops.go#L2078)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Oh, so we'll either copy the shared data or the external data? That's fine. Maybe randomize which path we choose, or prefer the external one since we care about that one more right now.
</blockquote></details>

Did the preference of external over shared. We'll already get some randomization because we'll be disabling external storage and shared storage in testOptions.

**Review by RaduBerinde — COMMENTED** [review]
:lgtm:  Please run under stress for a while :)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3438#-:-NtXccfbEVKBBNDrFha6:b-w8s4o2)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @itsbilal and @stevendanna)

___
*[`metamorphic/ops.go` line 2078 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3438#-NtXU83B7Vy2zDSChiUH:-NtXcYJQ6rFC7-xBg09S:b-euvz2t) ([raw file](https://github.com/cockroachdb/pebble/blob/e6e86e78c101873bd945433c897c6d96bbbf92f6/metamorphic/ops.go#L2078)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Did the preference of external over shared. We'll already get some randomization because we'll be disabling external storage and shared storage in testOptions.
</blockquote></details>

:thumbsup:  Thanks!

**Comment by itsbilal** [comment]
Sounds good! Ran it for a while and it kept passing. @RaduBerinde mind doing the "approve" checkmark so I can hit the green button?

**Review by RaduBerinde — APPROVED** [review]

**Review by stevendanna — APPROVED** [review]
Thanks for doing this!

**Pull request merged**
