### PR TITLE
compaction: use InterleavingIter to interleave rangedels

### PR DESCRIPTION
**Pull request by jbowens**
Previously, compactions used a temporary `keyspan.InternalIteratorShim` type to
insert range tombstones into the compaction iterator's internal iterator. These
range tombstones were inserted at their start user key and sequence number.

This change adjusts the compaction iterator to use the InterleavingIter type to
interleave range tombstones at the their start keys at the infinite sequence
number. The compaction loop continues to be responsible for adding these
tombstones to the range deletion fragmenter.

Since range deletions are interleaved at the infinite sequence number, this
change also resolves some inconsistent behavior at range deletion start keys.
For example, previously compactions would not combine a MERGE with a later SET
or MERGE at the same sequence number as a range tombstone beginning at the same
user key. Previously the compaction would preserve both unmerged keys as if a
snapshot had prevented the merge because the interleaved RANGEDELs were treated
as beginning a new snapshot stripe. The same oddity occurred when evaluating
whether SETs should become SETWITHDELs.

Future work may consider removing compaction's use of the fragmenter
altogether, since incoming range deletions are already fragmented. The
compaction loop would need to consult the InterleavingIter to know when pending
range deletions should be flushed, and logic to truncate tombstones to sstable
boundaries would still be required.

### CODE REVIEW

**Review by itsbilal — APPROVED** [review]
:lgtm:

> Reviewed 14 of 14 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1659#-:-N0WyYXH2ddQruoJc9UM:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @jbowens)

___
*[`compaction.go` line 366 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1659#-N0WqkpFEQpX2zwvJy12:-N0WqkpFEQpX2zwvJy13:bcfytbg) ([raw file](https://github.com/cockroachdb/pebble/blob/7f2a5865e8654bb691ba61583adf60686f8eb177/compaction.go#L366)):*
> ```Go
> 	// Referenced by `compactionIter` which uses it to check whether keys are deleted.
> 	rangeDelFrag keyspan.Fragmenter
> 	// The range deletion tombstone interleaving iterator that interleaves range
> ```

Nit: probably worth mentioning here that this iterator is the outermost returned iterator if there are any rangedels.
___
*[`compaction_iter.go` line 458 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1659#-N0Wy-hf1zEOmtJh7tPU:-N0Wy-hf1zEOmtJh7tPV:b-ky7w8g) ([raw file](https://github.com/cockroachdb/pebble/blob/8b3db52b6e3cfc631ac3476aecd7f51fe8f67145/compaction_iter.go#L458)):*
> ```Go
> 	i.iterKey, i.iterValue = i.iter.Next()
> 	// We should never see an exclusive sentinel in the compaction input.
> 	if i.iterKey != nil && i.iterKey.IsExclusiveSentinel() {
> ```

If I understand this correctly, we had to remove this because every key will appear like an exclusive sentinel, correct?

**Review by nicktrav — COMMENTED** [review]
> Reviewed 14 of 14 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1659)* status: all files reviewed, 4 unresolved discussions (waiting on @jbowens)

___
*[`compaction_iter.go` line 495 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1659#-N0Ce8dj6z8NoSo4j5JP:-N0Ccuse00nNeqUFxBXr:b-kn7idv) ([raw file](https://github.com/cockroachdb/pebble/blob/7f2a5865e8654bb691ba61583adf60686f8eb177/compaction_iter.go#L495)):*
> ```Go
> 	switch key.Kind() {
> 	case InternalKeyKindRangeDelete:
> 		// Range tombstones are always interleaved at the infinite sequence
> ```

This didn't immediately sink in. Could the first sentence end with something like ", and therefore a range tombstone (if present) will be the first key encountered.". This would underscore the fact that we should never see a range del in the switch statement.
___
*[`testdata/compaction_iter` line 476 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1659#-N0WTiIv7ZpkuEWf75MG:-N0WTiIv7ZpkuEWf75MH:b-bagi9n) ([raw file](https://github.com/cockroachdb/pebble/blob/8b3db52b6e3cfc631ac3476aecd7f51fe8f67145/testdata/compaction_iter#L476)):*
> ```
> c-d#3
> d-e#2
> e-f#1
> ```

The last fragment is gone? What's the explanation there?

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1659)* status: all files reviewed, 3 unresolved discussions (waiting on @itsbilal, @jbowens, and @nicktrav)

___
*[`compaction_iter.go` line 458 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1659#-N0Wy-hf1zEOmtJh7tPU:-N0gskOn82W3eywov_PR:b-lxumbx) ([raw file](https://github.com/cockroachdb/pebble/blob/8b3db52b6e3cfc631ac3476aecd7f51fe8f67145/compaction_iter.go#L458)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

If I understand this correctly, we had to remove this because every key will appear like an exclusive sentinel, correct?
</blockquote></details>

Yeah, that's right.
___
*[`testdata/compaction_iter` line 476 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1659#-N0WTiIv7ZpkuEWf75MG:-N0gtG4X0_nQclpLpKjF:bwhs79i) ([raw file](https://github.com/cockroachdb/pebble/blob/8b3db52b6e3cfc631ac3476aecd7f51fe8f67145/testdata/compaction_iter#L476)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

The last fragment is gone? What's the explanation there?
</blockquote></details>

We don't get as far through the input tombstones with the same number of `next`s, a consequence of the `MergingIter` fragmenting before the range deletions are interleaved. In the old test file, we encountered all three unfragmented tombstones `a-d`, `b-e` and `c-f`. Now we encounter the _fragments_ `a-b`, `b-c`, `c-d`, `d-e`. A subsequent next would surface `e-f`.

**Review by nicktrav — APPROVED** [review]
:lgtm:

> Reviewed 4 of 5 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1659#-:-N0h3b6UCzrRIUvvbvYF:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @itsbilal and @jbowens)

___
*[`testdata/compaction_iter` line 476 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1659#-N0WTiIv7ZpkuEWf75MG:-N0gzVsy51lzhi4qqWEp:b7pcw3) ([raw file](https://github.com/cockroachdb/pebble/blob/8b3db52b6e3cfc631ac3476aecd7f51fe8f67145/testdata/compaction_iter#L476)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

We don't get as far through the input tombstones with the same number of `next`s, a consequence of the `MergingIter` fragmenting before the range deletions are interleaved. In the old test file, we encountered all three unfragmented tombstones `a-d`, `b-e` and `c-f`. Now we encounter the _fragments_ `a-b`, `b-c`, `c-d`, `d-e`. A subsequent next would surface `e-f`. 
</blockquote></details>

Ah. So those fragments aren't in the fragmenter yet as they haven't been interleaved. And given that `tombstones` flushes the current state of the fragmenter, we don't see it. :thumbsup: 

What do you think about either having one test case that "nexts" through all fragments for completeness, or updating the test cases where we removed `e-f` in this PR to add an additional "next" operation so that `e-f` is emitted? Or just a comment. No strong opinion.

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1659)* status: 9 of 16 files reviewed, 1 unresolved discussion (waiting on @itsbilal and @nicktrav)

___
*[`testdata/compaction_iter` line 476 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1659#-N0WTiIv7ZpkuEWf75MG:-N1OqWLMCNUolevN_-z7:bs5mf9x) ([raw file](https://github.com/cockroachdb/pebble/blob/8b3db52b6e3cfc631ac3476aecd7f51fe8f67145/testdata/compaction_iter#L476)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

Ah. So those fragments aren't in the fragmenter yet as they haven't been interleaved. And given that `tombstones` flushes the current state of the fragmenter, we don't see it. :thumbsup: 

What do you think about either having one test case that "nexts" through all fragments for completeness, or updating the test cases where we removed `e-f` in this PR to add an additional "next" operation so that `e-f` is emitted? Or just a comment. No strong opinion.
</blockquote></details>

Updated to emit `e-f` in this instance. I want to preserve a combination of cases that exhaust input tombstones and case that do not.

**Review by nicktrav — APPROVED** [review]
Did another pass of the latest revs. :thumbsup: 

> Reviewed 7 of 7 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1659#-:-N2JBLcIDN3cAeXi5e_a:bz3lfhl)* status: all files reviewed, 1 unresolved discussion (waiting on @itsbilal and @sumeerbhola)

**Comment by jbowens** [comment]
This was rewritten and completed in #3219.

**Pull request closed without merging**
