### PR TITLE
sstable: introduce objstorage interface

### PR DESCRIPTION
**Pull request by RaduBerinde**
This change introduces `objstorage.Provider` which replaces uses of `vfs.FS` / `vfs.File` in sstable code.

We pull out the write-buffering and read-ahead logic into the Provider implementation. This simplifies the sstable reader code considerably.

The provider will be extended to support shared storage, along the following lines:
 - define a new `SharedObjectStore` interface
 - the Provider stores a `SharedObjectStore` instance (alongside the local vfs.FS)
 - the Provider maintains internally a mapping from `FileNum` to backend type (local vs shared). Methods like `OpenForReading` use the mapping to talk to the correct backend.
 - `Create` needs to be augmented with extra information (e.g. LSM level?) to allow the provider to decide where a new object is created

### CODE REVIEW

**Comment by RaduBerinde** [comment]
See #2254 for comments on an earlier version of this.

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
(still reading)

> Reviewed 5 of 36 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2267#-:-NM_SOLo63bI381swQTy:bm2k0ew)* status: 5 of 36 files reviewed, 4 unresolved discussions (waiting on @itsbilal and @RaduBerinde)

___
*[`-- commits` line 18 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2267#-NM_Ht2J-zP3gRMWdeWI):*
We can just expect the caller to specify whether it wants it created locally or shareable.
The input to that decision can include what key span the caller expects to write to this sstable, so it is probably best not to complicate the interface and keep the decision making in the caller.
___
*[`objstorage/provider.go` line 24 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2267#-NM_Oqyt8fXcUtmfQTMi:-NM_Oqyt8fXcUtmfQTMj:b4gno62) ([raw file](https://github.com/cockroachdb/pebble/blob/08787acfecd8d3e4b363ac3aff78d0345f5aa655/objstorage/provider.go#L24)):*
> ```Go
> 	st Settings
> 
> 	// TODO(radu): to we support shared storage as well, this object will need to
> ```

should this say: when we support ...
___
*[`objstorage/readahead.go` line 17 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2267#-NM_QQKo5UEgZOVjFD9r:-NM_QQKo5UEgZOVjFD9s:b-t1b4sx) ([raw file](https://github.com/cockroachdb/pebble/blob/08787acfecd8d3e4b363ac3aff78d0345f5aa655/objstorage/readahead.go#L17)):*
> ```Go
> 	maxReadaheadSize     = 256 << 10 /* 256KB */
> )
> ```

I ignored this file assuming this is code movement. Is that a fair assumption?
___
*[`objstorage/vfs_readable.go` line 160 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2267#-NM_RtCs7XGJcvqX_iLr:-NM_RtCs7XGJcvqX_iLs:b-uipnsh) ([raw file](https://github.com/cockroachdb/pebble/blob/08787acfecd8d3e4b363ac3aff78d0345f5aa655/objstorage/vfs_readable.go#L160)):*
> ```Go
> 	size int64
> 
> 	rh NoopReadaheadHandle
> ```

Isn't our current code able to do readahead (not the OS-level one) without having a file descriptor?
We now seem to be calling `newGenericFileReadable(file)` if there isn't a file descriptor.

**Comment by RaduBerinde** [comment]
*[`objstorage/vfs_readable.go` line 160 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2267#-NM_RtCs7XGJcvqX_iLr:-NM__sOO2VjLd24uZPxn:b-c8id6b) ([raw file](https://github.com/cockroachdb/pebble/blob/08787acfecd8d3e4b363ac3aff78d0345f5aa655/objstorage/vfs_readable.go#L160)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Isn't our current code able to do readahead (not the OS-level one) without having a file descriptor?
We now seem to be calling `newGenericFileReadable(file)` if there isn't a file descriptor.
</blockquote></details>

Not as far as I can tell - the only thing the (non-OS-level) readahead code does is call `Prefetch` which requires a descriptor.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2267)* status: 5 of 36 files reviewed, 4 unresolved discussions (waiting on @itsbilal and @sumeerbhola)

___
*[`-- commits` line 18 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2267#-NM_Ht2J-zP3gRMWdeWI):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

We can just expect the caller to specify whether it wants it created locally or shareable.
The input to that decision can include what key span the caller expects to write to this sstable, so it is probably best not to complicate the interface and keep the decision making in the caller.
</blockquote></details>

Done.
___
*[`objstorage/provider.go` line 24 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2267#-NM_Oqyt8fXcUtmfQTMi:-NM_aa0JCsDukDKgxFNN:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/08787acfecd8d3e4b363ac3aff78d0345f5aa655/objstorage/provider.go#L24)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

should this say: when we support ...
</blockquote></details>

Done.
___
*[`objstorage/readahead.go` line 17 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2267#-NM_QQKo5UEgZOVjFD9r:-NM_aa__1JanWxhz8wC4:bb77ufg) ([raw file](https://github.com/cockroachdb/pebble/blob/08787acfecd8d3e4b363ac3aff78d0345f5aa655/objstorage/readahead.go#L17)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I ignored this file assuming this is code movement. Is that a fair assumption?
</blockquote></details>

Yes.

**Review by itsbilal — COMMENTED** [review]
Looks like this is mostly in great shape! Just some minor comments.

> Reviewed 29 of 36 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2267#-:-NMaGHS6AM8TQSKWOsCE:b-vl6dpb)* status: all files reviewed, 6 unresolved discussions (waiting on @RaduBerinde and @sumeerbhola)

___
*[`table_cache.go` line 927 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2267#-NMaElD7Bz_s0vEVbFWk:-NMaElD7Bz_s0vEVbFWl:b-1diuu8) ([raw file](https://github.com/cockroachdb/pebble/blob/b7bfb695814ca55432a41ff0d58b2738911d39f0/table_cache.go#L927)):*
> ```Go
> func (v *tableCacheValue) load(meta *fileMetadata, c *tableCacheShard, dbOpts *tableCacheOpts) {
> 	// Try opening the file first.
> 	provider := objstorage.New(objstorage.DefaultSettings(dbOpts.fs, dbOpts.dirname))
> ```

it should be a pretty simple change to move this `provider` to `dbOpts` ?
___
*[`objstorage/vfs_readable.go` line 90 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2267#-NMaGlDb221QINGcor8i:-NMaGlDb221QINGcor8j:b-lleeov) ([raw file](https://github.com/cockroachdb/pebble/blob/b7bfb695814ca55432a41ff0d58b2738911d39f0/objstorage/vfs_readable.go#L90)):*
> ```Go
> var readaheadHandlePool = sync.Pool{
> 	New: func() interface{} {
> 		i := &readaheadHandle{}
> ```

Since these will only exist in the context of `singleLevelIterator`, which is already pooled, thoughts on making this an exported struct, adding it to the `singleLevelIterator` struct and doing some mild interface-no-nos by having an `InitForReadable(r Readable)` instead of the current `readable.NewReadaheadHandle()` ? It's less clean but reduces one pool. It would necessitate more "does this file support readahead, if not just do nothing / relay the read as-is" if-statements in the methods below because this handle would have to handle all readables, and that alone is enough of a reason to prefer the current approach, so feel free to dismiss this suggestion. Just throwing the idea around since I don't have much insight into the overhead of pools.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2267)* status: all files reviewed, 6 unresolved discussions (waiting on @itsbilal and @sumeerbhola)

___
*[`table_cache.go` line 927 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2267#-NMaElD7Bz_s0vEVbFWk:-NMag16348qdu0ZBNZlr:b2z6nlg) ([raw file](https://github.com/cockroachdb/pebble/blob/b7bfb695814ca55432a41ff0d58b2738911d39f0/table_cache.go#L927)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

it should be a pretty simple change to move this `provider` to `dbOpts` ?
</blockquote></details>

Yes, I'm working on a follow-up change that does this (and removes `fs` and `dirname`, updating the rest of the code to use the provider).
___
*[`objstorage/vfs_readable.go` line 90 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2267#-NMaGlDb221QINGcor8i:-NMagQO3-cGj79MAhdjB:b-u0lpnj) ([raw file](https://github.com/cockroachdb/pebble/blob/b7bfb695814ca55432a41ff0d58b2738911d39f0/objstorage/vfs_readable.go#L90)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Since these will only exist in the context of `singleLevelIterator`, which is already pooled, thoughts on making this an exported struct, adding it to the `singleLevelIterator` struct and doing some mild interface-no-nos by having an `InitForReadable(r Readable)` instead of the current `readable.NewReadaheadHandle()` ? It's less clean but reduces one pool. It would necessitate more "does this file support readahead, if not just do nothing / relay the read as-is" if-statements in the methods below because this handle would have to handle all readables, and that alone is enough of a reason to prefer the current approach, so feel free to dismiss this suggestion. Just throwing the idea around since I don't have much insight into the overhead of pools.
</blockquote></details>

Pools are very fast in the steady-state - each CPU maintains its own cache of objects so the fast path is very fast. I doubt removing the pool would be noticeable here.

I did ponder whether to make the handle a struct.. In the end it feels like as we will add one more implementation for shared storage, we'd benefit from having an interface.. In any case, it's easy to change this later if we change our mind.

**Review by itsbilal — APPROVED** [review]
:lgtm: though I'm not sure if @sumeerbhola has more stuff to suggest here.

> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2267#-:-NMeHRZCETYcRUm4on4d:bc14u8h)* status: all files reviewed, 4 unresolved discussions (waiting on @sumeerbhola)

___
*[`table_cache.go` line 927 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2267#-NMaElD7Bz_s0vEVbFWk:-NMeHLH65Kgd8Z3sTPB_:btozu5y) ([raw file](https://github.com/cockroachdb/pebble/blob/b7bfb695814ca55432a41ff0d58b2738911d39f0/table_cache.go#L927)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Yes, I'm working on a follow-up change that does this (and removes `fs` and `dirname`, updating the rest of the code to use the provider).
</blockquote></details>

Sounds good! Looking forward to that cleanup then.
___
*[`objstorage/vfs_readable.go` line 90 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2267#-NMaGlDb221QINGcor8i:-NMeHfbZD5z3Ow8rVW8O:b-gb5266) ([raw file](https://github.com/cockroachdb/pebble/blob/b7bfb695814ca55432a41ff0d58b2738911d39f0/objstorage/vfs_readable.go#L90)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Pools are very fast in the steady-state - each CPU maintains its own cache of objects so the fast path is very fast. I doubt removing the pool would be noticeable here.

I did ponder whether to make the handle a struct.. In the end it feels like as we will add one more implementation for shared storage, we'd benefit from having an interface.. In any case, it's easy to change this later if we change our mind.
</blockquote></details>

Makes sense, let's stick with this approach then

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 24 of 36 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2267#-:-NMebOTtEQrrUhSeZLu8:b593w57)* status: all files reviewed, 5 unresolved discussions (waiting on @RaduBerinde)

___
*[`sstable/reader.go` line 543 at r4](https://reviewable.io/reviews/cockroachdb/pebble/2267#-NMeUHCp6U6PQ3ZbxQnP:-NMeUHCp6U6PQ3ZbxQnQ:bozqghw) ([raw file](https://github.com/cockroachdb/pebble/blob/877229b32ff893a9264534dddb016b495959c4a2/sstable/reader.go#L543)):*
> ```Go
> //
> // TODO(radu, sumeer): we should use a ReadaheadHandle here, separate from the
> // ReadHandle for the data blocks. Especially for the compaction case, where we
> ```

nit: s/ReadHandle/ReadaheadHandle/

This PR will make this TODO trivial since we can simply create a new ReadaheadHandle via `NewReadaheadHandle()`.

**Review by RaduBerinde — COMMENTED** [review]
TFTRs! I consider this ready to merge but I will hold off on the merge for now to prevent interfering with the work in #2271.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2267#-:-NMebrxc3K5uCX6Cn_S4:b-92jvb2)* status: 35 of 36 files reviewed, 4 unresolved discussions (waiting on @itsbilal and @sumeerbhola)

___
*[`sstable/reader.go` line 543 at r4](https://reviewable.io/reviews/cockroachdb/pebble/2267#-NMeUHCp6U6PQ3ZbxQnP:-NMec4OhCqelpztciYou:bt2vr1b) ([raw file](https://github.com/cockroachdb/pebble/blob/877229b32ff893a9264534dddb016b495959c4a2/sstable/reader.go#L543)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nit: s/ReadHandle/ReadaheadHandle/

This PR will make this TODO trivial since we can simply create a new ReadaheadHandle via `NewReadaheadHandle()`.
</blockquote></details>

Fixed.

**Comment by RaduBerinde** [comment]
Updated. The only recent change was removing the `fd` from `fileReadable`; first commit is #2293.

**Pull request merged**
