### PR TITLE
travis: upgrade to go 1.15 for testing

### PR DESCRIPTION
**Pull request by otan**

### CODE REVIEW

**Review by petermattis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/983#-:-MLTQC3O60b28n5JOsRy:bnfp4nl)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @otan)

___
*[.travis.yml, line 17 at r1](https://reviewable.io/reviews/cockroachdb/pebble/983#-MLTPymY5DR-CMJpaDrK:-MLTPymY5DR-CMJpaDrL:b-8timrc) ([raw file](https://github.com/cockroachdb/pebble/blob/0a9477c080e09656fccc31f9731b2be0c9be0e98/.travis.yml#L17)):*
> ```YAML
> matrix:
>   include:
>     - name: "go1.13.x-linux"
> ```

Please bump this to go1.14. My general strategy here is to run the full test suite on the current Go release, and have one build config for the previous Go release.

**Comment by otan** [comment]
___
*[.travis.yml, line 17 at r1](https://reviewable.io/reviews/cockroachdb/pebble/983#-MLTPymY5DR-CMJpaDrK:-MLTSMcSCuJTF6M-CsIy:b-1sxy9a) ([raw file](https://github.com/cockroachdb/pebble/blob/0a9477c080e09656fccc31f9731b2be0c9be0e98/.travis.yml#L17)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Please bump this to go1.14. My general strategy here is to run the full test suite on the current Go release, and have one build config for the previous Go release.
</blockquote></details>

done! i kept 1.13 here since CRDB is 1.13.

**Comment by otan** [comment]
___
*[.travis.yml, line 17 at r1](https://reviewable.io/reviews/cockroachdb/pebble/983#-MLTPymY5DR-CMJpaDrK:-MLTSdDd2rqCIC2KSUMv:b2pg9ul) ([raw file](https://github.com/cockroachdb/pebble/blob/0a9477c080e09656fccc31f9731b2be0c9be0e98/.travis.yml#L17)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

done! i kept 1.13 here since CRDB is 1.13.
</blockquote></details>

(sorry, i mean I originally kept 1.13)

**Review by petermattis — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/983)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @otan)

___
*[.travis.yml, line 17 at r1](https://reviewable.io/reviews/cockroachdb/pebble/983#-MLTPymY5DR-CMJpaDrK:-MLTTuLY9XZwECKOZFaz:b-9tn3kw) ([raw file](https://github.com/cockroachdb/pebble/blob/0a9477c080e09656fccc31f9731b2be0c9be0e98/.travis.yml#L17)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

(sorry, i mean I originally kept 1.13)
</blockquote></details>

We're changing that soon, though, right?

**Comment by otan** [comment]
___
*[.travis.yml, line 17 at r1](https://reviewable.io/reviews/cockroachdb/pebble/983#-MLTPymY5DR-CMJpaDrK:-MLUScvKDy5_9vpVuzXQ:b-fsshqm) ([raw file](https://github.com/cockroachdb/pebble/blob/0a9477c080e09656fccc31f9731b2be0c9be0e98/.travis.yml#L17)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

We're changing that soon, though, right?
</blockquote></details>

if i can get cross compile to work ... :P

**Pull request merged**
