### PR TITLE
db: create new type for file numbers on disk

### PR DESCRIPTION
**Pull request by bananabrick**
Create a DiskFileNum type for file numbers which actually exist
on disk. This helps ensure that we don't perform reads on virtual
sstable file numbers.

### CODE REVIEW

**Review by bananabrick — COMMENTED** [review]
There's some definitions in `base/filenames.go` which will help with the rest of the review. The rest of it is mechanical. The choice was basically whether to turn a `FileNum` to a `DiskFileNum` or not.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2434#-:-NShHzMDBqeleNsnqSUh:b-ohq29f)* status: 0 of 56 files reviewed, all discussions resolved (waiting on @jbowens)

**Review by RaduBerinde — COMMENTED** [review]
`objstorage/` part LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2434#-:-NShhWHnAKvEwOKU23Jp:bdfibtd)* status: 0 of 56 files reviewed, 4 unresolved discussions (waiting on @bananabrick and @jbowens)

___
*[`internal/base/filenames.go` line 38 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2434#-NShehdTCb6lPJR20FGa:-NShehdTCb6lPJR20FGb:buh6ez1) ([raw file](https://github.com/cockroachdb/pebble/blob/f6214587cc4d03ac283ac182579f186ede3a0fe3/internal/base/filenames.go#L38)):*
> ```Go
> // the FileNum actually exists on disk.
> type DiskFileNum struct {
> 	Val uint64
> ```

Why is Val public? It should be read with `.FileNum()` and it should be written via `FileNum.DiskFileNum()` (or we can add a `MakeDiskFileNum(fn FileNum)` for convenience).

Also, the field should have type `FileNum` instead of `uint64`.
___
*[`internal/base/filenames.go` line 87 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2434#-NShf9DIB6Rb6nlRfV7q:-NShf9DIB6Rb6nlRfV7r:b-o2prod) ([raw file](https://github.com/cockroachdb/pebble/blob/f6214587cc4d03ac283ac182579f186ede3a0fe3/internal/base/filenames.go#L87)):*
> ```Go
> 
> // MakeFilepath builds a filepath from components.
> func MakeFilepath(fs vfs.FS, dirname string, fileType FileType, rh DiskFileNum) string {
> ```

[nit] `dfn` or `n` instead of `rh`?
___
*[`internal/base/filenames.go` line 144 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2434#-NShf6Ar8vk3s7zSElqn:-NShf6Ar8vk3s7zSElqo:b-pgguu9) ([raw file](https://github.com/cockroachdb/pebble/blob/f6214587cc4d03ac283ac182579f186ede3a0fe3/internal/base/filenames.go#L144)):*
> ```Go
> }
> 
> func parseReadHandle(s string) (rh DiskFileNum, ok bool) {
> ```

[nit] parseDiskFileNum?
___
*[`objstorage/objstorage.go` line 109 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2434#-NShhAvp2hpfMZkLnx-O:-NShhAvq2p3xSGNSAVcC:bnc8bbx) ([raw file](https://github.com/cockroachdb/pebble/blob/f6214587cc4d03ac283ac182579f186ede3a0fe3/objstorage/objstorage.go#L109)):*
> ```Go
> 		// CreatorID identifies the DB instance that originally created the object.
> 		CreatorID CreatorID
> 		// CreatedFileNum is the identifier for the object within the context of the
> ```

I think this should stay `Creator` (it's the filenum in the creator's DB)

**Review by jbowens — COMMENTED** [review]
> Reviewed 25 of 56 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2434)* status: 25 of 56 files reviewed, 9 unresolved discussions (waiting on @bananabrick and @RaduBerinde)

___
*[`checkpoint.go` line 263 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2434#-NSksQt79SSkzVIPOV5F:-NSksQt79SSkzVIPOV5G:be2vdux) ([raw file](https://github.com/cockroachdb/pebble/blob/f6214587cc4d03ac283ac182579f186ede3a0fe3/checkpoint.go#L263)):*
> ```Go
> 
> 	var excludedFiles map[deletedFileEntry]*fileMetadata
> 	// Set of FileBacking.ReadHandle which will be required by virtual sstables in
> ```

Ah, is "ReadHandle" the origin of the `rh` local variable naming?
___
*[`compaction.go` line 2039 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2434#-NSkt1te5TL2pru1vJIM:-NSkt1te5TL2pru1vJIN:b2pmlzg) ([raw file](https://github.com/cockroachdb/pebble/blob/f6214587cc4d03ac283ac182579f186ede3a0fe3/compaction.go#L2039)):*
> ```Go
> 				// been set yet. So, we directly use the FileNum. Since these
> 				// files were generated as compaction outputs, these must be
> 				// physical files on disk.
> ```

nit: I suspect in the future this won't hold (eg, after implementing #389), so I think it's worth caveating the comment.
___
*[`compaction.go` line 2550 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2434#-NSkuDNvAZnR16migVJj:-NSkuDNw73KHcex1N3u9:b-iipjm8) ([raw file](https://github.com/cockroachdb/pebble/blob/f6214587cc4d03ac283ac182579f186ede3a0fe3/compaction.go#L2550)):*
> ```Go
> 				// been set yet. So, we directly use the FileNum. Since these
> 				// files were generated as compaction outputs, these must be
> 				// physical files on disk.
> ```

nit: ditto
___
*[`compaction.go` line 3337 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2434#-NSkseFb2ztzX7uBjPHF:-NSkseFb2ztzX7uBjPHG:btgacia) ([raw file](https://github.com/cockroachdb/pebble/blob/f6214587cc4d03ac283ac182579f186ede3a0fe3/compaction.go#L3337)):*
> ```Go
> 
> 	for _, filename := range list {
> 		fileType, readHandle, ok := base.ParseFilename(d.opts.FS, filename)
> ```

s/readHandle/diskFileNum/
___
*[`internal/base/filenames.go` line 38 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2434#-NShehdTCb6lPJR20FGa:-NSksFjF1CTetc40VdCa:b32v57) ([raw file](https://github.com/cockroachdb/pebble/blob/f6214587cc4d03ac283ac182579f186ede3a0fe3/internal/base/filenames.go#L38)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Why is Val public? It should be read with `.FileNum()` and it should be written via `FileNum.DiskFileNum()` (or we can add a `MakeDiskFileNum(fn FileNum)` for convenience).

Also, the field should have type `FileNum` instead of `uint64`.
</blockquote></details>

+1
___
*[`internal/base/filenames.go` line 64 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2434#-NSksI3h3l0VRGdAILI_:-NSksI3h3l0VRGdAILIa:begg8hl) ([raw file](https://github.com/cockroachdb/pebble/blob/f6214587cc4d03ac283ac182579f186ede3a0fe3/internal/base/filenames.go#L64)):*
> ```Go
> 
> // MakeFilename builds a filename from components.
> func MakeFilename(fileType FileType, rh DiskFileNum) string {
> ```

I noticed `rh` used in a few places here. what's its meaning?
___
*[`internal/base/filenames.go` line 144 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2434#-NShf6Ar8vk3s7zSElqn:-NSksr1c1CNYS2gJjCGi:b32v57) ([raw file](https://github.com/cockroachdb/pebble/blob/f6214587cc4d03ac283ac182579f186ede3a0fe3/internal/base/filenames.go#L144)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] parseDiskFileNum?
</blockquote></details>

+1

**Review by bananabrick — COMMENTED** [review]
Thanks. I think I got all the read handle references.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2434#-:-NSm7tCNBCZu1VCgs4uu:b-6vxj0m)* status: 13 of 56 files reviewed, 3 unresolved discussions (waiting on @jbowens and @RaduBerinde)

___
*[`checkpoint.go` line 263 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2434#-NSksQt79SSkzVIPOV5F:-NSldG0a0N6Lzvs4sQWh:bngmj1q) ([raw file](https://github.com/cockroachdb/pebble/blob/f6214587cc4d03ac283ac182579f186ede3a0fe3/checkpoint.go#L263)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

Ah, is "ReadHandle" the origin of the `rh` local variable naming?
</blockquote></details>

Yea. I missed a couple of places.
___
*[`compaction.go` line 3337 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2434#-NSkseFb2ztzX7uBjPHF:-NSlewzUBitJ7OAtpNZQ:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/f6214587cc4d03ac283ac182579f186ede3a0fe3/compaction.go#L3337)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

s/readHandle/diskFileNum/
</blockquote></details>

Done.
___
*[`internal/base/filenames.go` line 64 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2434#-NSksI3h3l0VRGdAILI_:-NSlfd0m67iv-WVYWkP4:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/f6214587cc4d03ac283ac182579f186ede3a0fe3/internal/base/filenames.go#L64)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

I noticed `rh` used in a few places here. what's its meaning?
</blockquote></details>

Done.

**Comment by RaduBerinde** [comment]
*[`db.go` line 1866 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2434#-NSwADCu2kmeub4PKBzv:-NSwADCu2kmeub4PKBzw:b77h6fg) ([raw file](https://github.com/cockroachdb/pebble/blob/24a70158f9a3767fb1ec53d547de25f0c9f2f25d/db.go#L1866)):*
> ```Go
> 			}
> 			destTables[j].Virtual = m.Virtual
> 			destTables[j].BackingSSTNum = m.FileBacking.DiskFileNum.FileNum()
> ```

Should we make BackingSSTNum a DiskFileNum?

**Pull request merged**
