### PR TITLE
db_test: Add a unit test to exercise memtable/ingestion inversion

### PR DESCRIPTION
**Pull request by itsbilal**
This change adds a unit test that utilizes the EventListener to
slow down compactions/flushes to reproduce https://github.com/cockroachdb/cockroach/issues/101896.

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
Interesting approach!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2508#-:-NU87DXk-ZIPfi_fp6Ly:bfmwbf0)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @itsbilal and @sumeerbhola)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2508#-NU849zZCevz4LdbSIZ9):*
This seems stale (no hooks used)
___
*[`db_test.go` line 1377 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2508#-NU84WghBrg2b3uQka_9:-NU84WghBrg2b3uQka_A:bken3fb) ([raw file](https://github.com/cockroachdb/pebble/blob/ff930a8664f8a5e1fd5a02ae705c384134e988d8/db_test.go#L1377)):*
> ```Go
> }
> 
> func TestMemtableIngestInversion(t *testing.T) {
> ```

[nit] It would be useful to explain the high level approach, namely that we will stall completion of certain compactions in the `TableCreated` callback
___
*[`db_test.go` line 1394 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2508#-NU85h2M4IsUQ1MzKAFj:-NU85h2M4IsUQ1MzKAFk:b-ybpxsf) ([raw file](https://github.com/cockroachdb/pebble/blob/ff930a8664f8a5e1fd5a02ae705c384134e988d8/db_test.go#L1394)):*
> ```Go
> 	// intra-L0 compaction and 2 means block the next flush (as flushes have
> 	// a -1 start level).
> 	var nextBlockedCompaction int32
> ```

Why are we mixing mutexes and atomics? Can't everything be protected by the mutex? It would help to put all this state in a separate struct with a few helper methods.
___
*[`db_test.go` line 1397 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2508#-NU84gSR3mL9vHYQrUl3:-NU84gSR3mL9vHYQrUl4:b-3wz5ku) ([raw file](https://github.com/cockroachdb/pebble/blob/ff930a8664f8a5e1fd5a02ae705c384134e988d8/db_test.go#L1397)):*
> ```Go
> 	var el EventListener
> 	el.EnsureDefaults(DefaultLogger)
> 	nextSem := make(chan chan struct{}, 1)
> ```

[nit] This channel of channels deserves a comment. Btw given that we're only blocking one thing at a time, we could use the same fixed "resume" channel instead of creating a new one each time.
___
*[`db_test.go` line 1398 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2508#-NU87bSJDeoYJzxIiJtv:-NU87bSJDeoYJzxIiJtw:b-6g3g4) ([raw file](https://github.com/cockroachdb/pebble/blob/ff930a8664f8a5e1fd5a02ae705c384134e988d8/db_test.go#L1398)):*
> ```Go
> 	el.EnsureDefaults(DefaultLogger)
> 	nextSem := make(chan chan struct{}, 1)
> 	blockedCompactions := make(map[int]bool)
> ```

Unless I'm missing something, it seems that this map never has more than 1 entry that is `true`, is this right? If yes, we can just make it a single `blockedJobID`
___
*[`db_test.go` line 1463 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2508#-NU88GXu2xibG0tTNOgf:-NU88GXu2xibG0tTNOgg:b-a20ywp) ([raw file](https://github.com/cockroachdb/pebble/blob/ff930a8664f8a5e1fd5a02ae705c384134e988d8/db_test.go#L1463)):*
> ```Go
> 	// compactions later on.
> 	atomic.StoreInt32(&nextBlockedCompaction, 3)
> 	timeoutSem := time.After(1 * time.Second)
> ```

We should move this timeout to a constant (it's used multiple times), and make it bigger (we see even simpler stuff go over all the time, for reference CRDB's SucceedsSoon is 45s).
___
*[`db_test.go` line 1475 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2508#-NU86t6YEefOGJwOrrXW:-NU86t6YEefOGJwOrrXX:b3si122) ([raw file](https://github.com/cockroachdb/pebble/blob/ff930a8664f8a5e1fd5a02ae705c384134e988d8/db_test.go#L1475)):*
> ```Go
> 			t.Fatal("did not get blocked on an LBase compaction")
> 		default:
> 			require.NoError(t, d.Set([]byte("b"), []byte("foo"), nil))
> ```

This is a very hot loop.. might make sense to add a short sleep.

**Review by itsbilal — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2508#-:-NU8ZAyO008s7srLswcE:b-814g8k)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @RaduBerinde and @sumeerbhola)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2508#-NU849zZCevz4LdbSIZ9):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This seems stale (no hooks used)
</blockquote></details>

Done.
___
*[`db_test.go` line 1377 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2508#-NU84WghBrg2b3uQka_9:-NU8Xb0x2ZV04WVn5_SN:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/ff930a8664f8a5e1fd5a02ae705c384134e988d8/db_test.go#L1377)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] It would be useful to explain the high level approach, namely that we will stall completion of certain compactions in the `TableCreated` callback
</blockquote></details>

Done.
___
*[`db_test.go` line 1394 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2508#-NU85h2M4IsUQ1MzKAFj:-NU8Xblj9bVApPF8yvr5:b6etrwv) ([raw file](https://github.com/cockroachdb/pebble/blob/ff930a8664f8a5e1fd5a02ae705c384134e988d8/db_test.go#L1394)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Why are we mixing mutexes and atomics? Can't everything be protected by the mutex? It would help to put all this state in a separate struct with a few helper methods.
</blockquote></details>

Done, using the mutex for both.
___
*[`db_test.go` line 1397 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2508#-NU84gSR3mL9vHYQrUl3:-NU8XlGe0OnVS_ygLCPO:b-oeyk2g) ([raw file](https://github.com/cockroachdb/pebble/blob/ff930a8664f8a5e1fd5a02ae705c384134e988d8/db_test.go#L1397)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] This channel of channels deserves a comment. Btw given that we're only blocking one thing at a time, we could use the same fixed "resume" channel instead of creating a new one each time.
</blockquote></details>

We're actually not blocking one thing at a time; the base compaction stays blocked throughout the test so we do need a separate channel for each blocked compaction.
___
*[`db_test.go` line 1398 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2508#-NU87bSJDeoYJzxIiJtv:-NU8Xvkn6kr8SxEBz2Bz:by03g6j) ([raw file](https://github.com/cockroachdb/pebble/blob/ff930a8664f8a5e1fd5a02ae705c384134e988d8/db_test.go#L1398)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Unless I'm missing something, it seems that this map never has more than 1 entry that is `true`, is this right? If yes, we can just make it a single `blockedJobID`
</blockquote></details>

Yep. Changed.
___
*[`db_test.go` line 1463 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2508#-NU88GXu2xibG0tTNOgf:-NU8Ykdc6HNsaj-GG-qm:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/ff930a8664f8a5e1fd5a02ae705c384134e988d8/db_test.go#L1463)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

We should move this timeout to a constant (it's used multiple times), and make it bigger (we see even simpler stuff go over all the time, for reference CRDB's SucceedsSoon is 45s).
</blockquote></details>

Done.
___
*[`db_test.go` line 1475 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2508#-NU86t6YEefOGJwOrrXW:-NU8YlKt4FBPAcKLiHPM:bzdpnyz) ([raw file](https://github.com/cockroachdb/pebble/blob/ff930a8664f8a5e1fd5a02ae705c384134e988d8/db_test.go#L1475)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This is a very hot loop.. might make sense to add a short sleep.
</blockquote></details>

Added one, but the non-async Flush() should have already ensured it wouldn't be too CPU-hot.

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2508#-:-NU8dywt1Bisae7r941i:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @sumeerbhola)

**Comment by itsbilal** [comment]
TFTR!

**Pull request merged**
