### PR TITLE
db: support concurrency in TestIngestValidation

### LINKED ISSUE #2640: TestIngestValidation fails under stress
This test fails right away under stress but not if I just run it normally repeatedly. I believe the test creates a directory inside the local tree and can't be run in parallel like `stress` does. We should make sure it uses a temp dir with a unique name. CC @nicktrav 

```
radu (master)+ /go/src/github.com/cockroachdb/pebble # go test . -run TestIngestValidation -count 1 -exec 'stress'


--- FAIL: TestIngestValidation (0.03s)
    ingest_test.go:2226: rng seed = 1686874341769169600
    --- FAIL: TestIngestValidation/start_block (0.01s)
        ingest_test.go:2302: 
                Error Trace:    ingest_test.go:2302
                                                        ingest_test.go:2340
                                                        ingest_test.go:2387
                Error:          Received unexpected error:
                                open ext: no such file or directory
                Test:           TestIngestValidation/start_block
    --- FAIL: TestIngestValidation/non-end_block (0.01s)
        ingest_test.go:2282: 
                Error Trace:    ingest_test.go:2282
                                                        ingest_test.go:2340
                                                        ingest_test.go:2387
                Error:          Received unexpected error:
                                pebble/table: invalid table (bad magic number: 0x0f9a68868d7eeb29)
                                (1) forced error mark
                                  | "pebble: corruption"
                                  | github.com/cockroachdb/errors/withstack/*withstack.withStack::
                                Wraps: (2) attached stack trace
                                  -- stack trace:
                                  | github.com/cockroachdb/pebble/internal/base.CorruptionErrorf
                                  |     /go/src/github.com/cockroachdb/pebble/internal/base/error.go:27
                                  | github.com/cockroachdb/pebble/sstable.readFooter
                                  |     /go/src/github.com/cockroachdb/pebble/sstable/table.go:384
                                  | github.com/cockroachdb/pebble/sstable.NewReader
                                  |     /go/src/github.com/cockroachdb/pebble/sstable/reader.go:3867
                                  | github.com/cockroachdb/pebble.TestIngestValidation.func1.3
                                  |     /go/src/github.com/cockroachdb/pebble/ingest_test.go:2281
                                  | github.com/cockroachdb/pebble.TestIngestValidation.func1.4
                                  |     /go/src/github.com/cockroachdb/pebble/ingest_test.go:2340
                                  | github.com/cockroachdb/pebble.TestIngestValidation.func1
                                  |     /go/src/github.com/cockroachdb/pebble/ingest_test.go:2387
                                  | testing.tRunner
                                  |     /usr/local/go1.19.4/src/testing/testing.go:1446
                                  | runtime.goexit
                                  |     /usr/local/go1.19.4/src/runtime/asm_amd64.s:1594
                                Wraps: (3) pebble/table: invalid table (bad magic number: 0x0f9a68868d7eeb29)
                                Error types: (1) *markers.withMark (2) *withstack.withStack (3) *errutil.leafError
                Test:           TestIngestValidation/non-end_block
FAIL
```

### PR DESCRIPTION
**Pull request by nicktrav**
Currently, `TestIngestValidation` ingests a file from the local filesystem. The ingested file uses a path that remains the same across test runs. This limits the ability of the test to run in parallel.

Alter the test to use `t.TempDir()` to ensure that the path is unique across test runs.

Fix #2640.

### CODE REVIEW

**Comment by nicktrav** [comment]
Verified:

```console
$ go test . -run TestIngestValidation -count 1 -exec 'stress' -v
5s: 32 runs so far, 0 failures
10s: 80 runs so far, 0 failures
...
```

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

Thanks for the quick fix!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2642#-:-NY3W-xg0sjR9sPWd3o2:b-8ef6c5)* status: 0 of 1 files reviewed, all discussions resolved

**Review by jbowens — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2642#-:-NY56Zwp7DAoIR5KEzJo:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nicktrav)

**Comment by RaduBerinde** [comment]
I'll merge this, I want to run all tests under stress for one of my changes.

**Pull request merged**
