### PR TITLE
go.mod: update cockroachdb/errors

### PR DESCRIPTION
**Pull request by jbowens**
Update cockroachdb/errors and use its oserror.Is* error-checking
predicates rather than the standard library's. This commit also adds a
linter to enforce usage of oserror.

See cockroachdb/errors#54.
See cockroachdb/cockroach#56048.

### CODE REVIEW

**Comment by knz** [comment]
Hold on to this for a little - I have perhaps mistakenly bumped the dependency on gogo/proto and that needs to be reverted otherwise the code won't build inside the cockroachdb tree.

**Comment by jbowens** [comment]
Anyone else notice that travis-ci seems to have stopped running builds for pull requests? They get queued and die on the vine: https://travis-ci.org/github/cockroachdb/pebble/builds/742996326

**Review by jbowens — COMMENTED** [review]
This is ready for review now.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/977#-:-MLyLnYzE00V9FsYfF3V:bcqc7rn)* status: 0 of 167 files reviewed, all discussions resolved (waiting on @knz and @petermattis)

**Review by knz — APPROVED** [review]
> Reviewed 167 of 167 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/977)* status: all files reviewed, 1 unresolved discussion (waiting on @jbowens and @petermattis)

___
*[go.sum, line 1 at r1](https://reviewable.io/reviews/cockroachdb/pebble/977#-MM-ythS1WKwgahqcYpN:-MM-ythU63lhHB7ZzlJe:b-bzmk95) ([raw file](https://github.com/cockroachdb/pebble/blob/e825088a084a4f2ce6a54e1b1f3206cab86bfc62/go.sum#L1)):*
> ```
> cloud.google.com/go v0.26.0/go.mod h1:aQUYkXzVsufM+DwF1aE+0xfcU+56JwCaLick0ClmMTw=
> ```

I think you can reduce the size of this diff with `go mod tidy`.

**Review by petermattis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/977#-:-MM0hIt5-w6MAFxgJeZK:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @jbowens and @petermattis)

**Review by jbowens — COMMENTED** [review]
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/977#-:-MM1HabIDuaP6omXP9n_:bz5mair)* status: 165 of 167 files reviewed, 1 unresolved discussion (waiting on @knz)

___
*[go.sum, line 1 at r1](https://reviewable.io/reviews/cockroachdb/pebble/977#-MM-ythS1WKwgahqcYpN:-MM1HcuL5om3OJ32spj2:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/e825088a084a4f2ce6a54e1b1f3206cab86bfc62/go.sum#L1)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I think you can reduce the size of this diff with `go mod tidy`.
</blockquote></details>

Done.

**Pull request merged**
