### PR TITLE
Export TeeEventListener

### PR DESCRIPTION
**Pull request by nvanbenschoten**
I plan to use this is CockroachDB to tee events to a new `pebbleMetricListener`
object that will listen to and expose metrics on write stalls. This will give us
better visibility into these events.

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
Actually, I'm realizing that we don't strictly need this, as we can just reach into the `pebbleLogger`'s `EventListener` like we do in [`(*Pebble).connectEventMetrics`](https://github.com/cockroachdb/cockroach/blob/9936b14065ed511b765f1c4442ed440252a2d897/pkg/storage/pebble.go#L599). That seems a little unclean though, so I'm inclined to proceed with this approach and get rid of `connectEventMetrics`. The only argument I can see for it is that we may be concerned about the performance impact of the tee-ing `EventListener`. Is that the case?

**Comment by nvanbenschoten** [comment]
I was going to use this to power a new `write_stalls` metric by placing a listener on `WriteStallBegin`. But maybe this count should be part of the `pebble.Metrics` struct itself and exported by Pebble directly. Do people have opinions?

**Comment by nvanbenschoten** [comment]
It looks like there was discussion about this from @petermattis all the way back in https://github.com/cockroachdb/pebble/pull/330.

> Some of this can also be measured and reported externally. The EventListener.WriteStall{Begin,End} events can be used by CRDB to measure the duration of write stalls and hook them into the existing metrics infrastructure. Could also do the same for compactions and flushes which would argue against doing anything too sophisticated here. I don't have a sense yet of how to draw the line between the metrics that Pebble reports and the metrics that it enables through other means.

> This has been fleshed out and is ready for a look. I don't add metrics around write stalls, but that could certainly be added, though as I noted below, a user can track their own write stall metrics using an EventListener.

Has the thinking progressed here? One argument for reporting on write stalls through the EventListener is that the duration of write stalls can be tracked in a histogram. But if we're just trying to add a counter, it seems like this could easily live in Pebble itself.

**Review by itsbilal — APPROVED** [review]
I'm open to more opinions on `connectEventMetrics` vs the Tee-based approach here. Intiutively I do agree that the teeing approach is cleaner and can replace `connectEventMetrics`. The performance hit is likely not an issue as while Pebble events/logs are fairly noisy and hot, the ratio of events to KVs in the engine is still low enough and the amortization of the performance cost spread out enough for it to not materially impact anything.

There hasn't really been any additional discussion on counters in Pebble vs counters in Cockroach through `EventListener`.  I would slightly favour the `EventListener` approach - mostly because I can see the durations/starts/ends being valuable in Cockroach, in a way that's more instantaneously-relevant for the operator than other metrics currently tracked in Pebble (eg. ingestion counts). Also yes, durations.

Code :lgtm: 

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1168#-:-Mck7X19A3lSFamXiZx1:bca78vh)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jbowens)

**Review by jbowens — APPROVED** [review]
:lgtm:

I like the `EventListener` approach too :+1: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1168#-:-McoDCJZ-C_IoJNKVNVn:b91wfs0)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nvanbenschoten)

**Comment by nvanbenschoten** [comment]
Thanks for the feedback! I'll merge this as is then.

**Pull request merged**
