### PR TITLE
internal/manifest: InitProviderBacking in VersionEdit decoding

### PR DESCRIPTION
**Pull request by dt**

### CODE REVIEW

**Comment by itsbilal** [comment]
The comment on `ve.Decode` describes that it's the caller's job to set the `FileBacking`, and the manifest load code seems to do this correctly. It also looks like we do set the file backing correctly when ingesting external files. I'll have to dig deeper into where we tripped up this issue, as something else is likely going wrong.

**Comment by dt** [comment]
Huh, why is it init’ing the physical backing here then?

**Comment by dt** [comment]
Anyway, I see where to init it in tools/lsm.go, I’ll send that out in a bit.

**Comment by dt** [comment]
Did that over in https://github.com/cockroachdb/pebble/pull/3073

**Pull request closed without merging**
