### PR TITLE
db: ensure Metrics.WAL.BytesWritten is nondecreasing

### LINKED ISSUE #3505: db: Metrics.WAL.BytesWritten appears bogus
This metric spikes orders of magnitude beyond WAL.BytesIn, even orders of magnitude beyond bytes flushed or compacted, and beyond the node-level bytes written.

Internal slack link: https://cockroachlabs.slack.com/archives/C06TG0C6VGS/p1712855654340209?thread_ts=1712673101.370579&cid=C06TG0C6VGS

### PR DESCRIPTION
**Pull request by jbowens**
**db: update flushableEntry.logSize during flushable ingest**

Performing a flushable ingestion causes two WAL rotations: one to switch away
from the WAL corresponding to the mutable memtable to a temporary, intermediary
WAL for the ingestion, and one to switch to the next mutable memtable's WAL.
Both these WAL rotations ignored the previous log size, omitting the
propagation to the corresponding flushable.

This commit fixes this bug, propagating the logSize appropriately.

**db: ensure Metrics.WAL.BytesWritten is nondecreasing**

The Metrics.WAL.BytesWritten metric is intended to be a monotonically
increasing counter of all bytes written to the write-ahead log. Previously, it
was possible for this metric to violate monotonicity immediately after a WAL
rotation. The d.logSize value—which corresponds to the size of the current
WAL—was not reset to zero. It was only reset after the first write to the new
WAL.

Close #3505.

### CODE REVIEW

**Review by jbowens — COMMENTED** [review]
Looks like there's now different metrics for TestMetrics and TestEventListener depending on the presence of the invariants tag... will need to debug

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3555#-:-NwMCZXy2LYfrxpsY4GT:b-ec55xj)* status: 0 of 6 files reviewed, all discussions resolved (waiting on @itsbilal)

**Comment by jbowens** [comment]
Ok this is ready for a look

**Review by sumeerbhola — APPROVED** [review]
:lgtm_strong: 

> Reviewed 5 of 5 files at r1, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3555#-:-Nwfw7_4-FbULLIDLR0b:b-uwkowd)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @itsbilal)

**Comment by jbowens** [comment]
TFTR!

**Pull request merged**
