### PR TITLE
db: support range keys in delete-only compactions

### PR DESCRIPTION
**Pull request by nicktrav**
Two commits in this patch.

TODOs:
- [x] Avoid counting point key space on range key del only hints
- [ ] Squash additional commits

---

**db: add tableRangedDeletionIter for iteration of ranged deletion spans**

Add a new `keyspan.FragmentIterator` implementation that iterates over
the range deletion and range key blocks of a single table. The iterator
returns merged spans from the table corresponding to "ranged deletions".
A "ranged deletion" span contains keys that fall into one of three
cases: the span contains only range deletions; the span contains only
range key deletions; the span contains a mixture of both range deletions
and range key deletions.

The new `tableRangedDeletionIter` will be used to construct spans
necessary for calculating deletion hints on a table that takes range
keys into account. Previously, only range deletion spans were
considered.

For a tables that do not contain range key deletes, the iterator returns
the same set of spans that the existing logic would have returned.

**db: consider range keys in delete-only compactions**

Currently, when constructing delete-only compactions hints, only range
delete spans are considered. With the introduction of range keys, the
current hint construction logic is incorrect. Specifically, a hint
constructed from a range delete may completely cover a table containing
range keys. Currently, this table would be marked as eligible for
deletion. However, the table should only be deleted if the range keys
are also deleted.

Make use of the `tableRangedDeletionIter` for construction of
delete-only compaction hints. A new `deleteCompactionHintType` type is
used to distinguish between hints generated by a range delete (which may
not delete tables containing range keys), hints generated from a range
key delete (which may not delete tables containing point keys), and
hints generated from a span with both a range delete and range key
delete (which may delete any covering table).

### CODE REVIEW

**Review by nicktrav — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1656)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @itsbilal and @jbowens)

___
*[table_stats.go, line 596 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1656#-N-xi60jA7ByRcapp9F4:-N-xi60jA7ByRcapp9F5:bmuws1k) ([raw file](https://github.com/cockroachdb/pebble/blob/33fa37d344c8a122d3f2d295ff591a142e77cbdc/table_stats.go#L596)):*
> ```Go
> 	}
> 	if iter != nil {
> 		// FIXME(travers): Do we also need the truncation here too?
> ```

Note to self: truncation isn't required here, as range keys will not be split across tables.

**Review by jbowens — COMMENTED** [review]
Flushing comments on the first commit

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1656#-:-N-y6i8b6Yzht6lt7kwR:b9npqaw)* status: 0 of 6 files reviewed, 6 unresolved discussions (waiting on @itsbilal and @nicktrav)

___
*[-- commits, line 17 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1656#-N-xtdKy4_aMvgB6VpM8):*
nit: s/a tables/tables/
___
*[table_stats.go, line 535 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1656#-N-y0F8p8EQATXGcQgB2:-N-y0F8p8EQATXGcQgB3:b-nr85mn) ([raw file](https://github.com/cockroachdb/pebble/blob/708af6300e3040b40517676b944e568ca9450fdb/table_stats.go#L535)):*
> ```Go
> // tableRangedDeletionIter is a keyspan.FragmentIterator that returns "ranged
> // deletion" spans for a single table, providing a combined view of both range
> // deletion and range key deletion spans. The tableRAngedDeletionIter is
> ```

nit: tableRangedDeletionIter
___
*[table_stats.go, line 642 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1656#-N-y2jO13DuF-ByPBNTs:-N-y2jO13DuF-ByPBNTt:buh5y9v) ([raw file](https://github.com/cockroachdb/pebble/blob/708af6300e3040b40517676b944e568ca9450fdb/table_stats.go#L642)):*
> ```Go
> 	// largest and smallest keys in the defragmented span. This maintains the
> 	// contract that the emitted slice is sorted by (SeqNum, Kind) descending.
> 	reducer := func(current, incoming []keyspan.Key) []keyspan.Key {
> ```

I think there's a complication here where the reducer removes knowledge that the equality function needs. I'm imagining a scenario like:

```
a-b:{(#10,RANGEDEL) (#5,RANGEKEYDEL) (#3,RANGEDEL)}
c-d:{(#10,RANGEDEL) (#5,RANGEKEYDEL) (#3,RANGEDEL)}
d-e:{(#10,RANGEDEL) (#3,RANGEDEL)}
```

during forward iteration, if I understand it correctly, this iterator would yield
```
a-e:{(#10,RANGEDEL) (#3,RANGEDEL)}
```
___
*[table_stats.go, line 674 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1656#-N-y4TKZBuvgtp7cR2al:-N-y4TKZBuvgtp7cR2am:b-ifp9xb) ([raw file](https://github.com/cockroachdb/pebble/blob/708af6300e3040b40517676b944e568ca9450fdb/table_stats.go#L674)):*
> ```Go
> 	delIter := &tableRangedDeletionIter{
> 		FragmentIterator: dIter,
> 		closers:          closers,
> ```

is the closers slice necessary? wondering if we can let `DefragmentIter.Close` call `MergingIter.Close` which should fan out and close all the leaf iterators.
___
*[table_stats_test.go, line 168 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1656#-N-y5LTZ-CuymkgTcINQ:-N-y5LTZ-CuymkgTcINR:b-xpchgw) ([raw file](https://github.com/cockroachdb/pebble/blob/708af6300e3040b40517676b944e568ca9450fdb/table_stats_test.go#L168)):*
> ```Go
> 					err = w.RangeKeyUnset(start, end, []byte(parts[3]))
> 				case "range-key-del":
> 					err = w.RangeKeyDelete(start, end)
> ```

how about taking the `keyspan.ParseSpan` format in this test, which allows customizing the sequence numbers? We'd have have to use the `(*sstable.Writer).AddRangeKey` method. We care quite a bit about  this iterator surfacing the correct sequence numbers, since we might delete files with live keys if it doesn't.

**Review by nicktrav — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1656)* status: 0 of 7 files reviewed, 3 unresolved discussions (waiting on @itsbilal and @jbowens)

___
*[-- commits, line 17 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1656#-N-xtdKy4_aMvgB6VpM8):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

nit: s/a tables/tables/
</blockquote></details>

Done.
___
*[table_stats.go, line 535 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1656#-N-y0F8p8EQATXGcQgB2:-N-yPOWO9QFv-M-cnxFf:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/708af6300e3040b40517676b944e568ca9450fdb/table_stats.go#L535)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

nit: tableRangedDeletionIter
</blockquote></details>

Done.
___
*[table_stats.go, line 642 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1656#-N-y2jO13DuF-ByPBNTs:-N-yuS8qCk0F1sAfvQmn:bdcml01) ([raw file](https://github.com/cockroachdb/pebble/blob/708af6300e3040b40517676b944e568ca9450fdb/table_stats.go#L642)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

I think there's a complication here where the reducer removes knowledge that the equality function needs. I'm imagining a scenario like:

```
a-b:{(#10,RANGEDEL) (#5,RANGEKEYDEL) (#3,RANGEDEL)}
c-d:{(#10,RANGEDEL) (#5,RANGEKEYDEL) (#3,RANGEDEL)}
d-e:{(#10,RANGEDEL) (#3,RANGEDEL)}
```

during forward iteration, if I understand it correctly, this iterator would yield
```
a-e:{(#10,RANGEDEL) (#3,RANGEDEL)}
```


</blockquote></details>

Good catch. I pushed a separate commit (which I will squash into the first before merge, provided we're happy with it).

We're now preserving just the first and last key for each emitted span, and modifying the key kinds to act as a "marker" in the case where there are mixed key kinds (i.e. range dels and range key dels). I believe this is fine as the key kinds are only used to infer the type of span and thus hint type (see the second commit).

Open to alternative approaches on encoding this range del only / range key only / mixed key span information.
___
*[table_stats.go, line 674 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1656#-N-y4TKZBuvgtp7cR2al:-N-yPaAP5l9vpY38i-OT:b-7qtggh) ([raw file](https://github.com/cockroachdb/pebble/blob/708af6300e3040b40517676b944e568ca9450fdb/table_stats.go#L674)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

is the closers slice necessary? wondering if we can let `DefragmentIter.Close` call `MergingIter.Close` which should fan out and close all the leaf iterators.
</blockquote></details>

The problem I was running up against was that `keyspan.Truncate` returns a new `*keyspan.Iter` which has a no-op `Close` method. If we just close the merging iter, the original range del iter isn't closed, and we panic due to the leak.

We seem to do a similar thing [here](https://github.com/cockroachdb/pebble/blob/785bb36dae6e837c9fd3d2bbb245f7647fbacc78/compaction.go#L1002-L1027) (adding to a `closers` slice before we lose the reference to `Truncate`). It seems in this case we don't want to propagate the close, as we want to reuse the underlying iter.
___
*[table_stats_test.go, line 168 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1656#-N-y5LTZ-CuymkgTcINQ:-N-zq_ji5ZR5iuX2NSVd:b-5dup6n) ([raw file](https://github.com/cockroachdb/pebble/blob/708af6300e3040b40517676b944e568ca9450fdb/table_stats_test.go#L168)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

how about taking the `keyspan.ParseSpan` format in this test, which allows customizing the sequence numbers? We'd have have to use the `(*sstable.Writer).AddRangeKey` method. We care quite a bit about  this iterator surfacing the correct sequence numbers, since we might delete files with live keys if it doesn't.
</blockquote></details>

Good call. Updated.

**Review by jbowens — COMMENTED** [review]
> Reviewed 1 of 4 files at r2, 1 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1656)* status: 2 of 7 files reviewed, 4 unresolved discussions (waiting on @itsbilal and @nicktrav)

___
*[table_stats.go, line 642 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1656#-N-y2jO13DuF-ByPBNTs:-N01REyfECv0Pwtga65E:b-8oakbv) ([raw file](https://github.com/cockroachdb/pebble/blob/708af6300e3040b40517676b944e568ca9450fdb/table_stats.go#L642)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

Good catch. I pushed a separate commit (which I will squash into the first before merge, provided we're happy with it).

We're now preserving just the first and last key for each emitted span, and modifying the key kinds to act as a "marker" in the case where there are mixed key kinds (i.e. range dels and range key dels). I believe this is fine as the key kinds are only used to infer the type of span and thus hint type (see the second commit).

Open to alternative approaches on encoding this range del only / range key only / mixed key span information.
</blockquote></details>

Yeah, I think this mutation of the key kinds is fine for correctness, but I don't love the subtlety.  

Throwing out another idea:
* Wrap the range deletion and range key deletion iterators _separately_ in a `DefragmentingIter`, using `reduce` to only keep the first and last Keys of each. The range key `DefragmentIter` would need to ignore and drop `RangeKeySets`, `RangeKeyUnsets`. I think these could still share code if configured with a key kind to 'keep'.
* Wrap the resulting two iterators in a merging iterator.

The result would be just as defragmented, because the only fragmentation points are at defragmented start/end bounds of each of the kind kind. The resulting span would have at most 4 keys, and we can scan the keys list to check for the existence of multiple kinds.
___
*[table_stats.go, line 674 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1656#-N-y4TKZBuvgtp7cR2al:-N01Jj9O4R6ezD6LnPtz:byypp8b) ([raw file](https://github.com/cockroachdb/pebble/blob/708af6300e3040b40517676b944e568ca9450fdb/table_stats.go#L674)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

The problem I was running up against was that `keyspan.Truncate` returns a new `*keyspan.Iter` which has a no-op `Close` method. If we just close the merging iter, the original range del iter isn't closed, and we panic due to the leak.

We seem to do a similar thing [here](https://github.com/cockroachdb/pebble/blob/785bb36dae6e837c9fd3d2bbb245f7647fbacc78/compaction.go#L1002-L1027) (adding to a `closers` slice before we lose the reference to `Truncate`). It seems in this case we don't want to propagate the close, as we want to reuse the underlying iter.
</blockquote></details>

Ah, yeah, that makes sense. Looking forward to when we can drop that `keyspan.Truncate`.
___
*[table_stats.go, line 335 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1656#-N01M0aJ1Yo_q-azLjo4:-N01M0aJ1Yo_q-azLjo5:bjafhy7) ([raw file](https://github.com/cockroachdb/pebble/blob/12283952771fbb04f1bb7a281bc629286b005d45/table_stats.go#L335)):*
> ```Go
> 		}
> 
> 		estimate, hintSeqNum, err := d.estimateSizeBeneath(v, level, meta, start, end)
> ```

there's some awkwardness with `estimateSizeBeneath` and the `EstimateDiskUsage` call above. These functions estimate without knowledge of range keys. They include a file's entire size if the file's bounds fall within range of `[start, end)`. Otherwise they use the point index blocks to calculate an estimate at block-level granularity.

I don't think we can ignore a little loss of precision from excluding range keys blocks when calculating estimates, since range keys are expected to be rare, but we should avoid including a large swath of the point keys if the span only contains `RANGEKEYDEL`s
___
*[testdata/compaction_delete_only_hints, line 307 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1656#-N01TfCs0ZGWrI5i61QF:-N01TfCs0ZGWrI5i61QG:b7cb3pf) ([raw file](https://github.com/cockroachdb/pebble/blob/12283952771fbb04f1bb7a281bc629286b005d45/testdata/compaction_delete_only_hints#L307)):*
> ```
> #   +---+           +---+             +---+
> # __________________________________________________________
> #   a b c d e f g h i j k l m n o p q r s t u v w x y z
> ```

Love this test.

**Review by nicktrav — COMMENTED** [review]
TFTRs so far, @jbowens. Thoughts on the approach second commit? Regardless, I'm going to hold off on this until we have a path forward around #1663.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1656#-:-N07vtMDATmjYUo5_cpv:b7u0gk9)* status: 0 of 7 files reviewed, 4 unresolved discussions (waiting on @itsbilal and @jbowens)

___
*[table_stats.go, line 642 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1656#-N-y2jO13DuF-ByPBNTs:-N07uhl749jkksm0E79m:b4w7y9b) ([raw file](https://github.com/cockroachdb/pebble/blob/708af6300e3040b40517676b944e568ca9450fdb/table_stats.go#L642)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

Yeah, I think this mutation of the key kinds is fine for correctness, but I don't love the subtlety.  

Throwing out another idea:
* Wrap the range deletion and range key deletion iterators _separately_ in a `DefragmentingIter`, using `reduce` to only keep the first and last Keys of each. The range key `DefragmentIter` would need to ignore and drop `RangeKeySets`, `RangeKeyUnsets`. I think these could still share code if configured with a key kind to 'keep'.
* Wrap the resulting two iterators in a merging iterator.

The result would be just as defragmented, because the only fragmentation points are at defragmented start/end bounds of each of the kind kind. The resulting span would have at most 4 keys, and we can scan the keys list to check for the existence of multiple kinds.
</blockquote></details>

Latest commit implements this (which I shall also squash), building on the new `keyspan.Filter`. Thanks for the suggestion!

There's one wrinkle that came up around key stability with the merging iter that's causing some metamorphic test failures. I opened #1663, and will wait for the fix for that to go in. This wasn't an issue previously as the merging iter was at the bottom of the stack, and its inputs were stable.
___
*[table_stats.go, line 335 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1656#-N01M0aJ1Yo_q-azLjo4:-N07vPAG3bmVetnN2UG7:bwydzz6) ([raw file](https://github.com/cockroachdb/pebble/blob/12283952771fbb04f1bb7a281bc629286b005d45/table_stats.go#L335)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

there's some awkwardness with `estimateSizeBeneath` and the `EstimateDiskUsage` call above. These functions estimate without knowledge of range keys. They include a file's entire size if the file's bounds fall within range of `[start, end)`. Otherwise they use the point index blocks to calculate an estimate at block-level granularity.

I don't think we can ignore a little loss of precision from excluding range keys blocks when calculating estimates, since range keys are expected to be rare, but we should avoid including a large swath of the point keys if the span only contains `RANGEKEYDEL`s
</blockquote></details>

Good point. We have a TODO in the laundry list to update the size estimates. I'll look at that next. Depending on how it shakes out, I might put up a separate patch.

**Comment by nicktrav** [comment]
Pushed a rebased version that picks up b9e970a83ddd763b39e2d3270fa1d648c9a55866.

Still need to incorporate a tweak to the disk estimation to ensure we're not counting point key size under range key del deletion hints.

**Review by jbowens — COMMENTED** [review]
> Reviewed 2 of 4 files at r5, 2 of 4 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1656)* status: 6 of 7 files reviewed, 6 unresolved discussions (waiting on @itsbilal, @jbowens, and @nicktrav)

___
*[`compaction.go` line 1683 at r7](https://reviewable.io/reviews/cockroachdb/pebble/1656#-N0kTf6S1j2ZAq2Xb4AK:-N0kTf6S1j2ZAq2Xb4AL:b-k74fm0) ([raw file](https://github.com/cockroachdb/pebble/blob/a20684e42fa45f3248f9d670d87ddaa106788f78/compaction.go#L1683)):*
> ```Go
> 
> // deleteCompactionHintType indicates whether the deleteCompactionHint was
> // generated from a span containing a range del (point key only), a range delete
> ```

nit: "a range key delete (range key only)"

We use the language "range delete" to refer to `RANGEDEL`s in many places. I wish we had unambiguous names to differentiate these, but hard problems in computer science, amirite?
___
*[`compaction.go` line 1717 at r7](https://reviewable.io/reviews/cockroachdb/pebble/1656#-N0kU9Sy9lvRBZjrU-fm:-N0kU9Sy9lvRBZjrU-fn:b1oxmhi) ([raw file](https://github.com/cockroachdb/pebble/blob/a20684e42fa45f3248f9d670d87ddaa106788f78/compaction.go#L1717)):*
> ```Go
> 		switch k.Kind() {
> 		case base.InternalKeyKindRangeDelete:
> 			hintType |= 1 << 0
> ```

could this be `hintType |= deleteCompactionHintTypePointKeyOnly` and down below `hintType |= deleteCompactionHintTypeRangeKeyOnly` to make the relationship with the enum a little clearer?
___
*[`compaction.go` line 1721 at r7](https://reviewable.io/reviews/cockroachdb/pebble/1656#-N0kUqnS83BceUXBuK5V:-N0kUqnS83BceUXBuK5W:bbaywg5) ([raw file](https://github.com/cockroachdb/pebble/blob/a20684e42fa45f3248f9d670d87ddaa106788f78/compaction.go#L1721)):*
> ```Go
> 			hintType |= 1 << 1
> 		default:
> 			panic(fmt.Sprintf("unsupported hint hind: %s", k.Kind()))
> ```

nit: s/hint hind/key kind/
___
*[`table_stats.go` line 583 at r4](https://reviewable.io/reviews/cockroachdb/pebble/1656#-N0kT9ad4Ks11o4c6s2h:-N0kT9ad4Ks11o4c6s2i:bln2ab2) ([raw file](https://github.com/cockroachdb/pebble/blob/587bf7b88fcbf34b6c5a7ab79e4062581be6752d/table_stats.go#L583)):*
> ```Go
> 		// Truncate tombstones to the containing file's bounds if necessary.
> 		// See docs/range_deletions.md for why this is necessary.
> 		closers = append(closers, iter)
> ```

With your change to `Truncate`, I think we could drop the `closers` slice now.
___
*[`internal/keyspan/span.go` line 73 at r7](https://reviewable.io/reviews/cockroachdb/pebble/1656#-N0kWjVS-skBw7A4XA_v:-N0kWjVS-skBw7A4XA_w:bzbc1hj) ([raw file](https://github.com/cockroachdb/pebble/blob/a20684e42fa45f3248f9d670d87ddaa106788f78/internal/keyspan/span.go#L73)):*
> ```Go
> func (k Key) Equal(b Key) bool {
> 	return k.Trailer == b.Trailer &&
> 		bytes.Equal(k.Suffix, b.Suffix) &&
> ```

`bytes.Equal` is okay for comparing values, but suffixes need to be compared with a  user-provided `base.Compare` or `base.Equal`. At the moment, I believe `bytes.Equal` works for CockroachDB's use, but with cockroachdb/cockroach#77342 equal suffixes are not necessarily byte equal.

**Review by nicktrav — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1656)* status: 3 of 7 files reviewed, 4 unresolved discussions (waiting on @itsbilal and @jbowens)

___
*[`compaction.go` line 1683 at r7](https://reviewable.io/reviews/cockroachdb/pebble/1656#-N0kTf6S1j2ZAq2Xb4AK:-N0lETSdDglWCWyA0yZc:bop0gnj) ([raw file](https://github.com/cockroachdb/pebble/blob/a20684e42fa45f3248f9d670d87ddaa106788f78/compaction.go#L1683)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

nit: "a range key delete (range key only)"

We use the language "range delete" to refer to `RANGEDEL`s in many places. I wish we had unambiguous names to differentiate these, but hard problems in computer science, amirite?
</blockquote></details>

Yeah - bit of a mouthful. Fixed!
___
*[`compaction.go` line 1717 at r7](https://reviewable.io/reviews/cockroachdb/pebble/1656#-N0kU9Sy9lvRBZjrU-fm:-N0lFMZH2HJuc4a-P4ss:bcvjgzp) ([raw file](https://github.com/cockroachdb/pebble/blob/a20684e42fa45f3248f9d670d87ddaa106788f78/compaction.go#L1717)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

could this be `hintType |= deleteCompactionHintTypePointKeyOnly` and down below `hintType |= deleteCompactionHintTypeRangeKeyOnly` to make the relationship with the enum a little clearer?
</blockquote></details>

Good idea. Done.
___
*[`table_stats.go` line 583 at r4](https://reviewable.io/reviews/cockroachdb/pebble/1656#-N0kT9ad4Ks11o4c6s2h:-N0lFR0m1PeVcBtIc4Ap:b85ysyx) ([raw file](https://github.com/cockroachdb/pebble/blob/587bf7b88fcbf34b6c5a7ab79e4062581be6752d/table_stats.go#L583)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

With your change to `Truncate`, I think we could drop the `closers` slice now.
</blockquote></details>

Yeah - that disappeared in a20684e42fa45f3248f9d670d87ddaa106788f78. Reviewable is probably not doing it justice.
___
*[`internal/keyspan/span.go` line 73 at r7](https://reviewable.io/reviews/cockroachdb/pebble/1656#-N0kWjVS-skBw7A4XA_v:-N0lGmcM0El-JAccCli5:b60vwtz) ([raw file](https://github.com/cockroachdb/pebble/blob/a20684e42fa45f3248f9d670d87ddaa106788f78/internal/keyspan/span.go#L73)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

`bytes.Equal` is okay for comparing values, but suffixes need to be compared with a  user-provided `base.Compare` or `base.Equal`. At the moment, I believe `bytes.Equal` works for CockroachDB's use, but with cockroachdb/cockroach#77342 equal suffixes are not necessarily byte equal.
</blockquote></details>

Ah, thanks. Looks like we have a `base.Compare` wired up, so I'm plumbing that through now for the suffix comparisons.

**Comment by nicktrav** [comment]
I'm going to close this out in favor of a new PR with all the squashing done and a rebase to pick up the latest changes from master.

With all the changes that have happened in the last month, it's probably worth reviewing this with fresh context.

Happy to re-open this one if that ends up being simpler.

**Pull request closed without merging**
