### PR TITLE
Finalizer test

### PR DESCRIPTION
**Pull request by bananabrick**
On the first commit of this pull request, if I run `go test -tags 'invariants'  -run TestDBFinalizerCalled`, I see the test fail because the finalizer is not called.

Then, if I make a small change in the second commit of this pr, where I turn the `tableCache` in the `DB` struct into a pointer, we see that the finalizer is called, when `go test -tags 'invariants'  -run TestDBFinalizerCalled` is run.

So it seems like:
1. The finalizer isn't being run for most of our tests on the master branch.
2. We're not gracefully closing the db for our tests, but we've missed these because the finalizer isn't run.
3. For some reason, storing a pointer to the `tableCache` in the DB causes the finalizer to be called consistently.

### CODE REVIEW

**Review by bananabrick — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1234)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @bananabrick)

___
*[finalizer_test.go, line 37 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1234#-Mh_EyIv9NkGmVzz2UcI:-Mh_EyIwCskirG5T1vUZ:b-mkcd3b) ([raw file](https://github.com/cockroachdb/pebble/blob/866b3f40e3eb0b7fddcdb0cf4bfe70fdb077021a/finalizer_test.go#L37)):*
> ```Go
> 			t.Errorf("DB didn't open.")
> 		}
> 		d.closed.Load()
> ```

Note that i'm not calling `d.Close` here. The call to `d.closed.Load()` just exists so that I "use" the d variable, and don't get a warning.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1234)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @bananabrick)

___
*[finalizer_test.go, line 16 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1234#-MhdKtEc9lz-VgLnA4K8:-MhdKtEc9lz-VgLnA4K9:bp368wl) ([raw file](https://github.com/cockroachdb/pebble/blob/866b3f40e3eb0b7fddcdb0cf4bfe70fdb077021a/finalizer_test.go#L16)):*
> ```Go
> )
> 
> func TestDBFinalizerCalled(t *testing.T) {
> ```

This test is going to be flaky as it isn't guaranteed that the DB finalizer is called before one of the other finalizers (e.g. the one on the memtable buffer). Additionally, when the finalizer is called `DB.closed` will still be used causing the process to exit.
___
*[finalizer_test.go, line 37 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1234#-Mh_EyIv9NkGmVzz2UcI:-MhdJEmxE5OKNzaeQRbp:b2fakew) ([raw file](https://github.com/cockroachdb/pebble/blob/866b3f40e3eb0b7fddcdb0cf4bfe70fdb077021a/finalizer_test.go#L37)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

Note that i'm not calling `d.Close` here. The call to `d.closed.Load()` just exists so that I "use" the d variable, and don't get a warning.
</blockquote></details>

The standard way to mark a variable as used is `_ = d`.
___
*[open.go, line 103 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1234#-MhdLCWm8m2ix09ZxaQS:-MhdLCWm8m2ix09ZxaQT:b-syh2j7) ([raw file](https://github.com/cockroachdb/pebble/blob/866b3f40e3eb0b7fddcdb0cf4bfe70fdb077021a/open.go#L103)):*
> ```Go
> 		tableCacheSize = minTableCacheSize
> 	}
> 	d.tableCache = &tableCache{}
> ```

Huh. I'm not sure why this is having an effect. I don't mind making this change. `DB.tableCache` doesn't need to be embedded as a value, though I wish I understood what was going on better.

**Review by sumeerbhola — COMMENTED** [review]
Glad to see this reproduced in a small test.

> The finalizer isn't being run for most of our tests on the master branch.

Could you look into fixing this. Hopefully it is not too painful.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1234#-:-MhhweYbBO_OGsPjqB-j:b-kjo9og)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @bananabrick and @petermattis)

___
*[finalizer_test.go, line 16 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1234#-MhdKtEc9lz-VgLnA4K8:-Mhhv1ZG42hR0Xgj1SID:bykgdds) ([raw file](https://github.com/cockroachdb/pebble/blob/866b3f40e3eb0b7fddcdb0cf4bfe70fdb077021a/finalizer_test.go#L16)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

This test is going to be flaky as it isn't guaranteed that the DB finalizer is called before one of the other finalizers (e.g. the one on the memtable buffer). Additionally, when the finalizer is called `DB.closed` will still be used causing the process to exit.
</blockquote></details>

How about we add an Option,  `TestDBFinalizer` atomic, that if non-nil, causes the finalizer to alter its behavior and store 1 when ok and 2 when error and not exit. Then we loop and sleep for 1s each time and call runtime.GC and load the atomic, and give up after 10s.

**Review by bananabrick — COMMENTED** [review]
Yea, I'll try and see if I can add a test for this in a separate PR.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1234#-:-Mho3Rmr9NvwSZLiKHxS:b9pe9rx)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @petermattis)

___
*[finalizer_test.go, line 16 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1234#-MhdKtEc9lz-VgLnA4K8:-Mho3Xqy0RUkZGRbQt8d:b-4vr1d3) ([raw file](https://github.com/cockroachdb/pebble/blob/866b3f40e3eb0b7fddcdb0cf4bfe70fdb077021a/finalizer_test.go#L16)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

How about we add an Option,  `TestDBFinalizer` atomic, that if non-nil, causes the finalizer to alter its behavior and store 1 when ok and 2 when error and not exit. Then we loop and sleep for 1s each time and call runtime.GC and load the atomic, and give up after 10s.
</blockquote></details>

Thanks. I can try something like this.
___
*[open.go, line 103 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1234#-MhdLCWm8m2ix09ZxaQS:-Mho2zG_EbqRK-7hZk23:b-loqvrp) ([raw file](https://github.com/cockroachdb/pebble/blob/866b3f40e3eb0b7fddcdb0cf4bfe70fdb077021a/open.go#L103)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Huh. I'm not sure why this is having an effect. I don't mind making this change. `DB.tableCache` doesn't need to be embedded as a value, though I wish I understood what was going on better.
</blockquote></details>

I don't plan to change the tableCache to a pointer here. I ran into this issue when I was working on https://github.com/cockroachdb/pebble/pull/1229/files, where turning the `tableCache` into a pointer seemed to be the most straightforward way to make it shareable.

I wrote this PR to demonstrate the issues I was seeing and I don't plan to merge it.

**Pull request closed without merging**
