### PR TITLE
internal/testkeys: new package

### PR DESCRIPTION
**Pull request by jbowens**
Add an internal testkeys package for generating and comparing human-readable
test keys. These test keys may be suffixed with an integer timestamp. The
testkeys package exposes its own Comparer implementation that compares
timestamps based on their logical value, rather than their byte encoding.

As Pebble introduces new suffix-aware features, like range keys, we will
increasingly have a need for human-readable suffixed keys.

The key generation facilities in this package support generating keys of
varying lengths interleaved. This is anticipated to be useful when testing or
benchmarking compactions, where a subset of keys are overwritten and a subset
are new.

### CODE REVIEW

**Review by nicktrav — COMMENTED** [review]
> Reviewed 2 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1367)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @jbowens and @sumeerbhola)

___
*[go.mod, line 11 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1367#-Mo9s9NvD6a0R7mcxoW_:-Mo9s9NvD6a0R7mcxoWa:by4hixl) ([raw file](https://github.com/cockroachdb/pebble/blob/fd771cd6118b4522f447146db47a83c506dda23e/go.mod#L11)):*
> ```XML
> 	github.com/ghemawat/stream v0.0.0-20171120220530-696b145b53b9
> 	github.com/golang/snappy v0.0.3
> 	github.com/klauspost/compress v1.12.3
> ```

I presume these are from adding `strutil`?

Wondering if we can could just inline the function (with appropriate attribution), rather than pulling in another dep (looks like it has a ton of transitive deps, based on the go.sum diff)? Given we're adding a "test-only" package, it seems heavy handed to pull in all these other dependencies.

With that to one side, if we take the path of adding the new dep, do we need to regen the vendor directory?

**Review by nicktrav — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1367)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @jbowens and @sumeerbhola)

___
*[internal/testkeys/testkeys.go, line 137 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1367#-MoA1glI1fuimYRuDYve:-MoA1glI1fuimYRuDYvf:bh1uwpf) ([raw file](https://github.com/cockroachdb/pebble/blob/fd771cd6118b4522f447146db47a83c506dda23e/internal/testkeys/testkeys.go#L137)):*
> ```Go
> 	// Slice returns the sub-keyspace from index i, inclusive, to index j
> 	// exclusive.
> 	Slice(i, j int) Keyspace
> ```

nit: Wondering if these doc strings should indicate that a  _new_ `Keyspace` is returned (for `Slice` and `EveryN`)?

Looks like `alphabet` returns a mutated copy of the receiver. I guess you could also have a implementation that returns a pointer to `self` and mutates, though that would seem weird.

**Review by nicktrav — APPROVED** [review]
Neat. Just some nits. :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1367#-:-MoB6LsLA5xyXnLA5SvR:b34lqi7)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @jbowens, @nicktrav, and @sumeerbhola)

___
*[internal/testkeys/testkeys.go, line 226 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1367#-MoB4qboDoM0psHUZjJJ:-MoB4qbp17Inf-dmIIeU:b522vqq) ([raw file](https://github.com/cockroachdb/pebble/blob/c0c9661118a879bdc2f911b547230f6e16b3c333/internal/testkeys/testkeys.go#L226)):*
> ```Go
> }
> 
> func keyCount(n, l int) int {
> ```

nit: could this be `uint64` to squeeze as much out of the range as possible?

Also - does it make sense if `l > n`? In that case, do we need to cap `l` to be `min(l, n)`? Or is it a programmer error if `l > n`, in which case `panic`.

**Review by jbowens — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1367#-:-Mo_RY6209YNq63eC09h:b-814g8k)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @nicktrav and @sumeerbhola)

___
*[internal/testkeys/testkeys.go, line 226 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1367#-MoB4qboDoM0psHUZjJJ:-Mo_R73A0Gz-jgNSlnJ2:brsx4tu) ([raw file](https://github.com/cockroachdb/pebble/blob/c0c9661118a879bdc2f911b547230f6e16b3c333/internal/testkeys/testkeys.go#L226)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

nit: could this be `uint64` to squeeze as much out of the range as possible?

Also - does it make sense if `l > n`? In that case, do we need to cap `l` to be `min(l, n)`? Or is it a programmer error if `l > n`, in which case `panic`.
</blockquote></details>

Yeah, it does still make sense if `l > n`, because `l` controls the maximum number of slots and `n` controls the number of characters that can fill a slot.

**Pull request merged**
