### PR TITLE
*: fix misspellings

### PR DESCRIPTION
**Pull request by jbowens**

### CODE REVIEW

**Comment by jbowens** [comment]
Might be worth setting up golangci-lint in CI.

**Review by bananabrick — APPROVED** [review]
> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1291)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jbowens)

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1291#-:-Mkhlt335oFwTRk_YY6L:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jbowens)

**Comment by jbowens** [comment]
TFTRs!

**Pull request merged**
