### PR TITLE
internal/manifest: add size to debug string

### PR DESCRIPTION
**Pull request by dt**

### CODE REVIEW

**Review by itsbilal — APPROVED** [review]
LGTM

**Review by RaduBerinde — APPROVED** [review]
The brackets are unnecessary/confusing. Should be easy to make Parse work without them (just move the Expects inside the cases).

**Comment by dt** [comment]
> The brackets are unnecessary/confusing

I think there's a future where we put backing size as well as size here. I'd prefer to keep them?

**Review by RaduBerinde — APPROVED** [review]
Thanks! :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3401#-:-NstuLtU9jhxk8d5uCKD:b6duv8n)* status: 0 of 8 files reviewed, all discussions resolved

**Pull request merged**
